### ISSUE TITLE
Display current group name somewhere

### ISSUE THREAD

**Issue by jurgenhaas** [Drive4ik/simple-tab-groups#10]
The old QUicksaver extension displayed the name of the current group in the top right corner of the FF window which was very helpful. Something similar in simple tab groups would be much appreciated.

**Comment by Drive4ik** [comment]
@jurgenhaas Hi, I planed this functional in future versions, now I'm focused on fixing bugs and improve stability.
Thanks for proposal!

**Comment by Drive4ik** [comment]
Added in v1.8

**Comment by jurgenhaas** [comment]
Wow, that was quick. Just updated to 1.8 and I now see the colored rectangle on top of the icon, but the group name is only visible when I hover the mouse over it. Is that the intended solution or is there another option that I'm missing?

**Comment by Drive4ik** [comment]
@jurgenhaas Sory, but Firefox WebExtensions API doesn't support any "words" in browser action (top icon)
only icons supported.

**Comment by jurgenhaas** [comment]
The previous tab manager I used printed the group name in the pane above:

![2017-11-29 13 59 58 screen](https://user-images.githubusercontent.com/1475675/33376378-c346d086-d50d-11e7-8a29-928b623e18c4.jpg)

Is that possible at all?

**Comment by Drive4ik** [comment]
I know, I also used the old add-on in this place :) but unfortunately this can not be done right now

**Comment by grahamperrin** [comment]
> … is there another option that I'm missing?

@jurgenhaas FYI, if you're not already aware: #566

**Comment by jurgenhaas** [comment]
This is awesome, thanks @grahamperrin for pointing me that direction.
