### ISSUE TITLE
Add option to not load ANY tabs during group switch

### ISSUE THREAD

**Issue by nitinmehra20** [Drive4ik/simple-tab-groups#100]
This is quite irksome because I have tabs opened that don't need to be updated but somehow it still reloads all of them. Let the user decide which tabs to reload

**Comment by Termuellinator** [comment]
yeah that would be awesome - i just found this addon and was happy to finally see a seemingly good tab groub in webEx, but the fact that all tabs are loaded makes it useless for my usecase :(

**Comment by Drive4ik** [comment]
This question has already been raised many times. This is restriction of new FF.
Please read #2
