### ISSUE TITLE
Loading pinned tabs on start

### ISSUE THREAD

**Issue by mmmaiden** [Drive4ik/simple-tab-groups#1001]
Pinned tabs are not restored / loaded when starting Firefox.
To have pinned tabs restored you need to load a backup, that's annoying.  It would be very comfortable to have the pinned tabs available after starting firefox but they are not loaded at all, even not in the "manage tabs" site.

**Comment by nekohayo** [comment]
It works for me here, just like regular tabs 🤷

**Comment by Drive4ik** [comment]
![Без имени](https://user-images.githubusercontent.com/7843031/223188712-d82bd3ef-7dca-4298-8a51-c8d307c6a7c3.gif)
