### ISSUE TITLE
Can't open the URL into "CONTAINER NAME" container

### ISSUE THREAD

**Issue by katastrophe92** [Drive4ik/simple-tab-groups#1006]
Hello Git. First I want to thank the developer for this amazing extension. I get this popup almost every time when I select text then right click on the selected text to search. Then a new tab opens with this popup. Anybody knows a fix for it? Thanks
![18 01 2023  21-48-13](https://user-images.githubusercontent.com/103950507/213405890-111a33e6-7dc9-4259-94b8-63c78528579c.png)
![18 01 2023  20-47-29](https://user-images.githubusercontent.com/103950507/213405903-1aa91927-c642-455d-a27b-d2a7d227fc9a.png)

**Comment by sbirl** [comment]
What you are seeing is based off of [Mozilla's Mutli-Container extension](https://github.com/mozilla/multi-account-containers).  At some point you told FireFox to "Always Open This Site In ..." and chose a specific container.

There are multiple solutions to your problem, but it depends on what it is you're looking to achieve.  One fix would be:
- Click "Exclude Default container for group YouTube"
- Click "Open in Youtube container"
