### ISSUE TITLE
Keyboard shortcut for switching between groups

### ISSUE THREAD

**Issue by jonyeasyrider** [Drive4ik/simple-tab-groups#1007]
Hello, 

    if there isn't, please add function to be able to switch between tab groups with keyboard shortcut.

Even with the mouse I need to click on the puzzle icon, then on "Simple Tab Groups" then on the desired group. :(

Thank you!

**Comment by achernyakevich-sc** [comment]
@jonyeasyrider 

First advise from my side - try pressing `F8` and entering something about tab you search for. :)

Second, you are completely wrong about keyboard shortcuts. There are predefined shortcuts and as welll STG provides great possibility to introduce your own shortcuts to access groups you need. It could be configured by passing the following way:

* open Firefox Add-Ons configuration (Ctrl+Shift+A).
* Open options of Simple Tab Groups Add-On:
![image](https://user-images.githubusercontent.com/24388336/213860985-56fdec9d-1dd6-4752-82e1-78baabe9d14d.png)
* Select Hotkeys tab and configure shortcuts you need:
![image](https://user-images.githubusercontent.com/24388336/213861031-4c62dcb9-9fc1-4195-b3f1-d5bda54c0273.png)

I hope it will help you. So this issue could be treated as resolved so I would ask you to close it to show it other user. :)
