### ISSUE TITLE
Is this is a bug, feature, bad settings or me 😂?

### ISSUE THREAD

**Issue by katastrophe92** [Drive4ik/simple-tab-groups#1009]
**Describe the bug**
- I do not know if it is a bug. But often when I select and after search that I get this Pop-up 

**To Reproduce**
1. Select Text
2. Click on search with desired search engine
4. See error Can't open the URL in container

**Expected behavior**
- Just to open in a New Tab

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Win 10 Pro 19045.2486
 - Firefox version: LibreWolf 109.0-1 winget version
 - Simple Tab Groups version: 4.7.2.1

**Additional context**
![18 01 2023  21-48-13](https://user-images.githubusercontent.com/103950507/213933882-a29df053-e148-42f3-aa44-5f53209bbcc7.png)
![18 01 2023  20-47-29](https://user-images.githubusercontent.com/103950507/213933888-109c1114-e62a-403b-ac7a-6ece896aee51.png)

**Comment by JoshCode94** [comment]
This is a conflict with the other addons mentioned in the screenshots. I would dig around the settings for each of the addons (that isn't simple tab groups) and see if you can find something to do with containers and what the options are.
