### ISSUE TITLE
Import Quicksaver tab groups randomly merges groups together and disappears tabs.

### ISSUE THREAD

**Issue by spiralsam** [Drive4ik/simple-tab-groups#101]
Two issues when importing a backup group, tested importing an exported backup, 29 groups 1120 tabs total. The backup was created with multiple Firefox windows with multiple tabs groups for each when doing the backup in Quicksaver:

1. Missing tabs. Some groups had missing tabs. I took a look at the JSON file. For some reason these tabs are listed in their own "windows" node that itself is listed under a root node "lastSessionState" whereas the other tabs are listed under their own root "windows":

windows (_correctly imported tabs were under this root_)
....0
........extData
............tabview-groups (...)
lastSessionState (_disappeared tabs were under this root_)
....windows
........0
............extData
................tabview-groups (...)

These missing tabs are definitely part of the tab groups and are listed in Quicksaver's import preview list of tabs.

2. Tabs from different groups are merged together into random groups. This happened it seems with tab groups from the at least one of the Firefox windows. It contained 7 tab groups. Upon importing into simple-tab-groups, 4 of those tab groups were imported just fine, but the other 3 were disappeared. The tabs that made up those 3 tab groups were then themselves merged into some of the other imported tab groups. In the JSON, the format is like

window
....0
....1
....2

So for example tab groups from Window 0 imported fine, but 1 and 2 got randomly placed into groups from 0. I am able to get around this specific bug by backing up from Quicksaver one window at a time to their own separate JSON files (with the aid of Session Manager Firefox addon), then importing them sequentially into simple-tab-groups.

Simple Tab Groups v2.4.7

**Comment by spiralsam** [comment]
I've discovered that bug (1), disappearing tabs, is apparently related to Session data being added to exported Quicksaver JSON backup files. As of now, In order to import into simple-tab-groups without losing random tabs, you must exclude Session data when backing up group tabs data from the Quicksaver addon.

**Comment by spiralsam** [comment]
Correction: for sake of completeness I've discovered more tabs that are disappeared while importing. Tabs:
1. that point to file:///[...] URLs.
2. that point to firefox special urls ("about:options", etc)
3. whose URLs are data URLs that write the HTML you're looking at (example: data:text/html,;&lt;html&gt;&lt;/html&gt;)
4. whose URLs are "view-source:" URLs

**Comment by Tyrewt** [comment]
#62 
#70 
Official bug report: [https://bugzilla.mozilla.org/show_bug.cgi?id=1435077](https://bugzilla.mozilla.org/show_bug.cgi?id=1435077)
