### ISSUE TITLE
Font color for unloaded (discarded) tabs is difficult to read

### ISSUE THREAD

**Issue by blueacorn** [Drive4ik/simple-tab-groups#1015]
**Describe the bug**
When a tab is not loaded, STG displays the tab name in light gray - this is very difficult to read with default theme (white background)

**To Reproduce**
1. Go to STG in Side bar
2. Click on a group with some tabs loaded, others unloaded
3. Observe the unloaded tabs the tab name is hard to read.  
4. With lots of unloaded tabs, its very difficult to scan thru the tab names

**Expected behavior**
Tab name Unloaded tabs should be readable (black/blue text)
- Perhaps add option for color choice 

**Screenshots**
![image](https://user-images.githubusercontent.com/2761886/219565050-f4333661-f240-47fe-a417-18d467c37d83.png)

**Desktop (please complete the following information):**
 - OS and version: Mac 13.2
 - Firefox version: 102.7 esr
 - Simple Tab Groups version: 4.7.2.1

**Additional context**

**Comment by Drive4ik** [comment]
changed the color a little bit, it will be better to see
