### ISSUE TITLE
Unable to access groups, always see two flags rolling (like if it were "thinking")

### ISSUE THREAD

**Issue by GAsinPrieto** [Drive4ik/simple-tab-groups#1017]
**Bug description**
I am unable to access my groups.

**To Reproduce**
Click on the groups icon on the browser bar.

**Expected behavior**
See the groups. 

**Screenshots**
![imagen](https://user-images.githubusercontent.com/10688602/226530283-645d2bdd-ccfb-4099-bfb6-4cd9a3dd3db6.png)

**Desktop (please complete the following information):**
 - OS and version: Windows 10 Home 64b
 - Firefox version: 111.0
 - Simple Tab Groups version: 4.8.4

**Additional context**
I have detected it today, so probably occuring since yesterday.

**Comment by Drive4ik** [comment]
Did you try to restart your browser? 
What exactly caused this behavior of the addon?
What version of the addon?

**Comment by jose-victor** [comment]
I'm also having this issue.

Firefox version 102.10.0esr (64-bits)
STG 5.0.1

I don't know if this happened after a Firefox or STG update, I was a couple of weeks AFK. Already tried restarting Firefox and uninstalling STG, 

Now I can't:
- open tab groups
- open tabs on a new temporary container
- change the configurations of the group
- import my backup from STG

![image](https://user-images.githubusercontent.com/17819730/233187765-a7171421-3c9d-4f3d-8c6d-952a68bb41cf.png)

**Comment by GAsinPrieto** [comment]
> Did you try to restart your browser? 
> What exactly caused this behavior of the addon?
> What version of the addon?

Sorry for my late reply, I restarted the full profile in the browser, but continued having the issue. It pushed me to clean my session and come back to use bookmarks rather than having lots of webpages opened. Given the sudden appearance of the issue, it may be due to a change in the version of Firefox leading to inconsistencies between both pieces of software... Another cause that came to my mind, maybe totally wrong, is the language of the browser, it was Spanish in my very own case...

Hope this helps somehow

**Comment by Drive4ik** [comment]
I think the error has already been corrected. Open the ticket if it's wrong
