### ISSUE TITLE
request do not discard per domain or url | select language 

### ISSUE THREAD

**Issue by DandyClubs** [Drive4ik/simple-tab-groups#1018]
**Is your feature request related to a problem? Please describe.**
hide group auto discard option
current support only sound tab
i want to some url or domain 

and

i use korean window. 

discard = 삭제
delete = 삭제

korean Translations
discard = delete 

i want select english 

**Describe the solution you'd like**
discard option
add regex some url or domain 

and

UI select language

**Comment by Drive4ik** [comment]
> i want
