### ISSUE TITLE
Feature Request: Add option to not delete tabs from group when the window is closed, and without archinving the group.

### ISSUE THREAD

**Issue by YousufSSyed** [Drive4ik/simple-tab-groups#1019]
Sometimes I'd like to close a window in a group but come back to them later, but currently, the only way to do so is to archive the group first then close the window. What I'd like is to be able to close windows without the tabs getting removed from the group, and I could just load the group later. There should be an option for this in STG settings called "Don't delete tabs from group when window is closed."

**Comment by Drive4ik** [comment]
At the moment, after closing a window, the addon restores the closed tabs (or rather, creates them anew) in another window, if there is one. If not, it waits for the window to open and restores it there. Can you give more information? What system, what version of the addon. It's best to record a small GIF/video for better understanding.

**Comment by YousufSSyed** [comment]
I didn't notice this before submitting the issue, but I have recently now.
