### ISSUE TITLE
Feature Request: For the nortes extension allow for making notes for individual tabs. 

### ISSUE THREAD

**Issue by YousufSSyed** [Drive4ik/simple-tab-groups#1020]
Sometimes I have lots of tabs (maybe 100s) for doing deep research topics, so I'd like to keep track of them. Perhaps in the notes popup, you could have a sidebar to the left with all of the tabs in the group and you select a tab, and on the right a note for the select tab. In the sidebar window, thee list of tabs could be a section on the top half, and a note on the bottom half.

Does that make sense or should I make a mockup?

**Comment by Drive4ik** [comment]
This functionality should not be included in the STG addon. That's why they invented different addons that do not depend on each other. You need one of these:
https://addons.mozilla.org/firefox/search/?q=notes

**Comment by YousufSSyed** [comment]
@Drive4ik So this isn't something you would consider for the group notes addon?
https://addons.mozilla.org/en-US/firefox/addon/stg-plugin-group-notes/
