### ISSUE TITLE
STG contantly crashing with "Error(s) encountered during statement execution: database disk image is malformed" in the debug log

### ISSUE THREAD

**Issue by Nocifer** [Drive4ik/simple-tab-groups#1021]
**Describe the bug**
Since a few days ago, STG has been constantly crashing (and I do mean constantly; like every 5-10 minutes or so) and slowing down the whole browser. After reading the debug log, I found that:

1) There's a bunch of errors like this one:
```
        {
            "time": "2023-04-02T09:22:43.345Z",
            "fileName": "undefined",
            "lineNumber": 0,
            "columnNumber": 1,
            "message": "Error(s) encountered during statement execution: database disk image is malformed",
            "stack": []
        }
```
2) There's a bunch of stored URLs which are malformed like this:
```
                {
                    "id": 534,
                    "url": "moz-extension://6f94796e-0060-491e-9441-113bbfd1e078/lazyloading.html#https://www.google.com",
                    "hidden": true,
                    "cookieStoreId": "firefox-default"
                },
```
Searching through my tab groups, I found 2 of them that contain tabs with such malformed URLs.

**To Reproduce**
I have no idea what caused this, so I can't reproduce it.

**Expected behavior**
URLs should not be malformed and STG should not be crashing every 5 minutes.

**Desktop (please complete the following information):**
 - OS and version: Arch Linux
 - Firefox version: 111.0.1
 - Simple Tab Groups version: 4.8.1

**Additional context**
The one thing I'd like to ask is, where does STG store its session data on disk and is it at all possible to manually edit the data (e.g. if they reside in a SQLite database) in order to restore the malformed tabs into their proper forms? I could always do it by hand, but we're talking about some 500 tabs :/

Also, I've already tried to delete STG's data and import back my tab groups and the issue remains. These malformed URLs are part of the backup though, so maybe they're to blame for causing this.

**EDIT:** As I finished writing this I realized I can instead edit the backup, fix the URLs and then import them back. I did that and it worked as expected, so I'll report back if and when the crash happens again.
**EDIT:** Nope, the problem still persists even after fixing the malformed URLs. But it happens much less frequently now, once every 30-60 minutes maybe.
**EDIT:** Turns out the cause for the remaining crashes was the backup to bookmarks feature. I had it set to 60 minutes interval and that's why I observed that 60 minute window between crashes. Turning it off results in no crashes, turning it back on results in an immediate crash with the same "database disk image is malformed" error; and of course, the backup to bookmarks feature doesn't work at all.
**EDIT:** Also, I forgot to mention that the extension is messing with Firefox's ability to create new bookmarks - neither clicking the star button in the URL box nor pressing Ctrl+D will allow me to bookmark a page. Launching with the add-on disabled, even just in a private window, makes bookmarks work again as expected.

**Comment by Drive4ik** [comment]
This is not an STG problem. It does not create URLs of this kind. You have another addon to unload tabs from memory. That addon might have a name like "Discard tabs".

**Comment by Drive4ik** [comment]
By the way, on the `about:debugging#/runtime/this-firefox` page you can find and see what kind of addon it is. by UUID:
moz-extension://**6f94796e-0060-491e-9441-113bbfd1e078**/lazyloading.html#

**Comment by Drive4ik** [comment]
Just when you find the addon - don't delete it!!!! All those tabs will become inoperable. You need to load them all, so they are in memory and have a normal URL. and only then remove/disable the addon you found.

Or
If you haven't already fixed all your tabs (500+) you mentioned, I can give you another addon I made a long time ago because, for some reason, I've been approached by people thinking it was STG's fault. It takes out and replaces the correct URL in the tab, from this one:
`moz-extension://6f94796e-0060-491e-9441-113bbfd1e078/lazyloading.html#https://www.google.com`
or
`moz-extension://6f94796e-0060-491e-9441-113bbfd1e078/lazyloading.html?url=https://www.google.com`
