### ISSUE TITLE
Extension not clickable

### ISSUE THREAD

**Issue by verisorry** [Drive4ik/simple-tab-groups#1022]
**Describe the bug**
The button is not clickable and does not change on mouse hover–I can't access my tab groups or the menu because of it.

**To Reproduce**
1. Place extension on toolbar next to search bar (not sure if relevant)
2. Click on extension
3. See error

**Expected behavior**
The menu should show and allow me to navigate between my tab groups. Additionally, the shading of the surrounding box should change on mouse hover but it does not.

**Screenshots**
https://user-images.githubusercontent.com/59988812/229862644-b441f64c-c97d-4872-bd65-d4cff6378434.mov

**Desktop (please complete the following information):**
 - OS and version: MacOS Ventura 13.2.1, Apple M1 2020
 - Firefox version: 111.0.1 (64-bit)
 - Simple Tab Groups version: v4.8.1

**Comment by Drive4ik** [comment]
Hi, the problem should be fixed by now.

**Comment by vauhochzett** [comment]
Thank you! :pray:
