### ISSUE TITLE
Might be a good idea to warn new users to enable "Open previous windows and tabs" if not enabled

### ISSUE THREAD

**Issue by Ralithune** [Drive4ik/simple-tab-groups#1024]
Hey there - just got done troubleshooting why STG wasn't saving my tabs through reboots / closes on a brand new MacOS installation and realized it's because the global firefox preference "Open previous windows and tabs" was not set.

It might be a good idea to throw a dialogue box on install that checks if this preference is set and then tells people to set it if they want their tabs in groups to persist across reboots / sessions.  I feel like I reasonably assumed that would just happen with the addon, but maybe it's not that reasonable.

Thought I'd post for future users as well.

**Comment by Drive4ik** [comment]
Such a window already exists. "Welcome" is called. Maybe you closed it automatically without reading it? Reinstall the addon with a browser restart, and you will see it.
- Uninstall the addon.
- Restart your browser
- Install addon

**Comment by Ralithune** [comment]
Ahh, I see - that's great.  I was installing dozens of softwares necessary to get my work laptop back up and running, and it seems like I got bit by this Gotcha for not reading the welcome message of one of them.  Completely my fault.

You may want to consider making it a separate warning, since persisting the painstakingly set up groups across restarts of the browser is an expectation I'm sure many/most users have out of the box. I'm not sure why a person would take the time to open tabs in all the various groups they create, only to not care if they are saved or not when they close the browser.

Thanks for making the addon at all! 🙂

**Comment by Drive4ik** [comment]
Unfortunately, the addon has no way of knowing the status of this setting at all. Perhaps in the future Firefox will add this to their [api](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings), but I think unlikely. This is a very serious change in browser behavior.
