### ISSUE TITLE
When changing groups, sound get muted.

### ISSUE THREAD

**Issue by kkensuke** [Drive4ik/simple-tab-groups#1025]
**Describe the bug**
When changing groups from a tab group with music or videos to another tab group, the sound get muted.
(In settings page, `Discard tabs after hide (this willsave the RAM)` is disabled.)

**To Reproduce**
1. Open YouTube or YouTube Music
2. Play a video or music
3. Change groups

**Expected behavior**
 Sound doesn't get muted

**Desktop (please complete the following information):**
 - OS and version: Mac Version 13.2.1
 - Firefox version: 112.0
 - Simple Tab Groups version: 5.0.1

**Comment by Drive4ik** [comment]
I can't repeat the problem. A log file would be very helpful. Logging can be enabled on the settings page.

**Comment by kkensuke** [comment]
This is the log file.

Thanks.

￼

**Comment by Drive4ik** [comment]
@kkensuke You need to send this file to my email, because responding to the email, which is a notification from GitHub, apparently, the log file was not added.

**Comment by kkensuke** [comment]
I recently realized that `Preferences > Default group > Mute tabs when group close and restore when open` was enabled. This was the cause of the problem. 😂
