### ISSUE TITLE
The object could not be cloned.

### ISSUE THREAD

**Issue by khangly** [Drive4ik/simple-tab-groups#1026]
Hello
I'm using the latest version of this addon (5.0.1) and Firefox version 102.9.0. I think the addon just updated today, and when I tried to remove a tab, it crashed and I got this error in the log
```json
{
            "console.error": [
                "Options",
                "Catch error on: The object could not be cloned.",
                {
                    "time": "2023-04-12T19:24:22.170Z",
                    "message": "The object could not be cloned.",
                    "fileName": "undefined",
                    "lineNumber": 15,
                    "columnNumber": 0,
                    "stack": [
                        "importAddonSettings@options/options.js:4939:84"
                    ]
                }
            ],
            "indentIndex": 0,
            "time": 1681327462171,
            "stack": [
                "errorEventHandler@js/logger.js:348:16",
                "globalHandleError@js/vue.runtime.esm.js:3031:40",
                "handleError@js/vue.runtime.esm.js:3008:26",
                "invokeWithErrorHandling/<@js/vue.runtime.esm.js:3019:45"
            ]
        }
```
Also got similar error when trying to restore from backup.

**Comment by Drive4ik** [comment]
Yes, I know about this bug. Already fixed it here: c96dfae90284dd6d230cf5136bcbf7e8d8fe8ca4
That's because you're using the ESR version of Firefox.

Made release version 5.0.2, but Firefox reviewers check every 3-4 business days... Maybe there will be a release next week.

**Comment by khangly** [comment]
Thank you, I just pulled the latest change and it worked! Feel free to close this.

**Comment by Drive4ik** [comment]
For now, do not close, the ticket. Let other users see it and not create clones.
I will close it as soon as the new version comes out.

**Comment by ParoTheParrot** [comment]
similar problem here while restore process (Version 5.0.1 , FF 102.9.0esr 64-Bit): I couldn't import my restored tab groups!
Any idea for a quick fix, @Drive4ik ?

**Comment by Drive4ik** [comment]
@ParoTheParrot 
Unfortunately, no. You can only install Mozilla Firefox-signed add-ons. Or manually build an addon, and load it as a temporary one.

**Comment by ParoTheParrot** [comment]
Now version5.1 is published: https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/ ✅
