### ISSUE TITLE
Where can I find the old version? (5.0.1 messed up for me)

### ISSUE THREAD

**Issue by t984447** [Drive4ik/simple-tab-groups#1027]
**Issue at hand**
After the update to 5.0.1 my STG refused to open any other groups after un-archiving them.
Every action I try todo now is broken and I constantly get the STG Debug pop-up window.

After doing a Clear everything and trying to use ANY of the backups I still
get the same issue.

Now I cannot even use the web browser normally since it refuses to return tabs.
Not only are all my backups useless but now the tabs I could before access are also unreachable.
Since I am using waterfox I do not expect any extra support so Id rather revert to an older version to export my tabs 
and find a new way to manage my tabs.

My question is where can I find the addon version prior to 5.0.1?

I've tried to;
- uninstall the addon and reboot the web-browser and then reinstall
- Clear the settings

**Desktop (please complete the following information):**
 - Windows 11 x64
 - **Waterfox** G5.1.4 (64-bit)
 - Simple Tab Groups version: 5.0.1

**Comment by Klo77a** [comment]
> NVM, found addon page where it had all the version.
> 
> https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/versions/

Hi, were you successful with revert to 4.8.1 version? I'd tried the same, but when I'm trying to restore my tabs backup, it says me repeatedly "Please update to the newest version" and restoring is failed. I'm using FF112, Fedora 37 (Cinnamon environment / Xorg based).

Actually, 5.0.1 version works - but I'm observing big issue with rendering during switch between groups. I have just two groups (let's say 150 tabs in each one) - when I got switch in previous version (4.8.1 and less), switching was fast - or normal, let's say 2-3 seconds. In the new 5.x version, the STG extension is rendering, scrolling and "recounting" all the tabs, so each switch between the groups takes at least 20 second, maybe more. You can live with this, but it's really not so funny.
