### ISSUE TITLE
Group names are sometimes visibly prefixed by code that should be hidden

### ISSUE THREAD

**Issue by grahamperrin** [Drive4ik/simple-tab-groups#1028]
**Describe the bug**

In the screenshot below, for example: 

* a loaded group named `FreeBSD` is prefixed by `@563:#111`

**To Reproduce**

Maybe difficult to provide reproducible steps, sorry. 

Generally: this bug seems more likely to bite if there are many tabs (in recent weeks, I usually have more than six hundred) and if Firefox is launched whilst the computer is unusually busy with other things. 

**Screenshots**

![2023-04-15 13-55 @3:#7 name of group](https://user-images.githubusercontent.com/192271/232228500-8ebcd019-d496-4873-81cf-e38bb6c9af19.png)

**Desktop**

Simple Tab Groups 5.0.1

```text
% pkg iinfo firefox
firefox-112.0_1,2
% uname -aKU
FreeBSD mowa219-gjp4-8570p-freebsd 14.0-CURRENT FreeBSD 14.0-CURRENT #38 main-n262032-5e2e3615d91f: Fri Apr  7 18:54:28 BST 2023     grahamperrin@mowa219-gjp4-8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG amd64 1400085 1400085
% 
```

**Additional context**

**Comment by moll** [comment]
Just experienced the same thing with v5.0.1. They also show up in the group switcher (the popover with the search on top and "Manage Groups" at the end).

**Comment by V346Cen** [comment]
Same issue here. Visible since updating to the most recent Firefox version.

Ubuntu 18.04.6 LTS
Mozilla Firefox 112.0
STG 5.0.1

I've had STG 5.0.1 sine April 12th and I haven't seen the issue, so it looks like today's Firefox update triggered it for me.

**Comment by grahamperrin** [comment]
I can't associate the symptoms with any particular version of the extension, or Firefox. 

First observed by me … I can't say exactly how long ago (sorry) but it was almost certainly before the early April release of 5.0.1.

**Comment by V346Cen** [comment]
> I can't associate the symptoms with any particular version of the extension, or Firefox.

Looks like you're right, now I see it's kind of random for me. It goes away after restart of Firefox, but not always.

**Comment by Drive4ik** [comment]
That's right, you have to turn off the debug. I added a little note when it's on.
