### ISSUE TITLE
sessionStorage is lost upon switching groups

### ISSUE THREAD

**Issue by Draghmar** [Drive4ik/simple-tab-groups#103]
Hi
I love this addon so far because it really looks like Tab Groups replacement I was looking for!
I found a couple of issues though. Here's one of them:
I often use sessionStorage to keep some settings for the current session. I've noticed that switching between groups remove sessionStorage info completely. Like it wasn't set before. I didn't check localStorage.
This was tested on FF60 portable nightly.

**Comment by Drive4ik** [comment]
Hi! This is due to the re-opening of the tabs, i can't fix this bug in these version, sorry.
You can try experimental addon
https://addons.mozilla.org/firefox/addon/experimental-simple-tab-groups/
