### ISSUE TITLE
Since 5.01 restoration looks broken

### ISSUE THREAD

**Issue by camlafit** [Drive4ik/simple-tab-groups#1030]
Hello

Since 5.0.1 version , I've some trouble with backup/restoration feature. 
All day backups are done and data looks generated (size file look ok) but to restore service I must downgrade to 4.8.1 and search last backup file generated from this version.

I've tried to enable debug mode, but I've not see anything. I'm not sure how to propose a reproductible process.

Thanks

**Comment by Drive4ik** [comment]
I have already fixed all these problems. Expect a new release. It will be out this week and is currently being review.

**Comment by camlafit** [comment]
Hello

@t984447 yes your trouble looks similar to mine. I use firefox 102.10.0esr (64 bits) on debian 11.
@Drive4ik ok nice to notice :) 

I'll wait with 4.8.1 and stop auto update addons in meantime.

Have a nice day
