### ISSUE TITLE
Mute tab from STG popup

### ISSUE THREAD

**Issue by mare1203** [Drive4ik/simple-tab-groups#1032]
When I mute the tab from STG popup it takes a few seconds before it actually mute.

**Comment by mare1203** [comment]
In fact, the muting happens immediately, but then it takes a few seconds for the icon to show that the tab is muted so that you can unmute it again.

**Comment by Drive4ik** [comment]
I know. This behavior is based on messages from the browser, which is what, I don't know why, makes this delay. This does not happen when the sound is turned on.
