### ISSUE TITLE
Remove Tab Session Manager as conflicted addon

### ISSUE THREAD

**Issue by Speravir** [Drive4ik/simple-tab-groups#1034]
In recent version 5.1 of STG addon you added Tab Session Manager as conflicted addon, in your words:

> add Tab-Session-Manager@sienori to CONFLICTED_EXTENSIONS

Please, revert this change or provide some possibility to overrule this. I use both addons starting with Firefox 57 when the switch to web extensions did happen and nether noticed any conflict of both.

Instead, the nag window on every Firefox start is now very annoying (which feels like a bug for me).

**Comment by TheDelta** [comment]
I would love to have an ignore option as well.
Using both plugins for years now without major issues (I had some duplication and whatnot issues, but I'm fine with those and know the workarounds and keep backups of both plugins)

Side Note: the Readme must be updated to mention Tab Session Manager.

**Comment by 4fosaefp** [comment]
Same here. I was very confused when seeing the conflict window show up. I've been using both STG and Tab Session Manager for a while without any issue. Why is it listed as conflict now?

**Comment by davidhs0** [comment]
I have same problem.

If this has not solution... Can you add support for save/restore sessions in STG?

**Comment by sentix001** [comment]
same here

**Comment by Drive4ik** [comment]
Added option to ignore. But it will be reset when you reinstall/enable the conflicting addon. Also ignore will be reset when restoring backup with data clearing.
In general, constantly reminding that this ignore is very, very not desirable.

**Comment by sentix001** [comment]
i updated the addons but cant see the setting. where is it under general?

**Comment by Drive4ik** [comment]
@sentix001 I haven't even done a release yet. It will be in addon 5.2 (next release)

**Comment by IanQS** [comment]
I seem to still be unable to find the option to toggle this even though I'm on `5.2`. Am I just looking in the wrong place?

**Comment by sentix001** [comment]
WHEN YOU OPEN THE BROWSER AND THE CONFLICT NOTE APPEARS THERE IS A SMALL
ICON NOW TO IGNORE THE CONFLICT
