### ISSUE TITLE
A string of characters appear in tab/group list views

### ISSUE THREAD

**Issue by mikkishull** [Drive4ik/simple-tab-groups#1039]
When I click on the Tab/Group icon, I see a prefix string of characters before each tab/group name

Please see attached screen shot.

**Desktop (please complete the following information):**
 - Window version: Windows 10 Home, Version 22H2, OS build 1904.2846
 - Firefox version: 112.0.1 (64-bit)
 - Simple Tab Groups version: [5.1]
 
 - **Additional context**
This started happening about 2 weeks ago ~ Apr 12 2023
 
 - Screenshot: 

(![TabGroup List Problem](https://user-images.githubusercontent.com/79669641/234448564-b93be545-1787-4057-af1a-86fa824f41e0.png))

**Comment by Drive4ik** [comment]
hi, disable debug mode in addon settings

**Comment by mikkishull** [comment]
When I checked, debug mode was already disabled (see image below)
The character string disappeared today when I rebooted. 
I will keep vigilant to see if this problem persists, or I can discern a pattern. 

![image](https://user-images.githubusercontent.com/79669641/234710142-71729642-2658-4e0c-acff-6f56bfa01b22.png)
