### ISSUE TITLE
DevTools are closed upon switching groups

### ISSUE THREAD

**Issue by Draghmar** [Drive4ik/simple-tab-groups#104]
Hi
I love this addon so far because it really looks like Tab Groups replacement I was looking for!
I found a couple of issues though. Here's one of them:
I often work on many projects at the same time and grouping them help maintain some degree of order. Workflow like this enforce using at least few DevTool windows for different sites/projects. But when switching groups window that was opened in current group is closed. So whenever I have need to change group for whatever reason I have to reopen DevTools.
This is not a deal breaker but it is annoying.
BTW I'm working with DevTools as a separate window and this was tested on FF60 portable nightly.

**Comment by Drive4ik** [comment]
Hi! In the current version, this is impossible.
You can try experimental addon
https://addons.mozilla.org/firefox/addon/experimental-simple-tab-groups/
