### ISSUE TITLE
STG error, automatic Debug Mode enabling, and hide tabs option popup when a new container tab is opened

### ISSUE THREAD

**Issue by gaveen** [Drive4ik/simple-tab-groups#1041]
**Describe the bug**
This issue/annoyance started several weeks  ago and persisted until now, where when a new tab is opened in a Firefox container by clicking the "+" button ("Open a new tab button") on the tab bar (or its "Ctrl+t" shortcut). An error message notification _(screenshot included)_ is shown and the Debug mode is automatically enabled. When it is disabled manually,  a Firefox popup _(screenshot included)_ appears soon asking if STG should be allowed to keep tabs hidden.

**To Reproduce**
1. Have a tab open any webpage and in focus in a Firefox container
3. Click on '+' button (Open a new tab button) **_or_** use Ctrl+t shortcut

By this point the error message will be shown and the Debug Mode will be enabled automatically.

4. Click the STG error notification _(screenshop below)_, which takes you to 'Debug Mode' page.
5. Click on the "Disable DEBUG" button
6. Save the debug log file and/or close the save the debug log file window
7. Wait a few seconds for Firefox to show the popup message _(screenshop below)_

**Expected behavior**
1. When the "+" button ("Open a new tab button") on the tab bar (or its "Ctrl+t" shortcut) is invoked, a new tab is created in the same container as the current tab in focus, and
2. STG does not enable debug mode

**Screenshots**
Below are the screenshots referred to above.

![error message notification](https://user-images.githubusercontent.com/406/234804250-5e315413-b553-41bc-92e2-fb3bac54580b.png)
_Firefox notification showing the STG error, which if clicked opens the Debug Mode page_

![Firefox STG hide tabs permission pop-up](https://user-images.githubusercontent.com/406/234804294-2e91b5bb-ca46-4504-bb20-ae72bd5d162b.png)
_Firefox pop-up message with options to let STG keep hiding the tabs or disable STG_

**Desktop (please complete the following information):**
 - OS and version: Fedora Workstation 38 _(current latest with updates)_, Fedora Workstation 37 _(prior to OS upgrade)_
 - Firefox version: 112.0.1 (Mozilla Firefox for Fedora - 1.0) _(current latest)_
 - Simple Tab Groups version: 5.1 _(current latest)_

**Additional context**
This seems to happen only when the current focus tab is in a Firefox container.
- The default behaviour with Firefox containers is the new tab will be created in the same container of the current focus tab.
- Therefore, I checked if this can be replicated when a non-container tab is created, and that does not seem to trigger this.
- Further, if the "+" button is held (instead of clicking) to bring up the container list and then the new tab is created by picking the container from that list, this does not seem to trigger.

**Other attachments**
[STG-debug-logs.json](https://github.com/Drive4ik/simple-tab-groups/files/11341642/STG-debug.log)
_A recent saved debug log file from post-issue._

**Comment by Drive4ik** [comment]
Opening a tab with the same container by pressing "+" or Ctrl+T is not done by Firefox, but by the addon 
https://addons.mozilla.org/en-US/firefox/addon/conex/
If you disable it, the error will go away and so will this chip.
I put Conex, but I can't reproduce the error. Maybe if you give me a screenshot of the Conex settings, I can do it.

**Comment by gaveen** [comment]
Fair enough. I didn't recall Conex handled matching the current container.

I disabled 'Conex' and I wasn't able to reproduce the behaviour. Funnily enough, I haven't been able to reproduce it even after enabling Conex again. It's only been a hot minute. So I'll report back if it comes up again.

In the mean time, please find below the Conex settings I had. My primary use case for Conex is to ask which container an external link would open in.

![Conex Options](https://user-images.githubusercontent.com/406/234967228-0b875de1-f226-496b-9001-827a602795e2.png)

**Comment by Drive4ik** [comment]
Found where the bug and fixed it, will be available in the next release. Thank you!
