### ISSUE TITLE
"Export groups to main bookmark folder" not showing for me

### ISSUE THREAD

**Issue by zabarocky** [Drive4ik/simple-tab-groups#1043]
**Describe the bug**
"Export groups to main bookmark folder" not showing for me
![image](https://user-images.githubusercontent.com/85898484/234975796-99105739-a815-4c65-bf47-cecfb009c36e.png)

Automatic export to bookmark not showing for me
![image](https://user-images.githubusercontent.com/85898484/234976901-8193bb64-a7b6-4dd3-b591-dc9754619dc9.png)

**Desktop (please complete the following information):**
 - OS and version: Windows 10 Version 22H2
 - Firefox version: 112.0.2 (64-bit)
 - Simple Tab Groups version: 5.1

**Comment by Drive4ik** [comment]
These settings are now configurable for each group separately. You can also set up a default group where you specify settings for each new group.
The "main bookmark folder" is now always there. After creating a bookmark folder with groups, you can move it wherever you want.

![изображение](https://user-images.githubusercontent.com/7843031/234990640-f1679ef1-9b8d-486d-b0ca-73cd2ea93758.png)
![изображение](https://user-images.githubusercontent.com/7843031/234990708-0f8633ff-a2ff-4304-bda2-fa823be577e2.png)
