### ISSUE TITLE
Choosing Group Icon Color

### ISSUE THREAD

**Issue by BourgeoisDirk** [Drive4ik/simple-tab-groups#1046]
Is there a way to change the Color of a Group Icon ?
Because I'm not finding it ..

**Comment by vitusson** [comment]
It's in the Group setting, Icon Style, first item
![Screenshot_30-04-23--17_10_40](https://user-images.githubusercontent.com/16023080/235360785-401b8aac-9012-4472-9ee8-d156146dc5c0.png)

**Comment by BourgeoisDirk** [comment]
Oh ! Yeah ok i thought it was just another Icon.
