### ISSUE TITLE
Shortcuts don't work unless the window has at least one loaded tab of any kind.

### ISSUE THREAD

**Issue by spiralsam** [Drive4ik/simple-tab-groups#105]
If you create a new window (Ctrl+N) and the window is created a new taab that is created with a tab that simple-tab-groups doesn't recognize as a legitimate document, such as about:blank or about:newtab or about:addons for example, then none of the Global shortcuts will work. You must manually load some URL of some kind in at least one tab of that window in order to use any of the Global shortcuts (new group, delete group, etc)

**Comment by Drive4ik** [comment]
I can't fully fix it - this is limitation of FF WebExtensions API
