### ISSUE TITLE
extension unitentionaly takes keyboard shortcut ctrl+0

### ISSUE THREAD

**Issue by englishman-hu** [Drive4ik/simple-tab-groups#1050]
**Describe the bug**
Although no such keyboard shortcuts defined for the action, the extension takes the ctrl+0 key and switches to next tab group.

**To Reproduce**
1. hit Crlr + "0"

**Expected behavior**
The default firefox action of "reset zoom" performed

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10 22H2
 - Firefox version 112.0.2
 - Simple Tab Groups version: 5.2

**Comment by Drive4ik** [comment]
I can't repeat the problem. Need more information, screenshots, list of addons. And best of all, a file with logs. You can find the debug mode in the settings.
