### ISSUE TITLE
The UI becomes difficult to use after about 20+ groups because of the scrolling.

### ISSUE THREAD

**Issue by spiralsam** [Drive4ik/simple-tab-groups#106]
I assume the exact number of groups is related to browser font size perhaps, but for me after creating around 20 groups, you must scroll all the way to the bottom of the list in order to use any of the UI elements:

1. Create new group.
2. Manage groups.
3. Configurre

..and you must do so every time you open the main UI. For much better usability, the configuration UI area would simply need to be decoupled from the groups' scrollable viewport, rather than appended to the end of a single large scrollable viewport.

**Comment by Drive4ik** [comment]
Hey. I know about this problem, but I can not fix it yet, as this will cause a number of other problems, and still need to consider all the platforms - win, mac, linux
As soon as I come up with an elegant way to fix or change this panel, I'll write about it here

**Comment by Drive4ik** [comment]
But you can use keyboard shortcuts, or for example a addon for quick access to group management:
https://addons.mozilla.org/firefox/addon/stg-plugin-open-manage-groups/

**Comment by devurandom** [comment]
In case anyone else wonders: This is about the popup that opens when you click the STG icon in the firefox window's addon toolbar, which shows all the groups and also the "there are some windows not in groups, what shall we do about them" links.

**Comment by Drive4ik** [comment]
This issue is fixed on latest addon version
