### ISSUE TITLE
Add ability to set a hotkey to a specific group

### ISSUE THREAD

**Issue by tgienger** [Drive4ik/simple-tab-groups#1079]
**Is your feature request related to a problem? Please describe.**
I would like to be able to set hotkeys for specific tab groups. E.G. ctrl+1 = group1, ctrl+2 group2

**Describe the solution you'd like**
Set a hotkey to a specific tab group

**Describe alternatives you've considered**
"Next Group" and "Previous Group" is not sufficient.

**Additional context**
Nothing else to add :D

**Comment by matterharz** [comment]
This is already possible under Settings -> Hotkeys -> Load user-defined group (can be set multiple times)

The exact wording may be different as I'm using a different language.

**Comment by tgienger** [comment]
Load Custom Group would bet he English version. 

Thanks :)

**Comment by achernyakevich-sc** [comment]
@tgienger Please, close this issue as it is resolved. ;)

**Comment by tgienger** [comment]
Load Custom Group would bet he English version. 

Thanks :)
