### ISSUE TITLE
Feature request: Add much more user friendly interface to rename/delete/open groups from the UI.

### ISSUE THREAD

**Issue by spiralsam** [Drive4ik/simple-tab-groups#108]
Right now for example to rename a group, you must find the group in the list then,

1. click the tab count
2. click the cog
3. highlight the entire group name
4. enter name, and click save
5. optionally click go back to groups to rename another group.

Deleting a group is simliarly exhaustive. The addon [sync-tab-groups](https://addons.mozilla.org/en-US/firefox/addon/sync-tab-groups/) has an example nice intuitive inline interface for common actions like renaming/deleting/opening-new-window.

**Comment by Drive4ik** [comment]
Hi. You can sort/configure/delete group by context menu on group in groups list
STG 3.0 and FF 61
