### ISSUE TITLE
Preview of tabs in each group

### ISSUE THREAD

**Issue by d0peman** [Drive4ik/simple-tab-groups#11]
Would it be possible to add visual previews of each tab in the menu (even a thumbnail would be useful for quickly identifying the desired tab) within each tab group just as in the original Tab Groups addon?

**Comment by Drive4ik** [comment]
Yes, I planned added this feature in future version.

Thanks for your feedback!

**Comment by Drive4ik** [comment]
Thumbnail has been added in Manage Groups in version 2.0
Please, update addon to latest version (now is v2.1) and re-test
