### ISSUE TITLE
Feature request: Include matching group titles in search results, whose results are listed in a visually dinstinct manner than matching tabs results.

### ISSUE THREAD

**Issue by spiralsam** [Drive4ik/simple-tab-groups#110]
For example, searching in the main UI for the phrase "searchtext" will return not only a list of tabs whose title contains the phrase "searchtext", but also groups whose name contains the phrase "searchtext". The group names results could be listed at the top of the list, separated by some visual marker from the regular tab title results that are returned now.

Additionally (secondary feature request), these search-filtered group names that are returned could possibly then be presented to the user as the exact same UI that group names have now (when the UI is open and the search field is completely empty): In other words:

1. each group is presented on its own line
2. left justified is the the group name
3. right justified is that ">" symbol followed by the tab count
4. clicking the group name activates that group for the current window or new window (as per seettings)
5. clicking the tab count opens the tab listing inline of the UI. After opening, however, instead of the phrase "< Go back to groups" could be turned into "< Go back to search results" which takes the user back to the place before having clicked open that group's tab listing.

**Comment by Drive4ik** [comment]
Hi! Interesting idea. I'll add this feature in future versions.
Notice: now I working on [[EXPERIMENTAL] Simple Tab Groups](https://addons.mozilla.org/firefox/addon/experimental-simple-tab-groups/) with support Hide Tabs API, and I was removed option "open in new window" as unused
This version will be next generation of addon.
Thanks

**Comment by Drive4ik** [comment]
Implement on STG 3.0. You can it try on FF 61
