### ISSUE TITLE
have some extra stuff in group names

### ISSUE THREAD

**Issue by howdoesthiswork1** [Drive4ik/simple-tab-groups#1118]
There are some additional things in the names of the groups. 

**Desktop (please complete the following information):**
 - macOS Sonoma 14.0 M1 macbook air
 - Firefox version: 119
 - Simple Tab Groups version: dont know where to check but should be the latest version

<img width="80" alt="image" src="https://github.com/Drive4ik/simple-tab-groups/assets/149819426/77f5888f-1c87-49ae-8378-fd6f00daf15f">
<img width="116" alt="image" src="https://github.com/Drive4ik/simple-tab-groups/assets/149819426/8627c12f-a7e5-4311-9af5-c22c5bb52709">

**Comment by CarlaSa** [comment]
I had the same issue, but simply updating/restarting Firefox worked for me
