### ISSUE TITLE
Feature request: Focus the search field after the main UI is opened.

### ISSUE THREAD

**Issue by spiralsam** [Drive4ik/simple-tab-groups#112]
In other words, you can begin immediately typing your search right after you click open the main UI from the toolbar.

**Comment by hdd60311** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1324255
This is firefox's bug and it is fixed in 60 nightly.

**Comment by Drive4ik** [comment]
247676e commit has mistake in message, need to be #122
