### ISSUE TITLE
Add ability to change where backups are stored to somewhere other than downloads folder

### ISSUE THREAD

**Issue by Marcus5408** [Drive4ik/simple-tab-groups#1123]
**Is your feature request related to a problem? Please describe.**
The problem is that backups can only be saved to the downloads directory, which is problematic because I often clear out my downloads folder and lose my backups if I don't move the folder out of the downloads directory. Then, if I forget to move it back, I end up with no longer having my tab groups backed up and ready for use when I open Firefox again.

I also found someone else who would seem to benefit from this feature being added while looking for similar issues:
> I'm using version 5.2 on Linux. 
> 
> Setting the backup Folder name to 
> `/home/users/bob/backup/SimpleTabGroups`
> creates backups in
> `/home/users/bob/Downloads/homeusersbobbackupSimpleTabGroups`
> 
> — _@jonfre in https://github.com/Drive4ik/simple-tab-groups/issues/1112#issuecomment-1817192164_

**Describe the solution you'd like**
I want to be able to set a custom directory to put backups in, rather than just the name of the folder in the downloads directory specified in Firefox settings.

**Describe alternatives you've considered**
I don't really see other alternative solutions to this problem, other than asking the user where to save the backup every time the extension wants to save a backup.

**Additional context**
N/A

**Comment by vitusson** [comment]
> I also found someone else who would seem to benefit from this feature being added while looking for similar issues:

If you really looked  for similar issues, you would have found dozens of more. And tons of answers why it is not possible cause it's a FF restriction, ffs. Instead every month someone opens a new issue for the same problem.
