### ISSUE TITLE
Issue / conflict with other Firefox add-ons

### ISSUE THREAD

**Issue by dfumagalli** [Drive4ik/simple-tab-groups#113]
Hello,

I really love this add-on, it's almost exactly how I'd have wanted a tab groups manager.

However I have found an issue or conflict, on all the tabs managed by another Firefox addon.

In example, I am a software developer and use [RESTClient](https://addons.mozilla.org/en-US/firefox/addon/restclient/) a lot.

That addon, usually shows tabs with URLs like:

`moz-extension://97962cef-4e9a-4452-846b-2fbc9b60e731/index.html#`

Below the URL, the add-on user interface appears. If you restart a "vanilla" Firefox, the tabs reload whatever I was doing when I closed the browser. It's various edit fields reload the content they had before I closed Firefox.
However, if I put such tab inside a tab group and then work and then restart Firefox with your add-on installed and load that tab group, all the RESTClient windows loses all the edit boxes contents.

**Comment by Draghmar** [comment]
I think it could be related to #103 and by that I mean webext may have some limits of what can be pulled and stored by Simple Tab Groups. It looks like this add-on can't save session state.

**Comment by Drive4ik** [comment]
Hi. I fix this bug.
To show result you need wait new version STG, install it and change group to any one and go back.
