### ISSUE TITLE
Tab Group Password

### ISSUE THREAD

**Issue by RaiderLeader666** [Drive4ik/simple-tab-groups#1139]
**Is your feature request related to a problem? Please describe.**
I have a NSFW group that I don't want to have to delete and import the group constantly.

**Describe the solution you'd like**
Why not make it so certain groups are password locked? Like for example if you have a tab group entirely for banking or wanking you can put a password on them so if someone gets onto your device they can't accidentally open your porn stash or get into your banking info,

**Comment by tianjianchn** [comment]
Then that person uninstalls SimpleTabGroup and gets all of your tabs. Or even without this, he could also get all of your hidden tabs from the top-right icon of Firefox.

**Comment by RaiderLeader666** [comment]
So you make uninstalling it password protected too, plus nobody in their right mind would uninstall an add-on on YOUR device.

**Comment by matterharz** [comment]
Since it's only a single group, this could be an alternative: https://addons.mozilla.org/en-US/firefox/addon/webext-private-bookmarks/ Hasn't been updated in 2 years or so but it's still working fine.

**Comment by RaiderLeader666** [comment]
I'll look into it for sure but I do hope the dev takes this suggestion into consideration

**Comment by nekohayo** [comment]
> So you make uninstalling it password protected too

That is not possible. That's not how browser extensions work.

> Why not make it so certain groups are password locked

As pointed out by others, it is not possible to do this. This extension simply uses the browser's official API to hide/show tabs from the view, there is no such thing as tab isolation. You could still access those tabs simply through the addressbar, completely bypassing whatever the extension does.

If you can't trust your computer's user session, you have bigger security problems that this extension cannot solve. You should get an auditable operating system and dedicated user account with password screen locking + disk encryption. No extension can protect your tabs from someone actively sitting in front of your computer.

I recommend closing this issue.

**Comment by hentdisr** [comment]
you can try archiving said group to hide it from view, then unarchiving to bring it back (archiving deletes the tabs as well)
