### ISSUE TITLE
Support switching to arbitrary groups via keyboard

### ISSUE THREAD

**Issue by stephen304** [Drive4ik/simple-tab-groups#114]
With the old Panorama, I would use Ctrl + Shift + e to open the switcher, use up/down to change the selected group, and press enter to switch groups. This was extremely fast and convenient.

I propose 2 features to allow this:

* Add a hotkey support to open the switcher - only a few actions are hotkey supported now, including switching to a specific group, but I don't see anything to open the switcher menu.
* Allow navigating the switcher with up/down/enter, with the current group selected by default after opening. I noticed that you can already navigate the switcher with the keyboard, but only after clicking inside the switcher. This loses the benefit of having keyboard support by forcing people to reach for the mouse even if they can open the switcher with the keyboard.

As a bonus, it would also be great to be able to type into the switcher search without having to click into it.

**Comment by Drive4ik** [comment]
Please, read #111 and #112 
Now you can open popup by F8 key and then press double tab key
After fix bug https://bugzilla.mozilla.org/show_bug.cgi?id=1324255 in stable FF it will also works normal
You can try this fix in FF Nightly

**Comment by stephen304** [comment]
Yes, I am aware that I can tab to the group list, this bug is because I believe you should be able to use the up/down keys without extra keypresses.

**Comment by Drive4ik** [comment]
I understand, sorry but not is'nt possible. Only hardcoded shortcut in manifest.json
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Special_shortcuts

need `_execute_browser_action` action

**Comment by Drive4ik** [comment]
Now it's become possible:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands/update
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands/reset

**Comment by Drive4ik** [comment]
Hi, this feature will be available in STG 3.0. Thanks
