### ISSUE TITLE
Closing tab in "Manage Groups" causes group to scroll to top

### ISSUE THREAD

**Issue by stephen304** [Drive4ik/simple-tab-groups#115]
When managing the groups in the "Manage Groups" screen, I have a large group that I am sorting which has a scroll bar. If I scroll down halfway and close a tab, the group scrolls back to the top. This makes it very difficult to close multiple tabs that are not at the top.

**Comment by Drive4ik** [comment]
Hi. This bug was fixed in STG 3.0 and FF 61
