### ISSUE TITLE
STG button not showing on url bar

### ISSUE THREAD

**Issue by branic** [Drive4ik/simple-tab-groups#1150]
**Describe the bug**
I have installed the extension, but the "9 squares" icon does not appear in the url bar or the tab bar.

![image](https://github.com/Drive4ik/simple-tab-groups/assets/13800082/869c8132-6c43-4fcc-84f6-fa0def697bb8)

This makes it difficult to use the extension. I am able to navigate to View -> Sidebar -> Simple Tab Groups to bring up the sidebar, but that is more cumbersome than being able to use the icon would be. 

I'm also able to use F8 and get a popup from the extensions button

![image](https://github.com/Drive4ik/simple-tab-groups/assets/13800082/092c9244-e091-419e-95ff-9331ba8e2e36)

**To Reproduce**
1. Install the extension from the Firefox add-ons site

**Expected behavior**
The button to access the tab groups is available to be used.

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version:  Fedora Linux 39
 - Firefox version:  123.0 (Firefox build, RPM: firefox-123.0-2.fc39.x86_64)
 - Simple Tab Groups version: 5.2

**Additional context**
In addition to the Simple Tab Groups extension I have the following extensions installed:

-  Cisco Webex Extension
- Enpass Password Manager
- Firefox Multi-Account Containers
- Foxy Gestures
- GNOME Shell integration

**Comment by achernyakevich-sc** [comment]
@branic It looks like issue you created is not a bug and is duplicate of #1109.

Firefox by default all Add-ons' buttons has hidden behind of `Extensions` button in the toolbar. You could click this button, find STG Add-On there, click its gear button and pin STG's button to the toolbar.

It is really sad that in the actual version it is not automatically pinned. There is a #1111 Pull Request that fixes it. So as soon as it will be merged and included to the next version problem will be gone.

I would propose you to close this issue as the duplicate of #1109.

**Comment by branic** [comment]
@achernyakevich-sc Thanks for the help. I didn't find #1109 or PR #1111 when I opened this issue.

I will close it as a dup of #1109
