### ISSUE TITLE
Change icon color

### ISSUE THREAD

**Issue by candroid-man** [Drive4ik/simple-tab-groups#1154]
Currently you can either have a black icon with color, or a solid color icon in a circle. I would really rather have the icon you see below, but in white for obvious reasons. It is very hard to see if you have a dark theme enabled in the browser. It would be cool to have the option for at least black or white.

![image](https://github.com/Drive4ik/simple-tab-groups/assets/51019003/810431f9-4d5c-4e77-adaa-50678222e957)

**Comment by vitusson** [comment]
Hmm, I use this icon with triangle on a dark browser theme and it looks like this
![Screenshot_24-03-24--03_30_07](https://github.com/Drive4ik/simple-tab-groups/assets/16023080/1437a56b-346a-40eb-9ebd-0b6d93e5db23)
This being the icon in the browser toolbar, or are you talking about the icons in the popup after you click on the toolbar icon? (Firefox here)

**Comment by candroid-man** [comment]
Umm yeah that's exactly what I want but I don't know why it isn't that way. I am using LibreWolf with dark mode enabled

**Comment by vitusson** [comment]
Never used LibreWolf and don't know if the UI is really that different from FF. 
I'd try different themes to see if it's somehow theme related. If I switch themes, the color changes, if the toolbar has lighter background the sqares on the icon get black, on darker background  lighter, from gray to white

**Comment by candroid-man** [comment]
I didn't follow directions. 

> To fully support the dark theme, enable the `svg.context-properties.content.enabled` parameter to true on the `about:config` page

**Comment by vitusson** [comment]
Interesting. In my Firefox 115 ESR it changes nothing and the setting was always on "false", but in FF 124 the icon switches from white to black imediately. Good to know.
