### ISSUE TITLE
Groups with more than 11 entries not displayed correctly

### ISSUE THREAD

**Issue by flexibeast** [Drive4ik/simple-tab-groups#1166]
Context: Firefox 125 on Wayland/[Wayfire](https://github.com/WayfireWM), on Gentoo.

Since upgrading from FF 124 to 125, groups with more than 11 entries aren't displayed correctly; instead of a list of tabs, only a blank canvas is displayed. Thus, instead of e.g.

![11-tabs](https://github.com/Drive4ik/simple-tab-groups/assets/190652/d8881f99-5344-4d94-9c6b-6d766b910871)

i instead get:

![12-tabs](https://github.com/Drive4ik/simple-tab-groups/assets/190652/6e76334d-f68f-414b-9cca-621360021906)

Additionally, searching for a particular tab by name results in a blank canvas, regardless of the number of results.

Downgrading to FF 124 resolves the issue.

This issue was originally reported on the Gentoo bug tracker, as [#930414](https://bugs.gentoo.org/930414).

**Comment by vitusson** [comment]
Seems to be Wayland specific. Doesn't happen here on a Debian with Xserver

**Comment by flexibeast** [comment]
@vitusson: Thanks for the data point!

**Comment by nekohayo** [comment]
The issue does not happen with Firefox 125 on the Wayland version of GNOME with either Intel or AMD graphics, so this must be specific to your Wayfire setup; I'd suggest closing this ticket here, as you have correctly reported it to Wayfire as well :)

**Comment by flexibeast** [comment]
Yes, sorry, i meant to come back to this, but have been dealing with other stuff .... i'll close this ticket, although it does seem like it might be related to a possible change in Firefox defaults between 124 and 125, as per [this comment of mine on the WayfireWM issue](https://github.com/WayfireWM/wayfire/issues/2345#issuecomment-2080460153):

> Ah hah! i went to about:config, searched for 'tabs', and examined those settings that were different from the defaults. browser.tabs.inTitlebar, a setting i've never manually changed myself, was different to the default: it was set to 0. When i changed it to its default, it got set to 2. And then the issue disappears. Which is good, except: So does the title bar on the FF window, which i'd prefer to keep.
>
> In my wayfire.ini, preferred_decoration_mode is set to server, but changing it to client seems to make no difference.)
