### ISSUE TITLE
Firefox 126.0.1 Breaks STG

### ISSUE THREAD

**Issue by Cephalostrum** [Drive4ik/simple-tab-groups#1174]
**Describe the bug**
STG Fails to start/crashes immediately on Firefox launch, and prompts to open Debug page

**To Reproduce**
- Update Firefox to 126.0.1 (Issue is non-reproducible on 126.0)
- Restart Firefox
- Receive crash described above immediately on launch

**Expected behavior**
STG launches normally

**Screenshots**
N/A, no errors or additional information beyond Debug page prompt

**Desktop (please complete the following information):**
 - OS and version: Windows 11
 - Firefox version: 126.0.1
 - Simple Tab Groups version: 5.2

**Additional context**
Debug logs have been forwarded to drive4ik+stg@protonmail.com email per Debug prompt

**Comment by vitusson** [comment]
Can't reproduce it on Debian Linux. Everything just as normal as before with 126.0.1

**Comment by Cephalostrum** [comment]
Not sure what happened here, issue persisted through reboot but after uninstalling/reinstalling the extension it's working normally again.
