### ISSUE TITLE
Allow customizing F8 hotkey

### ISSUE THREAD

**Issue by stephen304** [Drive4ik/simple-tab-groups#118]
I think there should be an option in the settings to change the hotkey that opens the group switcher. There are already hotkey settings for cycling forwards/backwards through groups, so it would be great to be able to customize opening the switcher as well.

**Comment by stephen304** [comment]
Sorry if I'm being annoying with these issues, but it's important to me. I've previously donated to (or attempted to donate to) quicksaver, so if you have a tip jar, I'd be happy to send something over.

**Comment by Drive4ik** [comment]
I understand, sorry but not is'nt possible. Only hardcoded shortcut in manifest.json
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands#Special_shortcuts

need `_execute_browser_action` action

**Comment by stephen304** [comment]
Gotcha, that's very unfortunate. It might be helpful to list things like these under a list of limitations to avoid duplicate issues being opened.

**Comment by Drive4ik** [comment]
Maybe i can make list of limitations in future.

also on
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction/openPopup

**Comment by hdd60311** [comment]
About customizing hotkey there has some improvement in 60 nightly.
https://bugzilla.mozilla.org/show_bug.cgi?id=1421811

**Comment by Drive4ik** [comment]
As I did not notice? Good news, now we need to wait.
Thanks @hdd60311

**Comment by stephen304** [comment]
Ah, this is good news! Please do reopen if you find it helpful to keep open until it gets implemented.

**Comment by Keith94** [comment]
FYI, bug 1421811 was fixed.

**Comment by Drive4ik** [comment]
Implement in STG 3.0 and FF 61
