### ISSUE TITLE
Save group settings with enter key

### ISSUE THREAD

**Issue by stephen304** [Drive4ik/simple-tab-groups#119]
Not super important, but it would be nice to be able to press enter after editing the name of a group in the popup to save it. 

![2018-03-06-141916_1920x1080_scrot](https://user-images.githubusercontent.com/981915/37053399-09735e3e-214a-11e8-9c89-6c9a7b9bc637.png)

**Comment by Drive4ik** [comment]
Hi, this feature will be available in STG 3.0, thanks.
