### ISSUE TITLE
Question/suggestion: release memory upon closing the group 

### ISSUE THREAD

**Issue by az-z** [Drive4ik/simple-tab-groups#1195]
@Drive4ik ,
 the extension is a "must". I've been using it for at least the past 5-7 years and it is just perfect. Thank you very much for your continued dedication to evolve this extension.

This is not a bug request or problem description, but rather a suggestion or a question. 

I noticed that memory consumption (on linux Fedora 40 ) is increasing when I switch between the groups ( with tabs in them ). Is it possible to "offload" the pages that are not currently used? Or, maybe" only load those pages that I just made active ( clicked on them ).. and maybe offlad them after some time ( 5,15,3- minutes)...

Thank you again for your work!
Andrew

**Comment by achernyakevich-sc** [comment]
@az-z For me it looks that all described functionality is olready in place. :)

When you press F8 and see list of groups you could make right click either on the whole group or on separate tab and call discard action (it will unload either one tab or all tabs in the group). The screenshot below demonstrate it for a group:

![image](https://github.com/user-attachments/assets/20f47723-755b-4b5a-a436-578026757370)

I my explanation helped you to handle your case, could you close the issue and this way who other users that it really helped. :)

**Comment by az-z** [comment]
Thank you Aleksandr!
The only "wish" would be for the extention to do it "automagically"
