### ISSUE TITLE
Tabs reload on group change

### ISSUE THREAD

**Issue by Thor77** [Drive4ik/simple-tab-groups#12]
I'm not sure if this is expected behaviour, but once I change to another group, all tabs in this group reload.
This will probably kill some browsers for groups with too many tabs.
If it's desired/expected behaviour, please consider adding an option to disable it.

**Comment by Drive4ik** [comment]
At the moment, the Firefox WebExtensions API does not support hiding tabs, only closing ... I also do not like it, but I have no choice.
When this feature is added, I will make it support.

**Comment by Drive4ik** [comment]
let the task be opened so that people read

**Comment by youk** [comment]
Thanks for a nice extension! 
Are you aware of [an experimental way of hiding tabs](https://github.com/kesselborn/conex#getting-a-version-that-can-really-hide-tabs)? I am wondering if you can employ it. It works for Conex.

**Comment by j-rueger** [comment]
Is there a way to suspend the tabs after they begin reloading? Or make them inactive somehow?
Most annoying are youtube tabs that all start playing video and I have to go through each one and pause the video. All while everything is still loading and using lots of CPU making firefox or the video very unresponsive.

Maybe you can insert js into the pages to stop video playback? (There is an API for that, tabs.executeScript()...)

**Comment by pitchum** [comment]
In *about:config* setting `media.autoplay.enabled` to `false` may help.

**Comment by j-rueger** [comment]
@pitchum Thanks for the tip, I didn't know that applied to youtube! One mayor pain less :)

**Comment by Zeioth** [comment]
An option to not load the content of all tabs when you change group would be awesome.

Maybe something like

* "Show all tabs, but load only the one I clicked on the dropmenu".
* Or, "Show all tabs of the group, but load only the last one"

**Comment by dtrckd** [comment]
+1 for this feature, whose its lack prevent me for actually switching between groups...

**Comment by dhia-eddine** [comment]
I think there is already a way to not load tabs. because firefox configured to open last opened tabs, and when it starts only the active tab is loaded the others are not. that should be in the internal firefox session manager
there isn't already some option in the api tabs or window loading?

**Comment by lucascosti** [comment]
+1. Are we 100% sure there isn't a way to do this? We're not talking about hiding tabs here, just making sure the background tabs don't 'load' when switching groups. Like @dhia-eddine said, this is what happens when you initially open Firefox.

**Comment by AhTn12** [comment]
Go to Preferences > When Firefox Starts
Choose "Show your windows and tabs from last time"
If you have 4 tabs open, and close firefox, next time you start firefox only one tab loads, while others don't, though they're still there. So...
As dhia-eddine and lucascosti said, it can be done. 
Please fix this, as this is a major drawback in the add-on.

**Comment by me21** [comment]
Another plugin like [LoadTabOnSelect](https://addons.mozilla.org/en-US/firefox/addon/loadtabonselect/) or [LoadOnSelect](https://addons.mozilla.org/en-US/firefox/addon/carregar-ao-selecionar/) can do this. They seem to play with Simple Tab Groups nicely.

**Comment by me21** [comment]
UPD: This plugin now can load tabs lazily since version 2.1.

**Comment by Drive4ik** [comment]
This is just great news. 👍 
I will soon release an experimental version that supports this API!

**Comment by Drive4ik** [comment]
Closed. We will discuss in #2

**Comment by WolfganP** [comment]
Now that hide tabs functionality is being tested in FF, the ability to manually **suspend/discard selected/all tabs** would be a great complement feature to this extension, and be able to optimize the use of FF with many tabs without resorting to additional extensions (ie Tab Suspender)

Here's a sample of how it was implemented in a deprecated WE tab helper extension https://github.com/Allasso/WE_alltabshelper/search?utf8=%E2%9C%93&q=discard&type=
Thanks!

PS: it's great to see that saving sessions with tab groups can be achieved via https://github.com/sienori/Tab-Session-Manager/issues/201 as a complementary extension

**Comment by dgutov** [comment]
@WolfganP I think it would be better served by a separate, orthogonal extension. For instance, it could discard tabs after a certain timeout (time the tab has not been visible). It doesn't really need to know about groups for that.
