### ISSUE TITLE
Save size and location of the panorama pop-up window

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#121]
Hi
When using the panorama view in a stand alone window, it takes the whole screen by default. Which is far to wide with a... wide screen, imho :) So I resize it but the new size and location is lost on the next display.
Woudl it be possible to retain the size and position of that windows?
Thanks

**Comment by Drive4ik** [comment]
Hi! I made saving the window size, but here the position is not saved. Most likely this is another Firefox bug, and as soon as it is fixed - the position will also be preserved. At the moment the window takes the desired size and is displayed in the center of the screen.
This update will available in next release.

**Comment by Drive4ik** [comment]
P.S. size saves every 5 sec
