### ISSUE TITLE
TypeError: winTab is undefined on Firefox startup

### ISSUE THREAD

**Issue by irvin** [Drive4ik/simple-tab-groups#122]
<img width="351" alt="2018-03-08 19 22 27" src="https://user-images.githubusercontent.com/165936/37148622-05ccaa4a-22c3-11e8-8d08-b6fb010e44a3.png">

I bumped into this issue when I restart Friefox, and cannot open group manager for now.
Not really sure how to re-produce it.

**Comment by irvin** [comment]
However I can resolve the issue when I disable and re-enable the addon.

**Comment by Drive4ik** [comment]
Hi! Please, update addon to latest version and retest this bug.
Thanks

**Comment by irvin** [comment]
Still often appear when starting Firefox, not determine what cause the problem yet.

**Comment by Drive4ik** [comment]
What version STG and FF you are used?
Can you make screenshot STG popup?
Thanks

**Comment by Drive4ik** [comment]
fixed in STG 3.0
