### ISSUE TITLE
After Restarting Firefox, opening a Synchronized Tab Group opens tabs in reversed order

### ISSUE THREAD

**Issue by Tamehome** [Drive4ik/simple-tab-groups#123]
Hi, I am using Firefox 58.0.1 and plugin v2.4.7.
After restarting Firefox, when I open a Synchronized Tab Group, the first tab loads normally, but the remaining tabs open in reverse order.  So, if I have tabs:
1 2 3 4 5
After restarting Firefox and re-opening the tab Group, the order becomes:
1 5 4 3 2
It is tedious to have to reverse the order, although a workaround has been to close and reopen FF to get the tab groups to reverse order again.  It would be great if you can fix this.

**Comment by Drive4ik** [comment]
Hi! Are you has the same problem?
#18

**Comment by Tamehome** [comment]
Hi, yes, this does appear to be the same issue.  I have the "Open Tabs Next to Current" addon installed.  This appears to cause the reload of the tabs in reverse order.  Is there a way to detect if that plugin is installed and add the tabs back in in reverse order?

**Comment by Drive4ik** [comment]
I tried to fix this problem, but this is not possible, because of this there are many other bugs and conflicts.

**Comment by Drive4ik** [comment]
This bug will gone after I release next generation of STG with support hide tabs API (#2)
Perhaps in FF 60 (if hide tabs feature will be enabled by default).
