### ISSUE TITLE
No Group selected when opening FF

### ISSUE THREAD

**Issue by Dollique** [Drive4ik/simple-tab-groups#124]
**Problem description**
When I start Firefox there is no group selected (no color on the icon).  Also when I open 'Manage Groups' I don't see the tabs I have currently open.

If I click on any group there is a warning:  Load this group will close all current tabs!

As I use the tab groups seldom I don't want to change the groups because I fear that all currently open tabs will be lost.

**preferred solution:**
I would like STG to show me the last open group on startup.

**Not so much preferred solution:**
If you want to keep this 'no-group' state please at least give us an option to import the currently open tabs into a group.

**Environment tested**
1. Win 10, FF Nightly 61.0a1
2. Mac OS X, FF Developer Edition (Current release, but I don't have it here, so I don't know)

**Comment by Drive4ik** [comment]
Please update the addon to the latest version, move the open missing tabs to the desired group, go to it and agree that the current tabs will be closed (the tabs that are in the group will open) and retest this bug (reopen Firefox after all tabs was loaded)
Thanks

**Comment by Dollique** [comment]
Did this and it worked one time when I waited for FF to finish loading.
Second and all following tests didn't work and the following alert was shown on startup:

![2018-03-12 18_58_13-](https://user-images.githubusercontent.com/11680332/37300935-892e767c-2627-11e8-95e3-243a1c7b1157.png)

Also I could not move the currently open tabs to a group, as the the 'manage group' view doesn't show these tabs if they are not in any group.

**Comment by Drive4ik** [comment]
Are you update addon to latest version? (v2.4.8)
You can move tabs by context menu on active tab
![screenshot_1](https://user-images.githubusercontent.com/7843031/37301532-7c4a474c-2631-11e8-8e09-4c3794610ab7.png)

You need sync group with window in latest version of addon

**Comment by Dollique** [comment]
Ah, okay I didn't know about this feature.
With this I can at least move the tabs to not loose them.

Though, the main issue is still there.

**Comment by Tamehome** [comment]
Hi, if you can do that with a single tab, is there a way to open the Simple Tab Groups button at the tab bar for an unsynced Window, and select sync to a Group, to move all of the tabs of the Window into the managed Group, replacing the existing tabs in the Group?

I tested v2.4.8, and after the first FFX restart, all windows remained synced (I had 4 open).  I then closed and reopened FFX, and only Window 1 remained synced.  The other 3 became unsynced.  Every FFX restart after that only seems to load sync Window 1, even if I close and reopen synced Windows.

1) If you can fix this sync issue to always resync the Windows after restart, that would be great.
2) If you can expand that experimental option to the main Simple Tab Groups button and add an option to "Sync Tabs to Group" for a selected Group, replacing the existing tabs in the Group with those from the currently selected Window, that would be a great way to recover unsynced tabs.

**Comment by gagarine** [comment]
I have a similar issue. I'm using "individual windows for each group" option. When I reopens Firefox, all my group that was open open has windows because I have:
![screen shot 2018-03-15 at 18 42 43](https://user-images.githubusercontent.com/164074/37480903-ad3e06a8-2880-11e8-86d9-0edbb91c93c8.png)

But group has not "matched" with those windows. Clicking on group, open a new windows with the same tabs.

My settings:
![screen shot 2018-03-15 at 18 43 50](https://user-images.githubusercontent.com/164074/37480957-d4559c92-2880-11e8-9871-6942db746d78.png)

**Comment by Drive4ik** [comment]
Hi all.
Can you help me understand this problem?
First of all create backup all your data:
![screenshot_3](https://user-images.githubusercontent.com/7843031/37601671-55f75334-2b93-11e8-9764-a48659beea5a.png)

then disable STG, download and install this TEST build of STG:
rename file from
```
test_startup_simple_tab_groups-2.4.8-an+fx.xpi.zip
to
test_startup_simple_tab_groups-2.4.8-an+fx.xpi
```

[test_startup_simple_tab_groups-2.4.8-an+fx.xpi.zip](https://github.com/Drive4ik/simple-tab-groups/files/1825381/test_startup_simple_tab_groups-2.4.8-an.fx.xpi.zip)

restore backup, and try to replicate this bug.

if you replicate this bug you can see this notification
![screenshot_1](https://user-images.githubusercontent.com/7843031/37602056-3d1311e0-2b94-11e8-85b0-7f80faae2b41.png)

you need at once go to addon settings, scroll down and press this button
![screenshot_2](https://user-images.githubusercontent.com/7843031/37602098-5583c3b4-2b94-11e8-9b9a-137d1bf8d5fa.png)

send to me this file by email: drive4ik@gmail.com

P.S. all of your private data in this logs are replaced by security and your urls replaced by URL_1, URL_2, URL_3, URL_1 etc... You can open this file and see it.

Thanks

**Comment by Drive4ik** [comment]
Hi! Can you retest this bug in latest version? (v2.5)
If bug was fixed - close issue.

Thanks

**Comment by Dollique** [comment]
Perfect, I am not able to reproduce, seems to work now!
