### ISSUE TITLE
Feature request: Automatic backup

### ISSUE THREAD

**Issue by Draghmar** [Drive4ik/simple-tab-groups#125]
As there are no session managers that works properly with grouping tabs (they save only active group) could add option to make periodical backups of all groups? We already have option to manually backup everything so the change I'm proposing is just an extension to that feature.
This would be especially useful with all those reports about FF losing some tabs and sessions from time to time. :)

**Comment by Drive4ik** [comment]
Please, read this comment and below
https://github.com/Drive4ik/simple-tab-groups/issues/2#issuecomment-372612959

**Comment by Draghmar** [comment]
Oh, so there's a new and better version coming. Great to hear and can't wait! :)
