### ISSUE TITLE
All windows use the same color icon that the focused windows

### ISSUE THREAD

**Issue by gagarine** [Drive4ik/simple-tab-groups#126]
I'm using "individual windows for each group". So I can have more than one group open in the same time in different windows. But the icon of each windows is always the one of the windows (group) that have the focus.

Two windows that should have different icon (they are different group):
![screen shot 2018-03-15 at 18 46 56](https://user-images.githubusercontent.com/164074/37481195-7213c47c-2881-11e8-9054-ed7e38d02cbd.png)

**Comment by Drive4ik** [comment]
Hi! Please read #61 
When FF will add same functional I make it support.
Thanks.
