### ISSUE TITLE
I can no longer save changes to group settings because the 'save' button is not displayed

### ISSUE THREAD

**Issue by Philip-Sutton** [Drive4ik/simple-tab-groups#128]
I've got 22 groups.  When I go to the group settings dropdown window I can no longer see the save button even when I scroll right down to the bottom of the window.  Perhaps the save button could be relocated to the top of the window?  See the attached animated gif.
![can t see the save button in the group settings drop-down menu](https://user-images.githubusercontent.com/1549449/37843044-e5103004-2f17-11e8-868c-8869f49f3c42.gif)

**Comment by Drive4ik** [comment]
Hi. I partially fix this bug. This is strange FF behavior when FF window very close to bottom...

**Comment by Philip-Sutton** [comment]
thanks

**Comment by Philip-Sutton** [comment]
Hi,  Today's fix for this problem works on my system.  Thanks so much. 

I'm happy if you close this issue.  

Cheers, Philip

**Comment by Drive4ik** [comment]
Best regards
