### ISSUE TITLE
non-private cookieStoreId in a private window

### ISSUE THREAD

**Issue by schelmo** [Drive4ik/simple-tab-groups#13]
im getting "Illegal to set non-private cookieStoreId in a private window" in my notifications.
but i dont have any private windows. Do you have an idea ?
Im using some pinned tabs. Maybe that is the problem ?

Linux Firefox: 57.0.1 (64-bit)

**Comment by schelmo** [comment]
after i deleted all groups, everything works fine again.

**Comment by Drive4ik** [comment]
Hi! I can't replicate this bug. Please, update to version 1.8.2 or higher and retest this bug.
If its replicated tell me what are you doing before this notification.
Thanks!

**Comment by schelmo** [comment]
jau i cant replicate it too, after deleted all groups.
will reopen the issue if it happens again.
