### ISSUE TITLE
"phantom" windows after restoring session after Firefox crash 

### ISSUE THREAD

**Issue by gagarine** [Drive4ik/simple-tab-groups#130]
Restoring session after Firefox Crash create "phantom" windows.

**Step to Reproduce:**
- Use the settings "individual windows for each group"
- create a couple group and keep their windows open
- force quit Firefox
- open Firefox
- restore the session

**Result:**

Windows are restored with their tabs but the group are not "in sync". Closing those windows and reopening the group fix the problem

**Expected result**
Windows and tabs are restored and "in sync" with the corresponding group.

**Comment by Drive4ik** [comment]
The addon does not know that FF has restored windows or tabs, so it does not start the synchronization function. It works only when the addon starts. You can try disable/enable addon after restore FF session, so it can work.

**Comment by gagarine** [comment]
It's fixed. Thanks a lot.
