### ISSUE TITLE
All tabs in the last selected group will be wiped after reopening browser

### ISSUE THREAD

**Issue by JacobSvenningsen** [Drive4ik/simple-tab-groups#133]
Due to #124, I started Firefox with a single blank tab as this would allow me to open the tab groups I had to use when starting my browsing section.
However, with the fix of #124, a new bug was introduced. If you haven't selected the "Show your windows and tabs from last time" option, then when you start Firefox, all tabs within the tab groups you had opened from your previous browsing section, will be wiped and only a single blank tab will be displayed instead.

Expected behaviour: Either a new tab group or no tab group selected at all, leaving the tab groups intact from your previous browsing session

**Comment by Drive4ik** [comment]
Well, this is the expected behavior. For the correct operation of the add-on, you should have the option "Show your windows and tabs from last time" is enable.

**Comment by propagare** [comment]
I have the "Show your windows and tabs from last time" activated and I lost 46 of my most precious tabs in only one group. Any chance to recover them?

**Comment by Drive4ik** [comment]
@propagare You can recover tabs from browser history.

I need to explain a little: this addon never spontaneously closes the tabs, only when you switch the group, or open the tab to fit under the regular expressions (group settings), and nowhere else.

**Comment by Drive4ik** [comment]
Can you replicate this bug in STG 3.0 and FF 61?
If not - please close issue
