### ISSUE TITLE
All groups gone overnight? Any chance of recovery?

### ISSUE THREAD

**Issue by meru448** [Drive4ik/simple-tab-groups#134]
I'm on 61.0a1 (2018-03-26) (64-bit) nightly

Logged off last night with ~12 tab groups of varying amounts of tabs.

Booted it up just now to.....nothing not sure what to do.

**Comment by meru448** [comment]
Ok so when I make a new group, it makes Group 42, Group 43, Group 44, etc.

So they are in there somewhere?? but I don't know how to access them.

**Comment by propagare** [comment]
Same here. I can't even replicate it. It is so unexpected. No backup here. Is there any chance to recover them? Please. 

Any hints for a good group backup (auto) would also be highly appreciated.

**Comment by lemenkov** [comment]
Same here. Fortunately I've got a 3-week old backup.

**Comment by Drive4ik** [comment]
Please, update addon to v3.0
