### ISSUE TITLE
Unintentional opening of new tab on group start

### ISSUE THREAD

**Issue by Speravir** [Drive4ik/simple-tab-groups#136]
_I do not know who’s the culprit here, but let me nonetheless describe it here:_

On every start of my second saved group (I do not have more in the moment) also a new tab is opened, though I did not have saved this before, in fact I delete this every time before doing other actions. This new tab is from [New Tab Tools add-on for Firefox](https://github.com/darktrojan/newtabtools) (and Chrome, but I do not use this one), _not_ `about:home` or `about:newtab`. On the first group active on Firefox start this does not happen.

I think it started with version 2.5 of your addon about a week ago, but there was an update of New Tab Tools on the same day (version 86.5).

**Comment by Philip-Sutton** [comment]
The same thing is happpening for me too.

**Comment by Speravir** [comment]
@Philip-Sutton Do you use New Tab Tools or a similar addon, too, or didn’t you change anything?

**Comment by Philip-Sutton** [comment]
@Speravir I don't use New Tab Tools.  The automatic addition of a new tab (when opening any group other than my first group) just began recently.  But not sure what version of simple-tab-groups was running when it started.

**Comment by Speravir** [comment]
With version 3.0.8 of this addon the issue is gone. The actual duplicate #167 is already closed, and this can safely be closed, too.
