### ISSUE TITLE
Feature request: Sync tabs in an inactive groups

### ISSUE THREAD

**Issue by ohadt** [Drive4ik/simple-tab-groups#138]
Only the tabs in the currently selected group are being synced through the firefox account to other devices. It will be great if all of them can be synced... and it will AMAZING if the groups can be synced as well.
Thank you for your awesome work

**Comment by Drive4ik** [comment]
Hi. Can you retest this in STG 3.0 and FF61. If Firefox sync hidden tabs - everything should work

**Comment by ioda** [comment]
I vote for this request too
I hope your implement sync tab for hidden groups
