### ISSUE TITLE
Hide, not kill

### ISSUE THREAD

**Issue by White-Owl** [Drive4ik/simple-tab-groups#14]
The old TabGroups plugin did not reload the tabs on switching back into the existing group.
Not sure how it was done in the TabGroups, but could you please do the same or similar feature?

**Comment by Drive4ik** [comment]
At the moment, the Firefox WebExtensions API does not support hiding tabs, only closing ... I also do not like it, but I have no choice.
When this feature is added, I will make it support.
Thanks for your feedback!
