### ISSUE TITLE
BUG: Tabs have been moved between groups after the browser restart.

### ISSUE THREAD

**Issue by roman90sv** [Drive4ik/simple-tab-groups#141]
I created just 4 groups and gave them names. When I restarted the browser, I saw that the group names did not match their contents. -The groups exchanged tabs.

My Settings:
![stg bug1](https://user-images.githubusercontent.com/35082918/38471794-c72bb5fe-3b7e-11e8-9fa3-b6de4c1b48d4.JPG)
"Show your windows and tabs from last time" is enable.

**Comment by stephen304** [comment]
This may be the same issue or maybe just related, but I noticed that if I have Groups 1, 2, 3 and 4, and I am in group 4 when I restart the browser (or maybe just when I force quit the browser when restarting my laptop, need more testing), when I reopen the browser, I see the group 4 tabs, but the switcher indicates that I am not in a group. If I then switch to any group (1-4), it then adds another copy of the group 4 tabs to that group. For example, if I switched to group 1 after reopening, group 1 would have group 1 and 4 tabs, and group 4 would have another copy of group 4 tabs. If I switch to group 4 after restarting, group 4 will then have 2 copies of all the same tabs.

The solution I have come up with is: when reopening firefox, I create a new empty group, switch to that group, then delete that group and the duplicate tabs that got deposited into it. Unfortunately, I forget to do this half the time...

**Comment by roman90sv** [comment]
**stephen304**, Try to use this options: "the individual window for each group" + "Create a new group when you move a tab to a new window". This should help.

"TabHiding" feature has recently been released, in version 59. https://blog.mozilla.org/addons/2018/01/26/extensions-firefox-59/ #Experimental Tab Hiding
Perhaps the plug-in can not yet support this feature, so it's reasonable to open each group in a individual window.

**Comment by Drive4ik** [comment]
Hi all. You can to try [EXPERIMENTAL] Simple Tab Groups: https://addons.mozilla.org/firefox/addon/experimental-simple-tab-groups/
if this addon don't resolve this problem I will try fix bug in experimental version. I dont support big changes in stable version and I prepare addon to new FF API: Hide Tabs

**Comment by adipose** [comment]
I have been using EXPERIMENTAL ever since it supported hide tabs, and that's where I've experienced this bug repeatedly, including today while using FF60.  All tabs get copied into all groups, is what appears to happen.

**Comment by shaunmavronicolas** [comment]
I have experienced this same issue today, I am not using the Experimental version, this is the "stable version". Whole tab group sets have been replaced with other tab groups and the tab group set that was there is lost. This is a very ugly and unfortunate bug to have encountered. Kinda defeats the whole purpose of this plugin really...

**Comment by Drive4ik** [comment]
Please retest this issue in STG 3.0 and FF 61
If its not replicate - close bug
