### ISSUE TITLE
show all tabs on hover in group list

### ISSUE THREAD

**Issue by RobTranquillo** [Drive4ik/simple-tab-groups#142]
To have a fast overview, it would be great to popup a list of all containing tabs, while hovering over a tab group list entry.

At the moment you have to click on the list entry to see all the containing tabs. I like to hav this information right before, on hover about the list entry.

Thanks for the plugin.

**Comment by Drive4ik** [comment]
Done. To show this notification - you need to hover on group tabs text. This update will available in next release.
![screenshot_3](https://user-images.githubusercontent.com/7843031/42322441-397903f2-8065-11e8-8465-08e18723d4cc.png)
