### ISSUE TITLE
TypeError: t is null

### ISSUE THREAD

**Issue by beep** [Drive4ik/simple-tab-groups#143]
Hi! When Firefox first boots up, I’m getting an error message from the Simple Tab Groups addon:

<img width="347" alt="Firefox warning: “TypeError: t is null”" src="https://user-images.githubusercontent.com/124493/38824252-a7960016-4176-11e8-93f1-e96ca9ab00c1.png">

After that point, the plugin’s (sadly!) not usable. The icon’s replaced with a spinning graphic in the browser chrome:

<img width="97" alt="Spinning loader icon in Firefox toolbar" src="https://user-images.githubusercontent.com/124493/38824365-fc5e92de-4176-11e8-96de-b857469b22ab.png">

Clicking on it doesn’t do anything.

(If it helps, the plugin’s at v2.5.3; I’m running Firefox dev edition, v60.0b12.)

**Comment by Drive4ik** [comment]
Do you replicate this error now?
You can fix this bug manually: create backup (without thumbnails) and find string `null` in `groups` item and remove it. For example:

```
{
    "groups": [{
        "id": 1,
        "title": "my title",
        "tabs": [
            {
                "title": "google",
                "url": "google.com",
            },
            null,   <-- remove this with coma
            {
                "title": "facebook",
                "url": "facebook.com",
            }
        ]
    }],
}
```

**Comment by beep** [comment]
@Drive4ik thanks so much for the reply! I ended up deleting the extension and reinstalling it, which seems to have resolved the error. If it recurs, I’ll try this. Thank you.

> You can fix this bug manually: create backup (without thumbnails) and find string null in groups item and remove it.

Just to clarify: which file would I need to edit?

Thanks again!

**Comment by Drive4ik** [comment]
Thanks

**Comment by beep** [comment]
Great, thank you! I’ll give it a shot next time, and reopen if this doesn’t resolve the issue.
