### ISSUE TITLE
Add-on sends all domains to Google over unencrypted connection?

### ISSUE THREAD

**Issue by rugk** [Drive4ik/simple-tab-groups#144]
https://github.com/Drive4ik/simple-tab-groups/blob/54ea8ebfae5a3597317674bb80aa3da20c7aa328/addon/background.js#L117

Am I correct that the linked line in the source code says, that this add-on – in order to retrieve a colored icon – sends all URLs of the tabs it touches (so basically all URLs?) to Google?

So first: This needs an explicit statement! **At least in the privacy policy**, you can add on AMO.

Secondly, in any case, you **can use an encrypted connection** there, at least. So that not everyone on the network get's the domain information. Just add an `s` there…

Disclaimer: Did not test this add-on.

**Comment by Drive4ik** [comment]
fixed in v2.5.4.1
Thank you for reminding me, I was fix this bug in other branch but forget make that fix in master branch.

**Comment by wulmer** [comment]
Thanks for bringing this up. I also don't want an addon to send any URL I open to a Google server. Especially if you are working in an intranet environment, leaking all internal URLs tells Google a lot about the internal network and information structure (and often, URLs contain parts with slugs which tell much, e.g. about blog titles, etc.).

Although I can understand this quick fix in 9bbbc2d I would prefer a more versatile solution in the long-term. Perhaps something like an option for enabling/disabling favIcons for Tabs.

**Comment by Drive4ik** [comment]
@wulmer this code will work ONLY if you enable option `Use tabs fav-icons from Google S2 Converter` in addon settings. This option is made for normal operation of icons with sites that use [HTTP authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication)
P.S. this option is disable by default

**Comment by Drive4ik** [comment]
This code can "beautify" as:
```
if (useTabsFavIconsFromGoogleS2Converter) {
    safedFavIconUrl = ('http://www.google.com/s2/favicons?domain_url=' + encodeURIComponent(tab.url))
} else {
    safedFavIconUrl = tab.favIconUrl
}
```

**Comment by wulmer** [comment]
Oh, great to hear! Sorry, I am not (yet) familiar with the internals of this plugin. Nevertheless I appreciate all your work on this addon as my company will soon move from FF52 to FF60 which will make all the old plugins stop working so I am desperately on the search for a good replacement and here I got. Thanks!
