### ISSUE TITLE
Add button to "Customize" menu, so it can be added to toolbars other than the tab bar

### ISSUE THREAD

**Issue by losingkeys** [Drive4ik/simple-tab-groups#145]
Useful if you hide the tab bar, e.g. [like this](https://superuser.com/questions/1268732/how-to-hide-tab-bar-tabstrip-in-firefox-57-quantum/1269139).

Thanks for your consideration and the great addon!

**Comment by Keith94** [comment]
I've also run into this predicament, but keep in mind that hiding the tab bar in such ways is not officially supported and thus should be used at your own risk.

@Drive4ik probably added the button to the tab bar to mimic the behavior of the original Tab Groups add-on. Adding the button to the main toolbar by default could be a "solution" but not really necessary..

**Comment by Drive4ik** [comment]
@Keith94 Yes you are right.

Closed as resolved
