### ISSUE TITLE
[faeture request] remove duplicate per tab group

### ISSUE THREAD

**Issue by tbiberlin01** [Drive4ik/simple-tab-groups#147]
unsing your wonderful addon quite a lot, with around 30groups, 5-40 tabs per group. It ocours that i open several time the same page per tab, so i'm cleaning up the group from time to time and remove duplicate manualy using the list i see when opening the grouplist and select the ">" .. 
Would it be possible to intoduce a button, next to "open new tap" saying "remove duplicates" ?  
Thanks for having a look to it. 
Best from Berlin
thomas

**Comment by Keith94** [comment]
Hi,
Try out the [Duplicate Tab Closer](https://addons.mozilla.org/addon/duplicate-tabs-closer/) add-on as a possible solution. Does it work fine for you?

**Comment by tbiberlin01** [comment]
nice ... does what i need :-D  thanks mate!
