### ISSUE TITLE
Allow setting group icon from emoji

### ISSUE THREAD

**Issue by losingkeys** [Drive4ik/simple-tab-groups#150]
You might need to find a library that has image fallbacks, but this would be really cool!

**Comment by Drive4ik** [comment]
Yeah! This is good idea, but i will make that in next-gen version https://addons.mozilla.org/firefox/addon/experimental-simple-tab-groups/
Thanks

**Comment by Drive4ik** [comment]
You can set needed emoji in group title from https://getemoji.com/
😉

**Comment by JanPokorny** [comment]
Hello @Drive4ik, I found this issue after having the same idea. The link to the next-gen version is dead, did it get scraped? I'd appreciate if you could reconsider the #wontfix.

My workaround was to use https://formito.com/tools/favicon, but it stopped working recently with the following error (after I select to use the favicon as the group icon):
![obrazek](https://user-images.githubusercontent.com/4580066/104847212-fc12b300-58de-11eb-8933-62f762b56f89.png)

I found out that https://favicon.io/emoji-favicons/ works, though.

It also works to put the emoji as a first character and selecting the appropriate icon option, but it results in duplicated emojis in the menu:

![obrazek](https://user-images.githubusercontent.com/4580066/104847277-5d3a8680-58df-11eb-91c8-f24954b8b942.png)

Overall I would be glad for a simpler option to use an emoji as a group icon. If I may propose something, I like the way Microsoft To-Do does it -- if you put an emoji as a first character in a name, it automatically becomes the icon and it gets scraped from the name. (So if you type `"🎵 Music"`, it becomes "Music" with icon 🎵.) This already (partly) works, as seen above, except for the duplicated emoji, so it would be a matter of scraping the emoji after setting the icon.

**Comment by JanPokorny** [comment]
(also I don't think a dedicated emoji search is necessary, windows already has Win+. and other OSs have their emoji keyboards too...)
