### ISSUE TITLE
Manage Groups page is blank

### ISSUE THREAD

**Issue by eguerin** [Drive4ik/simple-tab-groups#151]
<img width="1440" alt="issues with group management" src="https://user-images.githubusercontent.com/1154270/39399172-1afd402c-4ace-11e8-90a5-684cbef4350d.png">

I have a total of 6 groups, however when I goto manage them, nothing appears but a small On off switch at the upper left corner and a search bar on the right side.

**Comment by Drive4ik** [comment]
Hi. Can you update to v2.5.4 and open Manage Groups and screenshot error notification for me?
Thanks

**Comment by Moilleadoir** [comment]
Same for me, v. 2.5.4.1 Linux.

**Comment by Drive4ik** [comment]
Hi all. Can you check whether this issue replicate on the new version of the add-on STG v3.0.7 and FF 61?
If not, please close the bug

**Comment by Drive4ik** [comment]
Can you retest this bug on STG 3.0 and FF 61?
