### ISSUE TITLE
When Browser starts and displays Master Password restore dialog, Synced tab groups don't restore.

### ISSUE THREAD

**Issue by Tamehome** [Drive4ik/simple-tab-groups#154]
Hi, I am experiencing an issue where opening Firefox doesn't restore synced tab groups.  This happens when once of the windows displays a Master Password dialog box (if you have a Master Password configured in the Firefox).  If that dialog appears in one of the windows (e.g., if you are opening a window that has a login page where you saved a password), then that window's tab group will not sync.  Also, any other tab groups for the remaining windows that open also do not restore sync.

For example, I have 4 windows that restore when opening Firefox.  Windows 1 and 2 open and restore the synced tab groups.
When Window 3 opens, the Master Password dialog box appears.  When that happens, the window will not restore the synced tab group.
Also, Window 4, which loads after Window 3, also will not restore the synced tab group.

Is there a way to re-link an unsynced tab group to a synced tab group, to replace all of the tabs in the synced tab group?  If not, can the sync restore be enhanced to handle the appearance of the Master Password dialog box?

**Comment by Tamehome** [comment]
I have updated the issue description after further testing to figure out the root cause.  I think this is the main issue, with the password dialog box appearing during Firefox startup.

**Comment by Drive4ik** [comment]
Hi. You can try press this button after you enter password, addon will restart and resync all tabs and windows. This feature available in STG 3.0 and FF 61.
![default](https://user-images.githubusercontent.com/7843031/41979547-10fd9b06-7a2d-11e8-91a2-a34d2f754c3c.png)
