### ISSUE TITLE
[Experimental] Changing groups while on a pinned tab switches from pinned tab.

### ISSUE THREAD

**Issue by yodaldevoid** [Drive4ik/simple-tab-groups#155]
If a pinned tab is in focus when the group is changed, the focus will be moved to one of the tabs within the new group. The pinned tab is not closed or modified. I expected the group to be changed opened, but the focus not to be moved from the pinned tab.

**Comment by yodaldevoid** [comment]
I understand the implementation choice, though I find it surprising coming from other tab-groups addons. Feel free to close the issue if you are not going to change this or add an option later on.

**Comment by Drive4ik** [comment]
Sorry, but I can not change the current behavior
