### ISSUE TITLE
Feature Request: Are you planning to or can you add the TabGroups and TabGroupsMenu functions...

### ISSUE THREAD

**Issue by Chazfr** [Drive4ik/simple-tab-groups#156]
Feature Request: Are you planning to or can you add the TabGroups [Quicksaver] and TabGroupsMenu [Char01] functions, especially sub-groups, that were available in those pre-Quantum add-ons. They do not appear to be forthcoming as a Quantum version. Furthermore, those features would be best serviced under one integrated add-on. I am already using your SimpleTabGroups, and with TreeStyleTabs [Piro] and TabGroupsMenu, I had cobbled together a business operating environment permitting many open tabs [between 300 and 600 was common]. Without TabGroupsMenu sub-grouping and management, I will have to add equipment and staff to cover what I alone was able to get done.

**Comment by Drive4ik** [comment]
New Firefox API don't has a functional for working with menu as "TabGroups Menu" ...
Only menu by context (on tab or on page)
