### ISSUE TITLE
Popup contents should not zoom with Ctrl+Mouse Scroll

### ISSUE THREAD

**Issue by Keith94** [Drive4ik/simple-tab-groups#158]
In the Simple Tab Groups popup, if you hold Ctrl and scroll your mouse wheel with the pointer over it, the popup contents zoom in an out. The expected behavior is not to scroll. It also happens when using a laptop trackpad for example.

**Comment by Drive4ik** [comment]
Ok, I try to disable it.
Thanks

**Comment by Drive4ik** [comment]
I fixed this issue in experimental version :)
