### ISSUE TITLE
Feature Request: When closing last group, do not close associated tabs

### ISSUE THREAD

**Issue by RevanProdigalKnight** [Drive4ik/simple-tab-groups#159]
Title says it all, really. If I'm closing my last tab group, I don't want the extension to close all my currently open tabs.

**Comment by Drive4ik** [comment]
Hi. This feature will release in next version of Experimental STG, and FF 61 (if its has hidetab enable by default)
Anyway this feature will released in Experimental STG

**Comment by Drive4ik** [comment]
Done in STG 3.0 and FF 61
