### ISSUE TITLE
switch group impossible if i'm in a blank tab

### ISSUE THREAD

**Issue by lyonelf** [Drive4ik/simple-tab-groups#161]
the switch group via keyboard is not possible if i'm in a new empty tab

**Comment by Draghmar** [comment]
And it won't unfortunately unless Mozilla will change their policy - FF blocks any extension on system pages as well as on their websites. For example try to invoke your shortcut at addons.mozilla.org

**Comment by Drive4ik** [comment]
@Draghmar you right. but now wee have new Wexextension api
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/commands
and i will soon refactor my code to use it's (this commands works in all pages)
