### ISSUE TITLE
Switching windows not working

### ISSUE THREAD

**Issue by systemovich** [Drive4ik/simple-tab-groups#162]
When clicking on the tab groups button, then clicking on the desired group, the current window loses focus, but the window containing the desired group does not come to the foreground. This is if the two windows are on the same monitor.

**Operating System:** Windows 10 Pro
**Firefox version**: 60.0.1

**Comment by Drive4ik** [comment]
Please update addon and Firefox to latest version and retest
STG 3.0 and FF 61
