### ISSUE TITLE
Exit strategy

### ISSUE THREAD

**Issue by victornoel** [Drive4ik/simple-tab-groups#164]
I wanted to stop using simple tab group and I found myself facing two problems:
1. if you just remove the extension, you loose all the tabs not opened in the current group
2. for tabs in the current group but not loaded, there is some kind of strange URL in the location bar that only works with STB

For 1. I think there should be at least a way to transfer all groups to one, or to transfer tabs to another group when closing a group.

For 2. At least disabling the quick tab loading option should put the tab in the unloaded state already existing in firefox (if it is enabled) because I had 30 existing youtube tabs and they all started to load when I unchecked the option.

The best would be for STB to have an exit strategy to do all of the above at once.

**Comment by Drive4ik** [comment]
Hi. I implement hide tabs api in STG 3.0. This version don't create urls like "moz-extension"
FF 61
