### ISSUE TITLE
What does "container" mean?

### ISSUE THREAD

**Issue by grandsong** [Drive4ik/simple-tab-groups#166]
I was improving translation and then I met "Catch and move tabs with **containers** to this group (only for web urls, empty tabs are not supported)"
Looks like some kind of categorization...
I never really understand or use this feature.
**What is it for? How does it work?**

BTW, this feature takes a lot of space in the panel of tab group settings.
I have to scroll down before I can see and click the Save button.
Could I hide this feature?

**Comment by Drive4ik** [comment]
Hi!

> What is it for? How does it work?

https://support.mozilla.org/en-US/kb/containers

> Could I hide this feature?

No. This functionality is used by other users.

**Comment by grandsong** [comment]
I mean, could there be an option in the global settings to hide theses categories so that the Save button can be seen without scrolling down?
Or any other solution for the same result?
