### ISSUE TITLE
[Bug?] Always opens an empty tab in new window

### ISSUE THREAD

**Issue by grandsong** [Drive4ik/simple-tab-groups#167]
I've enabled [Individual window for each group]
When I click a tab group in the group list, a new window is opened for that group.
However, besides the tabs of that group, there is always an extra empty tab.

Is this a bug? Or a limitation of Firebug itself?

**Comment by Drive4ik** [comment]
Hi! This is not a bug but a flaw, soon there will be a version with the ability to hide tabs and in this option there will be no need (it will be deleted).

**Comment by grandsong** [comment]
Great!
