### ISSUE TITLE
Right-click - Move tab to group:  tab not found 

### ISSUE THREAD

**Issue by Jaxx005** [Drive4ik/simple-tab-groups#168]
First step:  "Right-click tab \ Simple Tab Groups \ Move tab to group \ Create New Group..."
This create a new tab group "Group14"

I then renamed this group to "CCN2"

Then, moving other tabs there using:
"Right-click tab \ Simple Tab Groups \ Move tab to group \ Group14  <<<< !!!???
Note that the OLD name (Group14) showed here.

But then the Taskbar Note appears stating tab was moved to "CCN2"  (new, correct name).

Continued this, moving several tabs...

Then got "What's wrong... see log..." message at taskbar

Created LOG - changed extension to .TXT to allow attachment here.
[STG-error-logs.json.txt](https://github.com/Drive4ik/simple-tab-groups/files/2055436/STG-error-logs.json.txt)

The problem seems to be that the tab group rename was carried out, but the right-click code was not 'informed' so to speak (pointing to same group, just with old name?).  After a certain sequence or time, this no longer worked and the error "tab group not found" log entry appears?

Or, it could have been that the first tab did not actually fully complete it's move, and then a re-attempt on the still visible tab failed (i.e.with  tab not found)?

error moveTabToGroup: tab not found

Hope this helps debugging.

**Comment by Drive4ik** [comment]
Many thanks for the found bug, I will deal with it
