### ISSUE TITLE
Show the name of the selected tab group

### ISSUE THREAD

**Issue by xfr-dev** [Drive4ik/simple-tab-groups#169]
Hi,
Is-it possible to provide a way/an option to be able to show the current selected tab group ? For example : near the button or perhaps using another droppable widget?

Thanks, regards,

xfr

**Comment by Keith94** [comment]
It's not possible due to limitation - see #10.

**Comment by Drive4ik** [comment]
@Keith94 yes, but only this option is possible, and I do not consider it appropriate
![screenshot_2](https://user-images.githubusercontent.com/7843031/40991067-4f521b22-68fb-11e8-8af4-a72fd689a126.png)

**Comment by Keith94** [comment]
Ah, you mean toolbar badge. I agree with you though.
