### ISSUE TITLE
Dragging a tab outside to create a new window automatically creates a new group

### ISSUE THREAD

**Issue by llorllale** [Drive4ik/simple-tab-groups#17]
**Steps to reproduce:**
1. Open a new tab in an existing group
2. Drag the tab outside the firefox window and release. A new window will open containing just your tab.
3. Verify your list of tab groups

**Actual result:**
A new tab group will appear called "Group N" where `N` is some number.

**Expected result:**
No new tab group created. The only groups you should see in your list are the ones already explicitly created by you.

**Comment by Drive4ik** [comment]
Hey @llorllale . It was so specially done that all the windows were with the groups. If you do not want to create a new group - create a new blank window `Ctrl + N` and drag the tabs here.

**Comment by llorllale** [comment]
Hi @Drive4ik 

Sometimes the decision to move the tab to a new window is made after the tab is already open in a group.

Also, and I just checked this, the same issue occurs if you right click -> "Move to New Window": a new tab group is created.

**Comment by Drive4ik** [comment]
Hi @llorllale 

Please update addon to latest version, I added checkbox in options to disable this behavior

**Comment by Drive4ik** [comment]
Hi @llorllale 
Did it help you?

**Comment by llorllale** [comment]
Hi @Drive4ik ,

Sorry for the delay. Initially I didn't see any new option but now in `v1.8.3.2` I saw and unchecked *Create new group after attach tab to new window* and it works.

Thank you, closing.
