### ISSUE TITLE
Allow a shortcut to be made for "move tab to custom group" 

### ISSUE THREAD

**Issue by mrietveld** [Drive4ik/simple-tab-groups#170]
First off, **I LOVE THIS PLUGIN!** *Thank you* for making it! 

I often find myself with a lot of multiple tabs in my "scratch" tab group and then I realize that I actually want a different tab group for them. 

(For example, today I was looking at IoT/MQTT stuff and courses, and realized I wanted a new tab group to organize them.)  

Could we/you add a feature so that a shortcut could be assigned to moving tabs to a custom group? 

Thanks!

![screenprint-shortcuts](https://user-images.githubusercontent.com/783550/40831460-58db30a4-6589-11e8-93a6-9812f7ee48d0.png)

**Comment by Drive4ik** [comment]
Hi! I will add this functionality but it will not be soon

**Comment by Drive4ik** [comment]
Done :)
Please wait for FF63 stable and next STG release
![screenshot_1](https://user-images.githubusercontent.com/7843031/46222499-35633580-c359-11e8-8ef8-54d566c3c8d2.png)
![screenshot_2](https://user-images.githubusercontent.com/7843031/46222507-38f6bc80-c359-11e8-928b-abcb9c2ab75e.png)

**Comment by mrietveld** [comment]
Awesome! Thanks.. :D
