### ISSUE TITLE
Set default icon for new groups

### ISSUE THREAD

**Issue by Keith94** [Drive4ik/simple-tab-groups#171]
When creating a new group, the icon defaults to the one with nine squares, even if all other groups have a different icon. This results in having to set the preferred icon on each group creation. i.e.:

![2018-06-01_17-57-51](https://user-images.githubusercontent.com/5490615/40868805-a7417050-65c5-11e8-99d8-ecab950f1bdf.png)

Could STG possibly remember the last used icon and default to that for new groups, or can there be an option to choose the  default icon globally?

**Comment by Keith94** [comment]
Thanks for adding this new feature :-)

**Comment by Drive4ik** [comment]
You're welcome)
