### ISSUE TITLE
"Found hidden unsyncronized tabs"

### ISSUE THREAD

**Issue by Keith94** [Drive4ik/simple-tab-groups#172]
Hi. What does this message mean exactly? How can I prevent tabs from becoming "unsyncronized"? It frequently happens after browser crashes or is restarted.

![2018-06-01_18-25-48](https://user-images.githubusercontent.com/5490615/40869048-56da5146-65c9-11e8-8fa6-aa019e802b69.png)

**Comment by Keith94** [comment]
I see. I'm looking forward to whatever idea you have! :)

**Comment by Drive4ik** [comment]
If you work normally with the browser and do not turn off the extension, then this should not happen. In any case, this can be when after searching for tabs, tabs have been found which do not belong to any of the groups. For example, you turned off the addon and opened 2 new tabs google and wikipedia and then turned on the addon. These 2 tabs will appear as not synchronized and they will not belong to any of the groups, even the current one, so you do not decide what to do with them yourself

**Comment by Drive4ik** [comment]
Sorry for google translator))
