### ISSUE TITLE
Spanning multiple windows

### ISSUE THREAD

**Issue by grahamperrin** [Drive4ik/simple-tab-groups#174]
With this as an example: 

![2018-06-07 21 06 02](https://user-images.githubusercontent.com/192271/41123711-79cb2d2e-6a97-11e8-8daa-de52b0e069b6.png)

– as far as I can tell: 

- it's not possible to move the _GitHub_ tab (in the second window) from the _thinkbubble_ group to the _groupish_ group without losing its second window context

… true?

**Comment by Drive4ik** [comment]
Can you retest this behavior in STG 3.0 and FF 61?
If this bug not replicate - close issue. Thanks
