### ISSUE TITLE
Unexpected disappearance after a move from one group to another

### ISSUE THREAD

**Issue by grahamperrin** [Drive4ik/simple-tab-groups#175]
With this as an example: 

![2018-06-07 21 06 02](https://user-images.githubusercontent.com/192271/41123711-79cb2d2e-6a97-11e8-8daa-de52b0e069b6.png)

– I subsequently used the context menu for the _GitHub_ tab (in the second window) to move the tab from the _thinkbubble_ group to the _groupish_ group. 

The tab disappeared: 

![2018-06-07 21 09 34](https://user-images.githubusercontent.com/192271/41126934-17531800-6aa1-11e8-9147-910e7271df79.png)

– and was found in history: 

![2018-06-07 21 10 44](https://user-images.githubusercontent.com/192271/41126940-1ea660bc-6aa1-11e8-919f-100704aa1a14.png)

----

I imagined a conflict with other tab groups-oriented extensions so I disabled those extensions. The issue was reproducible: 

[2018-06-07 21:17.mp4.zip](https://github.com/Drive4ik/simple-tab-groups/files/2082103/2018-06-07.21.17.mp4.zip)

In that example, the disappeared tab is not amongst recently closed tabs. 

----

I made the issue reproducible in a different profile. In this case the disappeared tab **was** found as the most recently closed tabs. 

```text
$ pkg info firefox | grep Version
Version        : 60.0.1_3,1
$ date ; uname -v
Thu  7 Jun 2018 21:20:48 BST
FreeBSD 12.0-CURRENT #3 r334382: Thu May 31 01:37:12 BST 2018     root@momh167-gjp4-hpelitebook8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC 
```

**Comment by Drive4ik** [comment]
Hi. Can you retest this bug in latest STG 3.0 anf FF 61?
