### ISSUE TITLE
Close 'Manage Groups' tab after opening group

### ISSUE THREAD

**Issue by keptan** [Drive4ik/simple-tab-groups#176]
After using a shortcut to open the 'Manage Groups' page, and opening a different tab group the Manage Groups page remains in the old group when I come back later.

I think there should be an option to automatically close it after using it. 

Edit: Using the 'Manage Groups' hotkey in a different tab group brings me back to the original group if the tab remains open

**Comment by Drive4ik** [comment]
This feature will available in next version
