### ISSUE TITLE
Group switching still a bit too slow

### ISSUE THREAD

**Issue by werner-lehmann** [Drive4ik/simple-tab-groups#177]
On a fresh Firefox 60.0.2 install with a new profile I was checking out Tab Group replace extensions. This one stood out due to its refined UI. Unfortunately fast group switching does not work for me, or maybe it is not as fast as I would expect. I have enabled the webextension pref. Also disabled favicon options as recommended for extra fast switching. 

Switching groups with ~30 tabs works instantly on other extensions: Conex (by kesselborn), Panoramic View (by Photodiode). When doing this with Simple Tab Groups, there is a noticable visual rearrangement of tabs and several tabs do have a "loading" icon for a few seconds. The instant switch is what I like to have. And those tabs should not be loading content again - if that is really happening. Reloading the current tab of the switched-to group seems to be intended but personally I would avoid that, too. Reloading a tab manually is easy to do if needed.

Is there anything else which needs to be configured? Or maybe the tab showing / hiding code has a performance issue on this extension? Is anyone else seeing this?

**Comment by Drive4ik** [comment]
You need to update STG to v3.0 and update Firefox to v61
I implement hide tabs api
