### ISSUE TITLE
Feature request: search for group

### ISSUE THREAD

**Issue by mmewen** [Drive4ik/simple-tab-groups#178]
It would be great if the search field in the pop-up window could also be used to search group names.

I like to use the keyboard only, it would make group switch faster: `F8`, *type start of group name*, `Enter` (it would also need the first search result to be selected, `arrow down` is currently needed)

Thanks a lot for your work!

**Comment by Drive4ik** [comment]
Hi! Current search logic also find tabs and groups by title and web url.

**Comment by Drive4ik** [comment]
Done, this fix will available in next release
