### ISSUE TITLE
Enhancement request: a hotkey to display the popup and toggle between groups

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#179]
Hi
I miss one keyboard shortcut to toggle between group names very fast in order to select the right one by its name without moving the hand too much nor the mouse. Like ALT+TAB on Windows would do for windows, but without the tab previews to make it super fast.

Pressing the hotkeys would open a popup with group names and icons (possibly the number of tabs in each group), but nothing else to avoid latency. Also it would be displayed in the middle of the FF window rather than near to the button.

Pressing this shortcut again would just move from a group name to the other in the popup, until the right one is chosen. 

Then only FF would display the group itself.

The Panorama pannel is too big and has too much latency to do that imho. Same latency for the current menu.

I hope you will consider this at some point in the dev.

Thank you :)

**Comment by Drive4ik** [comment]
I understand that this can be convenient, but it completely repeats the functional popup window, this is a great functionality. And embedding it in every web page can significantly slow it down, and with the keys there will be conflicts. so this will not be realized, sorry.
You can configure keyboard shortcuts for opening a pop-up window, there is still search, navigation up, down, left, right (will open the group)
