### ISSUE TITLE
Tab order is lost when switching tab groups

### ISSUE THREAD

**Issue by llorllale** [Drive4ik/simple-tab-groups#18]
I think this one is important - users that have this plugin are likely to be the sort of people that like to keep things orderly.

**Steps to reproduce:**
1. Create a new group with tabs A, B, and C, in that order.
2. Create another group.
3. Switch back to the first group.

**Actual result:**
The tabs will most likely not be displayed in the same order you left them (A, B, C)

**Expected result:**
The tabs should appear in the same order you *left* them (A, B, C)

**Comment by Drive4ik** [comment]
Hi @llorllale !

Most likely you has conflict with another addon. Please see issue #7 
If you have the same addon or similar - sorry, I can not help you.

Best regards

**Comment by llorllale** [comment]
You are right. I disabled an "open new tab next to current one" plugin and issue is gone.

Thanks, closing.

**Comment by Drive4ik** [comment]
Hi! I fix this bug in v2.5.3. Please, update to it and retest.

**Comment by llorllale** [comment]
@Drive4ik i don't understand; this was not an issue with your plugin, see above

**Comment by Drive4ik** [comment]
I know, but I have the same issue sometimes and when I fix it, I remembered this issue, test and see - its fixed too)

**Comment by Drive4ik** [comment]
@llorllale Can you confirm that the problem has disappeared?

**Comment by llorllale** [comment]
@Drive4ik what are the steps to test?

**Comment by Drive4ik** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/18#issue-279868748

**Comment by llorllale** [comment]
@Drive4ik like i said, i stopped having this issue long ago after i disabled that other plugin

**Comment by Drive4ik** [comment]
Ok

**Comment by vrurg** [comment]
The fix is incomplete. Open Tabs Next to Current plugin still breaks ordering upon group switching.
