### ISSUE TITLE
not switching groups please help!

### ISSUE THREAD

**Issue by samboa86** [Drive4ik/simple-tab-groups#180]
I installed this and updated FF from old. I got all my tabs back and groups, but it wont actually load them! I dont know how to switch groups. if I click on a tab from a different group, it just moves it to my current group, it doesnt show the other group and all those tabs. So essentially it is useless right now besides having all my tabs but no groups.
please help!! thanks

**Comment by samboa86** [comment]
OK I literally just figured out, double click on the drop down (cant do it in the grid view), but now the problem is it erases your current tabs, and loads the others, meaning it erases your tab history (cant hit back button). 
This is not good. Theres no point of tab groups if history is not saved, might as well only have current group and a text file with links of other tabs.

**Comment by Drive4ik** [comment]
Hi. You can update addon to latest version (STG 3.0) and in it tabs not reload after group switch
