### ISSUE TITLE
Closed btowser, opened browser, and the currently selected group is replaced by the default New page

### ISSUE THREAD

**Issue by m60freeman** [Drive4ik/simple-tab-groups#181]
I lost 80 tabs. My other groups are fine, just the one that was selected when the browser was closed is gone.

Do I really have to manually back up before every time I close my browser to avoid losing data?

Is there any way to get these tabs back? This group was imported from an old .sessions file. How can I re-import just one group from that without losing all the changes I've made since then to the other groups?

**Comment by Drive4ik** [comment]
You need to update FF to v61 and addon to latest version (STG 3.0)
And this issue don't happens again

**Comment by m60freeman** [comment]
Is there any way to get these tabs back? This group was imported from an old .sessions file. How can I re-import just one group from that without losing all the changes I've made since then to the other groups?

**Comment by Drive4ik** [comment]
If you mean Quicksaver's "Tab Groups" backup - you can import again these backup and then remove not needed groups. Groups from this backup will added as new to current groups list. 
But if you mean STG backup you can manually copy urls from backup and open tab with its url
If you restore STG backup - your current groups and tabs will erase.
