### ISSUE TITLE
Tabs are duplicated when switching groups

### ISSUE THREAD

**Issue by theSoenke** [Drive4ik/simple-tab-groups#182]
When switching between tab groups the tabs are sometimes duplicated and the group selected contains all tabs of both groups. This has been happening multiple times. I have not been able yet to reliable reproduce this

**Comment by m60freeman** [comment]
I have also seen this but can't reliably reproduce it.

**Comment by Drive4ik** [comment]
Hi you need click to these button after step 5
![default](https://user-images.githubusercontent.com/7843031/41982271-aceb68b2-7a33-11e8-9e07-61736a6f31b9.png)

Please, update addon to latest version (STG 3.0, not experimental) and FF must be v61

**Comment by theSoenke** [comment]
Thanks. With the latest non experimental version this seems to be resolved
