### ISSUE TITLE
Respect multiselected status of tabs on Firefox 62 and later

### ISSUE THREAD

**Issue by Keith94** [Drive4ik/simple-tab-groups#188]
Perhaps it is possible to detect if tabs are multiselected and perform various actions with them (move to group, etc.).

[Bug 1464862 - Expose multiselected status to "tabs.Tab.highlighted", and allow to change it via "browser.tabs.highlight()"](https://bugzilla.mozilla.org/show_bug.cgi?id=1464862)

[Bug 1458007 - Allow multiselect operations on tabs](https://bugzilla.mozilla.org/show_bug.cgi?id=1458007)

**Comment by Drive4ik** [comment]
Hi! May be in the future, but not now.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/highlight#Browser_compatibility

**Comment by Drive4ik** [comment]
I already made support for multi-select tabs, wait for the release of Firefox 63 and the new version of STG :)
