### ISSUE TITLE
General spelling & grammar issue

### ISSUE THREAD

**Issue by misterHippo** [Drive4ik/simple-tab-groups#19]
This is just a generic spot where users can help with grammar, spelling & typos.

Options Section as per 8th Dec 2017
![tabgroups](https://user-images.githubusercontent.com/605912/33746021-7dbd6f18-dc0e-11e7-99e6-d765bea8c7a0.png)

Might be better to be: 
- Close popup after changing group
  - Open group after changing to it (if the popup isn't closed)
- Show colored group circle in search tab
- Show url tooltip when hovering over tab
- Show notification when tab is moved to another group
- Create new group if tab is moved to new window
- Enable keyboard shortcuts for next and previous group. i.e. Ctrl + Shift + < and Ctrl + Shift + >
- Enable keyboard shortcuts for switch to tab. i.e. Ctrl + Shift + [1-9]

[ Import settings from old "Tab Groups" add-on ]

**Comment by misterHippo** [comment]
As of 8th Dec 2017, the Generic info text for the add-on says: 

Create, modify and quick change tab groups. 
Inspired by the "Tab Groups" app :)At the moment, the Firefox WebExtensions API does not support hiding tabs, only closing ... I also do not like it, but I have no choice.
When this feature is added, I will make it support.

    Full rewrite addon without any third-party libraries
    New Design (fork old addon design "Tab Groups")
    Group colored icon
    Added the ability to import the backup groups of the old plug-in "Tab Groups"
    Added support of "Firefox Multi-Account Containers"
    Fully support multi windows
    Save last active tab after change group
    Show current used group in addon icon (see screenshot)
    Add sorting functional "Move group up/down" in group context menu
    Specially NOT supported Private (Incognito) Mode
    Added support switch groups thought keys:
    MacCtrl+Shift+Coma (MacCtrl+Shift+[<,]) - load prev group
    MacCtrl+Shift+Period (MacCtrl+Shift+[>.]) - load next group
    MacCtrl+Shift+[1-9] - load group by index
    Close tab by middle mouse click
    Support very simple switching between groups and tabs using the up, down, right and left keys, and in search mode too


More Settings ;)

Notice
You have Group 1 and Group 2. Group 1 loaded in window 1. Open Group 2 in new window (context menu on Group 2) and then in window 1 (Group 1) try to switch to Group 2, whitch loaded in another window.
You can load Youtube or music players in other windows (groups) and switch between them without closing tabs :)
Profit))

It may be better to consider changing it to be:

Create, modify and quickly change tab groups. 
Inspired by the old add-on "Tab Groups" :) 
(Note: At the moment, the Firefox WebExtensions API does not support hiding tabs, only closing ... I don't like it, but I have no choice. Assuming Firefox adds this feature, this add-on will support it.)

Current list of functionality / development notes:
    Full rewrite of add-on without any third-party libraries
    New Design (fork old add-on design "Tab Groups")
    Added colored group icon
    Added the ability to import the backup groups of the old plug-in "Tab Groups"
    Added support of "Firefox Multi-Account Containers"
    Now fully supports multiple windows
    Saves last active tab after change group
    Show currently used group in addon icon (see screenshot)
    Add sorting functionality - "Move group up/down" in group context menu
    Specially NOT supported Private (Incognito) Mode
    Added support to quick-switch groups using keys:
       Ctrl+Shift+Coma (MacCtrl+Shift+[<,]) - load prev group
       Ctrl+Shift+Period (MacCtrl+Shift+[>.]) - load next group
       Ctrl+Shift+[1-9] - load group by index
    Added close tab by middle mouse click
    Added simple switching between groups and tabs in search mode using the up, down, right and left keys
    Added more settings :)

Now, I don't actually fully understand the next section

Notice
You have Group 1 and Group 2. Group 1 loaded in window 1. Open Group 2 in new window (context menu on Group 2) and then in window 1 (Group 1) try to switch to Group 2, whitch loaded in another window.
You can load Youtube or music players in other windows (groups) and switch between them without closing tabs :)
Profit))

Did you want help rewriting this at all?

**Comment by Drive4ik** [comment]
@misterHippo 
Thanks for helping to improve my language.
My English is not very good, but I'm learning.

I will fix langs in next release :)

About the note:
You can switching between groups which loaded in different windows only with the help of a addon pop-up window.
Or
Group 1 is loaded into window 1
Group 2 is loaded into window 2
Try to load Group 2 or any tab from Group 2 into window 1 only with the help of a addon pop-up window :)

**Comment by misterHippo** [comment]
G'day @Drive4ik :)

That's ok :) no problem. English isn't easy languages to learn. It has a whole bunch of rules around words and sentences, and then doesn't follow them every time. (Good luck!) Besides all that, you're English is good enough, this note we're discussing is the first time that I've had any trouble understanding you. So that's great. :)

I should point out too, that I used 'American English' to write the above. It isn't technically 'English', but it's close enough. (You had already used 'color' in your wording, so I just went with it.) :)

Now, the notice... 
**Questions:**
- Is a description of the Simple Tab Groups, or if this is referring to another add-on for Firefox that isn't Simple Tab Groups?
- Are you stating that the Simple Tab Groups cannot handle switching between groups that are open in two separate windows? (ie: TabGroup1 on Window A, TabGroup2 on Window B)
- Or are you saying that Window A cannot reference _any_ Tab Groups from Window B?

**Comment by Drive4ik** [comment]
Hi @misterHippo !
Please see gif
http://rgho.st/7zPH8mXhL

I hope I here clearly showed that I meant :)

**Comment by misterHippo** [comment]
Hi @Drive4ik.

Oh, that's cool :)  I like that. Ok, the generic description of what you showed in that gif was that:
- You can switch between tab groups in other windows
- You can switch to specific tabs in groups in other windows
... for each of those, actions the containing window will be brought to focus (or 'the front').

So we could write it like this:
'Simple Tab Groups works across browser instances/windows too. If you select a group in another window, the selected window will jump to the foreground with the chosen group selected. You can even select the specific tab within that group in background browser windows.

This allows for easy switching between active and pre-loaded tabs across multiple browser windows'

Does that have all the information / description you wish to include?

**Comment by Drive4ik** [comment]
Hi @misterHippo 

I updated addon description with your latest text))

Thanks for helping 👍
