### ISSUE TITLE
Slow page load since FF61.0 and above.

### ISSUE THREAD

**Issue by Boymann** [Drive4ik/simple-tab-groups#190]
Pages load slowly, and buttons are unresponsive. Only have uBlock Origin and Simple Tab Groups installed. Turning off Simple tab groups solves the issue.

**Comment by Drive4ik** [comment]
It's strange, but this addon can not affect the speed of loading pages. What version of STG you are using?

**Comment by Boymann** [comment]
I was using 3.0.7

**Comment by Drive4ik** [comment]
How many tabs are you trying to download at the same time?
May not have enough RAM?
Have you tried to restart the browser?

**Comment by Boymann** [comment]
Restarted many times, went from Beta to release, 16gigs of ram currently but I can do 32, because I have 16 gigs unused not plugged in, and around 130 tabs

**Comment by Drive4ik** [comment]
Ok. Can you record screen with this issue and some test tabs, when STG enable and when it's disable? 

You can use this app or any way other app
https://www.screentogif.com/

P.S. latest version of STG now is 3.0.8
