### ISSUE TITLE
Option to open group in separate window?

### ISSUE THREAD

**Issue by rubcap** [Drive4ik/simple-tab-groups#191]
Great work on the new version! I like the improved UI, color picker and hide API support!

However, I can't find the option anymore to open a group in a separate window?
I believe there was a context menu before which allowed for a group to be opened in a separate window.

Thanks in advance for your help!

**Comment by gagarine** [comment]
It's gone. Creating a new group by opening a new  windows doesn't works neither.
I guess it's either not yet implemented with the new API or not even possible.

**Comment by Drive4ik** [comment]
Hi guys. No, I have deleted this functionality since it is not convenient since the introduction of Hide tabs Api, since after closing the second window the tabs also close, and when you again press "open the group in a new window", a new window is created and all the tabs are loaded again. Easier to switch the group and tabs just seem without rebooting and loss of content.
Sorry for Google translate)

**Comment by gagarine** [comment]
@Drive4ik sometimes I need to compare things from two website... But I can drag the tab out of the group. I also used a shortcut to switch from windows of the same program (like tab for switching from program to program).

But as changing group is lot more reliable and faster with the Hide Tabs API, I think I can adapt advantageously my workflow without the need of multiple windows. It is a really great update!

**Comment by Drive4ik** [comment]
@gagarine Yes, and yet you can assign each key combination to each group, and switch between them very quickly without losing the last open tab.
eg
group 1 - Ctrl + K
group 2 - Ctrl + L
Try this!

**Comment by rubcap** [comment]
Like @gagarine , I also used "Open group in new window" to compare websites.
But I guess I can press Ctrl+N to open a new window and open the group there.
Still, the shortcut was convenient, even if it meant reloading the tabs.
No big deal. Thanks @Drive4ik !

**Comment by Drive4ik** [comment]
Well guys, if you want that, I'll return this feature.
This update will available in next release
