### ISSUE TITLE
Group settings 'save' button is not displayed 

### ISSUE THREAD

**Issue by Philip-Sutton** [Drive4ik/simple-tab-groups#192]
Hi,  I like the new build using 'hiding tabs' technology.

Unfortunately a previously solved problem has returned.  when in "group settings' the  'save' button is not displayed on my machine (Windows 10, Firefox 61.0.  See animated gif.

Philip

![no save button](https://user-images.githubusercontent.com/1549449/42092609-d51fda2e-7bec-11e8-9bcf-e05b0292c13a.gif)

**Comment by Drive4ik** [comment]
You can use key Enter to save Group settings, or try to maximize Firefox window
please see https://github.com/Drive4ik/simple-tab-groups/issues/193

**Comment by Philip-Sutton** [comment]
**Drive4ik** - You can use key Enter to save Group settings

This works!!  Thanks heaps.
