### ISSUE TITLE
Creating tab thumbnails take to much memory on group change

### ISSUE THREAD

**Issue by me21** [Drive4ik/simple-tab-groups#194]
After updating to Firefox 61 & Simple Tab Groups 3.0.7, Firefox consumes several gigabytes of RAM when I switch to previously inactive tab within the same group. Then the memory consumption is back to normal. When I switch tabs again, it repeats.
I know I may have too many tabs in one group (> 700), but still... Version 2.5.4.1 didn't have this issue.

Here's my tab groups backup:

[simple-tab-groups-backup-2018-06-28-2.zip](https://github.com/Drive4ik/simple-tab-groups/files/2150983/simple-tab-groups-backup-2018-06-28-2.zip)

**Comment by me21** [comment]
I've tracked down the setting which causes this behaviour. It's "Create tab thumbnails". If it's turned off, memory consumption is back to normal.

**Comment by Drive4ik** [comment]
Hi! Can you try to enable option "Discard tabs after hide (this will save the RAM)"? What effect does it show?

**Comment by me21** [comment]
No effect.

**Comment by gagarine** [comment]
Can we edit the title of this issue with "Creating tab thumbnails take to much memory on group change" or similar?

**Comment by Drive4ik** [comment]
@me21 Hi! It's strange because I have no such problem. What version of STG and Firefox do you use now?
This code don't create thumbnail if its already exists
https://github.com/Drive4ik/simple-tab-groups/blob/b1f70edfb6716502f9db71a071b47135b062b287/addon/src/background.js#L736-L745

**Comment by gagarine** [comment]
Just a quick idea: Thumbnail are not deleted when tab are discarded?

**Comment by Drive4ik** [comment]
No, thumbnails will not delete/remove automatically. Only if you reset it's manually:
![screenshot_1](https://user-images.githubusercontent.com/7843031/44781020-00ae6380-ab8c-11e8-8ed1-e579007ac76b.png)

or don't include it in backup file on export groups:
![screenshot_2](https://user-images.githubusercontent.com/7843031/44781091-2176b900-ab8c-11e8-95f2-9839d343ed53.png)

**Comment by liffiton** [comment]
I'm not sure if this is relevant to the original issue here, but since it's been brought up here:  I think maybe thumbnails should be deleted automatically.  I go through lots of URLs - each in its own tab - that I will never return to again, and it looks like STG ends up keeping a thumbnail of every one of them indefinitely?  I was up to a 150MB storage.js file for STG, and the browser was doing some giant disk accesses just for this data that has no value anymore.  I think it was causing excessive memory usage, too, though I didn't specifically check that before clearing the thumbnail cache.

As far as I can tell, the default behavior of these thumbnails is "grow indefinitely," consuming memory, disk space, and I/O time in ever-increasing amounts.  This is bound to cause problems.

**Comment by gagarine** [comment]
My Firefox was going slow, and clearing the thumnail file seem to fix the problem. But I can say 100% it was that.

Until https://bugzilla.mozilla.org/show_bug.cgi?id=1246693 it's fixed I think tab's thumbnail are hacky. Perhaps best to disable the features for the moment?

Some internal code is certain their to render a thumbnail, as you can use ctr-tab to switch between tab if you enable  browser.ctrlTab.previews in about:config.

**Comment by gagarine** [comment]
It seem that Panorama View create thumbnail right when the group view is displayed:
https://github.com/photodiode/panorama-view/blob/a844934a9f1d9211d8a5dc42b91547f840db7158/src/js/view.js#L36-L67

and "store" it in https://github.com/photodiode/panorama-view/blob/a844934a9f1d9211d8a5dc42b91547f840db7158/src/js/tabNodes.js#L123-L138

In simple tab group it's a different technique by using browser.tabs.captureTab(): https://github.com/Drive4ik/simple-tab-groups/blob/b927ec22a6ff06acc37e1a5600f03f2d6885358f/addon/src/background.js#L779 

browser.tabs.captureTab is slower?

**Comment by me21** [comment]
> Hi! It's strange because I have no such problem. What version of STG and Firefox do you use now?
This code don't create thumbnail if its already exists

I'm using Firefox 61.0.2 and STG 3.1. I think the problem is that I don't have any thumbnails right now, so if I enable the setting, Firefox will try to create thumbnails for every page in the group, and if there are many tabs, it will run out of available memory.

**Comment by Drive4ik** [comment]
@me21 A thumbnail is created only when the tab has become active or the url has changed or the tab has loaded.

@liffiton You are right - I fix this bug.
Wait next release

**Comment by Drive4ik** [comment]
Please retest this issue on FF62 and STG 3.1.2

**Comment by me21** [comment]
Couldn't reproduce on FF62 and STG 3.1.2.1.

**Comment by Drive4ik** [comment]
@me21 Hi! please update STG to latest version, I update this bugfix. Now all unused thumbnails will removed on FF startup

**Comment by me21** [comment]
@Drive4ik which thumbnails are considered unused?

**Comment by Drive4ik** [comment]
Unused are those whose tabs you closed (equal by url). If you closed the tab with url `https://www.google.com/` and more such url is not in any group - the thumbnail with this url is deleted.
Tabs with url for example `https://www.google.com/search?q=abc` will not be deleted

**Comment by Drive4ik** [comment]
Purification of miniatures occurs at the startup of addon
