### ISSUE TITLE
Manage groups unable to open on new windows with popup

### ISSUE THREAD

**Issue by LiCybora** [Drive4ik/simple-tab-groups#195]
Manage groups unable to open on new windows with popup, but able to open with hotkey. 

Steps to reproduce:
1. Uncheck 'Open "Manage Groups" in new tab
2. Click the pop-up and click Manage groups, but nothing happen

GIF:
![error](https://user-images.githubusercontent.com/40160522/42098485-a3f2d41e-7bed-11e8-9d84-9fea171f5bd9.gif)

Environment: Debian 9.4 gnome Desktop on VirtualBox (Cannot reproduce in macOS)
Browser version: Firefox 61.0 stable, 62.0b3

I guess I have fixed in here:
In file `Popup.vue` line 472:
```
            openManageGroups() {
                BG.openManageGroups(window.screen);
                window.close();
            },
```
Remove the `window.screen` and just call `BG.openManageGroups();` without argument, which is just like the hotkey call. I am not sure whether it is an issue of VirtualBox or Debian's gnome Desktop. I may submit PR if you need my fix, but there would be another browser issue like this:
![badfixed](https://user-images.githubusercontent.com/40160522/42098958-d9c96976-7bee-11e8-9aab-6db437263cf1.gif)

The detached window goes blank until you right click or resize it. See: https://bugzilla.mozilla.org/show_bug.cgi?id=1408446. As this is a browser bug, I have no way to solve it.

Note: You may not reproduce it on other environments, as I cannot reproduce on my macOS as well.

**Comment by Drive4ik** [comment]
Hi! Thanks for find bug, and can you retest with this code?
```javascript
BG.openManageGroups(utils.clone(window.screen));
```

**Comment by LiCybora** [comment]
> `BG.openManageGroups(utils.clone(window.screen));`

This is good. Thx!
