### ISSUE TITLE
When creating new group, prompt for title

### ISSUE THREAD

**Issue by Keith94** [Drive4ik/simple-tab-groups#196]
Makes it easier to add a title for our new group straight away.

**Comment by Drive4ik** [comment]
I've already thought about this, but this will only work in the popup window and in manage groups page

**Comment by Keith94** [comment]
So, it won't work via the toolbar button popup? That's a bummer, I guess.

**Comment by Drive4ik** [comment]
Done :)

**Comment by Keith94** [comment]
Thank you!
