### ISSUE TITLE
No button on toolbar

### ISSUE THREAD

**Issue by montoner0** [Drive4ik/simple-tab-groups#197]
I've installed latest Simple Tab Group (3.0.7) on latest Firefox (61.0) and I can't find the button of the addon anywhere. It's not on toolbar or any other place. The addon itself is shown in addons list and I can configure it, but cant't use.

**Comment by montoner0** [comment]
![2018-07-01 14_31_30-customize firefox](https://user-images.githubusercontent.com/13542804/42134145-7872c6f8-7d3e-11e8-8278-30153f4411da.png)

**Comment by Drive4ik** [comment]
Hi! By default position icon adds there:
![default](https://user-images.githubusercontent.com/7843031/42261030-5d6b6832-7f6f-11e8-8182-9c2fd70ae70f.png)
Can you find it there? If not try to turn off the extension and turn it on again

**Comment by montoner0** [comment]
And what if the line with tabs is hidden? I'm using Tree Style Tab extension.

**Comment by Drive4ik** [comment]
You have to enable default tabs line, go to "Customize" and move this icon where do you want, and after that hide tabs line
![default](https://user-images.githubusercontent.com/7843031/42307995-f196210a-803c-11e8-9423-f82f335dda79.png)

**Comment by amfleurke** [comment]
I'm using Firefox 125 on Ubuntu 22.04. I have the tabs line visible, but the Icon is not there. On customize, I cannot find the icon either. I tried disabling all other extensions and restart, use light theme, but that didn't help. The extension is installed and working for the rest.

I can show it as sidebar, but where is the icon?

**Comment by achernyakevich-sc** [comment]
> I can show it as sidebar, but where is the icon?

@amfleurke This issue is not correct place for raising your issue. :)

See #1109. As well there is a pull request that fix it but it just waits approving/merging and including to the next release.

**Comment by achernyakevich-sc** [comment]
@amfleurke I hope screenshot below will help you.

![image](https://github.com/Drive4ik/simple-tab-groups/assets/24388336/04cd8534-070c-47f7-be3f-3e04196f1701)

**Comment by amfleurke** [comment]
AH! under 'extensions'! Perfect! Thank you a lot! Now I have it!
