### ISSUE TITLE
New version broke tab groups

### ISSUE THREAD

**Issue by avataroftime** [Drive4ik/simple-tab-groups#198]
Hi, 

I am unsure what version I was on, but STG just upgraded on me. During the process, it flicked up a dialog about permissions (which after reading, I said yes), and then proceeded to have issue with the icon (it didn't seem to load properly). So I rebooted FF (61.0 64bit), and it started to load, at which point STG loaded, it flicked to another tab group and then said something about hidden tabs.

When I changed back to my "main" tab group, it starts to load, and then seems to load some (I am guessing the first 50 odd - out of ~200) of the tabs - and each of the tab's previous pages in a new tab. At which point, the rest of my tabs seem to be left unattached (listed at the bottom of STG's menu).

I tried to downgrade the STG addon (I could only see version 2.5.4.1 around), but it doesn't seem to like the data is uses anymore (I am guessing a data format change between versions). 

So I am now stuck where I cannot access by tab groups, but at least my normal FF session is working and I can see my current tabs (and not all of their previous history in additional tabs).

Any thoughts?

Thanks

AoT

**Comment by Drive4ik** [comment]
Hi guys! Can you disable all other extensions and leave only the Simple Tab Groups and try to repeat the problem? And if this problem does not repeat, include extensions one at a time and test again. I have a suspicion that STG is incompatible with some other extension. Thanks.

**Comment by neomodern** [comment]
I found out it was a conflict with Panorama View, thanks for the help!

**Comment by avataroftime** [comment]
So, I just turned it back on again, and made sure that it was the latest version. And after a restart, it seems to be working again. So what ever changes have happened since 3.0.7, and the latest update to FF (61 to 61.0.1), seems to have resolved the issue.

Thanks for the help.

**Comment by Drive4ik** [comment]
Well, if you no longer have problems - please close the ticket
