### ISSUE TITLE
Discard tab with a delay

### ISSUE THREAD

**Issue by gagarine** [Drive4ik/simple-tab-groups#201]
The option "Discard tabs after hide (this will save the RAM)" is pretty usefull for peoples having a lot of tab. Yet I find myself switching between a couple of my groups quiet often and some I almost never use.

Discarding tab after a delay will avoid most reload and still save RAM and save CPU.

The base delay can be somethings small like 5min but the delay should be longer if you use the group regularly in the past hours.

**Comment by Keith94** [comment]
Did you try something like [Dormancy](https://addons.mozilla.org/en-US/firefox/addon/dormancy/)? It is somewhat related to what you want.

**Comment by gagarine** [comment]
@Keith94 I'm trying right now https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/ . I didn't know about Dormancy, I will check it out. Thanks

**Comment by gagarine** [comment]
Just to report that auto tab discard work fine and have a bit more options that dormancy (like never but pin tab in sleep, wait for a number of open tab before starting to put old one is sleep).

**Comment by Drive4ik** [comment]
Fixed by @Keith94 :)

**Comment by 3v1n0** [comment]
Great to hear, I've been looking for some option like that in STG (maybe it could mention to use other addons to have more control on the option instead) as I was already using auto-tab-discard but I was wondering if it worked with STG.
