### ISSUE TITLE
Tab Groups won't finish loading

### ISSUE THREAD

**Issue by Froghut** [Drive4ik/simple-tab-groups#203]
Since some update when I start FF I get a [notification from Tab Groups](http://screenshots.abomb.de/2018-07-04_19-09-49.png) and the toolbar icon stays in it's loading state (Tooltip: Waiting for all tabs to load, Please wait...)

**Comment by Drive4ik** [comment]
Fixed

**Comment by Drive4ik** [comment]
This fix will available in next release, please wait for it
