### ISSUE TITLE
Popup fails to fully show when extension icon inside overflow

### ISSUE THREAD

**Issue by LiCybora** [Drive4ik/simple-tab-groups#206]
**Describe the bug**
When addon icon is inside overflow, part of popup is hidden.

**To Reproduce**
1. Place addon icon into overflow (the hidden menu)
2. Open popup, either using hotkey or click the hidden menu and then STG
3. Part of popup cannot be shown like the screenshots below.

**Expected behavior**
It is expected to see the popup fit the size and shown fully.

**Screenshots**
![image](https://user-images.githubusercontent.com/40160522/42436395-5ef9f1f2-838c-11e8-9829-1d32dbb2be16.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.5
 - Version: 3.0.9
 - Firefox Version: 61.0.1 Stable/62.0b6 

**Additional context**
Seems hidden menu limit the exact width of popup. Maybe consider use of `auto` or `100%` for max-width?

**Comment by LiCybora** [comment]
@Drive4ik eh...forgot the screenshot after commit, my bad. The commit should be good.

![image](https://user-images.githubusercontent.com/40160522/42460437-7203f5c4-83d0-11e8-85db-fac5d21e3776.png)

**Comment by Drive4ik** [comment]
Done :)
