### ISSUE TITLE
No group in popup menu even if they are present in group managment window

### ISSUE THREAD

**Issue by Draghmar** [Drive4ik/simple-tab-groups#207]
**Describe the bug**
For some reason after update to 3.0.8 groups disappeared from popup menu. But they still available in grid view. Screenshots shows exactly what the problem is.

**To Reproduce**
Not sure - hit the popup button?

**Expected behavior**
I should see the list of all groups.

**Screenshots**
![stg-err-nogroups](https://user-images.githubusercontent.com/275348/42565186-1078db38-8503-11e8-95f2-f82449138487.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.9

**Additional context**
The screenshot shows only small portion of my groups.

**Comment by Drive4ik** [comment]
Hi! Can you do that:
- open "Manage Groups" in tab. You can see url like this
`moz-extension://9816af84-d451-453b-8cc5-b23600d10152/manage/manage.html`
and edit url to
`moz-extension://9816af84-d451-453b-8cc5-b23600d10152/popup/popup.html`
- press enter (go to `....popup/popup.html` page)
- press F12 and click on "Console"  button
![screenshot_2](https://user-images.githubusercontent.com/7843031/42641647-a3df73dc-85fd-11e8-96ff-05892ca6a491.png)
- make console screenshot. If its empty, press F5

like this
![screenshot_3](https://user-images.githubusercontent.com/7843031/42641879-4038c440-85fe-11e8-9ad6-e80ca141120f.png)


Thanks

**Comment by Draghmar** [comment]
The console is empty. No error, no message.

**Comment by Draghmar** [comment]
Ok, it's weird but all of sudden all the groups appeared again. And what's even more interesting right after launching FF it didn't work but after some time it started. I didn't do anything interesting in the meantime so I have no idea why it fixed itself.

**Comment by Drive4ik** [comment]
I found this bug and fix it. Please wait for next release
