### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by smorganl** [Drive4ik/simple-tab-groups#208]
Every time when I start Firefox I get the following message box from STG:
  **Error: not found any normal not private/incognito/popup windows. Addon stopped working. Please, restart browser.**
and STG never locks in.
If I disable the reenable STG all seems to work properly. I do get the message from Firefox that some tabs are hidden and do I want to keep them hidden. First time I click on the STG icon I get a notice that:
  **Found hidden unsynchronized tabs. Click on tab to show it into current group/window or:
  Move all of these tabs into current group/window
  Create new group with all of these tabs
  Close all of these tabs**
followed by some tab(s) that is hidden.

This problem has just started in the last week or so and is machine specific (I have another machine that seems to work just fine.

**Desktop (please complete the following information):**
 - OS: Windows 7 Professional

**Comment by smorganl** [comment]
21 days later, I am still having this issue and have seen no response or comment about it. Am I the only one having this problem - on multiple computers in multiple locations? Or am I just doing something wrong here? As I have figured a workaround - the disable/ reenable thing - it is not killing me, but it is quite annoying to have to do this every time I start Firefox.

**Comment by Drive4ik** [comment]
Hi! I don't know why this happend, but I know - this is Firefox bug. I made a small fix of this problem, but how can I see - if the problem you are having, then even he could not help. Maybe Firefox DEV team will fix it in future versions.

Ps. You can click on reload add-on button:
![screenshot_1](https://user-images.githubusercontent.com/7843031/43842032-2184d568-9b2d-11e8-996c-6e02c8bba005.png)

**Comment by smorganl** [comment]
Just an FYI: I can't get to the manage groups until after I go through the disable then reenable STG in the Add-ons section. STG just spins and never syncs.

**Comment by Drive4ik** [comment]
STG icons will rotate until the browser says that there are tabs that are not yet fully loaded at the moment.

**Comment by Drive4ik** [comment]
https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/background.js#L1956-L1976

**Comment by smorganl** [comment]
I have left the start go for a couple of hours and the STG never stops spinning.

I am not quite sure what I am supposed to do with the code you pointed to.

**Comment by Drive4ik** [comment]
Hi! You tried to turn off the addon and turn it on again. Does this give any result?

**Comment by Drive4ik** [comment]
Do you have any results? I also wrote to the post something like "STG just spins and never syncs.". We solved the problem by reinstalling/updating the browser, saving the STG data folder in advance like this:
1. about:support
1. click on "Open profile folder" button
1. go to `browser-extension-data\simple-tab-groups@drive4ik`
1. backup/copy this folder to other place
1. reinstall browser
1. restore folder from backup

**Comment by SebCanet** [comment]
I don't want to reinstall my browser! Too many data to retrieve...
When logo turns forever, I just reinstall extension and everything's fine. But I have to do it at each Firefox restart.

**Comment by Drive4ik** [comment]
@SebCanet Ok, tell me please, what version STG and Firefox you are using?

**Comment by SebCanet** [comment]
FF 61.0.2 x64
Simple Tab Groups 3.1

**Comment by Drive4ik** [comment]
@SebCanet Hi! Do you replicate this issue on FF 62 and STG 3.1.2 ?

**Comment by SebCanet** [comment]
I just tried an it seems ok..

**Comment by Drive4ik** [comment]
@smorganl Have you tested this bug on Firefox 63 and STG 3.3.2?

**Comment by Drive4ik** [comment]
@SebCanet Have you tested this bug on Firefox 63 and STG 3.3.2?

**Comment by helkav** [comment]
I get this issue too. I wonder if it's related to private browsing mode? I only seem to get it in a private browser and I notice multi-account conta
![simple_tab_groups_error](https://user-images.githubusercontent.com/21120026/51864711-602bbd80-233c-11e9-9689-9eb545c865b6.jpg)
iners are disabled although I don't know why that would be.

**Comment by Drive4ik** [comment]
@helkav Simple Tab Groups addon not working in private/incognito windows. So if you has only one window and it's incognito - addon show this message and stop working

**Comment by helkav** [comment]
sorry I'm not sure I follow. are you saying that it should not/will not work in private windows. tbh I don't follow the reasoning behind this...would still be useful to have groups within a private window

**Comment by MiauzGenau** [comment]
I got this issue in normal (not incognito) window. 
STG 4.0,  Firefox 68.0.1 (64-Bit).
All my tabs are in one window.

**Comment by hamselvdk** [comment]
I just started getting this message "no support for incognito mode, please disable incognito mode for addon" - And I am not running in private mode .. can any  tell me what is going on?

**Comment by Astromis** [comment]
Recently I ran into the same problem and yes it's the problem of browser (Firefox in my case), that by "itself' decided to allow all extensions working in incognito mode. It can be seen in addods list. For example, 
![image](https://user-images.githubusercontent.com/30126032/62616138-7cc23700-b917-11e9-9beb-b333c9169290.png)
The right purple icon indicates about that.
So, to resolve the problem, you just need to disallow STG working in incognito mode. To do this, go to preference of extension, make sure you are in **Details** tab and scroll down. 
![image](https://user-images.githubusercontent.com/30126032/62616593-a334a200-b918-11e9-8052-0ee8a6925415.png)
You will see the string **Run in Private Windows** and switch it to **Don't Allow**.
![image](https://user-images.githubusercontent.com/30126032/62616656-c4958e00-b918-11e9-8e17-877b9627c9a4.png)
Having done, restart the Firefox and all should work. For other browser, guess, the operations would be similar.

**Comment by Drive4ik** [comment]
Please update addon to latest version, now 4.0.0.2, and its has simple manual how to disable private access for addon
