### ISSUE TITLE
Closing last tab behavior

### ISSUE THREAD

**Issue by igvk** [Drive4ik/simple-tab-groups#209]
Simple tab groups has weird behavior when closing last tab in Firefox window (when browser.tabs.closeWindowWithLastTab is false).
It switches to different tab group or opens a tab from different tab group, but it triggers some bugs in the code. They can be seen if you try to close this tab again or switch to the previous group.
I think that the correct behavior is to stay in the same tab group and just show default tab (i.e. equivalent to FF without tab groups).

**Comment by klint** [comment]
If you mean, when closing the last tab in the currently displayed group, then yes, I have the exact same odd behaviours!

**Comment by LiCybora** [comment]
I make a GIF to demonstrate the way to reproduce the error. The weird behavior is one tab will be assigned to two groups (the group that the tab originally belongs to, and the group with last tab closed) at the same time. You can see from the GIF that when the tab is closed in one group, the one in another group is closed as well (so not duplicated tab, but same tab displayed and belongs to two groups).

![demo](https://user-images.githubusercontent.com/40160522/43007584-5584bb74-8c6b-11e8-8318-9f4fe475115d.gif)

By the way, @Drive4ik `npm run build-zip` seems no longer create valid dev-build. It is hard to debug without console log, although I can still build dev-build from source.

**Comment by Drive4ik** [comment]
Hi! Please retest this issue with STG v3.1

**Comment by igvk** [comment]
Now it switches to another tab group, but seems to do it correctly.
I think, it would be better to just stay in the same group (with default tab open).

**Comment by Drive4ik** [comment]
The fact is that I can not affect the closing of the last tab. And when this happens, Firefox shows the closest hidden tab if there is one. And at this moment my code works and switches to the group in which there is this tab. If I try to change this behavior, it will cause a lot of mistakes and bugs.

**Comment by igvk** [comment]
Oh, i see.
Now it behaves much better.
