### ISSUE TITLE
Shortcut that opens the tabgroups list

### ISSUE THREAD

**Issue by smonff** [Drive4ik/simple-tab-groups#21]
Hello and thanks for the hard work. I tried the various existing alternatives to the original TabGroups extensions since Firefox Quantum appeared and your's is the one that work the best for me so far.

I would suggest the feature of opening the tabgroups list with a configurable shortcut. I miss it a bit from the original TabGroup and find it useful to be able to just [ shortcut ] and select a group with the keyboard arrows.

Dunno if it is feasible with your extension or if you would have some time for this, it is only an idea!

**Comment by Drive4ik** [comment]
Hi @smonff !
If you mean keyboard shortcuts, please update addon to latest version.
Add options to disable keyboard shortcut if not used or if it's has conflict with another addon
Added there
`MacCtrl+Shift+Coma` (`MacCtrl+Shift+[<,]`) - load prev group
`MacCtrl+Shift+Period` (`MacCtrl+Shift+[>.]`) - load next group
`MacCtrl+Shift+[1-9]` - load group by index
`F8` - open popup, then press double `Tab` (this if temporary solution, blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1324255), and then you can choose group by `Down` and `Up`. Open (not switching) group `Right`, close group `Left`. Select group or tab `Enter`

Or you did not mean it?

Best regards.

**Comment by Flowm** [comment]
Is there a shortcut for the new (and awesome) "Manage groups" page?

The original Tab Groups had this screen accessible with `CTRL + Shift + E` as far as I can remember and with a simalar shortcut this extension would already come quite close to my previous workflow.

Greetings and thanks for your work.

**Comment by smonff** [comment]
@Drive4ik I was searching for the `F8` shortcut, or the `Ctrl + Shift + E` form the original Tab Groups extensions quoted by @Flowm . As `Ctrl + Shift + E` default on opening the developer tools network panel, I guess it is a bad bet, so I should just stick on `F8`.

Note that, as far as I know, this shortcut is not available in your documentation.

**Comment by manaskarekar** [comment]
Is it possible to re-assign shortcuts on your own in FF57? I too would prefer to have the Ctrl+Shift+E shortcut for showing the current group.

Thanks for making this, it sucks that the old one is no longer supported.

**Comment by Drive4ik** [comment]
Please, update addon to latest version

**Comment by smonff** [comment]
@Drive4ik is it possible to override the F8 hotkey through the configuration panel? Thanks again.

**Comment by manaskarekar** [comment]
Thank you for updating that. 

Is it because of the Firefox's new way of handling addons that it on't be possible to toggle the Groups page? 

As in, earlier, one could hit Ctrl + Shift + E, and have the groups show up as an overlay, than either the same shortcut again, or escape or enter or clicking on a thumbnail would take you to the relevant place.

Now the groups are launched in a new tab, so you have to close the tab to get rid of the view.

**Comment by Drive4ik** [comment]
@smonff no, FF does not support to hot change this hotkeys :(

@manaskarekar yes, ff extensions not workin on native ff tabs..
you can show manage groups in new window (not new tab) by option in settings

**Comment by manaskarekar** [comment]
Thanks for making this. 👍 

I really miss the old way of handling tabs (and a few other things), this comes close!
