### ISSUE TITLE
lost my group after unexpect shutdown

### ISSUE THREAD

**Issue by Monirzadeh** [Drive4ik/simple-tab-groups#210]
**Describe the bug**
hi 
I lost groups after my pc turn off suddenly (power outage)
STG say you have tabs that are not synced. I restore them but my groups and settings restart.

1. do lots of customization
2. take out the power cord

 - OS: [e.g. linux-kubuntu ]
 - Version [e.g. 3.0.9]

**Comment by yennor** [comment]
I seem to have the same problem. I'm not 100% sure if it was because a crash, since I just noticed today that all my groups are gone (besides the one which was activated), and the last system freeze I had is 2 days ago. Anyway, it also tells me "Found hidden unsynchronized tabs. Click on tab to show it into current group/window or:"
Anyway All tab groups gone. I've got like a 100 unsorted tabs now! argh!
os: linux debian
firefox: 61
stg: 3.0.9

**Comment by Drive4ik** [comment]
Sorry guys but I can not protect the data from the fall of the browser or computer. For normal operation of the browser, it must be rebooted at least once a day, and give it the option to completely turn off and then time to fully load the browser and tabs that are loaded. From everything I can not protect. I can only advise you to make backup copies.

**Comment by kotarou3** [comment]
What makes STG lose all its config on an unclean shutdown, but other addons like Greasemonkey and uBlock Origin retain them just fine? Is it the storage format? What storage does STG use?

And surely STG should be able to data loss, and automatically restore from latest backup if it exists?

**Comment by Drive4ik** [comment]
@kotarou3 
> What makes STG lose all its config on an unclean shutdown, but other addons like Greasemonkey and uBlock Origin retain them just fine?

Because STG uses much more data than other plugins. Depends on the number of tabs and groups.
> Is it the storage format? What storage does STG use?

I use the same as other addons:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/local
There is no other way to save data.

> And surely STG should be able to data loss, and automatically restore from latest backup if it exists?

firefox webextensions do not allow automatic recovery of such amount of data (tabs and groups)

You can find backups in the browser download folder and restore them manually. Not everything is possible to make "automatic"

**Comment by kotarou3** [comment]
> @kotarou3
> 
> > What makes STG lose all its config on an unclean shutdown, but other addons like Greasemonkey and uBlock Origin retain them just fine?
> 
> Because STG uses much more data than other plugins. Depends on the number of tabs and groups.

[Brief](https://github.com/brief-rss/brief) (a RSS reader) seems to retain ~82 MiB storage through crashes just fine, compared to STG of only ~3 MiB (if storage/default are where the data is stored):
```
0	moz-extension+++9ce5a2d5-5981-4134-9fb2-e119135d4916/idb/2885756783ssipmupolreg--tba.files/journals
0	moz-extension+++9ce5a2d5-5981-4134-9fb2-e119135d4916/idb/2885756783ssipmupolreg--tba.files
232K	moz-extension+++9ce5a2d5-5981-4134-9fb2-e119135d4916/idb
0	moz-extension+++9ce5a2d5-5981-4134-9fb2-e119135d4916/cache/morgue
60K	moz-extension+++9ce5a2d5-5981-4134-9fb2-e119135d4916/cache
300K	moz-extension+++9ce5a2d5-5981-4134-9fb2-e119135d4916
0	moz-extension+++9ce5a2d5-5981-4134-9fb2-e119135d4916^userContextId=4294967295/idb/3647222921wleabcEoxlt-eengsairo.files/journals
2.3M	moz-extension+++9ce5a2d5-5981-4134-9fb2-e119135d4916^userContextId=4294967295/idb/3647222921wleabcEoxlt-eengsairo.files
2.5M	moz-extension+++9ce5a2d5-5981-4134-9fb2-e119135d4916^userContextId=4294967295/idb
2.5M	moz-extension+++9ce5a2d5-5981-4134-9fb2-e119135d4916^userContextId=4294967295
0	moz-extension+++8752bcfd-95c6-4b00-b401-f7d7da6fa14f/idb/1070927728bfrei.files
82M	moz-extension+++8752bcfd-95c6-4b00-b401-f7d7da6fa14f/idb
0	moz-extension+++8752bcfd-95c6-4b00-b401-f7d7da6fa14f/cache/morgue
60K	moz-extension+++8752bcfd-95c6-4b00-b401-f7d7da6fa14f/cache
82M	moz-extension+++8752bcfd-95c6-4b00-b401-f7d7da6fa14f
0	moz-extension+++8752bcfd-95c6-4b00-b401-f7d7da6fa14f^userContextId=4294967295/idb/3647222921wleabcEoxlt-eengsairo.files
60K	moz-extension+++8752bcfd-95c6-4b00-b401-f7d7da6fa14f^userContextId=4294967295/idb
68K	moz-extension+++8752bcfd-95c6-4b00-b401-f7d7da6fa14f^userContextId=4294967295
```
(`9ce5a2d5-5981-4134-9fb2-e119135d4916` is STG, `8752bcfd-95c6-4b00-b401-f7d7da6fa14f` is Brief)

It seems like the bulk of STG's data is inside a directory with `^userContextId=4294967295` at the end, while Brief's is without the suffix. I'm not sure what the differences are between the two.

But maybe it might be worth investigating why exactly STG ends up wiping the data while Brief can keep it on crashes.

**Comment by Drive4ik** [comment]
It's not just that. Data is saved every 500 ms after the change, and no more
https://github.com/Drive4ik/simple-tab-groups/blob/cfa1870fc4b590237bbb836d8b6a4567e4967db3/addon/src/background.js#L35-L52

In Firefox 66, the data has been moved to IndexedDB, and there are problems with this too.
https://www.ghacks.net/2019/02/16/firefox-extensions-to-use-different-storage-type-in-firefox-66/
And not only this plugin
https://github.com/sienori/Tab-Session-Manager/wiki/IndexedDB-Error
https://github.com/gorhill/uBlock/issues/2925

When I tested the browser crash, when I started it, I suggested to restore the session, and I made code that in this case waits for the session to be restored before loading the plugin:
https://github.com/Drive4ik/simple-tab-groups/blob/cfa1870fc4b590237bbb836d8b6a4567e4967db3/addon/src/background.js#L2890-L2892
https://github.com/Drive4ik/simple-tab-groups/blob/cfa1870fc4b590237bbb836d8b6a4567e4967db3/addon/src/background.js#L2928-L2959

And no data while the browser is not lost. Addon can not be held responsible for system failure.
For this, I made an automatic backup of all data by default, to the downloads folder and the ability to save to bookmarks, and quick recovery from backup.
Most likely, Firefox developers already know about these issues.
