### ISSUE TITLE
Can't move tab to currently visible group

### ISSUE THREAD

**Issue by hkockerbeck** [Drive4ik/simple-tab-groups#211]
**Describe the bug**
I can move a tab from the currently visible group to another group just fine. But if I try the other way around, moving a tab from a non-visible group to the currently visible group, the tab becomes unsynchronized (appears in the list of "hidden unsynchronized tabs").

**To Reproduce**
1. Create multiple groups, let's say "GroupA" and "GroupB". Select GroupA, so its tabs are visible. 
2. Open a tab in GroupA.
3. Move this tab to GroupB. That works just fine.
4. Move the tab back from GroupB to GroupA. The tab becomes unsynchronized.

**Expected behavior**
I expect the tab I moved into the currently visible group to be moved to the currently visible group.

**Desktop (please complete the following information):**
 - OS: Ubuntu Linux 16.04.4 LTS
 - Browser: Firefox 61.0.1
 - STB Version: 3.0.5.1

**Comment by LiCybora** [comment]
Cannot reproduce in current version. Seems you are using old experimental version (outdated). Latest version is 3.0.9 (3 digits only) and you have to download again. Try if you can reproduce the same error in up-to-date version?

**Comment by hkockerbeck** [comment]
> Seems you are using old experimental version (outdated).

Ah, that seems to be the case. I used the experimental version since back when the "normal" version just removed and added tabs because Firefox Quantum couldn't hide tabs yet, and didn't realize that the experimental version is outdated now. The problem doesn't happen with the current version of the "normal" AddOn. Thanks :)
