### ISSUE TITLE
One of the default group icons doesn't change it's color

### ISSUE THREAD

**Issue by Draghmar** [Drive4ik/simple-tab-groups#213]
**Describe the bug**
On the group management tab, in the settings of a group that has one of the default icon, you can change it's color by clicking on the 'Random color' button. But one the icon is not affected by it even it was in the previous version. It's the selected one in the screenshot.

**To Reproduce**
1. Go to Group Management tab
2. Click on settings for the group that has default icon
3. Click 'Random color' to change icon's color
4. One of the icon doesn't change the color.

**Expected behavior**
In previous versions this icon did change color.

**Screenshots**
![stg-err-iconcolor](https://user-images.githubusercontent.com/275348/42944520-1f89d6e0-8b66-11e8-99f6-3b06c3bc7b61.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.0.10

**Comment by Drive4ik** [comment]
Yes, this behavior is intentional. The color of this icon will change depending on the current theme of Firefox. This feature will available in FF v63 (100%) or v62 (if they add there this feature)
Please see #129

**Comment by Drive4ik** [comment]
@LiCybora Thanks, I completely forgot about this feature.

**Comment by Draghmar** [comment]
Ok, but you could make it so it at least one of the rectangle changes colors. Similar to those two other icons where first has triangle and second has square that changes it's color.

**Comment by Drive4ik** [comment]
@Draghmar Hi! I did it in this issue https://github.com/Drive4ik/simple-tab-groups/issues/214#issuecomment-406335822
