### ISSUE TITLE
With FF62+ black theme, closing the last tab in a group opens a white empty page

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#215]
**Describe the bug**
With FF62 black theme, closing the last tab in a group opens a white empty page instead of a Firefox default new tab page

**To Reproduce**
- close all tabs in a group (from the tab itself, not from the addon menu)
Then a new and unique tab is open in the group, but totally white.

**Expected behavior**
I would have expected a default "new tab" page as selected in the FF options (in my case, a dark empty page with a FF hoverable icon on the top left corner)
 
**Screenshots**

![image](https://user-images.githubusercontent.com/218971/42957568-5d5c01c4-8b83-11e8-9410-1d39d23fba6b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 3.0.10

**Additional context**

**Comment by klint** [comment]
Another variant of this one is when the following scenario:
- using the STG menu, remove all tabs from a given group, the count says 0 now.
- then in the STG menu, click on that group to display it
A tab opens empty and that opens in white.
Look at the group on the STG menu, the count says 1 now.

- in the STG menu, click on the New tab icon in that group
A second new tab opens and that tab is white

Now you have 2 tabs in the group (the count says 2)
One is white, one is black while both should be black

Thanks

**Comment by Drive4ik** [comment]
I have already fix this bug, but it will only be available with Firefox v63 and the new version of STG. Please wait for this.
