### ISSUE TITLE
Unfinished Loading Tab Disappear from Group to Unsynchronized after Restart

### ISSUE THREAD

**Issue by LiCybora** [Drive4ik/simple-tab-groups#216]
**Describe the bug**

**To Reproduce**
1. Make some tabs and groups and allow Firefox restore previous session
2. Restart Firefox
3. Switch into any group such that a tab is loading
4. Switch into any other group **BEFORE THE TAB FINISH LOADING**
   - Tips: Video site that require continuous streaming is easily suffer from this. YouTube is used as example.
   - Users like quick group switching using hotkey can might also increase likelihood being trapped.
5. Restart Firefox
6. The unfinished loading tab disappear but found in unsynchronized

**Expected behavior**
All tabs should still be here without unsynchronized.

**Screenshots**
![disappear](https://user-images.githubusercontent.com/40160522/43016289-f9ec5bcc-8c84-11e8-9467-e545c03ad6cf.gif)

**Desktop (please complete the following information):**
 - OS: any (Tested macOS and Debian)
 - Firefox Version: 61.0/62.0b9
 - Version 3.0.10

**Additional context**
Probably related to #210, but just different way to reproduce.

**Workaround**
If you get into the group of unfinished loading, even not opening that tab, the problem still be solved since that tab unhidden. You can get noticed by a short animation (< 1 sec) indicating tab loading finished, and you can then quit Firefox for safe.

![image](https://user-images.githubusercontent.com/40160522/43016864-de7bff8a-8c86-11e8-908c-5ea44650ff66.png)

**Comment by Drive4ik** [comment]
Hi! Please retest this issue with STG v3.1

**Comment by LiCybora** [comment]
Much better, at least not reproducible when the page is partially rendered. Thx

However, it is still reproducible if group is switched before website server response arrived, especially when you are on slow network. But seems this is more about browser issue as that tab will become saved without an URL in browser session. Unless we compare the current session with backup file (but how to make sure the backup is up-to-date?) for restoring, otherwise there is nothing we can workaround.

You may close the issue if it is hard to find a better fix.

**Comment by Drive4ik** [comment]
@LiCybora Yes you are right. At the moment there is no solution to this problem.
