### ISSUE TITLE
Hotkey to work even when page not fully loaded

### ISSUE THREAD

**Issue by adipose** [Drive4ik/simple-tab-groups#217]
After restarting Firefox, all tabs are in the unloaded state (to improve startup speed).  When a tab is first opened, the content gets loaded.  I noticed that the STG hotkeys do not work while the page is loading, only afterwards.  Is it possible to hook into the hotkey before DOM is loaded, or is that the same limitation that keeps us from using the hotkey from the empty tab page?

**Comment by Drive4ik** [comment]
Hi! As you can see file `manifest.json` has
```js
    "content_scripts": [
        {
            "matches": ["<all_urls>"],
            "js": ["/web/hotkeys.js"],
            "all_frames" : true,
            "match_about_blank": true,
            "run_at": "document_start"
        }
    ],
```

I set key `run_at` to `"document_start"`
This is all I can do to speed up the loading of the script

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts#run_at
