### ISSUE TITLE
Duplicate tabs & never synchronize

### ISSUE THREAD

**Issue by SebCanet** [Drive4ik/simple-tab-groups#218]
**Describe the bug**
When I launch FF 61.0.1, TabGroup launch tabs and try to synchronize, but it duplicates tabs insisde the last group I was when I quit last time. Sometimes TabGroup never finish loading, say "synchronize not finished"

**To Reproduce**
1. Close and reopen with many groups & tabs.

**Expected behavior**
Before, when I open just see last tab in last group.

**Desktop (please complete the following information):**
 - OS: Windows 7x64
 - FF61.0.1 x64

**Comment by smorganl** [comment]
Good Morning,
Look at my issue "Error on startup #208" and see if we don't have the same problem. That being said, it has been entered here for over a month and no one has even acknowledged my existence and whether anyone else has seen the problem.

bye now,
Steven

**Comment by Drive4ik** [comment]
@SebCanet can you try this way: https://github.com/Drive4ik/simple-tab-groups/issues/208#issuecomment-416901664 ?
