### ISSUE TITLE
Unexpected behaviour when closing last tab in group

### ISSUE THREAD

**Issue by mxmehl** [Drive4ik/simple-tab-groups#219]
**To Reproduce**
1. Have two groups open, each one with an open tab, different from the other
2. Enter group 1, and close the only tab
3. The tab of group 2 become the one in group 1, it seems to be clones

**Expected behavior**
Instead of cloning the tab from group 2, it is expected to open an empty tab instead in group 1 so users can stay in their group. An alternative (and configurable) would be to open the "Manage groups" overview so people can select a new group

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 3.0.10, Firefox 61.0.1

**Additional context**
I might have set an config option to not close the Firefox window when the last tab is closed. Perhaps this may affect the reproduction. (Edit: it does not, just tried)

**Comment by LiCybora** [comment]
Duplicate of #209

It is not exact a clone, but that tab belongs to both groups (weird!), you may try to close that tab and seeing the tab disappear in both groups.

**Comment by mxmehl** [comment]
Ah yes, that seems to be it. I'll close here
