### ISSUE TITLE
Automatic group assignment for new pages based on rules/regex

### ISSUE THREAD

**Issue by adipose** [Drive4ik/simple-tab-groups#220]
With Panorama/Tab groups we had an extension called Autogroup that allowed us to use regular expressions or simple domain matching to identify which group we wanted NEW tabs to be assigned to.  Now that simple-tab-groups is the best addon for duplicating Panorama functionality, I wondered if the Autogroup capability could simply be integrated into this addon.

Basically what it would need to do is have a list of expressions (domain names with wildcards would probably suffice, such as news.google.com or *.microsoft.com, but regex would also be good), and an option to identify which tab group to put them in.  When a new tab is opened, it checks the URL and switches the loaded tab to that group automatically (transporting the user to the other tab group as well).

Do you think this functionality might be added to STG at some point?  Thank you!

**Comment by Drive4ik** [comment]
Do you mean this functional or another?
![screenshot_1](https://user-images.githubusercontent.com/7843031/44161869-4583c600-a0c7-11e8-97ce-07c199a54567.png)
![screenshot_2](https://user-images.githubusercontent.com/7843031/44161879-47e62000-a0c7-11e8-8f17-eca4220f06ee.png)

**Comment by adipose** [comment]
Yes, this is the feature!  I had missed it.

Thank you!
