### ISSUE TITLE
Stay on the foreground tab when automatic transferring it to another group

### ISSUE THREAD

**Issue by chaotic-sys** [Drive4ik/simple-tab-groups#221]
Tab in the foreground. Inside this tab opens an address that satisfies the rules for moving a tab to another group.

**Observed behavior.** The tab disappears because it is moved to another group.

The same happens if a new tab with a suitable address is opened in the foreground. The tab is transferred to another group and disappears from the visual field.

**Desired behavior.** The tab remains in front of the eyes to continue to work with it. The tab group is replaced with the correct group.

You can a check mark in the settings: "Stay on the foreground tab when automatic transfer it to another group. Groups are switched".

In addition, you can make a check mark "Stay on the foreground tab when manually transferring it to another group".

**Comment by Drive4ik** [comment]
Hi! Please retest this issue with STG v3.1. Option in group settings "Show the tab after auto-moving it into this group"

**Comment by chaotic-sys** [comment]
Yes! Yes! It work! Thank you : )
