### ISSUE TITLE
Allow undo, instead of confirmation when closing group

### ISSUE THREAD

**Issue by pradyunsg** [Drive4ik/simple-tab-groups#222]
It results in a better UX.

**Comment by Drive4ik** [comment]
Maybe you meant the restoration of deleted groups?
![197330](https://user-images.githubusercontent.com/7843031/43642632-09409082-9731-11e8-8c1d-ab2de1e67914.png)

**Comment by pradyunsg** [comment]
Ah well. That's a very poorly filed issue by. I'm going to try again...

---

**What's the problem this feature will solve?**
In the Manage Groups page, currently, every time a group is deleted, a confirmation modal/dialog is shown to the user, to confirm the act of deleting a group. This means when closing multiple groups, the user is asked to confirm each deletion which means each deletion involves 2 clicks of fairly small buttons.

<img width="1660" alt="screen shot 2018-08-03 at 7 08 35 pm" src="https://user-images.githubusercontent.com/3275593/43645826-b84f266e-9750-11e8-854b-86c96c827b55.png">

**Describe the solution you'd like**


Switch to something along the lines of GMail's "notification" that acts as confirmation and also allows undo.

<img width="308" alt="screen shot 2018-08-03 at 7 44 21 pm" src="https://user-images.githubusercontent.com/3275593/43647591-b96e0510-9755-11e8-8400-e7e8af22a86b.png">

**Comment by Drive4ik** [comment]
Done. Please wait next release

**Comment by Drive4ik** [comment]
Now you can restore a removed group from these two locations, will be like this:
![screenshot_1](https://user-images.githubusercontent.com/7843031/45089073-b0974a00-b113-11e8-96b3-1652361ee49f.png)
