### ISSUE TITLE
Switching groups loads all unloaded tabs

### ISSUE THREAD

**Issue by jonc125** [Drive4ik/simple-tab-groups#223]
**Describe the bug**

When I change to another group, any tabs in that group that were currently unloaded are loaded immediately. With large groups this takes a long time! From #12 it looked like this should now be fixed, but it isn't (on version 3.0.10).

**To Reproduce**
1. This is most easily seen after a Firefox restart, restoring a session with more than 1 group.
2. After restarting, switch to another group.
3. All tabs in that group start to load.

**Expected behavior**
I'd expect only the single tab to load; other tabs should not load until clicked on.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS Sierra
 - Version: 3.0.10
 - Firefox 61.0.1

**Additional context**
extensions.webextensions.tabhide.enabled is set to true.

**Comment by Drive4ik** [comment]
Hi! Maybe this will help you?
https://support.mozilla.org/en-US/questions/1185154

**Comment by jonc125** [comment]
The sessionstore prefs look to be set OK (see below), and indeed on starting Firefox tabs are loaded on demand.

- browser.sessionstore.restore_hidden_tabs;false
- browser.sessionstore.restore_on_demand;true
- browser.sessionstore.restore_pinned_tabs_on_demand;false
- browser.sessionstore.restore_tabs_lazily;true

If I disable all add-ons except for Simple Tab Groups, and restart Firefox, the problem still occurs.

Interestingly, it doesn't load all tabs if I switch back to the initial group (the one I'm in when Firefox starts, if I leave some tabs there unloaded), only when switching to a different group. But it does happen when switching to any group except the initial one.

**Comment by Drive4ik** [comment]
Ok. Have you checked this box?
![screenshot_2](https://user-images.githubusercontent.com/7843031/44158514-84ad1980-a0bd-11e8-985d-85db3a6b4902.png)

**Comment by jonc125** [comment]
Yes, it is.

**Comment by Drive4ik** [comment]
Ok? Can you create new Firefox profile and retest this issue in it?

**Comment by Drive4ik** [comment]
`about:profiles` page

**Comment by bradEss** [comment]
I can back jonc125 up on this one.  I haven't been able to nail down the exact pattern, but for the most part, it seems to occur when Firefox shuts down, either gracefully or ungracefully.  The first tab group after restore will only load on demand as expected, but when switching to any other group, all tabs in that group will load.

This happens whether I choose to restore the session by choosing a group from the Simple Tab Groups button or by using the Restore Previous Session option.

I have all the same config settings that jonc has.  My specs are nearly the same:

Version 3.1
Firefox 61.0.2
MacOS Sierra 10.12.5

I have the Auto Tab Discard addon too.  That's the only other thing that would touch sessions/tabs as far as I can see.  But I don't think jonc has that extension, so it's probably not a contributing factor.

I have rebuilt my profile pretty recently, and had the same behavior before and after.

**Comment by jonc125** [comment]
I've finally got round to trying a fresh profile with Ff 61.0.2 and version 3.1, and the add-on loads lazily as expected with this setup, hooray! I'll try adding back my other add-ons and settings one by one and see if the bug reappears...

**Comment by jonc125** [comment]
It looks promising - I now have everything set up & working OK. One factor that might have contributed: I noticed when importing a backup from the old Tab Groups that the first time I switched to each imported group every single tab was loaded. However, if I let them all load, then quit & restart Firefox, on subsequent switches the loading is lazy.
