### ISSUE TITLE
Sidebar support

### ISSUE THREAD

**Issue by HASJ** [Drive4ik/simple-tab-groups#225]
**Is your feature request related to a problem? Please describe.**
I have a great number of tabs opened, the default tab bar makes this a frustrating venture to manage with only horizontal control.

**Describe the solution you'd like**
A sidebar display, much like the old Tab Groups worked with the Tree Style Tab extension

**Describe alternatives you've considered**
The Power Tab extension came pretty close but it's grouping functionality is lacking.
Tree Style Tab is also close but I need more control over the grouping.
Simple Tab Groups is just perfect but it doesn't have sidebar support.

**Additional context**
Hidden horizontal tab bar
![image](https://user-images.githubusercontent.com/9345660/43775181-2e1596fc-9a22-11e8-821c-75cf3884207a.png)

How it looks like with Power Tab (with dark theme)
![image](https://user-images.githubusercontent.com/9345660/43775287-8b097fcc-9a22-11e8-9aab-2c916a55df99.png)

**Comment by Celti** [comment]
I've made a couple aborted attempts at merging STG with [Tab Center Redux](/eoger/tabcenter-redux) as about the best tab management sidebar out there these days. Might be time to try again...

**Comment by Drive4ik** [comment]
Sorry guys, I thought here and decided that there is no point in making similar functionality like the above-mentioned addons.
But, you can use these add-ons with STG, no conflicts have been identified.

**Comment by saithis** [comment]
@Drive4ik The above mentioned addons dont work that well for grouping tabs.

**The Power Tab:** Is lacking important functionallity and doesnt feel that polished.
**Tree Style Tab:** Doesnt really support tab groups, just tabs with children. So I always have to choose one tab of a group as the parent. But then it does behave differently for the parent tab and the children, which is annoying.
**Tab Center Redux:** Doesnt support tab groups at all.
**Tab Center Redux + Simple Tab Groups:** You have to manage the tabs and groups in different places and you cant have multiple groups open at the same time.

The Tab Center Redux author has decided against adding groups functionallity.
You have decided agains a sidebar.

So no hope in sight of getting a great tab group sidebar functionallity 😢

**Comment by Celti** [comment]
Frankly, once both STG and Tab Center Redux support the new native context menu features in recent Firefox versions, everything will be about perfect, as then you can access STG's features from the context menu just as with normal (horizontal) tabs.

**Comment by Drive4ik** [comment]
added sidebar support (in testing mode), please wait next STG release

**Comment by grahamperrin** [comment]
#10
