### ISSUE TITLE
When returning to a group, the previously active tab is lost

### ISSUE THREAD

**Issue by adipose** [Drive4ik/simple-tab-groups#227]
Sometimes a captured URL sends the tab to a new group.  After this, the user may wish to switch back to their previously active group/tab.  But when switching back to the old group, the "last active tab" of that group no longer exists, as it was moved to the new group.  Instead you get stuck in the last tab of that group.

Since the last "valid" tab that was active is the tab you were using before opening the new tab, that should be the active tab if you return to that group.

Example (*=Active tab):

Group A - tabs 1*, 2, 3
Group B - tabs 4, 5*, 6

In group A, open tab 7, which matches expression for Group B:

Group A - tabs 1*, 2, 3
Group B - tabs 4, 5, 6, 7*

Switch back to Group A:

Group A - tabs 1, 2, 3*
Group B - tabs 4, 5, 6, 7*

Tab 3 is now active but tab 1 would be preferred.

**Comment by Drive4ik** [comment]
Hi! I know about this bug, but I can't fix it.. When you open tab 7 in Group A (and Group B don't have any expression) and then close tab 7 you will auto active tab 3. Otherwise it will not work out at all.

**Comment by adipose** [comment]
In my example Group B has an expression that matches tab 7.  So I don't understand what you are saying.

Can't you remember the last active tab (1) per group, and if a new tab gets auto-assigned to a different group (B), mark the last active tab in group A back to (1)?

**Comment by Drive4ik** [comment]
It's not as simple as it seems at first glance. Firefox webextension api has a lot of bugs, and they then appear new, then fix the old ones. And those bugs when working with the tabs that I tracked, I also tried to fix them. And this led to a less stable work, but the complication of logic will lead to new bugs.

**Comment by Drive4ik** [comment]
Hi! I tried to fix this bug, wait until the next release and check it. Thanks

**Comment by adipose** [comment]
Awesome, thanks!
