### ISSUE TITLE
Default tab group

### ISSUE THREAD

**Issue by yonkavalow** [Drive4ik/simple-tab-groups#228]
With your addon I have 3 tab groups. 
1) my main group 
2) specific subject #1 
3) specific subject #2 

Groups 2 and 3 have regex rules to catch tabs.

If I open a link that doesnt match those expressions i would like for it to open in my main default tab group.
At the moment the behavior is that that new url will open in whatever window I used last.

Thanks! I love this addon.

**Comment by Draghmar** [comment]
Couldn't this be resolved by creating negative regex? So you have two positive regex for moving to 2 and 3 and then third that would catch everything that is not fitting for 2 and 3.
_I don't know if it's possible because I don't use this functionality with STG._
