### ISSUE TITLE
Send Message Actions in Gesturify Addon

### ISSUE THREAD

**Issue by cswhatsgit** [Drive4ik/simple-tab-groups#229]
I am trying to setup the open-manage-groups action in Gesturefy. Could you please educate us on what kind of message/command to input to achieve this? I copied and pasted _open-manage-groups_ but it won't implement the action.

Thank you!

**Comment by Drive4ik** [comment]
Hi! You can try this way
https://github.com/Drive4ik/simple-tab-groups/issues/63#issuecomment-413834941

**Comment by cswhatsgit** [comment]
Thanks for your quick reply! Got it working now. May I suggest to put it these lines in the Wiki section so future users can see them instead bother you ;)

**Comment by Drive4ik** [comment]
I have already updated the description to the add-on. And wiki someday then I'll do it))
