### ISSUE TITLE
PC crashed, Firefox restored session, STG asked what to do with desync'd tabs and now 300 tabs try to load at the same time

### ISSUE THREAD

**Issue by HASJ** [Drive4ik/simple-tab-groups#230]
**Describe the bug**
After a crach, STG asked what to do with desyn'c tabs and I chose to restore them into a new group.
Apparently, every single tab from the previous session had desync'd, which had more than 300 tabs.
If I ever switch to that new group, Firefox tries to load ALL of those tabs at the SAME time.
After 4 seconds, Firefox just hangs from lack of memory.
I tried it again, restored the previous session and then a new group with 600+ tabs came up. I simply gave up and disabled STG for now because I do not know which tabs are new and which are duplicates. Duplicate Tab Closer can't do it's magic because it requires duplicated tabs to be fully loaded plus I don't know if it works across STG's groups.

This obviously won't be a big issue if you have dozens of RAM gigabytes but I don't.

**To Reproduce**
1. Crash Firefox
2. Restore tabs
3. Restore desync'd tabs into a new group
4. Change to the newly created group
5. "Bug"

**Expected behavior**
Someway to make Firefox **NOT** load everything at the same time.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 3.1

**Comment by Draghmar** [comment]
Did you look and those desync tabs and check out if they are just duplicated from normal groups? This happened to me a lot and in 99% of cases those tabs weren't worth restoring. 
Anyway tip for the future - make regular backups of STG. It saved my ass a few times already. ;)

**Comment by Drive4ik** [comment]
![session-restore-with-stg](https://user-images.githubusercontent.com/7843031/45314741-3adc1580-b53b-11e8-936f-aa8b44581f2f.gif)

**Comment by Drive4ik** [comment]
Please, update addon to latest version and try retest FF crash/restore if you can. I added waiting if session restore page found
