### ISSUE TITLE
tab closed by releasing scroll button

### ISSUE THREAD

**Issue by anellus** [Drive4ik/simple-tab-groups#232]
When scrolling through the tabs in the drop-down list by holding down the scroll wheel button and then releasing it, the tab under the cursor is closed. It would be favourable to close the tab only when not scrolling by pressing down the scroll wheel.

**Comment by Drive4ik** [comment]
Hi! Unfortunately this can not be done because the tab delete functionality will stop working properly. This functional uses a lot of people. I can only advise to interrupt the scroll and release the mouse wheel when the mouse is on the scroll and not on the tab (when you start scroll not on tab)
