### ISSUE TITLE
Extension doesn't load

### ISSUE THREAD

**Issue by Vinayak-kadu** [Drive4ik/simple-tab-groups#233]
**Describe the bug**
extension is not loading, you can't select the tab groups. icon is keep spinning won't stop.

**steps to mitigate the problem**
1. backtup storage.js from user profile folder
2. uninstall STG, Re-install it again(3.1)
3. replace new storage.js with old storage.js(~ 250mb)
4. extension again hangs up

**Expected behavior**
tab groups load and let you select groups. normal operation.

**Additional context**
look like happening with latest verions
FF : 61.0.2 (64-bit)
STG : 3.1
could it be because of large storage.js file size.??

Edit: after trying to reinstall, STG start with new strage js file with no tab groups. all previous tabs are grouped into one dafault TG. in my case over 170 tabs in one group.

**Comment by Drive4ik** [comment]
Hi! I fix bug with big size of `storage.js` in #194

**Comment by Vinayak-kadu** [comment]
so it was issue of big size, this extension is way too important man, will wait for next verion.

**Comment by lemenkov** [comment]
I was hit by this too. Eagerly waiting for the next version :)

**Comment by Drive4ik** [comment]
Hi all! Can you retest this issue with FF 62 and STG 3.1.2.1?

**Comment by Vinayak-kadu** [comment]
FF 62
STG 3.1.2.1
as of now its flawless. groups are switching faster.. thank you.
