### ISSUE TITLE
Tabs mysteriously move from one group to another

### ISSUE THREAD

**Issue by alan8it** [Drive4ik/simple-tab-groups#234]
I have multiple tab groups. Occasionally, and I haven't yet found the common denominator, when I switch between groups, the Active Tab i am currently viewing in one group moves to the group I just selected. 
Example: 
Tab Group named Main with 3 tabs (Yahoo, Google, Bing).
Tab Group named Education with three different sites.
I am on Yahoo, then I click on the Education Tab Group and boom! the Yahoo tab shows up on the Education group!
To correct, I navigate back to the Main group - and the Yahoo Tab follows me - then I select a different Tab (or navigate to a different page on Yahoo). Then I click on the Education Group and all is right with the world again.

I am on Windows 10, Firefox V61.02, and Simple Tab Groups 3.1 (all are the most current versions as of this writing).
Appreciate any help in identifying why this happens and hopefully a fix will be forthcoming.

**Comment by Drive4ik** [comment]
Hi Can you try re-test this issue with latest FF62 and STG v3.1.2.1 or above?

**Comment by alan8it** [comment]
Still occurs, and both FF and STG Are up to date.
I have set each tab group to Sticky to see if that helped - no luck.
What else can I try? What other information do you need?
Perhaps this is being affected by one or more of my installed extensions?

- Ad Blocker Ultimate
- Auto Tab Discard
- Foxy Gestures
- HTTPS Everywhere
- Noise
- Tab Open/Close Control
- Yet Another Smooth Scrolling WE

Appreciate any help you can offer.

**Comment by Drive4ik** [comment]
Hi! Ok, do you use pinned tabs and how much RAM is in the computer?
P.S. may be proble with addon "Tab Open/Close Control". With him already had some problems, but maybe it's not his fault

**Comment by alan8it** [comment]
I don’t have any pinned tabs. 
16gb Ram
I will try disabling that extension and see what happens. 
Any debug options to send you some extra info?

**Comment by Drive4ik** [comment]
Hi! I replicate this issue with addon `Tab Open/Close Control` and it's settings:
![screenshot_2](https://user-images.githubusercontent.com/7843031/45416820-640abc00-b689-11e8-8a94-d82da0bbb4af.png)
what exactly are the options that affect it I do not know
But if I disable/remove addon - this bug not replicated. Please, re-test with disabled this addon
