### ISSUE TITLE
STG can't handle session restoration (e.g. after crash) properly

### ISSUE THREAD

**Issue by Illiou** [Drive4ik/simple-tab-groups#235]
I'm sure others have reported instances of this problem before, but I want to frame this more as a general problem: it seems like STG isn't able to handle Firefox's session restoration, by which I mean the tab that opens when Firefox wasn't able to restore the session normally because some error occured and it tries to use a backup instead.

**What happens**
You start the browser up and only the session restoration tab opens (happens to me once in a while even though I exited the browser normally).
Now there are two options, both suboptimal:
1. You just close the tab and switch to one of STG's tab groups. Now all tabs in that group load anew at the same time and even more critical often (not sure if always) the individual tab history is lost!
2. You restore the old session with Firefox.
In this case it has happened to me that all restored foreground tabs seem to have replaced the current tab group with the same tabs. And all tabs from other groups are shown as hidden but outside of groups within STG, which you could just close if you could be sure that they are all duplicates, which I'm not sure you can be.
But it has also happened to me that the restored foreground tabs have just been put in the current window, which then somehow wasn't a group of STG at all. And upon reloading STG everything was all over the place, some group just loaded all tabs again, and not sure where all the tabs went that were just loaded in the window, seemed like they were just gone.

**What should happen**
You would expect STG to handle problems with the session restoration much better. Most importantly not needing to reload all the tabs and losing individual tab history.
I don't know if for that to be possible it is needed to restore the session with firefox or ignore it, but whichever is the case, STG should ideally tell you what to do and then handle it such than you can seamlessly continue using your tabs/tab groups, without reloading, lost data, hidden ungrouped tabs etc. Like you can if you don't have STG and just restore the session and move on.

**Specs**
 - Windows 10
 - Firefox 61.0.2
 - STG 3.1

**Comment by m60freeman** [comment]
Coincidentally, this just happened to me this morning. I had Firefox restore the old session, and I now have a huge list of unsychronized tabs, which look like they come from many or all of my 16 groups.

In the future, am I better off closing the Firefox restore tab and then switching to the last tab group that I had open and hoping that it is up to date with before the Windows or Firefox crash?

Specs

    Windows 10
    Firefox 61.0.2
    STG 3.1 (Last updated August 13, 2018)

**Comment by Drive4ik** [comment]
https://github.com/Drive4ik/simple-tab-groups/wiki/How-restore-STG-groups-and-tags-after-PC-crash-FF-crash-etc.

**Comment by Illiou** [comment]
Good to see that all it takes is restoring the session and reloading the add-on afterwards.
Do you think it's possible to make the add-on detect the session restoration tab and display a relevant message and possibly even do a graceful reload in the background when it detects all the same tabs being restored as hidden? Because most people affected by this will probably not be able to make use of this wiki entry in a situation that requires immediate correct action.

**Comment by Drive4ik** [comment]
@Illiou Please, update addon to latest version and try retest FF crash/restore if you can

**Comment by Illiou** [comment]
I didn't even have to try, this morning my browser showed a session restoration again. But I really like your solution, more done automatically and fewer ways to mess it up. Worked without problems for me. Good job, thank you!

(Though I'm starting to wonder if those crashes are caused by Firefox or possibly STG, so maybe keep an eye out for other reports of that)

**Comment by Drive4ik** [comment]
It's very difficult to break Firefox with add-ons, but you can use a very large amount of memory, but I already fixed this bug 😄 #194

**Comment by grahamperrin** [comment]
> Drive4ik/simple-tab-groups/wiki/How-restore-STG-groups-and-tags-after-PC-crash-FF-crash-etc

I can't tell what's happening in this looping recording, might you add a written explanation? Thanks

**Comment by Drive4ik** [comment]
@grahamperrin This is a very old entry for the old version of the addon. For the new version (4.0+), if your browser crashes, just click on the blue button to restore the session, and if the browser will restore everything - addon will start working right away. If this does not happen, then you need to restore the groups from the backup.
