### ISSUE TITLE
'background not inited'

### ISSUE THREAD

**Issue by ConductedForce** [Drive4ik/simple-tab-groups#237]
STG popup does not open. Gives error 'background not inited' in browser console. I have my computer to hibernate often, so this may be the initial cause. Browser console says it was line 7 of popup.js

Using Windows 7, FF version 61.0.2 (64-bit). 

Simple close and open fixes problem. Likely will happen again.

**Comment by Drive4ik** [comment]
Hi, please read this my message https://github.com/Drive4ik/simple-tab-groups/issues/238#issuecomment-418691975

**Comment by Drive4ik** [comment]
Can you retest this issue, and if it's not replicate - close this ticket. Thanks
