### ISSUE TITLE
Takes up lots of memory occationally.

### ISSUE THREAD

**Issue by dspjm** [Drive4ik/simple-tab-groups#238]
**Describe the bug**
Sometimes the browser takes up lots of memory. Don't know what is happening but disabling this add-on solved the problem.

**To Reproduce**
1. Enable tab groups
2. Do normal browsing
3. Memory use will rise to almost 100% and hang the browser. After around 10s, the memory will drop to normal level but the problem will repeat after a while.

**Expected behavior**
Normal memory use.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Version 3.1

**Additional context**

**Comment by Drive4ik** [comment]
Hi! This bug was fixed in #194 
Please wait for FF62 and then update addon to v3.1.1 and retest. If bug will not replicate - close this issue
Thanks.

**Comment by unclechu** [comment]
I had this issue too with `3.1` (short peaks with about 2GiB eaten) on FF61 and FF62 (Fedora Workstation 28), after an update of the Simple Tab Groups to `3.1.2.1` everything is okay with memory, no anomalies noticed anymore.
