### ISSUE TITLE
Group icon for the current window used in all windows

### ISSUE THREAD

**Issue by shtrom** [Drive4ik/simple-tab-groups#239]
**Describe the bug**
With, say, two windows showing different groups. Both windows will show the same icon, which is the icon of the group in the currently active window. Selecting the other window will change the icon to the other group, for both windows.

**Expected behavior**
Each window keeps the icon of its own group

**Screenshots**
![tabgroup](https://user-images.githubusercontent.com/160280/45204628-2b529780-b2c3-11e8-899b-69450644607e.gif)

**Desktop (please complete the following information):**
 - OS: OS X 10.13.6
 - Firefox: 61.0.2

**Comment by Drive4ik** [comment]
Hi. Please update FF to v62 and then update STG to latest version and retest this issue.

**Comment by shtrom** [comment]
The

**Comment by Drive4ik** [comment]
You have to update STG to latest version
`about:addons` page

**Comment by shtrom** [comment]
Ah, yep, it seems fixed on ArchLinux with the version from 8th September.
