### ISSUE TITLE
FF62 and 3.1.2 shortcut keys don't work

### ISSUE THREAD

**Issue by lyonelf** [Drive4ik/simple-tab-groups#240]
**Describe the bug**
when i try to switch bt groups, ctrl + < don't work

nothing happend, yesterday before tab groups update but aldready in FF62 it was ok.

**Comment by Drive4ik** [comment]
You can now update to STG v3.1.2.1 and retest

**Comment by lyonelf** [comment]
All right, it's ok for me.
Thanks a lot to restore quickly my panic button when my boss is arriving :)
