### ISSUE TITLE
Add option to display tab group name instead of just icon

### ISSUE THREAD

**Issue by maeichris** [Drive4ik/simple-tab-groups#241]
**Is your feature request related to a problem? Please describe.**
I find I do not necessarily know which tab group is active (i.e. which tab group I'm currently in).  To find out, I have to click on the grid+triangle icon to bring up the STG menu and see which one is selected.

**Describe the solution you'd like**
On the control that pops up the STG menu, I'd prefer it if there were a way of configuring STG to display the current tab name instead of just an icon.  This is the behavior of the former Quicksilver Tab Groups.

**Comment by Drive4ik** [comment]
Hi! Please see #10 and #169

**Comment by maeichris** [comment]
Thanks for the update.  I'm sorry I wasted your time because I only looked through the open tickets before creating this one, and not the closed tickets.

**Comment by Drive4ik** [comment]
It's okay, if Firefox in the future will make it possible to do this functionality, I'll gladly embody it
