### ISSUE TITLE
STG icon spins constantly in private window

### ISSUE THREAD

**Issue by ryetek** [Drive4ik/simple-tab-groups#242]
**Describe the bug**
Whilst I appreciate that STG does not support private (incognito) mode from version 3.2 the STG icon constantly spins when in a private window.

**To Reproduce**
1. Press CTRL+SHIFT+P to start a private window
2. STG icon will constantly spin

**Expected behavior**
STG icon should be "greyed out" and become unavailable. Spinning animation should stop.

**Desktop (please complete the following information):**
 - OS: Windows 8.1Pro
 - Version: 3.2
 - Firefox Version: 62.0

**Comment by Drive4ik** [comment]
Hi! Thanks for fing bug, this fix will available on next release of STG
