### ISSUE TITLE
Feature request: Move focus to first search result after search

### ISSUE THREAD

**Issue by slovdahl** [Drive4ik/simple-tab-groups#243]
In order to make switching tabs using only the keyboard easier, it would be nice if after doing a search in the groups pop-up, the first result would be focused, which would make it possible to just press enter to switch to the tab.

Step by step:
1. Press hotkey for "open groups pop-up"
2. Type something in the search bar
3. First result is focused, press enter to switch to that tab

**Comment by slovdahl** [comment]
The problem with the current behaviour is that the first tab group is focused, but pressing the down button on your keyboard doesn't focus the first result in that group, instead if focuses something else (not sure what).

**Comment by Drive4ik** [comment]
Pressing the down button on your keyboard set focus on first group in search results (if its exists).
Pressing enter on search input (without down button and hover item) will have a similar result.
You can select the first tab using the following combinations:
input search: `youtube` -> `TAB or key down` -> `TAB or key down` -> `Enter`

**Comment by slovdahl** [comment]
The point here is that one click on either tab or arrow down should move the focus from the first tab group to the first actual tab. That's not the case at the moment, and it feels quite unintuitive.

**Comment by Drive4ik** [comment]
You say that this is not intuitive, but it depends on which side to look at 😄 #178 
I could have made another option in the settings to configure this behavior, but I do not want to pile up with various settings, because it's hard to maintain in the future and sometimes it's impossible at all

**Comment by slovdahl** [comment]
Yes, I can accept that. 🙂 And I totally agree with regard to introducing new settings.

I now realize this might be a problem only on Linux. I tried to reprodudce it on MacOS now as well, but it works better there. 

On Linux, to get from the focused tab group to the first tab in that group, you need two clicks on either tab or arrow down to even get to the first tab gropu in the search results, and that's what I mean feels unintuitive. It looks like the first tab/arrow down sets the focus on the checkbox to the right of the search bar. Are you following?
