### ISSUE TITLE
Setting to always open tab groups in a new window

### ISSUE THREAD

**Issue by Derek-m-f** [Drive4ik/simple-tab-groups#244]
**Is your feature request related to a problem? Please describe.**
The previous version of simple tab groups I was using on my old computer, had a setting for always opening tab groups in a separate/new window.  After using simple tab groups for a while, that was the option I preferred.  Now I got a new computer and installed the same version of firefox I had on the old computer, but simple tab groups was no longer available for that version of firefox, only for version 62 or greater.  So I installed the latest version of firefox, got simple tab groups for that version, and now this version of simple tab groups doesn't have that setting.  Not sure if that setting was removed for some reason as this extension was updated.

**Describe the solution you'd like**

Just would like that setting back.  So when I click on the tab groups icon so it drops down, and then I click on a specific tab group, it opens that tab group in a separate window (or switches to the window if that group is already open in another window.)

**Describe alternatives you've considered**

**Additional context**

**Comment by Drive4ik** [comment]
Yes, this option has been removed due to the fact that it is not rational to load tabs whenever you open a group. But I returned the opportunity to do this manually by context menu on group:
![screenshot_1](https://user-images.githubusercontent.com/7843031/45414581-60286b00-b684-11e8-96e3-3bf1accb3474.png)

**Comment by Derek-m-f** [comment]
I did find the context menu option, thanks.  I think that was actually the
reason I liked using the separate windows, so that the tabs would stay
loaded at least until I close that window.  So you are saying now the
latest version actually keeps all the tabs in all the other groups loaded
when switching back and forth between groups?

**Comment by Drive4ik** [comment]
Yes, provided that the tabs were not in the window that was closed
