### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Gnustier** [Drive4ik/simple-tab-groups#245]
Would you please make a dark theme for the manage-page and popup-menu and options-page ? In order to protect eyes when the ambience is dark (theme of browser and operating system), and in order to match the theme of browser.

**Describe the solution you'd like**

Put a switch in side the popup menu and manage page for quickly changing between bright and dark theme.

**Describe alternatives you've considered**

Make the color theme automatically change according to the theme of browser.
- Change to dark or bright theme when the theme of browser is dark or bright.
- Do not change the theme when the theme of browser is default.
- Make a switch for disable auto changing.

Make the colors and font-size and line-height could be changed using the css format.

**Comment by Drive4ik** [comment]
I've already thought about this, but for now I want to bring the addon to a stable state.
Soon I will get support for different themes

**Comment by Drive4ik** [comment]
Done. Dark theme will available in FF 63 and next STG release.

**Comment by Henry78** [comment]
A problem with the dark theme: the mostly dark group icons could changed to something with better visibility in dark mode.

**Comment by Drive4ik** [comment]
@Henry78 The color of the icons depends on the color of the text in the theme.

**Comment by Henry78** [comment]
@Drive4ik: Are you sure?

![2019-05-16 11_57_07-Window](https://user-images.githubusercontent.com/1314735/57845426-453d6600-77d2-11e9-9d5c-dff283648286.png)

**Comment by Drive4ik** [comment]
Yes. Please read addon description and this popup
![Screenshot_1](https://user-images.githubusercontent.com/7843031/57847344-ecc09580-77de-11e9-8a2f-5cdd00918dd1.png)

REQUIRED for dark theme: Set svg.context-properties.content.enabled to true in about:config page.
https://support.mozilla.org/ru/kb/redaktor-nastroek-firefox#w_zajaoaii-aboutconfig

**Comment by Henry78** [comment]
Jep, works.
Seems I missed that step. Sorry for any inconvenicence.
