### ISSUE TITLE
Hotkeys don't work on "special" pages sometimes

### ISSUE THREAD

**Issue by adtac** [Drive4ik/simple-tab-groups#246]
**Describe the bug**

I'm not entirely sure if this bug is even possible to fix given the constrains extensions work under, but I have no experience writing Firefox addons, so I figured I might as well ask before. I have Ctrl+Shift+Enter mapped to "Load next group". When I'm in "special" pages (such as about:addons, new tab, PDFs, mozilla.org domain and subdomains), the hotkey does not work.

I imagine this is due to a restriction on webextensions as a security thing, but this other extension I use called Vertical Tabs (which opens a window on the side) and I have Ctrl+Shift+Space mapped to toggling the tab list on and off. This hotkey always works regardless of which page I'm in. My guess is that since they have their own side pane, they have a different set of restrictions?

**To Reproduce**

1. Create a hotkey for "Load next group".

2. Go to any of the previously mentioned "special" pages.

3. Press the hotkey to load the next group.

**Expected behavior**

The next group should be loaded.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version Simple Tab Groups 3.2.1

**Comment by Drive4ik** [comment]
Hi. I know about this behaviour and this is written in paragraph 1 in Restrictions on Hotkeys tab.
I implemented a dynamic key assignment, and it will conflict or be completely incompatible with the WebExtensions API commands

**Comment by DatGrey** [comment]
Hi, any chance something has changed in the last year? I've seen similar extensions (like [Panorama Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/panorama-tab-groups/), for example) have working hotkeys in special pages.
Thanks.

**Comment by Drive4ik** [comment]
@DatGrey Hi!
You can change hotkeys by browser like this
![изображение](https://user-images.githubusercontent.com/7843031/72898236-60328380-3d2c-11ea-9242-30ed77347621.png)
![изображение](https://user-images.githubusercontent.com/7843031/72898256-67f22800-3d2c-11ea-8cb9-a8461dcced8c.png)
