### ISSUE TITLE
New tab extension not respected

### ISSUE THREAD

**Issue by adtac** [Drive4ik/simple-tab-groups#247]
**Describe the bug**

I have an extension installed to control my new tab look. When I open a tab group with zero tabs, I don't get this page.

As a side note, I want to mention that the https://github.com/Drive4ik/simple-tab-groups/issues/246 bug **does** happen on my custom new tab, but the hotkey works on the blank new tab created by Simple Tab Groups.

**To Reproduce**

1. Create a tab group and make sure there are no tabs in it.

2. Have an extension installed to control your new tab. I'm pretty sure this doesn't matter, but in case this helps, I use [BWNT](https://addons.mozilla.org/en-US/firefox/addon/bwnt/?src=search).

3. Switch to the newly created, empty tab group from a different tab group.

**Expected behavior**

New tab controlled by the extension should be opened.

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Version Simple Tab Groups 3.2.1

**Potential solution**

Allow a configurable URL to open when switching to a tab group with no tabs.

**Comment by Drive4ik** [comment]
Fixed. Please wait for FF 63 and new STG version
