### ISSUE TITLE
waiting for all tabs to load. Please wait...

### ISSUE THREAD

**Issue by Bobycop** [Drive4ik/simple-tab-groups#248]
Since a couple of days I can’t use my Tab Groups extension. I always have message "waiting for all tabs to load. Please wait...". I use Firefox 62.0 for x64. I'm worry, I like this extension… !

**Comment by Drive4ik** [comment]
Try to find tabs that are loaded in any window to go to it and press `Esc` to stop loading tab

**Comment by neomodern** [comment]
Is there no way to circumvent the need for all tabs to load? I use a web app called WorkFlowy which takes oftentimes a minute to load, it would be great if I could access my tab groups before the web app fully loads.

**Comment by batasrki** [comment]
@Drive4ik when I use Privacy mode in Firefox Developer edition, this message shows up and my Macbook's fans start spinning like crazy. The battery drain is also maximized. There should be an option to not synchronize tabs that are opened in Privacy mode.

**Comment by Drive4ik** [comment]
@batasrki STG does not support or synchronize any private tabs or private windows

**Comment by batasrki** [comment]
@Drive4ik I realize that's the intention, but that isn't the behaviour I'm observing. I am attaching a video that shows what I mean. In the video, I'm starting from the default state, then opening up a Private mode, loading a bunch of tabs and observing Firefox's CPU usage. You will see the continuous spinner saying `Waiting for tabs to load` and you'll see Firefox's CPU spike. If I continue to keep a set of private tabs open, my laptop's fans kick in. This isn't normal behaviour.

[STG behaviour with private tabs.mp4.zip](https://github.com/Drive4ik/simple-tab-groups/files/2417471/STG.behaviour.with.private.tabs.mp4.zip)

**Comment by devurandom** [comment]
I don't think this is related to private tabs. I observe the same behaviour with multiple windows [1], but without private tabs / windows.

[1]: I have 8 open, from the time when there were no tab group addons for Firefox Quantum.

**Comment by Drive4ik** [comment]
@batasrki Oh, I understand, I already fixed this bug. It was a visual bug (I just forgot to change the icon for private windows and tabs) and this should not affect performance in any way. When a stable version of FF63 comes out, I will issue an update that fixes this bug and fixes many other bugs and some improvements

**Comment by batasrki** [comment]
@Drive4ik cool. If can help in any way to get this fixed for the next release, let me know. I can't use the private functionality in FF until it's fixed, because it drains my laptop's battery really really quickly.

**Comment by mzelyony** [comment]
I get the spinning Icon too, and I do not have any private windows open. Actually I have only one window open. I think I started seeing this after last update

**Comment by Drive4ik** [comment]
Does the problem recur on the latest version 3.3.2?

**Comment by batasrki** [comment]
@Drive4ik hey, no, since the update, I haven't seen it. Thanks!

**Comment by mzelyony** [comment]
Still spinning for me

**Comment by Drive4ik** [comment]
@mzelyony Hi! What versions of Firefox and STG are you using?

**Comment by Drive4ik** [comment]
@mzelyony Icon spinning only on private windows or normal too? 
Spinning will continue for 10 minutes and then stop, or it will stop when no tabs load.
When icon spinning - extension wait when all tabs load

**Comment by mzelyony** [comment]
It spins in the normal window, but I guess it started after I opened a private window about 2 months ago.I did not give it 10 min and closed the laptop.Will check again in the evening.I have to say I have a lot of trans there, probably 140.On the other computer where I have a total of 35 tabs across 5 groups it does not happen.

Sent from Yahoo Mail on Android 
 
  On Fri, Oct 26, 2018 at 10:30 AM, Drive4ik<notifications@github.com> wrote:   
@mzelyony Icon spinning only on private windows or normal too?
Spinning will continue for 10 minutes and then stop, or it will stop when no tabs load.
When icon spinning - extension wait when all tabs load

**Comment by mmewen** [comment]
Same for me @Drive4ik : it's been spinning for at least a week and still does since the FF 63.0 + STG 3.3.2 update. I've also tried to force all tabs to load/stop loading and waited 10 minutes and it didn't solve it. Let me know if I can help you with this!

**Comment by mmewen** [comment]
Disable/enable it didn't work either. However, removing it, closing and restarting FF and reinstalling it did the job!

**Comment by mzelyony** [comment]
did it save the tabs after reinstall?

    On Saturday, October 27, 2018, 12:14:21 PM EDT, mmewen <notifications@github.com> wrote:  
 
 
Disable/enable it didn't work either. However, removing it, closing and restarting FF and reinstalling it did the job!

**Comment by mmewen** [comment]
@mzelyony Unfortunately not, but for some reason, the tabs of all my groups have been gathered in the default view before (or at the same time as?) the "Waiting for all tabs to load" bug, so no harm on my side.

**Comment by mzelyony** [comment]
Full reinstall helped, but I had to manually rearrange all the tabs. To add to my woes on of the previous upgrades multiplied my old 140 tabs to 560. Some of the tabs were duplicated 3 or 4 times. And finally after the reinstall they all ended up in one group

**Comment by Drive4ik** [comment]
Changed the logic of waiting and reduced the waiting time, I hope this will not happen again, and if it does, it will not block work

**Comment by rmk92** [comment]
I have this problem - I can't see any tabs that are loading (so no idea which to press "escape" on!)

If I go to about:addons for simple tab groups, it repeatedly refreshes down the bottom with this message.

**Comment by Drive4ik** [comment]
@rmk92 
Can you do this?
![Screenshot_1](https://user-images.githubusercontent.com/7843031/54274234-377c2200-4590-11e9-9744-22873182f574.png)

**Comment by dpalic** [comment]
having exactly the same issue.
How I got into the situation:
- firefox crashed
- restarted firefox
- tried to get my tabs
- now getting 
   ![Screenshot_00590](https://user-images.githubusercontent.com/1399203/58751342-835aab00-849d-11e9-9c55-5c048867ea49.png)
- the debug window
  ![Screenshot_00591](https://user-images.githubusercontent.com/1399203/58751380-fcf29900-849d-11e9-9083-e5bfceee16df.png)
- and in some random cases a flickering (disappearing and reappearing) 
   ![Screenshot_00592](https://user-images.githubusercontent.com/1399203/58751394-1562b380-849e-11e9-8b8b-58a3b8013b72.png)

**Comment by Drive4ik** [comment]
@dpalic This behavior should not be at all. It is likely that your methods in Firefox itself are somehow broken ... If reinstalling the add-on with restart browser and restoring from a backup does not help, then you need to create a new Firefox profile.
