### ISSUE TITLE
All tabs are loading at once

### ISSUE THREAD

**Issue by Moore231** [Drive4ik/simple-tab-groups#249]
**Describe the bug**
When opening a tab group in a new window or switching to a different group all of the tabs load at once rather than just the last tab activated. This is only happening when after opening Firefox. This initial opening of the browser still acts as expected. 

**To Reproduce**
1. Open Firefox and the last group active opens up with only the last activated tab loading like it should
2. Click on the icon in the toolbar
3. right click the group you want to open and select open in new window
4. Window opens with the tabs and then loads them all at once

**Expected behavior**
I'd expect only the the last activated tab to load; other tabs should not load until clicked on.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 7 64 bit
 - Version 3.2.1
 - Firefox 62.0

Additional context
There used to be an option to allow this "Enable fast group switching (without loading all tab, only active)" I no longer see this option.

**Comment by Drive4ik** [comment]
I have already implemented this feature, but it will only be available with Firefox v63 and the new version of STG. Please wait for this.
https://blog.mozilla.org/addons/2018/08/31/extensions-in-firefox-63/
https://bugzilla.mozilla.org/show_bug.cgi?id=1378647
