### ISSUE TITLE
autobackup

### ISSUE THREAD

**Issue by sylvercis** [Drive4ik/simple-tab-groups#25]
Hello,
First, excuse my very bad English.

Several times with the old extension tab-groups I lost all my tabs because of firefox crash or update etc ... 
grrrr...!!!

When this extension was no longer supported, I also lost everything without the possibility of recovering them with an old version of firefox because I did not have a recent manual backup and there was no possibility of manually reload one of the automatic backups made by the extension.

Today I was forced to restart firefox in safe-mode and I lost occasionally all my tabs that were not in the currently open group.

So please, could you add an automatic backup of the tabs to your extension? It would back up once a day and keep at least the last 7 backups and make sure that old backups can not be deleted during a crash or update.

And above all it would be necessary to be able to manually reload the backup of our choice. Subsequently the choice of the backup frequency will be paramètrable ideally and the choice of backup directory.

I understand that this will ask you a lot of work but I think that it is something of primordial, what is good to organize its tabs if we lose them at the least problem that meets firefox.

Thank you in advance.

**Comment by Drive4ik** [comment]
@sylvercis 
Hi!

Sorry, but auto backup data to file are not supported by WebExtensions API. Only manual backup.
In future versions I will add functional to sync groups and settings to cloud by through FF sync profile.
And create auto backup to cloud.

**Comment by sylvercis** [comment]
OK I understand,
a solution may be to open a pop up after x time (configurable, deactivatable) to remind and allow the user to perform the manual backup comfortably.
A backup in the cloud can also be very good, I'm waiting to see how it will work.

In any case, congratulations for your excellent work on this extension.

**Comment by Drive4ik** [comment]
Thanks)
I also like solution with remind user for backup, and optionally enable auto backups groups and settings to cloud.
