### ISSUE TITLE
How does "Discard tabs after hide (this will save the RAM)" option work?

### ISSUE THREAD

**Issue by mibocs** [Drive4ik/simple-tab-groups#251]
@Drive4ik Could you please explain how this "Discard tabs after hide (this will save the RAM)" work?
Here https://github.com/denschub/firefox-tabgroups/issues/60#issuecomment-423812282 i asked this but nobody knows. Or should we use this plugin https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard instead of that discard option?

Please clarify this. Thank you

**Comment by Drive4ik** [comment]
Hi! Yes, you and @me21 right. If this option is enabled and you change group from one to other - tabs for closed group will make as "discarded", unload its from computer RAM

**Comment by Drive4ik** [comment]
But addon "Auto Tab Discard" make tab discard without reference to the group

**Comment by me21** [comment]
So, Auto Tab Discard will save even more RAM by suspending tabs in the active tabs group?

**Comment by mibocs** [comment]
So "Auto Tab Discard" is better because it discards only the inactive tabs and if someone changes between groups frequently they don't want all tabs to be discarded/unloaded but only the unused tabs.

**Comment by me21** [comment]
@mibocs In that case you may disable discard option in Simple Tab Groups and use Auto Tab Discard for tab discarding. And Simple Tab Groups will be used for tab group management only.

@Drive4ik am I right? Will STG just hide tabs if discarding is disabled?

**Comment by mibocs** [comment]
@me21 The best would be if this auto discard option was implemented in the "Simple tab groups" plugin. Or auto discard plugin should be mentioned on the "Simple Tab Groups" webpage.

**Comment by Drive4ik** [comment]
@mibocs  I do not want to clone the functional of another addon. If someone needs this functionality - let him put the addon separately. All according to your desire :)
