### ISSUE TITLE
Feature request: Multiple shortcut buttons for "Load custom group" STG plugin

### ISSUE THREAD

**Issue by slovdahl** [Drive4ik/simple-tab-groups#252]
I think it would be useful to be able to add multiple group shortcut buttons the the UI for loading custom groups.

**Comment by Drive4ik** [comment]
Unfortunately this is not possible. Firefox Webextension API allows you to create only one button per addon. You can only clone several times the add-on "Load custom group", but this is not the best solution.

**Comment by slovdahl** [comment]
Alright. Crap, that's unfortunate. So I guess a WebExtension feature request should be filed for Firefox.. :smile:
