### ISSUE TITLE
After system crash tab groups are lost

### ISSUE THREAD

**Issue by jsilence** [Drive4ik/simple-tab-groups#254]
**Describe the bug**
Linux Ubuntu 18.04 LTS on Lenovo X1 Carbon froze. After hard reset all the tab groups are gone. Firefox was opened at the time of the crash. After restart Simple Tab Group found eleven "hidden unsynchronized" tabs from the last tab group that had previously been open. These could be recovered, all the other tabs from the other tab groups are gone.

**To Reproduce**
1. Freeze your computer
2. Hard reset the machine
3. Check whether the tab groups are gone
4. ...
5. Profit

**Expected behavior**
Since open tabs are functioning as a brain extension, a rock solid operation of the extension that "Never Forgets(tm)" tabs and groups would be awesome. 

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 18.04
 - Firefox 62.0
 - Simple Tab Group Version 3.2.1

**Additional context**
I'd like to express my gratitude to the developer for this extension!

**Comment by Drive4ik** [comment]
This should not happen, but just in case I added another protection against losing tabs. Please wait next STG release

**Comment by Drive4ik** [comment]
You can try this if issue will repeat
https://www.jeffersonscher.com/ffu/scrounger.html
