### ISSUE TITLE
Question: Scheduling a nightly backup?

### ISSUE THREAD

**Issue by Tyrewt** [Drive4ik/simple-tab-groups#256]
I know of the manual backup feature, but is there a way to schedule backup of Simple Group Tabs, or would a backup of Firefox dir be sufficient for recovery?

**Comment by Drive4ik** [comment]
Hey. Yes, I already did an automatic backup feature. Please wait for FF63 and next STG release
![screenshot_1](https://user-images.githubusercontent.com/7843031/46549021-60a9cf80-c8d9-11e8-8800-95cb2b32608d.png)

**Comment by Tyrewt** [comment]
Excellent. Does the backup over-write itself upon creation, or just keep spawning indefinitely (could be a problem)?

**Comment by Drive4ik** [comment]
Each automatic backup trigger creates a separate copy.

**Comment by Tyrewt** [comment]
Potentially that could be a problem for some users that set and forget (eating-up disk space), would be great to have an option for X copies or rotation. No?  :)
