### ISSUE TITLE
How to not load all pages when switching to another tab group?

### ISSUE THREAD

**Issue by HeRo002** [Drive4ik/simple-tab-groups#257]
Hi!

In FF-52-ESR I created a backup in Tab Groups (including session data), then I opened the profile with FF Quantum 62.0.3 (64-bit), installed STG and used it to load the backup. So far so good! (Thank you very much!!)
But when I switch to another tab group, all tabs are loaded. I would like very much to only load those I click on! Cab anyone help? Thank you! 

Henrik

**Comment by Drive4ik** [comment]
I have already done support for this feature, but for its full support, wait for Firefox 63 and the new release of STG

**Comment by HeRo002** [comment]
Yes! Now - in FF 63 and STG 3.3.2 I can switch groups without problems!
