### ISSUE TITLE
"Found hidden unsynchronized tabs." (many!)

### ISSUE THREAD

**Issue by HeRo002** [Drive4ik/simple-tab-groups#258]
Hi!

In FF Quantum v.62.0.3 (64-bit) I opened a profile I had used with FF-52-ESR, where I used good old Tab Groups, and where I had created a backup with Tab Groups (including session data). So I installed STG and restored the backup. 
It looks good, but there is a huge amount of "hidden unsynchronized tabs". Is that because I restored the backup while I already had all the tabs present in one big mess? 
Should I instead restore it into an empty session/window?

**Comment by Drive4ik** [comment]
Hi! If this happens again, just press the reload addon button:
![screenshot_1](https://user-images.githubusercontent.com/7843031/46736749-7be25980-cca2-11e8-8229-9c5c10ffb711.png)
