### ISSUE TITLE
FF56 import sessionstore with old tabgroupsaddon and Multi-Account Containers

### ISSUE THREAD

**Issue by Ren108** [Drive4ik/simple-tab-groups#259]
I currently use old FF 56 with the Tabgroups Addon from Quicksilver and FF Multi-Account Containers. Now i just want to switch to Simple tab Groups addon without loosing theese Multi Account tabs. If i restore Tabgroups backup with sessiondata, the Multi Account tabs are just normal tabs.

**Comment by Drive4ik** [comment]
Hi! Tabgroups Addon on FF 56 does'nt support Multi-Account Containers and Tabgroups create backup without "container ID"

**Comment by Ren108** [comment]
So its impossible to switch with that Containers even in an newer version of FF?

**Comment by Drive4ik** [comment]
No, Firefox 57 and above has build-in support containers and my addon support it and create backups with support this containers. In stable FF you can reopen tab in needed container:
![screenshot_1](https://user-images.githubusercontent.com/7843031/47210616-1b3ad700-d39c-11e8-992e-c111d503db4c.png)
Right click on "Open new tab":
![screenshot_2](https://user-images.githubusercontent.com/7843031/47210622-1d9d3100-d39c-11e8-90d3-04352a907e9e.png)

**Comment by Ren108** [comment]
That would be a hell of a work… Maybe there will be an Workaround in the future.

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: Drive4ik <notifications@github.com>
Gesendet: Friday, October 19, 2018 11:41:04 AM
An: Drive4ik/simple-tab-groups
Cc: Ren108; Author
Betreff: Re: [Drive4ik/simple-tab-groups] FF56 import sessionstore with old tabgroupsaddon and Multi-Account Containers (#259)


No, Firefox 57 and above has build-in support containers and my addon support it and create backups with support this containers. In stable FF you can reopen tab in needed container:
[screenshot_1]<https://user-images.githubusercontent.com/7843031/47210616-1b3ad700-d39c-11e8-992e-c111d503db4c.png>
Right click on "Open new tab":
[screenshot_2]<https://user-images.githubusercontent.com/7843031/47210622-1d9d3100-d39c-11e8-90d3-04352a907e9e.png>

**Comment by Drive4ik** [comment]
No, old Tabgroups addon will no longer be supported...
