### ISSUE TITLE
Multi select of tabs 

### ISSUE THREAD

**Issue by jolau** [Drive4ik/simple-tab-groups#261]
**Is your feature request related to a problem? Please describe.**
I often forget to switch to the right tab group when I do research for another project. That's why I often end up having a lot of tabs in the wrong tab group.

**Describe the solution you'd like**
I would like to have a multi select of tabs in the tabs group manager to move a bunch of tabs at the same time to another group.

Btw. many thanks for doing this addon, waiting for it since Firefox quantum came out :)

**Comment by Drive4ik** [comment]
Hi! You have to select multiple tabs by Ctrl + left mouse click on tab in Manage groups page and after FF 63 and next STG release this feature will available in popup window.

**Comment by jolau** [comment]
Unfortunately this doesn't work. If I do Ctrl + left mouse click I just get the pop-up menu. 
<img width="267" alt="screen shot 2018-10-19 at 08 43 52" src="https://user-images.githubusercontent.com/1056376/47201751-3b0dd300-d37b-11e8-8da3-0c5b204896c2.png">

**Comment by Drive4ik** [comment]
No)) Not right, need left button)
Try another mouse button click, same as select some files in file explorer

**Comment by jolau** [comment]
Of course I'm using the left button, but Mac OS X this seems not working. I even tried cmd, alt or shift. Anyway it would be great to be able to do bulk select with shift, as it is possible in file explorers.

**Comment by Drive4ik** [comment]
Hi! Can you retest this issue with latest Firefox (64) and STG (3.3.5) ?

**Comment by jolau** [comment]
Nice, now it works! I just have a suggestion how to improve the selection behaviour. Usually on Mac (like in Finder) with CMD + Click it does single add to the bulk selection and with Shift + Click you're able to select a range. In the list view it does do range selection, but on the manage page it doesn't. Would be cool, if you could also match the behaviour as in the rest of OS X. :)
