### ISSUE TITLE
With 3.3, checkboxes cannot be checked in options

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#262]
Hello
I just upgraded to 3.3, but all the checkboxes are gone from the option panel. And no check appears when clicking on them.

![image](https://user-images.githubusercontent.com/218971/47225429-5cdc7980-d3be-11e8-9150-560723faae8a.png)

Thanks

**Comment by Drive4ik** [comment]
and they work? Tap the inclusion of a dark theme. popup shown?

**Comment by Drive4ik** [comment]
Do you see this icon? copy and open in new tab
`chrome://global/skin/icons/check.svg`

**Comment by klint** [comment]
> 
> 
> Do you see this icon? copy and open in new tab
> `chrome://global/skin/icons/check.svg`

No I don't, actually

**Comment by Drive4ik** [comment]
Do you enable param `svg.context-properties.content.enabled` ?
What version FF you are use now? 

Update STG to v3.3.1, I fix this bug :)

**Comment by Drive4ik** [comment]
And thank you :)
ok, then I close this ticket
