### ISSUE TITLE
The history on several Tabs is lost

### ISSUE THREAD

**Issue by HeRo002** [Drive4ik/simple-tab-groups#263]
Hi

There is an issue called "Feature request: Save Tab's history after switching groups". It was closed in February, long before I started using STG. 
But now I am experiencing something similar. Namely that history is gone on certain tabs. The question is exactly when the history disappeared: 

1. When I saved a backup in the old Tab Groups add-on (including session data)? 
(I don't think so, because then I would have noticed it earlier.)
2. When I imported this backup into STG?
(Again: I don't think so, because then I would have noticed it earlier.)
3. When I switched to the tab group in question and all (78) tabs started loading, so I had to close Firefox?
4. Or now, when I opened a new tab, typed a domain name, saw an existing tab with that domain in the list of suggestions and clicked on it, and thus - miraculously - I was sent to the tab group to which that tab belongs, without all (78) tabs loading and blocking the CPU completely?

Note!: 
It was a big surprise to me, that I was sent to the other tab group! 
I think I have chosen open tabs on the suggestions list several times, and every time it was seemingly moved to the present tab group(!?)

As you might have guessed, I have not yet really been able to use all my many tab groups, because ALL tabs in the group load when I try. But that's another bug (or feature), which will apparently be solved when FF63 comes out - according to this issue: "How to not load all pages when switching to another tab group?"

I hope I have explained things clearly! 

**Desktop:**
 - OS: Ubuntu 18.04.1 LTS, with Gnome 3.28.2
 - STG Version 3.2.1
 - FF ver. 62.0.3 (64-bit)

Best regards,
Henrik R.

**Comment by Drive4ik** [comment]
Hi! Yes you are right - FF 63 and STG v3.3 and above fix reload tabs on switch group.
You lost tabs history (session data) when import backup into STG. (step 2), because STG does not support tabs history and it's create backup without session data. Most likely it will always be...

**Comment by HeRo002** [comment]
That's a pity. I think tab history is an important part.

**Comment by Drive4ik** [comment]
I understand, but webextensions don't support to work with tab history and change it(

**Comment by HeRo002** [comment]
OK.

**Comment by Drive4ik** [comment]
Everything is changing))
