### ISSUE TITLE
Allow users to choose STG auto backup folder location

### ISSUE THREAD

**Issue by C-Meinert** [Drive4ik/simple-tab-groups#264]
When auto backup is enabled, STG uses the download folder set by the user in the browser settings as the location for storing the backups.

As a user I would like to be able to select the location where STG saves auto backup files separate from setting the browsers download location.

Example:
I have %USERPROFILE%\Desktop set as my download location in Firefox. When I enable auto backups in STG it creates a "STG-backups" folder on my desktop where it stores the JSON files. Changing the browser's download location to %USERPROFILE%\Downloads creates the folder in my downloads folder.

I would like to be able to have my browsers downloads continue go to were I set, but have the STG backups go to a different location such as %APPDATA%\Mozilla\Firefox\Profiles\xxxxxxx\sessionstore-backups

**Comment by Drive4ik** [comment]
Hi! Currently you can only change the download folder in Firefox preferences (about: preferences)
There are no other ways yet

**Comment by Drive4ik** [comment]
This is restriction of webextension api...

**Comment by Kaju-Bubanja** [comment]
Good to know what it is, I was surprised by it and nearly deleted it. Thank you for the great plugin, it is greatly appreciated :)
