### ISSUE TITLE
doesn't work on 62.0.3 on macOS mojave

### ISSUE THREAD

**Issue by guchukouta** [Drive4ik/simple-tab-groups#266]
**Describe the bug**
It does not work on 62.0.3 on macOS mojave.

**To Reproduce**
1. install button shows 'STOP'

**Expected behavior**
nothing

**Screenshots**
nothing

**Desktop (please complete the following information):**
 - OS: macOS mojave
 - Version 62.0.3

**Additional context**
nothing

**Comment by Drive4ik** [comment]
Hi! Please wait for FF63 stable release (should be today) and then run install/update STG
