### ISSUE TITLE
Group icon in toolbar looks darker than in STG settings

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#269]
If you compare the selected group color (yellow) in the toolbar and in the group settings, they don't match. The one in the toolbar is darker than the one I chose in the settings.
This happens also with the Firefox normal theme, not only with the dark one.
And for other colours as well.

![image](https://user-images.githubusercontent.com/218971/47369563-3da65a80-d6e4-11e8-9148-613a77624f53.png)

Thanks

**Comment by klint** [comment]
And by the way (too lazy to open a new bug ;) ), the word "onglets" in French is plural while there is only 1 "onglet". 
Using "onglet(s)" would cope better with 0, 1 and plural.
Thanks

**Comment by Drive4ik** [comment]
Hi! I know about this issue (different colors), but I don't know how to fix it and how it is connected...

https://drive4ik.github.io/simple-tab-groups/translate/index.html
Can you help me fix translations?
