### ISSUE TITLE
Share a Tab across multiple groups

### ISSUE THREAD

**Issue by khionu** [Drive4ik/simple-tab-groups#270]
I have a Communications group with my email, Google Hangouts, etc. I use Hangouts to make calls relating to another group. I would like to have my Hangouts tab in both groups, so I'm not constantly switching groups.

How it would work would be simple: tab is opened with multiple groups, and closing the tab only closes it in that group.

Alternatively to the closing mechanism, closing could be prevented with a confirmation dialogue, which gives the option of total closing or removing from that group.

**Comment by Draghmar** [comment]
FF has a pin feature that makes tab appear in every group. Maybe it will help you?

**Comment by Drive4ik** [comment]
@khionu only pinned tabs are suitable for solving your problem

**Comment by khionu** [comment]
My intent isn't to have a tab in _every_ group, though. Surely you could have a reference to one tab in multiple groups?

**Comment by Drive4ik** [comment]
At the moment, this is impossible, and too difficult for an ordinary user to understand. To do this, and came up with pinned tabs. When a tab becomes pinned, it is excluded from group and is no longer controlled by the STG.
