### ISSUE TITLE
Switching groups outside the extension causes the current group forgets the active tab

### ISSUE THREAD

**Issue by jingyu9575** [Drive4ik/simple-tab-groups#271]
**Describe the bug**
When the user switches groups outside the extension, the current group forgets the active tab.

**To Reproduce**
1. Create tab A as the add-on manager (about:addons) in group 1. Create tab B, C, D in group 2. Switch to tab C.
2. Click ☰ → Add-on Manager or press Ctrl+Shift+A. This switches to tab A in group 1.
3. Switch back to group 2 in this extension.
Actual behavior: Tab B is active.

**Expected behavior**
Tab C should be active. 

**Desktop**
 - OS: Windows
 - Version 3.3.1

**Additional context**
It is probably because [this code](https://github.com/Drive4ik/simple-tab-groups/blob/1f4a9b7641b741a61c5446c5bc67f4a6fc83bc75/addon/src/background.js#L888) marks all the tabs inactive, when the extension gets `onActivated` as the first event.

This may be a minor issue on its own, but it causes incompatibility with my extension ["Select After Closing Current"](https://addons.mozilla.org/firefox/addon/select-after-closing-current/) ([user's report](https://addons.mozilla.org/firefox/addon/select-after-closing-current/reviews/1208712/)). It is for changing the tab activating behavior after closing the current tab, similar to "Tab Open/Close Control". The relations and effects are very complicated. Please sse [this analysis](https://github.com/jingyu9575/select-after-closing-current/wiki/Analysis-of-a-problem-with-Simple-Tab-Groups) if you are interested.

**Comment by Drive4ik** [comment]
Hi! Please retest this issue on STG v3.3.2

**Comment by jingyu9575** [comment]
It works, and the incompatibility with my extension is also fixed. Thank you!

**Comment by Drive4ik** [comment]
Hi! Yes, I made a small mistake there...

**Comment by Drive4ik** [comment]
Please retest on next release

**Comment by Drive4ik** [comment]
Retest on v3.3.4

**Comment by jingyu9575** [comment]
It is fixed. Thank you!
