### ISSUE TITLE
moz-extension

### ISSUE THREAD

**Issue by AlreadyFree** [Drive4ik/simple-tab-groups#272]
**Describe the bug**
I started using this extension with an extension called LoadTabOnSelect that limits tabs from being loaded until they are clicked on. I started using this because of the massive slow down and lag when switching between tab groups. This new extension really helped speed that up. But now I noticed after restarting that all the tabs that weren't loaded at shutdown now have mov-extension added to the front of the url, which is encoded in url format so that the browser won't open it. I can't use a url decoder website to translate to ascii and fish out the original website from all the trash but that really takes some time and there are a lot of tabs. Is there any easier way to recover my tabs? And is there someway to prevent this from happening again?

**Comment by Drive4ik** [comment]
If I understand you correctly, and you want to stop using the LoadTabOnSelect extension, then you need to enable or install it, then click and load all the tabs that have this url (moz-extension) and then remove or disable this plugin (LoadTabOnSelect). Then STG will save all url addresses of the tabs in the correct format (without moz-extension)
Maybe help #201

**Comment by AlreadyFree** [comment]
@Draghmar
No, i don't want to close the tabs. I want them to remain open but paused until i select them so that when i change tab groups in simple-tab-groups my computer doesn't freeze up for minutes while all the tabs load at once. I often found myself not even bothering to change tab groups or keep my tabs organized like I'd like, for this reason.

@Drive4ik
Well, ideally, i didn't want to stop using loadtabonselect because it was helping with load times but of it's going to cause this problem i guess i will. It's still installed as of now but firefox isn't loading those pages with the moz-extension header. I can dig through the garbled url string to pull out the real url most of the time, but again, this is very time consuming. I was hoping there was a way to load these pages normally without all that. Another extension that can interpret the garbled moz-extension url?

**Comment by Drive4ik** [comment]
Have you tried using the option "Discard tabs after hide (this will save the RAM)" in STG?

**Comment by AlreadyFree** [comment]
No, i doubt i would have known that did what i was trying to do of i had noticed that setting because i wasn't trying to hide or discard any tabs but i guess i could see how that might work. As soon as i get all my tabs back I'll definitely give it a try. But how do i get my tabs reloaded normally?

**Comment by Drive4ik** [comment]
OK, then I probably did not understand what you want.
Shouldn't the LoadTabOnSelect extension restore the tab url itself and load it?

**Comment by AlreadyFree** [comment]
The LoadTabOnSelect extension didn't change the url at all, it simply paused the tab from loading in the background until i selected it. I think what happened (and i'm only guessing) is that after I shutdown firefox and restarted that any tab that hadn't been loaded at the time of shutdown wasn't read and reloaded correctly again at start up by the simple-tab-groups extension. This is an example of what the urls all look like now after restart:
moz-extension://1ffb6256-d7a4-4220-a82a-559e83f6d1a1/replaced/index.html?state=redirect&title=MeGUI%20x64%20-%20Page%2020%20-%20Doom9%27s%20Forum&url=https%3A//forum.doom9.org/showthread.php%3Ft%3D153904%26page%3D20&favIconUrl=undefined

As you can see, the web address is buried in there but its in a format that can't be normally read by firefox. I can copy the actual address out (https%3A//forum.doom9.org/showthread.php%3Ft%3D153904%26page%3D20), run it through a url decoder and come up with the actual address (https://forum.doom9.org/showthread.php?t=153904&page=20) but that's a lot of work to do hundreds of times. I don't know which extension caused the web address to become garbled or if it was a combination of the two but i was hoping there was some simple way to restore my tabs. If these two extensions don't work together than i'll just stop using LoadTabOnSelect but I still need to restore my tabs.

**Comment by Drive4ik** [comment]
I looked at the code for this extension and I can say that this plugin could not do with tabs what you now have
LoadTabOnSelect create url like: `/html/tab.html?managedUrl=`
but your tabs has urls like `/replaced/index.html?state=redirect&url=...&title=...&favIconUrl=...`

This plugin definitely has nothing to do with this, most likely some other plugin.
How many such "broken tabs" do you have?
if there is a lot - I can help you by making a small plugin that will change all url in all tabs at the same time, but for normal operation after changing url the browser will load them all, you will have to wait until they all load.

**Comment by AlreadyFree** [comment]
Yeah, i wasn't 100% sure which extension caused the problem. I just assumed it had something to do with LoadTabOnSelect3 because it was the only new extension i installed before all this happened. I just assumed that it was causing a conflict with simple-tab-groups. I also did a Firefox update around the same time which introduced the whole new tab containers feature so maybe that was part of the problem. Really not sure. But absolutely, if it's not too much trouble, I'd really appreciate help recovering my tabs. I probably have around 300. And once i get all my tabs restored I'll uninstall LoadTabOnSelect3 and try out that tab hiding feature in simple-tab-groups you were telling me about.

**Comment by Drive4ik** [comment]
Hi)
LoadTabOnSelect3 also not related to such a url as you have...
Remove/disable all extensions like `LoadTabOnSelect`, `LoadTabOnSelect3` etc

download this file
[fix_broken_urls-1.0-fx.xpi.zip](https://github.com/Drive4ik/simple-tab-groups/files/2525689/fix_broken_urls-1.0-fx.xpi.zip)

and rename it from (remove `.zip`)
`fix_broken_urls-1.0-fx.xpi.zip`
to
`fix_broken_urls-1.0-fx.xpi`

and drag & drop into `about:addons` page (install), and click here:
![screenshot_2](https://user-images.githubusercontent.com/7843031/47657136-2c07fb80-db99-11e8-911e-edb7738d60ce.png)

Wait and relax :)

**Comment by Drive4ik** [comment]
That helped?

**Comment by AlreadyFree** [comment]
Just got a chance to try it out. It reloaded all the tabs but any tab that had a corrupted url like the example you gave you just turned into a blank new tab. The original webpage wasn't recovered.

**Comment by AlreadyFree** [comment]
no that wouldn't have worked. the back button was greyed out. luckily i have the TabSessionManager extension installed so was able to restore what i had but i'm still stuck with the tabs having corrupted urls

**Comment by Drive4ik** [comment]
Ok, write here 5 - 10 examples of those broken url and I will try to make a new version. I checked this version on the LoadTabOnSelect extension and everything worked.

**Comment by AlreadyFree** [comment]
moz-extension://ea88f278-2736-4019-9433-e2bb9e9ee26b/replaced/index.html?state=open_faild&title=1ffb6256-d7a4-4220-a82a-559e83f6d1a1/replaced/index.html%3Fstate%3Dredirect%26title%3D---%2520%253A%2520%2522One%2520Fast%2520Move%2520Or%2520I%2527m%2520Gone-%2520Kerouac%2527s%2520Big%2520Sur%2522-2008%2520Documentary-The%2520Heat%2520of%2520Fame%2520Blasted%2520Jack%2520Back%2520Like%2520a%2520Literary%2520Furnace-%2520Sam%2520Shepard%252C%2520Patti%2520Smith%252C%2520Tom%2520Waits%252C%2520S.E.%2520Hinton%252C%2520Donal%2520Logue%252C%2520Lawrence%2520Ferlinghetti%2520and%2520Robert%2520Hunter%2520Report%2520on%2520This%2520Pained%2520Period%26url%3Dhttp%253A//strangerintown.podcastpeople.com/posts/56049%26favIconUrl%3Dhttp%253A//strangerintown.podcastpeople.com/favicon.png&url=about%3Ablank&favIconUrl=data%3Aimage/png%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKTWlDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVN3WJP3Fj7f92UPVkLY8LGXbIEAIiOsCMgQWaIQkgBhhBASQMWFiApWFBURnEhVxILVCkidiOKgKLhnQYqIWotVXDjuH9yntX167%2B3t%2B9f7vOec5/zOec8PgBESJpHmomoAOVKFPDrYH49PSMTJvYACFUjgBCAQ5svCZwXFAADwA3l4fnSwP/wBr28AAgBw1S4kEsfh/4O6UCZXACCRAOAiEucLAZBSAMguVMgUAMgYALBTs2QKAJQAAGx5fEIiAKoNAOz0ST4FANipk9wXANiiHKkIAI0BAJkoRyQCQLsAYFWBUiwCwMIAoKxAIi4EwK4BgFm2MkcCgL0FAHaOWJAPQGAAgJlCLMwAIDgCAEMeE80DIEwDoDDSv%2BCpX3CFuEgBAMDLlc2XS9IzFLiV0Bp38vDg4iHiwmyxQmEXKRBmCeQinJebIxNI5wNMzgwAABr50cH%2BOD%2BQ5%2Bbk4eZm52zv9MWi/mvwbyI%2BIfHf/ryMAgQAEE7P79pf5eXWA3DHAbB1v2upWwDaVgBo3/ldM9sJoFoK0Hr5i3k4/EAenqFQyDwdHAoLC%2B0lYqG9MOOLPv8z4W/gi372/EAe/tt68ABxmkCZrcCjg/1xYW52rlKO58sEQjFu9%2Bcj/seFf/2OKdHiNLFcLBWK8ViJuFAiTcd5uVKRRCHJleIS6X8y8R%2BW/QmTdw0ArIZPwE62B7XLbMB%2B7gECiw5Y0nYAQH7zLYwaC5EAEGc0Mnn3AACTv/mPQCsBAM2XpOMAALzoGFyolBdMxggAAESggSqwQQcMwRSswA6cwR28wBcCYQZEQAwkwDwQQgbkgBwKoRiWQRlUwDrYBLWwAxqgEZrhELTBMTgN5%2BASXIHrcBcGYBiewhi8hgkEQcgIE2EhOogRYo7YIs4IF5mOBCJhSDSSgKQg6YgUUSLFyHKkAqlCapFdSCPyLXIUOY1cQPqQ28ggMor8irxHMZSBslED1AJ1QLmoHxqKxqBz0XQ0D12AlqJr0Rq0Hj2AtqKn0UvodXQAfYqOY4DRMQ5mjNlhXIyHRWCJWBomxxZj5Vg1Vo81Yx1YN3YVG8CeYe8IJAKLgBPsCF6EEMJsgpCQR1hMWEOoJewjtBK6CFcJg4Qxwicik6hPtCV6EvnEeGI6sZBYRqwm7iEeIZ4lXicOE1%2BTSCQOyZLkTgohJZAySQtJa0jbSC2kU6Q%2B0hBpnEwm65Btyd7kCLKArCCXkbeQD5BPkvvJw%2BS3FDrFiOJMCaIkUqSUEko1ZT/lBKWfMkKZoKpRzame1AiqiDqfWkltoHZQL1OHqRM0dZolzZsWQ8ukLaPV0JppZ2n3aC/pdLoJ3YMeRZfQl9Jr6Afp5%2BmD9HcMDYYNg8dIYigZaxl7GacYtxkvmUymBdOXmchUMNcyG5lnmA%2BYb1VYKvYqfBWRyhKVOpVWlX6V56pUVXNVP9V5qgtUq1UPq15WfaZGVbNQ46kJ1Bar1akdVbupNq7OUndSj1DPUV%2Bjvl/9gvpjDbKGhUaghkijVGO3xhmNIRbGMmXxWELWclYD6yxrmE1iW7L57Ex2Bfsbdi97TFNDc6pmrGaRZp3mcc0BDsax4PA52ZxKziHODc57LQMtPy2x1mqtZq1%2BrTfaetq%2B2mLtcu0W7eva73VwnUCdLJ31Om0693UJuja6UbqFutt1z%2Bo%2B02PreekJ9cr1Dund0Uf1bfSj9Rfq79bv0R83MDQINpAZbDE4Y/DMkGPoa5hpuNHwhOGoEctoupHEaKPRSaMnuCbuh2fjNXgXPmasbxxirDTeZdxrPGFiaTLbpMSkxeS%2BKc2Ua5pmutG003TMzMgs3KzYrMnsjjnVnGueYb7ZvNv8jYWlRZzFSos2i8eW2pZ8ywWWTZb3rJhWPlZ5VvVW16xJ1lzrLOtt1ldsUBtXmwybOpvLtqitm63Edptt3xTiFI8p0in1U27aMez87ArsmuwG7Tn2YfYl9m32zx3MHBId1jt0O3xydHXMdmxwvOuk4TTDqcSpw%2BlXZxtnoXOd8zUXpkuQyxKXdpcXU22niqdun3rLleUa7rrStdP1o5u7m9yt2W3U3cw9xX2r%2B00umxvJXcM970H08PdY4nHM452nm6fC85DnL152Xlle%2B70eT7OcJp7WMG3I28Rb4L3Le2A6Pj1l%2Bs7pAz7GPgKfep%2BHvqa%2BIt89viN%2B1n6Zfgf8nvs7%2Bsv9j/i/4XnyFvFOBWABwQHlAb2BGoGzA2sDHwSZBKUHNQWNBbsGLww%2BFUIMCQ1ZH3KTb8AX8hv5YzPcZyya0RXKCJ0VWhv6MMwmTB7WEY6GzwjfEH5vpvlM6cy2CIjgR2yIuB9pGZkX%2BX0UKSoyqi7qUbRTdHF09yzWrORZ%2B2e9jvGPqYy5O9tqtnJ2Z6xqbFJsY%2BybuIC4qriBeIf4RfGXEnQTJAntieTE2MQ9ieNzAudsmjOc5JpUlnRjruXcorkX5unOy553PFk1WZB8OIWYEpeyP%2BWDIEJQLxhP5aduTR0T8oSbhU9FvqKNolGxt7hKPJLmnVaV9jjdO31D%2BmiGT0Z1xjMJT1IreZEZkrkj801WRNberM/ZcdktOZSclJyjUg1plrQr1zC3KLdPZisrkw3keeZtyhuTh8r35CP5c/PbFWyFTNGjtFKuUA4WTC%2BoK3hbGFt4uEi9SFrUM99m/ur5IwuCFny9kLBQuLCz2Lh4WfHgIr9FuxYji1MXdy4xXVK6ZHhp8NJ9y2jLspb9UOJYUlXyannc8o5Sg9KlpUMrglc0lamUycturvRauWMVYZVkVe9ql9VbVn8qF5VfrHCsqK74sEa45uJXTl/VfPV5bdra3kq3yu3rSOuk626s91m/r0q9akHV0IbwDa0b8Y3lG19tSt50oXpq9Y7NtM3KzQM1YTXtW8y2rNvyoTaj9nqdf13LVv2tq7e%2B2Sba1r/dd3vzDoMdFTve75TsvLUreFdrvUV99W7S7oLdjxpiG7q/5n7duEd3T8Wej3ulewf2Re/ranRvbNyvv7%2ByCW1SNo0eSDpw5ZuAb9qb7Zp3tXBaKg7CQeXBJ9%2BmfHvjUOihzsPcw83fmX%2B39QjrSHkr0jq/dawto22gPaG97%2BiMo50dXh1Hvrf/fu8x42N1xzWPV56gnSg98fnkgpPjp2Snnp1OPz3Umdx590z8mWtdUV29Z0PPnj8XdO5Mt1/3yfPe549d8Lxw9CL3Ytslt0utPa49R35w/eFIr1tv62X3y%2B1XPK509E3rO9Hv03/6asDVc9f41y5dn3m978bsG7duJt0cuCW69fh29u0XdwruTNxdeo94r/y%2B2v3qB/oP6n%2B0/rFlwG3g%2BGDAYM/DWQ/vDgmHnv6U/9OH4dJHzEfVI0YjjY%2BdHx8bDRq98mTOk%2BGnsqcTz8p%2BVv9563Or59/94vtLz1j82PAL%2BYvPv655qfNy76uprzrHI8cfvM55PfGm/K3O233vuO%2B638e9H5ko/ED%2BUPPR%2BmPHp9BP9z7nfP78L/eE8/sl0p8zAAAAIGNIUk0AAHolAACAgwAA%2Bf8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAjSURBVHjaYvz//z8DJYCJgUIwasCoAaMGDBYDAAAAAP//AwBjmgMdmAkTNwAAAABJRU5ErkJggg%3D%3D

moz-extension://ea88f278-2736-4019-9433-e2bb9e9ee26b/replaced/index.html?state=open_faild&title=1ffb6256-d7a4-4220-a82a-559e83f6d1a1/replaced/index.html%3Fstate%3Dredirect%26title%3DBest%2520animated%2520movies%2520ever%2520made%2520including%2520Disney%2520and%2520anime%26url%3Dhttps%253A//www.timeout.com/newyork/film/the-100-best-animated-movies%2523tab_panel_10%26favIconUrl%3Dhttps%253A//dist.timeout.com/dist/img/TO-192x192-android.png&url=about%3Ablank&favIconUrl=data%3Aimage/png%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAACXBIWXMAAAsTAAALEwEAmpwYAAAKTWlDQ1BQaG90b3Nob3AgSUNDIHByb2ZpbGUAAHjanVN3WJP3Fj7f92UPVkLY8LGXbIEAIiOsCMgQWaIQkgBhhBASQMWFiApWFBURnEhVxILVCkidiOKgKLhnQYqIWotVXDjuH9yntX167%2B3t%2B9f7vOec5/zOec8PgBESJpHmomoAOVKFPDrYH49PSMTJvYACFUjgBCAQ5svCZwXFAADwA3l4fnSwP/wBr28AAgBw1S4kEsfh/4O6UCZXACCRAOAiEucLAZBSAMguVMgUAMgYALBTs2QKAJQAAGx5fEIiAKoNAOz0ST4FANipk9wXANiiHKkIAI0BAJkoRyQCQLsAYFWBUiwCwMIAoKxAIi4EwK4BgFm2MkcCgL0FAHaOWJAPQGAAgJlCLMwAIDgCAEMeE80DIEwDoDDSv%2BCpX3CFuEgBAMDLlc2XS9IzFLiV0Bp38vDg4iHiwmyxQmEXKRBmCeQinJebIxNI5wNMzgwAABr50cH%2BOD%2BQ5%2Bbk4eZm52zv9MWi/mvwbyI%2BIfHf/ryMAgQAEE7P79pf5eXWA3DHAbB1v2upWwDaVgBo3/ldM9sJoFoK0Hr5i3k4/EAenqFQyDwdHAoLC%2B0lYqG9MOOLPv8z4W/gi372/EAe/tt68ABxmkCZrcCjg/1xYW52rlKO58sEQjFu9%2Bcj/seFf/2OKdHiNLFcLBWK8ViJuFAiTcd5uVKRRCHJleIS6X8y8R%2BW/QmTdw0ArIZPwE62B7XLbMB%2B7gECiw5Y0nYAQH7zLYwaC5EAEGc0Mnn3AACTv/mPQCsBAM2XpOMAALzoGFyolBdMxggAAESggSqwQQcMwRSswA6cwR28wBcCYQZEQAwkwDwQQgbkgBwKoRiWQRlUwDrYBLWwAxqgEZrhELTBMTgN5%2BASXIHrcBcGYBiewhi8hgkEQcgIE2EhOogRYo7YIs4IF5mOBCJhSDSSgKQg6YgUUSLFyHKkAqlCapFdSCPyLXIUOY1cQPqQ28ggMor8irxHMZSBslED1AJ1QLmoHxqKxqBz0XQ0D12AlqJr0Rq0Hj2AtqKn0UvodXQAfYqOY4DRMQ5mjNlhXIyHRWCJWBomxxZj5Vg1Vo81Yx1YN3YVG8CeYe8IJAKLgBPsCF6EEMJsgpCQR1hMWEOoJewjtBK6CFcJg4Qxwicik6hPtCV6EvnEeGI6sZBYRqwm7iEeIZ4lXicOE1%2BTSCQOyZLkTgohJZAySQtJa0jbSC2kU6Q%2B0hBpnEwm65Btyd7kCLKArCCXkbeQD5BPkvvJw%2BS3FDrFiOJMCaIkUqSUEko1ZT/lBKWfMkKZoKpRzame1AiqiDqfWkltoHZQL1OHqRM0dZolzZsWQ8ukLaPV0JppZ2n3aC/pdLoJ3YMeRZfQl9Jr6Afp5%2BmD9HcMDYYNg8dIYigZaxl7GacYtxkvmUymBdOXmchUMNcyG5lnmA%2BYb1VYKvYqfBWRyhKVOpVWlX6V56pUVXNVP9V5qgtUq1UPq15WfaZGVbNQ46kJ1Bar1akdVbupNq7OUndSj1DPUV%2Bjvl/9gvpjDbKGhUaghkijVGO3xhmNIRbGMmXxWELWclYD6yxrmE1iW7L57Ex2Bfsbdi97TFNDc6pmrGaRZp3mcc0BDsax4PA52ZxKziHODc57LQMtPy2x1mqtZq1%2BrTfaetq%2B2mLtcu0W7eva73VwnUCdLJ31Om0693UJuja6UbqFutt1z%2Bo%2B02PreekJ9cr1Dund0Uf1bfSj9Rfq79bv0R83MDQINpAZbDE4Y/DMkGPoa5hpuNHwhOGoEctoupHEaKPRSaMnuCbuh2fjNXgXPmasbxxirDTeZdxrPGFiaTLbpMSkxeS%2BKc2Ua5pmutG003TMzMgs3KzYrMnsjjnVnGueYb7ZvNv8jYWlRZzFSos2i8eW2pZ8ywWWTZb3rJhWPlZ5VvVW16xJ1lzrLOtt1ldsUBtXmwybOpvLtqitm63Edptt3xTiFI8p0in1U27aMez87ArsmuwG7Tn2YfYl9m32zx3MHBId1jt0O3xydHXMdmxwvOuk4TTDqcSpw%2BlXZxtnoXOd8zUXpkuQyxKXdpcXU22niqdun3rLleUa7rrStdP1o5u7m9yt2W3U3cw9xX2r%2B00umxvJXcM970H08PdY4nHM452nm6fC85DnL152Xlle%2B70eT7OcJp7WMG3I28Rb4L3Le2A6Pj1l%2Bs7pAz7GPgKfep%2BHvqa%2BIt89viN%2B1n6Zfgf8nvs7%2Bsv9j/i/4XnyFvFOBWABwQHlAb2BGoGzA2sDHwSZBKUHNQWNBbsGLww%2BFUIMCQ1ZH3KTb8AX8hv5YzPcZyya0RXKCJ0VWhv6MMwmTB7WEY6GzwjfEH5vpvlM6cy2CIjgR2yIuB9pGZkX%2BX0UKSoyqi7qUbRTdHF09yzWrORZ%2B2e9jvGPqYy5O9tqtnJ2Z6xqbFJsY%2BybuIC4qriBeIf4RfGXEnQTJAntieTE2MQ9ieNzAudsmjOc5JpUlnRjruXcorkX5unOy553PFk1WZB8OIWYEpeyP%2BWDIEJQLxhP5aduTR0T8oSbhU9FvqKNolGxt7hKPJLmnVaV9jjdO31D%2BmiGT0Z1xjMJT1IreZEZkrkj801WRNberM/ZcdktOZSclJyjUg1plrQr1zC3KLdPZisrkw3keeZtyhuTh8r35CP5c/PbFWyFTNGjtFKuUA4WTC%2BoK3hbGFt4uEi9SFrUM99m/ur5IwuCFny9kLBQuLCz2Lh4WfHgIr9FuxYji1MXdy4xXVK6ZHhp8NJ9y2jLspb9UOJYUlXyannc8o5Sg9KlpUMrglc0lamUycturvRauWMVYZVkVe9ql9VbVn8qF5VfrHCsqK74sEa45uJXTl/VfPV5bdra3kq3yu3rSOuk626s91m/r0q9akHV0IbwDa0b8Y3lG19tSt50oXpq9Y7NtM3KzQM1YTXtW8y2rNvyoTaj9nqdf13LVv2tq7e%2B2Sba1r/dd3vzDoMdFTve75TsvLUreFdrvUV99W7S7oLdjxpiG7q/5n7duEd3T8Wej3ulewf2Re/ranRvbNyvv7%2ByCW1SNo0eSDpw5ZuAb9qb7Zp3tXBaKg7CQeXBJ9%2BmfHvjUOihzsPcw83fmX%2B39QjrSHkr0jq/dawto22gPaG97%2BiMo50dXh1Hvrf/fu8x42N1xzWPV56gnSg98fnkgpPjp2Snnp1OPz3Umdx590z8mWtdUV29Z0PPnj8XdO5Mt1/3yfPe549d8Lxw9CL3Ytslt0utPa49R35w/eFIr1tv62X3y%2B1XPK509E3rO9Hv03/6asDVc9f41y5dn3m978bsG7duJt0cuCW69fh29u0XdwruTNxdeo94r/y%2B2v3qB/oP6n%2B0/rFlwG3g%2BGDAYM/DWQ/vDgmHnv6U/9OH4dJHzEfVI0YjjY%2BdHx8bDRq98mTOk%2BGnsqcTz8p%2BVv9563Or59/94vtLz1j82PAL%2BYvPv655qfNy76uprzrHI8cfvM55PfGm/K3O233vuO%2B638e9H5ko/ED%2BUPPR%2BmPHp9BP9z7nfP78L/eE8/sl0p8zAAAAIGNIUk0AAHolAACAgwAA%2Bf8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAAjSURBVHjaYvz//z8DJYCJgUIwasCoAaMGDBYDAAAAAP//AwBjmgMdmAkTNwAAAABJRU5ErkJggg%3D%3D

**Comment by Drive4ik** [comment]
Now everything is clear
That's why all the tabs are broken (left empty):
![screenshot_1](https://user-images.githubusercontent.com/7843031/47793299-a4e88e00-dd26-11e8-979b-3061dddcda39.png)

You have the worst case .... some addon collapsed and broke all urls.
Like matrioshka ...
But I can try to return everything, and pull out the url from the tab title ...
![screenshot_2](https://user-images.githubusercontent.com/7843031/47793331-b336aa00-dd26-11e8-9b45-e15341d7b8e8.png)

I will not guarantee that all tabs will be restored, but it's worth a try.
Try this version
[fix_broken_urls-1.1-fx.xpi.zip](https://github.com/Drive4ik/simple-tab-groups/files/2534805/fix_broken_urls-1.1-fx.xpi.zip)

**Comment by AlreadyFree** [comment]
ok, I've got it pretty much squared away now. Like you said, your fix-broken-urls extension didn't restore all the tabs but it did most of them. strangely enough the ones that it didn't fix were the ones that had been paused by the LoadOnSelect3 extension. I could tell because they had the paused icon in the navbar that that extension added to tabs that it had paused. So I spent the last 3 hours restoring all those manually and now everything's back to normal. Still not sure what caused the problem but I uninstally LoadOnSelect3 and Tab Session Manager and am just using the auto backup feature in simple-tab-groups to save backups of my sessions. Also I turned on the 'discard tabs after hide' in the simple-tab-groups options and that solved my problem of massive cpu & memory use when changing tab groups. Although I think you should change the name of that feature because it makes it confusing about what it does, maybe 'auto pause background tabs' or something similiar. But all in all thanks so much for your help with this issue, it was much appreciated.

**Comment by Drive4ik** [comment]
I am glad to help)
