### ISSUE TITLE
How to easily move a tab to another group?

### ISSUE THREAD

**Issue by HeRo002** [Drive4ik/simple-tab-groups#273]
Am I missing something obvious? 
I can't find an easy way to move a tab to another group?
The only way I found was "Manage groups", where I need to drag the tab with the mouse. But this is VERY inconvenient, when the destination-group is far outside the currently visible groups! 
In Tab Groups you could just right-click on a tab, then choose 'move to another group' on the menu.

**Comment by Drive4ik** [comment]
Hi! You can try this way:
![screenshot_1](https://user-images.githubusercontent.com/7843031/47431003-98eb5200-d7a3-11e8-8a93-8c941ab585b1.png)

And you can select multiple tabs by CTRL + left mouse click on tab

**Comment by Drive4ik** [comment]
Or am I misunderstanding something?

**Comment by HeRo002** [comment]
Brilliant! Thank you! I WAS overlooking the obvious! :-) 
But I can't get selecting and moving multiple tabs with Ctrl + 'left mouse click' on tabs on that list, to work. :-(

**Comment by Drive4ik** [comment]
![screenshot_1](https://user-images.githubusercontent.com/7843031/47436394-1c5e7080-d7af-11e8-8700-fc85408be136.png)

**Comment by Drive4ik** [comment]
![move-multiple-tabs](https://user-images.githubusercontent.com/7843031/47436487-4152e380-d7af-11e8-8d0f-c72870755da6.gif)

**Comment by HeRo002** [comment]
I don't know how you do it? It doesn't work on my laptop.

**Comment by Drive4ik** [comment]
Before click on tab - press CTRL button

**Comment by HeRo002** [comment]
Yes, I am keeping Ctrl pressed before during and after 'left mouse clicking' on several tabs. But in the end, when I right-click and choose a group, only one tab gets moved...

**Comment by Drive4ik** [comment]
Ok, do the tabs have a blue bar on the left when they are selected (with CTRL pressed)?

**Comment by HeRo002** [comment]
No. And actually focus is switched to the tab I Ctrl+left-mouse-click on. 
(Did I mention I use Ubuntu 18.04.1 LTS? The mouse is a Logitech)

**Comment by Drive4ik** [comment]
I replicate this bug when press "right Ctrl" button, "left Ctrl" button works well on Ubuntu 16.04
P.S. on windows right and left Ctrl works well..

**Comment by HeRo002** [comment]
I use a Lenovo L570 + an external keyboard. That gives me 4 Ctrl-keys. But it doesn't matter which of them I press...

**Comment by HeRo002** [comment]
All 4 Ctrl-keys are "17" (Shift is 16). 
That page doesn't seem to react to mouse-buttons.

**Comment by Drive4ik** [comment]
Does ctrl + click work on the "manage groups" page?

**Comment by HeRo002** [comment]
In the sense that it marks them with a blue frame - yes. But when I right-click I only get 2 menu-items: 'Set tab icon...' + 'Update thumbnail...'.

**Comment by Drive4ik** [comment]
Yes, it should be so. There should be a similar behavior in the pop-up. It is strange that everything works on one page (manage groups) does not work on another (popup) ...

**Comment by HeRo002** [comment]
Yes. I am sorry for the strangeness... :-)

**Comment by Drive4ik** [comment]
Does restarting the browser have any effect?
And yet, any tabs are loading at the moment when you press Ctrl + click?

**Comment by Drive4ik** [comment]
Do you use Firefox 63 and STG v3.3.2?

**Comment by HeRo002** [comment]
Now I do. And that seems to have changed the bug slightly. Now, when I hold down Ctrl and left-mouse-click on tabs, in the 'pull down menu', there are blue marks to the left on the tabs for 1-2 seconds. Then they disappear again.

**Comment by Drive4ik** [comment]
Well, of course) it should be so! it was intended!)) as I had not guessed?
For the future - you need to always update the browser and the plugin to the latest version and try there. In previous versions, this functionality was not available, so it did not work.

**Comment by HeRo002** [comment]
According to Ubuntu, my software is updated daily. 
But anyway - now when I try again, I CAN move several tabs at once! So thank you!!

**Comment by Drive4ik** [comment]
You are welcome!

**Comment by HeRo002** [comment]
> Now I do. And that seems to have changed the bug slightly. Now, when I hold down Ctrl and left-mouse-click on tabs, in the 'pull down menu', there are blue marks to the left on the tabs for 1-2 seconds. Then they disappear again.

This is not very practical. When I have several tabs beneath each other that I want to move to another group, I start clicking on them, and when I have clicked on 4-5 suddenly all the blue marks disappear and none of them are marked. So it still doesn't really work. 
I use STG 3.3.4 with FF ver. 63.0 (64-bit), and Vertical Tabs Reloaded 0.11.0.

**Comment by Drive4ik** [comment]
@HeRo002 Hi!
I try to fix this this bug in 7b4cff0e62df24d2ffe6f87177e99a74784a7369
please wait next release of STG
