### ISSUE TITLE
Lost all Tab Groups with ff 62.0

### ISSUE THREAD

**Issue by propagare** [Drive4ik/simple-tab-groups#275]
. Build **Describe the bug**
All created simple tab groups and all my urls in it are gone.

**To Reproduce**
Not reproducible

**Expected behavior**
Restore all my tab groups and all links in it. 

**Screenshots**
Lots of single links in the overview

**Desktop (please complete the following information):**
 - OS: Windows 10 - 1709 b16299.665
 - Version Firefox 62.0 (now 63.0)

**Additional context**
Please tell me we have a backup file somewhere.

**Comment by Drive4ik** [comment]
Hi! Tell me, under what conditions were the groups lost?

**Comment by propagare** [comment]
I wish I could. There were from my point of view NO special conditions. I restart the browser and they are gone. Maybe in conflict with other Addons? I don't know. I can provide additional information if you want. Any chance to recover my tabs/links?

**Comment by Drive4ik** [comment]
At the time when they disappeared, what version of Firefox and STG you has?
Try find folder "STG-backups" in Firefox download folder

**Comment by propagare** [comment]
I search my PC for folders with the following names "STG-backups" "STG" and "-backups", nothing. I use STG version: 3.2.1 (no update since the crash fmpov). Firefox 62.0

**Comment by Drive4ik** [comment]
This is bad .. Firefox 63 and STG 3.3 has auto backups ...

**Comment by propagare** [comment]
Why wasn't STG not updated automatically?

**Comment by Drive4ik** [comment]
STG 3.3 required Firefox version 63

**Comment by propagare** [comment]
Are there maybe some NOT STG related backup possibilities? And does STG 3.3 also come with a restore? Thanks for your help.

**Comment by propagare** [comment]
Maybe this offers a solution: https://support.mozilla.org/en-US/questions/1221836 / https://www.jeffersonscher.com/ffu/scrounger.html

**Comment by Drive4ik** [comment]
Cool, have you tried this?

**Comment by propagare** [comment]
Yes, I double checked it, and it works.

**Comment by Drive4ik** [comment]
Ok, did you manage to solve your problem?

**Comment by propagare** [comment]
Yes, thanks. Please consider to use the information for STG as well.

**Comment by Drive4ik** [comment]
Ok, thanks
