### ISSUE TITLE
Use panorama-view plugin/code for the "manage group" functionnality

### ISSUE THREAD

**Issue by gagarine** [Drive4ik/simple-tab-groups#277]
https://github.com/photodiode/panorama-view is exactly the same functionality than "manage group" in STG. I love STG, and use the "manage group" functionality very rarely (but it's still useful!).

But wouldn't be possible to share some code? Or perhaps even integrate both plugin? Can't they share the same way of storing group information so you can use both together or switch between one or the other plugin?

Some time ago I asked the difference between the two plugin in https://github.com/photodiode/panorama-view/issues/94

**Comment by Drive4ik** [comment]
This is impossible .. Addons have different code, logic, functionality...
