### ISSUE TITLE
Browser Console display a lot of error

### ISSUE THREAD

**Issue by gagarine** [Drive4ik/simple-tab-groups#279]
Don't really know what they are. But the ID is from STG.
Mainly we have` Error: Could not establish connection. Receiving end does not exist.`. Clicking on the source give nothings.

![image](https://user-images.githubusercontent.com/164074/47680058-19f08200-dbc6-11e8-8c2e-e8790be01647.png)

**Comment by Drive4ik** [comment]
Do not pay attention to it. Firefox writes that there is no connection, but everything is working properly. I once tried to solve this problem, but after calling the function for "connect", the error still appears, but everything works.

**Comment by gagarine** [comment]
I see. Perhaps is this https://stackoverflow.com/questions/44673632/firefox-webextension-error-could-not-establish-connection-receiving-end-does-n#44683772 no?

**Comment by Drive4ik** [comment]
Yes that's it. I tried to do it but nothing happened. Let it work that way)))
