### ISSUE TITLE
Multiple issues if # of tab groups exceeds 12

### ISSUE THREAD

**Issue by Philip-Sutton** [Drive4ik/simple-tab-groups#28]
I really like this Firefox add-on.  Thanks so much for creating it.

In a special circumstance weaknesses in the software are exposed.  It seems to me that multiple issues arise if the number of tab groups exceeds about 12.  As the number of tab groups rise above twelve the special functions (creating new groups and managing the tabs) are no longer accessible/shown on the list that drops down from the FF toolbar.  Also there is no facility to have more than one column listing the groups or to allow for scroling up and down the list.  And also the ability to open a new group by clicking on its name in the list breaks and the tab content of groups is corrupted.  To fix things I had to reduce the number of groups (to 12 or below) by deletion and then delete and recreate the groups that had become corrupted.

Philip

Philip.Sutton@green-innovations.asn.au

**Comment by Drive4ik** [comment]
@Philip-Sutton Please, update addon to latest version and re-test issues

![many-groups-list](https://user-images.githubusercontent.com/7843031/34784238-67d8838a-f636-11e7-8415-2ffb4cfe6e88.gif)

**Comment by Philip-Sutton** [comment]
I'm using v57.0.4 of Firefox (64 bit) on Windows 10 and installed v2.2 of simple tab groups.  But when I create extra tab groups the scroll bar doesn't show up to the functions at the end of the pop-up window disappear still.  I'm not sure why my set up doesn;t behave like you showed in the demo above on git hub.
Philip

**Comment by Drive4ik** [comment]
@Philip-Sutton 
The fact is that I also use windows 10 x64 and I and I did not have such a problem with other add-ons.
Maybe has conflicts with other addon(s)?

Can you give me screenshot/GIF animation or video of this problem?

*You can create GIFs through http://www.screentogif.com/*

**Comment by Philip-Sutton** [comment]
OK - I will make an animated gif. 

I had a strange thing happen.  At first I could get the scroll bar to show.  Then all of a sudden I noticed it was there! (so I amended by comment above.  Now it's not there again!  (I was wondering about the issue of a conflict with another add on.)  I've got a work deadline that will keep me busy for the next couple of days.  I'll come back to this in a few days.  Sorry about the delay.  Philip

**Comment by Philip-Sutton** [comment]
OK - I can now reliably reproduce part of the new behaviour.  If I create a bunch of new groups so that the "Create new group" function and the "Manage groups" function are pushed out of sight - then the scroll bar appears.  But I can't get the scroll bar to go far enough down to reveal the  "Create new group" and the "Manage groups" functions.      If I keep creating groups through the "Create group" function that I can access via a tab label right click, then the scroll bar will allow me to see all the tab groups in the drop down list.  But I still can't get it to take me down to the "Create new group" and the "Manage groups" functions.  (I'll have to leave it now and do my work.)  Cheers, Philip

**Comment by Drive4ik** [comment]
You can try to go bottom by keyboard key `Down` arrow.

**Comment by Drive4ik** [comment]
Maybe you has these problem?
![stg-missed-buttons](https://user-images.githubusercontent.com/7843031/35005767-3d554546-fafd-11e7-8327-db2cfbe30777.gif)

**Comment by Philip-Sutton** [comment]
On my system, the down arrow doesn't reveal the ""Create new group" function and the "Manage groups" functions for me.  It just rotates through the groups.

**Comment by Philip-Sutton** [comment]
I have the simple tab groups button always showing on my toolbar - because I use it so often.  (It's not in the >> overflow drop down.)

**Comment by Philip-Sutton** [comment]
I've 'solved' the problem! (Kind of a work around.) If I put the simple tab groups button on the very top toolbar (the one with the main menu items) then it works pretty much correctly. The 'Manage groups' function is partly obscured at the bottom of the pop up screen, but not so mch that I can't use it.  So I'll stick with this now.  Thanks.  Cheers, Philip   (Over and out, I really do need to do my work now!!!  Running late!!)

**Comment by Drive4ik** [comment]
OK))

**Comment by Philip-Sutton** [comment]
Hi - he's a recording (animated gif) showing what's happening on my machine now since loading v2.2.

(
![philip s simple tab groups](https://user-images.githubusercontent.com/1549449/35054289-51d0ea80-fc00-11e7-9546-a81c53cbb220.gif)
I hope the gif works!! First time I've done this.)

**Comment by Drive4ik** [comment]
Hi @Philip-Sutton 

Please, update addon to latest version 2.2.1 and retest this issue. And, please, retest issue if put STG browser button to hidden menu bar:
![screenshot_4](https://user-images.githubusercontent.com/7843031/35058554-fe67a346-fbc0-11e7-82ff-ceb3cc27e61b.png)
or other menu bars.

**Comment by Philip-Sutton** [comment]
I just tested the new version 2.2.1 

It works better than before in that it seems to judge how big the screen space is given where the button is placed.  Clever!!

But this time I could see any of the "Manage groups" and the settings button right at the botton.   Also the scroll bar doesn't get the list to scroll as far as it will go.  But I was able to get the last bit of movement using the mouse scroll wheel.  I think you can see this in the gif below.  (I'm getting quicker at making gifs - now I know how to do it!! (What a surprise.)

![philip s simple tab groups take 2](https://user-images.githubusercontent.com/1549449/35061386-31c853d0-fc15-11e7-8d09-0739b241cb10.gif)
