### ISSUE TITLE
Ctrl+Tab Cycle through tabs in recently used order

### ISSUE THREAD

**Issue by falolaf** [Drive4ik/simple-tab-groups#281]
Hello, 

With FF63, with new profiles, the default behaviour is to cycle through tabs in recently used order. (And with thumbnails.)

Would it be possible with STG to cycle through only the tabs in the currently active tab group? I.e. only take unhidden tabs into account. As it is now, the recent tabs can belong to any tab group it seems.

I did go through all issues, open and closed, but didn't find any issue related to this scenario.

/Anders

**Comment by Drive4ik** [comment]
Currently, the WebExtensions API does not have the ability to change this. And in the very Firefox there is no such possibility. For some reason, it shows both hidden and unhidden tabs ... You can create bug into https://bugzilla.mozilla.org/ to exclude hidden tabs in menu

**Comment by falolaf** [comment]
There is allready a bug filed:
https://bugzilla.mozilla.org/show_bug.cgi?id=1488168

**Comment by Drive4ik** [comment]
I wrote a comment in that ticket, I think I should help.
