### ISSUE TITLE
All groups are gone after crash of computer - Tabs are found and can be saved in new group

### ISSUE THREAD

**Issue by jsilence** [Drive4ik/simple-tab-groups#282]
**Describe the bug**
After a complete freeze of my machine all the groups are gone. Simple Tabs finds the dangling tabs and offers to save them into a new group (or into the current group, or forget about them).

So all the tabs are safe, but they have to be resorted into new groups. 

**To Reproduce**
* Make your computer freeze
* Hard reset the machine
* Poof

**Expected behavior**
The groups and the saved and sorted tabs should survive a computer crash

**Screenshots**
Sorry, too late for a screenshot. Already saved the dangling  tabs into a new group. 

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Firefox version: 63
 - Simple Tab Groups version: Simple Groups updated to 3.3.2 after this incident. No idea whether the version update has anything to do with the loss of the groups.

**Additional context**
I really like this extension a lot and I am grateful that the developer is providing it. 
Thanks a lot and keep up the good work!

**Comment by Drive4ik** [comment]
Hi, do you remember what your previous version of add-on was?
If it was 3.3+ then look for the STG-backups folder in the download folder specified in the Firefox settings

**Comment by Drive4ik** [comment]
"current status" does it mean empty?

**Comment by jsilence** [comment]
No, I chose to save the "hidden" tabs in a new group as offered by the extension. Thus this group and all the tabs is present in the backup file.

I guess the previous version was pre 3.3, thus no backup files from before.

But no problem. I am happy that the extension makes backups now.

**Comment by Drive4ik** [comment]
Ok, hopefully backups will help in the future.
