### ISSUE TITLE
If Simple Tab Groups makes 'STG-backups,' please save in Mozilla profile rather than user's home

### ISSUE THREAD

**Issue by dchmelik** [Drive4ik/simple-tab-groups#284]
If Simple Tab Groups makes a STG-backups directory, please save that in the Mozilla profile directory rather than root of the user's home directory (rarely used, clutter.)

**Comment by Drive4ik** [comment]
Webextension does not allow you to change the folder for downloading

**Comment by dchmelik** [comment]
Then can we have an option to not download them?  It seems all one needs is a text list, not a download.  Also, I know other extensions save data in the Mozilla profile directory rather than the user's downloads directory (which I changed to my home folder.)

**Comment by Drive4ik** [comment]
Yes, the data is saved in the Firefox profile folder (`about:support -> Profile folder -> browser-extension-data\simple-tab-groups@drive4ik`), but it happens that it is deleted there for some unknown reason, after a crash of Firefox for example.
If you do not want to create backups - you can turn it off in the addon settings

**Comment by Draghmar** [comment]
Oh, so there's no way for making option to choose your own path to save backups?

**Comment by Boddlnagg** [comment]
I regularly see failed downloads for STG backups in the download history, most recently `stg-backup-2018-11-06@drive4ik.json`. This only happens sometimes, though. For example, the file from today (2018-11-07) exists in the STL-backups folder.

**Comment by poke** [comment]
@Drive4ik Do you happen to know if there’s some bug on Bugzilla to eventually allow extensions to store data on the file system directly? E.g. limited to some extension folder within the profile? If there isn’t one, would it help to ask for something like this?

**Comment by braydenhouston** [comment]
@Boddlnagg I am seeing that issue as well. It is driving me crazy! 

The failed backup downloads even happen on most manual backups I try to run.

I would guess that isn't the intended behaviors right @Drive4ik?

**Comment by Drive4ik** [comment]
Hi all!
I partially fixed this issue in #314 , and fix failed downloads in #313

**Comment by flowrean** [comment]
@nrutman That doesn't seem to work on my Mac, the `.` is just dropped.

**Comment by nrutman** [comment]
@flowrean yeah, sorry, I noticed that later last night. I guess I didn't realize how long it waited until it saved a backup. Sorry for the false hope.

**Comment by szafranP** [comment]
It's a pity that you can't choose your own location, and preferably the default location would be in the plugins folder. I install firefox for different people and everyone asks me if I follow him because garbage appears in the downloads folder.
