### ISSUE TITLE
Specify the backup location

### ISSUE THREAD

**Issue by ericwbailey** [Drive4ik/simple-tab-groups#285]
**Is your feature request related to a problem? Please describe.**
The STG-backups folder shows up on my desktop, where I have downloads set to go.

**Describe the solution you'd like**
I'd really appreciate the option to set a folder for the backup's destination, this would be especially handy if I could use a cloud-synced folder like Dropbox.

**Describe alternatives you've considered**
Right now I've just disabled backups.

Also, thank you so much for all your hard work on the extension—I love it!

**Comment by Drive4ik** [comment]
Hi! Webextension does not allow you to change the folder for downloading...

**Comment by ericwbailey** [comment]
Oh, I meant being able to set Simple Tab Group's backup location to a user-specified directory, not whatever the browser uses for its downloads destination. Apologies for the confusion.

**Comment by Drive4ik** [comment]
In Firefox Webextension `user-specified directory` = `browser downloads destination`, and the maximum that can be changed is the name of the folder (STG-backups) or file (stg-backup-...json)

**Comment by ericwbailey** [comment]
I guess that answers that, thank you.

**Comment by sinekonata** [comment]
Thank you, it was bothering me as well, I thought it was firefox' backup since I had just used it when it started happening.
Webextensions suck :D

**Comment by Joeyjoejoe** [comment]
A simple workaround would be to create a symbolic link in your firefox download folder pointing to the desired destination. Then, you could replace the backup folder name (STG-backups) with the symlink you created.

**Comment by sergeevabc** [comment]
@Joeyjoejoe, could you be so kind to provide the exact Windows commands to accomplish the aforementioned scenario? Something related to MKLINK, I guess.

**Comment by domme1234Do** [comment]
> @Joeyjoejoe, could you be so kind to provide the exact Windows commands to accomplish the aforementioned scenario? Something related to MKLINK, I guess.

After a bit of googling, what you need to do seems to be:
-Run cmd as Administrator
-Enter `mklink /d [symlink location & name] [path of actual folder]`
-Navigate to Simple Tab Groups Settings, Backup, and change the folder name to the name of your symlink

An example of your desired mklink command would be:
`mklink /d "C:\Users\[Name]\Downloads\STG Backups" "D:\Backups\Simple Tab Groups"`

If you were to enter this command, replacing [Name] with your directory (and assuming you had a D: drive), your backups would be stored in the "Simple Tab Groups" folder on your D: drive as long as you set the backup folder name to "STG Backups".

Hope this helps!

**Comment by cleveravi** [comment]
Do the commands you provided also work for MacOS? If not, would it be too much trouble to provide them? Thank you for your help.

**Comment by tigerjack** [comment]
The things that bothers me is that if I have multiple Firefox accounts sharing the same download location, the backup files get mixed. I guess the only workaround is to have a separate directory for each account.

**Comment by jemarq04** [comment]
> Do the commands you provided also work for MacOS? If not, would it be too much trouble to provide them? I appreciate any help.

The way to do it on a Mac would be something like this: `ln -s <DESTINATION> ~/Downloads/SimpleTabGroups`. Change `<DESTINATION>` to wherever you want the link to point to (e.g. `~/Documents/Backups` or wherever you'd like). I believe the destination directory has to already exist, though.

**Comment by fMagVen** [comment]
> Hooray, it works! Thank you for stopping by to help, [@domme1234Do](https://github.com/domme1234Do).
> 
> $ cmd
> Microsoft Windows [Version 6.1.7601]                           
> Copyright (c) 2009 Microsoft Corporation.  All rights reserved.
> 
> $ mklink /d C:\INBOX\Downloads\SimpleTabGroups X:\Backups\SimpleTabGroups
> symbolic link created for C:\INBOX\Downloads\SimpleTabGroups <<===>> X:\Backups\SimpleTabGroups
>                            \_______________/  \___________/
>                                    A                B
> 
> **A** is taken from Firefox settings » Downloads.
> 
> ![image](https://user-images.githubusercontent.com/373718/201687125-edded85c-04b4-4a96-83ea-5eae4ce86622.png)
> 
> **B** is taken from Simple Tab Group settings » Backup.
> 
> ![image](https://user-images.githubusercontent.com/373718/201687389-d79dbc63-7398-4496-a5a6-50f80e4e7319.png)

did this work for you? for me the download kept failing every time (lots of 0kb sized numbered attempts STG-backups(1) to STG-backups(5) ), a workaround i found it so use the selective folder syncing of mega to directly point at it, but would like to have all my backup files concentrated on a single encrypted vault i use with google drive
