### ISSUE TITLE
Feature request: Add an option to always use different windows as groups (never close tabs)

### ISSUE THREAD

**Issue by ico43** [Drive4ik/simple-tab-groups#29]
Hi, I know that right now it's impossible to just hide tabs, so they are still loaded and running but not visible on the tab bar. Therefore this addon handles tab grouping by closing and reloading tabs. There is also the option to treat different Firefox browser windows as tab groups so all tabs in one window are represented as a group and clicking on the group will bring that browser window to the front. For me this is much more convenient, so I would prefer to have an option to _always_ use different browser windows as tab groups and _never_ close any tab if I create or switch to another tab group - at least until Mozilla's API supports tab hiding.

Here is what I suggest in detail:
- A checkbox on the options page that says "Always use browser windows as tab groups". This is disabled by default. If you enable it, the addon will function as follows:
- If you click on "Create new group" the addon will open a new browser window and displays that window as a group in the tab groups list.
- If you click on a tab group in the list the addon will switch to that group by bringing the corresponding browser window to the front.
- If you move a tab to another group the addon will just move the tab to the corresponding browser window without closing the tab.
- If you close a browser window that is associated with a tab group the addon will also close the tab group (for example in the tab group list).
- If you delete a tab group from the list the addon will also close the corresponding browser window.
- The addon will _never_ close any tab.

For me this would be an excellent replacement for the tab group functionality until tab hiding is possible via the API. What do you think?

**Comment by White-Owl** [comment]
Right-click on group name, choose "Open group in a new window".
Do it just once for the existing group and until you close the 'group window' - everything you requested is already implemented.

**Comment by Drive4ik** [comment]
@ico43 
Please update addon to latest version and open add options page. There you needed options:
"Individual window for each group"
"Open new window when create new group"

**Comment by ico43** [comment]
Thank you very much! :)

I tried it but unfortunately I found two bugs:
- The first window (when I start Firefox) is not a group.
- When I close a window that is a group, the group still exists.

**Comment by Drive4ik** [comment]
@ico43 

1) if window not synhronize with group at startup - window stay without group.
This happens so that you do not lose the tabs when you assign to the wrong group
This is due to the fact that all FF windows at startup have different IDs.
You can manualy select group for not bined window after startup.

2) If you can not save tabs in window - open window by keyboard shortcut Ctrl+N
Groups never deleted automaticaly or other functionality, this is have no reason.

**Comment by Drive4ik** [comment]
Hi, you can check whether this issue replicate on the new version of the add-on STG v3.0.7 and FF 61?
If not, please close the bug
