### ISSUE TITLE
Delete backups older than X days

### ISSUE THREAD

**Issue by nicktiberi** [Drive4ik/simple-tab-groups#292]
**Is your feature request related to a problem? Please describe.**
Over time, the backup folder gets cluttered and large — currently mine is over 308MB.

**Describe the solution you'd like**
It would be nice to allow the user to specify how many days of backups to keep, and backups past that threshold would automatically be deleted (e.g. keep rolling last 7 days of backups and automatically delete any backups older than that). I'm not sure if WebExtensions can delete system files, though, so this may not be possible.

**Describe alternatives you've considered**
In the meantime I just periodically manually delete my backup files.

**Comment by Draghmar** [comment]
As far I'm understand the auto backup feature simply downloads the file into download folder. It can't access file system directly. That's why you can't choose your own backup folder. So unless something will change in regards to permissions webextentions can get it's not possible.

**Comment by Drive4ik** [comment]
@Draghmar you're right.
But in the new version you will be able to exclude the preview image in the auto-backup and it will make its size smaller
