### ISSUE TITLE
ctrl + shift to select more than one tab

### ISSUE THREAD

**Issue by nachancan** [Drive4ik/simple-tab-groups#296]
Hi

I use ctrl to select more than one tab and then move it to another group, but I have to click in every tab. And if you have hundreds of tabs this could be time consuming.

It would be perfect if in the "Manage Groups" tab we could select more than one tab at the same time. In the same way that we could do that in a file explorer with ctrl + shift.

For example I could do 
ctrl + shift + click on the first tab 
and
ctrl + shift + click on the 50th tab

And this way I have selected 50 tabs with 2 clicks.

Thanks a lot, today I discover this extension and it is mandatory to have it.

**Comment by Drive4ik** [comment]
Added support `Shift + Left Mouse Click` to select many tabs
