### ISSUE TITLE
TypeError: moveTabs type error: fromData can not be empty

### ISSUE THREAD

**Issue by lasers** [Drive4ik/simple-tab-groups#297]
**Describe the bug**

I received this notification whilst trying out this new extension. You might be interested in this.

>TypeError: moveTabs type error: fromData can not be empty background.js 1:25317 ne background.js:1:25317 created/< manage/manage.js:7:108710 t.prototype.$emit manage/manage.js:7:31366 dragHandle manage/manage.js:7:113496 drop manage/manage.js:7:102487 e manage/manage.js:7:12087 ir/i._withTask manage/manage.js:7:41291

**To Reproduce**
I was moving multiple tabs into a new group. I don't know if it is reproducible. It was also slowing down Firefox to the point where I was prompted to either stop now or wait (twice).

**Expected behavior**
No TypeError bug. 

**Screenshots**
N/A

**Desktop:**
 - Arch Linux 
 - Firefox 63.03
 - Simple Tab Groups 3.3.4

**Additional context**
N/A

**Comment by Drive4ik** [comment]
Hi! In theory, this bug should be fixed here 7b4cff0e62df24d2ffe6f87177e99a74784a7369
if this happens again - plase reopen this ticket

**Comment by Drive4ik** [comment]
And wait for next release before testing))
