### ISSUE TITLE
The tab is not saved if it is loading

### ISSUE THREAD

**Issue by me21** [Drive4ik/simple-tab-groups#298]
The tab is not saved on exit from Firefox if it is loading. On the subsequent Firefox restart, it is shown as empty new tab.

**To Reproduce**
1. Reduce the bandwidth of your Internet connection to have enough time for next steps.
2. Open new tab and start loading any url.
3. While it's loading, close Firefox.
4. Restart Firefox. You should see the tab as blank.

**Expected behavior**
Since the url is already specified, and the tab is loading it, it should restart opening that url if the browser is closed and reopened.

**Desktop (please complete the following information):**
 - Windows 10 x64 v1607 LTSB
 - Firefox version: 63.0.3 x64
 - Simple Tab Groups version: 3.3.4

**Comment by Drive4ik** [comment]
Hi! Can you try to repeat these steps, but without the STG addon?

**Comment by Drive4ik** [comment]
The browser itself does not save the URL and nothing can be done about it ....
