### ISSUE TITLE
Move tab to group

### ISSUE THREAD

**Issue by TomaszKane** [Drive4ik/simple-tab-groups#3]
Hi! I have feature request: Move tab to group...
in right-click tab context menu - just like in Tab Groups. Or any other nice method to manage groups (domain filter is not bad but...).

Cheers.

**Comment by Drive4ik** [comment]
Hello! This feature will be added in future versions :)
Please, wait few days/weeks
Now I'm working on adding the functionality of importing tabs from the old plugin.

**Comment by unclechu** [comment]
Maybe it will help someone for now: after migrating from the old Tab Groups and having hundreds of tabs I'm just pinning tabs on one group and unpinning them being on group which I need to move tab to.

**Comment by Drive4ik** [comment]
This functional is available on v1.7
Please update addon.
