### ISSUE TITLE
Feature request: Search in Manage groups

### ISSUE THREAD

**Issue by szegi** [Drive4ik/simple-tab-groups#30]
It would be great if i could easily filter tabs
in Manage groups view

something like:
one main search to search in all groups
and search in every group
so i could easily filter sites and put them to the right group

something like this
![image](https://user-images.githubusercontent.com/12111506/34492194-d6e8c04c-efe6-11e7-9b1b-7b6e6c5617df.png)

of course it is just a suggestion:) thanks for great addon

**Comment by dr-jan** [comment]
The main thing I'm missing from the old Tab Groups is when the groups are shown (like the screen shot above), I could just start typing a search string and any matching tabs would be highlighted (by dimming all the other tabs in the manager view). Just another suggestion :-)

**Comment by Drive4ik** [comment]
@szegi Please, test this feature in latest addon release :)

**Comment by szegi** [comment]
i tested it for few minutes and it seems to work quite good:)
one suggestion
![image](https://user-images.githubusercontent.com/12111506/34784277-1cf25be6-f62e-11e7-9541-ef77b4095b08.png)

also i would love to see here fuzzy search
so i dont have to put whole worlds or using *
and that i dont have to worry about order

i mean something like this

if i want to find page that has title like this"abc def ghi"
i could write "h bc" or "gh bc"
i suppose it wont be big performance issue if number of tabs is below few thousands
because sometimes titles are very long and are similar
and to find something
i have to know order of words in title or i dont find it easily
