### ISSUE TITLE
Tabs wont load, enabled svg.context - Error: [Exception...."Failure" nsresult:0x80004005 (NS_ERROR_FAILURE)" location: "JS frame ;; chrome;//extensions/content/child/ext-storage.,

### ISSUE THREAD

**Issue by meru448** [Drive4ik/simple-tab-groups#300]
**Describe the bug**
Came back to firefox after about a week of being away from my computer, went updated tab groups, enabled " svg.context-properties.content.enabled " // set to true - get error 

 Error: [Exception...."Failure" nsresult:0x80004005 (NS_ERROR_FAILURE)" location: "JS frame ;; chrome;//extensions/content/child/ext-storage.,

**To Reproduce**
Happens every time I try to load the tab group.

**Expected behavior**
The tab group gets loaded

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 10 Pro
Firefox Nightly 66
 - Simple Tab Groups version: 3.3.4 

**Additional context**

Pretty disheartening, I've lost my data to this addon before, with the "phantom tab groups" which I see has now been remedied, I definitely hope this is fixable. thank you for your time.

**Comment by Drive4ik** [comment]
Firefox Nightly is not stable version.. Reopen this bug if they repeat on the beta or release version.
