### ISSUE TITLE
Cannot change or add shortcut

### ISSUE THREAD

**Issue by HerbJiang** [Drive4ik/simple-tab-groups#301]
**Describe the bug**
Cannot put anything in the "KEY" field.
I can click add and it shows a new row with CTRL/SHIFT/OPTION/CMD 4 checkbox and one inputbox. 
But when click the inputbox, then type any key, it don't response and didn't show anything.

**To Reproduce**
1. Click add and it shows a new row with CTRL/SHIFT/OPTION/CMD 4 checkbox and one inputbox. 
2. Click the inputbox, then type "1" or "2", it don't response and didn't show anything.

**Expected behavior**
I think it should show what key I pressed in the inputbox.

**Screenshots**
![default](https://user-images.githubusercontent.com/875748/50038817-3e62c980-0061-11e9-8b9e-20f3963167bf.png)

**Desktop (please complete the following information):**
 - OS and version: MacOS Mojave 10.14.1
 - Firefox version: 64.0
 - Simple Tab Groups version: 3.3.4

**Additional context**
N/A

**Comment by Richie765** [comment]
I'm having the same problem. It just stopped working a couple of days ago, perhaps due to a Firefox update? Tried to reinstall STG but it didn't help.

Is there a work-around? E.g. editing the config file directly somehow?
(Using the same versions as above)
