### ISSUE TITLE
Switching to unloaded tab in a different group loads a different tab

### ISSUE THREAD

**Issue by superk2001** [Drive4ik/simple-tab-groups#303]
**Describe the bug**
When I switch to an unloaded tab in a different group, it doesn't select that tab. Instead it selects a different, loaded tab.

**To Reproduce**
1. Try and go to an unloaded tab in a group that is not selected.
2. You will see that tab be selected for a split-second, then another, loaded tab be selected

**Expected behavior**
Switching to an unloaded tab switches to that tab and loads it.

**Desktop (please complete the following information):**
 - OS and version: Windows 7
 - Firefox version: 64
 - Simple Tab Groups version: 3.3.4

**Other info**
I tested this in a new profile, using the unload tab addon

**Comment by Drive4ik** [comment]
Hi! Can you record screen with this issue?
You can use this app or another
https://www.screentogif.com/
Thanks

**Comment by Drive4ik** [comment]
What other addons do you use?

**Comment by superk2001** [comment]
Here's a video of the bug in a new firefox profile:
Addon used to unload tabs is: https://addons.mozilla.org/en-US/firefox/addon/unload-tabs/
https://vimeo.com/312064864

**Comment by Drive4ik** [comment]
I tried to repeat the bug on the new profile with this addon, but the bug did not exist.
P.S. no video available on vimeo

**Comment by Drive4ik** [comment]
I tried to repeat the bug on the new profile with this addon, but the bug did not exist.
You need to dig into the settings of this plug-in (unload tabs), most likely this is a conflict between the plug-ins, since they both manage the tabs
P.S. no video available on vimeo

**Comment by superk2001** [comment]
Here's a direct file upload:
[tabgroupsbug.zip](https://github.com/Drive4ik/simple-tab-groups/files/2772634/tabgroupsbug.zip)

**Comment by superk2001** [comment]
I figured it out, it looks like the problem was the Unload Tabs addon. Thanks for letting me know it worked for you.

**Comment by Drive4ik** [comment]
![default](https://user-images.githubusercontent.com/7843031/51382966-d05a6800-1b20-11e9-8e6d-64b4698e03a9.png)

I don’t see another solution and fix it in my plugin
