### ISSUE TITLE
Prepend Group Name To Window Title

### ISSUE THREAD

**Issue by GonzRon** [Drive4ik/simple-tab-groups#304]
**Is your feature request related to a problem? Please describe.**
This is similar to #10 and other linked requests.  There you describe this cannot be done.  I switched to simple tab groups from the "sync-tab-groups" tab manager extension which is unfortunately no longer under development.  SyncTabGroups extension solved this problem easily by updating the window title.

**Describe the solution you'd like**
Update the Window Title with the name of the current tab group for each window / group.

**Additional context**
Please see screenshot.
![si-09-40-42-am_0016](https://user-images.githubusercontent.com/18006895/50094176-8c520b80-01e0-11e9-9e26-cedf26b17728.jpg)

Here is the commit for sync-tab-groups Feature Request where this functionality is implemented:
https://github.com/Morikko/sync-tab-groups/commit/dfa7523186d99c0579584ae75e024054887d8480#diff-0c276ace26b8ef2d60eb21e8abfc1a85R43

**Comment by GonzRon** [comment]
do i really need it? It would help my workflow.  I open many different windows, I want to categorize windows so that I don't open tabs related to subject X in window Y.  Subject A -> Window A, Subject B -> Window B.  That way I don't waste time or open duplicates.  That's the use case behind this.  This enhancement becomes especially important in the context of functionality requested in #302.

**Comment by GonzRon** [comment]
Here's the taskbar Window previews, as you can see, you can only see the title of the current tab in the window.  If there was [Group Name] - (existing Tab Title), that would make it easier to identify the category of each window group.
![browser window taskbar previews](https://user-images.githubusercontent.com/18006895/51504686-40cae880-1db0-11e9-9146-825c1343276d.jpg)

**Comment by Drive4ik** [comment]
Please wait next release and find option `Prepend group title to window title` in addon options

**Comment by GonzRon** [comment]
Thank you very much!

**Comment by GonzRon** [comment]
I pulled from master and ran a local build with firefox developer, looks good!

**Comment by edison23** [comment]
@Drive4ik : Thanks for the great extension and sorry for the necromancy, but is it possible to make this option a default, i.e., show the group title in the window title automatically when I create new groups, instead of setting that explicitly for every group I create?

**Comment by Drive4ik** [comment]
@edison23  you can set the default settings for a new group like this:

![Image](https://github.com/user-attachments/assets/543a5593-5ef9-40f9-bb35-8c6bcc9201e9)

![Image](https://github.com/user-attachments/assets/6ce12c3f-37c9-4222-90be-0e878403ed70)

![Image](https://github.com/user-attachments/assets/b2a1f858-9eb9-46e3-9817-44709675edc4)

**Comment by edison23** [comment]
@Drive4ik : Oh, thank you very much for the prompt reply and help! I totally missed the option to set the default settings like this.
