### ISSUE TITLE
Moving multiple tabs to other group reverses order

### ISSUE THREAD

**Issue by Illiou** [Drive4ik/simple-tab-groups#309]
When selecting multiple tabs in the tabbar and doing Rightclick -> Simple Tab Groups -> Move to other group the order of the tabs gets reversed, which is not what you want usually.

Tested it in a fresh Firefox 64.0 Portable, too and the behavior is the same.
Simple Tab Groups 3.3.4 on Windows

Thanks :)

**Comment by klint** [comment]
Yes, same here.

**Comment by Drive4ik** [comment]
done)
P.S. tab selection in popup window saves order when selecting tabs
