### ISSUE TITLE
Regular expressions doesn't work as assumed

### ISSUE THREAD

**Issue by gmuellerfr** [Drive4ik/simple-tab-groups#31]
Hello,

I need a replacement for the loved tab groups and so I give this add-on a try.
In the group settings I've found a nice feature I would love if it does what I expect:
 
Regular expressions for catch tabs 

When I type an URL which is catched by the expression, firexfox changes to the correct group, but I'm faced with a new empty tab ;-( where I can type the URL again )

Best regards,
Guenter

**Comment by White-Owl** [comment]
I confirm the bug.
Version 1.9.0.1 from December 20.

- open a new tab
- type the URL in the address bar (or choose the bookmark).
- the new tab immediately closes and bottom-right of the screen appears pop-up "tab was moved to the group".
- Click on pop-up - I am in a correct group looking at new page with empty address bar.
- Waiting for pop-up to disappear and manually switching to the target group - the last page in a group is empty.

Another strange scenario:
- Have three tabs with open pages (source group without regexp)
- Change the address bar of the middle tab with a catchable URL (or choose a bookmark)
- The pop-up says, that it is moving tab with a name of the old URL of the middle tab
- The middle tab in source group disappears, but in a target group opens a tab with URL of the third tab of the source group.

**Comment by Drive4ik** [comment]
@gmuellerfr yes, I know about this bug. Please, retest this issue in latest addon version (2.0)

**Comment by White-Owl** [comment]
Yes, it is fixed in version 2.0
Thanks.

**Comment by gmuellerfr** [comment]
Yes, my problem is fixed in version 2.0, too.
Thanks.
