### ISSUE TITLE
Invalid TAB ID: 1 when selecting group.

### ISSUE THREAD

**Issue by roliverio** [Drive4ik/simple-tab-groups#310]
I'm facing this issue intermittently in different ports (Mac / Linux) of Firefox. It comes from time to time, however, 

I'm pasting here an screenshot of the browser debug console. Feel free to ask for more details if needed.

**Screenshots**

![captura de pantalla 2018-12-18 a la s 10 46 31 a m](https://user-images.githubusercontent.com/390821/50165246-8af11380-02b2-11e9-978f-1ca01d1cfbd6.png)

![captura de pantalla 2019-01-14 a la s 1 40 51 p m](https://user-images.githubusercontent.com/390821/51133384-dd1a4b80-1802-11e9-9a2c-bebd202c3670.png)

It's worth noting that this has happened intermittently since my initial install of this extension, which ocurred almost 8 months ago. (and, i update firefox as soon as a new version appears)

1. Open Firefox
2. Click on one tab group
3. Click on another tab group

**Expected behavior**
Switch tab group

**Desktop (please complete the following information):**
 - OS and version: MacOSX 10.13.5 (High Sierra) / Debian Linux, kernel. 4.18.
 - Firefox version: 64.0.2 (Both OS)
 - Simple Tab Groups version: 3.3.4

**Additional context**
if i go to the groups administration, i can see the tab group and it's tabs, but cannot change to it, my solution is to create a new group and move the tabs, and delete the failing group, but this is getting annoying.

Also, normally when this happens, i lose the group and often more than one group at a time.

**Comment by Drive4ik** [comment]
Hi! I fix this bug in 827002d4cc0ed1e34f99d660d72312d2e1a2669c
please wait next release. What other addons do you use?

**Comment by roliverio** [comment]
Hi @Drive4ik 

Thanks for noting this.

Additional extensions i'm using (in both installs of Firefox):
- uBlock origin
- Authenticator
- Youtube Classic

If you need more information, please let me know.

Thanks again.

**Comment by Drive4ik** [comment]
Hi! Try retest issue on new released version (3.3.5)
