### ISSUE TITLE
Error: wait loading addon

### ISSUE THREAD

**Issue by nhua6456** [Drive4ik/simple-tab-groups#312]
**Describe the bug**
Addon constantly crashes on startup.

**To Reproduce**
1. Launch Firefox
2. Wait for STG to load
3. See error in the debugger

**Expected behavior**
STG should finish loading and display the STG icon next to the address bar

**Screenshots**
![Image of Firefox](http://vigne.fgghjjkll.net/~fgghjjkll/firefox_2019-01-17_23-26-14.png)

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Firefox version: 65b11
 - Simple Tab Groups version: commit cbe2c007535e9db719f04a75f68e477e90057a62

**Additional context**
Many groups had previously been created. A small number of them have ~500 or so tabs. It doesn't seem like it's an issue with the extension data store, since after extension data is removed and STG is reinstalled, the same load looping can be observed in the debugger.

**Comment by Drive4ik** [comment]
Hi! Everything works as intended. You can close the addon settings window or the group management window and then these errors will not occur.
