### ISSUE TITLE
Regular failed download

### ISSUE THREAD

**Issue by mhmacleod** [Drive4ik/simple-tab-groups#313]
As someone else has already pointed out in this add-on's reviews, there is a backup file that is being generated regularly (~hourly) that goes by the name format "stg-backup-yyy-mm-dd@drive4jk.json", but it constantly appears as a failed download on my downloads history, with the error  message "file moved or missing".

**Comment by Drive4ik** [comment]
Hi! I fix this bug in 43ac44a367c3aa2e7e9f02ef60c6f2caf0a48611
wait next release please
