### ISSUE TITLE
Feature request: Auto close a tab group which has only single tab when closing the window

### ISSUE THREAD

**Issue by qpwakaba** [Drive4ik/simple-tab-groups#315]
I want "Close a group which has only one tab when closing the window" option.

I use "Create a new group when opening a new window" option. It is very useful but I can't help opening too many tab groups.
I often open new windows on each purposes. If the purpose is very small, I often close the window which has only one tab. Then the tab group is saved but I will never open the tab group.

**Comment by Drive4ik** [comment]
Once you use many windows, by and large you don’t need to turn on the option `Create a new group when opening a new window`?

**Comment by qpwakaba** [comment]
Thank you for your replying to my post.

There are two reasons why I use `Create a new group when opening a new window` option.

The first is to save tab groups that I will refer later and I often close the window without saving though I want to save.

The second is to separate desktop every work.
I often use virtual desktops and switch the desktop each work. Usually I open Visual Studio and Firefox in a desktop to develop an application, and I open Thunderbird in another desktop.

When I open a URL from Thunderbird, a new window will be opened.
If `Create a new group when opening a new window` option is turned off, the problem of the second reason is solved, but the problem of the first reason is not solved.

**Comment by Drive4ik** [comment]
Hi! Then I have another question: under what condition, what should be the tab when closing (tab URL) in order to delete this group? After all, it may remain the tab that is needed, but the group will be deleted.

There is another suggestion: use hotkeys to delete the current group (available in the addon settings), and then you will not even need to delete all the tabs until the last one in order for the auto-delete group to work.

And I can also make a plugin, like these: https://addons.mozilla.org/firefox/collections/1017663/STG-plugins/
And when you click on one button, the current window closes and delete the group attached to it will also be deleted.

**Comment by qpwakaba** [comment]
> There is another suggestion: use hotkeys to delete the current group (available in the addon settings), and then you will not even need to delete all the tabs until the last one in order for the auto-delete group to work.

Oh!! I didn't think this idea! I'll use it!


> And I can also make a plugin, like these: https://addons.mozilla.org/firefox/collections/1017663/STG-plugins/
> And when you click on one button, the current window closes and delete the group attached to it will also be deleted.

I want to try the button!


> Hi! Then I have another question: under what condition, what should be the tab when closing (tab URL) in order to delete this group? After all, it may remain the tab that is needed, but the group will be deleted.

I usually open many web sites and I didn't think URL condition. I think the hotkeys or the button to delete the current group are better than my idea.

**Comment by Drive4ik** [comment]
If hot keys suit you, use them. Just for a new plug-in (deleting a group) you need to draw another icon in the svg format .. but I don’t have an idea and not much time to draw it

**Comment by qpwakaba** [comment]
I made some icons. Is there the icon you like?
[icons.zip](https://github.com/Drive4ik/simple-tab-groups/files/2798574/icons.zip)

I used the hot keys. It is like what I wanted. But when I delete a group, another firefox window was activated. If the window was on another desktop, the current desktop was switched.
I want not to switch desktops. Is it possible?

**Comment by Drive4ik** [comment]
Cool icons! Thanks)
Please wait next STG release and install this plugin
https://addons.mozilla.org/firefox/addon/stg-plugin-del-current-group/
it will work on next release

**Comment by Drive4ik** [comment]
>  I want not to switch desktops. Is it possible?

Done in 83476431415ddac9c44fa4dedb854f58d85f3c0f

**Comment by qpwakaba** [comment]
Thank you!!
