### ISSUE TITLE
Simple Tab Groups addon crashes Firefox

### ISSUE THREAD

**Issue by arabesc** [Drive4ik/simple-tab-groups#317]
**Describe the bug**
Simple Tab Groups addon crashes Firefox.

**To Reproduce**
1. Install Simple Tab Groups addon;
2. Create new group;
3. RMB on the new group name;
4. Select Group settings;
5. See app crash.

**Expected behavior**
No crash.

**Desktop (please complete the following information):**
 - OS and version: macOS 10.14.3
 - Firefox version: 64.0.2
 - Simple Tab Groups version: 3.3.4

**Additional context**
AdapterDeviceID: 0x1b06
AdapterVendorID: 0x10de
Add-ons: jid1-MnnxcxisBPnSXQ%40jetpack:2018.12.17,jid1-XAZYVkS6OPAR5Q%40jetpack:0.8.20,uBlock0%40raymondhill.net:1.17.4,onepassword4%40agilebits.com:4.7.3.90,copyplaintext%40eros.man:1.8,%7B2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c%7D:1.19.0,%7B72b2e02b-3a71-4895-886c-fd12ebe36ba3%7D:0.2.1,%7B41c87c37-5730-46d1-92a0-2a05c4cb75c8%7D:1.0,historyblock%40kain:2.0,abb%40amazon.com:10.1805.2.1019,%7B522e3f34-aac8-4f2b-89f9-da90cee90806%7D:1.3.1,simple-tab-groups%40drive4ik:3.3.4,fxmonitor%40mozilla.org:2.8,screenshots%40mozilla.org:35.0.0,webcompat%40mozilla.org:3.0.0,formautofill%40mozilla.org:1.0,webcompat-reporter%40mozilla.org:1.1.0
BuildID: 20190108160530
ContentSandboxCapable: 1
ContentSandboxLevel: 3
CrashTime: 1548203047
DOMIPCEnabled: 1
FramePoisonBase: 9223372036600930304
FramePoisonSize: 4096
GraphicsCriticalError: |[0][GFX1-]: [OPENGL] Failed to init compositor with reason: FEATURE_FAILURE_OPENGL_CREATE_CONTEXT (t=0.597862) |[1][GFX1-]: [OPENGL] Failed to init compositor with reason: FEATURE_FAILURE_OPENGL_CREATE_CONTEXT (t=38.2269) |[2][GFX1-]: [OPENGL] Failed to init compositor with reason: FEATURE_FAILURE_OPENGL_CREATE_CONTEXT (t=130.212) 
InstallTime: 1547538525
Notes: FP(D00-L1000-W00000000-T000) WR? WR- OMTP? OMTP+4 GL Layers? GL Layers- GL Context? GL Context+ 
ProductID: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
ProductName: Firefox
ReleaseChannel: release
SafeMode: 0
SecondsSinceLastCrash: 140
StartupCrash: 0
StartupTime: 1548202912
TelemetryEnvironment: {"build":{"applicationId":"{ec8030f7-c20a-464f-9b0e-13a3a9e97384}","applicationName":"Firefox","architecture":"x86-64","buildId":"20190108160530","version":"64.0.2","vendor":"Mozilla","displayVersion":"64.0.2","platformVersion":"64.0.2","xpcomAbi":"x86_64-gcc3","updaterAvailable":true},"partner":{"distributionId":null,"distributionVersion":null,"partnerId":null,"distributor":null,"distributorChannel":null,"partnerNames":[]},"system":{"memoryMB":32768,"virtualMaxMB":null,"cpu":{"count":8,"cores":4,"vendor":"GenuineIntel","family":6,"model":158,"stepping":9,"l2cacheKB":256,"l3cacheKB":8192,"speedMHz":4201,"extensions":["hasMMX","hasSSE","hasSSE2","hasSSE3","hasSSSE3","hasSSE4_1","hasSSE4_2","hasAVX","hasAVX2","hasAES"]},"os":{"name":"Darwin","version":"18.2.0","locale":"en-RU"},"hdd":{"profile":{"model":null,"revision":null},"binary":{"model":null,"revision":null},"system":{"model":null,"revision":null}},"gfx":{"D2DEnabled":null,"DWriteEnabled":null,"ContentBackend":"Skia","adapters":[{"description":null,"vendorID":"0x10de","deviceID":"0x1b06","subsysID":null,"RAM":null,"driver":null,"driverVersion":null,"driverDate":null,"GPUActive":true}],"monitors":[{"screenWidth":1920,"screenHeight":1200,"scale":1}],"features":{"compositor":"basic","gpuProcess":{"status":"unused"},"wrQualified":{"status":"blocked"},"webrender":{"status":"opt-in"}}},"appleModelId":"iMac18,3"},"settings":{"blocklistEnabled":true,"e10sEnabled":true,"e10sMultiProcesses":4,"telemetryEnabled":false,"locale":"en-US","update":{"channel":"release","enabled":true,"autoDownload":true},"userPrefs":{"browser.cache.disk.capacity":1048576,"browser.search.region":"RU","browser.search.widget.inNavBar":true,"browser.startup.page":3,"network.proxy.ssl":"<user-set>","privacy.trackingprotection.enabled":true,"privacy.donottrackheader.enabled":true},"sandbox":{"effectiveContentProcessLevel":3},"addonCompatibilityCheckEnabled":true,"isDefaultBrowser":true,"defaultSearchEngine":"google","defaultSearchEngineData":{"name":"Google","loadPath":"jar:[app]/omni.ja!/google.xml","origin":"default","submissionURL":"https://www.google.com/search?client=firefox-b&q="},"searchCohort":"jan18-1"},"profile":{"creationDate":17460},"addons":{"activeAddons":{"{72b2e02b-3a71-4895-886c-fd12ebe36ba3}":{"version":"0.2.1","scope":1,"type":"extension","updateDay":17490,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Grab and download media (image and video) sources by monitoring network (like FlashGot)","name":"Bulk Media Downloader","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17490,"signedState":2},"{41c87c37-5730-46d1-92a0-2a05c4cb75c8}":{"version":"1.0","scope":1,"type":"extension","updateDay":17570,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Recognises qr-codes in images","name":"Context QR","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17570,"signedState":2},"copyplaintext@eros.man":{"version":"1.8","scope":1,"type":"extension","updateDay":17683,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Copy Plain Text without any formatting","name":"Copy PlainText","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17490,"signedState":2},"historyblock@kain":{"version":"2.0","scope":1,"type":"extension","updateDay":17685,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Cover your tracks!","name":"HistoryBlock","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17685,"signedState":2},"abb@amazon.com":{"version":"10.1805.2.1019","scope":1,"type":"extension","updateDay":17739,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"This is an official Amazon extension for Firefox","name":"Amazon Assistant for Firefox","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17739,"signedState":2},"{522e3f34-aac8-4f2b-89f9-da90cee90806}":{"version":"1.3.1","scope":1,"type":"extension","updateDay":17742,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Select words and look them up in macOS’s Dictionary application.","name":"macOS Dictionary Lookup","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17742,"signedState":2},"jid1-XAZYVkS6OPAR5Q@jetpack":{"version":"0.8.20","scope":1,"type":"extension","updateDay":17764,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Get cashback for every order in AliExpress, Ozon, ASOS, Banggood, GearBest, MVideo and Lamoda stores","name":"ePN CashBack Plugin","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17460,"signedState":2},"{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}":{"version":"1.19.0","scope":1,"type":"extension","updateDay":17829,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Reverse image search using various search engines, such as Google, Bing, Yandex, Baidu and TinEye.","name":"Search by Image","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17490,"signedState":2},"onepassword4@agilebits.com":{"version":"4.7.3.90","scope":1,"type":"extension","updateDay":17853,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Extends the 1Password app on your Mac or Windows PC, so you can fill and save passwords in your brow","name":"1Password extension (desktop app required)","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17460,"signedState":2},"uBlock0@raymondhill.net":{"version":"1.17.4","scope":1,"type":"extension","updateDay":17866,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Finally, an efficient blocker. Easy on CPU and memory.","name":"uBlock Origin","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17460,"signedState":2},"jid1-MnnxcxisBPnSXQ@jetpack":{"version":"2018.12.17","scope":1,"type":"extension","updateDay":17884,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Privacy Badger automatically learns to block invisible trackers.","name":"Privacy Badger","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17460,"signedState":2},"screenshots@mozilla.org":{"version":"35.0.0","scope":1,"type":"extension","updateDay":17879,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Take clips and screenshots from the Web and save them temporarily or permanently.","name":"Firefox Screenshots","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17441},"webcompat@mozilla.org":{"version":"3.0.0","scope":1,"type":"extension","updateDay":17879,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Urgent post-release fixes for web compatibility.","name":"Web Compat","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17441},"formautofill@mozilla.org":{"version":"1.0","scope":1,"type":"extension","updateDay":17879,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Form Autofill","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17441},"webcompat-reporter@mozilla.org":{"version":"1.1.0","scope":1,"type":"extension","updateDay":17879,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Report site compatibility issues on webcompat.com","name":"WebCompat Reporter","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17712},"fxmonitor@mozilla.org":{"version":"2.8","scope":1,"type":"extension","updateDay":17912,"isSystem":true,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":null,"name":"Firefox Monitor","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17912,"signedState":3},"simple-tab-groups@drive4ik":{"version":"3.3.4","scope":1,"type":"extension","updateDay":17913,"isSystem":false,"isWebExtension":true,"multiprocessCompatible":true,"blocklisted":false,"description":"Create, modify and quickly change tab groups. \nInspired by the old add-on \"Tab Groups\" :)","name":"Simple Tab Groups","userDisabled":false,"appDisabled":false,"foreignInstall":false,"hasBinaryComponents":false,"installDay":17913,"signedState":2}},"theme":{"id":"default-theme@mozilla.org","blocklisted":false,"description":"The default theme.","name":"Default","userDisabled":false,"appDisabled":false,"version":"","scope":1,"foreignInstall":false,"hasBinaryComponents":false,"installDay":0,"updateDay":0},"activePlugins":[],"activeGMPlugins":{"gmp-gmpopenh264":{"version":"1.7.1","userDisabled":false,"applyBackgroundUpdates":1},"gmp-widevinecdm":{"version":"4.10.1196.0","userDisabled":false,"applyBackgroundUpdates":1}},"persona":"default-theme@mozilla.org"},"experiments":{"searchCohort":{"branch":"jan18-1"},"pref-rollout-activity-stream-snippets-release-1517479":{"branch":"active","type":"normandy-prefrollout"},"rollout-monitor-v2-1505837":{"branch":"active","type":"normandy-prefrollout"},"rollout-restart-manager-release-1481278":{"branch":"active","type":"normandy-prefrollout"},"prefflip-push-performance-1491171":{"branch":"enabled","type":"normandy-exp"}}}
ThreadIdNameMapping: 8:"Gecko_IOThread",9:"Timer",10:"Socket Thread",11:"JS Watchdog",15:"JS Helper",12:"JS Helper",14:"JS Helper",13:"JS Helper",16:"JS Helper",17:"JS Helper",18:"JS Helper",19:"JS Helper",22:"Cache2 I/O",23:"Cookie",26:"GMPThread",27:"Compositor",28:"ImgDecoder #1",29:"ImageIO",30:"IPDL Background",33:"DOM Worker",36:"StyleThread#2",38:"StyleThread#4",34:"StyleThread#0",39:"StyleThread#5",37:"StyleThread#3",35:"StyleThread#1",43:"ImageBridgeChild",44:"ProcessHangMon",45:"DataStorage",46:"URL Classifier",47:"Classifier Update",48:"Cache I/O",47:"DOM Worker",48:"localStorage DB",50:"mozStorage #1",51:"mozStorage #2",52:"ImgDecoder #2",53:"ImgDecoder #3",54:"ImgDecoder #4",59:"mozStorage #3",60:"QuotaManager IO",57:"mozStorage #4",64:"DOM Worker",67:"mozStorage #5",67:"mozStorage #6",71:"DOM Worker",76:"SaveScripts",72:"mozStorage #7",74:"StreamTrans #144",
Throttleable: 1
URL: https://github.com/drive4ik/simple-tab-groups/issues
UptimeTS: 135.05552404
Vendor: Mozilla
Version: 64.0.2
useragent_locale: en-US

This report also contains technical information about the state of the application when it crashed.

**Comment by GonzRon** [comment]
I just tried your reproduction steps and could not reproduce the crash.

**Comment by GonzRon** [comment]
this crash:
[OPENGL] Failed to init compositor with reason: FEATURE_FAILURE_OPENGL_CREATE_CONTEXT

seems to be related to hardware acceleration.

Try disabling hardware acceleration and see if the crash reproduces by following these steps:
https://www.askvg.com/how-to-disable-hardware-acceleration-gpu-rendering-in-mozilla-firefox-4-0-to-fix-font-problem/

**Comment by Drive4ik** [comment]
This is Firefox issue, not addon's...
