### ISSUE TITLE
Make Action Bar in TabGroups list Dialog Window always visible (exclude from tabgroups list window-scrolling)

### ISSUE THREAD

**Issue by GonzRon** [Drive4ik/simple-tab-groups#318]
**Is your feature request related to a problem? Please describe.**

The following items at the very bottom of the Window Group Dialog
```
Create New Group
# Manage Groups | reload icon | settings icon|
```

is not visible with many tab groups present.  In my case, I have to scroll down a long list to access these items.  Also, when scrolling down, the Search Bar at the top of the Dialog Window is now hidden.

**Describe the solution you'd like**
These "action bar" items should be kept visible at all times no matter the length of the window group list.
Also Search Box should be visible at all times as well.

**Additional context**
the dialog should scroll the available tab groups, but the action bar should remain at the bottom of the dialog.
Example action bar not visible:
![2019-01-22_20-20-01](https://user-images.githubusercontent.com/18006895/51576442-3d089600-1e84-11e9-8902-86f7f9a1a10b.jpg)

Here is what the Dialog Window with my proposed Changes would look like:
![2019-01-22_20-20-01](https://user-images.githubusercontent.com/18006895/51576703-4cd4aa00-1e85-11e9-95e8-4de626b9c5f7.jpg)

**Comment by GonzRon** [comment]
This is a duplicate of #106

**Comment by Drive4ik** [comment]
Yes, duplicate..

**Comment by GonzRon** [comment]
Thank you, looks like this is fixed!
