### ISSUE TITLE
Will this import tab groups from the "tab groups" addon by "Quicksaver"? 

### ISSUE THREAD

**Issue by meru448** [Drive4ik/simple-tab-groups#32]
Have been holding off "upgrading" to firefox quantum due to lack of tab groups, this looks similar enough but can it import existing tab groups?

**Comment by meru448** [comment]
Alright I see the button for it - but I can't seem to locate the file to import, (windows 10) looking in appdata.

**Comment by me21** [comment]
Just do a manual backup of tab groups and you'll be able to choose the folder to put the backup into.

**Comment by meru448** [comment]
Gotcha
