### ISSUE TITLE
Add an option to open Manage Groups in a pinned tab

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#320]
**Is your feature request related to a problem? Please describe.**
This is a nice way to solve issue #289  (closing the last tab of a group opens a random non-empty group, hence inducing privacy issue). 
But that does not happen when a pinned tab already exists. THis request is about using the Manage Group tab in pinned state and have an easy way to open it in pinned state.

**Describe the solution you'd like**
An new option, in addition to "open Manage Group view in a tab": open it in a pinned tab

Thanks

**Comment by klint** [comment]
I just discovered that another addon can do the trick in the meantime, for those who are interested: AutoPinTab .

**Comment by Drive4ik** [comment]
and add url regexp like this
`^moz\-extension\:\/\/.*?\/manage\/manage\.html`
