### ISSUE TITLE
A way to switch to target group after moving a tab via the tab topbar STG menu 

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#322]
As of now, moving a tab via the STG menu at tab level does not open the target group (but maybe I missed anything?? :) )
Could it be possible to switch to the target group in this group based either on an option (so, the behaviour would always be the same), or better if feasible, only on pressing the SHIFT key when clicking on the target group in the STG menu?
In this case, no notification would be displayed.
Thanks

**Comment by Drive4ik** [comment]
I do not understand something) Tab moving is tab movement and not group switching. And the message about moving is shown only when moving tabs from the tab topbar, and not in the STG menu

**Comment by klint** [comment]
About tab movement and group switching: yes, today, these 2 features are not linked. This request is about providing a way to link them actually: when moving/sending a tab to another group, then switch to that group automatically.
This could be activated for instance, by pressing Shift and clicking on the group name on the tab topbar STG menu (not the main STG menu, the one on the topbar). Or by right clicking instead of left clicking.

And if you automatically switch to the group where the tab is being moved, there is no need for the message anymore, right?

Hope I have clarified enough :)
And by the way, thanks also for the new version that you released today.

**Comment by Drive4ik** [comment]
Did not quite understand the way to switch to the group.
In the group settings there is an option to automatically switch to this group if the tab has been automatically moved there.

**Comment by klint** [comment]
The option at group level is for automatic switch, isn'it ? I'm talking about manual switch. Let me explain better with use cases :)

Currently:
- Display a tab, in group A
- Right click on the tab topbar
- The "Simple Tab group" menu entry appears in the tab contextual menu
- In this STG menu, select and *Left* click on Group B
- The tab is moved to group B, the focus goes on the next tab in group A, and a notification message appears, allowing to switch to group B by clicking on it

My request is just to save one click actually (and a notification), so it is not really critical :). But it would work like this. 
- Display a tab, in group A
- Right click on the tab topbar
- The "Simple Tab group" menu entry appears in the tab contextual menu
- In this STG menu, select and *Right* click on Group B (or hold Shift and left click)
- The tab is moved to group B and the tab is displayed directly, along with group B. No notification message appears,

But again, it is not that important after all (unless you find it important, of course)

**Comment by Drive4ik** [comment]
Oh, I understand what you mean.
Only I can not decide how to implement it: in each group option or one globally option? or something else. 
And it needs to be done so that it is clear how this option will work, because it is very similar to the automatic movement of tabs...
there are options?

**Comment by klint** [comment]
actually, the best would be to let the user decides at the time when he moves the tab to another group: 
- *left clicking* on the group name in the tab topbar menu would move it without switching (as today)
and
- *right clicking* on the group name in the tab topbar menu would move it and switch to it
or, alternative implementation
- *SHIT and left clicking* on the group name in the tab topbar menu would move it and switch to it

Would any of the 2 last option be technically feasible? :)
Thanks

**Comment by Drive4ik** [comment]
I can implement this:

> right clicking on the group name in the tab topbar menu would move it and switch to it

pressing the left mouse button will have the same behavior as now (with a message).

It's all right?

**Comment by klint** [comment]
That would be perfect indeed! Thank you

**Comment by Drive4ik** [comment]
and allow this action in bookmarks context menu like in #323
