### ISSUE TITLE
AutoScroll to current Group in Group List

### ISSUE THREAD

**Issue by GonzRon** [Drive4ik/simple-tab-groups#324]
**Is your feature request related to a problem? Please describe.**
If there are too many groups, or create new group, you must scroll down list to go to current group.

**Describe the solution you'd like**
please auto scroll to current group so I can rename a new group easily.

**Describe alternatives you've considered**
Maybe it is better to allow you to enter a group name directly when selecting multiple tabs and move to new group?

**Comment by GonzRon** [comment]
I do not think 5045b8d fixes the issue in 3.3.6.
# I upgraded to 3.3.6.  
# I click the STG icon
# I scrolled down long list of groups to the bottom
# I right click on group and select open in new window
# I click on STG icon in the new window
# current tab group is not visible in scroll list
# I must still scroll down to view current selected tab group in list.

**Comment by Drive4ik** [comment]
**Desktop (please complete the following information):**
 - OS and version: [e.g. Windows]
 - Firefox version: [e.g. 63]
 - Simple Tab Groups version: [e.g. 3.0.8]

**Comment by GonzRon** [comment]
of course:

* Windows 10 x64
* Firefox 65.0 (january 29,2019)
* simple tab groups 3.3.6

**Comment by Drive4ik** [comment]
I try another fix, please wait next release of STG

**Comment by GonzRon** [comment]
looks like it's fixed, хорошо сделано, Спасибо большое
