### ISSUE TITLE
Add current tab to existing Group

### ISSUE THREAD

**Issue by MadDogDean** [Drive4ik/simple-tab-groups#325]
**Is your feature request related to a problem? Please describe.**
I would like to be able to add my current tab to an existing Group

**Describe the solution you'd like**
From the current tab, I would like to click the Simple Tab Group icon, right click and existing Group and be offered to "Add current tab to this Group"

**Describe alternatives you've considered**
Alternatively, if a current tab could be dragged and dropped on the Simple Tabs Group - Manage Group browser page to be added
Alternatively, a simple "Add to Group" icon on the FF toolbar could present a drop-down list of existing Groups and the desired Group could be chosen.

**Comment by GonzRon** [comment]
you can already do this by right clicking on the tab, selecting simple tab groups, then selecting the group you want to move the tab to.

**Comment by MadDogDean** [comment]
Got it, thanks. Didn't see that right-click menu...

**Comment by Drive4ik** [comment]
@MadDogDean 
Please read the description and thumbnails on the add-on page
https://addons.mozilla.org/firefox/addon/simple-tab-groups/
