### ISSUE TITLE
Archive Tab Groups

### ISSUE THREAD

**Issue by GonzRon** [Drive4ik/simple-tab-groups#328]
**Is your feature request related to a problem? Please describe.**
after creating too many tab groups, the list of tab groups in the regular STG dialog is too long.  Some of the tab groups are only relevant to past projects.  Some of them I can delete, and I have already done so. 
 I do not want to delete some of them because I may need to refer back to some of these resources in the future.  

**Describe the solution you'd like**
I would like to shorten my tab groups list by moving older tab groups to a secondary archived tab groups list.  This archived tab groups list may be accessible via a context menu or inside settings somewhere, and you can archive individual tab groups to remove them from the main list, and you can also click "make active" on a tab group in the new archived tabGroups list to move the tab group back to the main or active tab groups list.

**Describe alternatives you've considered**
The alternative is to implement #302, which will make only parent projects or parent categories visible in the list, instead of individual tab groups, thereby shortening the list.  In the case of implementing 302, I would also want to be able to archive parent tab groups as well, so the feature request to archive tab groups still stands. The point is that currently 1 tab group -> 1 window, with #302, you have 1 Container -> (many) tab groups -> 1 Window per tab group.

**Comment by Drive4ik** [comment]
done)

![screenshot_1](https://user-images.githubusercontent.com/7843031/53193356-7108df80-3619-11e9-88cd-790a4aa57e12.png)
![screenshot_2](https://user-images.githubusercontent.com/7843031/53193361-72d2a300-3619-11e9-8eea-0ca1ba1e3143.png)
![screenshot_3](https://user-images.githubusercontent.com/7843031/53193368-7534fd00-3619-11e9-8b61-9d51e8aa84be.png)

**Comment by GonzRon** [comment]
hey, this is excellent work!!! this helps very much! it is not perfect solution (like #302) , but it is damn good solution because now my group list is smaller and I have backup of older groups.

Thank you!!!!

**Comment by hluposti** [comment]
Does this work correctly for others?

Yesterday I managed to export my "default" group, but not others. Since then, I'm unable to even update the "default" group with its new tabs - I still only see the tabs which were exported yesterday.

**Comment by AndriiOmelianenko** [comment]
Hey @hluposti @GonzRon @Drive4ik , is this a correct behavior?
- create a new group
- export group to bookmarks
- archive and delete group
- observe that bookmarks were deleted as well.

When I'm done with the group - I'd like to keep it somewhere for the history (if I'll need it later). Archiving doesn't work for me because the archived group still stays on the list. So I thought maybe bookmarking the group and then deleting it, but deleting removes the bookmarks as well.

**Comment by tnthi115** [comment]
I would also like to save history of groups that I'm done with. I would like to see the bookmarks not be deleted after exporting a tab group to bookmarks before deleting the group, or hiding archived groups in the main list as they are strangely only hidden in the "Manage groups" page.

**Comment by AndriiOmelianenko** [comment]
@tnthi115 I don't remember how I learned it, as I don't see any responses in here on that topic, but basically you can hide archived groups by right-clicking the cogwheel
![image](https://github.com/Drive4ik/simple-tab-groups/assets/12183923/58dd4533-fc9c-4e78-9457-8872f0c443be)

**Comment by tnthi115** [comment]
That helps a lot, thanks! I wish I had found that on my own, but I feel like that it could have been in the settings menu or more obvious somehow.
