### ISSUE TITLE
STG not loading

### ISSUE THREAD

**Issue by trovkio** [Drive4ik/simple-tab-groups#329]
**Describe the bug**
STG icon never stops spinning. The extension is not loading. 
FF 65. STG 3.3.7.1

I'm not a programmer . But I use this tabs organizer since the Tab Groups was killed.
The extension worked perfectly until three days ago. 

If I disable / enable I will lose all the groups I've been using since last year?

Thanks in advance, I just created an account in github just to ask you about this
 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: [e.g. Windows]
 - Firefox version: [e.g. 63]
 - Simple Tab Groups version: [e.g. 3.0.8]

**Additional context**

**Comment by Drive4ik** [comment]
Hi!
> If I disable / enable I will lose all the groups I've been using since last year?

You can disable and enable the addon as you please, and you will not lose the tabs and groups.

Did you try to restart the browser?

**Comment by trovkio** [comment]
> Hi!
> 
> > If I disable / enable I will lose all the groups I've been using since last year?
> 
> You can disable and enable the addon as you please, and you will not lose the tabs and groups.
> 
> Did you try to restart the browser?

Hi! Thanks

I restarted and updated FF and STG. I disabled enabled and still spinning and not loading.

Is there any limit of tabs and/or groups?

**Comment by trovkio** [comment]
> > Hi!
> > > If I disable / enable I will lose all the groups I've been using since last year?
> > 
> > 
> > You can disable and enable the addon as you please, and you will not lose the tabs and groups.
> > Did you try to restart the browser?
> 
> Hi! Thanks
> 
> I restarted and updated FF and STG. I disabled enabled and still spinning and not loading.
> 
> Is there any limit of tabs and/or groups?

I just disabled > restar FF > enabled STG and I lost all the groups that i had.

All the tabs that were grouped are one next to the other in the four windows I usually use. 

Is there a way to restore the tab groups? I do a lot of research in different fields that I had organized until this problem, and it will be a lot of work lost if I can't restore it.

**Comment by trovkio** [comment]
Sorry Drive4ik, could you please help me?

Now I have 4 windows with more than 80 tabs each. The STG icon still spinning and all my organized work apparently lost. 

Is there a way to save some file from the library/app support and remove reinstall the STG?

Best,

T

**Comment by Drive4ik** [comment]
Hi, I do not know how you do it, in the sense of losing tabs and groups, but I can say that the addon makes backup copies. You can find these settings in the add-on settings and try to restore the backup.
For further research I need more information. But I want to say once again that the addon will not perform synchronization until at least one tab is in the loading state.

**Comment by trovkio** [comment]
More info
I always use for windows open, because of the different displays I use.
The STG stopped working (icon spinning last three days)
I restarted FF several times (also the computer). Tried different wifi connections.
Today I followed you and:
I disabled / enabled STG : nothing happened (icon spinning)
And when I disabled STG and then restarted FF all the tabs where open randomly in the four windows I mentioned. 
I tried again enabling. Nothing happens

Where do I access the prefs considering the icon never stops spinning?
In the add on panel only see the enable/disable & remove

**Comment by Drive4ik** [comment]
Hey. Find in the download folder for the STG-backups folder. If there are backups there - copy it to a safe place. Delete the STG, restart the browser, wait for the active tab to load, install the STG and try to restore the data from that backup folder starting with the last one.

**Comment by grssam** [comment]
These are very specific steps to perform. ALL TABS MUST ALREADY BE LOADED is a must have before reinstalling. What is the plan to let all the users of the addon know these steps? Because every single one of them is going to face this issue now that the Firefox 66 is rolling out.

**Comment by Drive4ik** [comment]
@grssam It's not about Firefox 66, but the fact is that even without this extension, closing the browser with a tab that is not loaded will lead to its loss (loss of the tab url). webextensions cannot affect this.

**Comment by grssam** [comment]
@Drive4ik  that's not what I meant.  The extension does not load at all (when you try to install it), unless all available tabs are loaded. This should not be a limitation for the extension to load at all.

**Comment by Drive4ik** [comment]
@grssam a5f2852 Not wait loading tabs if no groups found

**Comment by dpalic** [comment]
having exactly the same issue.
How I got into the situation:
- firefox crashed
- restarted firefox
- tried to get my tabs
- now getting 
   ![Screenshot_00590](https://user-images.githubusercontent.com/1399203/58751342-835aab00-849d-11e9-9c55-5c048867ea49.png)
- the debug window
  ![Screenshot_00591](https://user-images.githubusercontent.com/1399203/58751380-fcf29900-849d-11e9-9083-e5bfceee16df.png)
- and in some random cases a flickering (disappearing and reappearing) 
   ![Screenshot_00592](https://user-images.githubusercontent.com/1399203/58751394-1562b380-849e-11e9-8b8b-58a3b8013b72.png)
hope it helps?

**Comment by nekohayo** [comment]
There have been no new comments/reports on this ticket since a year ago, are you folks still experiencing the issue with the latest version of Firefox and of the extension?

**Comment by Drive4ik** [comment]
@nekohayo No, this has been fixed
