### ISSUE TITLE
Loses tab data when used together with LoadOnSelect plugin

### ISSUE THREAD

**Issue by me21** [Drive4ik/simple-tab-groups#33]
I'm not sure which plugin causes the bug, but currently these two don't play well with one another. LoadOnSelect plugin prevents the loading of inactive tabs and sets url of inactive tabs to be "about:blank". Simple Tab Groups, in turn, saves the urls in its own storage. If I switch to another tab group, then back, all inactive tabs are now displayed as empty pages and do not restore.

I have opened the issue in LoadOnSelect repository too: https://github.com/igorofc/Load-on-Select/issues/3

**Comment by Drive4ik** [comment]
Hi @me21 !

Please retest this bug with latest addon version (now 2.1).

In this version (2.1) I added similar functional. You probably will not need "LoadOnSelect" addon

**Comment by me21** [comment]
Yeah, looks like it works, thank you!
