### ISSUE TITLE
Set default icon color for new groups

### ISSUE THREAD

**Issue by Adam111** [Drive4ik/simple-tab-groups#330]
The default icon can be set in the Options, but not the color for it. Right now when a new group is created it gets a random color.
For those who prefer the icon to be the same for all groups, a new option (under Options, something like "Icon color for a new group") to set the default color would be very helpful so it doesn't have to be set every time a new group is created.

**Comment by Drive4ik** [comment]
done. pleae wait next STG releaase

**Comment by Adam111** [comment]
Thank you for adding this new feature!
