### ISSUE TITLE
Create thumnail when group is viewved

### ISSUE THREAD

**Issue by gagarine** [Drive4ik/simple-tab-groups#331]
I'm not sure this add-on use the best ways to create thumbnails.

It seem that Panorama View create thumbnail (using canvas)  right when the group view is displayed and then cache the result: https://github.com/photodiode/panorama-view/blob/a844934a9f1d9211d8a5dc42b91547f840db7158/src/js/view.js#L36

```
async function captureThumbnail(tabId) {

	var data = await browser.tabs.captureTab(tabId, {format: 'jpeg', quality: 25});
	var img = new Image;

	img.onload = async function() {
		var canvas = document.createElement('canvas');
		var ctx = canvas.getContext('2d');

		canvas.width = 500;
		canvas.height = canvas.width * (this.height / this.width);

		//ctx.imageSmoothingEnabled = true;
		//ctx.imageSmoothingQuality = 'high';
		ctx.drawImage(this, 0, 0, canvas.width, canvas.height);

		var thumbnail = canvas.toDataURL('image/jpeg', 0.7);

		updateThumbnail(tabId, thumbnail);
		browser.sessions.setTabValue(tabId, 'thumbnail', thumbnail);
	};

	img.src = data;
}

async function captureThumbnails() {
	const tabs = browser.tabs.query({currentWindow: true, discarded: false});

	for(const tab of await tabs) {
		await captureThumbnail(tab.id); //await to lessen strain on browser
	}
}
```

In simple tab group it's a different technique by using browser.tabs.captureTab() :

[simple-tab-groups/addon/src/background.js](https://github.com/Drive4ik/simple-tab-groups/blob/1c7588a98237fa790fcab5b170b68ca85ddee8aa/addon/src/background.js#L869)

Today, if you activate the thumbnail, you have to revisit all your tabs for example. The cache is also only cleaned when your restart Firefox.
I already note that in #194  but this was not discussed.

**Comment by Drive4ik** [comment]
Hi. I do not quite understand what you mean. If you mean that you need to load a tab to get a preview, then there’s no other way, and putting it in a loop is not the best idea in terms of memory usage. The tab preview cache is cleared either by pressing the clear button, or if the url is no longer open in any tabs, again to normalize memory usage.

**Comment by gagarine** [comment]
My bad, I didn't read the code closely enough. Both use browser.tabs.captureTab.

But I still think generating the thumbnail only when we click on "manage groups" will save total usage of CPU. How long it take to generate 100 thumbnails? We only need to generated the one that was not generated the last time.

**Comment by Drive4ik** [comment]
The fact of the matter is that to create 100 previews, you need to load 100 tabs (unloaded/discarded tabs cannot create previews), so when 100 tabs are loaded, the code has already created 100 previews and when you open manage groups, time and resources are not used to create previews. Because they were loaded separately when loading each of the 100 tabs.

**Comment by gagarine** [comment]
I see. I didn't think about the discarded/unload tabs. I think you can close the issue then.
