### ISSUE TITLE
Configuration options for context menu items

### ISSUE THREAD

**Issue by Ayesh** [Drive4ik/simple-tab-groups#332]
**Is your feature request related to a problem? Please describe.**
It's not exactly a _problem_, but I personally go a long way with userChrome CSS to get rid of several context menu items in the tabs and URLs. While I certainly understand how helpful a context menu item in tab and links are, I think there are users who like to not have this option.

**Describe the solution you'd like**
I'd love it if we could have a couple check boxes in the plugin configuration page to toggle the context menu "Simple Tab Groups" for tabs and URLs. 

**Describe alternatives you've considered**
So far, I'm using a userChrome CSS style to `display: none` the items. 

Thank you so much for your immense work on this plugin. This is the best productive plugin I have in Firefox!

**Comment by Drive4ik** [comment]
done

**Comment by Ayesh** [comment]
Wow thank you so much.
