### ISSUE TITLE
Specify where Tab Groups are stored

### ISSUE THREAD

**Issue by technochitlin** [Drive4ik/simple-tab-groups#333]
**Is your feature request related to a problem? Please describe.**
Currently, Tab Groups I've created are being stored as a subfolder (named STG) in my browser downloads path; This, on my system, is on an external drive that is not part of my system backup.

**Describe the solution you'd like**
I would like to specify the folder where they are stored. If there is a way to do this currently I don't see it.

**Describe alternatives you've considered**
I manually copy the STG folder in my downloads folder to a location that does get backed up.

**Additional context**
I tried changing the path in the STG backups block in the Add-ons Manager, but it will not parse the path correctly and creates a misnamed folder in the downloads folder. Example- I enter "C:\Users\jay-d\OneDrive\Documents\STG-backups" as a path and it creates a folder in downloads named "CUsersjay-dOneDriveDocumentsSTG-backups"

**Comment by technochitlin** [comment]
I did find a way to specify a folder for a backup with the "Create Backup" button in the add-on manager; however I cannot change where the default automatic backups go...

**Comment by Drive4ik** [comment]
Sorry, but this is a restriction of the Webextensions API and you can no longer specify any other folders except the downloads folder.
