### ISSUE TITLE
Move Currently open Tab Groups to top of List and highlight to indicate they are open

### ISSUE THREAD

**Issue by GonzRon** [Drive4ik/simple-tab-groups#335]
**Is your feature request related to a problem? Please describe.**
Simple Tab Groups displays a list of all tab groups in two places, the main popup, and in the tab context menu when moving a tab to a different group, the list of groups is presented.  

However it is not shown which groups are currently open in windows in the background.
Also, the list is not sorted by most recently used tab groups.

**Describe the solution you'd like**
I propose the list of groups is sorted First by currently open, second by most recently used.
* highlight the Tab Groups that are currently open in other windows in this list.
* also, move most recently used tab groups to the top of the list.

**Additional context**
This is useful in many different circumstances when there many groups exist in the list in many different use cases and workflows.

**Comment by Drive4ik** [comment]
Partially fix this issue, added only highlight opened groups. Sorting groups are not available now

**Comment by GonzRon** [comment]
thank  you, this helps very much!
