### ISSUE TITLE
After Update to FF 66.0b11 STG does not start anymore

### ISSUE THREAD

**Issue by umbertones** [Drive4ik/simple-tab-groups#337]
**Describe the bug**
STG not loading and throwing an error, see attachment
![problem_stg](https://user-images.githubusercontent.com/10536470/53434461-f95efa00-39f6-11e9-897b-d1a4e2299979.jpg)
I restarted the computer and loaded the browser from scratch - error persists

**To Reproduce**
Install FF 66.0b11
Restart the Browser

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Kubuntu 18.04, fully patched
 - Firefox version: [e.g. 63]: 66.0b11 (66b10 was working)
 - Simple Tab Groups version: 3.3.9.1, 3.4 fails as well (deactivated, restarted FF, activated, error persists)

**Additional context**
The tabs are still to see under the "hidden tabs"-section in the upper right corner of FF

**Comment by umbertones** [comment]
Reverted to FF65.0.1, STG starts again, but all my groups are gone (all tabs in top level).
Restoring Backup worked

**Comment by umbertones** [comment]
Ok, last message.

Close FF65.0.1, installed 66b11, error returns
Close FF66b11, installed 65.0.1, STG starts and groups are there without update.
Somethings broken in FF66b11...

**Comment by Drive4ik** [comment]
I try to fix this bug, please wait next STG release and retest this issue.

**Comment by umbertones** [comment]
Thanks for the quick replay but sorry: 3.4.1. does not fix this for me. Same behaviour as above.

**Comment by Drive4ik** [comment]
STG v3.4.1 does not have this fix, please wait for the next release.

**Comment by umbertones** [comment]
Does the 3.4.2.1 have the fix? Thanks.

**Comment by Drive4ik** [comment]
Yes, this version has this fix.

**Comment by umbertones** [comment]
Sorry, again error with FF 66.0b14
![bug_STG_140319](https://user-images.githubusercontent.com/10536470/54393279-0db71e00-46aa-11e9-9efb-7ba99934f2ee.png)

**Comment by Drive4ik** [comment]
Try to remove the addon, restart the browser, install the addon and restore the backup.

**Comment by umbertones** [comment]
Thanks for your effort. After removing and reinstalling STG and FF 66.0.b14 now are working again as expected.

**Comment by grssam** [comment]
@Drive4ik  I am still facing the issue even after uninstalling the addon, restarting browser and installing the addon back. The browser won't load any tabs and STG would simply give the same error as shown in the previous comments

**Comment by grssam** [comment]
Please reopen

**Comment by Drive4ik** [comment]
@grssam Are you updated to the latest browser/addon version? What OS do you have?

**Comment by grssam** [comment]
I managed to make it work finally by uninstalling, reinstalling and creating my groups again from scratch. But it is broken yet again today in today's nightly 68.0a1 (2019-03-27) (64-bit)

I guess, time to say good bye to this addon if i want to continue using nightly.

**Comment by Drive4ik** [comment]
@grssam This is due to the fact that you roll back versions of the browser whenever you want, and you use the nightly version of the browser in a stable version of your profile and it is not advisable to do so.
https://www.ghacks.net/2019/02/16/firefox-extensions-to-use-different-storage-type-in-firefox-66/

**Comment by grssam** [comment]
@Drive4ik  - I only use nightly. I had moved to Release once, because of some issues with this and many more addons. But since last couple of weeks, I am using nightly on a completely new profile.
