### ISSUE TITLE
Query: Why the need for extra permissions?

### ISSUE THREAD

**Issue by tur-ium** [Drive4ik/simple-tab-groups#34]
Hi there, an issue but not a bug. Firefox now prompts me to give permission for Simple Tab Groups to "Access your data for all websites". I love this addon, but as an interested user I feel I should ask: a) What data does it require and b) why is it necessary now but not previously?

**Comment by Drive4ik** [comment]
Hi!

This permission need for tab thumbnail in manage groups:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/captureVisibleTab

> Creates a data URI encoding an image of the visible area of the currently active tab in the specified window. You must have the <all_urls> permission to use this method.

**Comment by tur-ium** [comment]
I see, thank you!

**Comment by Drive4ik** [comment]
I don’t know how I hadn’t thought of it before ...
Made optional
Option in the "Create thumbnails for tabs" settings
