### ISSUE TITLE
Q: How can I switch off the automated sorting for a particular site?

### ISSUE THREAD

**Issue by bloodmandarin** [Drive4ik/simple-tab-groups#340]
Hey Drive4ik, 

I am loving your add-on. Has filled the void, the Mozilla add-on had left in my workflow. 

As said in the title, I want to switch off the automated sorting of "youtube" into "entertainment" as I have noticed that I also use Youtube for work occasionally. How can I do this?

Thanks in advance and best of luck with future projects of yours. 
Jonas

**Comment by Drive4ik** [comment]
Hi!
How did you turn on the automatic movement of the tab youtube into "entertainment"?

**Comment by bloodmandarin** [comment]
I had hoped you could tell me that. 

I think I figured part out, which is that Firefox's follow-up feature to Tab Groups, namely "Multi-Account Containers" has this capacity. 

![always open in](https://user-images.githubusercontent.com/9247936/53570698-67c2ca00-3b67-11e9-8bcb-06090cfb07d9.png)

However, I have yet to figure out how I can switch it off again... Which is - then again - not your wheelhouse or responsibility. Sorry to bother, thanks for being so responsive!
