### ISSUE TITLE
STG shown as LEGACY in add-ons manager

### ISSUE THREAD

**Issue by kstev99** [Drive4ik/simple-tab-groups#342]
Not sure when this started, but with the latest version of Firefox Nightly, STG has a "Legacy" label and clicking on the add-on or the options takes me to a blank screen.  Still works as expected, and I am able to go to the manage groups screen.

![2019-03-01_211244](https://user-images.githubusercontent.com/32485060/53676373-e05c8000-3c66-11e9-8a29-cbd856540357.jpg)

**Comment by Drive4ik** [comment]
Yes, I saw this message, but I have no idea why it appeared. Also, I can not find anything connected with it on the Internet. If you have information about what it is, please tell me about it. Thanks.

**Comment by LiCybora** [comment]
Regression from nightly. The latest Nightly is fixed now.

Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1531658

**Comment by kstev99** [comment]
Yes, it was a problem with nightly.  Everything seems normal now.  Thank you for the very useful extension.

**Comment by Drive4ik** [comment]
Thanks guys!
