### ISSUE TITLE
Use Human Language for Catching Tabs

### ISSUE THREAD

**Issue by Riajyuu** [Drive4ik/simple-tab-groups#343]
![image](https://user-images.githubusercontent.com/16912240/53693074-cdb48900-3dd5-11e9-96d1-648b931d3aab.png)

Here regular expression is required.
Although I understand what you are talking about as a developer but I can't imagine how it would like if a personal never touch programming to use this.

You can learn this from Cookie Autodelete.

**Comment by Drive4ik** [comment]
Hi. I added simple buttons to add the current domain to the list.

![Screenshot_1](https://user-images.githubusercontent.com/7843031/54134904-75a70380-4421-11e9-9807-6a8637d63965.png)
![Screenshot_2](https://user-images.githubusercontent.com/7843031/54134909-793a8a80-4421-11e9-9828-7dac8a2afa49.png)
