### ISSUE TITLE
Export groups to bookmarks deforms my bookmarks!

### ISSUE THREAD

**Issue by 532910** [Drive4ik/simple-tab-groups#345]
I have `Bookmarks Toolbar/blah-blah-blah/blah-blah-blah/blah-blah-blah/A` and `Bookmarks Toolbar/blah-blah-blah/B` and four simple-tab-groups groups: `A`, `B`, `C` and `D`. And it doesn't matter what `Default bookmark folder location` I choose, `Bookmarks Toolbar` or `Bookmarks Menu`, `C` and `D` groups (for wich I don't have  same name folders) will be saved to `STG bookmarks/C` and `STG bookmarks/D` in  `Bookmarks Toolbar` or `Bookmarks Menu` respectively. BUT tabs from `A` and `B` will be added to `Bookmarks Toolbar/blah-blah-blah/blah-blah-blah/blah-blah-blah/A` and `Bookmarks Toolbar/blah-blah-blah/B`!

**Comment by Drive4ik** [comment]
Hi. This is not a bug - this is a feature) Initially, it was intended that you can move the folder with bookmarks to any place, but if there is no such folder, create it in a certain place. And if you don’t like this behavior, you can just change the name of the group.

**Comment by 532910** [comment]
I have four `A` folders: `Toolbar/A`, `Toolbar/blah-blah-blah/A`, `Toolbar/blah-blah-blah/blah-blah-blah/A` and `Toolbar/blah-blah-blah/blah-blah-blah/blah-blah-blah/A`. How are you going to choose one for the `A` group?

**Comment by Drive4ik** [comment]
The first one is selected by coincidence by name, that is, in this case, the `Toolbar/A` will be selected.

**Comment by 532910** [comment]
How are you going to prioritize `Bookmarks Menu` `Other bookmarks` `Bookmarks Toolbar`?

**Comment by Drive4ik** [comment]
This is the browser search logic for the bookmarks.

**Comment by 532910** [comment]
So simple-tab-groups will choose some of my folders with logic that it doesn't control and deforms bookmarks in it. This is a bug!

**Comment by 532910** [comment]
Moreover `Default bookmark folder location`' is ignored. When I choose `Bookmarks Menu`, `A` group will deforms bookmarks in `Bookmarks Toolbar/blah-blah-blah/blah-blah-blah/blah-blah-blah/A`

**Comment by Drive4ik** [comment]
Maybe you're right, I did multifunctional, but not very obvious. Fixed. Please wait next release

**Comment by Drive4ik** [comment]
Try retest on latest version

**Comment by 532910** [comment]
3.4.2 has the same problem. Sorry. Please reopen.

**Comment by 532910** [comment]
`Allow access to bookmarks`: `yes`
`Default bookmark folder location`: `Other Bookmarks`
`Export groups to 'STG bookmars' bookmark folder`: `yes`

**Comment by Drive4ik** [comment]
Sorry... update STG to v3.4.2.1

**Comment by 532910** [comment]
3.4.2.1 puts all groups into `STG bookmarks`. Thank you!
