### ISSUE TITLE
bookmarks folder customization

### ISSUE THREAD

**Issue by 532910** [Drive4ik/simple-tab-groups#348]
I'd like to customize:

1. `STG bookmarks` folder name.
2. The full path. Not only `Bookmarks Toolbar/STG bookmarks`,  `Bookmarks Menu/STG bookmarks`, `Other Bookmarks/STG bookmarks`
3. The folder per group. Group `A` -> `Bookmarks Toolbar/X`, Group `B` -> `Bookmarks Toolbar/X/Y`

**Comment by Drive4ik** [comment]
This functionality (similar) was already there, and I removed it in ticket # 345. I will not return as this will further complicate the work of the addon.

**Comment by 532910** [comment]
This issue has nothing common with #345. What return are you talking about? How name selection for `STG bookmarks` wil complicate the work of the addon? How the full path will complicate the work of the addon?

Yes, the per group folder will complicate the work of the addon. But this is only a part of this issue and hope the complication worth the result.

**Comment by Drive4ik** [comment]
I added customize `STG bookmarks` folder name. Please update addon to latest version

**Comment by 532910** [comment]
Thank you!
