### ISSUE TITLE
supoport for changing group color

### ISSUE THREAD

**Issue by 532910** [Drive4ik/simple-tab-groups#350]
Please add support to change the color of the group.

**Comment by Drive4ik** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/7843031/54362520-bd23ce80-4671-11e9-9d56-2513a88fbad1.png)
![Screenshot_2](https://user-images.githubusercontent.com/7843031/54362529-c01ebf00-4671-11e9-9b84-8db9aac5f9ea.png)

**Comment by 532910** [comment]
F.....g awesome! I always thought it's just a solid icon style.
