### ISSUE TITLE
Manage groups to be a toggle

### ISSUE THREAD

**Issue by Elon61** [Drive4ik/simple-tab-groups#351]
Coming from Quicksaver's TabGroup, i really miss that the "Manage groups" window was a toggle, that you could press the UI button / hotkey  / escape to exit it and resume browsing.

Related, could you hide all other tabs too while in the "Manage groups" window?

Would you consider adding this feature again?
(v4.3.2.1, FF v65.0.2 x64)

**Comment by Drive4ik** [comment]
Do you mean close the "Manage groups" window? `Alt+F4`?

**Comment by Elon61** [comment]
ah. i have it in tab mode, as when opened as a new window it's rather small, instead of being fullscreen / maximized. (i can't even maximize it myself for some reason)
in window mode, `Ctrl+W` works too. it would be nice if `Esc` could work too though.

**Comment by Drive4ik** [comment]
@Elon61 In next STG version you can close manage groups window by `Esc` button

**Comment by Elon61** [comment]
Thank you so much!
