### ISSUE TITLE
Option to differentiate between windows.

### ISSUE THREAD

**Issue by Elon61** [Drive4ik/simple-tab-groups#352]
First of all i would like to say that this extension is absolutely amazing and significantly better than every other one i found for Quantum, so thank you very much for your work!

with that said, would it be possible to add an option so that each window will have it's own groups / show only it's own groups, instead of all the groups for all the windows being shown at all times? (as was the case with the old panorama feature before quantum)
especially with the way you currently have the "Manage groups" tab setup, it gets very hard to keep track of things when you have multiple windows with multiple groups on each one.

i think a good way to implement it would be a checkbox in the "Manage groups" UI.

sidenote: the "Manage Group" window will not close if you use it to switch to a group in another window.

**Comment by Drive4ik** [comment]
Duplicate #302
