### ISSUE TITLE
Export all groups to bookmarks on demand

### ISSUE THREAD

**Issue by guitarjorge24** [Drive4ik/simple-tab-groups#353]
I know there is an option to export a single group to bookmarks. What I would like to request is a button to export ALL of the tab groups to bookmarks on demand, instead of having to do so manually for each group.

**Comment by Drive4ik** [comment]
Hi. This happens every time with automatic backup.
![изображение](https://user-images.githubusercontent.com/7843031/54917420-71401780-4f04-11e9-9ab4-d82bbaf1c501.png)

**Comment by guitarjorge24** [comment]
Thank you, I did notice that but I wasn't sure how to trigger it on demand. Is there a way to use that feature to back up the bookmarks manually and immediately? or do I always have to wait at least 1 hour?

I dont want to back up the bookmarks on an automatic schedule, I just wanted to bookmark all of them manually at specific but random points in time.

**Comment by Drive4ik** [comment]
You can find there
![изображение](https://user-images.githubusercontent.com/7843031/55253163-4ab01280-525d-11e9-8278-4009b79fc34a.png)

**Comment by guitarjorge24** [comment]
I tried right clicking the STG icon but I don't have that option. Do I have to enable it somewhere?

![image](https://user-images.githubusercontent.com/12472021/55275644-4caabd80-52bf-11e9-8115-1d430dcdea4a.png)

**Comment by klint** [comment]
it will be in the next update I guess :)

**Comment by Drive4ik** [comment]
@guitarjorge24 This feature already available in latest addon version :)

**Comment by guitarjorge24** [comment]
awesome! thank you!
