### ISSUE TITLE
Feature request: Add a "hide/show sidebar" shortcut

### ISSUE THREAD

**Issue by onlycparra** [Drive4ik/simple-tab-groups#354]
Scenario:
You are in fullscreen mode, and you want to use the entire screen without having the sidebar.

Current implementation:
Exit fullscreen -> Press [Alt] -> View -> Sidebar -> Simple tab Groups. Then, Enter fullscreen.

Requested implementation:
It would be nice to have a key (like F1) to show/hide the sidebar (as the plugin "tab center redux" does), so we can use the full screen for web content.

Thanks for the plug-in, it is the most useful thing in my browser!!

**Comment by HASJ** [comment]
Seconded.

**Comment by Drive4ik** [comment]
Done
![изображение](https://user-images.githubusercontent.com/7843031/55347110-a6c4a200-54bc-11e9-98b3-68286375ef3d.png)

**Comment by onlycparra** [comment]
thanks, you are the best :D

On Apr 1 2019, at 10:28 am, Drive4ik <notifications@github.com> wrote:
Done
[изображение]
