### ISSUE TITLE
Start up delay

### ISSUE THREAD

**Issue by Decopi** [Drive4ik/simple-tab-groups#355]
Hi,

Thank you for your nice addon.

I am not sure if this is a bug, but I use Nightly, and with your addon I have a 20 sec (at least) delay at Nightly' start up. By "delay" I mean that my Nightly doesn't load all my addons, and your addon keeps showing the loading circular animation. I am using Windows 10, with 9 groups at your addon, with a total of 50 tabs.

If I disable your addon, my Nightly launches almost instantaneously (less than 3 sec).

Is this normal?
Do you recommend me something to improve this delay issue?

Thanks

**Comment by Drive4ik** [comment]
Hi!
Nightly builds are very unstable, I do not advise using it as daily use, and they may give incorrect data to addons because of what they do not work properly or for a long time.

**Comment by Decopi** [comment]
Thank you for your answer @Drive4ik 

I tested in FF stable, and FF Beta. Unfortunately, the problem always is there.
In brief, it happens at every FF (Stable, Beta and Nightly). And reading more about it, I found other users saying the same I am saying: There is a significant delay impact at FF' start-up.

I am not complaining. I love your addon.
I just hope you can review your code, how knows, perhaps you can find a bug, and you can correct the delay.

This huge delay happens only with your addon. When I disable or remove your addon, FF' startup is almost instantaneous.

Thank you

**Comment by Drive4ik** [comment]
> By "delay" I mean that my Nightly doesn't load all my addons, and your addon keeps showing the loading circular animation.

Firefox load all addons asynchronously. And the fact that the spinner is spinning in the top bar is that it is waiting for the tab to load, because while the tab is loading I do not have access to its URL and I don’t know which group it belongs to ... There are many factors that can lead to data loss, so I decided that it was better to wait for the tab to load and not lose data.

**Comment by Decopi** [comment]
Thank you for your answer.
