### ISSUE TITLE
Group close button

### ISSUE THREAD

**Issue by 29ayush** [Drive4ik/simple-tab-groups#357]
**Is your feature request related to a problem? Please describe.**
When I have too many multiple groups and my computer gets laggy due to too many open tabs, so I would like to have a way to close specific group atleast.

**Describe the solution you'd like**
Adjacent to group setting, and group delete button in extension menu there can be a close button which closes all the tabs in the group.

**Describe alternatives you've considered**
Currently I have to open the group in a new window then close that window.

**Comment by Drive4ik** [comment]
You can enable this checkbox and the tabs will be automatically unloaded from memory when switching to another group.
![Screenshot_1](https://user-images.githubusercontent.com/7843031/55251768-fce5db00-5259-11e9-8f92-32f2e129cda5.png)

**Comment by 29ayush** [comment]
That does it for all the tabs and all the time, I want to do it by choice.

**Comment by Drive4ik** [comment]
done) see screenshots in #359 
fix will available on next release
