### ISSUE TITLE
Add Discard Tab/Group on right click menu on popup and distinguish loaded page vs unloaded/discard page

### ISSUE THREAD

**Issue by LiCybora** [Drive4ik/simple-tab-groups#359]
Actually they are two features, but both are discard tab related so combined in one issue.

**Is your feature request related to a problem? Please describe.**
Having too many loaded page cause performance issue. Although there are options like `Discard Tabs after Hide`, it might cause loss of data if accidentally switched group. User is the best to know which tab should be discarded. Thus, manually discard is preferred. Addon like "Discard Tab" is good, but not integrated with STG: If you want to discard tab in non-active group, you will have to switch to that group first and discard.

Moreover, when `Discard after Hide` is disabled, there is no way to know which group have active tab without using other addon. However, no known existing addon integrated with tab groups and just simply show out all tabs.

**Describe the solution you'd like**
Allow manually discarding groups/tabs in popup by right click group/tab name is preferred. This will allow user to discard tab in any group they want without switching.

Besides, it would be great if discarded/unloaded tab is displayed as grey, and groups without an active tab displayed as grey in popup as well.

**Describe alternatives you've considered**
For now, the only alternative is to use extra addon like "All Tabs Helper". However, it is not integrated with STG and all tabs are not grouped.

**Additional context**
Here's are ideas (Note: the image is faked for now):
![image](https://user-images.githubusercontent.com/40160522/55134390-9bdbdb80-5163-11e9-8ded-2201e605310e.png)

![image](https://user-images.githubusercontent.com/40160522/55134626-448a3b00-5164-11e9-9cf6-d3d886649915.png)

**Comment by Drive4ik** [comment]
done)
