### ISSUE TITLE
tab groups and session

### ISSUE THREAD

**Issue by rayman89** [Drive4ik/simple-tab-groups#36]
I'm looking fordward to use this addon but I was wondering if this addon saves the tabs for each group because in ff57+ session manager addons are very unripe so I wouldnt want risk loosing the tabs.

**Comment by Drive4ik** [comment]
Hi @rayman89 

You can backup tabs if you worry about your tabs.
This addon not working with firefox sessions API.
It has its own system for saving tabs

**Comment by rayman89** [comment]
Are there plans to make it so in manage groups you can perform actions to multiple tabs at the same time like re arranging moving to an existing or new group closing them etc?
