### ISSUE TITLE
Allow to backup to bookmark folder without also backing up to download folder

### ISSUE THREAD

**Issue by OdinGitDat** [Drive4ik/simple-tab-groups#360]
**Is your feature request related to a problem? Please describe.**
I'd like to have a backup of my groups, but I don't want to clutter my download folder with an ever amount of backups.

**Describe the solution you'd like**
Allow to backup to bookmark folder _without_ also backing up to download folder.

**Comment by Drive4ik** [comment]
done, please wait next release
