### ISSUE TITLE
Tab unexpected swap in different groups with different container.

### ISSUE THREAD

**Issue by Arffi** [Drive4ik/simple-tab-groups#365]
**Describe the bug**

Sometime tab happen unexpected swap when restart firefox if a tab has same title(URL?) in different groups with different container.

**To Reproduce**

For example:
1. Open two facebook.com in different groups with different container.

2. Restart Firefox + Unknown condition

3. Two facebook.com tabs swap groups automatically.

**Desktop (please complete the following information):**
 - OS and version: Windows 10 1809
 - Firefox version: 66.0.2
 - Simple Tab Groups version: 3.4.3

**Comment by Drive4ik** [comment]
I guessed that such a problem may arise... I will try to fix it as there will be enough time

**Comment by Drive4ik** [comment]
Hi! Please update addon to latest version - it was fixed)
