### ISSUE TITLE
Current Tab moves to switched to Group

### ISSUE THREAD

**Issue by BobDwyer** [Drive4ik/simple-tab-groups#366]
**Describe the bug**
When switching to a new group either with hotkeys or the context menu the current active tab is moved to the new selected group.

**To Reproduce**
1. Active tab 1a in group 1
2. Switch to group 2
3. Tab 1a becomes part of group 2 as tab 2x at the end of the tab list

**Expected behavior**
Tab 1a remains in tab group 1 and only tab group 2 tabs are visible

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Windows 8.1
 - Firefox version: 66.0.2 Build ID 20190326175229
 - Simple Tab Groups version: 3.4.3

**Additional context**

**Comment by mac-dev** [comment]
Same here. Win10.  	66.0.1

**Comment by mac-dev** [comment]
Restarted Firefox and disabled the Tree Style Tab and now it works as desired

**Comment by Drive4ik** [comment]
@mac-dev Thanks, I thought for a long time what it is connected with and did not think that there is a conflict with another addon. I will test

**Comment by Drive4ik** [comment]
@mac-dev I can't replicate this issue with Tree Style Tab. Tell me please, what settings you are change in addon Tree Style Tab ?

**Comment by fritz-k** [comment]
Disabling Tree Style Tab solved this issue for me, reenabling TST did not trigger it again though. At least for me, this bug only appeared sporadically before, so maybe it takes some time/specific actions while TST is enabled for STG to trigger this behaviour?

**Comment by Drive4ik** [comment]
Unfortunately, I do not know why this conflict is happening. I just don’t use this plugin, and I couldn’t say which settings affect what, and there are a lot of them.

**Comment by BobDwyer** [comment]
I do not use the Tree Style Tab and the issue is still occurring. To add to the issue description:
- switch to a different group (either by shortcut or from the button) and the current tab moves
- switch to a different group by selecting a specific tab in a group from the drop down list and the grouping remains as it should, i.e. the current tab stays in the previous group.

**Comment by BobDwyer** [comment]
This behaviour happens for me when the "Select After Closing Current" add-on is active. Disabling that add-on and STG behaves as expected. With SACC active then the current tab is dragged into the new group.

**Comment by Drive4ik** [comment]
Another addition to the piggy bank of conflicting addons...
