### ISSUE TITLE
Catch-all group for tabs not matching any regular expressions

### ISSUE THREAD

**Issue by tonycpsu** [Drive4ik/simple-tab-groups#367]
**Is your feature request related to a problem? Please describe.**

Tabs that don't match a regular expression open in whatever tab group is currently selected.

**Describe the solution you'd like**

I would like any tabs that don't match a regular expression for another group to be directed to a default group.  The logic would essentially be:

IF tab doesn't match any regular expressions
AND tab groups is designated as default / catch-all group
THEN move tab to that group instead of the active one

**Describe alternatives you've considered**

Having a .* pattern causes all tabs to go to that group, including ones that match regular expressions for other groups.

Writing a catch-all inverse regular expression for all of the patterns in the other groups is extremely unwieldy and error-prone.

**Additional context**

This was requested in #228 but was closed without explanation.  I believe the idea merits additional discussion and consideration for a future release.

**Comment by Honigmelone** [comment]
Hey I'd also need this functionality. But I already struggle with the negative regular expressions. Are there examples for this availible?

**Comment by HASJ** [comment]
This is sorely needed (by me).

**Comment by Drive4ik** [comment]
done, please see #562

**Comment by Drive4ik** [comment]
Please, update addon to latest version and test.
