### ISSUE TITLE
Gesturefy Action - Activate Tab Group from list

### ISSUE THREAD

**Issue by SixthStreet** [Drive4ik/simple-tab-groups#368]
**Is your feature request related to a problem? Please describe.**
Not a problem per se, but easier use for mouse heavy users.  A more direct way to directly select a tab group via Gesturefy as opposed to first, last, next, and previous tab groups.

**Describe the solution you'd like**
Add a new action for a popup window that has a group list to select from.  Same concept as {"action":"move-active-tab-to-custom-group"} but just for selecting/activating the chosen tab group.

**Describe alternatives you've considered**
Currently use the first, last, next, and previous tab group actions, or the nav bar icon.

**Comment by Drive4ik** [comment]
Hey. In fact, there is one hack that already works, but it is a bit uncomfortable)))
You can take a groupId like this:
edit group -> cut in buffer group name (leave empty name field) -> click save button -> remember group id into new group name -> edit group -> paste old group name -> click save -> input groupId into action:
`{"action":"load-custom-group","groupId":5}`
Profit :)
