### ISSUE TITLE
DataCloneError: The object could not be cloned.

### ISSUE THREAD

**Issue by Sophia10** [Drive4ik/simple-tab-groups#369]
**Describe the bug**
Since tha last Firefox update (today, 11.4., version 66.0.3 (64-Bit), upon startup and when clicking on the Simple Tab Groups-icon, I get an error message. All tabs have been moved to the default group (but I can't open any other anyways).

**To Reproduce**
1. Start Firefox or
2. Click on Simple Tab Groups icon (a yellow warning triangle)
3. Error message appears:
"Error: DatCloneError: The object could not be cloned.
resource://gre/modules/ExtenionUtils.jsm 0:1"

**Expected behavior**

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/26280279/55956323-feed6800-5c63-11e9-8942-4ba101c10deb.jpg)

**Desktop (please complete the following information):**
 - OS and version: Windows 8.1
 - Firefox version: 66.0.3 (64-Bit)
 - Simple Tab Groups version: 3.4.3

**Additional context**
It worked perfectly fine earlier today... Does anyone have the same problem or is it just me?

**Comment by bardware** [comment]
Come back to work on monday mornig, have the exact problem. There's a button that says something went wrong and offers to reload the plugin. The error remains but all tabs I had open in the various groups now appear.

![grafik](https://user-images.githubusercontent.com/802702/56113666-c947c800-5f5e-11e9-9695-b4df241fe587.png)

**Comment by Drive4ik** [comment]
This error is associated with a change in the data storage of all addons in Firefox version 66 and higher. Only reinstalling the addon and restoring from the backup copy will help. You can find backups in the download folder of the Firefox browser (STG-backups folder)

**Comment by bardware** [comment]
OK, uninstalling and newly installing helped. Thanks!

**Comment by Sophia10** [comment]
Same for me. Thank you!
