### ISSUE TITLE
List View (in 'Manage Groups' hide the thumbnails)

### ISSUE THREAD

**Issue by ajvsol** [Drive4ik/simple-tab-groups#37]
This would show all tabs within a tab group as a list within a column, similarly to how [Tab Groups Helper](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-helper/?src=userprofile) used to look like:
![](https://addons.cdn.mozilla.net/user-media/previews/full/134/134926.png)

This really helps when you have many tabs within a group by showing all your tabs in the window, as well as reduced browser load from showing so many thumbnails.

**Comment by Drive4ik** [comment]
I think that I can do it. Wait this feature in new versions.

**Comment by Keith94** [comment]
This would be great to have especially when "capture thumbnails for tabs" is turned off.

**Comment by neomodern** [comment]
This would be especially helpful to enable selecting multiple tabs at once to drag-and-drop into a new tab group as well.

**Comment by gagarine** [comment]
[Tilted tab group](https://addons.mozilla.org/en-US/firefox/addon/tiled-tab-groups/) is doing something like that (but is very buggy at the moment):
![image](https://user-images.githubusercontent.com/164074/56893476-13fb3100-6a83-11e9-80c7-38c811d04f27.png)

**Comment by Drive4ik** [comment]
Fixed.
Sorry for making you wait...

**Comment by Drive4ik** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/7843031/65327491-bd6eca80-dbbc-11e9-9577-0611e1b1a28f.png)
![Screenshot_2](https://user-images.githubusercontent.com/7843031/65327492-be076100-dbbc-11e9-9a6b-8deeda947213.png)
