### ISSUE TITLE
tie bookmark folder to file

### ISSUE THREAD

**Issue by 532910** [Drive4ik/simple-tab-groups#372]
I have a dream: to make ties between specific folded in firefox bookmarks tree and specific file on a filesystem tree.

File should look like: one line - one link. Or in the markdown format. Not urls should be ignored.

Under tie I mean:
adding/removing/modifying bookmark in firefox folder should immediately add/remove/modify url in file
adding/removing/modifying url in file should immediately add/remove/modify bookmark in firefox
removing file should remove firefox folder

**Comment by Drive4ik** [comment]
Firefox removed the functionality of direct access to the file system and many other features to ensure security. So it turned out WebExtensions - secure add-ons.
Sorry but it's impossible

**Comment by 532910** [comment]
file system access is still possible through native messaging

**Comment by Drive4ik** [comment]
To do this, you need to write a program for Windows and other operating systems. Unfortunately, I do not know the full functionality in this area.
