### ISSUE TITLE
STG auto backups failing more then succeding

### ISSUE THREAD

**Issue by megamanzteam** [Drive4ik/simple-tab-groups#374]
**Describe the bug**
Most of the time when checking my download history I see a backup file of STG failed to download more then succeed.

**To Reproduce**
Since it is an automatic process and some are succeeding it is hard to provide exact reproduction steps.

**Expected behavior**
Should be not failing, however since I don't know how the file is generated or being downloaded I don't know the process being used.

**Screenshots**
Sorry, I didn't think to grab some before writing this.

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Firefox version: 66.03
 - Simple Tab Groups version: 3.4.4

**Additional context**
None that I can think of at this time. Thank you for looking into this.

**Comment by Drive4ik** [comment]
Please check the download folder itself, and free disk space.

**Comment by megamanzteam** [comment]
I checked my default download folder and found the files that did backup. I checked my free space and I have over a 1TB of free space still. Any other suggestions for me to try?

**Comment by Drive4ik** [comment]
Does the "Open backup folder" button work in addon settings?

**Comment by megamanzteam** [comment]
Yes it does.

**Comment by Drive4ik** [comment]
It turns out that sometimes the backup works and sometimes it doesn't? What is the average size of backup files?

**Comment by megamanzteam** [comment]
currently around 7,000KB to 8,000KB but had some a while back at 28,000KB range.

**Comment by megamanzteam** [comment]
It was already off, but I just turned off the fav icons saving as well, just in case.

**Comment by Drive4ik** [comment]
I will try to look for a solution to this problem, I have already solved this problem, maybe something has changed

**Comment by megamanzteam** [comment]
Understood, let me know if you require any additional information.

**Comment by Drive4ik** [comment]
Hi! Do you have this issue on latest STG version?

**Comment by stinos** [comment]
I'm having this from time to time, will try to keep an eye on it to see if there's a pattern.

**Comment by Drive4ik** [comment]
I try to fix this issue. Now the code will try to save the file 5 times, and if all 5 times do not work, then an error. There are no other options, this is not an addon problem but Firefox, maybe it has conflicts in the system ... I don’t know
