### ISSUE TITLE
Simple-Tab-Groups icon on tab bar next to new tab button

### ISSUE THREAD

**Issue by zorkerz** [Drive4ik/simple-tab-groups#375]
I just reinstalled Ubuntu and now my simple-tab-groups icon is stuck on the firefox toolbar with the other add-ons before it was next to the new tab button. I don't see a setting to add it back there. Is there a way to move the simple-tab-groups icon up a row row next to the new tab button?

**Comment by Drive4ik** [comment]
https://support.mozilla.org/kb/customize-firefox-controls-buttons-and-toolbars
