### ISSUE TITLE
Switch group without hiding tabs of other/specific groups

### ISSUE THREAD

**Issue by ReporterX** [Drive4ik/simple-tab-groups#376]
First of all, thank you for the great addon.

**Is your feature request related to a problem? Please describe.**
I notice some noticeable delay every time I switch to a group. It takes like 3-4 seconds to complete a switch.

Tab groups are not supported in other addons, so hiding tabs from other groups will break some functionality offered by other addons.

I like the way that I have groups to organize my tabs and a grid view of them, but I don't want to have the hiding-and-switching effect.

I keep switching different tabs. I don't want to bear constant delays when I switch from one tab (in one group) to another.

**Describe the solution you'd like**
Perhaps another mode which disable hiding tabs of other groups. All groups will be shown even if I switch from one to another.

Or an option to decide which tabs (of a particular group) will always show, when you switch groups.

Thank you.

**Comment by Drive4ik** [comment]
Hi! So far, it is impossible to increase the speed of switching groups, but you can turn off the addon if you want to see all the tabs from all groups, also after turning on the addon, it resynchronizes all the tabs.

Read about the pinned tabs:
https://support.mozilla.org/kb/pinned-tabs-keep-favorite-websites-open
