### ISSUE TITLE
Scrolling on the stg icon should switch to prev/next tab group

### ISSUE THREAD

**Issue by sirKitKat** [Drive4ik/simple-tab-groups#378]
**Is your feature request related to a problem? Please describe.**
I was looking into a way to quickly switch groups with shortcuts (not possible I've found) and I tried Gesturefy, but I'm not ready for that yet :D

**Describe the solution you'd like**
When hovering over the Simple Tab Group icon in the menu bar, scrolling the mouse could go to the next/previous tab group.
Alternative, 2 extra buttons that I can place on the menu bar would also be a good solution (maybe as a plugin? You've made already a few of those I've seen ;) )
(I don't know what is possible with the current FF api)

**Describe alternatives you've considered**
Gesturefy

**Additional context**
When you have more tabs than screen width, scrolling on the tabs will move them. I'm looking for a similar behaviour :)
Also, adding the information to the readme about how people can switch groups quickly, or that keybord shortcuts are not possible at the moment would be nice

**Comment by Drive4ik** [comment]
> When hovering over the Simple Tab Group icon in the menu bar, scrolling the mouse could go to the next/previous tab group.

This is not possible for technical reasons. But you can use hotkeys.

If this is very important, then I can freely make 2 plugins: the next / previous group. But it will not be soon, I now have a lot of other work ...

**Comment by sirKitKat** [comment]
Thanks for the reply. While looking into other possibilities for switching groups I had a suspicion that scrolling would not be possible.
I'm looking forward for the plugins next/prev but this doesn't have to be soon for me (maybe others)

**Comment by Drive4ik** [comment]
You can try this addon [Gesturefy](https://addons.mozilla.org/firefox/addon/gesturefy/)
It can work with STG addon by events.
