### ISSUE TITLE
After a tab (in a group) is moved to another window, STG behaves inconsistently due to the group split over windows

### ISSUE THREAD

**Issue by jlokier** [Drive4ik/simple-tab-groups#380]
**Describe the bug**
After a tab (in a group) is moved to another window by a non-STG action, STG seems to behave inconsistently due to the group being split over windows. I have the impression parts of STG aren't expecting this can happen.

**Expected behavior**
The STG data model should anticipate that different tabs in a group might be in different windows (due to user activity or another add-on), and do something logical with that. Maybe the logical thing would be:
- When STG is asking itself which is the currently selected group in a window, to highlight in the popup menu, it should look at the group of the currently selected tab in that window.
- When STG is searching for an open window already using a group that is being requested, it should use a method that accomodates split groups (maybe before it brings the group's tabs into one window). For example, it would be most helpful to pick the window which contains the largest number of tabs in the group, so that one accidentally moved tab doesn't affect the decision.

**Desktop (please complete the following information):**
- OS is Mac OSX 10.9 (Mavericks)
- Firefox is 67.0b14 (beta channel at the time of writing)
- STG version is 3.4.4, updated 26 April 2019

**Comment by Drive4ik** [comment]
Sorry, but I do not quite understand what kind of action to your problem, and I don’t really understand the problem itself. If you mean moving a tab from one window (with a group) to another window (without a group) using Drag & Drop, then this script should work fine.

If it is possible to record on video behavior and error
https://www.screentogif.com/

**Comment by jlokier** [comment]
Sorry for the unclear description.

I'll try to describe a more specific set of actions, but I'm not using STG now, so this is from memory a few weeks ago:

1. In window 1, make a new group, and put at least two tabs in the group.
2. Drag one of the tabs to another window 2 (which is already open).
3. As a result, one STG group now has tabs in two different windows.
3. In window 1, while focused on a tab in the group, using the STG drop-down, switch to the group.
4. In window 2, while focused on a tab in the group, using the STG drop-down, switch to the group.

I found the behaviour in steps 3 and 4 were different, and one of them changes the currently focused window but the other does not, which tells me STG has a concept of "the window of the group". This is counterintuitive, because from a user perspective, the windows are similar, and the currently focused tab is in the selected group in both cases.

Then:

5. In window 1, using the STG drop-down switch to a different group, then using the STG drop-down switch *back* to the first group.
6. In window 1, using the STG drop-down switch to a different group, then using the STG drop-down switch *back* to the first group.

If I recall correctly, if done in the right window, this has the effect of bringing all the tabs in the group together into one window. But in the other window, it doesn't.

As I said, I'm not using STG now, and I'm not likely to use it soon (due to other issues I've reported, which probably are caused by my large number of tabs, with some duplicates and some "about:"). I understand it is hard work to maintain a project like this, and that you need high quality bug reports with testing, but I can't provide that this time. So please don't feel obligated to fix this issue for me, however I'll try to respond to questions if any. Thanks.

**Comment by Drive4ik** [comment]
Hi! Can you check if your problem is repeating on STG v4?

**Comment by Drive4ik** [comment]
This bug should be fixed
