### ISSUE TITLE
Simplify what happens when closing a temporary window that was used for a tab group

### ISSUE THREAD

**Issue by jlokier** [Drive4ik/simple-tab-groups#381]
**Is your feature request related to a problem? Please describe.**
Typically I have a "main" window where all my groups have their tabs hidden, and a few windows showing other groups. When I'm done with one of the other windows and want to close it, the ritual to do this is complicated with many steps, and I have to make temporary "new tab" groups to make it possible. If I have switched groups a few times in the window being closed, the ritual is also quite tricky, because I have to figure out which groups have been used in this window last.

The ritual I do currently is this:
1. In the window I want to close, create a new "empty group for switching" group and switch to it. It will have an empty new tab.
2. Go to my "main" window.
3. In the "main" window, switch to the group that was previously in the window I want to close. I have to remember which group it was, but as long as I checked before step 1 that is just an inconvenience.
4. In the "main" window, switch to each of the other groups that were used last in the window I want to close. Figuring out these groups can be tricky if I don't remember what I did recently, and requires me to look in the hidden tabs context menu, then search tab groups for the tabs I see.
5. Go back to the window I want to close.
6. Close the window. If I have completed steps 3 and 4 ok, the browser will close the window without an alert box. If I haven't, it will warn me that I'm about to close 2 tabs, 10 tabs, 100 tabs or whatever. Then I know I should go back to step 3 and try again - I don't want to close the window and kill those tabs!

**Describe the solution you'd like**
There should be a way to close a window, without losing the grouped tabs currently in the window, by moving them to another active window, or in some other way making them dormant. If the tabs are already in the "discarded" state, it seems like moving them to the main window or a window of choice should be quite fast. Ideally, just closing the window would do this, maybe with the popup that normally warns you are about to close N tabs having an option to move the tabs instead.
 
**Additional context**
I first encounted this problem when initially using STG to start organising my existing tabs. I had about 10 windows each of which had a lot of tabs. I'd make a group in each window, the group would adopt all the tabs in that window, and then I wanted to close the window, since I was using STG groups to organise, instead of unnamed windows.  Later, I still have this problem when trying to organise a workspace by making a temporary window for a task with one group's tabs in it.

**Comment by Drive4ik** [comment]
Hi! Please disable this checkbox:
![Screenshot_2](https://user-images.githubusercontent.com/7843031/57711216-fd55fc00-7676-11e9-9c84-00efffe5bdba.png)


and try this:
![save-opened-tabs](https://user-images.githubusercontent.com/7843031/57711409-532aa400-7677-11e9-852a-23bb96f31e81.gif)

**Comment by jlokier** [comment]
Does that keep the actual tabs alive, with all the tab's context (history, form data, Javascript state, etc) or does it just remember the URL and reopen that URL when selecting the group?

**Comment by Drive4ik** [comment]
Addon saves only the URL of the tab and restores them. It also saves favicon and thumbnails, but it does not affect the work, only on the display.

**Comment by jlokier** [comment]
Thanks. Unfortunately that behaviour does not save the tab's state, such as page history, forms being filled, Javascript state and scroll positions. It's quite different from moving the tab away from the closed window, to the main window, and the result is lost state.

Because it loses state of _invisible_ tabs, and there can be 100s or 1000s of invisible tabs which belong to currently-not-selected Tab Groups, I think that's quite a big problem.

You generally don't know which Tab Groups will have invisible tabs in the window about to be closed, because it depends on your previous history. In other words, if you opened any Tab Group in a window at some time, and haven't opened the same Tab Group in a different window since then, that Tab Group's tabs will be unexpectedly destroyed. This applies to any Tab Groupt that happened to be opened temporarily in the window, and who can remember that.

Because that's so unpredictable, I think that's quite a problem.

So I'm afraid I really can't agree with the advice to turn _off_ the checkbox "Warn you when closing multiple tabs" in a comment above. It's a dangerous operation; the warning is important. (Though I think some people won't realise that the warning is also talking about invisible tabs, managed by STG.)

**Comment by Drive4ik** [comment]
If the user closes the window, he should be prepared for the fact that all tabs of this window will also close.
Firefox webextensions no longer have unlimited power like old add-ons, and can no longer interfere with tabs (javascript, scroll etc.). It is also unsecure.
