### ISSUE TITLE
[Feature Request]: Tabs can be shared amongst groups

### ISSUE THREAD

**Issue by FlorianGit** [Drive4ik/simple-tab-groups#384]
So first of all, thank you for developing this addon. I switch between different sorts of activities during the day (programming multiple projects, reading news, administration, etc), and I'm able to create a tab group for each of these activities. This addon improves my overview in ways I had not thought possible and much better than other options I tried.

However, I also have some communication tabs (e.g. gmail, whatsapp web, telegram web) open all the time. I would like to have them visible all the time. I tried to add them to each tab group, but some of these (at least whatsapp web) only allows for a single active window at a time. Hence this currently is not possible, as far as I understand.

Would it be possible to have some 'supertabs' that are a single instance, but are open regardless of which tab group you have opened?

**Comment by falolaf** [comment]
I belive that you can "pin" the tabs. Then they will be available in all groups.
Right click on any tab and then click "Pin Tab". More to read here:
https://support.mozilla.org/en-US/kb/pinned-tabs-keep-favorite-websites-open
