### ISSUE TITLE
"Found hidden unsynchronous tabs": consumes too much RAM 

### ISSUE THREAD

**Issue by ShinobiWPS** [Drive4ik/simple-tab-groups#385]
**Describe the bug**
I was using about 800-900 MB of RAM,
When it found an unsynchronous tabs, it started to use about 2,2Gb of  RAM, all of a sudden.
After i clicked on "open unsync-ed tab", it went down to 900 Mb of RAM.
Note: before i noticed the unsynced tab warning , i was typing a mail and it was sluggish! with a LOT of latency.

**To Reproduce**
1. Take note of how much RAM you use now then restart PC while firefox is running
2. When you open firefox: If you get an unsynchronised tab ,look into the Task Manager and see the RAM usage of Firefox

**Expected behavior**
RAM usage to be pretty much the same or less than double anyway.

**Screenshots**
I missed the occasion to make some. next time.

**Desktop (please complete the following information):**
 - OS and version: win10
 - Firefox version: 66.03
 - Simple Tab Groups version: 3.4.4

**Comment by Drive4ik** [comment]
Hi! Please wait for version 4.4.2 (under review) or above and check it out. I did some code optimizations, should be better.

**Comment by grahamperrin** [comment]
@ShinobiWPS what's your experience with more recent versions of Firefox and more recent versions of the extension? 

NB this option (which I have _not_ needed to enable): 

![image](https://user-images.githubusercontent.com/192271/108649374-17ac4300-74b5-11eb-9d01-b01314a04530.png)

**Comment by ShinobiWPS** [comment]
Apparently everything seems smooth and without issues, I also enabled that option too since I don't mind unloading content I don't use.
Keep up the good work guys! :)

**Comment by grahamperrin** [comment]
@ShinobiWPS thank you, would you like to close this issue? 

(I can not.)
