### ISSUE TITLE
STG overrides sidebar hotkey (F1) with Tree Style Tabs

### ISSUE THREAD

**Issue by whittacre** [Drive4ik/simple-tab-groups#387]
Previously, I would use the F1 key to show/hide the Tree Style Tabs sidebar. This is adjustable in the TST settings but the default is F1.
Recently, an update to STG has hard coded F1 to show/hide STG instead. It doesn't mention this anywhere in the about page and there is no way to change it.
Disabling STG will return control to TST.

**Comment by Drive4ik** [comment]
Try this
![Screenshot_3](https://user-images.githubusercontent.com/7843031/57715736-1a42fd00-7680-11e9-88bc-dc11df1f67cc.png)
