### ISSUE TITLE
Tabs are discarded not hidden

### ISSUE THREAD

**Issue by CamJN** [Drive4ik/simple-tab-groups#388]
**Describe the bug**
When switching tab groups, all tabs in the old group are discarded and then the tabs from the new group are reloaded.

**To Reproduce**
1. Create 2 or more groups with tabs in them
2. switch groups
3. tabs are reloaded and lose state.

**Expected behavior**
Tabs should maintain state and not reload.

**Desktop (please complete the following information):**
 - OS and version: macOS 10.14.4
 - Firefox version: 67.0b19
 - Simple Tab Groups version: 3.4.4

**Comment by Drive4ik** [comment]
Did you check addon settings? Try to test in the new firefox profile

**Comment by CamJN** [comment]
I did check the addon settings, the checkbox to discard tabs is unchecked. I'll see if a new profile helps.

**Comment by CamJN** [comment]
Well this seems fixed in FF68 anyway, closing.
