### ISSUE TITLE
where is the STL backup folder? Can't load my stg-backup-...json files

### ISSUE THREAD

**Issue by mrtoddly** [Drive4ik/simple-tab-groups#390]
My computer crashed, and I could not find my Mozilla sessions folder because that folder is hidden in my new Linux system. So I saved what I could find, which were stg-backup-2019-...json files. These files are saved on a thumb drive. Now where do I find the STL backup folder to copy these backup files to? 
I attempted to use the STG option to import these files, but nothing happened. Is this a glitch?
Is there a way that I can access these files, that represent months of online research? STG needs a help menu that discloses some of this info. Thanks.

**Comment by Drive4ik** [comment]
I do not quite understand what you are doing and why you cannot do it. In addon settings there is a restore button. Click it and select the file located in the download folder of the browser STG-backups folder

**Comment by gkaklas** [comment]
It has been a year, @mrtoddly can this be closed? :thinking: (Personally I haven't had any issues restoring from backup, and I'm thinking that, since your computer had crashed, the issue could be that the STG backup files were not saved properly and they could be empty?)

It can always be reopened if you have any additional input!

**Comment by mrtoddly** [comment]
George
Thanks for your input. My issue was that I had STG backup files, but did
not know how (the procedures) to access them. They cannot be opened in a
TXT or DOC file. I am clueless how to retrieve that info.
But as to your question, yes the issue can be closed, as I never received
any advice that I could understand or use. It seems as if programs are
written to be used intuitively, and I am completely lacking in that
intuition. I need step-by-step, but it seems all respondents simply assume
that I know what I am doing. Like they assume I know where the add-on
settings button is. If I have an STG file, how am I to find this add-on
settings button. It is not in the file. Where is it? See, I simply don't
comprehend what other users were advising me to do. (This isn't the first
time I have encountered this situation in a help forum. I tend to elicit a
lot of eye rolls.)
Anyway, thanks again.
Todd
