### ISSUE TITLE
Conflict with SmartAdBlock

### ISSUE THREAD

**Issue by EstherMoellman** [Drive4ik/simple-tab-groups#393]
Hi!

SimpleTabGroups seems to have a kind of conflict with SmartAdBlock add-on (https://addons.mozilla.org/en-US/firefox/addon/smartadblock):

If I have SmartAdBlock enabled, and I mouse-click SimpleTabGroups' icon, its popup has a significant delay until opening. It doesn't matter where is placed the SimpleTabGroup' icon or the SmartAdBlock' icon. If SmartAdBlock is enabled, then SimpleTabGroups' popup will open with a delay (around 10 seconds).

And vice-versa, if I disable SmartAdBlock, the conflict disappears, and SimpleTabGroups' popup opens instantaneously.

Thank you in advance!

**Comment by Drive4ik** [comment]
I can't repeat it. Can you test on a clean/new Firefox profile? Can it depend on the tab with a specific url? How many tabs do you have in groups (approximately)?

**Comment by EstherMoellman** [comment]
Hi @Drive4ik ! Thanks for you reply.

First, is important to say that in my opinion, the issue is more related to SmartAdBlock (SAB) than to SimpleTabGroups (STG). In other words, STG has the weird behavior I described here in my previous post, only when SAB is activated. Days ago I already posted the same issue at SAB' GitHub, let's see if they find something.   

If SAB is set with few block-lists, and STG is set with few tabs/groups, then the issue remains there but is almost imperceptible. The issue becomes annoying in 3 scenarios: 1) By adding block-lists at SAB or 2) By adding tabs/groups at STG or 1) + 2).

It was almost impossible to use STG with 10 groups and 100 tabs, mainly because in this scenario the STG' popup has a huge delay before opening, and the "Manage Groups" page breaks. And yeah, I already tested in a FF' clean install with clean profile etc. An no, it doesn't depend on any url. It seems that SAB interferes with STG, as long as block-lists are added, and STG has more and more tabs/groups.

The conflict between SAB and STG is so annoying, that I disabled SAB because I can live without your STG :)

But both add-ons are fantastic, and I would love to have the two working alone, without conflicts. That is the reason I posted the issue at the SAB' GitHub and here. Hope you guys can find a solution.

Thanks in advance! :)

**Comment by Drive4ik** [comment]
I manage to reproduce when I started adding all the tabs in a row to the SAB exception. Strange but the window draws a long time open groups in the pop-up window with .... 25 tabs. I do not even know what it can be connected with. I will watch.
And what does not suit you uBlock Origin?
https://addons.mozilla.org/firefox/addon/ublock-origin/

**Comment by EstherMoellman** [comment]
Years ago UBlock/UMatrix were heroes. Today they are dinosaurs. I am not saying they are dead. I am just saying they are old, but old in the sense that new generations of ad-blockers are better. Even Ghostery today is better (here is an interesting article:  https://dev.to/remusao/adblockers-performance-study-5b47).

SAB is great in everything (RAM, blocking capabilities, browser speed etc). It gives much more than UBlock/UMatrix, but using just 25% of the resources. Yeah, SAB is not a firewall as UMatrix is. But ad-blocking or track-blocking is not about blocking everything... is about smart blocking... is about blocking just bad stuff.

As I said, I disabled SAB because I prefer STG :)
But even in this scenario, I am not going to use UBlock/UMatrix. I prefer other more efficient solutions.
I just hope the SAB' guys can solve and avoid conflicts with other add-ons. And conflicts are not just with STG. SAB conflicts with other add-ons. It is a pity.

Feel free to close the issue, if you believe nothing can do from your side.

Cheers! :)

**Comment by jingyu9575** [comment]
> Strange but the window draws a long time open groups in the pop-up window with .... 25 tabs.

@Drive4ik I think it is probably [this problem](https://discourse.mozilla.org/t/performance-issues-due-to-add-on-incompatiblity/31603). If `data:` URL is used in src of `<img>`, it can be intercepted by other extension's `webRequest` handlers, and SmartAdBlock's handler has a loop that runs 8000+ times.

[Bug 1490932](https://bugzilla.mozilla.org/show_bug.cgi?id=1490932) should be the issue of Firefox but bugzilla is down now so I'm not sure what is the resolution.

**Comment by Drive4ik** [comment]
@jingyu9575 Thanks for the tip. Maybe this is the problem, but Firefox devs did not fix it ((
