### ISSUE TITLE
Feature request: "Move to tab group" in tab manager view

### ISSUE THREAD

**Issue by AfroThundr3007730** [Drive4ik/simple-tab-groups#397]
A potentially useful feature to have here would be exposing the "move to tab group" item in the right-click menu when selecting a tab or multiple tabs in the tab manager view. So if I wanted to move several tabs to another group, instead of dragging, I could right-click and send to a specific group.

This is yet another suggestion to ease tab management for users with dozens of tab groups.

**Comment by s-light** [comment]
this would also show useful as a workaround for #395
