### ISSUE TITLE
Tree Style Tab tree is broken after STG group switch

### ISSUE THREAD

**Issue by cebas** [Drive4ik/simple-tab-groups#399]
**Describe the bug**
After switching to a new group, the tree of tabs managed by the Tree Style Tab extension is broken.
This doesn't happen everytime, and not always break in the same way.

Sometimes it flattens visually, but the little triangles in parent tabs continue working, but collapsing/expanding the wrong tabs.

Sometimes the tree keep working fine, but it's hierarchy changes lilke this:

Original tree:

* A
  * A1
  * A2
* B
  * B1
  * B2
* C
  * C1
  * C2

where A, B and C are top level tabs.

Changed tree:

* A
  * A1
  * A2
  * B
    * B1
    * B2
    * C
      * C1
      * C2

B and C lost it's top level position and began children of the previous sub-tree

**To Reproduce**
I can't reproduce it on purpose. I start using FF and suddenly this happens.
As a developer, I understand how important is this. I'm sorry.

**Expected behavior**
The trees keep their structure, internally and visually after changing groups.

**Desktop (please complete the following information):**
Linux Mint 19.1
Firefox 67.0
STG 3.4.4
TST 3.0.17

**Additional context**
I have also installed these extensions that may be interfering:
Firefox Multi-Account Containers (I'm not using it yet. Everything is on the default container)
Auto Tab Discard 0.3.2 (https://add0n.com/tab-discard.html)
uBlock Origin (with it's default settings)

There are other extension, but not related to tabs.

I'm not sure if this is a bug of STG or TST's.
I'm reporting it in both issue trackers.

**Comment by m-thomson** [comment]
I'm experiencing the exact same symptoms on MacOS with FF 67.0

It's really a shame :cry: . Having these two plugins work well together is literally my dream browser setup.

**Comment by Drive4ik** [comment]
This may possibly occur if tabs are reopened. For example, when closing a window.
Nevertheless, please check on the latest version of the addon v4. 
Tree Style Tab create tree with tab parameter `openerTabId`
STG not work/change/disable tab parameter `openerTabId`

If the problem returns, create an issue in the addon Tree Style Tab.

**Comment by cebas** [comment]
ok. thanks
