### ISSUE TITLE
"Manage groups" page does not display hidden tabs

### ISSUE THREAD

**Issue by xRiot** [Drive4ik/simple-tab-groups#400]
**Describe the bug**
When you hide a tab through [Hide Tabs](https://addons.mozilla.org/en-US/firefox/addon/hide-tab/) addon the tab is not visible in **Manage Groups** page. Fortunately you can still view it through the navigation bar icon.

**To Reproduce**
1. Install [Hide Tabs](https://addons.mozilla.org/en-US/firefox/addon/hide-tab/).
2. Add a tab to a group.
3. Right-click on tab and select `Hide Tabs > Hide Tab`.
4. Go to `Manage Groups`, the hidden tab is not visible.

**Expected behavior**
I would love to have the option to see the tab in `Manage Groups` even if it's hidden.

**Desktop (please complete the following information):**
 - OS and version: Debian 10 Buster (64-bit)
 - Firefox version: 68.0b8
 - Simple Tab Groups version: 3.4.4

**Comment by Drive4ik** [comment]
Done. This changes available on next release
