### ISSUE TITLE
"Catch and move tabs with containers to this group" does not work as intended

### ISSUE THREAD

**Issue by xRiot** [Drive4ik/simple-tab-groups#401]
**Describe the bug**
`Catch and move tabs with containers to this group` option in group settings is not catching new container windows.

**To Reproduce**
1. Install [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/)
2. Create a new group in `Simple Tabs Groups` addon and enable `Catch and move tabs with containers to this group` for the new group
3. Click on navigation icon of `Firefox Multi-Account Containers`, select `+` on the container group _(to open a new window inside container group)_.
4. The window is not visible in group in Simple Tab Groups addon.

**Expected behavior**
New container tabs should automatically be added to group with the above option enabled.

**Desktop (please complete the following information):**
- OS and version: Debian 10 Buster (64-bit)
- Firefox version: 68.0b8
- Simple Tab Groups version: 3.4.4

**Comment by Drive4ik** [comment]
Hi! Is this problem repeated in v4?
