### ISSUE TITLE
How to backup tab groups after major version release?

### ISSUE THREAD

**Issue by KingZee** [Drive4ik/simple-tab-groups#403]
I only updated firefox yesterday, I realized all my tab groups were flattened into a big group of everything. I remember backing up a while ago the first time I installed tab groups. How do I restore them? Will the backup overwrite the current open tabs that aren't part of any group? Thanks!

**Comment by Drive4ik** [comment]
Привет. Аддон попытается найти те же вкладки и поместить их в группу. Он не будет удалять вкладки. Или попробуйте перезагрузить аддон.
Вы можете восстановить резервную копию в настройках аддона - нажмите кнопку восстановления и выберите файл резервной копии. Но восстановление сотрет текущие группы.

**Comment by Drive4ik** [comment]
Hi. Addon will try to find the same tabs and put them in the group. He won't remove any tabs. Or try to reload addon.
You can restore backup into addon settings - click restore button and select backup file. But restore will erase current groups.

**Comment by KingZee** [comment]
I don't know why I didn't see the backup tab after the update, but re-installing worked, thanks!
