### ISSUE TITLE
Ability to discard (suspend) tabs that are moved to another group

### ISSUE THREAD

**Issue by nekohayo** [Drive4ik/simple-tab-groups#404]
In #359 (and maybe somewhere else too) you implemented the ability to "discard" tabs (i.e. freeze/unload them so that they stop eating the CPU and RAM), which works very well, except for one missing corner case: it does not happen when you right-click -> move one (or more) tab(s) to another group.

I would like to be able to have that; that once I move it to another group, it gets unloaded.

Not sure if this would require an independent setting for it, or if it should simply piggyback onto the existing "discard tabs on group switch" setting...

**Comment by Drive4ik** [comment]
done. Select tabs to move -> right click (context menu) -> select group -> and left mouse click on selected group with pressed Ctrl key (or Command on Mac)
if click right mouse on group - this select tabs after moving - no discard any tabs

**Comment by nekohayo** [comment]
Hmmm... The 2nd part kinda makes sense, but I'm not sure about the 1st part, i.e. the requirement for the ctrl key to be held down while finishing the move click: this is a bit un-discoverable, and I never remembered this; I would have expected that the tabs get unloaded automatically (even without ctrl) when moved to another group when the discard setting is enabled; all this time, with the current implementation, I was wondering why it kept using my CPU/RAM/etc. after moving tabs to another group (that I assumed should have stopped using resources since they're now in another group and I have the discard setting enabled), and so I had to start using the "Discard other groups" menu action feature manually each time recently, which is an extra step (and 3 extra clicks) that seemed a bit unnecessary in theory...

**Comment by Drive4ik** [comment]
You don't always need to unload tabs from memory. If you make an option in the addon / group settings, users will forget that they have enabled it. So I made it customizable when needed.
