### ISSUE TITLE
Shift-selection of a tab range in the sidebar doesn't work as expected (confusing selection indicators)

### ISSUE THREAD

**Issue by nekohayo** [Drive4ik/simple-tab-groups#405]
In #296 you implemented ctrl and shift selections, however it seems that there is a bug with the way shift (range) selections are handled.

If you open the sidebar (F1) and have a bunch of tabs, you are currently in one active (and therefore selected) tab; if you press and hold Shift and click another tab, it simply adds that other tab to the selection instead of selecting the whole range between the two tabs. However, if you click another (third) tab somewhere else, it will do a range selection between the 2nd-selected tab and the 3rd-selected tab. Oops!

The reason behind this, I think, is that STG does not consider the currently focused tab as the initially selected tab... and yet, the UI clearly shows it in the same kind of color as a selected tab (with the little color bar on the left) so it is confusing as it contradicts usual selection patterns in other UIs (including Firefox's main tabs UI). Normally I would expect to switch to the 1st tab to be selected in the range before shift-clicking the end of the range.

**Comment by Drive4ik** [comment]
That's right, only this is not a bug, it was made this way on purpose.
Imagine the situation, you have such tabs (** active, * selected)

1**
2
3
4
5
6

you want to move tabs 3-5 to another group, you press `shift+tab 3` (you have already selected tabs 1-3) and then `shift+tab 5` :

1**
2*
3*
4*
5*
6

you can remove the selection from tabs 1 and 2, but between them there may be a hundred tabs, for example


100**
201*
202*
203*
204*
205

and then you need to cancel selection from tabs 100 and 201 tab index.... ctrl + click will take a very long time
other way
but you can go to tab 201, make it active, and then make a selection 204, but if 201 is not loaded, then it will start loading, which will take some more time.

I understand that this is different from the implementation in Firefox, but it is more flexible.
