### ISSUE TITLE
whitelist tridactyl

### ISSUE THREAD

**Issue by robertgzr** [Drive4ik/simple-tab-groups#406]
hey I'm working on STG integration for tridactyl (based off an upstream wip branch so no hurry...)

the extension id would be `tridactyl.vim.betas@cmcaine.co.uk`

**Comment by Drive4ik** [comment]
done :)
Sorry for making you wait.

**Comment by Drive4ik** [comment]
If you don’t need any actions, tell me about them and I will delete them.
