### ISSUE TITLE
QuickSaver TabGroups import feature does not handle tabs that were in Firefox "reader" mode

### ISSUE THREAD

**Issue by nekohayo** [Drive4ik/simple-tab-groups#407]
STG version 3.4.4 on Firefox 67 on Linux.

When migrating my tabs from a QuickSaver "TabGroups" .json export file, I realized that a portion of them systematically got ignored or improperly handled (ex: the tab gets created as a blank tab, you can't just "load" it after import), and it took me a while to figure out why: it is all the tabs that were in "[reader mode](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages)" in Firefox, because Firefox internally represents them with a different (non-http/non-https) URI. So in the file format, it would look like this:

`{"entries":[{"url":"about:reader?url=https%3A%2F%2Fmacbethstudio.com%2Fblog-home%2Fbuilding-a-giant-overhead-light-bank","title":"Building a Giant Overhead Light Bank — Macbeth Studio","charset":"","ID":1201193829,"persist":true}],"lastAccessed":1548024227189,"hidden":true,"attributes":{},"extData":{"tabview-tab":"{\"groupID\":2}"},"index":1},`

I had to go through all those tabs in Firefox 56 to exit reader mode to get STG to import them correctly. Interestingly enough, STG/Firefox67 has no issue dealing with tabs in reader mode _after_ the import, i.e. if you visit some website and set it in Reader mode, exit the browser and restart it, STG/Firefox will restore it without problems (it seems).

While you're at it, it may be worth checking if your code handles that usecase for exporting/importing backups of STG itself, too...

**Comment by Drive4ik** [comment]
Hi. STG v4 supports this, but only from its backups

**Comment by nekohayo** [comment]
Ok sure, but why not support it in the other formats as well and save your migrating users from data loss and headaches? Is it that much different than supporting it in your own format? (I honestly don't know)

**Comment by Drive4ik** [comment]
Of course, I can do support for reading mode, but do you really think that there are people who have not updated Firefox for so long?

**Comment by Drive4ik** [comment]
done :)
