### ISSUE TITLE
Can we get this for Chrome?

### ISSUE THREAD

**Issue by 29ayush** [Drive4ik/simple-tab-groups#408]
I used it for firefox and I really liked it, Now I switched to chrome, so can I get this for chrome?

**Comment by LiCybora** [comment]
Impossible unless chrome implement the missing API.

See: [this](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide) and [this permission](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs#permissions)

**Comment by Drive4ik** [comment]
Porting to chrome is possible only if new functionality is added as @LiCybora wrote

**Comment by tonglil** [comment]
I'm curious, is it possible to use:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/discard

as alternatives to `hide` on Chrome?

**Comment by Drive4ik** [comment]
Of course you can! STG did just that before version 3.
Imagine just switching groups from 500+ tabs ... 
And they all start loading at the same time ..

**Comment by Kol9yN** [comment]
What about to make it as temporal solution - likes bookmarks manager.
when you change group setup, it unload previous group from memory, btw, Chromium now have feature to unload tabs
