### ISSUE TITLE
The groups button on ALL windows takes the colour of the most recently opened group 

### ISSUE THREAD

**Issue by Philip-Sutton** [Drive4ik/simple-tab-groups#41]
In latest version (2.2), when you create a new window, the 'simple tab groups' button on ALL windows takes the colour of the most recently opened group.  I think that each window should keep its own colour (as was the case previously).   Cheers, Philip

**Comment by Drive4ik** [comment]
Browser button colors will change after focus on window.
Is this how it is?

**Comment by Philip-Sutton** [comment]
Yes.  But I find the colour changing confusing.  (I guess I'll get used to it!)

**Comment by Drive4ik** [comment]
I'm sorry, but this is restriction of WebExtensions API...
