### ISSUE TITLE
STG Nukes Tabs When Multiple Tab Group Windows Are Closed.

### ISSUE THREAD

**Issue by JYNxYoshii** [Drive4ik/simple-tab-groups#413]
**Describe the bug**
Say that I don't like Discord and choose to use the webapp in its own container, but I also need to access something from my Main or Research containers. I leave Discord open in one window and open either my Main or Research container in another. After everything is done, I close the Main/Research window and then the Discord window. When I next open Firefox, all of my tabs from the Main/Research container are nuked. When I say 'nuked', I mean they are all replaced with New Tabs.

**To Reproduce**
--Create two or three STG containers, populate them with plenty of tabs (5+).
--Keeping an STG container open in your window (Say you're on YouTube in the Main STG container), open the STG dropdown, right-click and open another STG container in a new window.
--Do something, whatever, then close the second window, then close the first window, quitting Firefox altogether.
--TA-DAAAA! You have now lost all or nearly all of your tabs in the second STG container that you opened in a new window.

**Expected behavior**
Well, it would be great if it didn't nuke your tabs when you used another STG container in a second window, but apparently the addon uses a single instance method rather than multitasking, which is what the options insinuate.

**Desktop (please complete the following information):**
 - Win7Enterprise 64-bit, also confirmed on Win7Pro 64-bit, Win10 LTSC 64-bit, Ubuntu 19.04 64-bit, and Pop!_OS 64-bit, all over the last 10 months across a SATA3 SSD, NVMe SSD, and a 5400 RPM HDD. Storage and system appear to be independent of the issue.
 - 54, 64, 67, and now 68.
 - STG current version, cannot recall other versions.

**Additional context**
I think that this could be a critical issue that might be unpatchable, simply because of how Firefox operates. This only happens when you open another container in a new window, so it could be that either Firefox refuses to save the particular data when the window is closed, or it could be that the method for saving the data that is used in STG only saves data when the app itself is closed and not the window. If so, that means that you could lose all of your data just by multitasking or referencing data from other tabs simultaneously.

The reason why this is such a concern? I just lost about 20 references for a side project, and if it wasn't for the constant backup that I have enabled, I would have no real hope of finding them again. In the blink of an eye, an end-user can lose everything because they chose to open a second window.

**Comment by Drive4ik** [comment]
Can you more simply describe the problem?
If I understand you correctly, I can answer, Firefox webextensions do not have a strong effect on the state of the tab. If you closed it, then it is closed, and STG creates the same tab in the background so that you do not lose it permanently. But the state of the tab will be reset. No other way.

**Comment by Drive4ik** [comment]
@JYNxYoshii Please check this problem in the latest version of the addon, it should be solved

**Comment by JYNxYoshii** [comment]
Sadly, it was not. As to the problem, thanks to your description, I now know exactly what the problem is. See, I have restore tabs enabled. This means that it will save the tab title and URL but not load it until the tab is activated. So, by technicality, it registers as something of a New Tab. Sadly, I don't think that this is a solvable issue on your end, merely a problem with how Firefox works. Thanks for your time and reply. I'll have to find an alternative method for keeping my tabs.

Great addon, however, it helps keep things tidy.

**Comment by JYNxYoshii** [comment]
If you're interested, I did put together this Imgur album with a few screenshots detailing the problem.
https://imgur.com/a/cKxNb2s

**Comment by Drive4ik** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/431#issuecomment-520475572
Doesn’t it happen for you?
P.S. After closing the main window, everything is saved

**Comment by neuffer** [comment]
How do you shutdown Firefox? File-Quit (Ctrl-Q)?
My FF is running from system shutdown to system shutdown and is automatically killed by the init system of the OS (Linux) during the shutdown.
Alternatively I usually kill it when it needs a restart since it otherwise wants to close >>100 tabs.

"Restore previous session" has been enabled since the option first appeared in FF

**Comment by Drive4ik** [comment]
> @neuffer How do you shutdown Firefox? File-Quit (Ctrl-Q)?

Yes. Force shutting down Firefox when you turn off the system is not good. He may not have time to save the data that he should.
