### ISSUE TITLE
Suppress group delete notification

### ISSUE THREAD

**Issue by yarnweaver** [Drive4ik/simple-tab-groups#416]
Hi, I think Simple Tab Groups is great. However, the desktop notification generated upon deleting a group is extremely irritating, and I don't know how to disable it.

Is it supposed to be possible to disable it? Thanks.

**Comment by yarnweaver** [comment]
I have discovered that if you kill firefox from your task list when the group delete notification displays, then the notification instantly disappears too. That tells me that the display of the notification is being handled by firefox, rather than by the underlying operating system. So I'm looking for a workaround either within firefox config or at the window-manager level, but I'd appreciate other ideas about how to suppress them, thanks.

**Comment by yarnweaver** [comment]
I have found a solution - albeit an ugly one. In firefox you want hamburger menu > Preferences > Privacy & Security > Permissions > Pause notifications until Firefox restarts.

Voila! No more irritating group delete notifications. Snag is, as the menu option implies, closing and reopening firefox makes it forget. Additionally, the option to pause notifications will only appear after you have had at least one notification since launching firefox.

So I am now looking for a way of automating the process of pausing notifications as quickly as possible upon launching firefox - although I'd still appreciate any better ideas, thanks.

**Comment by yarnweaver** [comment]
I've discovered a simpler method for suppressing them. Firstly, visit website for testing HTML5 notifications - such as https://www.bennish.net/web-notifications.html or https://web-push-book.gauntface.com/demos/notification-examples/ - and click the relevant button on the web page to cause it to request permission to give notifications. Grant it permission, and then bookmark it.

Then, each time you launch Firefox, visit the website from the bookmark, and click the button to generate a notification. Once the notification appears, there will be a cog symbol in the bottom right hand corner. This will open a context menu - and from this menu, select "Pause notifications until Firefox restarts".

I tried saving these web pages for offline use; when loaded from offline, they still create the notification, but unfortunately the cog widget that allows you to open the menu does not appear, although maybe a local http server might get around that problem.

I may also see if I can modify the Simple Tab Groups addon so that it doesn't generate notifications but I suspect it will probably take me at least a few weeks to figure out how to do this. I'd still appreciate any other suggestions, thanks.

**Comment by Drive4ik** [comment]
Hi! Do you delete groups very often?))
I can make an option in the add-on settings so that the message does not show after deleting the group, but this also has a negative side - if you accidentally delete the group, then you will not immediately understand this.

**Comment by Drive4ik** [comment]
Done. I added option into addon sessings `Show notification after group delete`
