### ISSUE TITLE
Add setting to protect a group from getting discarded.

### ISSUE THREAD

**Issue by taro8** [Drive4ik/simple-tab-groups#417]
Hey, I like this addon as i was a happy user of the good old Tab Groups.

I have many, many tabs and it really eats up the RAM. STG has the option to discard groups to save on RAM. The problem is if you have any videos playing in the discarded tab they get reloaded after going back to them, meaning you have to find where you were at before switching tab groups.

I would suggest to add an option to "tag" a tab group as "protected" meaning it does not get discarded when its hidden, while other groups that are not "protected" get discarded normally.

This way you would be able to keep stuff you want always loaded in a "protected" tab while having other groups discarded when hidden to save up on RAM.

**Comment by Drive4ik** [comment]
Hi. STG v4 has group option `Don't discard tabs into this group after hide`
