### ISSUE TITLE
Tab Mix Plus + Simple Tab Groups

### ISSUE THREAD

**Issue by xmas578** [Drive4ik/simple-tab-groups#42]
TabMixPlus adds functionality to not load tabs before they're chosen, if SimpleTabGroups would support this feature so tabs opened from another group won't load automatically ('cause there may be too many of them, i've got firefox crashing a few times in this way), that would be great.

P.S. Quantum sucks

**Comment by Drive4ik** [comment]
Please tell us where you got this information from or give us a link.

**Comment by xmas578** [comment]
About Quantum thing?)

**Comment by Drive4ik** [comment]
No, about "TabMixPlus adds functionality to not load tabs before they're chosen"

**Comment by xmas578** [comment]
Doublechecked that, it appears that functionality for not loading tabs before they're chosen is built-in in Firefox itself (sorry about that, i was using Tab Mix Plus so long, so it became inherert for me).
Still adding an option to limit amount of tabs loading upon choosing a group would be just awesome...
...as an option of preventing auto-coloring groups upon creating.
