### ISSUE TITLE
STG fails to load after 4.0 upgrade

### ISSUE THREAD

**Issue by solymosi** [Drive4ik/simple-tab-groups#420]
**Describe the bug**
After the addon has auto-updated to version 4.0, suddenly it stopped working and started displaying a yellow exclamation mark in the place of the STG icon. Hovering over it displayed a message similar to "STG has failed to load, click here to reload".

To work around the issue, I have restored the last v3.x version for now.

**To Reproduce**
1. Do nothing
2. Wait for the auto-updater to update STG to 4.0
3. The addon breaks while the browser is running, no restart is needed

**Expected behavior**
Everything keeps working as expected, the addon doesn't crash

**Desktop (please complete the following information):**
 - OS and version: Win7
 - Firefox version: 68.0.1
 - Simple Tab Groups version: 4.0.0

**Comment by Drive4ik** [comment]
Hi. Sorry for this issue, please do this https://github.com/Drive4ik/simple-tab-groups/issues/419#issuecomment-518813788

**Comment by solymosi** [comment]
Thanks, that fixed it!
