### ISSUE TITLE
Latest update clobbers standard macOS app preferences shortcut [cmd+,]

### ISSUE THREAD

**Issue by tribayf** [Drive4ik/simple-tab-groups#421]
Hi! Love your plugin, but I'm having a problem with the latest version.

**Bug Description:**
The standard shortcut for opening the application preferences menu in macOS [cmd-,] is overridden by the "Load next group" action in the latest 4.0.0.1 release of Simple Tab Groups.

**To Reproduce:**
1. Update Simple Tab Groups from 3.4.4 to 4.0.0.1
2. Keyboard shortcut [cmd+,] loads next tab group instead of opening Firefox preferences
3. Reverting to 3.4.4 restores the correct shortcut behaviour, but it seems that tab groups exported in 4.0.0.1 cannot be restored in 3.4.4

**Expected behavior**
1. Standard OS shortcuts should not be overridden by default
2. Binding the "Load next group" action to a new shortcut should restore the default behaviour of [cmd+,] (currently this does not work)

**Desktop (please complete the following information):**
 - OS and version: macOS 10.12.6
 - Firefox version: 69.0b11
 - Simple Tab Groups version: 4.0.0.1

**Comment by Drive4ik** [comment]
Hi. You can change shortcut in browser:
![Screenshot_3](https://user-images.githubusercontent.com/7843031/62616812-19390900-b919-11e9-8ccc-e538b14edfcd.png)
![Screenshot_4](https://user-images.githubusercontent.com/7843031/62616820-1b9b6300-b919-11e9-949d-05834b10e933.png)

**Comment by LiCybora** [comment]
However, not all keys can be recorded in the this shortcuts page. e.g.: punctuation such as `[`, `]`. `;` or `~` etc. They are restricted by the API `commands`. Those keys still work when setting them in legacy shortcut recording page, so please do not discard them.

If there is conflict between two pages, the one setting in new shortcuts page will override the legacy. So in order not to surprise legacy user, would it be possible not setting a default?

Source: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations

**Comment by Drive4ik** [comment]
LiCybora you're right. Since there are such problems with hot keys, then I will remove them. Let users put what they want.
37f3f554c62f2fbf10cbea3b0dbdd2ca08c4b596

**Comment by tribayf** [comment]
> Hi. You can change shortcut in browser:

@Drive4ik ah, I never noticed that before. Thanks for the tip! And thank you for the fix as well.
