### ISSUE TITLE
Need install simple tab groups

### ISSUE THREAD

**Issue by popkutt** [Drive4ik/simple-tab-groups#422]
It says 'Need install simple tab groups' notification on bottom right corner when clicking on the icon. FF 68.0.1, W10 x64.

**Comment by Drive4ik** [comment]
Click (no close) on this notification

**Comment by popkutt** [comment]
Thank you,


(no close)? there is only the X button fos close.

Also all my tabs are gone, any way to restore them? I had a SG tab open and
all the groups were empty.

Elvis Nigol
www.nordoutlet.com

**Comment by Drive4ik** [comment]
What version of `Simple Tab Groups` addon do you have?

**Comment by popkutt** [comment]
Version 4.0.0.2

**Comment by Drive4ik** [comment]
Hi. You can restore closed windows by Ctrl+Shift+N.
And you can restore from latest file backup.
