### ISSUE TITLE
Unable to change the group

### ISSUE THREAD

**Issue by Michel-Rotta** [Drive4ik/simple-tab-groups#423]
**Describe the bug**
Since the last update, I have a request to modify the autorisation for the private tab. In this time, all the tabs are open. After the modification evry thing seen correcte.

But it was impossible to change the group. If I try to, it open the groupe I ask and change just after every time for the same group. 

If I open a new tab who as it's adresse attribuated to a specific groupe, the mod change to this group, but if I try to modify for an other groupe, the problem is the same. 

**To Reproduce**
1. Try to change the group
2. Cry !

**Desktop (please complete the following information):**
 - Windows 10 - 18362
 - Firefox version: 68.0.1
 - Simple Tab Groups version: 4.0.0.2

**Comment by Drive4ik** [comment]
Could you more simply describe the problem, can take screenshots.

**Comment by Michel-Rotta** [comment]
![Img2](https://user-images.githubusercontent.com/848785/62634418-27495280-b936-11e9-8233-c15b44fd2b8f.png)
![img1](https://user-images.githubusercontent.com/848785/62634420-27495280-b936-11e9-85fe-c0f81576281d.png)

When I open the selection (Img1) and chose any of the other groups, It stay to the groupe "Allopneus" (Img2)

**Comment by Drive4ik** [comment]
It can not be :)
And there were no errors/notifications?
Do you has this button? If you has it, please click on it, save file and send it to me
![изображение](https://user-images.githubusercontent.com/7843031/62635040-9bd4bf00-b93f-11e9-95aa-e759b4fc622c.png)

**Comment by Michel-Rotta** [comment]
It's just very strange.

I don't have this buton "Save Last Error Logs into JSON file", so I suppose I haven't any error.

I leave my office to my home, for that I put the computer in hybernation. When I arrive home, STG work fine and change the group without any problem. Very strange.

I have one tab who disaper, a internal company web site I can have at home. I'll make a test tomorow, maybe I can have a problem when this site is on, but it's a site I use every day, befort the problem to. 

Best regard, 
Michel

**Comment by Michel-Rotta** [comment]
How tu reproduce this bug.

1. create a group
2. modify the properties and add an URL how have to be in this group.  (see img11). Here I hask that all the URL with allopneus.com go in this group.
3. Open the group. In this group, open some tabs an one of them with an URL with the name above.
4. Try to change to another group, and you stay in the previous group.

Best Regards,
Michel



![Img11](https://user-images.githubusercontent.com/848785/62685465-02e78780-b9c3-11e9-9169-26e9a8203efb.png)

**Comment by Drive4ik** [comment]
Restarting the browser gives any effect?

**Comment by Michel-Rotta** [comment]
I try the restart computer to, no effect.

**Comment by Drive4ik** [comment]
![62685465-02e78780-b9c3-11e9-9169-26e9a8203efb](https://user-images.githubusercontent.com/7843031/62877688-4417c880-bd30-11e9-82a2-df8b008e3980.png)
