### ISSUE TITLE
The addon is completely broken!

### ISSUE THREAD

**Issue by 532910** [Drive4ik/simple-tab-groups#424]
It shows:  "Something went wrong, click here to reload STG addon."
As soon as I click it new page is opened "Please disable add-on access to private mode in windows".

1. I have no windows. It's debian.
2. I have no "private mode" permission.
3. All my tabgroups are merged into one widow, it's completely impossible to use firefox at all. Please fix it ASAP!

**Comment by Drive4ik** [comment]
Please update addon to latest version (now v4.0.0.2) it has simple manual how to do this.

**Comment by 532910** [comment]
It's already 4.0.0.2!

**Comment by 532910** [comment]
I've not updated it manually. It's automatically updated.

**Comment by Drive4ik** [comment]
You have opened a tab with pictures how to disable incognito mode?

**Comment by 532910** [comment]
Yes.

**Comment by Drive4ik** [comment]
Did you do as in the pictures? 3 steps
