### ISSUE TITLE
Why are you asking the user to change browser settings without explanation?

### ISSUE THREAD

**Issue by bughit** [Drive4ik/simple-tab-groups#425]
```
Welcome to Simple Tab Groups v4
Please enable "Restore previous session" in browser settings:
```

**Comment by Drive4ik** [comment]
Because the tabs will not be saved, and the addon will not work.

**Comment by bughit** [comment]
Whatever the reason is you should put it into the the page asking for the change. Why do you expect the user to blindly carry out you instructions?

As to the specifics.
> addon will not work

Are you referring to not saving tabs or something more? 

By the way, 4.0.0.2 upgrade also hid all my tabs (they were not part of any group), any reason you needed to do that?

**Comment by Drive4ik** [comment]
> Are you referring to not saving tabs or something more?

The link between the group and the tab in v4 is saved in the session, if the session is not restored, the tab will not open when the browser starts and will be absent in the group. In the old version (v3), the tabs were saved elsewhere, and this was the cause of numerous problems, bugs and slow work.
Tabs that weren’t in groups were hidden for normal migration to v4. Why are you so indignant? You can find them here:

![изображение](https://user-images.githubusercontent.com/7843031/62642302-10aef580-b94e-11e9-8348-f0b2d08b38ef.png)

> Whatever the reason is you should put it into the the page asking for the change. Why do you expect the user to blindly carry out you instructions?

I can suggest you use another addon:
https://addons.mozilla.org/firefox/addon/hide-tab/
It is not updated and does not ask to do anything.

**Comment by bughit** [comment]
> Tabs that weren’t in groups were hidden for normal migration to v4. Why are you so indignant? 

Are you kidding me? All my tabs suddenly disappear without explanation (due to your upgrade) and you think that's reasonable?

> I can suggest you use another addon:
> https://addons.mozilla.org/firefox/addon/hide-tab/
> It is not updated and does not ask to do anything.

There's no issue with upgrading or requesting changes. The problem is:

1. Asking the user to make changes blindly without explanation.
2. Hiding all user tabs without any real necessity and no explanation.

**Comment by DavidBM** [comment]
@bughit chill man. He is doing his best. There is no reason to be edgy. I think you have a valid constructive feedback point and an bug, but honestly, I don't think this is the way to communicate it. As a developer I would feel bad if my user (that don't pay me) speak with me like this. You got enjoyment and usefulness from this add-on for some time, maybe a bug is tolerable, right?

**Comment by neuffer** [comment]
The problem is that this is now happening on every browser restart.
Tabs are duplicated, triplicated, some or all groups are suddenly partially or completely empty (this morning all groups were empty for example) and the tabs may or may not end up with the hidden group-less tabs or get lost. This morning I estimate I lost upwards of 3/4th of my tabs.
 
Before I already wasn't very happy when the addon lost a few tabs every couple restarts, but I could live with it. This version however is definitely not production ready.

**Comment by Drive4ik** [comment]
@neuffer You are talking about another problem. It’s one thing when the tabs just disappeared and you can show them, and another thing is when the groups become empty.
If you turned on session recovery in your browser settings, then you need to restore backup from a file in the add-on settings. There is a corresponding functionality.
