### ISSUE TITLE
Hot key "Ctrl + ~" no longer works

### ISSUE THREAD

**Issue by mkeroppi** [Drive4ik/simple-tab-groups#427]
Describe the bug
Hot key "Ctrl + ~" no longer works

To Reproduce
Hit "Ctrl + ~" on keyboard and nothing happens.

Expected behavior
Expected to switch to next tab group.

Desktop (please complete the following information):

    OS and version: Windows 10
    Firefox version: Firefox 68.0.1
    Simple Tab Groups version: 4.0.0.1

Additional context
Shortcut works on some tab but not others.
Seems may be linked to when the tab opened - tabs that were opened after the addon is loaded seems to work with the shortcut.  Tabs that were opened before the addon is loaded (e.g., when the browser is first started) does not work with the shortcut.

**Comment by mkeroppi** [comment]
Seems may be linked to when the tab opened - tabs that were opened after the addon is loaded seems to work with the shortcut. Tabs that were opened before the addon is loaded (e.g., when the browser is first started) does not work with the shortcut.

Further: tested to not work on a "New Tab" but works but the "New Tab" is loaded with an actual website.

**Comment by LiCybora** [comment]
The reason is mentioned in hotkey page:
`1. These hotkeys will only work on web pages (http:, https:), not on the browser pages (about:), because the WebExtensions API does not allow this.`

When the page is new tab, that is `about:newtab` and thus not working.

**Comment by mkeroppi** [comment]
Then it still no longer works for pages that were loaded early.  It used to work prior to version 4.

**Comment by Drive4ik** [comment]
@mkeroppi They could not work on secure browser pages (`about:...` `addons.mozilla.org` etc). 
But you can configure other hotkeys that will work on these pages:
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

available hotkeys:
https://developer.mozilla.org/ru/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands#Key_combinations
