### ISSUE TITLE
F10 overloads Firefox behavior from "Show menu" to "open manage groups"

### ISSUE THREAD

**Issue by jjdelc** [Drive4ik/simple-tab-groups#428]
**Describe the bug**
The new version makes the F10 key open the "Manage groups" tab. But that key is used by the browser to "Show menu". Now hitting F10 both shows the menu and opens the tab, which is unexpected behavior when I just wanted to show the menu.

**To Reproduce**
1. Install version 4.0.0.1
2. Hit F10
3. "Manage groups" tab will open and the browser window menu will both show.

**Expected behavior**
Only the browser action should happen without side effects.

**Comment by Drive4ik** [comment]
You can configure this hotkey:
https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox
