### ISSUE TITLE
'Scratch' group that is emptied when you close the browser

### ISSUE THREAD

**Issue by adc17** [Drive4ik/simple-tab-groups#429]
**Is your feature request related to a problem? Please describe.**
Since v4, we have to enable restoring the previous session on startup. Sometimes this is fine, because I want tabs to persist across sessions (like when I save them in simple tab groups, thank you <3), but other times I just want to open a few tabs, then close the browser and forget all about them (without closing each tab individually first).

**Describe the solution you'd like**
A special tab group (maybe called 'scratch') that is auto-emptied when the user exits firefox.

**Describe alternatives you've considered**
An override of firefox's default 'restore session' behaviour, so that tabs are not restored when you're not in a tab group. I would be happy with either option, but this alternative messes with default behaviour, which I think is to be avoided if possible.

**Additional context**
n/a

Thanks for all your work on this plugin 👍

**Comment by Drive4ik** [comment]
Hi! You can disable addon option `Create a new group when opening a new window`, open new window and tabs in it, and after close it - they will be forgotten. Or you can open private window (incognito) the addon in this window does not work at all, and Firefox itself will forget everything that was there after closing this window.

**Comment by adc17** [comment]
> Hi! You can disable addon option Create a new group when opening a new window, open new window and tabs in it, and after close it - they will be forgotten.

Not anymore 😞, when 'Restore previous session' is checked, firefox remembers the window and tabs if you close and reopen. 

This is the behaviour I'd like back, which is why I made the feature request.

**Comment by adc17** [comment]
Should also have dealt with the second option:

> Or you can open private window (incognito) the addon in this window does not work at all, and Firefox itself will forget everything that was there after closing this window.

This has other complications, like not storing history. The behaviour I'm after is 'normal' firefox behaviour without session restore—I open some tabs, close firefox, reopen firefox, the history is there, but the tabs aren't there.

**Comment by Drive4ik** [comment]
I understand what you want. Have you tried using one of these add-ons for working with sessions? On your choice:
https://addons.mozilla.org/en-US/firefox/search/?platform=WINNT&q=session

**Comment by adc17** [comment]
Thanks for this advice @Drive4ik, are you suggesting I replace simple tab groups with one of these (they look like they store sessions, not like they remove them when the browser closes)?

**Comment by Drive4ik** [comment]
No, I do not propose replacing the STG. These addons have different functionality. I just showed the add-ons that are managed by session management, in them you can delete a session that you do not need.

**Comment by adc17** [comment]
@Drive4ik I'm still confused, I'm looking at [session sync](https://addons.mozilla.org/en-US/firefox/addon/session-sync/?src=search) for example, and I see no way to configure it to only save sessions that are part of a tab group. Can you give me a more concrete example of the workflow you're proposing I use to get the 'only save pages in a tab group' behaviour?

**Comment by Drive4ik** [comment]
Maybe you need to configure this options
![изображение](https://user-images.githubusercontent.com/7843031/64870503-146c2100-d64c-11e9-891e-9467f44d5892.png)
?

**Comment by adc17** [comment]
@Drive4ik I don't understand. Here's what I'm after: 
- Tab groups that are preserved if I close and reopen the browser.
- Tabs outside a tab group (or in a special tab group) that are not preserved if I close and reopen the browser.

Is this possible since v4? If yes, please list the steps I can take to get this behaviour. If no, would you add this functionality or should I just close the issue?

**Comment by Drive4ik** [comment]
> Not anymore 😞, when 'Restore previous session' is checked, firefox remembers the window and tabs if you close and reopen.

Version 4 and higher no longer saves tabs in its storage. Tabs are saved in browser sessions. This is done for greater stability and acceleration of the addon. Unfortunately, without option `Restore previous session`, the addon will not work, since the browser will not restore tabs from the session. And as far as I know, it is impossible to make custom which tabs to restore and which not...

**Comment by adc17** [comment]
Ok, that sounds like it's not possible, no worries. I will close this issue as it's a no-go request. Thanks for all your work on the plugin!
