### ISSUE TITLE
Cuando abro el navegador la pestaña de whatsapp web que está fija se abre otra vez

### ISSUE THREAD

**Issue by mperezguendulain** [Drive4ik/simple-tab-groups#43]
Cuando abro mi navegador, la pestaña de wattsapp web (https://web.whatsapp.com/) que tengo fija se abre otra vez, es decir, tengo repetida esa pestaña fija, tambien se abre fija.

Esa pestaña yo no la fijé, sino que instalé el complemento: WhatsApp™ Quartz en su versión 0.1.5 (https://addons.mozilla.org/es/firefox/addon/waq/)
Creo que el error tiene que ver con este complemento.

**Comment by Drive4ik** [comment]
Sorry, but I no understand what the issue.
Can you translate to English, or create screenshots or record GIF animation of issue?

http://www.screentogif.com/

**Comment by aleksejrs** [comment]
IIUC: The add-on WhatsApp™ Quartz creates a pinned tab. When mperezguendulain starts Firefox, a new WhatsApp™ Quartz pinned tab is added.

**Comment by Drive4ik** [comment]
Hi! Ok, but how this plugin is related with STG? STG does not touch/work with pinned tabs.

**Comment by aleksejrs** [comment]
The reporter believes the opening of another tab has something to do with STG. That's all.

**Comment by Drive4ik** [comment]
@aleksejrs Thanks for helping)
@mperezguendulain STG does not work directly or indirectly with "WhatsApp™ Quartz"
Thanks
