### ISSUE TITLE
Hotkeys appear hardcoded; don't respect STG preferences

### ISSUE THREAD

**Issue by jwhitley** [Drive4ik/simple-tab-groups#430]
**Describe the bug**
STG 4.0.0.2 appears to have hardcoded hotkey settings for switching previous/next groups, and doesn't respect the user configured hotkeys (or no hotkeys).

**To Reproduce**
Prerequisites: Ensure that more than one STG group exists

1. Type ⌘, (Command-<comma>) or ⌘. (Command-period)
2. Observe that these keys switch groups backwards and forwards, respectively
3. Remove all hotkeys set in STG preferences; in my case the above keys weren't even set
4. Type ⌘, or ⌘.
5. Observe that these keys still switch groups backwards and forwards

**Actual behavior**
STG switches groups forward (⌘.) or backwards (⌘,) regardless of hotkey preferences configuration. This is especially bad on macOS, since ⌘, shadows Firefox's own (and the macOS conventional) Preferences shortcut key setting.

**Expected behavior**
The user configured hotkeys (e.g. ⌃` and ⌃⇧`, or none at all) should work as expected.  No hotkeys should be hardcoded. 

**Desktop (please complete the following information):**
 - OS and version: macOS 10.14.5
 - Firefox version: 68
 - Simple Tab Groups version: 4.0.0.2

**Comment by LiCybora** [comment]
Related: #421

Workaround: use the official shortcut key page shown as above post to remove or set something else for the default hotkey. The author will remove the default one and honor user setting in next version.

**Comment by jwhitley** [comment]
Thanks @LiCybora.  It does look like this issue is fixed by 37f3f554c62f2fbf10cbea3b0dbdd2ca08c4b596, so I'm really just waiting for a new release.

**Comment by Drive4ik** [comment]
fixed in #421
