### ISSUE TITLE
Group lost (all about:blank) when closing second window

### ISSUE THREAD

**Issue by uselessgithub** [Drive4ik/simple-tab-groups#431]
Firefox 68.0.1
STG 4.0.0.2

When using multiple windows, groups are lost (url of all their tabs are now blank) when closing a second or third window.

How to reproduce :
- create 2 groups A and B with some tabs with real urls
- open group A in current window 1
- open new window 2
- load group B in window 2
- close window 2
- try to manage groups:  -> group B is full of "New Tab" about:blank instead of the real urls.

Expectd behaviour:
- tabs in group B should not be blanked

**Comment by Drive4ik** [comment]
Are you doing the same thing?

![save-closed-tabs-in-window](https://user-images.githubusercontent.com/7843031/62877404-a1f7e080-bd2f-11e9-9a22-c72c638725a6.gif)

**Comment by Drive4ik** [comment]
Please retest this issue on latest STG v4.0.3
