### ISSUE TITLE
REPEATED TABS ISSUES

### ISSUE THREAD

**Issue by EstherMoellman** [Drive4ik/simple-tab-groups#432]
Hi @Drive4ik ! I have the following issue:

If a tab is repeated in one or more groups, STG tends to deal bad with this, sometimes the repeated tabs are deleted or hidden, or sometimes they appear in wrong groups etc.

Yeah, I confess that I'm a "heavy-STG-user", having more than 30 groups, with more than 500 tabs.... and this might not help normal STG' functions. Also, I use Temporary Containers, and seems to me that sometimes STG and TC don't get along (some tabs and STG' backup are corrupted. I easily can see that, if for example I count the total of tabs at STG' groups, then I disable or remove STG, and as result more tabs appear to me (than the total of tabs appearing at original STG' tab groups)). 

Thanks!

**Comment by Drive4ik** [comment]
Hi! I never used `Temporary Containers` addon, but I added functional to create containers which not exists in Firefox on restore STG backup

**Comment by EstherMoellman** [comment]
... thanks @Drive4ik ... but adding containers to STG' backup, I still believe this is not the "bottom of the issue". Besides the STG' backup, something is wrong with repeated tabs, with FPI (first-party-isolation), with ad-blockers, with etc. At STG, sometimes tabs behaves weird. I repeat and stress the word "sometimes"... it is not all the time. Also, it can be Firefox' bugs, or other add-ons conflicts etc... I'm not saying this necessarily is a STG' bug.

Sadly, this is happening randomly, I can't point for sure a perfect way to reproduce this bugs. For now, this just appear/disappear on my STG' daily use. Very annoying by the way.

**Comment by Drive4ik** [comment]
> And sometimes STG' data is corrupted, for different reasons. I point again to the example, where using 500 tabs in 20 groups, if STG is enabled, "x" number of tabs appear at each group, but if STG is disabled the total number of tabs may be higher (than STG enabled). I stress the word "sometimes"... it is not all the time. 

This is normal behavior if some tabs do not belong to any group. For example, here you can see / move / close tabs from other windows that are outside groups
![изображение](https://user-images.githubusercontent.com/7843031/62954945-e8654200-bdf8-11e9-970e-1c2996f2cf9f.png)

**Comment by EstherMoellman** [comment]
... yeah, but of course, I was talking just about the case where there are not tabs out of STG' groups, where the number of tabs at STG-enabled should match the number of tabs at STG-disabled... tabs that were grouped at STG, but somehow disappeared, went hidden etc, and they only reappear when STG is disabled.

Another spooky weird effects, happen when:

a) A tab is open at group "X", we move to group "Z", and the tab at "X" appears at the same time at "X", "Z" and even other groups (sometimes by restarting Firefox, the issue is solved, and the appears only at "X" group).

b) Blank-tabs opened in group "X", appear in group "Z" and not in group "X".

c) Corrupted backups.

d) Conflicts with blocker-add-ons (tracking, ads etc)... they mess a lot with STG, almost making it unusable.

Etc.

This is not happening all the time. And I can't say for sure "how", "when" or "why" it happens.
Also, as I said, it might be a Firefox' bug, another add-on conflicting with STG.

But STG is so good, that I can't work without it. So I learnt to coexist/tolerate this issues.

From my ignorant point of view, I believe that a new STG abandoning "hiding"/"discarding" functions, and working just with "bookmarking" (tabs), may solve lot of problems, lot of conflicts, and it might be better in terms of browser performance. This is one add-on trying to do this (https://addons.mozilla.org/en-US/firefox/addon/tab-group-switch/). STG still is much more advanced. But something is saying me that "bookmarking tabs" is better than "hiding/discarding".

**Comment by Drive4ik** [comment]
@EstherMoellman Hi, can you retest your issues with STG v4.0.1.1 into new profie without other addons?

**Comment by EstherMoellman** [comment]
@Drive4ik , yeah, of course, it will be my pleasure.

We are a small "club" of university students (around 150 members in 8 different countries), using FF' Nightly with special CSS customizations, hacks etc. I offer you the help of these 150 students (including me) in order to test your fantastic add-on, or to do other tests, researches etc... whatever we can help, I offer you.

But please, just give me some days.

**Comment by Drive4ik** [comment]
Hi, it's better to use the latest version

**Comment by Drive4ik** [comment]
@EstherMoellman And please do the same
https://github.com/Drive4ik/simple-tab-groups/issues/382#issuecomment-521181724

**Comment by EstherMoellman** [comment]
Hi @Drive4ik !

So, I took a couple of days to do the test you requested me. I believe that in real life tests (let's say 2 weeks testing) it would be possible to see and to identify more issues. But with these couple of days testing, I already have for you some results I want to share.

50 users participated on your requested test.
We used the specific FF' prefs you asked me to use.
Also, we tested using new profiles without add-ons.
But we tested only on Nightly, because is Nightly what we only use.
We used 500 tabs and 30 groups.

In brief:
Issues still happen with the STG' latest version. They are more or less the same issues I already reported you, and other users reported you.
One of the most common issues is tabs disappearing from original group "X", and appearing in different groups. It seems like when we jump from one group to another, some tabs are discarded but not hidden.... and that's the reason these tabs remain appearing at other groups (restart browser sometimes solves the issue). It doesn't happen with all the tabs, but it does happen with some tabs (and same tabs) all the time. Here are two tabs where this issue appears many times in some users:
https://userstyles.org/styles/browse/recently-updated?page=1 
https://techxplore.com/news/2019-07-robot-machine-harvest-lettuce.html 

Also, STG' popup (navbar icon) seems more snappy/slow than previous versions, it has a slight delay while opening, it doesn't open instantaneously (but this is a minor detail).
RAM and CPU of course, also are higher than older STG' versions.

If we test with other add-ons... STG' issues get worse.
The same happens when we test STG with different FF' preferences (FPI, containers, content blocking etc, normally cause issues on STG).
It's important to mention that after weeks of STG' use, Firefox storage and json files are huge, it seems that endless data keeps accumulating without sanitation (this might be one of the causes of corrupted data).

The rest of the STG add-on works perfect (and by that I mean that most of the STG' add-on works fine, and the issues we saw are annoying but never catastrophic).

I apologize because I can't tell you the causes of the issues. I'm not an expert. The best I can do is to report you what I see. 

Now, please allow me a personal comment:
We (150 users) have been using STG for a while now. In our opinion it's still the best tab group add-on. And we plan to keep using it.
However, after months of testing different tab-group-add-ons (TGAD), our conclusion is that "bookmarking/closing" tabs is better than "hiding/discarding". It is better in terms of less add-ons conflicts, less Firefox' functions conflicts, less browser negative performance impact, less privacy issues, less security issues etc.

I perfectly understand if some users will prefer "hiding/discarding" tabs. So please, keep present STG as it is now.
I just invite you to create a STG' fork, but using "bookmarking/closing" tabs instead of "hiding/discarding". My guess is that most of the existent issues will be mitigated. It is common-sense: "A closed tab always is better than a hidden/discarded tab, in the sense that a closed tab is dead, it creates zero issues".
I can confirm that on add-ons using "bookmarking/closing" tabs, they have almost zero issues compared to add-ons using "hiding/discarding". Sadly we can't use these add-ons, because they are too basic, primitive in terms of options. Just in case you want to take a look, here is a good model: https://addons.mozilla.org/en-US/firefox/addon/tab-group-switch/
You'll see that this add-on has less conflicts, better browser performance, but sadly is unusable because it mess up with user-tab-order, and it lacks options/functions, it is too basic.

Thank you!

**Comment by Drive4ik** [comment]
Hi @EstherMoellman !
Thank you very much and the whole team for the work done!

> Also, STG' popup (navbar icon) seems more snappy/slow than previous versions, it has a slight delay while opening, it doesn't open instantaneously (but this is a minor detail).
RAM and CPU of course, also are higher than older STG' versions.

The delay occurs because every time you open a popup window, all the tabs of all windows and their session data are read to find out which tab belongs to which group.

I experimented with the latest Nightly version, and I can say the following: I not only repeated those problems that I hadn’t had before, I just found a bunch of new ones! But then, looking at the logs, I realized that the code works as it should, but the Firefox API doesn’t. For example: the browser.tabs.hide([...]) function is called, but it does absolutely nothing, I don’t even know what it depends on. There are no errors, it just does not hide the tabs and returns the result that it did nothing.
Since your group specifically uses only the Nightly version, maybe this is related to work, I can only advise you to wait until a new version is released and these errors go away. 
There are no such errors on the stable and beta versions.
Firefox Nightly is very unstable, once again I'm convinced of it...

Regarding the creation of a parallel version without hiding tabs, I will not do this, since it was much more complicated and had many unobvious bugs that led to data loss.

**Comment by EstherMoellman** [comment]
@Drive4ik , thanks for your comment. My replay to you:

1) Yeah, I'm already aware that most of the bugs, are not necessarily inherent to STG. I am not an expert and don't know the causes of the bugs. So, when I report something, always is considering the possibility that the bug may come from: a) Add-on b) Another add-on c) Browser

2) Nightly may present more issues than other FF' versions. But at the same time, Nightly may work for you as a way to anticipate issues you will see in the next 3 months. With all due respect, I disagree with you, Nightly is a pretty solid version, and most of the issues you see today in Nightly, you will see in the next 3 months in Beta or Stable' versions. After using Nightly for more than a year, I rarely saw an issue at Nightly that was solved for Beta/Stable. Sometimes people wrongly assume Nightly is "unstable", when in real-life Nightly is "experimental" (not unstable). Generally, what is wrong with Nightly, will be also wrong at Beta/Stable.

3) With regards to tab "bookmarking/closing" instead "hiding/discarding", let's be fair, both ways have lot of bugs at Bugzilla. "Hiding/Discarded" also have lot of bugs at Bugzilla. Choosing one way or the other, only based on reported bugs... is wrong! So, I don't ignore FF' bugs, but I choose "bookmarking/closing" because in real-life the existent add-ons with this function, they work better than add-ons like yours (STG) using "hiding/discarding".
The tab "bookmarking/closing" add-ons compared to your add-on STG, they are not better, but they have less conflicts (with other add-ons or with browsers), and they also have less negative browser performance impact (they use less RAM, less CPU, less SDD/HDD, less heat, less battery, less etc).

So, why I don't use these tab "bookmarking/closing" add-ons? Because they are too simplistic for me. That's the reason I'm still using your add-on STG, and I was forced to live with the issues/bugs.
My dreamed tab-group-add-on will be to have SimpleTabGroup, but using tab "bookmarking/closing" instead of "hiding/discarding". If by chance one day in the future you build this STG' fork, I'm sure it will be the ultimate winner one!

**Comment by Drive4ik** [comment]
@EstherMoellman Hi!
I created bug
https://bugzilla.mozilla.org/show_bug.cgi?id=1577480

This is due to your problem. I will wait for a decision.

**Comment by EstherMoellman** [comment]
@Drive4ik Hi and thank you!
As I said, I hope you will think about the possibility to make a STG' fork, based on "bookmarking/closing" tabs (instead of "hiding/discarding" tabs).
Again, please fell free to keep the present STG based on "hiding/discarding" tabs. I have nothing against it. I just invite you to think about a STG' fork, exactly the same STG, but just using "bookmarking/closing" tabs.

If you see the "tabs groups" add-ons at AMO, most of them use "bookmarking/closing" tabs, not "hiding/closing". And there are lot of good reasons for that:
1) Less conflicts with other add-ons
2) Less conflicts with Firefox' functions
3) Less negative browser performance (less RAM, CPU, SDD/HDD, heat, battery etc)
4) More privacy (tabs might be cleaned by closing them)
5) More security
6) More visibility to the add-on, because more articles are written about add-ons using "bookmarking/closing" tabs
7) Same or less number of Firefox' bugs than "hiding/discarding" tab add-ons
8) Etc

Please, think about it!
