### ISSUE TITLE
Tab forced into foreground when it plays a sound if it would be automatically moved to its current group

### ISSUE THREAD

**Issue by jackwickham** [Drive4ik/simple-tab-groups#435]
**Describe the bug**
If a tab is set to automatically move to a particular group, and is already in that group, but that group is in the background (a tab from a different group is in focus), then if that tab plays a sound that tab will be forced to the foreground.

**To Reproduce**
1. Configure a site that plays notification sounds to always move to a specific group, such as messenger.com
2. Visit that site, so that it is loaded in the group that it is meant to belong to
3. Switch to a different group and use firefox normally in that group
4. Receive a notification that triggers a sound
5. The tab and its corresponding group will be moved to the foreground, and the tab will be moved to be the last tab in the group. A notification is also shown saying that the tab was moved to that group, even though it was already there.

**Expected behavior**
The sound should play without forcing the tab or group into the foreground or triggering the tab's group to be updated.

**Desktop (please complete the following information):**
 - OS and version: Fedora 30 (Linux)
 - Firefox version: 68
 - Simple Tab Groups version: 4.0.0.2

**Comment by Drive4ik** [comment]
Yes, there is a similar bug, maybe I fixed it here bfb39472fbf575fb41343984d934c7d5868956dd. You need to wait for the next release and check again.

**Comment by jackwickham** [comment]
Sorry, I forgot to update this, I've not experienced it for the past few weeks, I think since I was updated to 4.0.1.2, so I think this is resolved now.
