### ISSUE TITLE
Welcome to Simple Tab Groups v4

### ISSUE THREAD

**Issue by MickCasanova** [Drive4ik/simple-tab-groups#436]
**Describe the bug**
"Welcome to Simple Tab Groups v4" opens up in a new tab every single time I open the browser. Is there any way to disable the page from constantly opening? It just gets annoying to have it open up every time I start. I don't see any option to turn it off though.

**To Reproduce**
Simply start Firefox

**Desktop (please complete the following information):**
 - OS and version: Windows 7 Pro.
 - Firefox version: 68.0.1
 - Simple Tab Groups version: 4.0.0.2

**Comment by AfroThundr3007730** [comment]
Indeed, it also constantly prompts me to enable "Restore previous session" as well:

![image](https://user-images.githubusercontent.com/7613032/62824465-eb102f00-bb8d-11e9-83e5-05a389761bc8.png)

This setting is, of course, already enabled.

I'm running the latest Firefox Nightly 2019-08-09 on Debian Testing x86_64 with STG 4.0.0.2.

**Comment by Drive4ik** [comment]
This message is shown once when the addon migrates from version 3 to version 4.
If you do nothing, the data from the backup is not restored, nothing is ordinary, but simply launch the browser - this tab is shown to you, you close it, then close the browser and open it - and again this tab, this means the add-on data is not saved. And this is strange.
Try to remove the addon, restart the browser, install the addon again, and restore the last backup. (P.S. if the backup version is <4 then this tab will appear once again)

**Comment by MickCasanova** [comment]
I followed the steps you recommended, and the screen is still popping up. No change.

**Comment by Drive4ik** [comment]
@MickCasanova Firefox does not restore addon data...  I have no idea why this happens.
Can I ask you to make a copy of your profile and send it to me? And with this copy of the profile, be sure to delete all history, passwords, cookies, bookmarks, cache, the download bar and group tabs, replace with any type
group 1: 3 tabs with google.com
group 2: 3 tabs with firefox.com
group 3: 3 tabs with github.com

**Comment by ani2life** [comment]
I have the same problem.
backup STG => remove STG => restart firefox => install STG => restore backup
I tried but didn't fix the problem.

macOS: 10.14.6
Firefox: 68.0.1
Simple Tab Groups: 4.0.1.1

**Comment by Drive4ik** [comment]
fix this bug in e4513d8bccc3ca01a69ace832245fc3cfe3fe799
