### ISSUE TITLE
Feature Request: To refresh/reload discarded/unloaded tabs

### ISSUE THREAD

**Issue by EstherMoellman** [Drive4ik/simple-tab-groups#437]
Please @Drive4ik , if possible, it will be nice if STG can refresh/reload discarded/unloaded tabs (when the user selects them again). The present STG' behavior is to load discarded tabs (when selected again). But for example, in sites like REDDIT, users must manually reload/refresh discarded tabs (if they want to see new posts, comments, new stuff etc). It will be nice if STG can do it automatically. Today I use this add-on (https://addons.mozilla.org/en-US/firefox/addon/update-discarded-tab-on-select/), but I would prefer to have this function in STG. 
Thank you!

**Comment by Drive4ik** [comment]
Hi, I understand your desire. If between these add-ons there are no conflicts in the work, then it is better to leave everything that way. Because then the whole meaning of the diversity of add-ons is lost. You can turn on some functionality, or you can turn it off. Yes, and if I make analogues of the existing functionality, then this addon will grow and become a monster))) The word `Simple` will have to be removed)

**Comment by Drive4ik** [comment]
Next release will have option "Reload tab" in tab context menu on popup.
Click on this item with pressed `Ctrl` (or `Command` on mac) will reload tab without cache.

**Comment by EstherMoellman** [comment]
@Drive4ik , thank you for your efforts... but I don't think this is a good idea. If the user want to manually reload a tab, you know, he can do it through the navbar, reload button, or simple by just selecting the url and pressing "enter" etc. I mean, another manual-reload-tab way... is totally unnecessary.

I disagree with your logic about add-ons diversity... this is simple not the case. Your logic applies to different functions (for example, if a user suggest STG to block ads). Different or weird requested functions, yeah, you're right! But if STG hides + discards tabs + loads tabs etc... then is totally part of STG' functions, to offer an option to automatically refresh loaded tabs (automatically reload discarded tabs when loaded). May I achieve this with another add-on? Sure! But again, this is not the case. The question here is if a new requested function will improve or not STG, regardless what other add-ons do. At least, this is my opinion.

If you decide to keep your decision and not adding the automatic-refresh-tab option, is fine, no problem, I still will love you! : )
