### ISSUE TITLE
STG Takes over Ctrl+Shift+L - Wordaround

### ISSUE THREAD

**Issue by esa1975** [Drive4ik/simple-tab-groups#439]
**Describe the bug**
I noticed that Bitwarden was no longer filling in forms using Ctrl+Shift+L. It took me a while to figure out what was going on but I finally noticed a dozen or so new "Group NN" entries (NN is the next number i.e. 10, 11, 12).

**To Reproduce**
1. Use the Ctrl+Shift+L key combination

**Expected behavior**
Ctrl+Shift+L is not captured by STG

**Desktop (please complete the following information):**
 - Reproduced on Windows 10 and Linux
 - Firefox version: 68.0.1 (64-bit)
 - Simple Tab Groups version: 4.0

**Additional context**
I was able to work around this issue by disabling, testing that Crtl+Shift+L worked in Bitwarden again (it did) and then enable STG again. I tested Bitwarden a second time and it was still working after re-enabling STG. Also, there were no new "Group NN" created.

I don't expect the developer to spend any meaningful time addressing this since the workaround is so simple. I just thought it would be helpful to post this in case anyone else runs into this issue and is trying to figure it out.

**Comment by Drive4ik** [comment]
Hi! To solve the problem right now reassign the add-on key to any other. In the next release I will remove the default values for STG.

https://support.mozilla.org/kb/manage-extension-shortcuts-firefox
