### ISSUE TITLE
Losing Tab contents

### ISSUE THREAD

**Issue by hopsGH** [Drive4ik/simple-tab-groups#442]
Updates in the last few weeks have been causing Tab group contents to be lost.
Havent quantified exact sequence to lose the contents.

Have a lot of Tab groups, a few that switch between all the time (others occasionally)
Running on Firefox Beta update channel and  in spite of reports of Tab Group content loss previously this has never happened to me until about 2 weeks ago ( maybe one update previous to the current
current 4.0,1.2 so maybe fm 4.0* change).
Current Firefox ver is 69.0b4 - have been on 69.0b for about that long so maybe related to that
Firefox version..

Shows as 
    a) switch away from a Tab group 
    b) when start to switch back the meni display shows only 1 (empty) Tab in group - rest gone
Have been managing this by restore from backup which loses any additions/changes since backup.

Suggestion - Loss has only been happening on single Tab group at a time
in lieu of this/these bugs fixed suggest providing a Tab group selective restore.
Current restore gives  restore of all TAB groups from full backup.
Suggest allow select a Backup file (as now "restore")
 add option to - do TABgp selective restore:
Display Tabgroups from that backup and restore (replace contents of) only the tabgroup selected. 

Thx

**Comment by EppyGA** [comment]
Have seen this myself. Today, opened a tab group (4 tabs) in a new window, all was good. Closed that window and then opened it again in a new window and the first three tabs were empty.
![Simple Tab Groups Screen Shot](https://user-images.githubusercontent.com/4790980/64445794-3f330400-d0a5-11e9-813e-71d5d1aeb0eb.PNG)

**Comment by Eagna** [comment]
I also have a problem with some groups losing all tabs. In my case it was the last 4 tab groups in the drop down list. All tabs in these 4 groups disappeared. As far as I am aware there were no crashes or updates since I last used these groups.

**Comment by Drive4ik** [comment]
Please retest this issue on latest STG v4.0.3
