### ISSUE TITLE
Moving multiple tabs to another group sometimes duplicates (does not hide) the last tab across groups

### ISSUE THREAD

**Issue by nekohayo** [Drive4ik/simple-tab-groups#443]
I don't recall noticing this bug until recently so maybe it's a regression somewhere, but if I select multiple tabs _using the Firefox top tab bar_, and then right-click one of the tabs in the group and select the last menu option, "Move tabs to group > " and move them to another group, sometimes one of the tabs remains in the current view. Yet:

* If I inspect the other (target) group in the TabGroups sidebar, I see that all the tabs have been sent there, so the tab remaining in the currently visible/active group is kind of duplicated...
* ...if I close that tab in the current group it gets closed in the other (target) group as well, suggesting it's somehow an issue with tab hiding?

This is the latest version of STG on Firefox 68.0.2.

**Comment by Drive4ik** [comment]
For a long time I could not repeat this problem, since many people wrote about it. But as soon as I repeated it, I created a bug in Firefox bugzilla.
We will wait for a solution to the problem.
https://bugzilla.mozilla.org/show_bug.cgi?id=1577480

**Comment by AltB** [comment]
Same problem or something close with FF70.0b3. When I move tab between groups, some tabs moves (notification) but remains at the end of the group. If you close FF or change group, the current group is stored with this 'moved' tabs at his end. It seems It's not systematic, but some tabs are moved other copied (duplicates).
It's very new but very very annoying, and I understand It's Mozilla bug

**Comment by AltB** [comment]
For me this bug is only with FF70.0b (It's exactly the bug 1577480). I revert to stable release 69 and the problem disappear.
