### ISSUE TITLE
Closing Last Tab in Group

### ISSUE THREAD

**Issue by valsamis-d** [Drive4ik/simple-tab-groups#444]
Hello,

I would greatly appreciate if the developers of this great add-on consider the following change/enhancement:

**Current Behavior**
I see this has already been discussed, but what I'm observing is not exactly the same #209 and #219. Closing the last tab of a group, say _GroupA_, automatically moves focus to the 1st tab of another group, and leaves _GroupA_ with 0 (zero) tabs. Note: the newly focused tab is unique among all open tabs in all groups.

**Describe the solution you'd like**
I believe it would make more sense to create a new tab when the last tab of a group is being closed and have focus remain on the same group. Complete removal of a group could be performed via the "Manage Groups" form.

**Describe alternatives you've considered**
Honestly, I haven't considered any other alternative or workaround. I'd be glad to hear if there are any.

NOTE: I'm using STG in Firefox Stable Channel.

Thank you
Dimitrios

**Comment by Drive4ik** [comment]
The fact is that the addon cannot prevent the user from closing the tab. Firefox window cannot be opened without tabs. And when the last visible tab closes, Firefox looks for hidden tabs and shows it. In my add-on, I can’t change this in any way, and I just show/load the group to which this tab belongs. It is also convenient if you write the name of a tab from another group in the url field, Firefox displays it and you choose to go to this tab - you go to this tab, and I immediately load the group to which this tab belongs.
Therefore, to do what you want, I will have to create a new tab, and switch the group back, it will all work very unstable .. and other errors are possible ..

**Comment by valsamis-d** [comment]
I see @Drive4ik :) Even though current behavior is irritating, I can understand that your hands are tied. Anyway, if I had to choose between this change and stability, I would definitely go with stability ;) Thanks for the response!
