### ISSUE TITLE
Make windows more identifiable

### ISSUE THREAD

**Issue by shtrom** [Drive4ik/simple-tab-groups#445]
**Is your feature request related to a problem? Please describe.**
With multiple browser windows, each with a distinct group, it quickly becomes tricky to find the right window with the right group in it.

**Describe the solution you'd like**

1. Simply, add the name of the group somewhere in the window title, so it shows up in various window-sorters (Alt+Tab, Exposé,...)
2. For extra goodness, maybe set the icon of the group to something that could be displayed as a property of the Window, for more visual identification (not sure if possible and/or cross-platform) [Gnome at least adds an icon on each window thumbnail, but it may just be the app's]

**Describe alternatives you've considered**
None that I could think of.

**Additional context**
Apart from the small icon in the top right of each window (thumdnailed), there is no way to tell what window contains which group.

![Screen Shot 2019-08-22 at 14 11 31](https://user-images.githubusercontent.com/160280/63485465-d6fdf300-c4e6-11e9-85cb-a9c4286b704b.png)

The title may help, there.

**Comment by Drive4ik** [comment]
Hi! Please go to the addon options and enable checkbox `Prepend group title to window title`.
Sorry, but Firefox no longer provides any ways to split windows visually.
