### ISSUE TITLE
Group icons get displayed with 1 second delay

### ISSUE THREAD

**Issue by kparal** [Drive4ik/simple-tab-groups#446]
**Describe the bug**
Every time I open the group list menu (`F2`), all groups icons **except the first one** are blank, and get loaded after about 1 second. It's quite distracting and it worked completely fine some weeks back (before version 4?). Thank you for looking into this.

**To Reproduce**
1. Create several tab groups
2. Click in the menu/press `F2`
3. See the icons being empty except the first one
4. Wait ~1 sec, see the icons loaded

**Expected behavior**
The icons should appear immediately, as it was the case a few weeks back

**Screenshots**
This is what I see immediately after showing the menu:
![stg1](https://user-images.githubusercontent.com/755451/63511603-e9296280-c4e1-11e9-9da6-79bba8d2ec91.png)

And the icons load after ~1 second:
![stg2](https://user-images.githubusercontent.com/755451/63511618-f3e3f780-c4e1-11e9-894d-90a5849bc5ee.png)

**Desktop (please complete the following information):**
 - OS and version: Fedora 30
 - Firefox version: 68.0.2
 - Simple Tab Groups version: 4.0.1.2

**Additional context**
Tested on two different computers (both with Fedora), behaves the same.

**Comment by Drive4ik** [comment]
Yes. Only this is not a bug but a feature :)
This is done to speed up window loading. Perhaps for groups I will remove this, but I will leave this functionality when displaying tabs, as this speeds up (20%-50%) loading and showing tabs if you have 200+ tabs

**Comment by kparal** [comment]
Thanks!
