### ISSUE TITLE
Keyboard shortcut to open the side bar disappeared and can't be set

### ISSUE THREAD

**Issue by kparal** [Drive4ik/simple-tab-groups#447]
**Describe the bug**
There used to be a keyboard shortcut `F1` to open the Firefox side bar with STG list. I used it a lot. The shortcut disappeared recently (with upgrade to version 4?). Now it seems I can't open the STG sidebar in any simple way - the shortcut is not configurable through STG preferences.

**To Reproduce**
1. Try to open STG sidebar just with your keyboard. Seems impossible at the moment.

**Expected behavior**
I can open STG sidebar with just a single keyboard action.

**Screenshots**
No keyboard shortcut is listed for STG, as opposed to other content.
![stg](https://user-images.githubusercontent.com/755451/63512223-92bd2380-c4e3-11e9-9a18-5e80f547c92e.png)

**Desktop (please complete the following information):**
 - OS and version: Fedora 30
 - Firefox version: 68.0.2
 - Simple Tab Groups version: 4.0.1.2

**Additional context**
 Tested on two different computers (both with Fedora), behaves the same.

**Comment by Drive4ik** [comment]
Hi. Now you can change keyboard shortcuts here:
![Screenshot_3](https://user-images.githubusercontent.com/7843031/64031144-80c92980-cb50-11e9-94eb-dc5cf7c825ca.png)
![Screenshot_4](https://user-images.githubusercontent.com/7843031/64031149-8292ed00-cb50-11e9-8a20-395b5b0247b1.png)

**Comment by kparal** [comment]
Oh wow, I had no idea. It works! I think the confusing thing is that you can configure the shortcuts in two different places, and opening the sidebar is probably the only action missing from the shortcut list inside STG preferences (but it's present in global shortcuts configuration, as shown above).

**Comment by Drive4ik** [comment]
Yes that's right. I left the setting inside the addon because in the Firefox settings not all keys can be configured for actions.
