### ISSUE TITLE
Auto backup to a hidden folder doesn't work

### ISSUE THREAD

**Issue by kparal** [Drive4ik/simple-tab-groups#449]
**Describe the bug**
I use the auto backup feature into a folder, it's great. It only allows to select a folder that's inside the Downloads folder, I assume it's a limitation of Firefox (is that correct?). However, I'd still prefer to have the backup folder somehow hidden from plain sight, so that I don't look at it every time I open the Downloads folder, or accidentally delete it. So instead of using `STG-backups` folder, I typed in `.STG-backups` (every file/dir starting with a dot is hidden on Linux). However, it seems that selecting a hidden folder is simply not working - no backup files are every created in there. Also, if I hit `Open backup folder` button, it shows up a notification `What's wrong...` and doesn't open the folder. If I select `STG-backups` (without the dot), both auto backup and the button work fine.

Is this also a limitation of Firefox, or is this a bug in STG that might be fixed?
I'd really appreciate it, thank you.

**To Reproduce**
1. Go to STG preferences (on Linux)
2. Enable auto-backup to a folder and type in an existing folder name starting with a dot (e.g. `.STG-backups`)
3. Select the backup interval to 1 hour
4. Check in a few hours, no backups were performed
5. Repeat with a folder which doesn't start with a dot, everything works fine then

**Expected behavior**
I can back up to a hidden folder (starting with a dot).

**Desktop (please complete the following information):**
 - OS and version: Fedora 30
 - Firefox version: 68.0.2
 - Simple Tab Groups version: 4.0.1.2

**Additional context**
 Tested on two different computers (both with Fedora), behaves the same.

**Comment by C-Meinert** [comment]
I was able to reproduce the issue and, at least in my case, it cared less about if a folder was "hidden" or not and more so about the folder starting with a period. I also tested with folder name that contain a period (eg `STG.Test`) and that worked as expected.

Setup
- Firefox 70a1
- Windows 10
- STG 4.0.1.2

Output from STG Error JSON
`{
    "version": "4.0.1.2",
    "logs": [
        {
            "date": "8/23/2019, 10:24:38 PM",
            "message": "filename must not contain illegal characters",
            "lineNumber": 0,
            "stack": [
                "Async*",
                "options/options.js:1:970 -> n",
                "options/options.js:1:110",
                "options/options.js:7:126241 -> n",
                "options/options.js:1:110",
                "options/options.js:1:902",
                "options/options.js:1:912"
            ]
        }
    ]
}`

**Comment by Drive4ik** [comment]
Fixed, please wait next small release. It will be soon)

**Comment by kparal** [comment]
I have now version v4.0.3 which says it fixes this bug. However, if I input `.STG-backups` into `Folder name` in settings, I go back up to the Addons Manager, and then back into STG settings, the `Folder name` is changed to `STG-backups`. In other words, the starting dot is never saved, and so I can't use such a hidden directory.

**Comment by Drive4ik** [comment]
@kparal All right. Because it causes a browser error. Therefore, I delete all unsupported characters or phrases.

**Comment by kparal** [comment]
So it will not be possible to back up to folders starting with a dot?

**Comment by Drive4ik** [comment]
Yes
