### ISSUE TITLE
Opening browser using a link (from a different app) hides the new tab into "other tabs"

### ISSUE THREAD

**Issue by kparal** [Drive4ik/simple-tab-groups#450]
**Describe the bug**
If Firefox is already open, I can click a link in a different application (e.g. the terminal) and the new tab with the link loads up just fine in my current group. However, if Firefox is closed, and this action starts the browser, the tab with the link is **not displayed**. Instead, the tab is moved into `Show other tabs` section in STG menu with description `Found hidden unsynchronized tabs`. Not many people will find it there, though.

**To Reproduce**
1. Close the browser
2. Open the browser from a different application using a link (e.g. in terminal hover over an URL and select Open Link)
3. See the browser started and the new tab immediately hiding itself. The browser only shows your existing group in the same state that it was when you last closed the browser, but not the new tab.
4. Find the new tab in `Show other tabs` in STG menu

**Expected behavior**
The new tab with the selected link should be opened as part of the existing tab group.

**Desktop (please complete the following information):**
 - OS and version: Fedora 30
 - Firefox version: 68.0.2
 - Simple Tab Groups version: 4.0.1.2

**Comment by midgleyc** [comment]
This is also the case for tabs sent from a different device.

One solution might be to add a setting to always force unsynchronized tabs into the main group, because that's pretty much what I always want to do.

**Comment by Drive4ik** [comment]
@kparal Fixed. Please wait next release

@midgleyc I tested your solution, but can't replicate you bug. Try retest on next release.

**Comment by Acru** [comment]
Note: This issue is still occurring often in v4.2.2, and it seems to happen more so with links that are fast to load like links to images, or just opening a new tab too soon.

**Comment by Drive4ik** [comment]
@Acru I try to fix your issue, please retest it on next STG release. Thanks.

**Comment by Acru** [comment]
Just an update, still occurring as of 4.3.6.2

**Comment by Drive4ik** [comment]
@Acru Hi!
I checked what you are saying, and it turns out that as many browser instances are launched in linux as there are links. And in windows, one window is launched, and all links, let them be 20 pieces, are passed in one parameter.
I don’t even know what to think, how to fix this problem .. Most likely I won’t be able to fix it.
I recorded a video (gif) how it works on windows and how on linux (long video):

https://send.firefox.com/download/720a4fabe3d27d9e/#HT1SuWhGx3JBSFm8TB_aKw

**Comment by kparal** [comment]
The original issue is resolved for me. If I open a new link e.g. from gnome-terminal, it starts Firefox and the new tab is displayed correctly in the currently active tab group. I haven't tried interacting with URL links as in the GIF above, but latest Nautilus removed support for URL links anyways (so this now only affects certain distributions/desktop environments, in vanilla GNOME you can't do it).

**Comment by Drive4ik** [comment]
Yes you are right. I'm not omnipotent)
