### ISSUE TITLE
Notification asking to click to show tab appears when "show tab after auto-moving option" is set

### ISSUE THREAD

**Issue by nunocastromartins** [Drive4ik/simple-tab-groups#452]
When the option "show the tab after auto-moving it into this group" is set for a group, I believe that a notification should **not** appear asking the user to "click here to show the tab" since the tab is already being shown.

**Desktop:**
 - OS and version: Linux 5.2.9
 - Firefox version: 68.0.2
 - Simple Tab Groups version: 4.0.1.2

**Comment by Drive4ik** [comment]
Yes you are right.
