### ISSUE TITLE
Matching URLs exactly when catching tabs

### ISSUE THREAD

**Issue by nunocastromartins** [Drive4ik/simple-tab-groups#453]
I don't know if this is already supported, if so I haven't figured out how.

I wish to match a URL exactly, as an example consider:
```
https://www\.reddit\.com
```
I expect the RegExp to match: `https://www.reddit.com` but not `https://www.reddit.com/r/firefox`.

I tried:
```
^https://www\.reddit\.com$
```
but it doesn't seem to work.

Is this currently supported? What RegExp format is currently being used?

**Comment by Drive4ik** [comment]
Hi, try this `^https://www\.reddit\.com/?$`

**Comment by nunocastromartins** [comment]
I could swear I tried that! Thanks, it works.
Seems like the browser (at least Firefox) adds and then removes the forward slash even if you type the URL without it.
