### ISSUE TITLE
Youtube tabs show up in all groups [Firefox 70 beta]

### ISSUE THREAD

**Issue by dgutov** [Drive4ik/simple-tab-groups#454]
Just visit YouTube in a tab, start the video, and it will show up as one of the open tabs no matter what group you switch to. When I close the tab, it disappears from all groups.

(Whereas, when I view the lists via the popup, it's just in one of them).

**Desktop (please complete the following information):**
 - OS and version: Ubuntu 19.04
 - Firefox version: 70.0b1 (64-bit)
 - Simple Tab Groups version: 4.0.1.2

**Comment by Drive4ik** [comment]
For a long time I could not repeat this problem, since many people wrote about it. But as soon as I repeated it, I created a bug in Firefox bugzilla.
We will wait for a solution to the problem.
https://bugzilla.mozilla.org/show_bug.cgi?id=1577480

**Comment by GIS1980** [comment]
I've been seeing this problem for a month or so, aways on the same two urls (not youtube related).
I'm on the latest Nightly.  Good to know it's a firefox issue.

**Comment by Drive4ik** [comment]
There was no this problem before. Apparently optimized the code and missed something.

**Comment by Ezneh** [comment]
Also to be noted that this behavior happens as well with gmail tab. It might then be related to all google products but has to be verified.

**Comment by dgutov** [comment]
> For a long time I could not repeat this problem

Eh, I also have "Enhancer for YouTube" installed, and I forgot about it.

So my first guess was that the problem tabs are somehow special ones (like the ones that are playing audio). But I stopped short of verifying this.

**Comment by dgutov** [comment]
I'm also seeing this with gog.com tabs. :hushed:

With no video playback or anything.

**Comment by CamJN** [comment]
This also happens with discordapp.com tabs.

**Comment by LukBukkit** [comment]
This Firefox bug should now be fixed (at least for Firefox 71):
https://bugzilla.mozilla.org/show_bug.cgi?id=1577480#c15

I guess we'll have to wait a little bit until it gets backported to all Firefox 70 editions.

**Comment by dgutov** [comment]
Fixed in Firefox 70 now as well.

Thanks all!
