### ISSUE TITLE
Closing tab (not the last tab) switches group

### ISSUE THREAD

**Issue by victoriastuart** [Drive4ik/simple-tab-groups#455]
Firefox 68.0.  Apologies in advance if this question / "Issue" has already posed.

Very often when I am in a tab group and I close a tab (***not*** the last tab in that group -- i.e., I don't believe that this Issue is this is related to Issues https://github.com/Drive4ik/simple-tab-groups/issues/209 | https://github.com/Drive4ik/simple-tab-groups/issues/289 | ...), STG switches to another tab group.

It's annoying and worse, I often forget which group I was working in (I have many groups with many tabs in each).

Here's a list of installed FireFox add-ons.

![screenshot-2019-08-28](https://user-images.githubusercontent.com/2575920/63878029-95a19380-c97d-11e9-8049-5c50562430a6.png)

Here are my STG:

![screenshot-2019-08-28(001)](https://user-images.githubusercontent.com/2575920/63878277-22e4e800-c97e-11e9-86e3-6430f70ce0c4.png)

... and here are my STG preferences:

![screenshot-2019-08-28(002)](https://user-images.githubusercontent.com/2575920/63880765-3050a100-c983-11e9-9176-aa75c8f8a02b.png)

**Comment by Drive4ik** [comment]
Hi! There was no such bug before.
Please, try it and write here if the error is repeated
![Screenshot_2](https://user-images.githubusercontent.com/7843031/64019661-756a0400-cb38-11e9-92e0-0e1897b764c2.png)

**Comment by victoriastuart** [comment]
Thank you @Drive4ik -- although I only very recently (a few days ago -- this week) installed `Tree Style Tab`, I think that the `TST` setting that you indicate in your screenshot (above) may resolve the `Simple Tab Groups` issue!  :smile:   It was not selected, and when I selected it, it seemed to help re: this STG issue.  :+1: 

That is, the combination of the two add-ons with those preferences -- appears to be 'needed.'

I wonder: is the `TST` add-on setting indicated in your screenshot, above, changing a Firefox `about:config` setting?  I looked there previously in regard to this issue, and I did not find anything obviously relevant, except (perhaps) the legacy/residual old `tabmix` (`TabMixPlus`) entry.

![screenshot-2019-08-30](https://user-images.githubusercontent.com/2575920/64039900-9fa7cb80-cb10-11e9-91e6-163d6a5fa1f6.png)

BTW, I really like this add-on (`STG`) -- really fabulous and very useful to me.  Very intelligently implemented! Thank you,again, for responding to this issue!  :+1:

**Comment by Drive4ik** [comment]
Thanks!)
`Tab Open / Close Control` addon had problems with my addon in the past and more than once.
People wrote that when it was turned off, the problems in the STG disappeared.
This add-on does not take into account the tab option `hidden` since it has been done for a long time and at that time there was no this functionality in Firefox.
`Tab Open / Close Control` addon page:
> Last updated
> 2 years ago (Oct 27, 2017)


> I wonder: is the TST add-on setting indicated in your screenshot, above, changing a Firefox about:config setting? 

It seems that more addons can not change `about:config` page settings.
Now all add-on settings are stored elsewhere. At first it was a json file, now it is Indexed DB.

**Comment by victoriastuart** [comment]
Good to know (re: `Tab Open / Close Control`).  :wink:   Thank you -- I'll uninstall it, and see if that helps.  :smile:

**Comment by victoriastuart** [comment]
**Update:** after a couple of days with the `Tree Style Tab` setting referenced above by @Drive4ik and each of the following add-ons disabled, `Simple Tab Groups` appears to be working fine, re: this "issue" ([#455](https://github.com/Drive4ik/simple-tab-groups/issues/455)).  :grin: 

* Focus On Left Tab After Closing (disabled)
* Tab Control (disabled)
* Tab Open/Close Control (disabled)
