### ISSUE TITLE
Backup files are broken and unusable

### ISSUE THREAD

**Issue by kssi** [Drive4ik/simple-tab-groups#456]
**Describe the bug**

For some reason my unloaded tabs which are part of an active group/window are backed-up with an "about:blank" _url_ and empty _session_ value. This makes the backup files broken and unusable.

STG became totally unreliable since the 4.0 update, and now I realize I cannot even trust the automatic backup feature...

**To Reproduce**

Despite my attempts to understand what's going on, I have no idea why this happens nor how to reproduce this behavior on purpose.

**Screenshots**

Broken backup file:

![Broken backup file](https://i.imgur.com/FfCTRtl.png)

Tabs URLs & favicons also appear to be lost* ** in the STG menu (only for grayed out/unloaded tabs):

![Tabs URLs also appear to be lost in the STG menu (only for grayed out/unloaded tabs)](https://i.imgur.com/JCc1zrL.png)

\* Clicking on any of these tabs seems to load it properly (not sure what would happen if I first closed and reopened the Firefox instance).

\*\* Only occurs on some groups.

**Desktop**

 - OS and version: macOS El Capitan 10.11.6
 - Firefox version: 68.0.2 (64-bit)
 - Simple Tab Groups version: 4.0.1.2

**Additional context**

This is my current STG configuration:

```
"lastCreatedGroupPosition": 60,
"discardTabsAfterHide": true,
"closePopupAfterChangeGroup": true,
"openGroupAfterChange": true,
"prependGroupTitleToWindowTitle": false,
"createNewGroupWhenOpenNewWindow": false,
"showNotificationAfterMoveTab": false,
"openManageGroupsInTab": true,
"showConfirmDialogBeforeGroupDelete": true,
"showNotificationAfterGroupDelete": false,
"showContextMenuOnTabs": true,
"showContextMenuOnLinks": true,
"exportGroupToMainBookmarkFolder": true,
"defaultBookmarksParent": "toolbar_____",
"defaultGroupIconViewType": "old-tab-groups",
"defaultGroupIconColor": "#000000",
"autoBackupEnable": true,
"autoBackupLastBackupTimeStamp": 1567086103,
"autoBackupIntervalKey": "hours",
"autoBackupIntervalValue": 1,
"autoBackupIncludeTabThumbnails": true,
"autoBackupIncludeTabFavIcons": true,
"autoBackupGroupsToBookmarks": true,
"autoBackupGroupsToFile": true,
"autoBackupFolderName": "STG-backups",
"autoBackupBookmarksFolderName": "STG bookmarks",
"enableDarkTheme": false
```

**Comment by Drive4ik** [comment]
Yes, there are already reports of such a problem. Only here it is not an addon, but the fact that Firefox for some reason makes the url empty for NOT loaded tabs (discard tabs). That is, if the tab is selected by clicking on it, then it will display a url. And the automatic copy function, when executed, scans all tabs, the browser API `browser.tabs.query()`, and saves everything that is.
It might be necessary to create a bug in bugzilla...

**Comment by kssi** [comment]
Drive4ik,

Thank you for your comment.

How can all STG users possibly NOT lose some or more of their tabs on a regular basis with such a critical issue?

Why did I never encounter this problem prior to version 4.x.x.x?

**Comment by eetievent** [comment]
Looks the same problem than #451 , #448 and #442
It began with Firefox 68.0.2 (August 14)

**Comment by kssi** [comment]
Also #382 from April 26 (on Firefox 67.0b14)

**Comment by kssi** [comment]
Also #382 on Firefox 67.0b14 (April 26)
