### ISSUE TITLE
Side bar doesn't reflect correct tab position

### ISSUE THREAD

**Issue by kparal** [Drive4ik/simple-tab-groups#457]
**Describe the bug**
The STG side bar often doesn't show the real tab position (as presented by Firefox tab bar). This mainly happens when you open a link by middle-clicking (that opens it next to the current tab, and not as the last tab), or when you re-arrange your tabs by drag&drop. The side bar is only updated when you close it and re-open it, it doesn't update automatically. This used to work well not long ago, so it's a recent regression.

**To Reproduce**
1. Open STG side bar
2. Activate a tab that's not the rightmost one
3. Open some links by middle-clicking (or right click->open in a new tab)
4. Drag&drop tabs around
5. See tab positions not matching in STG side bar
6. Close and reopen STG side bar, see the tab positions corrected

**Expected behavior**
The tab position in STG sidebar should match Firefox's tab position in the tab bar

**Screenshots**
Here's a video:
https://youtu.be/-7JFnrZNC9s

**Desktop (please complete the following information):**
 - OS and version: Fedora 30
 - Firefox version: 68.0.2
 - Simple Tab Groups version: 4.0.1.2

**Comment by Drive4ik** [comment]
Fixed, please wait next release
