### ISSUE TITLE
pinned manage groups tab not in dark mode on initial load

### ISSUE THREAD

**Issue by iheinrich** [Drive4ik/simple-tab-groups#458]
**Describe the bug**
My workflow is based on a pinned tab of the manage groups page. Dark mode is enabled and working. After starting Firefox then switching to the managed groups pinned tab for the first time it always shows in "light" mode.
Reloading the tab always and consistently switches to dark mode for the remainder of the Firefox session.

**To Reproduce**
1. Configure Simple Tab Groups to 'dark mode'
2. Open 'Manage Groups' in a new tab
3. Pin the tab
4. Close Firefox
5. Open Firefox
6. Switch to pinned 'Manage Groups' tab. See dark mode styles have not been applied.
--
7. To fix: reload pinned 'Manage Groups' tab. Dark mode styles are applied now.

**Expected behavior**
Pinned manage groups tab initially in dark mode without need to reload.

**Desktop (please complete the following information):**
 - OS and version: Debian sid/unstable
 - Firefox version: 68.0.2 (64-bit)
 - Simple Tab Groups version: 4.0.1.2

**Additional context**
This is a cosmetic/low priority issue. It is not affecting the great usefulness of STG in any way.

**Comment by klint** [comment]
Same here with FF69
