### ISSUE TITLE
"Understand" tab groups session layout

### ISSUE THREAD

**Issue by mirh** [Drive4ik/simple-tab-groups#46]
When you install simple tab groups it throws everything under a single group, no matter whichever distinction you may have had with [original] tab groups. 
IIRC [conex](https://github.com/kesselborn/conex) has no troubles mapping everything to its internal representation. 

This is also a problem when importing backups, given that it basically duplicates every tab, no matter if they are the same ones I have already open.

**Comment by Drive4ik** [comment]
Can you retest this issue with this addon?
https://addons.mozilla.org/firefox/addon/experimental-simple-tab-groups/
