### ISSUE TITLE
Ctrl + W on pinned tab should select first non-pinned tab of current group rather than switch to first group

### ISSUE THREAD

**Issue by SebastianSimon** [Drive4ik/simple-tab-groups#462]
When you press `Ctrl` + `W` on a pinned tab in Firefox, the tab doesn’t close, but rather selects the first non-pinned tab. I like this behavior; it provides a quick and convenient way of switching to the first tab that isn’t pinned.

However, in recent versions of this extensions, the first tab _in the first group_ is selected, causing the group to change, if any other group is active. In older versions, just the first tab in the _current_ group got selected.

Can we have this older behavior back?

**Comment by Drive4ik** [comment]
Hey. I don’t quite understand what you’re saying. `Ctrl+W` should close the current tab, and not switch to the first. 
Perhaps you mean switching to the parent tab? There are various add-ons in which you can configure this behavior, but they conflict with STG.

**Comment by SebastianSimon** [comment]
> `Ctrl+W` should close the current tab, and not switch to the first.

Not on pinned tabs.

**Comment by Drive4ik** [comment]
Interestingly, I did not know about this behavior. This is because Firefox selects the first tab despite its visibility status. Unfortunately, I can’t fix this. Need to create a bug in bugzilla for this issue.

**Comment by SebastianSimon** [comment]
Okay, that’s interesting. We should probably wait for https://bugzilla.mozilla.org/show_bug.cgi?id=1577480 to be resolved. Maybe this issue directly influences the different behavior.

**Comment by Drive4ik** [comment]
Hey. No, most likely this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1577480 is not related to your problem. Your problem is most likely connected with a banal flaw. Need to search for a bug in bugzilla.Maybe it is already created. If not, you can create it, and it will be examined within a few days and it will go to the next browser release.
