### ISSUE TITLE
Override apperance with custom CSS

### ISSUE THREAD

**Issue by ww7** [Drive4ik/simple-tab-groups#463]
Please add option in STG preferences for setting custom CSS

**Comment by Drive4ik** [comment]
Hi! Why do you need this? Don't you like the look of the addon?

**Comment by ww7** [comment]
Hi, sidebar pane looks great, but I have issues with 13" screen. 
I want more responsive, more narrow it, now controls is outside of view.

**Comment by Drive4ik** [comment]
Hi, can you make screenshot? Maybe it is bug.

**Comment by ww7** [comment]
Вообщем не существенно. Но если резонно, сделай пожалуйста минимальную ширину меньше. Кнопки закритыя вкладок и разворацивания груры убегают за край сайдбара.

**Comment by ww7** [comment]
![](https://i.imgur.com/wljZE3D.png)
![](https://i.imgur.com/EMWD3bl.png)

**Comment by Drive4ik** [comment]
Хорошо, сделаю. Не думал что кто-то будет использовать на такой маленькой ширине. Неудобно ведь, мало текста влазит. Но если экран 13 дюймов, тогда понятно)

**Comment by ww7** [comment]
Спасибо. Я после того как нашел аддон и закрыл/разложил по группам свои милионы вкладок (тогда юзал сайдбар и открыл это ишью) то после уже сайдбаром как то и не пользовался. И милиона вкладок теперь нету, все как то организовано и тематично стало.
Чудо а не аддон :))) Супер клас

А, еще не хватало кнопки в дроп даун меню для закрытия всех выделенных владок, дискард и перенос в другую группу есть, а закрать  - нету.

**Comment by ww7** [comment]
Сразу отпишу про баг, или коллизию с другими екстеншенами:
иногда как бы фризится таб и отображается во всех группах

**Comment by Drive4ik** [comment]
Ок, сделаю. Сам тоже хотел, руки не доходили.
Да, есть такой баг. Только это не баг аддона а баг браузера. Почитай #443. Я там создал баг Firefox, и его вроде как пофиксили. Нужно ждать релиза.
