### ISSUE TITLE
Tab Group tabs

### ISSUE THREAD

**Issue by rihadik** [Drive4ik/simple-tab-groups#464]
Can you add another row of tabs for switching between existing tab groups, just like in the original Tab Groups Manager?

**Comment by Drive4ik** [comment]
Can you take a screenshot explaining exactly what you want? I don’t quite understand.

**Comment by rihadik** [comment]
Sure. See the above row? It's TabGroupsManager showing the number of tabs inside parens. The reason I'm still with FF 52.x is that I haven't found a anything similar.

![image](https://user-images.githubusercontent.com/4375281/64980772-9b7afc80-d8cb-11e9-8b62-9dfc83793e63.png)

**Comment by Drive4ik** [comment]
Hey. Now I understand what you're talking about. But I have to upset you ... Firefox Webextensions API does not support such magic as the old Firefox... This is done, including for security reasons, as well as maintaining the general appearance of the UI.
But I can offer a couple of solutions if you want.
Multiline tabs can be done using `userChrome.css`
And switch between groups using the STG function by hotkey:
![изображение](https://user-images.githubusercontent.com/7843031/65034062-f7d33000-d94e-11e9-9f57-d4029aad9be4.png)
