### ISSUE TITLE
preferences dark mode support

### ISSUE THREAD

**Issue by 532910** [Drive4ik/simple-tab-groups#465]
![image](https://user-images.githubusercontent.com/14617699/64498006-f0f74e00-d2ba-11e9-849e-90741c4e7b31.png)

**Comment by Drive4ik** [comment]
Nope, it doesn’t work ...
![Screenshot_1](https://user-images.githubusercontent.com/7843031/64847261-4c0ca600-d617-11e9-8987-9ce89cf84978.png)
![Screenshot_2](https://user-images.githubusercontent.com/7843031/64847263-4c0ca600-d617-11e9-8453-5f368bc0b083.png)
![Screenshot_3](https://user-images.githubusercontent.com/7843031/64847264-4c0ca600-d617-11e9-8283-f8540524648d.png)

**Comment by 532910** [comment]
Try to restart Firefox.

**Comment by Drive4ik** [comment]
Did not help.
It is necessary to include a dark theme in windows
![Screenshot_4](https://user-images.githubusercontent.com/7843031/64848857-d276b700-d61a-11e9-8a1f-51295e4fcb1c.png)
:)

**Comment by Drive4ik** [comment]
Only then begins to work

**Comment by Drive4ik** [comment]
please, wait next release :)
![изображение](https://user-images.githubusercontent.com/7843031/64856507-cdb9ff00-d62a-11e9-8c81-562f9e32a6bb.png)
