### ISSUE TITLE
Page appears in all groups.

### ISSUE THREAD

**Issue by kapitainsky** [Drive4ik/simple-tab-groups#466]
Love it and usually works great until now. Suddenly I have a page I added to one of the groups but this page appears in all other groups. I can remove it manually but than it is enough when I open it again in whatever group is is back again in all groups. It is is simple all or nothing situation:) Annoying and would love to get rid of this issue.

**Comment by kapitainsky** [comment]
Also what I noticed that this "stucked" page is only shown in actually open group - when I e.g. create two new groups with one tab each and in either I open offending page when I am in the group it shows in add-on tabs count - 2 tabs. Not active group shows 1 tab. When I switch group situation reverses. Active group has 2 tabs - other only 1.

**Comment by kapitainsky** [comment]
As I was playing with this annoyance it happens that I found the way to fix it. As this page behaved like "pinned" one but just without usual moving it to other pinned pages I pinned it properly, unpinned and now all behaves like it should. Might be useful if it happens to others. Not sure if issue was with add-on or firefox 'pin tab' functionality.

**Comment by sezar-gantous** [comment]
I have created an account and left a comment.

**Comment by kapitainsky** [comment]
with Mozilla bug [1577480](https://bugzilla.mozilla.org/show_bug.cgi?id=1577480)  fixed and deployed in the latest Firefox 70.0b9 the issues seems to be solved. I can report that problematic tabs are no problem any more for me.

**Comment by sezar-gantous** [comment]
Yup seem to be fixed.
