### ISSUE TITLE
Hotkeys for cycling between groups don't work very nicely with multiple windows.

### ISSUE THREAD

**Issue by notJerl** [Drive4ik/simple-tab-groups#469]
**Describe the bug**
If you have many groups (I have 7) and multiple windows (I usually have 4, but sometimes open a fifth or sixth), the hotkeys for cycling between groups don't work very nicely.  Specifically, if the next group is open in another window, it focuses that window.  If you Alt+Tab back to the other window and try again, it'll keep just sending you to the other window.  If you have a third window with another group open, the result is that **you cannot use the hotkeys to access any groups between the other two windows within the first window**.  No matter what you do, the only way to access those groups with keyboard shortcuts is in the other windows, which in my case are on completely different screens. 

**To Reproduce**
1. Have at least 3 windows open with groups selected in them.
2. Have several groups that aren't selected in a window.
3. Attempt to cycle through to a specific group in a specific window using keyboard shortcuts.

**Expected behavior**
There should be *some* way to use the keyboard shortcuts to cycle through all of the groups within one single window.  Perhaps it should skip groups that are already selected in a window (because you could just use Alt+Tab to switch to that window instead).

Another remedy would be to make it possible to set a hotkey to open the group switcher as if you'd clicked the STG button.  A hotkey for manage groups exists, but as far as I can tell it won't let you actually switch groups using only the keyboard.  The group switcher you get when you click the STG button already supports using the keyboard to select and switch to a group, but no way that I can find to pull it up using only the keyboard.

Ideally both of these would be implemented.

**Desktop (please complete the following information):**
 - OS and version: Windows 7
 - Firefox version: 69.0.1
 - Simple Tab Groups version: 4.0.6

**Additional context**
This forces me to use the mouse to click the STG icon, which interrupts my almost entirely keyboard-based workflow (I use Tridactyl to interact with webpages using only a keyboard).

**Comment by Drive4ik** [comment]
Hi! You can open addon settings and hotkey:
![Screenshot_3](https://user-images.githubusercontent.com/7843031/66672998-564ab000-ec68-11e9-9581-515de1ce83da.png)
![Screenshot_4](https://user-images.githubusercontent.com/7843031/66673050-711d2480-ec68-11e9-8f0c-c980505dc79f.png)

press saved hotkey and see this popup

![Screenshot_5](https://user-images.githubusercontent.com/7843031/66673053-737f7e80-ec68-11e9-9d8c-cb01104a2f10.png)

Does this option suit you?

**Comment by notJerl** [comment]
Being able to hotkey specific groups is a useful feature, but having to create and remember a hotkey for each group I make *and* ensure they don't conflict with any of Windows', Firefox's, Tridactyl's, or specific webpages' myriad hotkeys doesn't seem ideal.  I really do think having it skip groups that are open in a separate window would be ideal, since you can just use Windows-native Alt+Tab to get there.

Also, I just noticed that while the popup when you click the STG button will let you switch groups using the arrow keys or tab and enter, it rolls back up to the top once you hit the last group, making it impossible to create a new group, access ungrouped tabs, or get to the settings menu using only a keyboard. Due to an arm muscle injury, my situation is even worse than it was when I posted this; now it isn't that I don't use a mouse, but more that I *can't* use a mouse without massive pain, while I can use a keyboard with very little arm movement.  Please consider making keyboard navigation easier as an accessibility feature.

**Comment by notJerl** [comment]
I'm not sure why you'd need to do much with the browser, or anything with Alt+Tab, though.  Your add-on can *already* see which groups are already open in a window (the blue bar to the left of the group name in the popup when you click the STG button).  Just make it not cycle to groups already open.  You don't have to do anything to Alt+Tab; I was saying that the functionality is *already there* and you don't need to do anything for it.

**Comment by Drive4ik** [comment]
Do you want to use the keys to move to groups that are not yet open?

**Comment by Drive4ik** [comment]
Now it is clear) Done. Will available on next release.
Hotkey actions `Load next unloaded group` and `Load previous unloaded group`

**Comment by notJerl** [comment]
Thank you.

**Comment by Drive4ik** [comment]
@notJerl This functional is available in latest version v4.2
