### ISSUE TITLE
Discard tab delay

### ISSUE THREAD

**Issue by ww7** [Drive4ik/simple-tab-groups#471]
I suggest to add option to set custom timeout for tabs discard. 
Sometimes wrong tab switch, or searching something in other groups can discard important data. 
Also whitelist (not only pinned tabs).

**Comment by Drive4ik** [comment]
Hi.
> I suggest to add option to set custom timeout for tabs discard.

Already have add-ons with such functionality
https://addons.mozilla.org/en-US/firefox/addon/auto-tab-discard/?src=search

> Sometimes wrong tab switch, or searching something in other groups can discard important data.

In the group settings, turn on the checkbox "Don't discard tabs into this group after hide" and the tabs of this group will not be discarded

**Comment by ww7** [comment]
Yeah, sorry, I know about this. At my user experience is better way to control Discard manually.
My trouble is a touchpad (mouse not used). Than hover button appeared at every group would be cool. Also keyboard shortcut maybe better.

**Comment by Drive4ik** [comment]
Well, in the context menu of the tab and group there are unloading options. Or I don’t understand something.

**Comment by ww7** [comment]
Прошу прощения за неясный английский. На тачпаде сложно юзать контекстное меню.
Хоткеи было бы оптимально.

**Comment by Drive4ik** [comment]
Аа, понял) 
![изображение](https://user-images.githubusercontent.com/7843031/66584948-aa816180-eb8e-11e9-9e93-0e237a195990.png)
у аддона `Auto Tab Discard` есть горячии клавиши для выгрузки

**Comment by ww7** [comment]
Имею ввиду дискартить группы, мы же о simple-tab-groups)

**Comment by Drive4ik** [comment]
Вы писали про вкладки, вот я и про них) не хочу нагромождать аддон уже имеющимся функционалом из других аддонов.
Вы имеете ввиду нажимаешь кнопку - аддон предлагает группу которую выгрузить?

**Comment by ww7** [comment]
Да, этот ишью просто старый запрос, о ручной настройки задержки перед дискардом, в секундах (120 секунд например). Что бы можно было без постоянного релоада пройтись по группам когда стоит опция автоматический выгружать неактивные группы.

А отвечаю Вам про новый запрос, более актуальный, добавить хоткеи или всплывающие по наведению кнопки напротив группы: Дискард (эту группу) и Дискард азерс (все кроме этой)

**Comment by Drive4ik** [comment]
По поводу задержки выгрузки вкладок/группы я подумаю в будущем.
По поводу наведения курсора - это врядли.. но я сделал две новые опции в хоткеях: `Выгрузить группу` и `Выгрузить другие группы`. В `Выгрузить группу` можно не указывать конкретную группу и появится попап с группами и выделенной текущей группой.

**Comment by Drive4ik** [comment]
Можете протестировать на последней версии аддона

**Comment by ww7** [comment]
Круто.
