### ISSUE TITLE
Group focused mode

### ISSUE THREAD

**Issue by ww7** [Drive4ik/simple-tab-groups#472]
Maybe it's a point to have possibility change sidebar opened group to currently active group?

Имею ввиду, может опционально стоит и возможно ли внедрить функцию которая держит открытой активную группу в сайдбаре. Если вызывается другая группа или вкладка из другой группы, то переключать сайдбар в активную автоматом. А список груп уже отображать только при клике "Go back to groups" если режим "focused" активен

**Comment by Drive4ik** [comment]
Опцию "Следовать за загруженной группой (в боковом меню)" переместил в "Открыть группу после перехода на неё", будет в новой версии
