### ISSUE TITLE
Pop-up opens in 2 steps

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#473]
When clicking on the pop-up icon, the pop-up opens in 2 steps, visually speaking, first the half of it, then a couple of seconds later, the whole pop-up is displayed. See the 2 steps here:

![image](https://user-images.githubusercontent.com/218971/66551758-61a6ba00-eb48-11e9-8c3e-717949346601.png)

**Comment by Drive4ik** [comment]
I know this happens ... Firefox allocates little memory for this pop-up window, there are also quite a lot of bugs there (you can search at https://bugzilla.mozilla.org/)
It also depends on the amount of RAM in the computer and on the total number of tabs.

**Comment by Drive4ik** [comment]
Unfortunately, I can’t influence this behavior in any way ..
