### ISSUE TITLE
Load tabs shourtcut and button

### ISSUE THREAD

**Issue by ww7** [Drive4ik/simple-tab-groups#475]
When group loaded all tabs is unloaded.
I suggest to add functionality for load (refresh) all tabs in group.

Не знаю как лучше, но теряется время на каждой вкладке пока снова загрузиться. 
Может кнопку для загрузки всех вкладок возле шестеренки?
![](https://i.imgur.com/yDNi6Ud.png)

**Comment by Drive4ik** [comment]
Так есть уже такая кнопка в контекстном меню группы
![изображение](https://user-images.githubusercontent.com/7843031/66943891-bb314c00-f054-11e9-920d-d17d6a19ff8d.png)

Кстати, при её нажатии с зажатой кнопкой `Ctrl` или `Command` (на Mac) будет полная перезагрузка, без учета кеша браузера

**Comment by ww7** [comment]
О круто

**Comment by Drive4ik** [comment]
да)

**Comment by Drive4ik** [comment]
Ок, сделал..
