### ISSUE TITLE
Temporary/Ephemeral Container

### ISSUE THREAD

**Issue by EstherMoellman** [Drive4ik/simple-tab-groups#476]
Hi @Drive4ik !

I loved the new option (at Manager Groups) allowing to open tabs (always) in a defined container.

Please, a simple request: 
Add the option for Temporary/Ephemeral Container.
The general idea here is to allow the user the possibility to open tabs (in a defined Group) always in a different Temporary/Ephemeral Container.

As you know, Permanent Containers can include several tabs (sharing the permanent container). And when one of the tabs (inside a permanent container) is closed, the permanent container remains.
In the other hand, Temporary/Ephemeral Containers are deleted when tabs inside are closed.

Considering that you already included the option for opening tabs (always) in a permanent container, I suppose that now it will be easy for you to add the option for temporary/ephemeral containers... same function, just a different kind of container.

My request doesn't need fancy stuff.
I just request the option for Temporary/Ephemeral Containers.
That's all.

Personally I believe this should be a default function in Firefox, every tab should be opened as a Temporary/Ephemeral Container (until user determines a different behavior such opening in "no container" or "permanent container").
Unfortunately, today this is achieved only through add-ons.
In my opinion, your add-on took a giant positive step by including the option to opening tabs in containers. Fantastic! Congrats!
So, if now you add the variant for temporary/ephemeral instead permanent container... wowwww! this will elevate your add-on (even more) to a higher level.

Thanks in advance!

**Comment by GonzRon** [comment]
This is not a function that an extension can control, it would need to launch tab groups in private windows for the concept of an ephemeral container. This is functionality that would need to be built into or provided by the browaer itself.

**Comment by EstherMoellman** [comment]
nope, ephemeral container function doesn't need private mode / private window.

For example, these add-ons creates ephemeral containers in normal browsing:

1) [Ephemeral Container](https://addons.mozilla.org/en-US/firefox/addon/confiner/)
2) [Temporary Containers](https://addons.mozilla.org/en-US/firefox/addon/temporary-containers/)

Also, I know a Dev that is working in a new TabManager-add-on, adding temporary/ephemeral containers for normal browser. It's still an ALFA, but it is working perfectly.

**Comment by GonzRon** [comment]
My point is that permanent container is feature that is inside browser by default, while ephemeral Container is added by other extensions. It would require implementing such functionality inside tab group add on which is outside the scope of a tab manager, or it would require integration with an add on that provides this functionality.

**Comment by EstherMoellman** [comment]
OK, but now you're saying something a little different... it has not to do necessarily with PB (private browsing)... ephemeral container has to with an alternative, that today is not a browser built in function, and may require (or not) integration with other add-on. That's all!

I use the term "or not" because I'm not a Dev.
I only say that I already saw the ephemeral function working in an ALFA new tab-manager add-on. And the Dev never said it was difficult to made this function.

Perhaps, in the worst case, yeah, it may need an integration with other add-on.
But if it is possible/doable/feasible/easy... why not?

You say "this function is outside the scope of a tab manager".
With all due respect, this is your subjective opinion.
Such definition is only in Dev's hands, and users hands.
If the Dev wants to make this function, then it will be inside the scope.
And if users want this function... also it will be inside the scope.
At the end, what you are saying, is that all is just a matter of definitions (inside/outside)... and this is a theoretical debate.... in my opinion a waste of time... because the real debate is if the function is doable, and if it is useful for the add-on.

Please, don't get me wrong! I respect your opinion, and your argument (against ephemeral containers) is clear. I just hope you will respect my opinion in favor of ephemeral containers inside SimpleTabGroups.

**Comment by GonzRon** [comment]
>Please, don't get me wrong! I respect your opinion, and your argument (against ephemeral containers) is clear.

Actually I am not arguing against this idea, it is a good idea. I hope we get as many features as possible from a user perspective. 

>You say "this function is outside the scope of a tab manager".  With all due respect, this is your subjective opinion.

I think it's objectively true. Should tab manager extensions also be responsible for fixing hard drive of computer if it broken?  Just because one tab manager implemented this functionality does not mean that it is a feature that is not external to the main job of a tab manager extension. 

Heres a different use case example for feature request: Should tab manager also store passwords for sites in tab?  Maybe one user subjectively thinks this is good idea too?

Perhaps we could have one big browser extension that does all functionality of all existing add ons? What then? Perhaps this add on would then turn into a whole new browser itself, no longer even Firefox.

**Comment by EstherMoellman** [comment]
Please, allow me to answer you, just with the intention of defending my request:

As a student of Physics, I say "there is no objective true".  Even 1+1=2 is not an objective true. True always is relative, and depends on the observer.

Fixing HDDs? Storing passwords? Etc? You totally exaggerated in your examples, and you know that.
You are right, my request (ephemeral containers) may depends on the integration of something else. But that's all. Piece of cake. Please, let's not make a big deal from that.
A lazy Dev certainly is going to use your argument, rejecting requests under the concept that "everything is not specific to his add-on".
In the other hand, a good Dev first will think if the request is doable, and if it is good for users and his add-on.

According to your logic, the IPhone is a bad idea, because a phone never can be a computer, photo camera, audio player, movie player etc etc etc
Well, in the theoretic world... you're right.
However, in the real world, is the market (consumption) who determines what is "the objective true". And if the market wants an add-on having everything, then so be it.

I have nothing against you. Again, I am just trying to defend my request (ephemeral containers).
Again, there are just two points to debate about my request:
a) Ephemeral containers is doable at SimpleTabGroups?
b) Is it useful for users and for STG?
That's all! Nothing else. The rest... is just theoretical philosophy.

**Comment by GonzRon** [comment]
So just to be clear you want a group where each tab in this group is opened in its own ephemeral container, or for the tabs in the group to share one ephemeral container?

**Comment by EstherMoellman** [comment]
My request is the option of opening any tab (one or more tabs) in individual (not shared) ephemeral/temporary container, at any Group (one or more Groups).
And it will be great if the ephemeral/temporary container deletes itself (including all its content) when the tab is closed or the Group is deleted.
For 99% of the needs, this kind of ephemeral/temporary container function will be more than enough, and will be extremely useful too! A great added-value for STG.

And for the 1% who may need a "shared ephemeral/temporary container", if I am not wrong, by duplicating the tab (mouse right-click over tab => Tab Menu => Duplicate Tab) this automatically will also duplicate the same ephemeral/temporary container.
If I am wrong, and if this is a "shared ephemeral container" is difficult to be done at STG, honestly I won't care too much, because shared containers can be done through permanent containers.

**Comment by Drive4ik** [comment]
@EstherMoellman Hi!
I think your request will be completely satisfied with the `Temporary Containers` addon.
I do not want to duplicate the functionality that has already been implemented and perfected in other add-ons. Then my addon will become a monster...

**Comment by EstherMoellman** [comment]
@Drive4ik Hi! Thank you for your answer.

I perfectly know the TemporaryContainer' add-on (TCA).
The TCA is a bazooka for killing mosquitoes, great for those users that are looking for killing mosquitoes with bazookas. Nothing against them, neither nothing against TCA!

If I had requested to duplicate TCA into STG, yeah, then you would really be right in your argument.
But this is not the case at all! I just requested the minimalist function of opening ephemeral containers at STG.
I don't need all the TCA' functions into STG!
I just requested 1 sole simple minimalist function at STG: The alternative to open ephemeral containers. That's all!

And no, STG is not going to be a monster by incorporating ephemeral containers.
As I wrote here days ago (please see above), I already saw an alfa (under development) tab-group-manager add-on incorporating ephemeral containers, and this add-on is very lightweight and simple. Also, the Dev never said a word about "monsters", "difficulties", "impossibilities", "specificity" etc.

I confirm you, to include ephemeral containers into STG... it is perfectly doable.
To include or not include it, is just your personal prerogative @Drive4ik , but it has nothing to do with  "monsters", "difficulties", "impossibilities", "specificity" etc. If you want, you can do it, and vice-versa.

Thank you in advance!

**Comment by Drive4ik** [comment]
@EstherMoellman how about this:
https://addons.mozilla.org/firefox/addon/click-to-contain/
?

**Comment by EstherMoellman** [comment]
@Drive4ik , I thank you for trying to find replacements to my request.
With all due respect, thank you once again, but I don't need replacements for my request here.
If you have the patience, please read my posts from the beginning, and you will see that my request has nothing to with finding other add-ons, or replacing my request with other add-ons etc.

My request is specifically to you, and specifically for STG.
And I'm convinced that ephemeral containers inside STG, it will be useful for users and for STG itself.

If you don't accept my request, or don't like it, or don't have time for it, or whatever, please, don't worry, I understand.
In this case, please, let's be honest, and let's recognize that any rejection of my request is not based on "monsters", "difficulties", "impossibilities" etc. Let's be honest and let's close my request, by saying the truth (that you don't accept my request, or don't like it, or don't have time for it etc). Again, I perfectly understand any rejection of my request, but not based on the arguments that already were posted.

Cheers

**Comment by Drive4ik** [comment]
@EstherMoellman 
Regarding the "monster": I don’t understand why it hurt you so much, because users often ask me to add this or that function from another addon. And if I fulfill all the wishes, then the word "Simple" will have to be removed from the addon name... I hope you understand me.

And yet, I still do not understand what you mean by the word "temporary container"?
Do you mean, for example, in the context menu on the button to create a new tab in the pop-up window (there is a list of current containers) will there be a new item with a "temporary container"? What he will do: create a container and open a new tab with it. And then the code should make sure that when this tab closes this container needs to be removed. Right?
There are several problems:
- what to do if the user selects this container as the main one in the group
- the user can create a lot of such tabs with containers, and the group editing window will be very long ... it will turn out ugly
- what to do if with open tabs with these containers, auto-backup will occur, exclude these tabs from backup or not
- The same thing, only backup to bookmarks.
- What to do if the user pins this tab, because the addon does not follow pinned tabs due to the great complexity and a great chance of error
- if a group has one permanent container selected, and you try to move a tab with a temporary container to this group, the addon will delete this tab and create a new one with the container that is attached to the group, which will no longer be correct. for some it will be obvious not to move this tab, but for others it’s obvious to move anyway, because the user himself chose this tab to move
- there may also be problems with regular expression matching (in tab url) from another group that also has a persistent container set as the main

There are many different non-obvious behaviors, and they all need to be processed and tested both in the STG add-on and with all similar add-ons so that there are no conflicts.

Just for you to understand, you cannot distinguish one container from another except by name or ID. It is impossible to understand which container which addon was created and which addon it is monitoring which container. It is impossible to understand that the container is temporary, to write in its name that it is temporary is a so-so solution, because the user can easily change this name.

There are some more difficulties, for example:
you have 3 permanent containers
their id:
`firefox-container-1`
`firefox-container-2`
`firefox-container-3`
When you create a new container (or addon create), its id will be `firefox-container-4`. Then you delete this container and create a new one, and its id will also be `firefox-container-4`, which greatly complicates the development, taking into account all the behaviors described above ...

I can do what you ask very easily, literally 20 lines of code, but processing various behaviors and conflicts with other add-ons or other functions in STG is not so simple.

Sorry for my bad English, I wrote with google translate))

**Comment by EstherMoellman** [comment]
@Drive4ik ,

Nothing/No one is "hurting" me.
I just defended my arguments, and sadly this may be misunderstood. I disagree with all the arguments presented here above, trying to reject my request. But this has nothing to do with "hurting" me.
Your add-on STG is great, I love it, I really want changes on it, it is not the first time I try to sell you my requests etc... but that's all @Drive4ik ... nobody is hurting anyone... if I am here arguing, is just because I like your add-on, and I want changes. That's all.

You recently added Permanent Containers (it was a fantastic addition!).
This was the reason I requested Temporary Containers.
This is why I define my request as a SIMPLE request. It is simple, because my request was a consequence of your previous addition (Permanent Containers). Again, if you first added Permanent Containers, then secondly it makes all the sense to have the option for Temporary Containers. This is logical! Your action drove to my request.
All the arguments presented here against my request are illogical, because all said against Temporary Containers, it also might be said against Permanent Containers.
At the precise moment you added Permanent Containers at STG, that validated my request for Temporary Containers, that made logical my request, and that also made simple my request.

You may not like my request for Temporary Containers, but you may not say that may request is not logical, is not simple etc. Again, if you say that, then I may say the same for your Permanent Containers.

By "Temporary Containers" I mean what technically is known as "Ephemeral Containers". It is the same, Temporary Containers is the expression used for users (sounds more friendly), and Ephemeral is the technical expression used by Devs. From now on, I will use "TC" for temporary/ephemeral, and "PC" for permanent. 
So, TC is an individual container that when the tab is closed, it deletes itself, including all its content.
A PC, means that a specific domain will be open always at the same container.
A TC, means that this domain always will be opened in a new different individual container.
PC are useful when you know a domain you want to containerize.
TC are useful when you want to containerize everything else you don't know, any domain, and each one in a different individual container.
At PC, stuff is shared inside the PC, and tracking is easier inside this PC.
At TC, stuff is isolated inside the TC, making difficult tracking, because different TCs are isolated, individual, they don't share stuff.
Sometimes an user may open a TC, and may need to share this TC. This is possible by duplicating the TC' tab.

The first example you described is correct.
I don't mind where you want to put the selector for TC. It may be placed at the the context of the Tab Menu, or at STG' options page, STG' manage groups page etc.
My simple request is to have an option, to open every tab, at every group, in a TC. And when the tab is closed, the TC deletes itself (with all its content).

Answering now your described "problems":
- As I explained above, TC are individual. So, there is no such thing like "main container for a Group". A TC is for tabs, independently of Groups. If an user chooses to open all tabs in TC, the result will be that one or more groups will have individual tabs, in TC, each container different than the other.
-  It is not going to be ugly, because the GUI of a TC may be done by a simple "TC01", "TC02" etc.
- Tabs are only excluded when user excludes them. And only when tabs are excluded, that TC are excluded. A TC never may be excluded before closing a tab. A TC will live until the tab is closed. The same goes for bookmarks, pin tabs etc.
- A Group may have one PC or infinite PC, and at the same time may have one or infinite TC. They are two different kind of containers, and they are compatible. A TC doesn't replace a PC, and vice-versa.

Your list of "problems" is great!
That showed me that as long as you better understand the difference between TC and PC, you immediately will understand that my request is simple. Now is clear to me, that you are having difficulties to accept my TC' request, because naturally you don't understand completely how TC work.
Days ago, I posted here, an add-on that will help you to understand how TC work ([EphemeralContainer](https://addons.mozilla.org/en-US/firefox/addon/confiner/)). It is a tiny and simple add-on, that may be incorporated inside STG. Just for fun, please install this add-on, and see that all your "described problems" are solved.
Also and as I mentioned, I am in contact with a Dev, he has an alfa version of a new tab-manager add-on (under development), he already included TC inside his alfa versions, and no problems at all!

Your English is perfectly fine, sorry indeed for my English! : )

I really hope you'll be patience with my TC' request.
Again, I'm sure you first need to better understand what a TC is. By doing that, I'm sure you'll see that my request for TC is not just SIMPLE and LOGICAL, but also it will tremendously useful for STG' users, and for STG' itself.

Thank you once again in advance!

**Comment by Drive4ik** [comment]
Hi! Done! This update will be in next release.

**Comment by Drive4ik** [comment]
@EstherMoellman Please test this functional in latest version v4.2

**Comment by EstherMoellman** [comment]
@Drive4ik , please forgive my ignorance, but I can't find the TC' option.
At your release note you wrote "added Temporary Container in context menu on create tab button". Please, sorry again, which context menu? Which create button?
I tried to look at every single menu in SimpleTabGroup, and I can't find de TC' option.
I'm on Nightly.

**Comment by GonzRon** [comment]
i found it by going into manage groups, and then right clicking inside a group, the last option is "temporary container"

**Comment by Drive4ik** [comment]
@EstherMoellman Done. Please, update addon to latest version (v4.2.1)

**Comment by EstherMoellman** [comment]
Wowwwwwww... FANTASTIC! THANK YOU! I LOVE YOU! : )

At first sight, everything seems very, very, nice.
Kudos! Great job @Drive4ik .
In the next days I'll perform stress tests, with lot of tabs and groups, just to confirm that everything is perfect.

Now I will give you an irrelevant suggestion: To make short at UrlBar, the long text "temporary container etc + icon". It takes lot of space at the UrlBar, and is useless. Personally a "TC01", "TC02" etc will be enough, no icons needed (because is always same kind of container, just the number is different).
Why I say is "irrelevant"? Firstly because it is really a minor detail. And second because I can hide this by using CSS, so is not a problem at all for me.
I'm just mentioning the suggestion because it may be useful for other users. A "TC01" text is all needed at UrlBar, icon is not needed, and this will save lot of space at UrlBar.

Once again @Drive4ik , congrats and zillions of thanks to you !!!!!

**Comment by EstherMoellman** [comment]
Hi @Drive4ik , continuing with my previous message, with regards to the "temporary container" text label at UrlBar:

A great Dev here at GitHub helped me with the CSS, in order to make it shorter.
Just in case you are interested, here is the [Model01](https://pastebin.com/15LEzD4g), and here is the [MODEL02](https://gist.github.com/MrOtherGuy/0810e32ae0d1f50a03b696682f7a8996).

The problem as you will see, is that the first model with small code, only works for 3 temporary containers.
The second model is perfect, it shows just a simple minimalist and clean "TC01"... "TC99". However, it works until 99. It demands 999 rules for 999 temporary containers.

So, the best solution for your "temporary containers" text label at the UrlBar still is from your side. I know you are busy, so I'm not asking you to do nothing today. But please, take all the time you need, and if you have several minutes, please:
1) Remove the clock icon at the UrlBar
2) Remove the text: "Temporary Container" at the UrlBar
3) Instead, change "Temporary Container" for "TC"
4) Keep the counter number
5) Remove the glasses icon

That's all.
The final result will be at urlBar: "TC01"... "TCXXX".
It will be much more smaller, freeing space from urlBar, less visual pollution, while keeping all the information.

Thank you once again!

**Comment by Drive4ik** [comment]
@EstherMoellman Hi
Sorry, but I won’t do it.
Perhaps this option is right for you:

``` css
#userContext-icons[class*="toolbar"] {
    overflow: hidden;
    display: flex;
}

#userContext-icons[class*="toolbar"]::after {
    content: "TC";
    margin-left: 4px;
}

#userContext-icons[class*="toolbar"] > #userContext-label[value$="0"],
#userContext-icons[class*="toolbar"] > #userContext-label[value$="1"],
#userContext-icons[class*="toolbar"] > #userContext-label[value$="2"],
#userContext-icons[class*="toolbar"] > #userContext-label[value$="3"],
#userContext-icons[class*="toolbar"] > #userContext-label[value$="4"],
#userContext-icons[class*="toolbar"] > #userContext-label[value$="5"],
#userContext-icons[class*="toolbar"] > #userContext-label[value$="6"],
#userContext-icons[class*="toolbar"] > #userContext-label[value$="7"],
#userContext-icons[class*="toolbar"] > #userContext-label[value$="8"],
#userContext-icons[class*="toolbar"] > #userContext-label[value$="9"] {
    margin-left: -12em !important;
}

```

**Comment by EstherMoellman** [comment]
Hi @Drive4ik ,

By using CSS, I managed to perfectly customize the Temporary Container label at UrlBar (I replaced with TCXXX), and also at Pop-up (I removed the image). Both now are perfectly clean and minimalist.

The last one I have is at TabMenu (mouse-right-click at tab => STG' Move to tab grooup => TC' clock + label).
I tried to use:

`#simple-tab-groups_drive4ik-menuitem-22 > label:nth-child(2) { margin-left: -140px !important }
`
... but only works at BrowserToolbox and for the first label.

Please @Drive4ik , any suggestion about how to remove the image and text label here?

Thanks in advance!

**Comment by Drive4ik** [comment]
Try this
```css

menupopup menuitem[id^="simple-tab-groups_drive4ik-menuitem"]:nth-child(2 or what u need) > .menu-iconic-left {
    position: relative;
}

menupopup menuitem[id^="simple-tab-groups_drive4ik-menuitem"]:nth-child(2 or what u need) > label {
    margin-left: -140px !important;
}

```

or remove 
`:nth-child(2 or what u need)`
to apply for all items

**Comment by Drive4ik** [comment]
@EstherMoellman hi!
I create new STG plugin https://addons.mozilla.org/firefox/addon/stg-plugin-create-new-tab/
If you can - try it)
P.S. this addon has options

**Comment by EstherMoellman** [comment]
Hi @Drive4ik ! I saw your add-on early in the morning (before your message), and said to myself: "hell, yeah, why not?". In simple words, yeah @Drive4ik , good job, someone may want your temporary-container-add-on without using STG. Good idea! And of course, I'll test the add-on for you, just give me few days. Also I will compare your add-on with [EphemeralContainer add-on](https://addons.mozilla.org/en-US/firefox/addon/confiner/).
Personally, I still believe temporary-containers should be a built-in FF' default function. I can't imagine a reason why one would like to open a page without temporary container. So, IMO it was perfect to include it at STG.

By the way, changing subject, please, allow me two new suggestions for STG:

1) Refresh discarded tab: Normally, when a discarded tab is loaded again, the page is the old one, it doesn't reload/refresh. So, for example, if you are on Reddit/GitHub etc, your tab is discarded, and after "x" minutes the same tab is loaded again, the page content in this case will remain always the same, and users are not going to see new posts, new messages etc. And considering that most of the discarding tabs, when loaded, need to be manually refreshed by the users, I think it will great to add an option at STG, where the Group may be automatically reload/refresh every discarded tab that becomes active again.

- Select specific tab, when current tab is closed: Firefox has an ugly behavior, when a tab is closed, Firefox jumps to the tab on the right. In my experience, most of the users prefer Firefox jumping to the tab on the left (is more intuitive). But it will nice an option at STF, allowing the user to choose which tab he wants Firefox to jump when current tab is closed. For example, it will be nice an option offering the right tab, or left, or last, or pinned etc.

Yeah, yeah, I know, you're going to say to me that these functions already may be found in other add-ons. But the logic here is similar to temporary container inside STG: It doesn't matter that other add-ons can offer all the functions. What really matters is if these functions inside STG are going to be useful for the STG' user, and also if these functions are going to be useful for STG itself. And exactly as happened with temporary container, I believe that these two new features I'm requesting here to you, both IMO are going to be very useful for users and for STG itself. Also, STG won't be impacted in size, performance, RAM etc, because these two features are extremely lightweight. Here are two add-ons doing that:

- [UpdateDiscardedTab](https://addons.mozilla.org/en-US/firefox/addon/update-discarded-tab-on-select/)

- [SelectAfterCurrent](https://addons.mozilla.org/en-US/firefox/addon/select-after-closing-current/)

Thank you in advance! : )

**Comment by stoically** [comment]
Just wanted to quickly say that it's great to see more Add-ons implementing disposable containers. Hopefully that helps to one day make an argument for a native disposable container API to do it. Keep it up!

**Comment by Drive4ik** [comment]
@EstherMoellman Hi! I added rename temporary container title in addon settings. Update will available on next release

**Comment by benyaminl** [comment]
This is such a blessing! Thanks for @EstherMoellman and @Drive4ik  this make me use less addons just STG rule them all, and it's simple.
