### ISSUE TITLE
Null tab error

### ISSUE THREAD

**Issue by Monirzadeh** [Drive4ik/simple-tab-groups#48]
hi 
today I send some tabs(11) from Group A to Group B(6+11) after a while
I try to jump Group B (17 tabs show me in Group B )
but get an error about null tab and Group B load with only 6 tabs.
list of tabs in some Group not acceptable and manage Group too (not load).
unfortunately, i lost multitab address today.
what am I Do?
save a backup from all of my groups and check json file 
in the groups that I have  problem with them, i found something like this
`                },
                {
                    "id": 15,
                    "title": "title i remove",
                    "url": "https://urliremove.com/",
                    "active": false,
                    "cookieStoreId": "firefox-default",
                    "thumbnail": null
                },
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null,
                null`
            ],`
after i remove all of null from end of my Groups in json and restore every thing work correctly
i am not sure about source of problem but maybe and i say again maybe when i try send tabs(not all of them ) to other group some of them is not load completly and firefox still loading them

**Comment by Drive4ik** [comment]
Hi @Monirzadeh 
I kind of fixed this problem ...
If you use the latest version of STG, tell me how you transferred the tabs, and do you use some other extensions to work with the tabs?
Thanks

**Comment by Monirzadeh** [comment]
I update that yesterday.
I send to other groups with right click on tabs STG > GroupB
about other extensions I am not sure

**Comment by Drive4ik** [comment]
Was Group B open in another window at the time?

**Comment by Drive4ik** [comment]
Hi! Can you backup your tabs groups (so as not to lose) and retest this issue on latest version? (v2.3)
Thanks

**Comment by Monirzadeh** [comment]
hi
I don't remember group B was open or not.
I test V2.3 with that backup and
everything works correctly GroupB with 6 tabs (other 11 tabs not show) but STG load and accessible all groups and manage groups too.
it isn't bad if you add an automatic backup option

**Comment by Drive4ik** [comment]
This error is still repicated on version v2.3.6?
