### ISSUE TITLE
After update to STG 4.2 Groups Popup looks broken 

### ISSUE THREAD

**Issue by alexanderchernyakevich** [Drive4ik/simple-tab-groups#480]
**Describe the bug**

I have updated today to STG 4.2 and have found that Groups Popup looks either broken or changed how it works:
- after opening it _Search_ field is not focused so you can't start to type and search
- up and down keyboard arrows do not do navigation in the displayed list 

**To Reproduce**
1. Call keyboard shortcut to open Groups Popup (in my case Ctrl+Shift+F8)
2. Cursor is not located in Search field. 
3. Up and Down keyboard arrows do not move focus inside displayed list of tab groups/tabs

**Expected behavior**
After opening Groups Popup Search field should be focused, Up and Down keyboard arrows should work to navigate in the tab groups/tabs list the same as it worked earlier.

**Desktop (please complete the following information):**
 - OS and version: Windows
 - Firefox version: 69.0.3 (64bit)
 - Simple Tab Groups version: 4.2

**Comment by falolaf** [comment]
I can comfirm this! I would say that https://github.com/Drive4ik/simple-tab-groups/issues/481 is a duplicate.

**Comment by Drive4ik** [comment]
Hi!
I fix focus on search field, but the up and down arrows will most likely not be redone.. You can now switch using `Tab` and `Shift + Tab`
Buttons left and right should work as before. 
But now you can control the entire popup only using the keyboard, create tabs and navigate the context menu.

**Comment by alexanderchernyakevich** [comment]
Dear @notJerl 

This is why I raised this issue - because I work from keyboard very actively. So I feel uncomfortable immediately after installing new version. :)

And now I would vote to return back navigation using Up/Down keys instead of (or in addition to) `Tab` / ~Shift+Tab` shortcuts. Main reason is that it is much more convenient from the point of view of usability - you just don't need to involve left hand when you navigate in menu.

So @Drive4ik, is there any technical limitations why Up/Down keys could not be used for navigation? Be frankly, as you have implemented using Left/Right there should be a problem to make similar.

Meantime, I see a problem of using `Tab`/`Shift+Tab` for navigation - if you started to type something in Search field then to navigate in the list at first you need to press `Tab` **2 times before** you will get to list of filtered tabs and will start real navigation. You just need to pass through `Exteded Search` checkbox and Search Reset button. Be frankly, it will seriously annoy me as I use searching very often and do not expect that I will either these buttons.

Even more, probably it could be much better idea to make `Extended Search` available in global Add-On settings than in the popup dialog.

Similar for Search Reset - I can clean it by pressing `Ctrl+Backspace` even not leaving of Search field. Or pressing `Esc` followed by recall of Group Popup (`F8`).

What do you think?

**Comment by falolaf** [comment]
I fully agree with what @alexanderchernyakevich says!

**Comment by alexanderchernyakevich** [comment]
@Drive4ik 

I have just installed STG 4.2.1 and Search field receive focus on opening of the popup. But... when I clear Search field completely (for example, `Ctrl`+`Backspace`) then accidentally Search field lost the focus and I need to navigate using mouse back to Search field. :)

As well... Having searched something and found one tab only I need to use **3 (three)** press to `Tab` to get reached this item. :( If you would like I could move topic of using Up/Down arrows for navigation in Groups Popup to separate issue/feature request and we could make voting about it.

**Comment by Drive4ik** [comment]
Hi all)
I fixed these issues. Please update addon to v4.2.2

**Comment by alexanderchernyakevich** [comment]
thanks a lot! Looks working now. :)
