### ISSUE TITLE
Technical Question: ... and thx for the addON!

### ISSUE THREAD

**Issue by pmario** [Drive4ik/simple-tab-groups#482]
Hi, 
Your addOn is great, it helps me to get order into my "open tabs chaos". Thx a lot!

I did create an addOn that has about 1000 users and I need to open/reload a file:// URL. I am able to create the tabs, with `tabs.create()` ... It only shows the browser URL but the site content isn't reloaded. ... The problem started with FF 67 or something like that. ... 

Your addOn seems to handle this function well. So: I do have a technical question about the "open/reload tab" function of your extension. 

Can you point me to the code, that handles group: tab creation and reloading the content from a file:// based URL. 

thx

**Comment by Drive4ik** [comment]
Hi!
You can find code here
https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/js/tabs.js#L10
and for reload tabs
https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/js/tabs.js#L532

**Comment by pmario** [comment]
Thank you very much for your fast response. ... I'll close the issue and have a closer look.
