### ISSUE TITLE
Regression in up&down arrow handling in popup window

### ISSUE THREAD

**Issue by kparal** [Drive4ik/simple-tab-groups#483]
**Describe the bug**
I believe just a few days ago I could use up&down arrow in the popup in a more convenient way:
* Pressing `up` or `down` moved the group selection up or down. So if third group was selected and you pressed `up`, the second group got selected. If you instead pressed `down`, the fourth group got selected.
* Both `up` and `down` arrows worked immediately after opening the popup.

But now it works like this:
* `up` arrow doesn't work in the popup until you press `down` at least once (that shifts focus from the search field to the groups list).
* You always start on the top. So if you want to switch from fifth group to fourth group, you need to press `down` 4 times. That is annoyingly cumbersome.

**To Reproduce**
1. Activate fourth group
2. You want to switch to the third group
3. Open the popup (ideally with a keyboard shortcut)
4. Press `up`. Nothing happens.
5. Instead you need to press `down` three times.

**Expected behavior**
`up` and `down` should function immediately in the popup window and should move the current selection up and down (instead of starting from the top every time)

**Desktop (please complete the following information):**
 - OS and version: Fedora 30
 - Firefox version: 69.0.3
 - Simple Tab Groups version: 4.2.2

**Comment by kparal** [comment]
Thanks! :heart: Why is this just a partial fix? Which part remains unfixed?

**Comment by Drive4ik** [comment]
@kparal Hi! I do not know) But it seems to me that I missed something ... we'll see

**Comment by kparal** [comment]
I have version 4.3 now and this is not fixed. The up&down arrows move the focus starting from the search field (so one press down moves the focus to the first group, and one press up moves the focus to the last group), instead of moving the focus relative to the *currently active* group.

**Comment by Drive4ik** [comment]
@kparal That's what I talked about)
Fixed

**Comment by Drive4ik** [comment]
@kparal Please, update addon to latest version and retest issue

**Comment by kparal** [comment]
It's now working as expected! Thanks a lot!
