### ISSUE TITLE
Setting to not reload tab in the group-related container when the tab is already in a container

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#485]
**Is your feature request related to a problem? Please describe.**

Today, when a existing tab is moved to a group which is assigned to a container (ie all tabs in this group will open in this container), the tab is reopened in the group-container even if it was already open in a container (I mean, not the "default" container)

**Describe the solution you'd like**

Maybe an addon-wide setting to choose the behaviour:
- On/Off: a tab already in a non-default container will be reopened in the group-related container when moved to such a group

Thanks :)

**Comment by Drive4ik** [comment]
Hi! Sorry, but now it’s impossible to do, the logic is getting too complicated...

**Comment by Drive4ik** [comment]
Hi! Done :) I added group option named `If the container is different from the selected one - change the container`
please update addon to latest version and restart browser
