### ISSUE TITLE
Data URIs are saved as blank URLs when group is closed

### ISSUE THREAD

**Issue by kssi** [Drive4ik/simple-tab-groups#488]
**Describe the bug**

I often use "blank" tabs as tab separators within a single group/window. Instead of about:blank, they're loaded on a custom data URI so they stand out better as separators.

When I close the group/window, said tabs are saved as about:blank and the data URI is lost.

**To Reproduce**

1. Inside a group, [open a tab](data:text/html;charset=utf-8,%3C%21DOCTYPE%20html%3E%3Chtml%3E%3Chead%3E%3Ctitle%3Edata%20URI%3C%2Ftitle%3E%3C%2Fhead%3E%3Cbody%3Edata%20URI%3C%2Fbody%3E%3C%2Fhtml%3E) with the following URI:

`data:text/html;charset=utf-8,%3C%21DOCTYPE%20html%3E%3Chtml%3E%3Chead%3E%3Ctitle%3Edata%20URI%3C%2Ftitle%3E%3C%2Fhead%3E%3Cbody%3Edata%20URI%3C%2Fbody%3E%3C%2Fhtml%3E`

The tab name should be "data URI".

2. Close the group/window.
3. The tab is saved as a blank tab and not with the expected URI.

**Desktop (please complete the following information):**
 - OS and version: macOS 10.11.6 El Capitan
 - Firefox version: 70.0
 - Simple Tab Groups version: 4.2.2

**Comment by Drive4ik** [comment]
When you close the window, the tabs really close, I then open them again in background, so this is not possible for technical reasons:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create
read about `url` parameter

**Comment by kssi** [comment]
Thanks for providing the documentation.
