### ISSUE TITLE
Hide firefox permission dialog on group switch

### ISSUE THREAD

**Issue by mustaqimM** [Drive4ik/simple-tab-groups#489]
**Describe the bug**
I keep on getting the permission dialog window popup on switching

![image](https://user-images.githubusercontent.com/24436622/68322174-dd9a1080-00ba-11ea-8301-9388fbac0e4d.png)

**To Reproduce**
1. Switch Group
2. See error

**Desktop (please complete the following information):**
 - OS and version: [Linux]
 - Firefox version: [70.0.1]
 - Simple Tab Groups version: [4.3]

**Comment by Drive4ik** [comment]
Click on button
`Keep Tabs Hidden`

**Comment by mustaqimM** [comment]
I can't, it shows only for a split second

**Comment by Drive4ik** [comment]
This window is controlled by Firefox, not addon.
Try to assign hotkeys to switch groups, switch groups, and hold the mouse near the place where this popup is, and as soon as it appears - immediately click on it.
:)
Well, I don’t know what else to offer you, apparently the focus of the window is lost, and Firefox closes this window (popup).

**Comment by mustaqimM** [comment]
I've actually been trying that exact sequence for a very long while, but it still continues to show...

**Comment by Drive4ik** [comment]
So try to figure out what exactly the focus takes.
You can also try turning off the addon and turning it on
**But be sure to backup the addon (available in the addon settings)!**

**Comment by mustaqimM** [comment]
@Drive4ik I managed to click the dialog after temporarily disabling my custom chrome configurations. Thanks for your help
