### ISSUE TITLE
Tab hiding news

### ISSUE THREAD

**Issue by hdd60311** [Drive4ik/simple-tab-groups#49]
Seems that a preliminary support for it has been added in latest 59nightly.
https://bugzilla.mozilla.org/show_bug.cgi?id=1423725
https://addons.mozilla.org/en-US/firefox/addon/hide-tab/

**Comment by Drive4ik** [comment]
This is just great news. 👍
I will soon release an experimental version that supports this API!

**Comment by Drive4ik** [comment]
Closed. See #2
