### ISSUE TITLE
Clicking on Open group in new window reloads all tabs for this group

### ISSUE THREAD

**Issue by lafiel** [Drive4ik/simple-tab-groups#491]
Hi there,

**To Reproduce**
1. Click on the STG in Firefox
2. Right click on the group and select "Open group in new window"

**Expected behavior**
Before you could be sure "open groups in new window" would load the tabs from cache (or perhaps only the on the tabs you clicked on) and not refresh _all_ of them from the internet. 
If you have 20 tabs it slows things down and uses more RAM than necessary.

**Desktop 
 - Linux 5.3.8-3
 - Firefox version: 70.0.1
 - Simple Tab Groups version: 4.3.2

**Additional context**

**Comment by kssi** [comment]
I think that's a temporary fix for bug #456 and related.

**Comment by Drive4ik** [comment]
Yes, this is a temporary fix and inconvenience...
Need to wait when they fix
https://bugzilla.mozilla.org/show_bug.cgi?id=1580879
and the code that does the reloading of the tabs will stop working automatically
