### ISSUE TITLE
Rest groups not active when closing a window

### ISSUE THREAD

**Issue by skyline-ch** [Drive4ik/simple-tab-groups#492]
sorry i do not speak english, i use google translate

**Describe the bug**
Hello, I'm having problems with the extension simple-tab-groups, I open the group A, the extention in other as group B, C, D .... ect.

If I open another group in a new window or open a new tab in another window and then close one of the 2 windows, all the groups that are not open are left with 0 tab.

So I have to reload from a backup group, and there is also a bug, I end up with 2 times the same group once with 0 tab and once with the tabs save.

**To Reproduce**
1 start Firefox
2 open a group (example group A)
3 open in another window another group (example group B)
4 Femer Group B
5 Access the list of groups

**Screenshots**
![STG-Capture d’écran de 2019-11-10 13-17-44](https://user-images.githubusercontent.com/13089438/68544039-1ee23700-03bf-11ea-8117-1d03087650a2.png)
![STG-Capture d’écran de 2019-11-10 13-30-54](https://user-images.githubusercontent.com/13089438/68544040-1ee23700-03bf-11ea-8bc3-c9a9f32f1c0d.png)

**Desktop (please complete the following information):**
 - OS and version: Linux, Ubuntu 18.04
 - Firefox version: 70.0.1 64x
 - Simple Tab Groups version: 4.3.2

**Comment by Drive4ik** [comment]
Hi! I fix this bug, but this applies only to one group open in the window, while the addon does not touch tabs from other groups

**Comment by skyline-ch** [comment]
Thank you for the answer, I have not understood everything, I have to open all the tabs so that it corrected silk?

**Comment by Drive4ik** [comment]
You need to wait when Simple Tab Groups version would update to 4.3.3 or above and retest this issue.
Perhaps you did this by each group, so they are empty for you. Just wait for the new version and check again - everything should work.

**Comment by Drive4ik** [comment]
I release STG v4.3.3

**Comment by skyline-ch** [comment]
I just tested version 4.3.3, I have no more bug. thank you
