### ISSUE TITLE
Restore backup not working

### ISSUE THREAD

**Issue by harvimt** [Drive4ik/simple-tab-groups#493]
**After upgrade to 4.3.3 lost all large tab groups and pinned tabs, cannot load backup**
- After the upgrade to 4.3.3 I launched Firefox, and it hung, so I had to force firefox to quit (it happens and I have a lot of addons)
- after relaunching, some of the groups loaded fine, many were empty or missing tabs. Additionally, all my pinned tabs were gone (I only have 3).
- I attempted to load the last good backup, but it endlessly spun never loading the data
- I tried launching a new fresh profile with just STG and no other add-ons
- I tried only loading some of the group, or only loading groups and not features.
- I tried loading the backup from 2 days ago instead of yesterday
- I was going to try to downgrade to 4.3.2, but it is not available to downgrade to (only 4.1.0)

I could manually extract the URLs from the JSON file of the backup... and get some semblance of normalcy... but the fact that the restore backup is not working concerns me.

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Firefox version: 70.1
 - Simple Tab Groups version: 4.3.3

**Additional context**
I have 2 very large "background" groups of about 50 tabs.

**Comment by Drive4ik** [comment]
Hi! Sorry for this... please update addon to latest version - I fixed this bug

**Comment by Drive4ik** [comment]
P.S. and restart browser
