### ISSUE TITLE
Switch between two last Groups (like Ctrl/Cmd+Tab in OS)

### ISSUE THREAD

**Issue by ww7** [Drive4ik/simple-tab-groups#494]
Switch between two last Groups (like Ctrl/Cmd+Tab in OS)
Currently it's a two separate shortcuts for prev and next Group from history

**Comment by mzguy** [comment]
Furthermore, I can't get history to actually work correctly. It seems like multiple presses of the hotkey result in no change of group, then on the second, third, fourth attempt, etc., it finally switches. It's as if the history is unclean somehow.

**Comment by Drive4ik** [comment]
@ww7 
Addon cannot reassign browser hotkeys. Ctrl / Cmd + Tab toggles browser tabs and not groups. And you can’t change it ..

@mzguy 
Hotkeys in addon settings may not work everywhere, this is a limitation of FF webextensions. Try setting up hotkeys in your browser settings.
![изображение](https://user-images.githubusercontent.com/7843031/83417120-56333680-a42a-11ea-881a-3689274e8f02.png)
![изображение](https://user-images.githubusercontent.com/7843031/83417150-60553500-a42a-11ea-9a7f-435ae6cc9d73.png)

**Comment by ww7** [comment]
> @ww7
> Addon cannot reassign browser hotkeys. Ctrl / Cmd + Tab toggles browser tabs and not groups. And you can’t change it ..

не важно какой хоткей, запрос был о функции

**Comment by Drive4ik** [comment]
а чем не подходит загрузка группы по истории? у меня стоит `Ctrl+<` и `Ctrl+>` и я между ними переключаюсь. это уже перегрузка по функционалу получается

**Comment by ww7** [comment]
Не знаю кому то нужно это или нет...
Подобная функция широко востребована и используется при переключении между окнами и языками (Android, macOS, Windows ...) 
Думаю чаще всего человек использует до двух окон (груп) в активном режиме, в таком режиме один зоткей был бы удобней. Хз... Я приспособился просто убирать лишние окна и переключаться средствами ОС.
