### ISSUE TITLE
Tabs restored in one block but groups are empty

### ISSUE THREAD

**Issue by Eagna** [Drive4ik/simple-tab-groups#495]
Firefox was not working correctly after a Windows 10 update. All of the drop down menus were empty and it would not even close down but had to be stopped via the control panel. The tab groups also disappeared. Firefox somehow started working again but the tab groups were missing. I tried restoring them but the tabs came back all together and the groups came back but were all empty. I have nearly 3000 tabs so manually regrouping them is a big task.

Steps taken in STG:
settings
options
Backup your simple tab groups
Restore backup
Select backup
Open

After a while the tabs appear and all the groups appear but are empty. A message saying they were successfully restored appears also.

OS: Windows 10 Home 64 bit
Firefox: 70.0.1
STG: 4.3.6

**Comment by Eagna** [comment]
This problem has been resolved. For some reason multiple copies of my groups were present at the same time. When I opened my list of tab groups they were all empty as mentioned in my original comment but if I scrolled down there were more copies of the same tab groups all of which were empty except for the last one. This last one had the correct set of tabs in each group. This situation could presumably be avoided if duplicate tab group names were not allowed. I don't know how the situation arose in the first place but I assume that when I did subsequent restores (because all I saw were the empty tab groups) new empty tab group sets were created. The solution was to delete the empty tab groups leaving only the populated ones.

**Comment by Drive4ik** [comment]
If you scroll down the add-on backup page, you will see a button there to delete all add-on data, and after that you would not have duplicate groups. Also, you probably already noticed, you could choose the necessary groups during restoration.
Yes, the group recovery system has become a bit more complicated, but it has also become more flexible.
