### ISSUE TITLE
Tab from other group jump in after closing tab

### ISSUE THREAD

**Issue by kraml** [Drive4ik/simple-tab-groups#497]
**Describe the bug**
After I closed a tab in current group, a random tab from other group suddenly jumped in to current group, at the position of the just closed tab.

**To Reproduce**
1. Create a few groups, each with a few tabs.
2. Switch to a group.
3. Close a tab.
4. Some tab from other group may appear.

**Expected behavior**
No other tab appear.

**Desktop (please complete the following information):**
 - OS and version: Windows 10 1909
 - Firefox version: 71.0 beta 11
 - Simple Tab Groups version: 4.3.6.1

**Additional context**
I didn't have such problem since the first day I use this add-on. It only started to be so recently, maybe started in the past few weeks. I didn't run into this problem each time I close a tab, but I haven't identified a clear pattern yet. This is what I have observed so far:

1. I have 7 groups. The first one is the default group. Closing tab in this group never had the problem.
2. The tab that jumped in from other group seems mostly from the last one in the group. Although I also saw tab from the middle, but less chance.
3. After a tab jumped in from other group, it was still showed in the original group but not in the group where it currently in, from the group list of the addon icon. After switched groups back and forth the group tab lists would reflect the actual situation.

**Comment by Drive4ik** [comment]
Hi, tell me what other add-ons do you use? Perhaps this is a conflict with one of them (perhaps one of them was updated and caused this).
Try to test this problem on a new clean Firefox profile.

**Comment by kraml** [comment]
Here is the list:

Auto Reload Tab
BugzillaJS
Checker Plus for Gmail
Direct Currency Converter
Distill Web Monitor
Enhancer for YouTube™
EverSync - Sync bookmarks, backup favorites
Firefox Multi-Account Containers
Firefox Private Network
Gesturefy
Glitter Drag
JSON Lite
Kee - Password Manager
Keepa - Amazon Price Tracker
Offline QR Code Generator
Proxy SwitchyOmega
Referer Control
Refined GitHub
Select After Closing Current
Simple Tab Groups
Stylus
uBlock Origin
Vimium
Violentmonkey
WhatRuns


And thanks for reminding, let me disable other addons that also manipulate tabs and see if it will change.

**Comment by grago57** [comment]
I've had this exact same issue. The only two extensions we seem to have in common are: 
Firefox Multi-Account Containers
uBlock Origin

Did you find the problem?

**Comment by kraml** [comment]
I can confirm my problem was caused by the extension Select After Closing Current. It allows to configure which tab to select after current tab is closed. Previously I didn't check the "Skip Hidden" option of it so it can select a tab from other groups, i.e. a hidden tab. After I checked this option the problem didn't occur anymore.

**Comment by Drive4ik** [comment]
@kraml Sorry for such a long wait, and yes you're right. There are several add-ons that conflict with STG.
Specifically, this is caused by the behavior of STG, when the user enters the name of the tab in the URL bar and the browser automatically prompts you to switch to it, and when you select the tab, the addon needs to change the group automatically since the tabs belong to another group. Something like this
