### ISSUE TITLE
Incorrect symbols in tab context menu

### ISSUE THREAD

**Issue by unclechu** [Drive4ik/simple-tab-groups#5]
Related to new feature #3 

1. ![1](https://user-images.githubusercontent.com/799353/33195365-afb885fa-d0f8-11e7-8501-e39136bfaefb.png)
2. ![2](https://user-images.githubusercontent.com/799353/33195370-b64d12be-d0f8-11e7-9edd-454091f88963.png)
3. ![3](https://user-images.githubusercontent.com/799353/33195375-bbd34b54-d0f8-11e7-9284-225072962faf.png)
4. And **only here** we have incorrect symbols:
  ![4](https://user-images.githubusercontent.com/799353/33195386-cc93d148-d0f8-11e7-8e6d-4c5a1234f3ec.png)

**Comment by Drive4ik** [comment]
Thanks for helping to find bugs 👍 

This bug fixed in v1.7.1
Please update addon
