### ISSUE TITLE
[Feature Request] Show Groupname in Symbolbar

### ISSUE THREAD

**Issue by Stefan1232** [Drive4ik/simple-tab-groups#503]
**Is your feature request related to a problem? Please describe.**
Currently, the group is only indicated by color. I would prefere that the group name is written somewhere in the Window. The Groupname in the window Title is not enough as it is not shown when the window is open.

**Describe the solution you'd like**
Maybe a small indicator next to the searchbar which states the active groupname 

**Describe alternatives you've considered**
Using the window title, but thats not shown in the window itself.

**Comment by Drive4ik** [comment]
This question has already been raised in previous tickets.
In the topbar there is no way to do this.
Also, there is no way to do this in the URL bar, where the name of the container is. This is all a limitation of the Firefox API.
