### ISSUE TITLE
Pressing Ctrl+9 switches to a specific group, instead of using the Firefox native go to last tab.

### ISSUE THREAD

**Issue by jtagcat** [Drive4ik/simple-tab-groups#507]
**Bug description and reproduction**
Title: Pressing Ctrl+9 switches to a specific group, instead of using the Firefox native go to last tab.

I have unset all keyboard shortcuts under settings, but still happens.
I think this is probably caused by the extension stealing a the hotkey.
**Expected behavior**
Hotkey doesn't get captured by STG and Firefox switches to the last tab.

**Platform**
 - Fedora 31
 - Firefox 72.0b11 (20191227034945)
 - STG 4.3.6.2

**Comment by C-Meinert** [comment]
I do not see that behavior on my system. As expected Ctrl+9 goes to the last tab that is "open" in a group. Did you previously have Ctrl+9 set in the hotkeys for STG?

- Windows 10 (1909)
- 74.0a1 (2020-01-08) (64-bit)
- STG 4.3.6.2

**Comment by jtagcat** [comment]
Have never set Ctrl+9 on STG
Also meanwhile platform changed to 73.0b3.

**Comment by Drive4ik** [comment]
@jtagcat What you have on this
![изображение](https://user-images.githubusercontent.com/7843031/72985450-abad6600-3dee-11ea-95c1-9141e0f5280e.png)
![изображение](https://user-images.githubusercontent.com/7843031/72985476-b962eb80-3dee-11ea-831a-c8c6fd6af4a8.png)

And what other add-ons do you have? And their hotkey settings.

**Comment by jtagcat** [comment]
![image](https://user-images.githubusercontent.com/38327267/73122644-14c3e380-3f7f-11ea-9ed3-af6c381e612d.png)
Other items in the hotkeys section do not have anything near `Ctrl`+`9`. Except the extension, what changes the `Alt`+n to `Ctrl`+n, but can confirm it's working with STG disabled.
![image](https://user-images.githubusercontent.com/38327267/73122664-42109180-3f7f-11ea-9f67-4b723138fac1.png)
I think the cause might be, that STG works by hiding tabs and the last tab (including all visible and hidden tabs) just happens to be from an another group, thus a hidden tab from an another group is moved to the current one and also switched to.
I'm using the [Ctrl Tabs](https://addons.mozilla.org/en-US/firefox/addon/ctrl-tabs/?src=search) extension, same behaviour with [Ctrl+Number to switch tab](https://addons.mozilla.org/en-US/firefox/addon/ctrl-number-to-switch-tabs/?src=search), but with [shortcuts](https://addons.mozilla.org/en-US/firefox/addon/shortcuts/?src=search) it needs access to all tabs and switches to a whole an another group instead. None of them aren't unfortunately open-source, though I think it would be possible to ask the developers to release the code.
This thing feels like it should have an `about:config` variable, but I couldn't find it. The behavior of this supposed variable could be tested under Windows, where `Ctrl`+n is supported natively. This behavior does not seem to happen with `Alt`+n on Linux, so I would expect the same on Windows, if so, then find out a native way to switch to `Ctrl`+n on Linux.

**Comment by jtagcat** [comment]
One more thing, I binded 'last tab' on [Saka Key](https://addons.mozilla.org/en-US/firefox/addon/saka-key/) and tried that out. It seems that the behavior is the same.

**Comment by Drive4ik** [comment]
@jtagcat Hi. I create simple alternative addon aka `Ctrl Tabs`, but given hidden tabs
[ctrl_tab-1.0-fx.zip](https://github.com/Drive4ik/simple-tab-groups/files/4155182/ctrl_tab-1.0-fx.zip)

If you want, you can install and try it.
![изображение](https://user-images.githubusercontent.com/7843031/73774356-81638d00-478c-11ea-937a-a295d0335684.png)
and select downloaded zip file

**Comment by jtagcat** [comment]
Thank you, it works!
Now get it to GitHub, to Firefox Add-ons and write something that it works with STG.

What's different with this extension, that it works?

**Comment by jtagcat** [comment]
bit related
https://addons.mozilla.org/en-US/firefox/addon/copy-tab-urls-webex/
does not work, since it also takes all loaded hidden tabs

there probably should be an effort to make stuff compatible, I'm willing to (at least try) write copy-tab-urls compatible with stg

**Comment by jtagcat** [comment]
bit related
https://addons.mozilla.org/en-US/firefox/addon/copy-tab-urls-webex/
does not work, since it also takes all loaded hidden tabs

there probably should be an effort to make stuff compatible, I'm willing to (at least try) write copy-tab-urls compatible with stg

**Comment by Drive4ik** [comment]
>  Now get it to GitHub, to Firefox Add-ons and write something that it works with STG.

no) There are 10 lines of code, this is pointless

> What's different with this extension, that it works?

now when selecting tabs, hidden tabs are skipped.

[copy_tab_urls-1.4-fx.zip](https://github.com/Drive4ik/simple-tab-groups/files/4159666/copy_tab_urls-1.4-fx.zip)

Just use newer addons.
Older addons do not support hidden tabs because there was no such functionality then.

![изображение](https://user-images.githubusercontent.com/7843031/73845598-a824d080-482b-11ea-97f4-261fd8131adf.png)

I will not redo add-ons anymore))

**Comment by jtagcat** [comment]
Congratulations, you made me get in to Firefox Add-on development!
Copy Tab URLs is available here: https://gitlab.com/jtagcat/copy-window-urls/
Ctrl, not Alt: https://gitlab.com/jtagcat/ctrl-not-alt
Tab numbering soon to be PR/Forked from https://github.com/tuomassalo/tab-numbering

**Comment by Drive4ik** [comment]
@jtagcat Well done! Keep it up!

**Comment by jtagcat** [comment]
@Drive4ik one question: how did you get the source code for Copy Tab URLs?

**Comment by Drive4ik** [comment]
![изображение](https://user-images.githubusercontent.com/7843031/74167415-e443a100-4c30-11ea-8350-2ecbca662136.png)

`.xpi` is zip archive

But, some add-ons have minimized code, and this will not help you much.
