### ISSUE TITLE
Selecting unloaded tab from other group brings that tab to current group

### ISSUE THREAD

**Issue by pintassilgo** [Drive4ik/simple-tab-groups#509]
This works as intended only if I select the unloaded tab using STG (by the panel or groups manager).

From other ways, for instance by addressbar (type "%" to list all your tabs), if I select an unloaded tab from other group, this tab appears on the current group screen. But the tab is still listed as being from the other group. It's a weird bug.

**Comment by C-Meinert** [comment]
I have tried to reproduce this issue without success.
- Windows 10 (1909)
- Firefox 74.0a1 (2020-01-08) (64-bit)
- STG 4.3.6.2

Could you try to reproduce the issue in a clean profile with only STG enabled. If the issue stops happening then its possible another add-on or some user setting is causing some sort of conflict.

**Comment by pintassilgo** [comment]
Yes, it seems to be an incompatibility with Tree Style Tab (150k users). But it seems to be fixable by STG, because due to this issue I migrated to Tiled Tab Groups (0.3k users) which doesn't have this "bug".

**Comment by pintassilgo** [comment]
Proof of this issue in a clean profile:
https://streamable.com/cl9ga

(P.S.: please ignore the title change above, it has nothing to do with the Tree Style Tab)

**Comment by Drive4ik** [comment]
fixed
browser.tabs.onUpdated.addListener filter changed props of tabs not working... again... :(
I had to roll back a little and return the `good old crutches`
thanks @pintassilgo
