### ISSUE TITLE
Implement tab hiding (API now available in Nightly)

### ISSUE THREAD

**Issue by koobs** [Drive4ik/simple-tab-groups#51]
A tab hiding API recently landed in [Bug 1423725](https://bugzilla.mozilla.org/show_bug.cgi?id=1423725) (subtask of [Bug 1384515](https://bugzilla.mozilla.org/show_bug.cgi?id=1384515))

It currently requires about:config -> _extensions.webextensions.tabhide.enabled_ being set to **true**.

This issue is to track the (feature) implementation of tab hiding/showing when switching tab groups

**Comment by iceflash** [comment]
There is a date in which version will include this API in stable?

**Comment by koobs** [comment]
See [Mozilla Release Calendar](https://wiki.mozilla.org/RapidRelease/Calendar)

**Comment by ScottRFrost** [comment]
[Conex by Kesselborn](https://github.com/kesselborn/conex) has tab hiding now (with the about:config flag) if you'd like to review how he did it.

**Comment by Drive4ik** [comment]
See #2 
discussion will be there
