### ISSUE TITLE
No way to restore backups

### ISSUE THREAD

**Issue by Ayayaye** [Drive4ik/simple-tab-groups#510]
**Describe the bug**
I lost all my tabs, and even the pinned ones. All the groups were listed, but with no tabs in it. I have an auto-backup that seems ok but there's no way for me to restore it. I tried to delete the wrong ones (there was two auto-backups with the groups but no tabs in it) and restart Firefox, but it didn't load the tabs. I looked the wiki page where there is a video who show how to reload but my stg "menu" don't have the button "reload" that is shown on the video. I tried to uninstall/reinstall the add-on, but the button didn't show up, and I lost all my groups. I'm new to github so I don't really know what to do (I tried to look at other issue but I didn't really see the same problem, or something I could try)

**Screenshots**
<a href="https://zupimages.net/viewer.php?id=19/01/c6rg.jpg"><img src="https://zupimages.net/up/19/01/c6rg.jpg" alt="" /></a>

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Firefox version: 71.0
 - Simple Tab Groups version: 4.3.6.2

**Additional context**
I'm not sure if the issue is linked to the update of firefox or to a long use of "private mode" (where stg is disabled)

**Comment by C-Meinert** [comment]
To restore a backup you will need to go to the add-on settings.

1. Click the "Gear" icon from the STG menu
2. Select the "Options" tab
3. Select the "Backup your simple tab groups"
4. There will be a section titled "Restore Simple Tab Groups from backup"
5. Click the button and select the backup you want to restore

**Comment by Ayayaye** [comment]
Thanks a lot ! I was wondering why I don't have the button directly in the STG menu and didn't really thought there would be another way to restore backups...
