### ISSUE TITLE
STG unusable after upgrade to Firefox 71

### ISSUE THREAD

**Issue by TheWanderer2020** [Drive4ik/simple-tab-groups#511]
Having a MAJOR problem with this it is now completely unusable !!!

I open Firefox and although all the groups are there they all have 0 tabs.
Ever single tab is in the hidden unsynchronized tabs section (I started out with around 200 tabs and 15 Tab groups.) Before updating Firefox this worked perfectly :)
If I put ONE tab back into it's right group and then open it ALL the other tabs are also transferred into the same group.
If I then close and reopen Firefox ALL those tabs are once again back in hidden tabs and all groups are once again are empty... but it gets even worse ALL the tabs are then also duplicated so now I have over 400 tabs (2 of each). If I then do it again the same happens now I would have over 800 tabs an so on... at one point while trying to figure this out I ended up with over 4000 !!! tabs in the hidden unsynchronized tabs section

Hopfully this is just some setting somewhere ?
or will be fixed soon ?

Firefox 71.0(64-bit)
Windows 10 Pro 10.0.18362
Simple Tab Groups 4.3.6.2

**Comment by charlesb-yesmail** [comment]
I'm also seeing this behaviour with Firefox 72.0.1 & STG 4.3.6.2 but on MacOS10.14.6.

> I open Firefox and although all the groups are there they all have 0 tabs.
> Ever single tab is in the hidden unsynchronized tabs section (I started out with around 200 tabs and 15 Tab groups.) Before updating Firefox this worked perfectly :)

I haven't tried doing this - it sounds too scary! :-)

> If I put ONE tab back into it's right group and then open it ALL the other tabs are also transferred into the same group.
> If I then close and reopen Firefox ALL those tabs are once again back in hidden tabs and all groups are once again are empty... but it gets even worse ALL the tabs are then also duplicated so now I have over 400 tabs (2 of each). If I then do it again the same happens now I would have over 800 tabs an so on... at one point while trying to figure this out I ended up with over 4000 !!! tabs in the hidden unsynchronized tabs section

STG is a really important part of my Firefox workflow ( I have about 40 groups holding over 1200 tabs) so a quick fix would be much appreciated if at all possible.

**Comment by suntzuisafterU** [comment]
Firefox 72.0.1 on MacOS10.13.6, same issue.

**Comment by suntzuisafterU** [comment]
Simple tab groups is also a core part of my firefox workflow.  Honestly this should become a builtin feature, it is just so much more useful than bookmarks etc.

**Comment by BenjamenMeyer** [comment]
@suntzuisafterU  it was a built-in feature starting with FF4 - originally called Panorama, later renamed to Tab Groups, and then later moved to a plugin. The FF devs dropped support for their extension a while back. Others picked up the ball. Then the XUL to WebExtensions stuff hit and blew everything to shreds. STG is one of the few that survived after several convinced the FF devs to add the requisite APIs into WebExtensions - of course, even that took time; the issue was raised before WebExtensions was released but it took until several releases of FF after XUL was dropped to get the APIs in.

Any how... enough history - it's just that. Looking forward to the greatness that is STG. ;)

**Comment by suntzuisafterU** [comment]
@BenjamenMeyer I'm glad someone is there and willing to pull STG through.

So,
Firefox 72.0.1
Windows 10
STG 4.3.6.2 (same as my mac)

And STG works with this configuration.

**Comment by charlesb-yesmail** [comment]
> I'm also seeing this behaviour with Firefox 72.0.1 & STG 4.3.6.2 but on MacOS10.14.6.

> STG is a really important part of my Firefox workflow ( I have about 40 groups holding over 1200 tabs) so a quick fix would be much appreciated if at all possible.

I have managed to work around the issue by creating a new profile in Firefox.  I was able to copy all the important stuff I wanted to keep to the new profile by following these instructions:

http://kb.mozillazine.org/Transferring_data_to_a_new_profile_-_Firefox

After creating the new profile I re-installed STG and my other extensions (one thing you shouldn't is copy extensions from one profile to another) and restored a previous backup of STG to get back the groups, etc.   So far, after a few days, everything is working fine with no problems.

**Comment by suntzuisafterU** [comment]
After changing nothing on my Mac (
Firefox 72.0.1
MacOS10.13.6
STG 4.3.6.2
)
everything seems to be working again, although I did not bother restoring my old tabs.

Problem solved, for me at least.

**Comment by TheWanderer2020** [comment]
Seems something has changed... update to Firefox 72.0.2

Groups tabs no longer go to 0, they seem to stay correct... with the following exception!

I have created a new group for this test with just a google search page as the only tab in it.

Make sure to close Firefox while that group is selected.

Open Firefox, Firefox opens and looks correct for a split second firefox will then restart and that is when it all goes wrong. 
(Don't know why Firefox restarts though???)

It is then that the open group (1 Tab) then has every other tab added to the open group, 
look at the SGT menu and it still show just 1 tab for the group, open that group and it appears that a copy of ALL other tabs are then added to that group... group now has 195 tabs!!!

But it seems that if before opening that group I close all these tabs from the SGT menu Show other tabs then open the group it only opens the 1 tab, and then sgt seems to behave correctly... until I close Firefox that is.

**Comment by Drive4ik** [comment]
@TheWanderer2020 Please do the following:
Create a backup of the STG (in the STG settings) when you says that STG works correctly.
Check this backup file so that all your tabs and settings are there
Uninstall addon -> Restart browser -> Install STG and restore backup from file

Everything should return to normal operation.
Many people have problems with Firefox 71, even without STG addon ...

If this does not help - only one option - a new clean profile.

**Comment by nekohayo** [comment]
As we haven't heard from this in months, and personally I'm not encountering issues even with Firefox 77, maybe this should be closed? I'm suspecting if it was still a problem in recent Firefox versions there would be new people commenting on this bug since February...

**Comment by gkaklas** [comment]
I agree; I haven't encountered any problems either, with Firefox 79 :thinking: 

@TheWanderer2020 do you still have this issue, can this be closed?
