### ISSUE TITLE
"New tab" button in list view of Mange groups window is hard to see

### ISSUE THREAD

**Issue by e2e8** [Drive4ik/simple-tab-groups#512]
**Problem**
The "Open new tab" button in the list view of the Mange groups window is not distinct enough from the list of tabs. It looks too much like another tab item in the list.

**Solution**
Change the styling or location of the "new tab" button in the list view.

Here is a minimal change that accomplishes the goal. PR: #513 
Another possible solution would be to move it to the header or footer of the box.
![sample1](https://user-images.githubusercontent.com/1097356/72045759-e2c73780-3284-11ea-8ec0-0bf71f791dbb.png)

**Comment by Drive4ik** [comment]
Done. Update will available on next release)
