### ISSUE TITLE
Backup rotation.

### ISSUE THREAD

**Issue by 532910** [Drive4ik/simple-tab-groups#514]
Please add support for backup files rotation, as right now it grows infinitely and so is not usable.

**Comment by kssi** [comment]
+1

I had to write a Bash script to achieve this. From my experience, hourly backups from the last 2 days or so are the most useful.

Not sure the Firefox addon API would allow file deletion though.

**Comment by Drive4ik** [comment]
Hi all.
Unfortunately, this is not possible when working with files. WebExtensions API does not allow to delete any files that are not downloaded by this addon
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/removeFile

There is only one not so good idea.
For example, it's February. I want to delete all January backups. I can make a list of files by day:

1. `stg-backup-2020-01-01@drive4ik.json`
2. `stg-backup-2020-01-02@drive4ik.json`
3. `stg-backup-2020-01-03@drive4ik.json`
4. `stg-backup-2020-01-04@drive4ik.json`

...

Make a download of each of this empty file and rewrite it, and then as I have the download ID I can delete them. Thus delete the backup files. 
But this is a very bad idea, as Firefox devs will not allow it. And I completely agree with Firefox devs.

I myself have a lot of such backups, I have to remove it with my hands.
By the way, I changed the name of the folder for backups, and now if it has not been changed by the user, different versions of Firefox will have a different backup folder. For example

- STG-backups-FF-72.0
- STG-backups-FF-73.0
- STG-backups-FF-74.0a1

Firefox is updated approximately once a month, so these folders will be different for each version of Firefox and if the user has not changed the format of the folder name.
https://wiki.mozilla.org/Release_Management/Calendar

**Comment by 532910** [comment]
so
1. At least you should add a big warning to remember users delete backups.
2. backups should be disabled by default

**Comment by Drive4ik** [comment]
1. As for the "Big warning" this will definitely not be, but I will make a mention in the backup section.
2. I do not agree.

**Comment by 532910** [comment]
2. It means wasted disk space for every people who installed this addon and didn't not pay attention to this default.

I believe more than 90% of STG users don't know about this.

Programs must not store files infinitely.

**Comment by Drive4ik** [comment]
I understand you. And I know that this is not the best option. But, what’s better - to delete the file folder once every half a year, or not to be able to recover when everything broke at a time (and this most often happens) ...?

You can disable this checkbox
![изображение](https://user-images.githubusercontent.com/7843031/74148478-31624b80-4c0e-11ea-98e8-19086f1c0669.png)
And data will take up less space.
As I already wrote, the API does not have such an opportunity.
Backups for that and backups, and they must lie far from a working system in order to recover data when this system crashed. Otherwise, backups will be broken if they are in the addon database, not files.

**Comment by 532910** [comment]
> You can disable this checkbox

It's not about me or STG options. It's about regular users, who never open any settings. From their point of view it's unwanted garbage, the existence of which they do not even know and that will never be removed.

The better is to make backups disable by default and offer to enable it after installation.
BTW do you know any other software that has backups enable by default?

**Comment by Drive4ik** [comment]
> It's not about me or STG options. It's about regular users, who never open any settings. From their point of view it's unwanted garbage, the existence of which they do not even know and that will never be removed.

I agree with you that users rarely open settings and have little understanding. I’ll think about how to notify the user about backups.

> BTW do you know any other software that has backups enable by default?

Yes) Firefox:
![изображение](https://user-images.githubusercontent.com/7843031/74235911-bb76e680-4cd8-11ea-94f7-9a172a7bfff4.png)

![изображение](https://user-images.githubusercontent.com/7843031/74236025-f6791a00-4cd8-11ea-88b9-d6a30979beaf.png)

![изображение](https://user-images.githubusercontent.com/7843031/74236051-ff69eb80-4cd8-11ea-8780-d650dc9907e4.png)

**Comment by 532910** [comment]
> Yes) Firefox:

There are two huge differences:

1. they are rotated.
2. will be removed together with firefox

**Comment by 532910** [comment]
> I’ll think about how to notify the user about backups.

OK!

**Comment by Drive4ik** [comment]
> 
    they are rotated.
    will be removed together with firefox

Yes, but addons do not have such functionality. It is specially made for safety.

Here's an example of a similar case.
The user asked to make an addon similar to this:
https://chrome.google.com/webstore/detail/simpleextmanager/kniehgiejgnnpgojkdhhjbgbllnfkfdk

Maybe I would have done in my free time, but FF has limitations:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management

![изображение](https://user-images.githubusercontent.com/7843031/74242255-37c3f680-4ce6-11ea-9d3b-3db56bf97703.png)

even getting a list of all installed add-ons is impossible...
This happens very often. Maybe this functionality will change or supplement in the future.
And in part I agree with the developers. 

P.S. I have one idea. But it is so bad that FF developers will not miss it. I don’t even want to tell her.
It remains to wait for additions to the FF API.
