### ISSUE TITLE
Add functionality to close all tabs in a tab group

### ISSUE THREAD

**Issue by flexibeast** [Drive4ik/simple-tab-groups#515]
At the moment, in order to close all tabs in a group, i delete the group, then re-create it.

What i would like to be able to do instead is click on a icon to close all the tabs in a particular group. For example, the icon might be located in-between the 'group settings' icon and the 'delete group' icon.

Thanks for your work on STG!

**Comment by Drive4ik** [comment]
Hi! You can do this - hold down the Shift key and select the first tab of the group, scroll down and select the last tab of the group also with Shift held. Then press the right button on the selected tabs (context menu) and press the "delete tab" button.

**Comment by flexibeast** [comment]
Oh neat! Thanks for that. :-) Closing.
