### ISSUE TITLE
New Feature: Scroll mouse on Add-On icon to change Between Groups

### ISSUE THREAD

**Issue by szhatef** [Drive4ik/simple-tab-groups#516]
Dear Developer,

It would be very handy if we can go forward and backward through the groups just by scrolling on Add-On icon by scroll button of the mouse.

**Comment by Drive4ik** [comment]
Hi @szhatef ! 
I have already been asked about this functionality, but unfortunately the Firefox WebExtensions API does not have such functionality. All you can do with this icon:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction#Functions
