### ISSUE TITLE
Searchable Group-Picker

### ISSUE THREAD

**Issue by pibebtol** [Drive4ik/simple-tab-groups#517]
**Is your feature request related to a problem? Please describe.**
I'm always a little bummed when I have to go through the list of tab groups when I want to switch to another group in the select group mode of the "Load custom group"-window or the "Move active tab to custom group"-window.

**Describe the solution you'd like**
I'd like to be able to search for the group name. (Maybe even for tabs within groups)

**Describe alternatives you've considered**
Use the extension popup (default upper right) and make it accessible via shortcut.
(I even think, that this was possible some time ago, but I can't find the shortcut to open the pop up.)

**Comment by Drive4ik** [comment]
Regarding the search, I’ll think about how to do it, but later.
Addon hotkeys you can set here
![изображение](https://user-images.githubusercontent.com/7843031/72989365-c71c6f00-3df6-11ea-9883-d2a1618c2d42.png)
and here
![изображение](https://user-images.githubusercontent.com/7843031/72989426-e87d5b00-3df6-11ea-98bc-6710b627b3fa.png)

**Comment by grahamperrin** [comment]
> … able to search for the group name. (Maybe even for tabs within groups) …

This is implemented: 

![image](https://user-images.githubusercontent.com/192271/108648293-c7cc7c80-74b2-11eb-9ff1-e2a8fdb69a6f.png)

**Comment by pibebtol** [comment]
Thanks for the heads up 👌
