### ISSUE TITLE
Feature Request: easy way to rename groups

### ISSUE THREAD

**Issue by BurntBrunch** [Drive4ik/simple-tab-groups#518]
I like to keep my tab groups named by project/focus area. Unfortunately, it's currently pretty cumbersome to set the group name. The two ways I know of are:

1. Toolbar button -> right click group -> group settings -> change the name
2. Manage groups keyboard shortcut -> wait for it to load (it takes a bit) -> change name

It would be great if "set group name" or "open current group settings in the toolbar pane" were actions I could assign keyboard shortcuts to. Alternatively, "add new group" could prompt for a name instead of using numbers in the name.

Overall, while I enjoy having this extension, it's not currently possible to create keyboard shortcuts that encompass the complete browsing experience. Reaching for the mouse prevents me from _loving_ this extension.

**Comment by Drive4ik** [comment]
I added prompt for new group mane in popup in tab (move tab or load group)

**Comment by Drive4ik** [comment]
Hi @BurntBrunch ! I added rename selected group in popup by F2 key. Feature will be in next release

**Comment by Drive4ik** [comment]
Done. Please wait next addon release

**Comment by BurntBrunch** [comment]
Thank you, this is much appreciated! :grin:
