### ISSUE TITLE
Discard group not working 

### ISSUE THREAD

**Issue by tuxayo** [Drive4ik/simple-tab-groups#519]
**Describe the bug**
Discarding a group doesn't seem to be effective. It should close the window of the said group right? 

**To Reproduce**
1. click the STG add-on button next to the search field in the FF UI
2. choose an opened group
3. discard
4. nothing seems to happen 

**Desktop (please complete the following information):**
 - OS and version: EndeavourOS (very close to Arch Linux)
 - Firefox version: 73.0b7 dev edition
 - Simple Tab Groups version: 4.3.6.2

**Additional context**
Doing this from the windows/group to be discarded or from another one chances nothing.
Firefox restart changes nothing

Logs don't seem to indicate any error.
[STG-error-logs(1).json.txt](https://github.com/Drive4ik/simple-tab-groups/files/4089902/STG-error-logs.1.json.txt)

**Comment by tuxayo** [comment]
Anything else I can do to get more info?

**Comment by tuxayo** [comment]
Discard other groups doesn't work also.

Discarding a new group with one tab doesn't work also.

**Comment by Drive4ik** [comment]
Hi! Discard group will only unload all tabs (from memory RAM) in this group, not close tabs or close windows.
User can close the window by himself.

**Comment by tuxayo** [comment]
My mistake, I though that was the way of closing a window without loosing the tabs.

When wanting to close a window, Firefox warned that it would close more tabs that the currently shown in this group. So I assumed that even if the group shown in the window would be preserved, there would be collateral damage to other groups.

But it's not the case, it's working perfectly :D
Thanks, now I have more than 20 groups and a lot of RAM saved thanks to STG <3

**Comment by tuxayo** [comment]
So I finished my cleanup and have only one window now.
Maybe I just lost the one tab that was out of a group when closing the other group windows. But I'm not sure.
Anyway, I'll do everything in groups now :)

**Comment by Drive4ik** [comment]
@tuxayo The addon has a mechanism for saving tabs when closing a window. That is, for example, you have window ID 1 and window ID 2. In window 2, you have 3 groups of 10 tabs open, that is, you have one group and its 10 tabs active, and the other two groups are hidden, but are in window 2. If you close window 2, the tabs will indeed close, but the addon will create copies of these tabs in window 1. And it will place these 30 tabs in the desired groups.
