### ISSUE TITLE
Group Icon resolution

### ISSUE THREAD

**Issue by reuy** [Drive4ik/simple-tab-groups#520]
**Describe the bug**
When manually assigning a png file as a group icon, the result will be grainy and blurry.

By contrast, when you load that exact same png file into an HTML document as a Favicon, load the resulting HTML document as a tab, and then click "set tab icon as group icon" the resulting group icon has perfect resolution.

**To Reproduce**
1. Go to manage group tabs
2. Click the gear icon on any given group
3. Load an image you would like to have as the group's tag

**Expected behavior**
Uploading an image via direct upload should have equivalent, if not better, quality than selecting a website's favicon.

[**Screenshots**](https://ibb.co/dmKLSXR)

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Firefox version: 72.0.2 
 - Simple Tab Groups version: 4.3.6.2

**Additional context**
I used a fairly simple icon, but this difference becomes dramatically worse the more complex the icon in question is.

**Comment by Drive4ik** [comment]
Fixed. I change size icon from 16px to 64px
before:
![Screenshot_5](https://user-images.githubusercontent.com/7843031/73359919-92069580-42aa-11ea-9c90-4c1e1d4827a9.jpg)
after:
![Screenshot_6](https://user-images.githubusercontent.com/7843031/73359934-96cb4980-42aa-11ea-9040-b2388544ada4.jpg)
