### ISSUE TITLE
Feature Request:  Can exporting a group to bookmark completely replace the contents of that bookmark folder?

### ISSUE THREAD

**Issue by okumam** [Drive4ik/simple-tab-groups#521]
If you have a bunch of tabs in a group and export it to a bookmark folder for the first time, you get those tabs in a folder as you would expect.  However, if you continue browsing, closing many of the tabs from before and opening some new ones, exporting to the same bookmark folder keeps the old tabs in that folder that are no longer open.  You do get a separator to indicate where the old stuff begins, but the folder keeps growing.

Is this because maybe addons are not allowed to delete bookmarks?  Is it possible to have an option to completely overwrite the contents of the bookmark  completely so we don't have to go in and manually delete all the now obsolete tabs from the bookmark folder?

The exporting is a great way to deal with a  group of tabs that you will put away for a while, but will want to return to.  It's just that when you return to it and open/close a bunch, the second and subsequent exports become messy.

Thanks for the great addon.  I was still on FF 56 because of tab groups.  This allowed me to upgrade!

**Comment by Drive4ik** [comment]
done.
You need to disable option `Leave bookmarks of closed tabs` in addon settings after update addon in next release.

**Comment by okumam** [comment]
Thanks so much!  I can't tell you how much I appreciate your work.
