### ISSUE TITLE
Reseting the Group Counter

### ISSUE THREAD

**Issue by sikmo** [Drive4ik/simple-tab-groups#522]
When having STG automatically create groups whenever a windows is opened, it can reach a high number of groups. Even after renaming, deleting or discarding previous groups, the counter only increments from there. 

It would be nice if STG checks if any currently saved group has a title with the format "Group [number]" and just increments on that rather than following a global counter. Alternatively, if there's a way to reset the counter manually.

**Comment by Drive4ik** [comment]
Unfortunately this is not possible. Since this counter affects many parameters, it is also taken into account when restoring backups.
