### ISSUE TITLE
Error while assigning tab group to container

### ISSUE THREAD

**Issue by marinier** [Drive4ik/simple-tab-groups#523]
**Describe the bug**
While assigning a tab group to a container, the plugin started popping up notifications to save the logs and send them to the author. As I continued to use firefox, the popups became very frequent, such that the entire right edge was filled with them.

**To Reproduce**
I don't have real reproduction steps, but I can give more info about what I was doing.

I was in the process of assigning several tab groups to containers. This was the last one (the others had been fine), and unlike the others, I had to define a new container. In the manage groups tab, I then selected both "Catch and move tabs with containers to this group" and "Always open tabs in container" to the new container (which has the same name as the group).

Also note that, after restarting FF and looking at the settings for that group again, I realized that the UI was not rendering properly before -- none of the radio buttons or checkboxes had appeared in the settings dialog, but they are there now. So perhaps something else was in a bad state.

**Expected behavior**
No errors :)

**Desktop (please complete the following information):**
 - Windows 10.0.18363 Build 18363
 - FF Version: 72.0.2 64-bit
 - Simple Tab Groups version: 4.3.6.2

**Additional context**

[STG-error-logs.zip](https://github.com/Drive4ik/simple-tab-groups/files/4117661/STG-error-logs.zip)

**Comment by Drive4ik** [comment]
Try restarting your browser. This error occurred when you added a container to the tracking group and then deleted this container, but the addon did not receive notification about this from the browser. Therefore, this error arose.

**Comment by marinier** [comment]
Everything seems fine after a restart, so I'll close the issue. If it comes up again, I can repost. Thank you for taking a look!
