### ISSUE TITLE
Feature Request: Some keyboard control improvements.

### ISSUE THREAD

**Issue by Foldex** [Drive4ik/simple-tab-groups#524]
**Is your feature request related to a problem? Please describe.**
I'm using the search feature of the F8-popup a fair bit, but hitting Enter while the search box is focused doesn't seem to do anything. If I want to swap to a tab/group using the popup, I have to search, tab twice, and then hit enter. It's a minor thing, but feels unnatural.

Additionally when you open the "Load Custom Group" popup, but decide you don't want to switch groups, you have to click outside of the popup to close it.  Seems unintuitive to have to use the mouse to close it, when it is opened with the keyboard.

**Describe the solution you'd like**
Enter on the F8 popup searchbox should open the current top result.
Escape should close the "Load Custom Group" popup.

**Describe alternatives you've considered**
Maybe using the "Load Custom Group" shortcut would toggle the popup if it is active.

**Comment by Drive4ik** [comment]
> If I want to swap to a tab/group using the popup, I have to search, tab twice, and then hit enter. It's a minor thing, but feels unnatural.

Added select first tab by Enter or group if no tabs found by search

> Escape should close the "Load Custom Group" popup.

It works now - Esc closes the popup window with the groups in the tab (move tab or load custom group popup)
What version of browser and addon are you using? And what is your OS?

**Comment by Foldex** [comment]
> Added select first tab by Enter or group if no tabs found by search

Thanks!

> It works now - Esc closes the popup window with the groups in the tab (move tab or load custom group popup)

Oops, looks like the problem was that tridactyl conflicts with the escape binding. Would the toggle idea for the prompt shortcut still work?

**Comment by Drive4ik** [comment]
> Would the toggle idea for the prompt shortcut still work?

I do not quite understand what you are talking about. Can you explain in more detail?
