### ISSUE TITLE
Allow to use same container for multiple groups

### ISSUE THREAD

**Issue by eduardoweiland** [Drive4ik/simple-tab-groups#525]
**Is your feature request related to a problem? Please describe.**
I would like to use the option "Always open tabs in container" using the same container for different groups. Currently, if the container is already assigned to one group, I can't select it again for a different group (the option is disabled).

I want to use this extension to group tabs that I use for work: one group for code review, another one for testing, others for research and development of new features. All of these groups should use the same container "work", so I don't need to login to the websites I use (like GitHub) on every group.

**Describe the solution you'd like**
Allow to use same container for multiple groups.

**Describe alternatives you've considered**
- Use an anonymous container and login to websites on every new group I open (but that's annoying);
- Use a single group for work tabs (but then there is no need for this extension)

**Additional context**
Nothing

**Comment by Drive4ik** [comment]
Done.
