### ISSUE TITLE
Make tab and group management with keyboard only

### ISSUE THREAD

**Issue by pietrodito** [Drive4ik/simple-tab-groups#526]
**Is your feature request related to a problem? Please describe.**
A) I want to be able to name a created group without using the mouse.
B) I want to be able to assing new shortcut to send tabs to this newly created group without the mouse.

**Describe the solution you'd like**
A) One could use F2 to rename groups inside F8 popup menu.
B) After choosing a default modifier keys in add-on preferences (eg `<CTL>+<SHIFT>`), one could go in F8 popup menu and when a group is selected hit `q` (choose shortcut) then the desired shortcut key (eg. `1`). Eventually, `C-S-1` is now the shortcut to send tab to the group.

**Describe alternatives you've considered**
None

**Additional context**
I think your work is great

**Comment by Drive4ik** [comment]
I can’t understand what exactly you want. You can open a popup, select a group or tab and move it to the desired group through the context menu. And all this only from the keyboard.
Also in the new version it will be possible to set the group name in the popup that opens in the tab (popup like: `move active tab to group` or `load custom group`).

**Comment by Drive4ik** [comment]
like #518

**Comment by pietrodito** [comment]
A) Name groups : prompt at group creation will be great as you said in [#518](https://github.com/Drive4ik/simple-tab-groups/issues/518)
A') Rename group in popup menu with F2 would be great also.

B) I want to be able to assing new shortcuts of type `move active tabs to custom group` wihtout the mouse or entering addon settings menu. Please read again my original message.

**Comment by pietrodito** [comment]
I think your extension is great, so great that it is the only `software` on my computer that makes me use the mouse... I will love to be able to reorganize tabs in groups wihtout the mouse. Thanks you again for your work.

**Comment by pietrodito** [comment]
About creating a new group:

I think that common workflow will be:

1) Open new tab
2) Access url with new topic
3) Create a new group

Maybe `create a new group` action could add the current tab into the new group as default

**Comment by Drive4ik** [comment]
Done. Please wait next addon release
