### ISSUE TITLE
how to load only tabs in an active group upon FF start? 

### ISSUE THREAD

**Issue by az-z** [Drive4ik/simple-tab-groups#527]
Hello,
 this addon is excellent. Hats off to the developers. thank you!

One question - is it possible to load only tabs in the current (active?) group upon FF start?

I have about 88 tabs across 10ish groups. And it _appears_ ( i maybe incorrect) that FF loads all 88 of them when it starts which takes time. It would be nice to have current tabs loaded on start and the rest when i switch on that group.

this is just a suggestion/question.

**Comment by Drive4ik** [comment]
Hi!
What do you mean by loading a tab?
It’s just that the FF tabs have several states

- tab exists - tab content loaded
- tab exists - tab content not loaded (tab discarded)
- tab exists and hidden - tab content loaded
- tab exists and hidden - tab content not loaded (tab discarded)
- tab not exists - tab not exists in addon too (maybe tab was saving in browser session as closed)

By default, when the browser starts, it does not load all the tabs, it opens them, but the content itself does not load. Content will only load when you click on the tab.

If you have the content of all the tabs loaded when you open the browser and not just the active tab, then you need to switch a certain option in the browser settings.

**Comment by az-z** [comment]
> By default, when the browser starts, it does not load all the tabs, it
opens them, but the content itself does not load. Content will only load
when you click on the tab.

Perfect. That is exactly what i want .

>If you have the content of all the tabs loaded when you open the browser
and not just the active tab, then you need to switch a certain option in
the browser settings.

How do i check the setting in the latest firefox?

**Comment by Drive4ik** [comment]
Try to make a new Firefox profile, install the STG addon, make a backup import and try to replicate your problem.

Check, here the value should be `true`

option: `browser.sessionstore.restore_on_demand`

![изображение](https://user-images.githubusercontent.com/7843031/73852693-4fa80000-4838-11ea-874f-3c1eb9cb68c0.png)

**Comment by HASJ** [comment]
You can use the Auto Tab Discard extension.

**Comment by az-z** [comment]
Oh, sorry, i forgot to reply to this.
The delay is not because of the extension, but because of the time it takes
to load (connect to site, get data) the first (active) page.
Awesome extension. Thank you,  guys!
Please close as not an issue.
