### ISSUE TITLE
STG slow to open with FF 72.0.2

### ISSUE THREAD

**Issue by Russ95501** [Drive4ik/simple-tab-groups#528]
Running FireFox 72.0.2 with several tab groups.  Recently it has been taking over a minute before STG is done initializing after FF has launched.  High CPU and memory utilization during the startup.  I use STG with FireFox on several computers and it is the same on each.

**Comment by Drive4ik** [comment]
What is your OS? And how many tabs do you have in groups?

**Comment by Russ95501** [comment]
Good afternoon,
I have a Windows 10 computer (latest build) with 16Gb of RAM as well as a Linux VM (VMware) with 6Gb (was originally 4Gb) of RAM on another PC.  
I normally run about 140-150 tabs (yeah, that's a lot).  But, it hasn't been a big issue until recently.  I just timed the Linux VM and it took almost 10 minutes to finish loading (9:45).  During startup, the CPU and RAM usage spikes up so I thought it might be a RAM constraint.  Since I had more control of the VM, I upped it from 4Gb to 6Gb and there was no significant change in the load time.
I went through my tabs and closed down a whole bunch on my VM.  Now I have 94 tabs which takes about 6 minutes to load (5:45).  That still seems like a long time to wait for STG to be done loading.  I am using the setting "Discard tabs after hide" to recover system memory and the memory usage does drop to a normal range once STG loads completely.  It's during startup that the memory and CPU usage goes way up.
In addition to STG, am running the following addons:  Adblock Plus, ColorfulTabs, LastPass, Resurect Pages, and X-Notifier Neo.
Russ Catalan 

    On Wednesday, February 5, 2020, 05:30:00 AM PST, Drive4ik <notifications@github.com> wrote:  
 
 
What is your OS? And how many tabs do you have in groups?

**Comment by Drive4ik** [comment]
Hi!
I do not quite understand how an addon can load 10 minutes. Even with 1000 tabs, Firefox will load longer than the addon ..
Can you take a screenshot of exactly how the browser, and add-on, or record video (not necessarily all 10 minutes)?
like this app
https://www.screentogif.com/

Also, you can try to disable other add-ons, and check how the STG works? Maybe he has a conflict with another addon.
For example, such a conflict of addons. Also there was a long load of the addon:
https://github.com/Drive4ik/simple-tab-groups/issues/393

**Comment by Russ95501** [comment]
After reading the link you included, I disabled Adblock Plus.  Now Firefox is ready in 13 seconds.  I will be contacting the Adblock Plus devs to resolve the issue.  Thank you so much for helping me and steering me in the right direction!
Russ Catalan 

    On Thursday, February 6, 2020, 05:57:33 AM PST, Drive4ik <notifications@github.com> wrote:  
 
 
Hi!
I do not quite understand how an addon can load 10 minutes. Even with 1000 tabs, Firefox will load longer than the addon ..
Can you take a screenshot of exactly how the browser, and add-on, or record video (not necessarily all 10 minutes)?
like this app
https://www.screentogif.com/

Also, you can try to disable other add-ons, and check how the STG works? Maybe he has a conflict with another addon.
For example, such a conflict of addons. Also there was a long load of the addon:
#393

**Comment by Drive4ik** [comment]
Better use `uBlock Origin`, it is much faster and more stable. I have been using it for a long time and there are no problems.
A worthy replacement `Adblock Plus`
https://addons.mozilla.org/firefox/addon/ublock-origin/

**Comment by Russ95501** [comment]
I just switched and it works great.  Thanks!
Russ Catalan 

    On Thursday, February 6, 2020, 10:17:05 AM PST, Drive4ik <notifications@github.com> wrote:  
 
 
Better use uBlock Origin, it is much faster and more stable. I have been using it for a long time and there are no problems.
A worthy replacement Adblock Plus
https://addons.mozilla.org/firefox/addon/ublock-origin/
