### ISSUE TITLE
Load last open group on firefox start

### ISSUE THREAD

**Issue by thevladsoft** [Drive4ik/simple-tab-groups#53]
With the old tab groups addon and using firefox's option to load last open tabs on start, it opened the last open group too.

With simple tab group (in firefox 58), that option will show you the tabs from the last open group alright, but if you open a new tab it won't be recognized in any group. Also, by selecting the group that should have been open, a new window with the same tabs will appear, making me think no group was opened to begging with.

In this moment the solution is to open firefox, load the group and close the initial window so there aren't repeated tabs.

Wonder if this happens only to me?

(Great addon, by the way. This is the last thing preventing me to finally update my firefox.)

**Comment by SladeThe** [comment]
Confirmed. If you restart the Firefox, restored tabs are no longer associated with any of addon groups. You should manually reload the group.

**Comment by gaddman** [comment]
Does it look the same as issue #50 ?

**Comment by thevladsoft** [comment]
gadddman a think is the same. By the title I didn't thought it was the same, so opened a new one. My mistake. But I think I noticed the problem was the group not being loaded at all.

I can think of a **very hacky** way to go around this:

   - To have an option to always load certain group, selected by the user. Lets call it "main"

   - When firefox start, automatically change to that tab, substituting the the initial tabs (indifferently if the user have the load groups in individual windows option activated or not).

Problems:
   
    - This must happen very early in firefox load. Possible?

    - What happens if the user deletes "main"?

**Comment by SladeThe** [comment]
My answer is yes. But I think that the problem of issue starter is more complex.

Probably he does not enable the "Open new windows in a new instead" option, while the addon relies on it in a some way.

**Comment by Drive4ik** [comment]
Please, retest this issue with latest addon version (2.3.1)

**Comment by thevladsoft** [comment]
It has the same behavior with 2.3.1

**Comment by thevladsoft** [comment]
Also, noticed if more than one window opens on firefox start, none will be really synced with their respective group.

**Comment by Drive4ik** [comment]
Please, re-test this issue in latest version v2.3.5

**Comment by thevladsoft** [comment]
A **fast** test with 2.3.6. it's close, but with faults:

    1. If I open only one group, close ff and restart it loads as it should.

    2. If open more than one and close each one by one (making sure ff is totaly closed in the end), restart will open the last closed window, with the group synchronized.

    3. But if i open several windows and close firefox with the hamburger menu (or pressing Ctrl-Q), It wont load the tab in restart, or only some of the loaded windows will be in sync. After that, it took closing and reopening ff some times (following procedures in 2 and 3) for the group loading working again.

Like I said is not a very complete test, but this version is very promising.

**Comment by Drive4ik** [comment]
@thevladsoft FF 57 and above has some bugs with tabs, see https://bugzilla.mozilla.org/show_bug.cgi?id=1435077
this issue has GIF, please see it

**Comment by Drive4ik** [comment]
@thevladsoft please read my comment https://github.com/Drive4ik/simple-tab-groups/issues/70#issuecomment-362435347
perhaps this issue blocks by https://bugzilla.mozilla.org/show_bug.cgi?id=1435077

**Comment by thevladsoft** [comment]
I see. Like I said, the latest version behaves neatly most of the time, so it is a matter of the user being cautious. 

Thanks for your work.

**Comment by Drive4ik** [comment]
Hi all!
Can you update to v2.4.1 and retest again?
I find some strange behavior and try to fix this issue.

**Comment by thevladsoft** [comment]
2.4.1 works the same for me.

**Comment by Drive4ik** [comment]
Hello!
I think I found the problem. it turned out this is not the clean-up behavior of firefox. eg
you have a synchronized group that has 3 tabs

- tab1
  - active: false
  - status: complete
  - url: URL_1

- tab2
  - active: true
  - status: complete
  - url: URL_2

- tab3
  - active: false
  - status: complete
  - url: URL_3

-------
but, if restart FF and on startup call "function get tabs" it returns there:
- tab1
  - active: false
  - status: complete
  - url: URL_1

- tab2
  - active: true
  - status: loading
  - url: about:blank (and at that moment load URL_2)

- tab3
  - active: false
  - status: complete
  - url: URL_3

sorry for my English))

this fix will be in next version 2.4.2

**Comment by thevladsoft** [comment]
I have to correct my last statement: with 2.4.1, if load tabs from last session is enabled, it works with about:... and local files open, even if those are not synced with the group. 

With 2.4.2, if I close using the menu, the group es recovered on restart. I think it's working pretty well right now.

**Comment by Drive4ik** [comment]
Hi all! Can you retest this bug in latest version of STG?
I found new bug in FF and try to fix it again))
