### ISSUE TITLE
Shortcut to open Popup with group expanded 

### ISSUE THREAD

**Issue by ww7** [Drive4ik/simple-tab-groups#530]
Feature to show list of current group tabs would be cool.
I think just Popup with current group expanded would be perfect. 
(Close popup after Tab changing optionally)

**Comment by Drive4ik** [comment]
Fixed small bug :)

In next release:
![firefox-show-active-group](https://user-images.githubusercontent.com/7843031/74148128-5acea780-4c0d-11ea-8e1f-26105f3e2a7e.gif)

**Comment by ww7** [comment]
Не принципиально, а можно отдельный хоткей который открывает раскрытой групу независимо от этой опции?

**Comment by Drive4ik** [comment]
К сожалению, нет.. потому как https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup требует прямого действия пользователя, а оно теряется на моменте передачи действия
