### ISSUE TITLE
Be able to cancel the automatic move of a tab to a new group

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#531]
When assigning a tab to a container (by using the Containerise addon for instance), the tab can move automatically to a defined tab group based on that new container. In that case, a notification can be displayed where one can click and go to the moved tab in the new group.

In some cases though, it could be useful to be able to manually cancel the move of the tab to the other group based on the container newly assigned to the tab (as long as the notification is being displayed, actually). Only the move itself, not the assignment to the new container.

The request is to add a clickable option to the "move" notification to "bring back" the tab to the current group after being moved based on newly assigned container, without altering the newly assigned container (and independently from the setting in #485).

Hope that is clear enough ;)

Thanks

**Comment by Drive4ik** [comment]
Hi!. This is difficult to do from several angles.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/NotificationOptions#Type

> Firefox currently: only supports the type, title, message, and iconUrl properties; and the only supported value for type is 'basic'.

![изображение](https://user-images.githubusercontent.com/7843031/74237321-f4648a80-4cdb-11ea-8d8c-32bdbd626561.png)

And secondly, when you press F5 on the canceled tab, the function for capturing tabs by url or container will work, and again transfer the tab. And if you later want to cancel the tab cancellation? difficult..

**Comment by klint** [comment]
Yes, I get the first point. Too bad but ok!
About the 2nd one, that is the deal with the autocapture feature, I know. And I don't press F5 too much on those tabs ;)
Thanks.

**Comment by Drive4ik** [comment]
It’s not even a matter of F5, even when you simply select a tab that is not loaded, it loads and this is the same F5.

**Comment by klint** [comment]
Yes, that is true, like when you restart the browser, isn't it? So,
anyway, my request had too manu holes around it actually, making it
rather unuseful ;)

**Comment by Drive4ik** [comment]
Ok, then i will close the ticket
