### ISSUE TITLE
When opening a new window, a random group is opened.

### ISSUE THREAD

**Issue by jtagcat** [Drive4ik/simple-tab-groups#534]
**Describe the bug**
Open a new window, STG has no group selected. ![image](https://user-images.githubusercontent.com/38327267/74580530-193b5500-4f9d-11ea-965d-dc6bec397d6a.png)

It opens the tabs of the first group (doesn't matter if I close them, close the 2nd window and open it again, they are there again).

I tried moving the tabs back to the first group, but now I have duplicate tabs in the first group.
**Expected behavior**
Open a new tab in the new window, remain groupless.
**Desktop (please complete the following information):**
 - OS and version: Fedora 31
 - Firefox version: 74.0b3
 - Simple Tab Groups version: 4.3.6.2

**Comment by jtagcat** [comment]
![image](https://user-images.githubusercontent.com/38327267/74611611-43a02600-50f5-11ea-8b8e-c2404ce30f61.png)
![image](https://user-images.githubusercontent.com/38327267/74611615-4f8be800-50f5-11ea-8577-2cbb7ecaa6f8.png)
I thought the tabs loaded were already closed in that group and no matter what I did, the exact same tabs opened.

I have a group named 'ExpNeu', all the tabs that opened were from this folder.

Nevertheless, this shouldn't happen.

**Comment by Drive4ik** [comment]
Perhaps this is a mistake. Can you please upgrade to the latest version of the add-on (4.4.2.4), enable the DEBUG mode in the add-on settings, do what you are talking about (open a window), turn off DEBUG and send me that log file?

**Comment by jtagcat** [comment]
> Perhaps this is a mistake. Can you please upgrade to the latest version of the add-on (4.4.2.4), enable the DEBUG mode in the add-on settings, do what you are talking about (open a window), turn off DEBUG and send me that log file?

The log would probably include personal information, where may I contact you?

**Comment by Drive4ik** [comment]
@jtagcat Please tell me what other addons do you have? If possible, take a screenshot. Because by the logs, I see that the tabs are created, but the addon can not do this. Tabs are created precisely, not transferred. The addon has only the option to create a new group when creating a new window. And this option is turned off for you.
Maybe another addon does it?

**Comment by Drive4ik** [comment]
And, please, take screenshot this page
![изображение](https://user-images.githubusercontent.com/7843031/75705117-63be1080-5cc3-11ea-8dd0-c905ed187017.png)

**Comment by jtagcat** [comment]
I think I found the cause:
![Screenshot from 2020-03-02 22-50-14](https://user-images.githubusercontent.com/38327267/75716742-b6013080-5cc7-11ea-96c2-5cf963989012.png)
Long list of URLs there. A better question is, how did they end up there (as I had Firefox Home as new tab). 
I have hourly backups going, after automatic cleanup, I have every-3-hourly backups from the day range it happened on. I can determine the exact date and go surfing in the backups if needed.

Tab-related add-ons I have: copy window urls, do not auto activate pinned tabs, firefox multi-account containers, open multiple urls, stg, tackup, temporary containers

When testing this fix, I also noticed a new (possible duplicate) (possibly too edge-case) (possibly conflict with do not auto activate pinned tabs extension) issue: with firefox's built in recover open tabs:
 - open a new window next to your normal stg-managed tabs
 - in that new window open something (or multiple tabs, to make it relevant for firefox to save)
 - close the stg-enabled window
 - close the 2nd window (exiting browser)
 - open browser, getting the 2nd window
 - in that window, open the same group you had opened in the stg-enabled window
 - open a new window (you get the old stg-enabled window with tabs, but without the stg group (so groupless))
 - close everything in that window (not the window)
 - (finally, the bug) after closing the last tab, a new tab will be opened, the tab will be from one of your groups, it will take the first one from your groups (so first tab is from the first group, second is from the second group, first and second is order of group creation); expected: tab closes and window closes

**Comment by Drive4ik** [comment]
@jtagcat I fixed this bug in latest addon version, please check
