### ISSUE TITLE
New Tab gets moved 

### ISSUE THREAD

**Issue by jolau** [Drive4ik/simple-tab-groups#536]
When I open a new tab (i.e. CMD+T), the blank tab gets first opened right next to the previous one - as expected. But as soon as I open a website, the tab gets moved two positions to the right. This happens only if the "Always open tabs in container" is activated (resp. is set to something different than "default").

I've already reset Firefox without any improvement.

Firefox 73.0.1 (64-Bit) on macOS 10.14.6 (18G3020)
SimpleTabGroups version 4.3.6.2

**Comment by Drive4ik** [comment]
A tab with a new container should open at the place of the tab without a container, or with a different container (if this option is specified). I do not have a Mac, and I can’t check the work on it. Perhaps you have other add-ons that can manage tabs with containers, Firefox Multi-Account Containers or Facebook Container? Then there may be conflicts with these addons

**Comment by jolau** [comment]
AFAIK I don't have such an addon - here is the list of installed addons:
![grafik](https://user-images.githubusercontent.com/1056376/75427356-a213a280-5946-11ea-9ef5-902b110e8d59.png)

**Comment by Drive4ik** [comment]
Disable this addon `Open Tabs Next to Current` and try again

**Comment by Drive4ik** [comment]
And please, update STG addon to latest version
