### ISSUE TITLE
Tabs get duplicated

### ISSUE THREAD

**Issue by fjssilva** [Drive4ik/simple-tab-groups#537]
All tabs get duplicated after opening Firefox. I did a backup of my session with multiple groups and hundreds of tabs, delete all settings, and restored the whole thing. As soon as I opened Firefox again all tabs where duplicated.

It seems that removing "Open tabs" sync from the Firefox account sync options avoids duplicating the tabs, but this was working before.

Thanks for the great job you've been doing.

**Comment by fjssilva** [comment]
UPDATE: removing the sync open tabs option doesn't solve the problem. I just closed and reopened the browser and all tabs got duplicated again.

BTW, I'm using FF 73.0 and STG 4.4.2.

**Comment by Drive4ik** [comment]
What OS you are using?

**Comment by fjssilva** [comment]
Ubuntu 19.10

**Comment by Yssy00** [comment]
same problem.  I restored also, but is not resolved the problem...  and few restart duplicate again and again... I have thousands tabs now...  Firefox use 8-10GB ram, and it doesn't load normally... and I can't disable the plugin...  my browser has become unusable.  (new plugin version, uptodate FF, uptodate win10)

**Comment by Drive4ik** [comment]
Guys, try exiting the browser with this button:
![изображение](https://user-images.githubusercontent.com/7843031/75257531-c740cd80-57ed-11ea-9f6b-a4cf1d0404cb.png)

**Comment by Drive4ik** [comment]
not [X] button

**Comment by Drive4ik** [comment]
I made a fix for Mac OS when the user closes the window, but there the FF process does not end and the user loses all the tabs on the window. So I save the tabs and restore them when I open the window or launch the browser. To prevent this from happening, please turn off your browser like in the picture above. I will roll back this fix in the next release.

**Comment by fjssilva** [comment]
Yes, it makes all the difference. Works if closing with ctrl+Q too.

**Comment by Yssy00** [comment]
crash crash crash... so I reinstall my FF,  and reinstall the addon. It seems to be ok.

other question, sorry: 
When I click the Tabgroup icon, because I would change the tabgroup, I got the list of page, not the list of tabgroup (as earlier)... and I need scrolling up (hundreds of tabs, so long time) and click to 'Go back to group' button. Can I disable it? I would like to see the tabgroup list without scrolling.. 
thanks!

**Comment by Drive4ik** [comment]
@Yssy00 Please, read this: https://github.com/Drive4ik/simple-tab-groups/issues/538#issuecomment-590934809

Please tell me what OS you are using?

**Comment by Drive4ik** [comment]
I upload `v4.4.2.2` with hotfix this issue, it's now under review. Please wait.
And sorry for the inconvenience, it is not always possible to test on different devices and with different settings...

**Comment by Yssy00** [comment]
> @Yssy00 Please, read this: [#538 (comment)](https://github.com/Drive4ik/simple-tab-groups/issues/538#issuecomment-590934809)
> 
> Please tell me what OS you are using?

Win 10 Pro

**Comment by Yssy00** [comment]
> I upload `v4.4.2.2` with hotfix this issue, it's now under review. Please wait.
> And sorry for the inconvenience, it is not always possible to test on different devices and with different settings...

thanks :)

**Comment by fjssilva** [comment]
> I upload `v4.4.2.2` with hotfix this issue, it's now under review. Please wait.
> And sorry for the inconvenience, it is not always possible to test on different devices and with different settings...

Thanks!

**Comment by arganoid** [comment]
How long will it take for the fixed version to be rolled out to auto-update? And will the duplicated tabs be removed? I now have 1,800 tabs in my main group, and hundreds more in the others.

**Comment by Drive4ik** [comment]
@arganoid Tabs will not be deleted automatically. Addon removes tabs only at the request of the user.
You need to update the addon to the latest version v4.4.2.3
![изображение](https://user-images.githubusercontent.com/7843031/75336896-a5e6ec80-5894-11ea-8de9-3340944d3229.png)
![изображение](https://user-images.githubusercontent.com/7843031/75336946-b6976280-5894-11ea-881f-8e5879c4a0b4.png)

And you need to wait about 30 seconds until the version version is updated here
![изображение](https://user-images.githubusercontent.com/7843031/75337015-d9c21200-5894-11ea-93f2-fb51d3a989a4.png)

I can recommend this addon as a temporary solution for duplicate tabs.
https://addons.mozilla.org/firefox/addon/duplicate-tabs-closer/

**Comment by Drive4ik** [comment]
Guys, please, update to the latest version of the add-on: v4.4.2.4 (it is already uploaded and it under review), and wait about 30 seconds until it applies. This version fixes most of the problems. I accidentally committed unverified code due to rush.
Strongly do not scold ...

**Comment by fjssilva** [comment]
All working nicely again. Many thanks and keep up the good work!

**Comment by Drive4ik** [comment]
Version v4.4.2.4 was released, please update addon into it

**Comment by pan64** [comment]
I just wanted to report the same issue, but finally found this one (just now). I think I have 4.4.2.5 and all of the tabs were duplicated (after opening). So it looks like it is not solved (or am I missed something)?

**Comment by Drive4ik** [comment]
@pan64 what is your OS, browser version and what other add-ons do you have?

**Comment by pan64** [comment]
Linux, ubuntu 18.04. Theoretically fully uptodate. 
Firefox 74.0, addons: AdBlock, Blur, STG, UserAgentSwitcher (inactive) and GooseGooseJump (disabled). Nothing more.

**Comment by Drive4ik** [comment]
Can I guess that you close the browser with a cross? When you click on the cross, the browser is in memory for some time, and sends the addon messages that all the tabs of this window are closed. The addon adds all these tabs to the repository, and tries to restore it when you open a new window, or the next browser starts.
Try closing the browser with:
![изображение](https://user-images.githubusercontent.com/7843031/77309690-c5432f00-6d05-11ea-8495-d3d778cf3635.png)
then the browser finishes its work differently.
In any case, the addon tries to restore the tabs (recreate) only if they are not in the group.
Do you have session recovery enabled in your browser settings?

**Comment by pan64** [comment]
restore previous session is on. But I don't know if it can restore tab groups.

**Comment by Drive4ik** [comment]
It is better to close the browser separately before turning off the computer, as it may not always be able to correctly terminate all its processes and save the session. Because as we can see, browsers become media combines that can play video, audio, games. All this takes up many places in the RAM and on the hard drive.
