### ISSUE TITLE
STG icon expands group to active tab

### ISSUE THREAD

**Issue by fjssilva** [Drive4ik/simple-tab-groups#538]
Clicking on the STG icon opens the popup showing the active group expanded and with focus on the active tab. In previous versions it was showing the list of groups only.

I've always used the STG icon to switch between groups. As it is now, I have to scroll to the top and click on "Go back to groups" to see the list of groups, which is overkill. Not sure if this change was on purpose or by mistake.

Can this behavior be reverted? Or, even better, configurable.

Using FF 73.0 and STG 4.4.2 on Ubuntu 19.10.

**Comment by Drive4ik** [comment]
Yeah. Addon's got the settings, there's a lot to influence. The group also has settings (context menu on the group).

**Comment by fjssilva** [comment]
I didn't get it, sorry. Will you change the old behavior back?

**Comment by Drive4ik** [comment]
You need to do this:
![изображение](https://user-images.githubusercontent.com/7843031/75263632-ee4fcd00-57f6-11ea-82f1-abe0ce7e35dc.png)


If something doesn't work out, write to me.

**Comment by fjssilva** [comment]
The name/description of the option is not very clear... but it works, so I'm happy! Thanks!

**Comment by Drive4ik** [comment]
Yes, because this option has one more action, if the STG is open in a sidebar, the UI also follows the loaded group.

**Comment by zweif** [comment]
I got here investigating the same problem. The german translation of this setting is a little bit off, so I didn't get its purpose. I'd suggest something like 'Öffne Gruppe nach Wechsel zu ihr'.

**Comment by Drive4ik** [comment]
@zweif I made a little page to help me with the translations. If you want, you can help me.
https://drive4ik.github.io/simple-tab-groups/translate/index.html

**Comment by Drive4ik** [comment]
@zweif Mostly I write in Russian and translate into English. And all other languages help me with users.  For which many thanks to them!

**Comment by zweif** [comment]
Thanks for the info, I'll have a look. Also thanks for the work you're putting into this extension :)

**Comment by davidlav** [comment]
I love this extension to death, but also wish that the old behavior was preserved, especially when it takes 20 minutes of Googling and combing through GitHub issues to find the above answer.  Can that setting be unchecked by default in a future version?

I appreciate that you're adding more options/settings to tweak, that's fantastic (seriously!), but changing the _default_ behavior seems to be confusing a lot of users (so many so that multiple issues on this are springing up #549).

**Comment by Drive4ik** [comment]
Hi all! Please, wait version 4.4.2.5 (now under review) I fixed this bug
