### ISSUE TITLE
Move tab to not working

### ISSUE THREAD

**Issue by imwhynowhy** [Drive4ik/simple-tab-groups#539]
Move Tab To from tab is not working on Gallium Linux. But it does work from Manage Groups. I have tried deleting settings and also reinstalled extension but no joy.

**Comment by timglong** [comment]
> 
> 
> Move Tab To from tab is not working on Gallium Linux. But it does work from Manage Groups. I have tried deleting settings and also reinstalled extension but no joy.

Having the same problem in Firefox.

Right clicking on a tab -> Move tab to group does not work.

To reproduce the behavior:

    Open a tab
    Right click on the tab
    Scroll to "Move tab to group"
    Select a group
    Nothing happens

Expected behavior is the tab leaves the current group and moves to the assigned group.

    Windows 10
    Firefox version: 73.0.1 64-bit
    Simple Tab Groups version: 4.4.2.1

**Comment by Drive4ik** [comment]
Hi all! I fix this silly bug.. please wait next release

**Comment by timglong** [comment]
You're amazing! Thank you so much! :)

**Comment by imwhynowhy** [comment]
Yes,Thank you this was driving me crazy.

**Comment by Drive4ik** [comment]
Oh, no... I haven't been doing very well with the latest changes... although I was checking that I could... many mistakes... I'll try harder, don't scold me too much :)
