### ISSUE TITLE
Usability Bug opening tabGroups menu auto open some submenu and now we need every time go one step up

### ISSUE THREAD

**Issue by Jes28** [Drive4ik/simple-tab-groups#540]
**Describe the bug**
Usability Bug opening tabGroups menu auto open some submenu and now we need every time go one step up

**To Reproduce**
1. Open tabGroups menu
2. submenu is opened

**Expected behavior**
Submenu not opened on opening menu

**Screenshots**

**Comment by Jellby** [comment]
+1
Please restore the old behaviour or add an option for it (I couldn't find one).

**Comment by asdgfd** [comment]
Yes, pleeease fix.

Also, Thanks Jellby for info. (I'm not sure what that description is supposed to mean, so probably would have never tried it, but seems to undo the problem for me, too.)

**Comment by Shdwdrgn** [comment]
Another "me too"... I can't imagine such an option was purposely enabled by default, as it really defeats the ease-of-use of this plugin.  Please turn it off.

And thanks Jellby, I also used your 'fix'.

**Comment by kparal** [comment]
> EDIT: It looks like disabling the "Open group after changing to it" option does it. If this is what the option is for, I'd change the description.

This was added in #504, I just didn't expect to be enabled by default. I think it would make sense to have it enabled by default in the side bar but not in the popup menu, but that would further complicate the configuration options (right now it affects both places).

**Comment by xGnoSiSx** [comment]
It shouldn't affect both places, either it gets removed or another option must be added. I wasted so much time to track this and get the old behaviour back.

**Comment by Drive4ik** [comment]
The fact is that I turned off this option by default, but for some reason it gave the opposite effect ... I will look at what's the matter.
4f2790f49142801c6db3fd8136c7dac37898b8ae

**Comment by Drive4ik** [comment]
Guys, please, update to the latest version of the add-on: v4.4.2.4 (it is already uploaded and it under review), and wait about 30 seconds until it applies. This version fixes most of the problems. I accidentally committed unverified code due to rush.
Strongly do not scold ...

**Comment by Darkazas** [comment]
> 
> 
> +1
> Please restore the old behaviour or add an option for it (I couldn't find one).
> 
> EDIT: It looks like disabling the "Open group after changing to it" option does it. If this is what the option is for, I'd change the description.

Still can't understand why where is need to change old defaults - add new features but leave flags not toggled.

**Comment by Drive4ik** [comment]
@Darkazas There is such functionality that was originally made, but there are 5% of users who do not need it, and I make an option that is turned on by default, and it can be turned off in the settings.
For example, "Show notification when a tab is moved to another group"

**Comment by Darkazas** [comment]
Fine with me.
Don‘t understand me wrong – your work is highly appreciated. Using this plugin several years.

**Comment by achernyakevich** [comment]
> @Darkazas There is such functionality that was originally made, but there are 5% of users who do not need it, and I make an option that is turned on by default, and it can be turned off in the settings.

For me it looks like different cases when you use sidebar and popup:
- sidebar - mainly for visual navigation, often mouse is used
- popup - as an entry point for searching, in most cases keyboard is used

So popup that has no focus in search field after opening (usually open by pressing F8) looks really like a bug. :)

And getting to understanding that that behavior was controlled by `Open group after changing to it` option in setting was another one mind trick. If you are going to keep this behavior as it is now then maybe you need to rename it to something more straightforward that will identify that popup and sidebar could be affected.

**Comment by Drive4ik** [comment]
Guys, please update addon to latest version (4.4.2.5) All of these bugs was fixed in it.
