### ISSUE TITLE
Can't move Tabs to Groups anymore

### ISSUE THREAD

**Issue by MechEngr106** [Drive4ik/simple-tab-groups#541]
When selecting Move Tab to Group, it no longer moves the tab to a new group.  I've uninstalled & reinstalled FireFox and Simple Tab Group Add On with no effect.  Just checked my office manager's workstation with the same results.  No longer works for her either.  Also, somehow the Open Group After Changing To It was enabled on both our machines without enabling it.  Has there been a recent update?

Windows 10 Pro Version 1909
Firefox 73.0.1 (64-bit)
Simple Tab Groups 4.4.2.1

**Comment by carlost** [comment]
i just installed this extension a few minutes ago and am seeing the same behavior.  the only way i have been able to move tabs between groups is to drag and drop tabs in "manage groups" view.

granted i just started using this so i might be doing something wrong.

MacOS 10.14.6
Firefox 73.0.1 (64-bit)
Simple Tab Groups 4.4.2.1

**Comment by timglong** [comment]
See #539, should be fixed in the next release!

**Comment by timglong** [comment]
For the other issue, see #540; the fix is very fast. Right click on the extension -> Manage Extension -> Options -> Ensure "Open group after changing to it" is unchecked.

There was a previous feature request for this behavior but I can't remember what # it was.

**Comment by Drive4ik** [comment]
Guys, please, update to the latest version of the add-on: v4.4.2.4 (it is already uploaded and it under review), and wait about 30 seconds until it applies. This version fixes most of the problems. I accidentally committed unverified code due to rush.
Strongly do not scold ...
Best regards

**Comment by MechEngr106** [comment]
Drive4ik, I just updated the add-on and it updated to 4.4.2.3, which is working.  The Move To feature works great.  Kudos to you and your team for such a super add-on.  I don't know how we would work around here without it.  Keep up the good work!!
