### ISSUE TITLE
Regular expressions not working

### ISSUE THREAD

**Issue by Cryvage** [Drive4ik/simple-tab-groups#542]
**Describe the bug**
Tabs doesn't move to containers on base of regular expressions.

**To Reproduce**
1. Create container.
2. Add regular expression, e.g. (facebook|twitter|youtube)\\.com
3. Open website, which URL match regular expression, e.g. "facebook.com", in new tab, or open new tab, and go to this website there.
4. And nothing happened.

**Expected behavior**
The tab should be moved to the container.

**Desktop:**
 - OS and version: Linux Mint
 - Firefox version: 73.0.1
 - Simple Tab Groups version: 4.4.2.1

**Additional context**
Reproduced on fresh profile, without other extensions installed.

**Comment by Drive4ik** [comment]
Try with escapes dot, like (facebook|twitter|youtube)**\\**.com

**Comment by Cryvage** [comment]
In tests it was escaped. I've made a typo in description. Sorry. 
Now checked both cases, with escaped dot and not. Same result.
Also checked: "facebook", ".*facebook.*", and ".*".
Seems like, it doesn't matter which expression I use, it's just ignored.

**Comment by Drive4ik** [comment]
Please, check this option in the group where the tab should be moved from.

![изображение](https://user-images.githubusercontent.com/7843031/75354583-e014b600-58b5-11ea-9ecd-9e5570287cae.png)

**Comment by Cryvage** [comment]
Seems like problem occur, when I open tabs not from group (from default group, or how it named). All worked, when I open tab, from another group, without "sticky" option enabled. But for default group it's look like "sticky" behaviour is enabled by default.

**Comment by Drive4ik** [comment]
Yes, I get it. All these rules do not work in a window in which there is no assigned group. That is, a window without a group. Since the tabs in such a window do not belong to any group, the rules do not apply to them.
