### ISSUE TITLE
Closing a tab doesn't update the side bar

### ISSUE THREAD

**Issue by kparal** [Drive4ik/simple-tab-groups#543]
**Describe the bug**
When the side bar is opened and you see all your current tabs, closing one of the tabs doesn't update the side bar, so the tab is still visible in there. Closing and reopening the side bar updates the information.

**To Reproduce**
1. Open the side bar.
2. Open a new tab, e.g. go to mozilla.org.
3. Close the tab.
4. See that mozilla.org tab is still visible in the side bar. Clicking on it does nothing.
5. Close the side bar and open it again, the mozilla.org tab is no longer shown (which is correct). 

**Expected behavior**
Closed tabs should disappear from the side bar.

**Desktop (please complete the following information):**
 - OS and version: Fedora 31
 - Firefox version: firefox-73.0.1-1.fc31.x86_64
 - Simple Tab Groups version: 4.4.2.3

**Comment by Drive4ik** [comment]
Please, you need update to the latest version of the add-on: v4.4.2.4 (it is already uploaded and it under review), and wait about 30 seconds until it applies. This version fixes most of the problems. I accidentally committed unverified code due to rush.
Strongly do not scold ...

**Comment by kparal** [comment]
This is fixed with 4.4.2.4, thanks!
