### ISSUE TITLE
Doubles all the tabs with a group

### ISSUE THREAD

**Issue by Michal-Sitarz** [Drive4ik/simple-tab-groups#544]
**Describe the bug**
If I'll close the Firefox and reopen it, the extension doubles all the tabs in each group.
Doubles, I mean I see the list of all tabs twice within a group. This is done to all groups.

**To Reproduce**
1. Close Firefox
2. Reopen it

**Desktop (please complete the following information):**
 - OS and version: Windows 8
 - Firefox version: 73.0.1
 - Simple Tab Groups version: 4.4.2.1

**Comment by Drive4ik** [comment]
I already fix this bug, please, update to latest version 4.4.2.3

**Comment by Darkazas** [comment]
> 
> 
> I already fix this bug, please, update to latest version 4.4.2.3
4.4.2.4 already

**Comment by Darkazas** [comment]
> 
> 
> **Describe the bug**
> If I'll close the Firefox and reopen it, the extension doubles all the tabs in each group.
> Doubles, I mean I see the list of all tabs twice within a group. This is done to all groups.

I'd got tripples but it's already fixed.

**Comment by Drive4ik** [comment]
All this because of my rush ...
Then I will close the ticket.

**Comment by Michal-Sitarz** [comment]
I've updated to the latest version (4.4.2.4) and it works fine.
Thanks for info and quick reply!
