### ISSUE TITLE
Starting firefox and all tabs are empty !

### ISSUE THREAD

**Issue by Erreur32** [Drive4ik/simple-tab-groups#545]
Each time i start to open Firefox , all my tabs are blank ( empty ) ,
EACH time i need to apply a backup , all days every days ...

It's boring and i don't undertand WHY  all my tabs are empty ?
it was running clean last year.

What i have done to fix :
- I have already read all issue ,
- I have  try to desinstall and reinstall simple tab groups without success...
- i have also reinstall my firefox , not better

HELP please !

Regards,
Steve

**Comment by Drive4ik** [comment]
Hi! Do you have enabled this option?
![изображение](https://user-images.githubusercontent.com/7843031/75368790-ee210180-58ca-11ea-9213-8c171c427883.png)

**Comment by Erreur32** [comment]
Ho , it's the first thing i have checked ;)

**Comment by Drive4ik** [comment]
What is your OS and version of the addon?
Checked on the latest version of the addon? (v4.4.2.4)

**Comment by Erreur32** [comment]
All my tabs groups are ok ,

 i know u have more 400 bookmark in 15 tabs

OS : wiondows 10 ( clean install )
Firefox Dev

**Comment by Drive4ik** [comment]
I do not quite understand your last message.

**Comment by Erreur32** [comment]
![screenshot 1](https://user-images.githubusercontent.com/2248137/75370118-ebbba900-58c4-11ea-8b93-b03f5c1fc2aa.jpg)


It's maybe better to understand ? :P
(I have edit my latest comment)

**Comment by Drive4ik** [comment]
Such a question: if you disable the add-on and restart the browser, will the open tabs (in the screenshot) remain in the window?

**Comment by Drive4ik** [comment]
If the tabs are not restored when the browser starts and with the add-on disabled, I can advise you to create a new FF profile and transfer all your bookmarks, tabs, passwords, etc. to it. Apparently your profile has been damaged.

**Comment by gorbachev** [comment]
I had an issue like this when using STG with another addon. Removing the offending addon fixed my issue.

**Comment by Erreur32** [comment]
@gorbachev you have right !

After  disable some plugins,  seem to be runing well ;) !
i really don't know which plugin was  bad, i keep checking if i find the  guilty plugin.

@Drive4ik ,  Thank for this amazing plugin!

**Comment by Drive4ik** [comment]
@Erreur32 and @gorbachev , guys, please tell me what conflicted addon you are disable?
It is very important for me to know this. I am making a list of conflicting addons to notify the user if he has one of the addons from this blacklist

**Comment by gorbachev** [comment]
I believe it was Tab Session Manager:

https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/

It could've been another session manager type addon as well, it's been a while and I'm not using it any longer, obviously, but I'm pretty sure it's this one.

**Comment by Erreur32** [comment]
I have also disable this useless extension too: Tab Session Manager.

and i can confirm  it's look fine now since my last issue.

**Comment by Drive4ik** [comment]
Then I close the ticket. Thank you all for finding the cause of the problem.
