### ISSUE TITLE
Launching Firefox creates dublicates of open tabs

### ISSUE THREAD

**Issue by CazeW** [Drive4ik/simple-tab-groups#546]
When launching Firefox the open tabs are restored like usually, but once STG finishes loading, it opens/restores the tabs again creating dublicates. If I uncheck the option to restore the session in Firefox settings, STG still restores the opened tabs. I didn't have this issue a few days ago.

**To Reproduce**
Close Firefox.
Open Firefox.
Once STG finishes loading you have dublicates of all the tabs in all groups.

**Expected Behaviour**
Not create dublicates of all open tabs when launching Firefox.

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox version: 73.0.1
 - Simple Tab Groups version: 4.4.2.1

**Comment by Drive4ik** [comment]
Please, update add-on to latest version (4.4.2.4) this bug was fixed in it.

**Comment by CazeW** [comment]
Updating to 4.4.2.4 seems to indeed have fixed it.
