### ISSUE TITLE
STG opens up with tabs instead of group after deleting my Cookies and Site Data for Firefox

### ISSUE THREAD

**Issue by Phooh** [Drive4ik/simple-tab-groups#547]
**Describe the bug**
The STG button opens up with tabs instead of group forcing me to always hit the "Go back to groups" every time I open it. I'm assuming this had something to do with me enabling the option of  deleting my Cookies and Site Data in FireFox 73.0.1 as I had unrelated connection problem with my router on late Monday(Had no internet until Tuesday afternoon) and seeing if deleting cookies and site data would fix that issue and this wasn't happening before I did all that.

It seems like it also did a number of issues with STG as it also created duplicate of tabs for all of my groups at Firefox startup.  

**To Reproduce**
1. Go to 'Firefox tools-> options -> Privacy & security'
2. Scroll down to 'Cookies and Site Data'
3.Click on 'Delete cookies and site data when Firefox is closed'
4. Unknown if the issue is related

**Desktop (please complete the following information):**
 - OS and version: Windows 7
 - Firefox version: 73.0.1
 - Simple Tab Groups version: 4.4.2.1

**Comment by HeRo002** [comment]
I use Firefox 73.0 on Ubuntu 18.04.4 LTS (with GNOME 3.28.2). 
I also experience that the STG-icon in the top-bar gives me a list of tabs instead of the list of groups. It has been so for a few days, and it's quite annoying. I can't see any way of changing it. Any help would be appreciated.

**Comment by Drive4ik** [comment]
@Phooh Please, update addon to latest version (now 4.4.2.4) and disable option in addon settings "Open group after changing to it"

@HeRo002 Please, disable option in addon settings "Open group after changing to it" too.

**Comment by HeRo002** [comment]
Thank you! That works!

**Comment by Phooh** [comment]
That worked, thanks

**Comment by Phooh** [comment]
That worked, thanks
