### ISSUE TITLE
Pinned tabs get duplicated as normal tabs

### ISSUE THREAD

**Issue by phaolo2** [Drive4ik/simple-tab-groups#548]
**Describe the bug**
With this new version, when opening Firefox, Pinned tabs get duplicated as normal tabs at the end of the current group.

**To Reproduce**
Pin some tabs, close and reopen Firefox, check tabs.
EDIT: maybe only pinned tabs already existing before the update caused this, not new ones.

**Expected behavior**
Pinned tabs should be restored as they are, without duplicates.

**Desktop (please complete the following information):**
 - OS and version: Windows7 Pro x64
 - Firefox version: 73.0.1 x64
 - Simple Tab Groups version: 4.4.2.4

**Comment by phaolo2** [comment]
Nevermind, the problem went away after removing ALL existing pinned tabs, restarting, and then readding them.

**Comment by Drive4ik** [comment]
Strange, in theory, pinned tabs should be skipped. I still can’t repeat it. I will investigate.

**Comment by arganoid** [comment]
I was finding that on startup, an extra "New Tab" tab was always opened. But this stopped happening when I closed my only pinned tab.

**Comment by Drive4ik** [comment]
Guys, please update addon to latest version (4.4.2.5). All of these bugs was fixed in it.
