### ISSUE TITLE
Issue with Group List

### ISSUE THREAD

**Issue by alan8it** [Drive4ik/simple-tab-groups#549]
When the update was pushed today, Whenever I click the button in my title bar to see the Groups, it instead shows me a list of tabs within the group I am currently in. To recover, I have to scroll to the top of the list then click on Go Back to Groups. From there, I can then select the group I wish to navigate to.
Then, If I want to go back to a different group, I have to do the same thing again.
Didn't happen yesterday, just started after the update on 2/26/2020.

**To Reproduce**
1. Click the simple tab groups Icon in Title Bar

**Expected behavior**
It should show the list of Groups unless I choose the arrow to the right of the group name and then it can expand to show the complete list of Tabs within that group.

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Windows
 - Firefox version: 73.0.1
 - Simple Tab Groups version: 4.4.2.4

**Additional context**

**Comment by aisen0921** [comment]
I have the same issue.

**Comment by MartinGraive** [comment]
See #538

**Comment by el95149** [comment]
Facing the same issue as well, since the latest update.

- OS and Version: Kubuntu 19.10 x64
- Firefox version: 73.0.1
- Simple Tab Groups version: 4.4.2.3

**Comment by el95149** [comment]
> Facing the same issue as well, since the latest update.
> 
>     * OS and Version: Kubuntu 19.10 x64
> 
>     * Firefox version: 73.0.1
> 
>     * Simple Tab Groups version: 4.4.2.3

Never mind, I just RTFMed and looked at #538 , like you suggested. All's well now, thanks a lot.

**Comment by Drive4ik** [comment]
Please, wait version 4.4.2.5 (now under review), I fixed this bug
