### ISSUE TITLE
Move multiple tabs

### ISSUE THREAD

**Issue by SladeThe** [Drive4ik/simple-tab-groups#55]
The possibility to select many tabs and move them to another group all at once is highly requested.

**Comment by Drive4ik** [comment]
I will to make this functional in future versions

**Comment by m60freeman** [comment]
This would be very helpful.

**Comment by alreadydone** [comment]
It's still not possible in the experimental version, right?

**Comment by Drive4ik** [comment]
@Keith94 Maybe in next versions))
Now I'm working to improve stability
