### ISSUE TITLE
STG Toolbar Menu Opens with Current Group Instead of List of Groups

### ISSUE THREAD

**Issue by NickNackN** [Drive4ik/simple-tab-groups#550]
**Describe the bug**
Formerly the toolbar menu of STG opened with the list of tab groups, which makes sense as it is the most common use case to change the group. Selecting another tab inside the current group is already supported by the browser tabs as they are.

**To Reproduce**
1. Click the STG toolbar button
2. See the wrong menu as described above

**Expected behavior**
Former behavior: Open the list of groups. Not needing to click on "Go back to groups"

**Desktop (please complete the following information):**
 - OS and version: Windows 10, 
 - Firefox 73.0.1
 - Simple Tab Groups version: v4.4.2.4

**Comment by Drive4ik** [comment]
Please, wait version 4.4.2.5 (now under review), I fixed this bug

**Comment by NickNackN** [comment]
Oh, that's quick! Thank you!
