### ISSUE TITLE
Cant move Tabs between the Groups

### ISSUE THREAD

**Issue by ichbins77** [Drive4ik/simple-tab-groups#551]
**Describe the bug**
The Context-Menu "move Tab to Group XY" isnt anymore.

**To Reproduce**
tab
right click to tab

"move tab to" - Btton is gone

**Desktop (please complete the following information):**
 - OS and version: [e.g. Windows] win 10 pro 64
 - Firefox version: [e.g. 63] 73.0.1.
 - Simple Tab Groups version: [e.g. 3.0.8] 4.4.2.

**Comment by Drive4ik** [comment]
Please, update add-on to latest version, now 4.4.2.5. This bug was fixed in it.

**Comment by ichbins77** [comment]
> 
> 
> **Describe the bug**
> The Context-Menu "move Tab to Group XY" isnt anymore.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Go to '...'
>        tab
> 
>     2. Click on '....'
>        right click to tab
> 
>     3. Scroll down to '....'
> 
>     4. See error
>        "move tab to" - Btton is gone
> 
> 
> **Desktop (please complete the following information):**
> 
>     * OS and version: [e.g. Windows] win 10 pro 64
> 
>     * Firefox version: [e.g. 63] 73.0.1.
> 
>     * Simple Tab Groups version: [e.g. 3.0.8] 4.4.2.

i did. forget nr 5 .
have version 4.4.2.5

**Comment by Drive4ik** [comment]
To be honest, I didn’t understand anything. Can you take a screenshot and show on it?
