### ISSUE TITLE
Inconsistent backup filenames

### ISSUE THREAD

**Issue by kssi** [Drive4ik/simple-tab-groups#553]
The backup filename format keeps changing upon updates... And this keeps breaking my cleanup script.

So far I had filenames like:

`stg-backup-2018-10-29@drive4ik.json`
`stg-backup-2019-03-01~05-50@drive4ik.json`
`stg-backup-v4.2.2-2019-11-04~00-06@drive4ik.json`

After updating to v4.4.2.5 it's now:

`stg-backup-mac-2020-03-03~07-48@drive4ik.json`

This is quite boring to be honest, and I don't see a good reason not to choose a solid convention and stick to it.

Ideally, this would be `stg-backup-%Y-%m-%d~%H-%M-%S@drive4ik.json`.

**Comment by Drive4ik** [comment]
I would love to do that if the add-ons had a little more ability to save the file. The fact is that if you have to create a copy once a day, then the timer starts, and every 2 hours it creates a copy without time, thereby overwriting the existing copy that is older than 2 hours. That there was the freshest copy in case of breakdown of something. If this is not done, then 12 files will be created in one day, and if I reduce the time by 1 hour, then all 24 files ...
And to find out if there is a file and if you need to delete it - there is no such possibility in the browser yet.

I changed the file name format a bit by removing the OS d338a8c

By the way, I did create a new folder for each version of the browser. Delete the name of the backup file folder in the addon settings. The addon will generate a new name when changing the version of the browser. I should help you with the file search, as the browser is updated ~ every month.
