### ISSUE TITLE
Firefox hangs/consumes everything on startup

### ISSUE THREAD

**Issue by floyddebarber** [Drive4ik/simple-tab-groups#554]
Since last week when I start Firefox it hangs (immediately consuming most if not 100% of CPU and 4+ GB of RAM). After a while it usually sends a window to stop a process ( chrome://browser/content/tabbrowser-tab.js:231), doing so sometimes repeats this message on a different line. This afternoon it failed completely - after stopping that process, the one active tab works as intended with the address bar, but the interface itself is unresponsive (and by the looks of the tabs, it seems to open every tab at once).

This happened last week, I sort of solved it by refreshing Firefox and restoring my tabs from backup. It was still very slow on startup but after a couple of minutes it worked as usual. I did the same step now, it works so far - starts quickly and no extra consumption.

One important detail: I have LOTS of tabs, more than a two thousand in total and in some tabs hundreds open at the same time. It was never an issue: until last week, it only affected browser start and tab group change for an extra 5 seconds or so.

My setup:
Win 10 1903/1909 (I just updated, it didn't help)
Firefox 73.0.1.
Simple Tab Groups 4.4.2.5, but it happened on the previous version too.

**Comment by Drive4ik** [comment]
As far as I understand, did this happen before reinstalling the addon with restoring data from backup?
A bug cannot be repeated or repeated on the same version. The behavior is either there or not. You say that you have a lot of tabs, I just want to explain that when you start the browser, all these tabs are restored from the browser session, and if there are a lot of them, a message like yours appears: `chrome://browser/content/tabbrowser-tab.js:231`
This is a browser script, it takes a long time to restore tabs from a session.
The browser will behave this way even if you disable the addon.

Especially for such cases, I did archiving groups. Available on the context menu of the group in a pop-up window.
This action saves the group’s tabs in the addon’s memory, and removes all these tabs from the browser, thereby making its work much easier. Also, the archive group becomes completely non-working - you cannot go to it, or move tabs there.

Also check, maybe you have some add-ons that slow down the browser and tabs. There are a lot of them. Here is even such a harmless: #533 or #393
