### ISSUE TITLE
Loop when opening a tab in a container-related group

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#555]
Steps: 
- Create a new group and assign it to a container (so that new tabs in this groups open in the container)
- Uncheck the "If the container is different from the selected one - change the container" option for this group
- Move to this group
- Click on a generic bookmark (with no container-specific rules)

Actual result: 
- the new tab keeps looping on opening

Expected result:
- the new tab opens in the above container

**Comment by Drive4ik** [comment]
Hi! I already know about this bug, and right now I'm sitting and modulating this logic :)
Fix will be in next release

**Comment by klint** [comment]
Perfect, thanks a lot :)

**Comment by Drive4ik** [comment]
done) 
new strings will be here
![изображение](https://user-images.githubusercontent.com/7843031/76344136-bde55400-6309-11ea-93b9-33810a2ab2e6.png)
