### ISSUE TITLE
Unarchive reverses tab order

### ISSUE THREAD

**Issue by Adam777Z** [Drive4ik/simple-tab-groups#556]
If the browser.tabs.insertAfterCurrent preference is true, the tabs get reversed on Unarchive.

A potential solution would be checking if that preference is true and if yes, reverse the tabs before unarchiving them.

**Comment by Drive4ik** [comment]
Unfortunately, already or for now, the browser does not even allow you to read the value of parameters from `about:config`. 
Here are the parameters that the addon can modify and read:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings

But, I want to make an option in the add-on settings, which will reverse tabs when restoring and creating. You can simply enable it in the addon settings if your parameter `browser.tabs.insertAfterCurrent` is set to true

**Comment by Drive4ik** [comment]
done

**Comment by Adam777Z** [comment]
I see. I tried the new version with that option enabled and it works correctly. Thank you!
