### ISSUE TITLE
Backup-Folder

### ISSUE THREAD

**Issue by Max-Grapho** [Drive4ik/simple-tab-groups#557]
Since yesterday I have a Backup-Folder on my Desktop named "STG-backups-win-20191030021342".
Normally it should be under "Downloads" but now on the Desktop. I don#t find settings how to change the folder where STG should make it's backup.

**Comment by Drive4ik** [comment]
Hi! Addon cannot control this. This folder is configured in the browser settings, here:
![изображение](https://user-images.githubusercontent.com/7843031/76345716-81ffbe00-630c-11ea-9489-12ca4cb34276.png)
