### ISSUE TITLE
[Feature Request] Allow custom css for the sidebar

### ISSUE THREAD

**Issue by saithis** [Drive4ik/simple-tab-groups#558]
**Is your feature request related to a problem? Please describe.**
I would like to make the background black to increase the contrast, maybe adjust the tab height a bit and try to make black favicons (github, etc.) in the dark theme more readable.

**Describe the solution you'd like**
A textbox in the addon settings where a can input custom css rules that are applied to the sidebar. It would be ok with me if this feature would be "at your own risk". If the rules break on some updates, I can just fix them myself.

**Describe alternatives you've considered**
Either making settings for background color, tab height, etc. But the more things should be customizable, it gets complex really fast. Or make a PR with my preffered styles, but other people might not like the changes.

**Additional context**
none

**Comment by Drive4ik** [comment]
Hi! Perhaps I will do it in future versions.
But unfortunately, you will not be able to change the color of the github icon, because it is of type icon and not svg ...
Please tell me, did you enable the `svg.context-properties.content.enabled` parameter?

**Comment by saithis** [comment]
Yes I did enable `svg.context-properties.content.enabled`. My Plan was not to change the color of the icon, but maybe to make a bright background behind the icon. I think most icons are optimized for a bright background.

**Comment by arbitar** [comment]
@saithis - Even if this is not supported by individual extensions, it is possible to target extension pages (including sidebar) using userContent.css.

For information on the userContent.css file, see: http://kb.mozillazine.org/index.php?title=UserContent.css

1. go to `about:support`, open Profile directory
2. create `chrome` subdirectory
3. create new text document named userContent.css)

Populate this new file with desired CSS rules. They will apply to *all* webpages, so craft your rules carefully.
If you don't use Firefox Sync and intend to use this only on one system, I would suggest using a `-moz-document` block matching the plugin's document. To do this, find the Internal UUID value for Simple Tab Groups under `about:debugging` > _This Firefox_ > _Simple Tab Groups_, and wrap your userContent.css rules in something like this:

```
@-moz-document url("moz-extension://INTERNAL_UUID_HERE/popup/popup.html#sidebar") {
  /* ... css rules here ... */
}
```

From that about:debugging page, you can also hit the _Inspect_ button to see how the sidebar document is structured to advise the creation of your rules. This is what I use to change the background color:

```
#stg-popup.is-sidebar {
  background: #0c0c0d !important;
}
```

It may be worth improving the specificity and coverage of classes and ids in these documents throughout the plugin to help support people who want to customize STG to suit their needs without needing to go through the somewhat arduous process of forking and rebuilding the plugin!

**Comment by Drive4ik** [comment]
This option completely solves your request.
