### ISSUE TITLE
Disabling tab tear off

### ISSUE THREAD

**Issue by youk** [Drive4ik/simple-tab-groups#560]
**Describe the bug**
Firefox 74 introduced a new setting to control tab tear off behavior – **browser.tabs.allowTabDetach**. However, it has no effect on tabs managed by STG.

**To Reproduce**
1. Drag a tab and drop it outside the tab panel area.
2. A new window containing that tab is created.

**Expected Behavior**
When browser.tabs.allowTabDetach is disabled, it should not be possible to drag and drop tabs into new windows.

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Firefox version: 74
 - Simple Tab Groups version: 4.4.2.5

**Comment by Drive4ik** [comment]
I just can not understand, where does the STG?
And by the way, this option prohibits the Detach tab, and not moving between windows.

**Comment by youk** [comment]
I consider it an UX issue. Firefox has a setting meant to disable tab tear off. Currently this setting has no effect on the tabs managed by STG. Thus STG creates difference experience that a user might not expect.

> And by the way, this option prohibits the Detach tab, and not moving between windows.

I don't think I follow. Detaching a tab leads to creation of a new window with that tab placed into it. That's how it works on my system and how it is described in [Tab tearing is too sensitive. Tabs frequently moved to new window accidentally](https://bugzilla.mozilla.org/show_bug.cgi?id=727420). ``browser.tabs.allowTabDetach`` allows to overcome this behavior. Does it work differently for you?

**Comment by Drive4ik** [comment]
I have never had a problem with this. Maybe once when the mouse jumped out and brought out a tab in a separate window.
Those steps that you described like that work, STG does nothing and cannot affect it in any way. This is a limitation of the webextensions API. Maybe I misunderstood you. Can you describe in more detail the problem with using STG and this bug?

**Comment by B00ze64** [comment]
@youk Works fine for me, I did not know about this preference, thanks, I used to use an AddOn by Alice White to fix some of the too-easy-detaching, but this is even better! Anyway, I just flipped the preference, and I am inside a STG group, and I just CANNOT detach Tabs! :-)
