### ISSUE TITLE
Move all tabs that don't match a group's capturing regex to another group

### ISSUE THREAD

**Issue by HASJ** [Drive4ik/simple-tab-groups#562]
**Is your feature request related to a problem? Please describe.**
While trying to organize my tabs, everything is fine until I open a URL that isn't capture by the rules of my groups.

Example:
Group 1 captures youtube links with `youtu\.?be`
Group 2 captures social media links with `(twitter|t\.co|reddit)`
Everything else that is ignored by these rules would be moved to Group 3 with a `.*` but it does not work

**Describe the solution you'd like**
An option to "Move all tabs that do not match to this group" in the Manage Groups window

**Describe alternatives you've considered**
I tried making a group with `.*` as rule but all this does is move all tabs to that group, regardless. Even made a previous issue about it as a bug (https://github.com/Drive4ik/simple-tab-groups/issues/226) but I'm not sure it was fixed.

Just found this #367

**Comment by Drive4ik** [comment]
done, you will find these
![изображение](https://user-images.githubusercontent.com/7843031/77075416-f9afa600-69fa-11ea-8b31-1a40674ede68.png)

**Comment by Drive4ik** [comment]
Please, update addon to latest version and test.

**Comment by Honigmelone** [comment]
Thanks, I tested and it works!
