### ISSUE TITLE
Raise awareness of the Simple Tab Groups sidebar

### ISSUE THREAD

**Issue by grahamperrin** [Drive4ik/simple-tab-groups#566]
The sidebar is neither described, nor pictured: 

* https://github.com/Drive4ik/simple-tab-groups/blob/master/README.md#user-content-description
* https://addons.mozilla.org/addon/simple-tab-groups/

Now I see #225 👍 (closed), however it took me **days** to discover the feature. I stumbled across it during a rare visit to the shortcut management area of `about:addons` where intended to weed conflicts (I wasn't aiming to do anything with Simple Tab Groups). 

----

Joy! 

![2020-03-22 04:04:37](https://user-images.githubusercontent.com/192271/77242181-92107b00-6bf3-11ea-9e4b-1272344c63fb.png)

– helps me to treat #319 (closed, not truly a duplicate of #304) as suitably worked around 😹

**Comment by Drive4ik** [comment]
Thanks. I added sidebar into description and screenshots.
