### ISSUE TITLE
FF jumps to wrong tab, 

### ISSUE THREAD

**Issue by Intenditore** [Drive4ik/simple-tab-groups#569]
Problem: many times I close the tab FF with the addon enabled jump to wrong tab - usually, the first which was opened in the group. The tab which should have been activated shows as "loading" instead, but actually it isn't.
Can't describe the steps to reproduce, as well as guess what causes the behaviour 

FF 74.0

**Comment by Drive4ik** [comment]
Please tell me what is your OS and version of the addon.
Does this happen every time you restart the browser?
If so, try disabling the addon, all hidden tabs will appear, and check if this behavior repeats.

**Comment by Intenditore** [comment]
It happens randomly, no particular order noticed. 
Windows 8.1 x64
Addon version 4.5
I tried it without addon and nothing like this happens

**Comment by Drive4ik** [comment]
Then try to remember exactly what you did with the groups before this happened. Maybe you opened the group in a new window, and then closed this window. Or something similar.

**Comment by Intenditore** [comment]
Nothing like that. 
Maybe there's some debug mode to catch such behaviour?

**Comment by Drive4ik** [comment]
In the add-on settings there is a DEBUG mode.
Try turning it on, and restart the browser several times. Try to repeat the bug. Logs are saved only in the last launch of the browser.
Turn off DEBUG and save the log file. You can mail it to me.

**Comment by Intenditore** [comment]
Hi!
I hope I caught the thing. Third pinned tab "disappeared", it unloaded itself and appears blank, no history, no address 
[STG-debug-logs.zip](https://github.com/Drive4ik/simple-tab-groups/files/4375273/STG-debug-logs.zip)

**Comment by Drive4ik** [comment]
I looked at the logs and saw that you have a tab that clears, has a container: firefox-container-6
Is it repeated with pinned tabs without containers?
I also noticed that according to the logs, FF sends events to change the state of the tab, and they are all correct. That is, the correct url is there, but for some reason, after loading this tab, the browser can no longer give its url, or rather gives an empty url.
By the logs, I see that you are not doing anything with this tab, you can only see that it is being updated.
I can’t say with certainty that this is happening, but I can say that the addon works with pinned tabs to a minimum. With backup for example.

**Comment by Intenditore** [comment]
What could it be if not your addon? I didn't install anything but STG for a long time and never had such problems before

**Comment by Drive4ik** [comment]
If you do not answer my questions, I can not help you.
Now I don’t understand what you want from me.

**Comment by grahamperrin** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/569#issuecomment-604509742

> … the correct url is there, but for some reason, after loading this tab, the browser can no longer give its url, or rather gives an empty url …

Maybe Mozilla bug [1695346 - Discarded hidden tab's URL is "about:blank" after moving the tab to a new window](https://bugzilla.mozilla.org/show_bug.cgi?id=1695346)

**Comment by nekohayo** [comment]
Or maybe this could be [Mozilla bug 1727569: Firefox selects and scrolls to the last tab when hiding a tab](https://bugzilla.mozilla.org/show_bug.cgi?id=1727569)

Other than that, beats me, I haven't experienced other issues on my end.

**Comment by grahamperrin** [comment]
1727569 is interesting, thank you! 

It _might_ also explain another symptom (with steps that differ from [the opening post](https://github.com/Drive4ik/simple-tab-groups/issues/569#issue-586477133)) that bugged me frequently for months. Maybe less frequent recently. (I'll not attempt to describe it here.)

**Comment by Drive4ik** [comment]
@nekohayo 
Just for clarification on the bug https://bugzilla.mozilla.org/show_bug.cgi?id=1727569

STG addon after moving a tab performs the function setActive, in it on line 98 you can see that the addon makes active the tab that was last active. If it was the last tab in the list of tabs - it will be active after moving the selected tab. That is, it is not the tab next to it that is activated, but the last active tab.

https://github.com/Drive4ik/simple-tab-groups/blob/70a2859fb90b702c094df8cd8656d01c439dada0/addon/src/js/tabs.js#L90-L111
