### ISSUE TITLE
hide tabs available in FF59.0a1?

### ISSUE THREAD

**Issue by tbiberlin01** [Drive4ik/simple-tab-groups#57]
Enable tab hiding?
in the latest version of Conex https://github.com/kesselborn/conex 
the following text was found: 
"Conex uses a feature which only exists in Firefox >= 59.0a1 updated after the 19th of January 2018.
At the moment, tab hiding has to be enabled manually: In the location bar, type in `about:config`, filter for `extensions.webextensions.tabhide.enabled` and set the value to `true`"

not saying copy it, but having a look to might a first step to solve the "close" not "hide" issue and all the workarounds we need to perform. 
( if i understand it right this is the nightly version, right ? ) .. any option/idea to get this into the dev.version or feedback from mozilla ? )

**Comment by gaddman** [comment]
@Drive4ik is already working on it, tracked under issue #2.
