### ISSUE TITLE
Loop when loading a page on a No Container tab in a container group

### ISSUE THREAD

**Issue by lextatic** [Drive4ik/simple-tab-groups#570]
**Describe the bug**
When using a group that is assigned to a container, if you don't check to change the container automatically and try to open a new tab as a "No Container" tab. Trying to load anything in this recently created tab will cause it to start a closetab/newtab loop.

**To Reproduce**
1. Create a new Group and open it;
2. In the group options, under "Always open tabs in container" select a container different from "No Container";
3. Uncheck "If the container is different from the selected on - change the container";
4. Open a new Tab with No Container (Ctrl+T or any other mean);
5. Try to load any page on this recently opened tab (google for example);

**Expected behavior**
The page loads normally, the tab continues as a No Container tab.

A feature request would be to have Ctrl+T open tabs on the new container, but this No Container bug would still exist.

**Desktop:**
 - OS and version: Windows 10
 - Firefox version: 74.0 (64-bit)
 - Simple Tab Groups version: v4.5

**Additional context**
Might have something to do with issue #555

**Comment by Drive4ik** [comment]
> Expected behavior
The page loads normally, the tab continues as a No Container tab.

No. This is the correct behavior. A tab without a container closes, and in its place a tab opens with this url in new container, since you told the group to do it. A tab without a container automatically falls under the rule "always open in this container".
Only tabs with containers other than the designated container are excluded, as well as tabs with a temporary container.

**Comment by lextatic** [comment]
Yea, sorry... suddenly I can't reproduce it anymore. I know I just updated the plugin today and I'm sure the loop thing was happening before and after the update. Strangely it's not happening anymore and I don't remember closing the browser or anything.

The expected behavior should be the one you mentioned.

**Comment by Drive4ik** [comment]
Nothing wrong. Actually there was such a problem, only in version 4.5 it was fixed. The version confused me. Apparently you saw an error, started to create a bug, and the add-on was updated at that time, and you took a new version where this bug is no longer there. 😄
