### ISSUE TITLE
[Feature Request] Move tabs to the Right/Left to group option

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [Drive4ik/simple-tab-groups#573]
**Problem:**

I often get distracted by new problem and start researching on it, so a lot of new tabs gets open. But then i have to  put this problem aside and return to previous task. If i want to continue researching on it later, for now i have to move each tab to the group separately.

**Solution:**

It would be great to have new option in menu, like "Move tabs to the Right/Left to group". That will move all tabs to the right/left from the tab(including it) to selected/new group. So, all newest open tabs can be moved to the same group by one click.

**Comment by Drive4ik** [comment]
I don’t quite understand what you are saying.
To move many tabs to another group, you can use the Shift or Ctrl button to select the desired tabs, and use the context menu to move them to a new group.
This works both on the tabbar and in the popup window.
If you want to move many tabs to the end of the group, you can also select them, and use the context menu to move to the end or the beginning of the list, this is available without an addon.
![изображение](https://user-images.githubusercontent.com/7843031/79497046-bc592b00-802f-11ea-9724-2a539d85aca2.png)

**Comment by GrigoriyMikhalkin** [comment]
@Drive4ik I see, thanks for pointing at that, didn't knew that i can select multiple tabs and move them to group. That's actually partially solves my problem.

Initially, what i wanted, is analogue of `Close Tabs to the Right` button, that would move all tabs to the right(so i don't have to manually select them) to group, instead of closing them:
![firefox_context_menu_ss](https://user-images.githubusercontent.com/3637857/80278853-e5e21880-86f9-11ea-8db1-f092534c7bc8.png)

**Comment by Drive4ik** [comment]
I don’t understand anything anyway)
How can I move ALL tabs to the right?
They did not change their position, since they were all displaced. 😄

**Comment by GrigoriyMikhalkin** [comment]
Ah, i poorly expressed myself. What i meant is to move tabs that are located to the right from selected tab to group. So if there would be a function, it would be like `(moveToGroup (all tabs to the right))` not `(movePosition ((all tabs), (to the right)))` )

**Comment by Drive4ik** [comment]
It seems to understand. You want a button that moves all the tabs on the right (left) to another group. Correctly?
If so, I don’t know how to do it yet. Because in the navigation menu you select the group where to move the tabs, but you can’t choose the option - move the tabs on the left or the tabs on the right ... It’s difficult ... I don’t even know how to implement this, and so it would be clear to the user and not complicate him simple actions to move ...

**Comment by GrigoriyMikhalkin** [comment]
> You want a button that moves all the tabs on the right (left) to another group
Yep, that's correct.

From UI perspective, maybe add option here:
![mtge](https://user-images.githubusercontent.com/3637857/81098197-531b5800-8f09-11ea-95d3-f8cfc23ae979.png)
And, on click, open list of available groups?

I'm not sure how hard to implement all this technically, but i could look into it if that's ok.

**Comment by Drive4ik** [comment]
This is not yet feasible. I will close the ticket, but I will keep in mind. If I come up with something that will be convenient and logical and understandable, I’ll do it
