### ISSUE TITLE
when reopening a group, the tabs have changed position from 123 to 321, why?

### ISSUE THREAD

**Issue by swealpha** [Drive4ik/simple-tab-groups#574]
**Describe the bug**
When reopening a group (window), the tabs have changed position from 123 to 321, why?

**To Reproduce**
1. Fill a group with tabs, remember the position, for example from left to right (top to bottom on sidebar) 1. a.com 2. b.com 3. c.com.

2. close the window

3. reopen window with correct group

4. now the tabs have switched position to 1. c.com 2. b.com 3. a.com

**Expected behavior**
Expected behavor should be that the tabs in the group should remain with there positions, 1. a.com 2. b.com 3. c.com.

**Desktop (please complete the following information):**
 - OS and version: [mac os el capitan macbook pro 2014]
 - Firefox version: [74,  64bit]
 - Simple Tab Groups version: 4.4.2.5

Thank you very much!

**Comment by swealpha** [comment]
nooooo, i see it is because i have another addon that opens tab on "right of active tab".
😢 👎 

Is it possible in someway make it possible so that Simple-tab-groups open the tabs in correct position even due i have this another addon that opens tab on the right?

Thank you very much! 

YOU are the reason we use FireFox.

**Comment by Dexter9313** [comment]
I can confirm enabling this option fixes the problem. I think you can close this issue.
