### ISSUE TITLE
[Feature] Add Manage groups & Settings buttons to sidebar

### ISSUE THREAD

**Issue by jul1u5** [Drive4ik/simple-tab-groups#575]
**Is your feature request related to a problem? Please describe.**
Currently, the only way to access "Manage groups" and STG "Settings" pages are via the extension's popup. Although it seems that the sidebar has the same functionality as the popup, the two buttons I mentioned are missing in the sidebar.

The buttons I am talking about:
![STG popup screenshot](https://user-images.githubusercontent.com/8469822/77860671-0ad98d80-7219-11ea-8b44-3ec74fa172ef.png)

**Describe the solution you'd like**
I would like the "Manage groups" and "Settings" button to be in the sidebar like they are in the popup.  

**Additional context**
I find the sidebar to be more convenient as it does not close when I click on something, so if these buttons would be implemented I would be able to solely use the sidebar to interact with the extension, without needing to pin the extension's popup in Firefox's toolbar.

**Comment by Drive4ik** [comment]
To prevent the popup from closing, you can turn off this option in the add-on settings.
![изображение](https://user-images.githubusercontent.com/7843031/79497794-fbd44700-8030-11ea-9a8b-0cd7a2baf403.png)

About your request - done
![изображение](https://user-images.githubusercontent.com/7843031/79502242-03e3b500-8038-11ea-8e82-84703f502d61.png)
