### ISSUE TITLE
Ctrl+Tab cycles between tabs across groups

### ISSUE THREAD

**Issue by jul1u5** [Drive4ik/simple-tab-groups#576]
**Describe the bug**
I've enabled the option for the Ctrl+Tab to "cycle between tabs in the recently used order".

I would expect that the tabs would cycle only in the current group. However, that's not the case and Ctrl+Tab cycles between all the tabs in all of the groups.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'Firefox preferences'
2. Enable the setting:
![Firefox Preferences](https://user-images.githubusercontent.com/8469822/77861664-e7b1dc80-721e-11ea-9f2a-a17f4f071f6c.png)
3. Change STG group
4. Press Ctrl+Tab

**Expected behavior**
I am not sure if the issue is with STG or Firefox itself. But I would like that the Ctrl+Tab shortcut would only cycle between tabs in the current group.

**Desktop (please complete the following information):**
 - OS and version: NixOS 20.09 (Linux)
 - Firefox version: 74.0
 - Simple Tab Groups version: 4.5

**Comment by falolaf** [comment]
Here is a FF bug for the issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1488168

**Comment by Drive4ik** [comment]
@jul1u5 This should be done by the FF developers.
@falolaf I even commented on this ticket for a long time... But as we see, to no avail.

**Comment by jul1u5** [comment]
Oh, ok. Hopefully this gets fixed sooner rather than later.

Should we keep this issue open until the fix arrives or close it now?

**Comment by Drive4ik** [comment]
I close this issue. Once the developers FF fix this bug, everything will work immediately in the addon. :wink:
