### ISSUE TITLE
Keyboard shortcut name is not displayed correctly

### ISSUE THREAD

**Issue by jtagcat** [Drive4ik/simple-tab-groups#578]
**Describe the bug**
`__MSG_manifest_shortcut_browser_action_description__` Should probably have to have the variable set.
![image](https://user-images.githubusercontent.com/38327267/77900627-da700e80-726d-11ea-887a-77df40139a1e.png)

**Desktop**
 - Firefox version: 75
 - Simple Tab Groups version: 4.5

**Comment by Drive4ik** [comment]
You were wrong, this is another addon
