### ISSUE TITLE
F2 is hardcoded for group renaming, can't be unset/remapped

### ISSUE THREAD

**Issue by kparal** [Drive4ik/simple-tab-groups#579]
**Describe the bug**
Hello, since STG 4.5, the `F2` key is hardcoded to "rename group/tab". The problem is that that shortcut can't be unset or remapped, it seems. I actually use `F2` for opening the popup, and I'd like to continue doing so. The first `F2` opens the popup, that's fine, but pressing `F2` doesn't close it again, as it used to, but now shows `Rename group` dialog:
![stg-rename-dialog](https://user-images.githubusercontent.com/755451/77919520-93017680-729d-11ea-9a13-494db3e9312a.png)

I went to `Manage Extensions Shortcuts` and I see `Rename group` as empty, so I can't "delete" that shortcut:
![stg-rename](https://user-images.githubusercontent.com/755451/77918690-8597bc80-729c-11ea-8a26-733217cf59d7.png)

If I override that shortcut with something else, it still doesn't see to free the `F2` shortcut. `F2` still wants to rename the group, every time.

Please don't make `F2` hardcoded, let users delete that shortcut and replace it with something else. Thank you!

**To Reproduce**
1. Open and close the popup with `F8`, see that it works (even for closing)
2. Go to `Manage Extension Shortcuts`
3. Set `Open popup` to `F2`
4. Try to open and close the popup with `F2`, see that you can open it but not close it, because it wants to rename the group
5. Try to unbind `F2` from the "rename group" action, seems impossible

**Desktop (please complete the following information):**
 - OS and version: Fedora 32
 - Firefox version: 74
 - Simple Tab Groups version: 4.5

**Comment by SaltatorMortis** [comment]
cant confirm this on my system.
have you maybe set it inside about:addons>options>Hotkeys?

**Comment by kparal** [comment]
> have you maybe set it inside about:addons>options>Hotkeys?

Set what exactly? I haven't set a shortcut for `Rename group`, there's even a screenshot in my bugreport. I actually haven't set any shortcuts in there except for `Open popup = F2`. I also tested with a completely fresh Firefox profile.

I have found an interesting thing, though. `F2` closes the popup just fine, if I use arrow keys to move around at least once (even if I move the focus back to the current group). But if I simply hit `F2` to open popup and right away `F2` to close popup, `Rename group` dialog appears instead.

**Comment by SaltatorMortis** [comment]
sorry for the late response..
my question was if the "rename group" was set to F2 inside the Settings of the STG [about:addons>simple-tab-groups>tripple dots on the top right side>options/settings>Hotkeys] and not inside the firefox Manage Extensions Shortcuts 

at the time of writing i was on mobile thus havn't tested the F2 key, i only remembered that you could set shortcuts inside the addon options.
but after retesting i found out that its true. F2 is hardcoded to rename, F3 to search
inside `src/popup/popup.vue` is the line `@keydown.f2.stop.prevent="tryRenameGroup"`
a removal of this line should fix your issue

**Comment by Drive4ik** [comment]
@kparal I understand what you're talking about, but it’s done on purpose. These hotkeys do not work in a popup window.

**Comment by Drive4ik** [comment]
You can close the popup by pressing `Esc`

**Comment by kparal** [comment]
I know that I can use `Esc`. But it's no longer as comfortable to use as before. Why do those hotkeys need to be hardcoded? Can you please reconsider?

**Comment by Drive4ik** [comment]
> Why do those hotkeys need to be hardcoded?

Because customizable hotkeys in the addon do not affect its pages (popup / sidebar), but affect only the main window with tabs.

For example. You have loaded group 1 in the window, you open a popup, select (focus) group 3 and press F2 (rename).
What then should happen? Renaming group 1 because it is loaded in the window, or group 3 because you put focus on group 3 in the popup? 

> Can you please reconsider?

In order to avoid misunderstandings, I hardcoded it. And so far I will not change.
