### ISSUE TITLE
Can not install into FF 58

### ISSUE THREAD

**Issue by dbrnz** [Drive4ik/simple-tab-groups#58]
Using the latest Firefox, the Add Ons [installation page](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/) reports `This add-on requires a newer version of Firefox`.

![screen shot 2018-01-24 at 9 15 56 am](https://user-images.githubusercontent.com/239220/35298599-92c3c58e-007a-11e8-8131-176da782807e.png)

**Comment by Drive4ik** [comment]
Maybe you has FF 52? Or some other addon change your User-Agent in browser.
https://www.whatismybrowser.com/

**Comment by dbrnz** [comment]
Hmm, I'm definitely running FF 58 under macos with all add-ons disabled yet What's my Browser reports ff 52 under Windows... Debugging hints would be appreciated!

![screen shot 2018-01-25 at 8 00 28 am](https://user-images.githubusercontent.com/239220/35352322-803d51fc-013b-11e8-8a12-e7f208ca3913.png)

![screen shot 2018-01-25 at 8 00 45 am](https://user-images.githubusercontent.com/239220/35352336-87cfa7e4-013b-11e8-8939-eea364ee43a4.png)

**Comment by dbrnz** [comment]
Running FF in Safe Mode didn't change the user agent string.

Fixed by doing `Refresh Firefox...` from `about:support`.
