### ISSUE TITLE
Sidebar tab positions don't match real tab positions

### ISSUE THREAD

**Issue by kparal** [Drive4ik/simple-tab-groups#580]
**Describe the bug**
Ever since STG 4.5, if you open new tabs, the sidebar often shows them in a completely wrong position. Here is an example with an empty Firefox profile, only STG installed:

![stg-sidebar](https://user-images.githubusercontent.com/755451/77924837-7d437f80-72a4-11ea-909d-aeee3556c251.png)

Compare the position of the first 3 tabs on the top vs in the sidebar.

Here's a video:
[stg-sidebar.mkv.zip](https://github.com/Drive4ik/simple-tab-groups/files/4403316/stg-sidebar.mkv.zip)

Reopening the sidebar fixes the position of the tabs.

**To Reproduce**
1. Open some tabs using the middle mouse button or the context menu "open in a new tab", so that they are opened directly next to the current tab. (Alternatively, use an extension like "Open tabs next to current" to see that behavior even for newly opened empty tabs).
2. See the sidebar doesn't reflect actual tab position
3. Reopen the sidebar
4. See the sidebar now properly showing tab positions (until you open new ones)

**Desktop (please complete the following information):**
 - OS and version: Fedora 31
 - Firefox version: 74
 - Simple Tab Groups version: 4.5

**Comment by saithis** [comment]
I have the same problem with:
    OS and version: Windows 10
    Firefox version: 76b1
    Simple Tab Groups version: 4.5

**Comment by Drive4ik** [comment]
Fixed, please wait next release
