### ISSUE TITLE
What's the difference between "discarding" a group, "unloading" a group, and "archiving" a group?

### ISSUE THREAD

**Issue by dlobue** [Drive4ik/simple-tab-groups#582]
None of these terms are defined anywhere. Some documentation would be really helpful!

Thanks!

**Comment by klint** [comment]
Hi

My understanding is the following:
- Discarding a group: this operation simply unloads the tabs in the group from memory
- Unloading a group: this operation "hides" the *current* group and displays the ungrouped tabs if any
- Archiving a group: this operation "freezes" the group and prevents the user from displaying it as it cannot be selected anymore in the popup or in the "move tab to group" feature. Until it is unarchived by the user.

I hope this helps

**Comment by dlobue** [comment]
> Hi
> 
> My understanding is the following:
> 
>     * Discarding a group: this operation simply unloads the tabs in the group from memory
> 
>     * Unloading a group: this operation "hides" the _current_ group and displays the ungrouped tabs if any
> 
>     * Archiving a group: this operation "freezes" the group and prevents the user from displaying it as it cannot be selected anymore in the popup or in the "move tab to group" feature. Until it is unarchived by the user.
> 
> 
> I hope this helps

That is very helpful, thanks! Still not sure under what circumstance I would use the unload feature though.

Would be useful if you could continue to move tabs to archived groups. Also would be nice if clicking on the archived group would restore it; this would save the user 3 clicks.

**Comment by Drive4ik** [comment]
> Would be useful if you could continue to move tabs to archived groups. 

This is not possible because it breaks the logic of archive groups. Perhaps in the future I will revise, and come up with something

> Also would be nice if clicking on the archived group would restore it; this would save the user 3 clicks.

This is impossible, because it breaks the logic of the archive group, because there can be many tabs, for this it was created.
