### ISSUE TITLE
Option to hide archived groups from main list in pop-up and "move to" menu

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#583]
Today, unused groups can be archived but they still clutter the lists of groups that are mostly used (pop-up list and "move to" option list, in right-click menu).
It could be useful to have an option to hide archived group from those lists. 
And instead, in the pop-up, the archived groups could have their own section below the main list.
Thanks :)

**Comment by Drive4ik** [comment]
Hi. I removed archived groups from the move list, and others. But I left it in the popup, because there is no way to make a separate UI for archive groups yet.
