### ISSUE TITLE
Feature request: Keyboard shortcut for opening popup

### ISSUE THREAD

**Issue by joepie91** [Drive4ik/simple-tab-groups#584]
**Is your feature request related to a problem? Please describe.**
The search feature in the extension's popup is quite useful (especially as it auto-focuses the search box once opening the popup, and the results layout is easy to understand), but it takes a mouse interaction to open it.

Being able to assign a keyboard shortcut to it, would make working with it much faster.

**Describe the solution you'd like**
Adding an option in the keyboard shortcut action list for "Open extension popup".

**Describe alternatives you've considered**
I've not found any alternative approaches, besides the awkward one (opening the popup with the mouse).

**Additional context**
n/a

**Comment by sjsrey** [comment]
You can set shortcuts to extensions with [this](https://winaero.com/blog/assign-keyboard-shortcuts-extensions-firefox/).

**Comment by joepie91** [comment]
@sjsrey Thanks! Seems it's actually already bound to F8.

Perhaps the shortcut settings page in this extension itself should be updated to point there, then, or even be deprecated entirely? It seems that the other actions can also be configured from there.

**Comment by sjsrey** [comment]
Yes, I have a laptop that does not have dedicated Fn keys so I wanted to use a different shortcut (CTRL-8) which works great for my purposes.

**Comment by Drive4ik** [comment]
That's right)
