### ISSUE TITLE
SideBar Shortcut/Hotkey

### ISSUE THREAD

**Issue by Aetylus** [Drive4ik/simple-tab-groups#589]
While the F8 key opens up the addon toolbar and there is an option to customize shortcuts for various actions, there doesn't seem to be a way to open the SideBar menu for Simple Tab Groups through a shortcut.

If one wants to use the SideBar regularly, they would need to press the SideBar toolbar button or open up an existing SideBar option like Bookmarks (Ctrl+B) or History (Ctrl+H), then further navigate to the Simple Tab Groups option from the drop down.

**Comment by Drive4ik** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/584#issuecomment-612093279
