### ISSUE TITLE
When moving a tab to a different group, the notification does not automatically disappear

### ISSUE THREAD

**Issue by terminalmage** [Drive4ik/simple-tab-groups#59]
When moving a tab to a new group, there is a notification in the upper-right letting you know that the tab was moved, and letting you switch to that tab if you click the notification. However, this notification stays up forever, or until clicked. This means that I need to click the X in the corner of the notification to close it without switching to a different tab group.

The notification should automatically disappear after a few seconds, and failing that, there should be an option to disable the notification completely.

**Comment by Drive4ik** [comment]
This notification will be closed by browser after ~ 30 sec. If it doesn't happens - try re-test this bug with new FF profile.
Most likely it is to change setting of the FF, this addon hasn't access to these setting.

**Comment by Drive4ik** [comment]
Please, re-test this issue in latest version v2.3.5

I added auto close notification after 30 sec

**Comment by terminalmage** [comment]
Just tested on 2.3.6, and it is disappearing automatically now, thanks. I think it took less than 30 seconds to disappear, actually. It would be nice if this were configurable, but since the original issue as reported is resolved, I'll go ahead and close this. Thanks!

**Comment by Drive4ik** [comment]
Reduced to 20 seconds, will be in the next update :)
