### ISSUE TITLE
When I enable the extention it hides all tab on a window

### ISSUE THREAD

**Issue by sguergachi** [Drive4ik/simple-tab-groups#591]
**Describe the bug**

**To Reproduce**
Enable extention
All tab on window become hidden
No way to unhide except by disabling extention

**Expected behavior**
Don't hide tabs.
**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: [e.g. Windows] Windows 10
 - Firefox version: [e.g. 63] Firefox 76
 - Simple Tab Groups version: [e.g. 3.0.8] Latest version

**Additional context**

**Comment by iTeaMaster** [comment]
When first installing the extension, there are no groups. As I see this, the requested behaviour here is that all tabs would be moved to a default group so they don't become hidden.

**Comment by sguergachi** [comment]
Correct

- Sammy Guergachi
________________________________
