### ISSUE TITLE
Streamlined backup

### ISSUE THREAD

**Issue by grahamperrin** [Drive4ik/simple-tab-groups#595]
### Current routine

Extension version `4.5`: 

1. click the toolbar icon
2. click the preferences icon
3. click the _Backup …_ tab
4. click _Create backup_
5. in the dialogue, double-click the required folder
6. click _Save_.

I typically perform a manual backup before every quit of Firefox. 

### Feature request

I'd like single-click backup. 

Realistically: there's nothing (no separate toolbar icon) on which a single click can be effective. Instead, maybe: 

* add context menu functionality to the toolbar icon
* have **Backup** as a menu option. 

### Background

#36

To the best of my knowledge, no session manager extension is compatible with Simple Tab Groups.

**Comment by Drive4ik** [comment]
If you select the backup option to the file once a day in the add-on settings, in this (and only this) case, the addon will backup every 2 hours and overwrite the file by the current date. You have a fresh backup with an interval of 2 hours.

> To the best of my knowledge, no session manager extension is compatible with Simple Tab Groups.

If you need to restore a session or something else, disable the STG addon, restore the session and enable the STG addon. Otherwise, the connection between the group and the tab will be lost, since it is in session, and the addon has no idea that another addon will now restore or close the tabs. That is the problem.

**Comment by grahamperrin** [comment]
Thanks, the intention is to have a streamlined backup **on demand** (in addition to scheduled backups). 

I once had a corrupt session, resulting from a kernel panic, recovery from which quite painful.

I already have auto-backup set to one hour so (for example) 204 files in `STG-backups-FF-76.0` and 41 so far in `STG-backups-FF-76.0.1`. I'll occasionally manually weed most of the oldest backups.

**Comment by Drive4ik** [comment]
I added a backup hotkey. #602 
It will not call the save file window, it will just backup based on the backup settings of the addon. Will it be okay?

**Comment by grahamperrin** [comment]
Sorry, I only just read your comment. 

I don't see the feature: 

![image](https://user-images.githubusercontent.com/192271/94837999-dbe0e600-040c-11eb-930b-8caaccd4b287.png)

**Comment by Drive4ik** [comment]
@grahamperrin 
Sorry for the long absence, I made changes but I haven't released the new version yet. There will be a new version soon and will include this change.

**Comment by grahamperrin** [comment]
Found (thank you). 

For now, I choose <kbd>Control</kbd>-<kbd>Alt</kbd>-<kbd>B</kbd>: 

![image](https://user-images.githubusercontent.com/192271/108593147-f25eee00-7369-11eb-88d4-900957fd53b3.png)

**Comment by grahamperrin** [comment]
PS 

> Sorry for the long absence

No need to apologise!
