### ISSUE TITLE
Choose backup location

### ISSUE THREAD

**Issue by goolied** [Drive4ik/simple-tab-groups#596]
On MacOS, STG backs up to the downloads folder. As far as I can tell there is no way to change the backup location. Is it possible to include that option in future updates?

**Comment by ahnion** [comment]
It's the same on Windows, and I wholeheartedly support adding the option to choose another location. The download folder is for downloads. Settings should logically be in the Firefox profile somewhere, even if they're backups of settings.

**Comment by Drive4ik** [comment]
Addons do not have the ability to change the file save folder, this is done to ensure security. In the addon settings, you can only change the name of the folder and that's it ..
