### ISSUE TITLE
Tabs created within few seconds after the browser launch get send to the "Other Tabs" group.

### ISSUE THREAD

**Issue by fusuyfusuy** [Drive4ik/simple-tab-groups#597]
**Describe the bug**
When the browser launches, if i don't wait for a few seconds but open new tabs immidiately, that newly opened tabs don't stay in the active group but get regrouped under the "Show Other Tabs" section. After few seconds, it behaves as expected. I have 9 groups with 40+ tabs total. I can share the debug file. 

**To Reproduce**
1. Launch Firefox. It doesn't matter if the launch is cold or hot.
2. Immidiately open new tabs.
3. Wait few seconds.

**Expected behavior**
Newly opened tabs should stay in the active group.

**Desktop (please complete the following information):**
 - OS and version: Windows 10 Home Single Language 1909
 - Firefox version: 75
 - Simple Tab Groups version: 4.5

**Comment by Drive4ik** [comment]
This bug was fixed in 23db8a479c21e50c5d817bbfd34c8ddc4d690211
please wait next release
