### ISSUE TITLE
Catch tab regex fails on www subdomain

### ISSUE THREAD

**Issue by iTeaMaster** [Drive4ik/simple-tab-groups#598]
**Describe the bug**
The catch tab regex functionality works for arbitrary subdomains (e.g. 'gist.github.com'), but not for the 'www' subdomain (e.g. 'www.youtube.com'). Normally, the domain itself is sufficient, but for example when I want to differentiate between 'www.youtube.com' and 'music.youtube.com', that is not possible, since using only 'youtube\\.com' catches both.

**To Reproduce**
1. Create group with catch tab regex of the pattern 'www\\.example\\.com'
2. Open 'www.example.com' in any other group
3. The tab doesn't get moved to the group that has the catch expression set

**Expected behavior**
When using the regex as above, the tab should be moved to the corresponding group regardless of the subdomain.

**Screenshots**
none

**Desktop:**
 - OS and version: Windows 10
 - Firefox version: 75.0
 - Simple Tab Groups version: 4.5

**Additional context**
Probably linked with [addon/src/js/edit-group.vue around line 66–67](https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/js/edit-group.vue#L60):
```
...
61            currentDomainWithSubdomainsRegexp() {
62                if (this.currentTabUrl) {
63                    let parts = this.currentTabUrl.hostname.split('.');
64
65                    if (parts.length > 2) {
66                        if (parts.length === 3 && parts[0] === 'www') {
67                            return;
68                        }
...
```
This could maybe also be addressed via an approach that sorts the regular expressions of all groups based on their specificity before moving tabs. Also it could be implemented alongside with folders/nested groups (#586, #594) so that one could assign a group to catch 'youtube.com' and then create subgroups to catch the subdomains.

**Comment by Drive4ik** [comment]
Please check group option `Sticky group`.

**Comment by iTeaMaster** [comment]
I can't reproduce it now, regardless of the sticky group option. I'll close it for now.
