### ISSUE TITLE
Keep tab icons when closing a window

### ISSUE THREAD

**Issue by Dexter9313** [Drive4ik/simple-tab-groups#599]
**Is your feature request related to a problem? Please describe.**
Closing a tab group window will destroy their icons. As icons are an important visual cue to navigate across large amount of tabs I think some effort should be made to retain this information. Right now loading every tab in the group (clicking on all of them) is the only way to get the icons back (firefox downloads them again).

**Describe the solution you'd like**
When closing a window, STG should force firefox to retain the icons of the closed tabs in cache somehow, as it does when just switching groups from the main window.

**Comment by Drive4ik** [comment]
What version of STG you are use? Tab favicons already save in tab session, and after close window addon restore tab icons. I can't replicate this issue. (v4.5)

**Comment by Dexter9313** [comment]
I'm using v4.5 as well. Steps to reproduce for me : right click on a tab group in the list, then select "Open in a new window". Close this window, the tab group you selected won't have favicons anymore when opened (either by switching to it or opening it in a new window). This bug only occurs when opening the group in a new window, not on group switching within the same window. I don't have much other addons installed so I don't think it would come from any of them. How could we investigate this further ?

**Comment by Drive4ik** [comment]
Perhaps you mean the tabs on the tab bar, and not in the addon? In this case, I can say that this is a feature of the browser and webextensions. When you close a window, or a tab, it really closes, and the addon cannot affect this. But the STG addon restores tabs in another window, and yes, they are without icons. Because they are restored in the "unloaded" mode, that is, the tabs are not loaded. And since the tabs are not loaded, there are no icons.

**Comment by Dexter9313** [comment]
Ok so we are on the same page here. Is there nothing STG could do about it ? Like backing the favicons itself or something ? Could be an option if it uses significant disk memory.

**Comment by Drive4ik** [comment]
Unfortunately, the addon does not have the ability to install favicon.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/update#Syntax

**Comment by grahamperrin** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/753#issuecomment-787505828
