### ISSUE TITLE
Dropbox crash

### ISSUE THREAD

**Issue by arreposao** [Drive4ik/simple-tab-groups#600]
**Describe the bug**
When trying to open dropbox always crashes

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: [e.g. Windows]
 - Firefox version: [e.g. 63]
 - Simple Tab Groups version: [e.g. 3.0.8]

**Additional context**

**Comment by Drive4ik** [comment]
Can you give more information?

**Comment by arreposao** [comment]
I use Firefox to connect to a dropbox account shared by my working team, yesterday i installed simple tab plugin and since then when i try to access to dropbox firefox gives me this message
<img width="776" alt="Screenshot 2020-05-07 at 16 00 50" src="https://user-images.githubusercontent.com/64969639/81303437-f8eed400-907b-11ea-9e4e-a9f8f940a2b1.png">
I can access dropbox from safari, and my other coworkers have no problems to connect to the account.

**Comment by Drive4ik** [comment]
It is unlikely that the addon is to blame for this, the addon does not have such permission. 
Turn off the addon on the `about:addons` page and try again

**Comment by Drive4ik** [comment]
I also advise you to check the proxy settings

**Comment by arreposao** [comment]
You're right, the problem continues after disabling the addon, i will try to check the proxy as you suggest.
Thanks for the advise
