### ISSUE TITLE
Conflict with "Tree-style tab" add-on : Tree structure flattened when opening new window.

### ISSUE THREAD

**Issue by Elaws** [Drive4ik/simple-tab-groups#601]
## Short description

Tree structure created with Tree Style Tab add-on are flattened when a new Firefox windows is opened, with "Simple Tab Groups" add-on installed.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install "Tree Style Tab" (TST) and "Simple Tab Groups" (STG) (versions indicated below).
 3. With STG, create 4 tab groups and add shortcuts to switch between them (e.g. : Alt + & to load custom tab group n°1, ..., Alt + ' to load custom tab group n°4).
 4. In each of these tab groups, create a simple tree structure with TST. For e.g. :

Folder A
- Subfolder 1
-- URL i
-- URL ii

Folder B
- Subfolder 1
-- URL i
--- URL ii
- Subfolder 2
-- URL i

5. Open a new Firefox window and switch between tab groups defined in STG using your shortcuts.

6. Close one of the two opened Firefox windows.

7. Switch between tab groups in the remaining Firefox window : one or all the trees created in TST may display the following message (it is possible that these messages are displayed at step 6) :

> "X" tabs are opened in a time. Do you want them to be grouped in a tree?
> -> Group tabs.
> -> Keep tabs flat

## Expected result

The tree structure should not be modified.

## Actual result

No matter which answer you choose in step 7, one or all of your trees are now flattened :

Folder A
Subfolder 1
URL i
URL ii
Folder B
Subfolder 1
URL i
URL ii
Subfolder 2
URL i

TST + STG is very useful but since opening a new Firefox window is a frequent use case, tree structures keep getting flattened.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 74.0.1
 * Version (or revision) of Tree Style Tab: 3.4.8
* Version of Simple Tab Groups : 4.4.2.5

**Comment by Elaws** [comment]
Issue already reported on TST's github ([issue 2546](https://github.com/piroor/treestyletab/issues/2546#issue-593799975)).

**Comment by piroor** [comment]
The easiest way is: adding some codes to STG to get/set tree structure of tabs as I described at https://github.com/piroor/treestyletab/issues/2546#issuecomment-611976143 But I agree that it is too TST specific.

The second way is: reproduce relations of tabs with their `openerTabId`. TST is designed to construct tree structure based on the information, so if STG open tabs with their `openerTabId` it may improve compatibility with all other addons using the information, not only TST.

**Comment by byblo** [comment]
On this new STG version (4.5.2), when archiving a group, it seems to save the trees somehow, but once restoring the same group from his archive, the tabs order and the tree are totally incorrect. Not sure if this new problem is related to the STG or the TST addon.

This problem is also reported at the TST's topic: https://github.com/piroor/treestyletab/issues/2673
