### ISSUE TITLE
[Feature Request] HotKey for 'Create backup'

### ISSUE THREAD

**Issue by Solid-Ice8** [Drive4ik/simple-tab-groups#602]
**Is your feature request related to a problem? Please describe.**
I would like to be able to use `HotKey` to "Create A Backup".

**Describe the solution you'd like**
In the `HotKey` section, add a new feature for creating backup (Ctrl / Alt / Shift + `)

**Describe alternatives you've considered**
Since WebExtention doesn't allow for changing directories or any type of bypassing:

`./STG-Backups/STG-backups-FF-76.0.0` or `../STG-Backups/STG-backups-FF-76.0.0`

This is an alternate way of choosing a new destination for saving the backups.

**Additional context**
This add-on has been awesome overall and I've suggested many people use it. It would've been more helpful if WebExtention allowed changing directories.

The past week, FireFox upgraded 3 times. Now STG has 3 different backup folders... 75.0, 76.0, and 76.0.1. Well, not that I mind but, I'm an organized person so...to me, this is a little messy.

**Comment by Drive4ik** [comment]
> I would like to be able to use HotKey to "Create A Backup".

do you mean backup without a window to choose where to save the backup file? That is, as if it was called in time?

> ./STG-Backups/STG-backups-FF-76.0.0 or ../STG-Backups/STG-backups-FF-76.0.0

This is not possible because it violates the security of the user and the system.

> Now STG has 3 different backup folders... 75.0, 76.0, and 76.0.1

You can simply rename the backup folder to `STG-Backups` in addon options, and that's it, it will no longer change its name to `STG-backups-FF-76.0.0` etc.

**Comment by Drive4ik** [comment]
added hotkey here:
![изображение](https://user-images.githubusercontent.com/7843031/81934770-2bf31380-95f8-11ea-9b14-3e957fbdeffa.png)
