### ISSUE TITLE
FF switches to last loaded tab after tab closing instead of right one

### ISSUE THREAD

**Issue by Intenditore** [Drive4ik/simple-tab-groups#603]
When the tab is closed FF switches to last loaded one instead of the one it should. The one it should have been switched to becomes a "zombie" tab appearing as loading but in reality it's doing nothing. 
Pretty disturbing behaviour
Video demo and log containing at least one such error are attached 
[STG_tabLoadError.zip](https://github.com/Drive4ik/simple-tab-groups/files/4609477/STG_tabLoadError.zip)

**Comment by Drive4ik** [comment]
Tell me, what other add-ons do you have that control the behavior of tabs?

**Comment by Intenditore** [comment]
Unload tabs 
https://github.com/NiklasGollenstede/unload-tabs
But I disabled it tested without while it's been turned off too - seems no changes.

**Comment by Drive4ik** [comment]
Ok, then can you tell me please, in more detail how you reproduce the bug? Which tab / group was active before closing the first tab? If possible, the video will be better visible.
