### ISSUE TITLE
STG popup contents too small 

### ISSUE THREAD

**Issue by kauesena** [Drive4ik/simple-tab-groups#605]
When using my external monitor, the size of the contents of the popup are hard to read. It would be nice to be able to scale it or increase the font size. 

I took screenshots for comparison between the contents scale of the firefox menu and the STG groups menu:
![Screenshot from 2020-05-13 13-18-08](https://user-images.githubusercontent.com/30255100/81838449-8323b600-951c-11ea-92ee-7952609ff200.png)
![Screenshot from 2020-05-13 13-18-02](https://user-images.githubusercontent.com/30255100/81838458-8454e300-951c-11ea-9696-d4bebe637212.png)

Thanks for creating this great extension.

**Comment by Drive4ik** [comment]
change default popup width from 432px to 450px
and added addon option to use full width, but it only 800px
https://developer.mozilla.org/ru/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups#Popup_resizing

![изображение](https://user-images.githubusercontent.com/7843031/81942146-6eb9e900-9602-11ea-8361-38bfb8d73da9.png)
