### ISSUE TITLE
How to take backup every 15min, not every 60min.

### ISSUE THREAD

**Issue by swealpha** [Drive4ik/simple-tab-groups#606]
Hello dear coder!

I would like to ask, how i can make Simple-tab-groups take backup every 15min instead of 60min.

I see it is only possible to choose between hours or days in the alternative dropdown, not minutes.

Thank you!

**Comment by Drive4ik** [comment]
Hi!
Unfortunately, no way.
But I make a hotkey for manual backup, it will be available in the next version.
https://github.com/Drive4ik/simple-tab-groups/issues/602#issuecomment-628604506
