### ISSUE TITLE
Add a button to hide archived groups from the panorama view

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#609]
**Is your feature request related to a problem? Please describe.**
Having lots of archived groups can clutter the panorama view with unnecessary information. One may prefer to hide the archived groups by default and show them on request :)

**Describe the solution you'd like**
Add a (persistent) check box at the top of the panarama view to "Show archived groups" and hide those groups by default.
This may be preferrable to an option setting (that would be too hidden).

Thanks

**Comment by Drive4ik** [comment]
Done)
