### ISSUE TITLE
When more than one window is opened, the app Icon color is the same on all of them.

### ISSUE THREAD

**Issue by thevladsoft** [Drive4ik/simple-tab-groups#61]
When more than one window is opened, the app Icon color is the same on all of them, which makes it a little confusing (not much, as you can still differentiate by the tabs).

I have checked and there are some addons that doesn't have this problem: tampermonkey and ublock can have icon active or deactivated and a small colored number in a corner, depending of the selected tab in each window.

Maybe a similar approach could work on STG? (though STG icons have a better look as they are right now).

**Comment by Drive4ik** [comment]
Tampermonkey and ublock use default browser "badge" functional to display the number of something.
I do not need to show the numbers, so I use a different way - svg icons.

**Comment by thevladsoft** [comment]
Yes, I thought so. Also svg icons allows to have better quality in compared with ff badges.
