### ISSUE TITLE
Can we get this extension for chrome

### ISSUE THREAD

**Issue by sdevineni** [Drive4ik/simple-tab-groups#610]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Drive4ik** [comment]
Unfortunately, not yet. Chrome does not support hiding tabs.

**Comment by JackKuo-tw** [comment]
@Drive4ik but how can some app like toby do so?

**Comment by rosenpin** [comment]
anyone knows of good alternative addons on chrome? this extension is the only reason I still use FF
