### ISSUE TITLE
Faster opening of links temporary containers or different groups

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#611]
**Is your feature request related to a problem? Please describe.**

I need to do a lot of clicking to properly manage tab openings in new containers. I often am browsing a site for which I've set up a container (Gmail / Google, Reddit, Twitter, etc), when I see a link to a third-party site. I'd like to open this link in its own temporary container. I can do so by right-clicking it and opening it in a group where all tabs open in temporary containers. Or, I can choose to open it in my Reddit (etc) group but right-click to select "Temporary container" from the STG container. This slows things down a lot.

**Describe the solution you'd like**
I would love a shortcut such as Alt-Click for example, where clicking on a link that way has a defined, customizable behavior (such as opening it in a temporary container). Or, any other solution that is fast.

**Comment by Drive4ik** [comment]
I would love to, but the addon cannot affect browser behavior. Even if I write a lot of code - it will be a lot of bugs, and still I can not cancel the behavior of the browser by clicking on the link. And then 2 tabs will open: one is opened by the browser in a regular container, and the second is opened by the addon ...

**Comment by mzguy** [comment]
How about a favorite group that has its own right-click context menu item, so users don't have to wade through their group list?

**Comment by mzguy** [comment]
Better yet... have a top-level context menu shortcut to open the link in the last group a tab was moved into. That way, it's easier to do in bulk when opening links.

**Comment by Drive4ik** [comment]
I understand your desire, but all that you say is absolutely not feasible, because webextensions api does not have such functionality

**Comment by mzguy** [comment]
Ok, thanks. I think an additional right-click menu option at the top would be possible, but I don't think it would help much if Firefox restrictions force to be with all the other groups.

Can you please clarify what the "Set this group as main" button does?

**Comment by Drive4ik** [comment]
If a group has regular expressions installed, a checkmark will appear at the bottom, when you turn it on, all tabs that do not match regular expressions will be moved to the main group.  That is, as it were, exceptions for the whole group.  If, for example, you indicated in a regular expression that there will only be YouTube.com in this group, all other calculations that are not YouTube will be moved to the main group.
Hopefully explained normally with a translator)

**Comment by mzguy** [comment]
Thank you for the explanation. I use regular expressions, and they work. However, I never get the checkmark at the bottom as you described. It's just not there to be activated.

**Comment by mzguy** [comment]
> I use regular expressions, and they work. However, I never get the checkmark at the bottom as you described. It's just not there to be activated.

Should I file this separately as a bug?

**Comment by Drive4ik** [comment]
This is not a bug, you need to click the button in the settings of the "set main group" group, and then this checkmark will appear

**Comment by mzguy** [comment]
It wasn't working before, but it works now. The "set as Main" buttons wasn't activating. I'm not sure why. In any event, thanks for the explanation. I like this feature.
