### ISSUE TITLE
[Bug] Open New Tab Icon displaced to extreme right.

### ISSUE THREAD

**Issue by chinook77** [Drive4ik/simple-tab-groups#612]
Last STG update (4.5.1) randomly cause Open New Tab Icon depicted to extreme right. 

Restarting FF fix it.

 - Windows 10.
 - Firefox 76.0.1
 - Simple Tab Groups version: 4.5.1

![Screenshot (172)_LI](https://user-images.githubusercontent.com/19517348/82329722-20b53480-99b8-11ea-94aa-5ec589d8155f.jpg)

**Comment by Drive4ik** [comment]
This is not an addon bug.
Move the button where you need with personalization
![изображение](https://user-images.githubusercontent.com/7843031/82331880-60e2da00-99ed-11ea-8fdf-522edd803c90.png)

**Comment by chinook77** [comment]
I've tried before posting, but it keeps resetting to that position.

**Comment by Drive4ik** [comment]
It doesn’t depend on the addon .. These are browser settings.
