### ISSUE TITLE
Serious bug:Always loosing all tabs in this condition

### ISSUE THREAD

**Issue by vsub** [Drive4ik/simple-tab-groups#613]
1.Start Firefox normally
2.Open a private window in which the addon is disabled
3.Close the non private window
4.Try to run firefox again from the desktop shortcut while the private window is still opened

This results in loosing ALL of the tabs and all of the groups become empty
Unless you have a backup,all of the tabs are gone with no way to restore them.
Even after completely closing firefox and running it again the tabs are still gone

FF 76 and addon 4.5.1

**Comment by Drive4ik** [comment]
Unfortunately, this cannot be fixed, because the addon does not work in private windows, and it cannot restore tabs. These are the limitations of FF WebExtensions. I have yet to find a way to fix this behavior. I will update the description so that people know.

**Comment by vsub** [comment]
Any progress on this?

**Comment by Drive4ik** [comment]
Should be fixed in the next release (4.7.1+)

**Comment by vsub** [comment]
Thanks,it's an improvement but here is what I notest
1.Start FF
2.Open a private window
3.Open a new non private window
4.Close the first window(ff asks you if you want to close multiple tabs)
5.When you switch to the other non private window,you can see that all of the tabs are non grouped and the addon is trying to group them(which takes a while if you have a lot of them)

Before closing the first non private window,you can access the groups and look at the tabs normally like using the first window of ff but once you close the first window,the addon restarts itself(I think)
