### ISSUE TITLE
[Bug?] New container created each time a new group is created

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#614]
Hi
Not sure whether it's a bug or intented that way, but STG seems to create a new container bearing the new group's name each time I create a new group via the popup.
Or maybe a side effect of the temporary context creation?
Anyway it kind of clutters the list of containers in the end ;)
Thanks

**Comment by Drive4ik** [comment]
Hmm ... STG only creates temporary containers. It creates other containers if necessary when restoring backup ..
