### ISSUE TITLE
Label for the tab count get truncated in the popup

### ISSUE THREAD

**Issue by nekohayo** [Drive4ik/simple-tab-groups#615]
Latest STG on Firefox 75 on Linux. This is really a minor/trivial problem, but the labels for the tab count get truncated under some circumstances:

![STG ellipsized](https://user-images.githubusercontent.com/479401/82757552-2abba680-9daf-11ea-80be-50c55b1748ff.png)

**Comment by Drive4ik** [comment]
In the new version of the addon there will be a setting for increasing the size of the popup
![изображение](https://user-images.githubusercontent.com/7843031/83418782-d064ba80-a42c-11ea-9bbf-c098dcb98568.png)

![изображение](https://user-images.githubusercontent.com/7843031/83418705-b3c88280-a42c-11ea-8d5d-442fba5fb5f8.png)
