### ISSUE TITLE
Feature Request - One Click Convert Window to New Group

### ISSUE THREAD

**Issue by GonzRon** [Drive4ik/simple-tab-groups#616]
This is a feature request to ask for a one-click button that allows you to add a new group, move all tabs in the current window to the group, and then switch to the group so the current window takes the new group name as the Window Title

Simply add a button to the main dialog of the plugin, "New Group From Window". 
Functionality is described as above.

This is useful because now I have to make many steps to perform the same function,

1. Click tab group icon, 
2. (scroll down long list of groups) click create a new group, 
3. type name for group
4. select tabs in window
5. right click and select move to group
6. click tab group icon again
7. search or select the group for the current window to switch to that group.

What about if choose to do another way, select tabs first, still many steps.

1. I select all tabs
2. right click tabs, select move to new group
3. Type name for group
4. click tab group icon
5. Search and/or select new group

With the new Proposed Feature the steps are reduced to just:

1. click tabgroup icon
2. click new button or option in dialog "New Group from Window"
3. Enter Name and hit enter (group is created, tabs in current window are moved to the new group, and the new group is automatically selected for the current window).

**Comment by Drive4ik** [comment]
How about this?
![save-tabs-to-new-group](https://user-images.githubusercontent.com/7843031/83424573-3fdea800-a435-11ea-9db6-b71c89a4aec3.gif)

**Comment by GonzRon** [comment]
That will work.  Thanks.

May I ask, what is the explanation for "hidden / unsynchronized tabs" ?

**Comment by Drive4ik** [comment]
Non-synchronized tabs, these are tabs that do not belong to any of the groups. For example, tabs in a new window without a group. They are not affected by regex rules, container capture rules, etc. These are just tabs in another window.
Tabs can also be hidden if, for example, another addon has hidden the tab. But, if another addon hid the tab that belongs to the group, then this tab will automatically be untied from this group.

**Comment by GonzRon** [comment]
"unsynchronized" tabs are fine, but I do not like the concept of hidden tabs.  It makes me feel as if there is a "memory leak", i.e. tabs open in the background that the user is not aware of, tabs that should be either closed or a part of some window group inside tab groups.  

It makes me think I am losing control of tabs and they are adding up taking memory in the background without a way to reclaim them or clean them up.

**Comment by Drive4ik** [comment]
STG addon does not do anything with non-synchronized tabs, it does not hide them and does not move them. Any other addon can do this.

> It makes me think I am losing control of tabs and they are adding up taking memory in the background without a way to reclaim them or clean them up.

This is not true, you can close them all with one click)
![изображение](https://user-images.githubusercontent.com/7843031/83758438-c0dab100-a67a-11ea-997e-e865dde9d430.png)

Maybe I will change the description of these tabs, because not all of them may be hidden

**Comment by GonzRon** [comment]
No Problem, please let me explain : my last comment about hidden / unsynchronized tabs was not a complaint necessarily about STG addon, it was more of an observation, as I was previously unaware as to the meaning of these hidden/unsynchronized tabs in Firefox.   Thank you for the explanations that is much appreciated.

**Comment by GonzRon** [comment]
Reopening the Feature Request, the provided workaround attempts to create a new group from all hidden and or unsynchronized tabs across the browser (across many open windows), my feature request is clear: I would like to create a new group only from the tabs open in the current window.  In other words, convert current window to new group.

**Comment by Lcstyle** [comment]
thank you!!!!!!!
Большое спасибо!

**Comment by pete-may** [comment]
I'm also interested in the "One Click to Convert Window to New Group" feature.

As @GonzRon pointed out, the button that was implemented converts all un-grouped tabs into a group - but I'm interested in a one-click button to convert all tabs _in the current window_ into a group.

I usually have many windows open with many tabs in each so when I want to organize them into groups the one-click button would be perfect.
