### ISSUE TITLE
External links don't get appropriate container

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#618]
**Describe the bug**
If I click on a link from Windows that opens Firefox, the tab opens in the correct group as specified by regular expression, but it does not get the container required by the group.

**To Reproduce**
1. Set up an STG group to catch a URL and force a container.
2. Open that site from Firefox. Watch it work correctly.
3. Save that same link to the desktop. Open the link. The link opens in Firefox, is moved to the correct group, but does not get the correct container. Reloading the page then gets it into the correct container.

**Desktop (please complete the following information):**
 - Windows 7
 - Firefox version: 76.0.1
 - Simple Tab Groups version: 4.5.1

**Additional context**

**Comment by Drive4ik** [comment]
fixed
