### ISSUE TITLE
[BUG? ] Some cards cannot be reloaded

### ISSUE THREAD

**Issue by nameman** [Drive4ik/simple-tab-groups#620]
Hello
sorry, but is it a bug that after a reboot of the pc and the recall of a group some links are not activated?
Even clicking on 'Reload the card' the page is not reloaded, I have to rewrite the address in order to reload it ....

**Comment by nameman** [comment]
I have sent to you the log relating to the problem ....
one more question,  is it normal that if I am in a card of a group and open another group do I also find the card of the previous group? Let me explain better, open a group and visit the site www.xxx.com, open another group and among the cards of this group I also find the card of the site www.xxx.com belonging to the previous group?
Thanks for your help

**Comment by Drive4ik** [comment]
I answered you in a letter
