### ISSUE TITLE
More frequent, than hourly backups.

### ISSUE THREAD

**Issue by jtagcat** [Drive4ik/simple-tab-groups#621]
**Is your feature request related to a problem? Please describe.**
I have to admit I restore from backups a few times per month. I currently use hourly backups, but often enough the latest available (valid) backups are from an hour ago. I can get days work done in an hour or two, what might mean significant losses.

**Describe the solution you'd like**
A smaller increment, minute(s) for example, in the automatic backups' menu:
![image](https://user-images.githubusercontent.com/38327267/83512622-043cf000-a4c0-11ea-9f97-af0f015c8bf3.png)

**Describe alternatives you've considered**
Making an external backup program backup the whole ff profile.

**Additional context**
_hugs_

**Comment by grahamperrin** [comment]
You can set a shortcut for on-demand backup, for example: 

![image](https://user-images.githubusercontent.com/192271/108648605-92745e80-74b3-11eb-8fb7-a76fff03ab4c.png)

– result: 

`auto-stg-backup-2021-02-22@drive4ik.json`

A repeat of the shortcut, on the same day, will overwrite the backup. This is reasonable; it avoid proliferation.

**Comment by jtagcat** [comment]
For more frequent backups, overwriting the backup makes it less frequent.

**Comment by Drive4ik** [comment]
Sorry, just noticed your Pullrequest. But I've already done the exact same functionality in a different task: #506 :)
I added the "Backup number as day of month" option. Now there will be a maximum of 31 backups if you want.
