### ISSUE TITLE
Tab multi-acc-container state is not recorded in backups.

### ISSUE THREAD

**Issue by jtagcat** [Drive4ik/simple-tab-groups#622]
**Describe the bug**
When restoring backups, all tabs are in the default container.

**To Reproduce**
1. Open tabs in non-default containers.
1. Backup
1. Restore backup
1. All tabs are in the default container.

**Expected behavior**
1. All tabs are in the containers they were in.

**Desktop (please complete the following information):**
 - OS and version: Fedora 32
 - Firefox version: 76.0b9 (64-bit)
 - Simple Tab Groups version: 4.5.1

**Comment by Drive4ik** [comment]
I cannot repeat this bug, check on the latest stable version of FF

**Comment by jtagcat** [comment]
Haven't noticed it happening and can't reproduce either.
