### ISSUE TITLE
Notes field

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#623]
**Is your feature request related to a problem? Please describe.**
Groups of tabs often correspond to research or ongoing projects. There's no way to connect the group to non-browser apps.

**Describe the solution you'd like**
A way to add notes to the group. I think ideally the extension should be able to create a tab in a group with a notes box "group notes tab" that is preserved between sessions. The note tab preferably should support markdown for formatting. One could use this box to store ideas, links to other apps or resources, such as Evernote links, etc. Also, it can be used to store keywords for search. For example I could put a project goal in there. STG search would then allow me to easily search for that text in the notes after seeing the goal in a project management app to find the corresponding group. There are many other potential uses.

**Describe alternatives you've considered**
The alternative when linking browser tabs to another external app is to place links in the external app, which forces me to reconstruct the STG group each time after opening all the links.

**Additional context**
This feature would increase the value of STG as part of a wider set of tools.

**Comment by Drive4ik** [comment]
Your request does not match the main purpose of the addon. The essence of addons is that you can install them whenever you need them. Therefore, other addons are suitable for this purpose, for example:
https://addons.mozilla.org/firefox/addon/notes-by-firefox/

**Comment by mzguy** [comment]
I see your point, but I thought the purpose of the add-on is to enable the effective use of groups, which is why you incorporate containers, automatic moving, etc. Having notes specific to a group is the same idea.

A workaround through another extensionay be fine, but it looks like your suggested one is shutting down. Do you know another that will allow me to add group-specific notes?

**Comment by Drive4ik** [comment]
Here's a good addon for example. The binding goes by URL.
https://addons.mozilla.org/firefox/addon/ourstickys/

For these purposes, you can make a plugin for STG. The plugin will receive notifications from STG that the group has changed, and when you click on the button in the topbar, show different text.
When I have some free time, I will make a simple version of this plugin, but it will be very simple, no bells and whistles.

**Comment by Drive4ik** [comment]
@mzguy Here I did:
https://addons.mozilla.org/firefox/addon/stg-plugin-group-notes/

**Comment by mzguy** [comment]
> 
> 
> @mzguy Here I did:
> https://addons.mozilla.org/firefox/addon/stg-plugin-group-notes/

Thanks! This works well with STG. Will these notes get backed up with the usual STG backup mechanism?

Also, is there a way to get them included in the Bookmark-based multi-device sync approach somehow?

**Comment by mzguy** [comment]
Another suggestion for an improvement: change the extension icon a little if the group contains notes. Perhaps just give it a yellow glow?

**Comment by Drive4ik** [comment]
> Will these notes get backed up with the usual STG backup mechanism?

No. These are two different plugins. Group notes will only have manual backups for now.

> Also, is there a way to get them included in the Bookmark-based multi-device sync approach somehow?

No. This is the first path to data loss and bugs.

> Also, can we get the note contents included in the STG extension's search?

No. These are two different plugins.

> Another suggestion for an improvement: change the extension icon a little if the group contains notes. Perhaps just give it a yellow glow?

Done :) 
![изображение](https://user-images.githubusercontent.com/7843031/98450669-2b6eac00-2147-11eb-94d1-513c894e4231.png)

f5d303b1a6fb3bc31862575d16a394d1ad4679cd

**Comment by mzguy** [comment]
Glad to have the indicator, thanks. I think a search within all group notes would be useful then. It's a way to allow for references from other programs: add a keyword, find quickly where it is in the group structure.

**Comment by mzguy** [comment]
Another small change would be useful: make the side-by-side view option sticky, so that it doesn't switch itself off.
