### ISSUE TITLE
"Export all groups to bookmarks" doesn't work properly

### ISSUE THREAD

**Issue by cluxter** [Drive4ik/simple-tab-groups#624]
**Bug description**
When STG bookmarks already exist, using the "Export all groups to bookmarks" will actually restore the previous existing bookmarks instead of erasing them with the new tabs.

**How to reproduce this bug**
1. In `STG boookmarks/OneFolder`, note how many bookmarks you have. Let's say 10.
1. With STG, open this group (called `OneFolder`). You know have 10 tabs opened in your `OneFolder` group.
1. Now open a new tab and go on a website. You know have 11 tabs opened, but still 10 bookmarks. So far, so good.
1. On the main STG favicon, click on it, then right-click on it and select `Export group to bookmarks`. Now check in `STG bookmarks/OneFolder` and count the bookmarks: you should have 11 bookmarks, which is fine.
1. Now, on the main STG favivon, right-click on it and select `Export all groups to bookmarks`. Check in `STG bookmarks/OneFolder` and count the bookmarks: you now have 10 bookmarks instead of 11. The last opened tab is gone.

**Expected behavior**
The `Export all groups to bookmarks` feature should export all the new opened tabs.

**Desktop:**
 - ArchLinux
 - Firefox version: 77.0
 - Simple Tab Groups version: 4.5.1

**Comment by Drive4ik** [comment]
STG exclude `about:...` tabs. Have you opened such a tab?

**Comment by cluxter** [comment]
I didn't. I tested it with Google News and a couple of mainstream websites.

**Comment by Drive4ik** [comment]
Do you have disabled this option?
![изображение](https://user-images.githubusercontent.com/7843031/83555434-f4042f80-a516-11ea-9673-425c33f100f9.png)


I can't replicate this behavior.. The export of a group is, say, function 1, the export of all groups, this is the same function 1 that is called in the loop.

**Comment by cluxter** [comment]
Yes I have disabled it (and it was actually not enabled).

**Comment by Drive4ik** [comment]
> STG exclude `about:...` tabs.

this is not true, I was mistaken. But still I can’t reproduce your problem

**Comment by Drive4ik** [comment]
Can you record a gif, with test group?

like this app:
https://www.screentogif.com/

**Comment by Drive4ik** [comment]
https://www.cockos.com/licecap/
or this app (simple)

**Comment by cluxter** [comment]
Okay I got it working. But there definitely is a bug somewhere.

I only had this bug with one group, let's called it `BuggedGroup`.

Here is what I did:
1. I installed Firefox
1. I logged in Firefox Sync, and all my Firefox bookmarks got synced, including the old `STG bookmarks` that I already had. STG was also installed in the process
1. For some reason, the permission that allows STG to access the bookmarks was not enabled in the STG settings. I enabled this option
1. I restored `BuggedGroup` with right-click on it, "Open bookmark in new group"
1. Then, I restore all the groups with right-click on `STG bookmarks`, "Open bookmark in new group"

This is how I ended up with a bug on one specific group. I don't know what happened exactly, but it feels like STG was still refering to the first restored `BuggedGroup` when I used `Export group to bookmarks`, but was referring to the second restored `BuggedGroup` when I used `Export all groups to bookmarks`. Maybe the opposite, or something else. But something went wrong somewhere in the process.

**Comment by Drive4ik** [comment]
There are too many conditions. First, you did the restoration and most likely export back when FF was doing bookmark synchronization. You can’t do this, you need to wait until one process ends, because when you exported bookmarks from the add-on, FF could delete the created STG bookmark as part of synchronization.

> For some reason, the permission that allows STG to access the bookmarks was not enabled in the STG settings. I enabled this option

STG does not sync its settings.
