### ISSUE TITLE
Пропали все вкладки из всех групп!

### ISSUE THREAD

**Issue by annahonda** [Drive4ik/simple-tab-groups#625]
Здравствуйте!
Установила аддон Simple Tag Groups. Очень полезная и удобная программа для управления вкладками. Но что-то произошло, и все вкладки из всех папок разом удалились!!! Как их вернуть? Помогите, пожалуйста!

**Comment by Drive4ik** [comment]
Здравствуйте!
Попробуйте восстановить их из резервной копии. Она находится в папке загрузок Firefox папка STG backups. Зайдите в настройки аддона, последняя вкладка, восстановить, и выберите последний файл бекапа.

**Comment by annahonda** [comment]
В бэкапе пусто. Файл есть, группы там присутствуют, но вкладок там нет. Восстановление ничего не дало. 
![01](https://user-images.githubusercontent.com/66372464/83647877-156c2680-a5be-11ea-9ddb-f3cc2ccfb599.jpg)

**Comment by Drive4ik** [comment]
А предыдущий файл бекапа?

**Comment by annahonda** [comment]
Аддон установили только сегодня. Это единственный файл бэкапа.
Как так вообще произошло, что удалились все вкладки, а все группы остались?!

![02](https://user-images.githubusercontent.com/66372464/83649091-7cd6a600-a5bf-11ea-8992-ea5ecd80753f.jpg)

**Comment by Drive4ik** [comment]
Что вы делали до того как пропали вкладки?

Включено ли у вас восстановление сессии?
![изображение](https://user-images.githubusercontent.com/7843031/83649961-798fea00-a5c0-11ea-9fc9-0d15c5f24b61.png)

Пытали ли восстановить вкладки и окна обычным способом?
![изображение](https://user-images.githubusercontent.com/7843031/83650232-c8d61a80-a5c0-11ea-8e1b-9faf091b1a85.png)

**Comment by annahonda** [comment]
Восстановление сессии включено. Точную последовательность действий, к сожалению, я не произведу. Просто нажала на какой-то "крестик" и всё исчезло. :)

Перезапускать Firefox пробовали после того, как вкладки уже исчезли, но он не предложил восстановить предыдущую сессию.
Может, как-то можно восстановить его вчерашнюю сессию?

![03](https://user-images.githubusercontent.com/66372464/83651411-1ef78d80-a5c2-11ea-8e2e-412c4f91e631.jpg)
![04](https://user-images.githubusercontent.com/66372464/83651416-1f902400-a5c2-11ea-86d8-a9ad457b6c4b.jpg)

**Comment by Drive4ik** [comment]
Я только заметил, не используйте аддон OneTab вместе с STG. Их нельзя использовать вместе потому что они по своей логике работы конфликтуют друг с другом - и тот управляет вкладками и тот. Это также распространяется и на другие аддоны связанные с вкладками.
STG аддон не закрывает вкладки при переключении группы, а OneTab - закрывает. Аддон STG не знает кто или что закрывает вкладку, поэтому закрытые вкладки пропадают из групп. Аддон не хранит у себя в памяти вкладки, за исключением архивных групп.
Если вы использовали аддон OneTab, попробуйте отключить STG, восстановить все вкладки через аддон OneTab (чтобы все они были видимые на панели вкладок), затем отключите OneTab и включите STG.

**Comment by annahonda** [comment]
Вы абсолютно правы! Вспомнила, что я как раз собиралась перенести все вкладки из групп One Tab в STG, нажала на значок One Tab и после этого все вкладки из ранее добавленных в группы STG исчезли! Сейчас повторила эти действия и, да, действительно произошло всё то же самое! Огромное Вам спасибо, что помогли разобраться, в чём проблема! Даже не предполагала, что эти программы могут так конфликтовать... ((( Сейчас попробую восстановить потерянные вкладки.

**Comment by annahonda** [comment]
Виталий, ещё раз спасибо! Вкладки никуда не пропали! Сейчас отключила STG, после чего зашла в One Tab и увидела, что все вкладки, которые я ранее распределила по группам в STG, оказались в одной группе в One Tab! Без Вашей помощи я бы ни за что не догадалась в чём была проблема!

**Comment by Drive4ik** [comment]
Все верно) OneTab не различат скрытые и видимые вкладки, поэтому они все оказались в одной группе OneTab.
Теперь, если вы все еще хотите использовать STG, вам нужно отключить OneTab когда все вкладки видны, и заново распределить вкладки по группам STG. Для удобства можно удерживать нажатой кнопку Shift или Ctrl и выбирать сразу несколько вкладок.
Рад был помочь)

**Comment by annahonda** [comment]
Спасибо за помощь и за удобное приложение!
