### ISSUE TITLE
Open bookmarks subfolder with multiple bookmarks as a new group?

### ISSUE THREAD

**Issue by mainmachine** [Drive4ik/simple-tab-groups#626]
I am very happy with the way that STG saves tabs to bookmarks, and this opens the door for syncing bookmarks across systems. I believe FF sync does this, but I am not certain it organizes them consistently.

Can you add a feature to open an entire folder of tabs as a new group, or even import a bookmarks folder structure as one or more tab groups?

You would be able to leverage bookmark syncing from any number of pre-existing add-ons with this seemingly simple feature.

The end result that I would like to see would be that I can have the same tab groups synced on any device on which I have STG installed and bookmarks synchronized...

Thank you for your hard work!

**Comment by Drive4ik** [comment]
Your request is already there:
![изображение](https://user-images.githubusercontent.com/7843031/95586563-88dce380-0a49-11eb-9b9f-0b1f80c825e6.png)
