### ISSUE TITLE
Открытие отдельной вкладки из группы

### ISSUE THREAD

**Issue by annahonda** [Drive4ik/simple-tab-groups#627]
Добрый день! 
Недавно начала использовать аддон STG, ранее пользовалась One Tab. Расширение STG удобнее, но есть одна функция, которая в One Tab реализована, а у вас нет. Будет очень полезно, если вы тоже её добавите. А именно - возможность открывать только одну вкладку из группы в текущем окне (не заменяя уже открытые вкладки). Например, выбрав соответствующий пункт при клике правой кнопкой мыши на нужной вкладке. Сейчас можно открыть только сразу все вкладки группы (заменяя открытые), а, наведя курсор на отдельную вкладку из списка в группе, и кликнув по ней правой кнопкой мыши, из возможностей  реализовано только перемещение этой вкладки в другую группу.

![STG](https://user-images.githubusercontent.com/66372464/83794868-4aa07380-a6a7-11ea-8953-e0fa57b08374.jpg)

**Comment by Drive4ik** [comment]
Всё верно. Открытие отдельной вкладки из другой группы - это и есть перемещение вкладки из одной группы в другую.
Откройте контекстное меню перемещения вкладки, выберите группу и вместо щелчка левой кнопки мыши на группе - нажмите правой кнопкой, и тогда только эта вкладка переместится в выбранную группу, и станет активной. По сути это и есть открытие отдельной вкладки из группы.
