### ISSUE TITLE
Syncing Groups Across Devices

### ISSUE THREAD

**Issue by s3hMC** [Drive4ik/simple-tab-groups#628]
The title is pretty self-explanatory. I don't know if this is possible, but it would be really nice if tab groups could be synchronized across my Firefox devices.

**Comment by ejm554** [comment]
**I want to know this too!** I use the Extension on my WIndows 10 device, and I created four groups. After installing the extension on my Mac, these groups don't appear. However, in the STB menu, this phrase appears: "Found hidden unsynchronized tabs."

I'm not sure what this phrase means, exactly. Note that I have Firefox Syncing turned on on both devices.

**Comment by ejm554** [comment]
Is this issue a Duplicate of #636 ?

**Comment by bonnepioche** [comment]
Hi, I would LOVE to have syncing the tabs accross devices as well. And yes, this feature request is a duplicate of #636 (the way I understand it).

**Comment by goacid** [comment]
+1

**Comment by Drive4ik** [comment]
Duplicate of #291
