### ISSUE TITLE
Transparent/faded-out text to differentiate the tab group names from the summary of tabs they contain?

### ISSUE THREAD

**Issue by nekohayo** [Drive4ik/simple-tab-groups#629]
Currently we have this, where the tab group names are a bit hard to distinguish visually from the summary of their open tabs:

![Screenshot from 2020-06-07 15-22-45](https://user-images.githubusercontent.com/479401/83978127-52dcf680-a8d3-11ea-8a01-5bf677bd5d88.png)

Would it be possible to have something like this, where the text other than the tab group name has 50% opacity (and that way, instead of hardcoding gray, it works with both light and dark themes)? :

![Screenshot from 2020-06-07 15-22-45 half transparent](https://user-images.githubusercontent.com/479401/83978142-73a54c00-a8d3-11ea-8600-51e23b9267dd.png)

**Comment by Drive4ik** [comment]
Done, please wait next release
