### ISSUE TITLE
Support for a mouse gesture to display the panorama-like page

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#63]
With the former Panorama feature, it was possible to define a mouse gesture  to display the visual Panorama page (by mapping a certain JS function in one of the gestures addons). I had mapped that to the Right-click+DOWN gesture and it was quite handy.

Is there already or could there the same ability with this addon? 
Note that I'm now using Gesturify as the gestures addon in FF57+.

Thanks

**Comment by Drive4ik** [comment]
Hi @klint 
Now I will not support mouse gestures, but I can make gesture support from this extension.
For example:
you create a gesture for the go to the next group and Gesturify send my addon a message about it, and my addon in turn performs this action.
If you are interested in it - you can contact the developer Gesturify and invite him to implement the support of this with help:

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendMessage
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/onMessageExternal

**Comment by klint** [comment]
Sure, I'll do that. Thanks
Yes, I won"t not asking your addon to perform the gesture, but the other one to perform it and execute an action in your addon in response. Like you explained :)

**Comment by klint** [comment]
One more word on this request: it could be implemented in a more open way by linking gestures in the other add on and shortcuts in your addon:
- add an id to each shortcut in Simple Tab Group
- on the other side, the gesture addon would just ask for the user for a free ID to be associated to the gesture
- then Simple Tab Group would be listening to IDs sent by the gesture addon and execute the corresponding shortcut
This way, any keyboard shortcut could have its equivalent as a gesture.

**Comment by klint** [comment]
And by the way, see the previous response of the gesture addon's developer here: https://github.com/Robbendebiene/Gesturefy/issues/238#issuecomment-361545919

**Comment by Drive4ik** [comment]
@klint 
about https://github.com/Drive4ik/simple-tab-groups/issues/63#issuecomment-363346717
I just planned it and I already realized it :)

**Comment by klint** [comment]
Thanks, looking forward to using it :)

**Comment by Robbendebiene** [comment]
@Drive4ik Hey, it's been a while but I finally moved to a fixed Add-on ID:
`{506e023c-7f2b-40a3-8066-bc5deb40aebe}`

Is there a list of message strings that your add-on accepts, I'm curious to try it out after you've white-listed Gesturefy :)

**Comment by Drive4ik** [comment]
Hi @Robbendebiene ! I added your Gesturefy to white list with all supported STG actions. Try it on STG v3.1

Example:
when STG ready it send external message to Gesturefy
```javascript
browser.runtime.sendMessage('{506e023c-7f2b-40a3-8066-bc5deb40aebe}', {
    action: 'i-am-back'
});
```

and other actions: `group-added, group-updated, group-removed`:
```javascript
browser.runtime.sendMessage('{506e023c-7f2b-40a3-8066-bc5deb40aebe}', {
    action: 'group-updated',
    group: {
        id: 1,
        title: 'group 1',
        iconUrl: 'http://...',
    }
});
```

on action `group-removed` send: 
```
{
    action: 'group-removed',
    groupId: 2
}

```

```javascript
browser.runtime.sendMessage('simple-tab-groups@drive4ik', {
    action: 'load-next-group'
});
```

you can see all actions on
https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/background.js#L1623-L1721

**Comment by Drive4ik** [comment]
@Robbendebiene Allowed actions for Gesturefy:
https://github.com/Drive4ik/simple-tab-groups/blob/master/addon/src/js/constants.js#L43-L63

**Comment by klint** [comment]
@Robbendebiene  @Drive4ik 
Thank you for implementing this!!
So, I have tried to set up a gesture in Gesturify with the following settings, but I don't get any result so far. Is anything wrong with it? 
Thanks :) 

![image](https://user-images.githubusercontent.com/218971/44223543-30bb3700-a188-11e8-8081-24bdd52d0a5f.png)

**Comment by Drive4ik** [comment]
@klint Hi!
You have to do it like this, and then everything will work.
![screenshot_1](https://user-images.githubusercontent.com/7843031/44263498-dffb1b00-a227-11e8-95c7-1b9474199ef0.png)

But for full support it seems to me it is necessary to make a separate functional.
With this functionality it will be difficult to work with such actions: `get-groups-list` & `load-custom-group`

**Comment by klint** [comment]
@Drive4ik 
Thanks a lot for the hint, it works perfectly now :)

By the way, maybe I already asked you in another request, not sure though, so here it is.
Would it be possible for you to add a new action that would open the below menu? It displays quicker than the panorama view and it is my favorite way to navigate through groups with the mouse.
And even better if it could open the menu next to the mouse cursor instead of next to the toolbar button :)

![image](https://user-images.githubusercontent.com/218971/44275477-1d21d600-a245-11e8-960e-6ce684d824c1.png)

Anyway, thanks a lot to both of you for implementing all this.

**Comment by Drive4ik** [comment]
Hi! You are welcome))

Open popup by action is not supported due to security reason:

> Open the browser action's popup.
You can only call this function from inside the handler for a user action, such as:
> - Selecting a context menu item defined by the extension.
> - Activating a keyboard shortcut defined by the extension. (Note: this is not currently supported in Firefox.  Instead consider binding the keyboard shortcut to the _execute_browser_action special action.)
> - Clicking a button in a page bundled with the extension.


https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction/openPopup
