### ISSUE TITLE
Regular expressions don't move tabs when they are navigated from links

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#630]
**Describe the bug**
Regular expressions work to move tabs to the correct group when I type a matching URL in the URL bar. However, if I click on a link from a tab, they do not. 

**To Reproduce**
1. Create a regular expression to catch tabs to a group.
2. Click on a link from a different group that matches the regular expression.
3. The group is not changed for the new tab.

**Expected behavior**
The tab is moved to the correct group as specified by the regular expression, regardless how the tab is created.

**Desktop (please complete the following information):**
 - OS and version: Windows
 - Firefox version: 77.01
 - Simple Tab Groups version: 4.5.1

**Additional context**
Some people may prefer the behavior as-is (where links always create a tab in the current group), so perhaps this can be a configurable option on a per-group basis.

**Comment by Drive4ik** [comment]
Most likely the "Sticky group" option is enabled in the group in which you create the tab?

**Comment by mzguy** [comment]
That's not the case.

**Comment by Drive4ik** [comment]
Write a regular expression and the link it doesn't work on

**Comment by mzguy** [comment]
Regex in my Amazon group:
amazon\.com

Link on a page in a different (non-sticky) group, open in a temporary container:
https://amazon.com/gp/coupon/on-earphone-tips-from-comply-for-a-more/A291B4I7VKRQTT?tag=wcpd2020-20&linkCode=xm2&ascsubtag=primeday20dealspagezz28759&smid=ATVPDKIKX0DER

I just discovered that the problem doesn't arise because the URL is in a link, but rather if it's already in a container. Since the link is in a page that has a container, it doesn't change groups (and container) according to the regex.

So, if I open a new tab without a container and paste the above into the URL bar, it gets moved to the Amazon group and gets a container as specified in that group. If I first open a tab in a temporary container, then paste the URL into the URL bar, it doesn't get moved.

**Comment by Drive4ik** [comment]
Yes that's right. This is done due to the fact that the logic of private tabs will be broken.
If you open a tab in a private container, the addon cannot automatically move it to a group in another container, because the tab will lose its anonymity.

> I have a backslash before the '.', but when posting here it gets stripped

Write like this `amazon\\.com`
(two slashes)
