### ISSUE TITLE
number of groups (rows) in dropdown list

### ISSUE THREAD

**Issue by skyxx** [Drive4ik/simple-tab-groups#631]
Hi, first thank you for you great work and share with us this addon.

Clicking on addon icon on FF bar will show list of groups but there is only visible 18 rows, if there
is more groups than 16 you have to use scroll which woks fine but is a little bit less clear.

Its possible to have option set up larger menu with more items to dont use scroll ? When user have monitor with 1440p+ resolution there can be more items.

Regards
S.

**Comment by Drive4ik** [comment]
Unfortunately not. 
https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups#Popup_resizing

But the new version will have an option to increase the popup to a maximum
