### ISSUE TITLE
Opening bookmarks reverses tab order

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#633]
**Describe the bug**
STG saves groups to bookmarks in the same order as the tabs appear in the group. However, importing / opening them to a group reverses that order.

**To Reproduce**
1. Save a group to a bookmarks folder.
2. Right-click the folder in bookmarks and either move the tabs to an existing group or open in a new group.
3. Note that the tabs open in reverse order.

**Expected behavior**
Re-creating a group through the bookmarks functionality should not reverse the tab order.

**Desktop (please complete the following information):**
 - OS and version: Windows
 - Firefox version: 77.0
 - Simple Tab Groups version: 4.5.1

**Comment by Drive4ik** [comment]
Please enable this option in addon settings
"Reverse tabs on create, if you have the `browser.tabs.insertAfterCurrent` preference is `true`"
