### ISSUE TITLE
Moved tabs are replaced by a blank tab

### ISSUE THREAD

**Issue by kssi** [Drive4ik/simple-tab-groups#635]
**Describe the bug**
On version 4.5.1, when right-clicking a tab in a window/group to move it into another group, the tab gets replaced with a new blank tab (which I must close manually). This didn't happen before and I assume this is a bug since it is both awkward and useless.

**Comment by Drive4ik** [comment]
If you move the last tab in the group, and you do not have pinned tabs, then yes, there must be at least one tab in the window. No windows without tabs. This is not a bug.

**Comment by kssi** [comment]
Can you please reopen this issue? I never mentioned I was moving the last tab. This happens everytime, and the blank tab is added to the remaining tabs in the group.

**Comment by Drive4ik** [comment]
Ok. Please record screen with this issue.

**Comment by kssi** [comment]
I'm not able to record the screen, nor do I want to share all my tabs/groups with people over the Internet. Though I know I could cleanup my session and further restore it from a STG backup, I'd prefer to avoid fiddling stuff as much as possible. A screen recording won't be much more informative than what I described above. This just happened again, when moving a set of 3 selected tabs straight from the Firefox tabs toolbar (_right click > Move tab to group_). They got replaced by a single blank tab. I can't reproduce it on demand because it _seems_ to happen randomly.

**Comment by kssi** [comment]
I just recorded a debug log file:

[STG-debug-logs.json.zip](https://github.com/Drive4ik/simple-tab-groups/files/5360062/STG-debug-logs.json.zip)

Please let me know if it's any helpful.

**Comment by Drive4ik** [comment]
Yes, my mistake. Fixed.

**Comment by kssi** [comment]
Thank you!
