### ISSUE TITLE
Follow tabs on create if moved to other group

### ISSUE THREAD

**Issue by stevefan1999-personal** [Drive4ik/simple-tab-groups#637]
**Is your feature request related to a problem? Please describe.**
It's pretty frustrating that I have to click that little notification to follow my tab that has been sent to other group with regex matching. This is repetitive if you have to switch from Google to GitHub which I had separated to different groups too.

**Describe the solution you'd like**
Just follow it?

**Comment by Drive4ik** [comment]
![изображение](https://user-images.githubusercontent.com/7843031/95485786-dfd7af80-099a-11eb-800e-e2f636744dea.png)
