### ISSUE TITLE
Sort group name

### ISSUE THREAD

**Issue by stevefan1999-personal** [Drive4ik/simple-tab-groups#638]
**Is your feature request related to a problem? Please describe.**
Ditto to title. Besides from manually dragging along the group to fit the name order, why don't we just let the computer do it.

**Describe the solution you'd like**
Implement a simple button to execute a natural lexicographical sort. For an example set {9, 5, 11, 1, 8}, by natural sort it means {1, 11, 5, 8, 9}. For a word set {aba, aab, abba}, by lexicographical sort it means {aab, aba, abba}.

**Additional context**
Would be even better if the tabs in the group could also be sorted automatically.

**Comment by Drive4ik** [comment]
![изображение](https://user-images.githubusercontent.com/7843031/95485304-355f8c80-099a-11eb-8c26-0deac460314d.png)

>  Would be even better if the tabs in the group could also be sorted automatically.

Use one of these extensions:
https://addons.mozilla.org/firefox/search/?q=sort tabs
