### ISSUE TITLE
2.3.1 - broken

### ISSUE THREAD

**Issue by White-Owl** [Drive4ik/simple-tab-groups#64]
Just updated to 2.3.1...
No plugin's icon on toolbar
No settings in plugin's screen in addon manager
Hot keys do not work.

Panic mode on!

**Comment by Drive4ik** [comment]
Can you do this:
![screenshot_3](https://user-images.githubusercontent.com/7843031/35402931-b2081458-0206-11e8-97f7-8956eb06c375.png)
![screenshot_4](https://user-images.githubusercontent.com/7843031/35402936-b45cf908-0206-11e8-8bdf-00210296f4ff.png)


and screenshot console

**Comment by White-Owl** [comment]
Once I click on Debug (step 3), I got a connection request:
![image](https://user-images.githubusercontent.com/5298837/35403444-baae6d2a-01cd-11e8-886d-c3730b62be90.png)
and on Ok, a completely blank window
![image](https://user-images.githubusercontent.com/5298837/35403489-dfbef648-01cd-11e8-9bd6-e245d9607642.png)

**Comment by White-Owl** [comment]
On Cancel, I have something:
![image](https://user-images.githubusercontent.com/5298837/35403535-fd177e18-01cd-11e8-9e41-d1b195251454.png)

**Comment by White-Owl** [comment]
On the about:debugging#addons page, if I click on "Manifest URL" link  - I am getting an empty page.
Other addons show a proper JSON files.

**Comment by White-Owl** [comment]
Ok.... Restart FF did bring the addon back to live.
Completed all the debugging steps and got this:
![image](https://user-images.githubusercontent.com/5298837/35404447-02f8c5d2-01d1-11e8-9924-4ecffc877996.png)

**Comment by Drive4ik** [comment]
Queerly, maybe firefox crookedly update addon?
Are you not afraid to reinstall the addon?

**Comment by Drive4ik** [comment]
or try uninstall and then unde uninstall

**Comment by White-Owl** [comment]
BTW, restarted FF again - addon did not pick up auto-restored windows. (issue #60)

Ok, doing addon reinstall now...

**Comment by Drive4ik** [comment]
restart firefox does not produce results?

**Comment by Drive4ik** [comment]
wait

**Comment by Drive4ik** [comment]
if you have not already removed the addon, do so:
go to
![screenshot_5](https://user-images.githubusercontent.com/7843031/35404828-e754af9e-020c-11e8-83f2-0a7dc142ea7c.png)
and backup this file

**Comment by White-Owl** [comment]
Sorry, I saw your "wait" message after the reinstall

It looks like addon is working now. I'll make backup next time. Sorry again

**Comment by Drive4ik** [comment]
Do not need to apologizes.
I need to know about all the bugs and conflicts to make this add-on even better (if I can do it).
But I can fix problems if I know step-by-step to reproduce issue.

Thank you for helping me to make this addon better!
