### ISSUE TITLE
bookmark all tabs and close group

### ISSUE THREAD

**Issue by Teslafly** [Drive4ik/simple-tab-groups#640]
**Is your feature request related to a problem? Please describe.**
a common part of my workflow, along with having a lot of groups. is that when i am done with a group for the moment I will bookmark all tabs in it to a custom folder using "bookmark all tabs", then close the group. This is NOT the "export group to bookmarks" function. I need to be able to manually input the name of the group (default should be the current group name though), and select the folder that the group folder goes into. Then the group should be closed and manage page and view moved to ungrouped tabs page. this needs to work in the manage groups pane the most. 

**Describe the solution you'd like**
action steps:
1. In manage groups pane. right click and select "bookmark and close all"
2. A popup similar to the builtin ff "bookmark all tabs" comes up with the current group name as default name that can be edited. you can also search and select the folder you want to nest this bookmark folder in.
3. On clicking ok, all tabs are bookmarked and the group is closed. Since manage groups resides in a tab,(and you cannot clobber the ff ui like old tabgroups) if you are in the group being deleted, that tab needs to be moved to ungrouped tabs along with the current view. The manage tabs view stays open/focused. If the manage tabs tab is not in the deleted group then it should stay there.
(currently, deleting the group that you are opening the manage window from closes the manage window and dumps you into unorganized tabs, the manage tab should be moved and remain in focus during normal use too.)
4. select another tab group/bookmark another group/etc to go back to your workflow.

**Describe alternatives you've considered**
 "Export group to bookmarks" is currently not helpful to my workflow. it does not let you select the name or location of the bookmarks. It also does not close the group, which if you are managing/closing from within that group it takes a few clicks to get back to the manage window.

**Comment by nekohayo** [comment]
You can already select multiple tabse natively in Firefox (ex: shift-clicking to select a range), right-click them and bookmark them all to the folder of your choice; and then you could delete the group from STG in a single operation as well. As a user, I'm not convinced this two-step operation is so frequent that it needs to be implemented as a one-step operation in STG.

**Comment by Drive4ik** [comment]
@nekohayo Totally agree with you

@Teslafly You want functionality that cannot be implemented and is too specific.
