### ISSUE TITLE
Recent files are spammed

### ISSUE THREAD

**Issue by 532910** [Drive4ik/simple-tab-groups#641]
Just another side effect of the backup implementation:
![image](https://user-images.githubusercontent.com/14617699/85826299-01ff4600-b78d-11ea-9f12-1ba8f13aad9f.png)

**Comment by nekohayo** [comment]
Probably the only way to avoid this would be for STG to store its backups in a folder inside Firefox's profile directory (which is a hidden directory) rather than in plain sight?

**Comment by Drive4ik** [comment]
@532910 You have to back up every hour, that's to be expected.
For the sake of safe storage of the backup, this is inevitable.
Set the backup time once a day, and the addon will overwrite this backup file every 2 hours.
