### ISSUE TITLE
Closing a pinned tab with Ctrl-W switches to another tab group

### ISSUE THREAD

**Issue by 532910** [Drive4ik/simple-tab-groups#642]
Closing a pinned tab with Ctrl-W switches to another tab group

Steps to reproduce:
1. Open several tabs in several groups
2. Pin one tab
3. Try to close it with Ctrl-W

stg 4.5.1, ff 77, debian sid

**Comment by gkaklas** [comment]
I believe this is a duplicate of #462 :thinking:

**Comment by 532910** [comment]
Looks so
