### ISSUE TITLE
"Add new group" Hotkey not working

### ISSUE THREAD

**Issue by mccarthyp-snet** [Drive4ik/simple-tab-groups#644]
**Describe the bug**
The `Add new group` Hotkey is not working.

**To Reproduce**
1. Go to `Hotkeys` tab in the Extension Settings.
2. Add a Hotkey for `Add new group` with `Alt + N` as the keybinding.
3. Attempt to add a new group using `Alt + N`.
4. No new group is created.

**Expected behavior**
I'd expect the hotkey for `Add a new group` to add a new group.

**Desktop (please complete the following information):**
 - OS and version: Windows
   - Edition: Windows 10 Enterprise
   - Version: 1909
   - Build: 18363.900
 - Firefox version: 78.0.1 (64-bit)
 - Simple Tab Groups version: 4.5.1

**Comment by Drive4ik** [comment]
Everything works, read the description.
Also recommend this:
![изображение](https://user-images.githubusercontent.com/7843031/95484304-f8df6100-0998-11eb-99a7-ba3c09dde795.png)
