### ISSUE TITLE
Simple Tab Groups auto backups causes my PC to crash

### ISSUE THREAD

**Issue by kaporli** [Drive4ik/simple-tab-groups#645]
**Describe the bug**
Whenever my STG backs up my FF starts to not respond and my entire computer freezes up.

**To Reproduce**

I don't do anything specific, it's just that whenever it backs up my PC just dies.

**Desktop (please complete the following information):**
 - OS and version: Windows 64 PRO
 - Firefox version: [78.0.1.7486]
 - Simple Tab Groups version: [4.5.1]

**Additional context**
Not context per se but is there a way to disable these backups?

**Comment by Drive4ik** [comment]
You will find everything in the addon settings
