### ISSUE TITLE
[Feature Request] Bookmark Toolbars per Group

### ISSUE THREAD

**Issue by DavidLGCrawford** [Drive4ik/simple-tab-groups#646]
It would be great if each tab group had the option of a customized bookmark toolbar.

When you create a new group it starts with either the default bookmark toolbar (preferred), or an empty one.

Then I can add/delete bookmarks, but those changes appear only when I'm on that tab group. Change tab group and a whole different selection of bookmarks would appear.

Example:
Tab Group "Cars". Bookmark Toolbar shows: [Ebay Autos]  [Car Site B]  [Car Site C]
Switch to tab group "Sailing". Bookmark Toolbar shows: [Yachtworld]  [RYA.uk.org]  [Sailing Site C]

Maybe make it as simple as the extensions searches for a folder in the bookmarks with the same name as the tab group, and uses that folder as the bookmark toolbar. If there's no matching folder then it displays the "Bookmark Toolbar" folder.

**Comment by Drive4ik** [comment]
This cannot be realized, if only due to the fact that bookmarks are synchronized to the FF cloud. The addon should not remember bookmarks, it was not created for this.
