### ISSUE TITLE
Option to reset "Last backup" date

### ISSUE THREAD

**Issue by mindgs** [Drive4ik/simple-tab-groups#647]
**Is your feature request related to a problem? Please describe.**
Yes. If the computer date and time is changed for whatever reason (manually or due to a bug) and an auto-backup is made before the computer date is corrected, then that incorrect date gets set as "Last backup". If the computer date is then corrected, no further auto-backups will be made, until the "Last backup" date is actually reached. 

**Describe the solution you'd like**
Either provide a button to reset the "Last backup" date in the extension settings.

**Describe alternatives you've considered**
The "Last backup" date could be reset when a _manual_ backup is made, even if the "Date modified"/"Date created" attributes on that new file refer to an earlier date compared to the last backup.

**Additional context**
[Screenshot](https://files.catbox.moe/4s591q.png)

**Comment by Drive4ik** [comment]
This cannot happen so often for which you need to make a separate button... Sory

**Comment by mindgs** [comment]
That's fair, but it actually happens more often than you'd think if you dual-boot Linux+Windows... Due to the way each OS handles local time, so the clock is often set forward when you boot back into Windows.
