### ISSUE TITLE
Temporary Container conflict with "Always Open in ..."

### ISSUE THREAD

**Issue by MrQwerky** [Drive4ik/simple-tab-groups#648]
**Describe the bug**
Using STG's "Always Open Tabs in Container - Temporary Container", and with Multi-Account Containers installed, there is a conflict when Multi-Account Containers is set to "Always Open in ..." for a particular site, and that site is opened either from the URL bar, or from a bookmark.

**To Reproduce**
1.  Open a site (for example, a weather site), and in Multi-Account Containers, select "Always Open in ..." (for example, Personal).
2.  Bookmark that site, then close the tab.
3.  For the current group, set STG's "Always Open Tabs in Container - Temporary Container".
4.  From your bookmarks, open the site you just bookmarked (or just paste the URL into the URL bar and open).
5.  Firefox opens **two** tabs:

The first says "Open this site in your assigned container?" and offers two choices, which are:
"Open in Temporary Container XXX container" or "Open in Personal container".  This is the expected behavior with STG's "Always Open Tabs in Container - Temporary Container" selected.

The second tab also says "Open this site in your assigned container?", and the two choices are:
"Open in Current container" and "Open in Personal container".  This is the normal Firefox behavior without STG.

**Expected behavior**
With STG's "Always Open Tabs in Container - Temporary Container" selected, only the first tab above should appear.  (The second tab above [and not the first] might be expected without that STG setting.)

**Desktop (please complete the following information):**
 - Windows 10 64-bit
 - Firefox 77.0.1
 - Simple Tab Groups version: 4.5.1

**Additional context**
Thank you for STG!  It goes far beyond the pre-Quantam Tab Groups extension.  Temporary Containers is a valued addition, but please provide some documentation on its configuration and use!

**Comment by Drive4ik** [comment]
I have already fixed this bug, wait for the next release
