### ISSUE TITLE
Show total tab count in group list and in the manage groups page

### ISSUE THREAD

**Issue by jtagcat** [Drive4ik/simple-tab-groups#649]
**Is your feature request related to a problem? Please describe.**
No. I guess all other tab counter add-ons slow down the browser too much, as they expect to keep the tab count up to date with each tab opened (and recount all hundreds of tabs each time).

**Describe the solution you'd like**
Show 'n tabs total' in Manage Groups header: 
![image](https://user-images.githubusercontent.com/38327267/86859786-f8da7700-c0b2-11ea-8baf-216f906323a7.png)

..and/or at the bottom of 

**Describe alternatives you've considered**
Answer 'How many tabs was that?' (when STG showed all tabs unhidden for a moment, with multi-row-tabs amplifying the effect) without going to about:addons, enabling a tab counter add-on, waiting a few and getting the answer.

**Additional context**
I might come back in 3 months and make a PR.

**Comment by Drive4ik** [comment]
Please enable option "Show active tabs in groups popup" in addon options

**Comment by jtagcat** [comment]
I have that enabled, might be miscommunication, total tab count sum of all tabs in all groups.

Additional context:
 - Other extensions can't count archived tabs.
 - But bash can: https://github.com/Drive4ik/simple-tab-groups/wiki/Use-backups-to-get-statistics-on-your-total-tab-count.

**Comment by jtagcat** [comment]
@Drive4ik did you delete the wiki post? :/

**Comment by Drive4ik** [comment]
@jtagcat 
Firstly, I didn't know that anyone can edit the project's wiki.
Secondly, you did not ask me if it is possible to post the bash code, because the code has not been tested by me.
In the third, I do not consider it so important to know the total number of tabs, and for this to run untested code that can harm the user's system.
