### ISSUE TITLE
Invisible Group? lost tabs.

### ISSUE THREAD

**Issue by meru448** [Drive4ik/simple-tab-groups#65]
Not sure how to describe it otherwise, but my group with dozens of tabs shows only 1 tab via the overview display & if I click on it I lose my active session with no way to return to it on the overview.

**Comment by Tyrewt** [comment]
Sounds similar to: [Tabs missing from Group after closing / restarting Firefox](https://github.com/Drive4ik/simple-tab-groups/issues/62)

@Drive4ik Please re-open Issue #62

**Comment by Drive4ik** [comment]
ok
@meru448 please, read last me comment in #62
