### ISSUE TITLE
Enable use of sub-groups

### ISSUE THREAD

**Issue by Stetto** [Drive4ik/simple-tab-groups#651]
Hi, 

i have some groups like a "Shopping List" for a smartwatch, washing maschine, LED bulbs, motorcycle .. 
i want to group this in a supergroup. 

and i have some groups for excel/VB, contao, web design and so forth and want to groups this groups as a super group "programming" or something like that.

is that possible or will be? can't find existing issues or features.

**Comment by gkaklas** [comment]
I believe this is a duplicate of #302 :thinking:

**Comment by Stetto** [comment]
oh yes, i think so. and #535 

don't know why i didn't find those tickets earlier.

unlovely to read, that it is nearly impossible and so hard work :-/ 

thanks

**Comment by gkaklas** [comment]
Then you can close this issue! :)

**Comment by jdevoldere** [comment]
I have several groups that have 100+ tabs. Sub-groups would really make life easier.
