### ISSUE TITLE
Hide group opened in a new window or the opposite of [Open group in new window]

### ISSUE THREAD

**Issue by brain8891** [Drive4ik/simple-tab-groups#653]
**Is your feature request related to a problem? Please describe.**
You can open a group in a new window using `Open group in new window ` right click context menu 
![image](https://user-images.githubusercontent.com/7104190/87604466-72084880-c709-11ea-82d6-cdaf91b4c227.png)
but you can't close that group without loosing your tab history, and loaded/active tabs. I

**Describe the solution you'd like**
another right click context menu to `Close tab group window` and it would work if you have more than one window opened 

**Describe alternatives you've considered**
-

**Additional context**
 just a question, web extension API still don't give access to tab history?

I tried a work around which didn't work. I created a new group and switched to it, and then when I tried to close the window it warned me about more than one tab. So is there any workaround for now?

Lastly, THANK YOU! For maintaining this amazing addon

**Comment by Drive4ik** [comment]
> web extension API still don't give access to tab history?

No

This button unloads the tabs, but does not close them (it just makes them hidden in the same window)
![изображение](https://user-images.githubusercontent.com/7843031/95477771-5ec7ea80-0991-11eb-86aa-83e275fc9b0f.png)

and here is how the addon restores tabs
![restore-tabs](https://user-images.githubusercontent.com/7843031/95477984-9fbfff00-0991-11eb-90f2-5626c2e6ca44.gif)


however, the entire history of the tabs will be lost. It's unavoidable
