### ISSUE TITLE
Losing group contents

### ISSUE THREAD

**Issue by a-rock-lobster** [Drive4ik/simple-tab-groups#656]
**Describe the bug**
Whenever I close all Firefox windows, but firefox remains open (mac os) I lose all of my groups content. Basically, I have to keep one window open at any time or lose all of the tabs within STG.

**To Reproduce**
On mac OS. Have some groups set up with tabs. Close all firefox windows, but do not quit firefox (in other words, firefox is open but with no active windows). Open a new window and all STG tabs are gone. The groups are there, but empty.

**Expected behavior**
I would expect STG tabs to be permenant unless I personally delete them and not worry about making sure I have one active window around.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - MAC 10.15.6 
 - Firefox version: 78.0.2
 - Simple Tab Groups version:  4.5.1

**Additional context**
N/A

**Comment by bd808** [comment]
I have been seeing this problem consistently for at least a week and a half. A backup is generated when I close my browser, but not loaded on startup. Instead as @a-rock-lobster said I see a list of my groups but all are empty. Manually restoring the prior backup recreates the groups with tab content.

**Desktop (please complete the following information):**
* OS X 10.15.6
* Firefox 79.0
* Simple Tab Groups 4.5.1

**Comment by slinkp** [comment]
Yes, all groups empty at start. "Restore previous session" works for me as
a workaround.

**Comment by Drive4ik** [comment]
Unfortunately, add-ons do not have such great features. This topic has already been raised.
Close the last window with the hamburger menu or Ctrl + Shift + Q
