### ISSUE TITLE
Feature request: automatically clean up empty groups

### ISSUE THREAD

**Issue by kahing** [Drive4ik/simple-tab-groups#658]
**Is your feature request related to a problem? Please describe.**
I open up new windows for video meetings from time to time but simple tab groups always create a tab group for these new windows. As a result after each week I have a dozen of new tab groups that are empty.

**Describe the solution you'd like**
When a window is closed, if that's the last tab in the tab group, and the tab hasn't been renamed from the default, delete the tab group

**Comment by kssi** [comment]
You might want to go to the preferences and disable the "Create a new group when opening a new window" option instead.

**Comment by Aybee** [comment]
I have now deactivated this option. Let's see if empty groups continue to be created.

**Comment by Drive4ik** [comment]
@kahing please, disable option "Create a new group when opening a new window" in addon settings

**Comment by Aybee** [comment]
> I have now deactivated this option. Let's see if empty groups continue to be created.

Yes, this works 👍
