### ISSUE TITLE
Restore Quicksaver's "Tab Groups" option has trouble if Session Data included in backup

### ISSUE THREAD

**Issue by Tyrewt** [Drive4ik/simple-tab-groups#66]
New issue discovered with the Restore Quicksaver's "Tab Groups" option. When creating a backup in Quicksaver's Tab Groups, you have the option to export the session data. Your import feature works correctly on a regular backup, but if the session data is included in the backup, the Tab count listed in Groups is WAY off.

For example, on a regular backup (no session data) I have 20 Groups, one of these Groups has 239 Tabs. This imports correctly.

I also tried a backup which includes session data and then imported. The 20 Groups are intact, but the Tab count is 1002. Doesn't seem to be any logic to the count increase. You can replicate the issue by importing a backup from Quicksaver's Tab Groups both with and without session data.

**Comment by Drive4ik** [comment]
Hi!
can you gite me example this backup?

**Comment by Tyrewt** [comment]
@Drive4ik No, sorry. Private information is included within the Session Data. I'll see if I can create a generic backup though. In the mean time, perhaps you can install an older version of Firefox with Quicksaver's Tab Groups in a Virtual Machine to generate a backup too.

**Comment by Drive4ik** [comment]
Please, re-test this issue in latest version v2.3.5

**Comment by Tyrewt** [comment]
@Drive4ik Confirmed fixed - Tested 2.3.6.
