### ISSUE TITLE
Slow to show Manage Groups

### ISSUE THREAD

**Issue by fish-face** [Drive4ik/simple-tab-groups#660]
On Linux, Firefox 76, STG version 4.5.1 there is a noticeable maybe half second delay between pressing the "manage groups" shortcut and the tab displaying. This makes rapidly switching between groups in a random fashion quite slow - slower than with the Panorama View extension I was using before, which was showing and animating fancy thumbnails.

A loading spinner is shown briefly before the groups display. I wonder if the contents can be cached to make this quicker. Also the loading spinner fades out smoothly which is actually a significant fraction of the overall delay - if this could be reduced or eliminated it would probably be better UX. Notably the new tab does not fade *in* so it's not like you're preventing the whole browser window from flashing during this process.

**Comment by Drive4ik** [comment]
"Manage groups" mostly done to organize tabs between groups, not to quickly navigate between groups. Use the popup window to quickly switch. You can also choose which group to load by creating a hotkey.
In any case, with future versions, I will optimize the entire add-on to increase speed.
