### ISSUE TITLE
Quicker "random access"

### ISSUE THREAD

**Issue by fish-face** [Drive4ik/simple-tab-groups#661]
Currently there are shortcuts (from FF) to navigate to next/previous tab, and (from STG) to navigate to next/previous tab group. There is also a shortcut to open Manage Groups but, as per #660 this is rather slow. Parallel to improving the speed of showing Manage Groups, more shortcuts could be added to, for example, display the popup from the extension's icon and focus the search bar, to allow rapidly going to a tab unrelated to the current one.

**Comment by mzguy** [comment]
Go to Firefox options, navigate to the Extensions section, then click the top-level gear icon (not the three dots next to each extension). From there, you can set a shortcut key to the extension popup button. When opened this way, focus is already in the search bar. This already works wonderfully when done that way.

**Comment by Drive4ik** [comment]
Answered at #660, tickets are very similar
