### ISSUE TITLE
STG Archiving and Backup function breaking Tree Style Tab trees

### ISSUE THREAD

**Issue by byblo** [Drive4ik/simple-tab-groups#662]
I am using both of addons: Simple Tab Groups & Tree Style Tab, which makes FF browser fantastic for who uses a lot of tabs everyday, without wasting time bookmarking everything all the time.

But I noticed that after restoring an archived group or restoring tabs from the backup json file, the trees that TST uses are all gone. 

I guess remember it is the same with the STG bookmarks save, there is no tree structure using prefix characters like > and >> >>> ect...

Is there a compatiliby problem between those 2 addons or is it a bug?

If not bug, can STG support those tree prefixes from TST to make both addons compatible on this topic?

**Comment by piroor** [comment]
Just an idea: if STG saves "openerTabId" information to its archive and restores them, TST can restore tree structure for tabs in imported groups based on their "openerTabId". Moreover, it will help other tab management addons referring "openerTabId" of tabs. How about this?

**Comment by Drive4ik** [comment]
@byblo 
I've already implemented this (as much as possible) here #601.
I just checked it, it seems to work. But bugs are possible. If you have any questions, write in this ticket #601
Please, wait next release

@piroor If there are bugs, your help will be needed)
