### ISSUE TITLE
Clicking 'Create Group' results in 0 tabs group

### ISSUE THREAD

**Issue by technochitlin** [Drive4ik/simple-tab-groups#663]
**Describe the bug**
When I tell the addon to create a new group it creates a group with zero tabs

**To Reproduce**
1. Go to Simple Tab Groups addon
2. Click on 'Create New Group'
3. Group created has 0 tabs

**Expected behavior**
Group created containing all open tabs

**Screenshots**
Attached

**Desktop (please complete the following information):**
 - OS and version: Windows 10 Pro 2004
 - Firefox version: 79.0
 - Simple Tab Groups version: 4.5.1
![STG1](https://user-images.githubusercontent.com/737753/89126414-167cdf80-d4ab-11ea-9b45-399b533ce036.png)

**Additional context**

**Comment by Drive4ik** [comment]
>  Group created containing all open tabs

No, you shouldn't. Because it is not obvious, and many users who do not want this behavior do not know how to pull tabs out of this group later ..
Use this button:
![изображение](https://user-images.githubusercontent.com/7843031/95469699-9da57280-0988-11eb-82f4-484fd32bce08.png)
