### ISSUE TITLE
Allow STG popup height to be larger

### ISSUE THREAD

**Issue by iDuck12** [Drive4ik/simple-tab-groups#664]
If there are many groups created (18+), the STG popup has a fixed height with a scroll bar forcing the user to scroll down to view more existing groups. My screen resolution has more than enough space to allow the STG popup to display all groups at once without the need for a scrollbar. Is this possible to implement?

**Comment by nekohayo** [comment]
Just a thought if the author is indeed able to fix this (i.e. if the WebExtensions API allows it?) : you'll probably have to take into account multi-screen setups. I've seen many apps trying to size to the dimensions of the biggest screen while they are positioned on the smallest screen (such as a laptop's monitor).

**Comment by Azhe403** [comment]
up

**Comment by Drive4ik** [comment]
@iDuck12 
Unfortunately this is not possible. But I made an extended popup option in the settings. Wait for the addon update.

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Popups#Popup_resizing
