### ISSUE TITLE
STG breaks downloads in Private windows

### ISSUE THREAD

**Issue by adrian5** [Drive4ik/simple-tab-groups#665]
**How to reproduce**

NOTE: This works _despite_ STG being disallowed in Private windows!

1. In a Private window, open one or more tabs (empty ones are fine)
2. Start a (sufficiently slow/long) download in that window
3. Open Downloads pane (`about:downloads`)
4. Close all other tabs in that window (you'll end up on the Downloads tab)

Result: Download is terminated and immediately cleared from the Downloads pane. One doesn't even need to close the Downloads pane itself to cause this.

**Expected behavior**

STG shouldn't disrupt the usual download behavior in Private windows.

**Comment by Drive4ik** [comment]
I was unable to repeat the problem. And it is unlikely that STG is associated with this.
Try to make a new clean profile in FF and record this behavior on video. 
https://www.cockos.com/licecap/

**Comment by adrian5** [comment]
I can get it to break with a fresh profile if I set `browser.newtabpage.enabled`¹ to **false**. That seems to be the key ingredient.

Related Firefox bug reports: [1474743](https://bugzilla.mozilla.org/show_bug.cgi?id=1474743) and [1188732](https://bugzilla.mozilla.org/show_bug.cgi?id=1188732). Not sure if you could fix it on your side, or if that has to be done in Firefox's innards.

¹: _Makes new tabs open as blank pages, instead of ads/suggestions._
