### ISSUE TITLE
Tab icons are not restored from the backup

### ISSUE THREAD

**Issue by me21** [Drive4ik/simple-tab-groups#667]
**Describe the bug**
Tab icons are not restored from the backup. Tab icons saving was enabled. Examining the backup file contents suggests that icons data is there, but isn't restored.

**To Reproduce**
1. Include tab icons in the backup.
2. Backup tab groups.
3. Close all & Restore tab groups.

**Expected behavior**
Tab icons should be restored. Notice there's no icons in the tabs which were not opened since restore.
![stgbug](https://user-images.githubusercontent.com/807120/89742850-25b0ee00-daa6-11ea-8298-1a201e759656.png)

**Desktop (please complete the following information):**
 - Windows
 - Firefox version: 79
 - Simple Tab Groups version: 4.5.1

**Comment by Drive4ik** [comment]
This is not a bug but an FF limitation. The addon cannot set the favicon of the tab, it does the browser. And the browser does this when the tab is loaded. Imagine what could happen when restoring a backup of 2000+ tabs, and each of these tabs will load ...
