### ISSUE TITLE
Where is the option to hide archived groups?

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#669]
In #609 , there it is stated that there should now be a way to hide archived groups from view. Where is that? I don't see it anywhere.

**Comment by Drive4ik** [comment]
This will be released soon
![изображение](https://user-images.githubusercontent.com/7843031/95354259-e0097980-08cc-11eb-8615-d6a1d1b011ea.png)

**Comment by mzguy** [comment]
Thanks. However, this setting doesn't affect archived group visibility in the button view, or in the sidebar. I think it should.

**Comment by Drive4ik** [comment]
@mzguy done. new option will available by context menu on addon settings icon
![изображение](https://user-images.githubusercontent.com/7843031/97934689-0e209300-1d7f-11eb-8178-f38da2d77d56.png)
