### ISSUE TITLE
Adjust the behavior when clicking on a tab within a group in the "Manage Groups" window

### ISSUE THREAD

**Issue by jeremymeyers** [Drive4ik/simple-tab-groups#673]
At the moment, when you click on a tab within a group in the manage groups window, it moves the tab.  This seems less than ideal especially since there aren't any UX elements that imply this behavior.

My suggestion would be to have three icons show up on the right hand side when Mouseover-ing a tab:
"->" which would open a context menu with a list of groups and the tab could be moved
"X" which would delete with a confirmation message
(down arrow) which would move the tab to the end of the row/bottom of the list

**Comment by Drive4ik** [comment]
> when you click on a tab within a group in the manage groups window, it moves the tab.

The tab doesn't move anywhere. Clicking a tab on the manage groups page loads the selected group with the selected tab in the selected window.
