### ISSUE TITLE
Feature request: Close tabs with middle-click from Manage Groups when thumbnails are active

### ISSUE THREAD

**Issue by tobz1000** [Drive4ik/simple-tab-groups#675]
We can close tabs by middle-clicking them from the STG drop-down dialog. We can also do this from the Manage Groups page, but only when 'Show tabs with thumbnails in "Manage Groups" page' is disabled.

It would be convenient if middle-click-to-close was available on the "Manage Groups" page when thumbnails are enabled.

Related: #132

**Comment by Drive4ik** [comment]
It already exists and works. Press the middle mouse button on the title of the tab.

**Comment by tobz1000** [comment]
Thanks! Would you consider a PR to expand the clickable area to the whole tile?

**Comment by Drive4ik** [comment]
It's my pleasure) 
No, then scrolling within a group with many tabs will stop working (1000+)
