### ISSUE TITLE
Win10: Allow auto backup of groups to file to specify 'folder name' other than under 'downloads'

### ISSUE THREAD

**Issue by sugob** [Drive4ik/simple-tab-groups#676]
In STG settings, tab 'Backup your Simple Tab Groups'  (Win10 64-bit)
Can specify a 'Folder Name' to 'Auto backup all groups to file (**into downloads folder**)' - as it says, this folder is my Windows  Download folder i.e. '%USERPROFILE%\Downloads'

Request: I'd like it to save these files elsewhere i.e. be able to specify an alternative path to downloads folder
Reason: If this computer disc corrupts, then I'd also loose all these STG backup files just when I needed them the most! e.g. I'd want the last backup file to load into FireFox of my rebuilt disc
If I could change this downloads folder, I'd specify a path under my 'S:' as this is my NAS & it is set to auto backup these files to dropbox

TIA

**Comment by Drive4ik** [comment]
This is prohibited by the browser itself for security reasons.

**Comment by sugob** [comment]
Ok, thanks
I found a workaround by using a directory symbolic link - I'm running latest Win10
i.e. create a symlink from where STG thinks it's writing it [under users 'Downloads' folder]
     to the actual location I want it [e.g. a path under the 'S:' for my NAS]

Use windows explorer to create the location where want to actually create the STG backup files - for me this is 
S:\Backup_Win10\Firefox\SimpleTabGroups 

Run windows 'cmd'    - To avoid a privilege error with 'mklink' later, I needed to run it as administrator [maybe as my S: is a network share?]
In this 'cmd' window, enter the following commands
cd %USERPROFILE%\Downloads                                                                    # Change to where STG writes it's backups 
mklink /d "STG-backups-FF"  "S:\Backup_Win10\Firefox\SimpleTabGroups"     # Create the symlink              

In Firefox, STG setting tab 'Backup your Simple Tab Groups' change the field 'Folder Name' to the new symlink
i.e. "STG-backups-FF"

That's it - will now create the backups when manually click button 'Create Backup' or by the automated 'Create backup every'

**Comment by Drive4ik** [comment]
As an option! There is hardly any other way to solve this problem. This is a little easier on Linux.

**Comment by sugob** [comment]
Yea, I usually use that too. Remember, Linux equiv command '**ln**' has the params the other way around
e.g. if want to backup to '**/home/user/SimpleTabGroups/**', 
**ln -s   /home/user/SimpleTabGroups/     STG-backup-FF**

I notice that STG names the backup folder with the FF version number e.g. '**STG-backups-FF-81.0.1**' 
Will this field update for every new version of FF i.e. will I need to remember to set it back to my val of '**STG-backups-FF**'  ?

**Comment by sugob** [comment]
P.S. Drive4ik - Nice work, this is a really (really!) great addon/extension or whatever mozilla calls it. I used to use TabMixPlus/Tab Groups/Session Manager with FF before their demise and now use STG and a chrome.css hack to enable multi row tabs (one day it will irrevocably stop working and I will cry :-(  ;-) )

**Comment by sugob** [comment]
Just noticed minor issue (IMHO) in that clicking the STG option 'Restore backup' does not use the value I set in 'Folder name' i.e. "STG-backups-FF" - the popup dialog seems to use the original default value for this field i.e. 'STG-backups-FF-81.0.1'

**Comment by Drive4ik** [comment]
@sugob This is not an issue, just FF/OS (exactly in windows) keeps the last path in the file selection dialog

**Comment by sugob** [comment]
@Drive4ik. Ok, my mistake [shocker..not!]
Thanks for your time - keep it up [or down/sidewards - whatever keeps it moving forwards!] ;-)
Cheers
M
