### ISSUE TITLE
Groups set to "always open in container <x>" no longer work correctly 

### ISSUE THREAD

**Issue by helkav** [Drive4ik/simple-tab-groups#677]
**Describe the bug**
e.g. a groups named X set to "always open in container <x>" opens instead in no container and therefore is moved to the group I call "default" which has open in no container and catch and move to no container set.

**To Reproduce**
1. Go to group X
2. Click on + for new tab to right of existing tabs
3. Open any web page/address
4. the tab gets moved to my default group
5. I go back to the default group and have to reopen in container x at which point it is caught and moved to tab X and I have to move back there!

**Expected behavior**
1. Go to group X
2. Click on + for new tab to right of existing tabs
3. Open any web page/address
4. _**the tab should be opened in container x**_

**Desktop (please complete the following information):**
 - OS and version: windows 10
 - Firefox version: 81.0 / 64bit
 - Simple Tab Groups version: 4.5.1

**Additional context**
I have only noticed this happening recently so I suspect it's in a recent update: I allow updates to happen automatically. If you need me to downgrade and test etc let me know

**Comment by Drive4ik** [comment]
Opening a tab and moving a tab are two different things. Most likely this option is enabled. It is disabled by default.
![изображение](https://user-images.githubusercontent.com/7843031/95349427-c0bc1d80-08c7-11eb-8323-9c58d36758b3.png)
