### ISSUE TITLE
No method to undo "Open Group in New Window"

### ISSUE THREAD

**Issue by Solid-Ice8** [Drive4ik/simple-tab-groups#678]
**Describe the bug**
When right-clicking X group, the first option available is _Open Group in New Window_, This is working correctly.

However, how does one **merge the group back into the main window**?

I have FoxyTabs installed, this add-on is my little workaround to "Merge all windows", but I'd have to manually move each tab back into their appropriate group(s).

**To Reproduce**
Steps to reproduce the behaviour:
1. Right-click any existing group.
2. Click on 'Open in New Window'
3. Look for a way to merge the new window back.
4. There is currently no way to merge newly opened Window(s) back into the main groups.
5. a) When closing the new window, all tabs in that specific group will be completely lost and unrecoverable with Undo Close Tab.
5. b) FireFox option: "_When you when closing multiple tabs_"  won't help in this scenario as well.

**Expected behaviour**
A method should be available to merge newly windowed groups back into one window session instead of 2.

Desktop & Laptop
 - OS and version: Windows 10 Education, 64Bit, version 2004 (& Win10 Home 64Bit, version 1909)
 - Firefox version: 81.0.1
 - Simple Tab Groups version: 4.5.1

**Comment by Drive4ik** [comment]
addon work like this:
![restore-tabs](https://user-images.githubusercontent.com/7843031/95348749-01fffd80-08c7-11eb-9f20-6eb31852573d.gif)

**Comment by Qwerty-Space** [comment]
> addon work like this:
> ![restore-tabs](https://user-images.githubusercontent.com/7843031/95348749-01fffd80-08c7-11eb-9f20-6eb31852573d.gif)

This doesn't work for me.

I have two Firefox Windows open, but if I attempt to close one, it asks if I want to close that window.  Will I lose my tabs if I do that?

![image](https://user-images.githubusercontent.com/6967592/123526400-869de080-d6cf-11eb-8ee9-ad2d25ada0d7.png)

**Comment by kgadek** [comment]
I have the same behaviour as Qwerty-Space

**Comment by Qwerty-Space** [comment]
It seems to be fine if you close. Though, the tab tree might not be restored correctly.
