### ISSUE TITLE
FF crashes during startup in most of the cases. If it passes startup, everything is fine.

### ISSUE THREAD

**Issue by ddTech** [Drive4ik/simple-tab-groups#679]
Not sure if it is a bug, but it's definetly not a feature request, so I place it here :-)

**Describe the bug** / **To Reproduce**
I really like the simple tab groups, the design and handling is wonderful and once my FF is up and running everything is fine. 
however in most of the cases FF crashes upon startup.
In these cases FF comes up and at the position where normally the tab groups icon is located a "wheel" is spinning constantly. 
It's then either spinning forever and firefox stays up or firefox crashes and brings up its crashreporter.

If everything goes well, I do see the tab-groups icon within a few seconds after startup. 

If we (FF and me) make it past that startup phase, I have no issues whatsoever. 

I do have lots of open pages (currently 297) and 20 tab groups. Win7 with 8GB  RAM.  That seems to relate to the problem. Sometimes it seems to be impossible to get out of the spinning wheel phase. If I then deactivate the plugin, close a few pages, reactivate the plugin and restart FF, it seems to work better. 
Needless to say that I close all unnecessary applications before starting FF

Starting FF with the plugin deactivated seems to work fine every time, as well as activating the plugin after FF is completely loaded.

Any Idea ? Let me know, if You need more information

regards

Frank

**Comment by Drive4ik** [comment]
Your system may not be pulling in as many tabs. However, this is not addon related. If not, create a new clean FF profile and test on it.
