### ISSUE TITLE
Don't close firefox if closing last tab and another group exists

### ISSUE THREAD

**Issue by nico202** [Drive4ik/simple-tab-groups#68]
Hi, thanks for this, I love tab groups/panorama while it seems that mozilla tries to kill it every time.

The problem I having with this is, if I have a 2 tab groups and I close the last tab from the group I'm in, firefox closes. I'd like it to switch to the other group, is it doable?

Thanks, Nicolò

**Comment by Drive4ik** [comment]
Hi @nico202 
Sorry, but in FF API doesn't have functional to save window after closing last tab.
But, if you delete current group (loaded in current window) you will auto-redirected to closest group.

I found other solution:
https://support.mozilla.org/ru/questions/1015675
> You can set the browser.tabs.closeWindowWithLastTab pref to false on the about:config page.
    about:config page: browser.tabs.closeWindowWithLastTab = false 
You can open the about:config page via the location/address bar. You can accept the warning and click "I'll be careful" to continue.

**Comment by nico202** [comment]
Thanks! Set this, does not switch to the other group but better than nothing
