### ISSUE TITLE
Mark groups as sticky

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#680]
**Is your feature request related to a problem? Please describe.**
I have many rules for automatically catching and moving tabs, and many groups. Some of the groups are sticky, some are not. It's hard to remember which groups are sticky, and which are not. To know whether they are, I have to go into the group's settings.

This is an issue because many of my groups match my containers, and I don't want a tab to fail to get the right container simply because I forgot I'm in a sticky group when I open it.

**Describe the solution you'd like**
Much like the browser makes pinned tabs look different, STG should make sticky groups look different. I believe this should happen in two types of locations:
1. Lists of groups, such as that visible in the toolbar button, or the Manage Groups window.
2. The extension's button.

To enable #2 to work the group's icon needs a small changes, such as a little pin, asterisk, or similar revision to the group's icon. Alternatively, the icon could get some sort of glow effect (or a background color), though I think a small but obvious mark would be better, such as a little yellow pin.

**Describe alternatives you've considered**
I suppose one alternative is to use one of the stock icon types to always denote sticky groups. This is a clumsy solution though, since I have to remember which one, I have to remember to set it, and I then can't use the website icon feature. It's much cleaner to simply mark a group as sticky somehow.

**Comment by Drive4ik** [comment]
Done. Please wait next release

**Comment by mzguy** [comment]
It appears there's a small issue with this. I just removed the "sticky group" setting on a group, but the pin remained on the icon until I switched groups then switched back again. It appears "Sticky group" setting removal does not trigger an icon refresh.

**Comment by Drive4ik** [comment]
I know, this bug was fixed in 358a00384e0db9b14019b4fe9c7f8a633a8b39fd
Fix will be on next release

**Comment by EnderMk9** [comment]
Hello, would it be possible to add an option to hide the little pin when a group is sticky, at least in the extensions button. I understand it's use but for me it's a bit distracting and hides part of the group's icon.
