### ISSUE TITLE
Resizing the groups in the view "Manage groups"

### ISSUE THREAD

**Issue by impala75** [Drive4ik/simple-tab-groups#681]
Hello,

The view "Managed groups" being set on displaying the tabs with stickers (sorry, I don't use STG in English, so I might not use the right words here), I would like to be able to resize the groups manually, according to:

- the importance I grant to one group or another,
- the number of tabs of each group: 1) if a group only has a few tabs, I don't need the display to use so much space, 2) on the other hand, when the number of tabs is high, I often want to reduce the size of the group (and the size of each tab sticker to adapt accordingly).

**Describe alternatives you've considered**
I have tried the add-on "Panorama Tab Groups" before trying STG, and it offers this possibility, in addition to moving the groups in the display as much as needed.

**Comment by Drive4ik** [comment]
dublicate of #362
