### ISSUE TITLE
Dynamic archiving.

### ISSUE THREAD

**Issue by jtagcat** [Drive4ik/simple-tab-groups#689]
Possibly major performance improvements can be gained, if discarded tabs are closed, and moved to the json archived datastore.

In groups not loaded for at least n minutes, archive (close) discarded tabs.

This seems like loads of work, but might be worth it, as the browser would be dealing with <1% of the tabs actually open.

(Getting near to processor architectures here...)

Related #688

**Comment by Drive4ik** [comment]
It is too complicated in terms of implementation, and as for me it is absolutely unnecessary. Firefox uses almost no memory for discard tabs. Even if there are 5000+ of them.
I think this addon will suit you:
https://addons.mozilla.org/firefox/addon/auto-tab-discard/
