### ISSUE TITLE
Admin groups -> Vertical scroll resets every time you close a Tab

### ISSUE THREAD

**Issue by Zeioth** [Drive4ik/simple-tab-groups#69]
Right now this feature is great to order your tabs, but not for closing your old tabs when you have a lot of them, since every time you close one tab, the scroll goes up every time. Probably you are already working on it, just opening the issue.

Example: http://i.imgur.com/ncN958D.png

**Comment by Keith94** [comment]
This seems to be fixed in the latest experimental version.

**Comment by Drive4ik** [comment]
Hi this bug was fixed in STG v3.0 and FF 61
