### ISSUE TITLE
Backup location

### ISSUE THREAD

**Issue by onebrowtech** [Drive4ik/simple-tab-groups#693]
Is there any possibility of adding an option, in settings, for _choosing_ the location for the Backups folder, as opposed to the default location (Downloads)
If the desktop is set as as the default location for downloads, the backups folder stays permanently on the desktop.

**Comment by Drive4ik** [comment]
No addon can do this. Firefox did this for security reasons.
Maybe this will help
https://github.com/Drive4ik/simple-tab-groups/issues/676#issuecomment-706592426

Dublicate of #596
Dublicate of #676

**Comment by onebrowtech** [comment]
@Drive4ik - Thanks v.much.
I would like to re-iterate @sugob's PS:
"Nice work, this is a really (really!) great addon/extension or whatever mozilla calls it."

**Comment by sugob** [comment]
@onebrowtech - if have issue setting up the symlink trick, then post into this thread

I didn't realise this (specify path for backups) is such a frequent request!

Minor request: When going into STG and doing a manual backup, it'd be nice if could specify a string in the STG options that is added to the filename by default - would make it easier to spot manual backups when reviewing the backup files 
e.g. if this string is '-adhoc', then the default name would be 'stg-backup-2020-10-16~23-04-adhoc@drive4ik.json'
Or, as can change the filename on the popup anyway, maybe instead allow a similar string to be added to the automated backup filename (and default it to '-auto') ?

**Comment by Drive4ik** [comment]
@sugob I added prefix to file name `auto-` or `manual-`  
296706632d763e6da6f752e0efda269d9db3f3fd
I think the prefix will be better for sorting files in a folder

**Comment by sugob** [comment]
@Drive4ik Nice 🥇 
On windows explorer, I usually sort files by mod date and will now be able to easily see which I created manually

As I have the STG auto backup at max [i.e. backup every 1 hour] which creates many backup files [each 2.1MB - I have total of ~330 tabs in 7 groups], I can periodically sort by name [which includes backup date] and easily select/zap the older auto files [without risk of deleting a manual backup].
Now if STG didn't create an automated backup file if it would have identical contents to previous backup [e.g. when browser idling overnight], that would be impressive!

Looking forward to STG 4.5.2
Thanks again for this great add-on

**Comment by Drive4ik** [comment]
@sugob There is an undescribed feature in STG - if the interval for creating a backup is 1 time per day (by default), then STG makes a backup every 2 hours, but does not add a timestamp to the file, and turns on the overwrite option. It turns out if there is an interval of 1 time per day, every 2 hours you have a fresh backup with today's date.

**Comment by sugob** [comment]
@drive4ik An undocumented feature always sounds interesting!
Not sure I follow entirely except that it overwrites by having the same filename [so will get only one file?] but I suppose if computer crashed as STG was overwriting the file, then you'd end up with a corrupt file [don't know it you have option to write with a tmp filename then rename?]. Apologies for being a bit pedantic
Having old backups files maybe useful sometime e.g. if I accidentally delete a tab and don't notice for a while I can always load [or view/grep] the old backups. 
Using symlink trick to write to a NAS with 4TB free space, so I'll come back and hassle you when it fills up in ~200 years ;-)

Actually, I just noticed that it does seem to stop creating backups overnight [maybe when computer sleeps?]

**Comment by sugob** [comment]
Got the update to STG 4.5.2 & restarted FF but I don't see the extra prefix on filename when doing a manual backup
How do I know what commit(s) are in a release (or in the next release)?

**Comment by Drive4ik** [comment]
Addons do not have full file system access due to security reasons.
I haven't rolled out an update with this change yet.

**Comment by sugob** [comment]
Ok. Just wondered how I know what's in a release [some kind of sum of commits?]

**Comment by Drive4ik** [comment]
@sugob 
https://github.com/Drive4ik/simple-tab-groups/compare/v4.5.2...v4.5.5.1
