### ISSUE TITLE
Irregular Behavior With Multiple Windows

### ISSUE THREAD

**Issue by Aetylus** [Drive4ik/simple-tab-groups#694]
**Describe the bug**
When there are multiple Firefox windows open, the behavior of switching groups seems irregular and unintuitive. It's been impossible for me to reasonably open one specific group in one window and another specific group in the second.

**To Reproduce**
1. Have at least two groups defined with tabs in the group
2. Open one group in the window.
3. Open a second window of Firefox (e.g. `Ctrl+N`)
4. Click a second group in the second window.

I've experienced behavior where the second group in the second window will open on that second window, as well as sometimes changing the group on the first window. There doesn't appear to be any pattern that I can discern.

If you have at least three groups, I've noticed just switching between groups 2 and 3 repeatedly can eventually result in one of the groups being opened in a different window then it was previously.

**Expected behavior**
I expect the group clicked in a specific window would open that group in that window.

**Desktop (please complete the following information):**
 - OS and version: Windows 10 1909
 - Firefox version: 81.0.2 (64-bit)
 - Simple Tab Groups version: 4.5.2

Let me know if I can provide any additional details.

**Comment by Drive4ik** [comment]
> as well as sometimes changing the group on the first window

What do you mean by "changing the group"?
Group 1 in window 1 does not change when opening group 2 in window 2.

**Comment by Aetylus** [comment]
I did some further testing with the two groups issue. Given two windows, Window 1 and Window 2, in which Window 1 has Group 1 opened and Window 2 has no group:

1. Press Group 1 in Window 2. No visible changes are made - Window 1 still has Group 1 open, and Window 2 has no group.
2. Press Group 2 in Window 2. Window 1 opens Group 2.
3. Press Group 1 in Window 2. Window 2 opens Group 1.

I would expect the behavior at step 2 to open Group 2 in Window 2.

**Comment by Drive4ik** [comment]
That's right, the bug has been fixed
