### ISSUE TITLE
[Feature Request] Automatic "First Character" Tab Group Icons

### ISSUE THREAD

**Issue by arbitar** [Drive4ik/simple-tab-groups#695]
**Problem**
When one has many tab groups, it is sometimes difficult to immediately recognize which group a window is in based solely on the color of the icon in the toolbar, and uploading custom icons for each group is rather tedious. Some more options for icons would be welcome, particularly ones that dynamically represent some aspect of the tab group in question.

**Example solution**
An option that would be particularly welcome, among the other icon options, would be to support a 'letter' icon that draws as the first character of the name of the tab group. In combination with the existing group coloring functionality, this would represent an increase in the ability to quickly (or even automatically) categorize or recognize many distinct tab groups.

**Alternate solution**
Even without the automatic derivation of the icon character from the group name, the ability to specify a letter would be very welcome. Support merely for character-based group icons this could also lead to the use of "icon fonts" such as fontawesome to help introduce a substantial number of new icons for use.

**Comment by Drive4ik** [comment]
Added new group icon template: group title b7374b7b56e85f977637e63da7f72e1273301d40
It will look like this
![изображение](https://user-images.githubusercontent.com/7843031/97064595-b54b4080-15af-11eb-8514-c024a2075dec.png)
