### ISSUE TITLE
Only create new backup if changes occured in tab groups

### ISSUE THREAD

**Issue by kssi** [Drive4ik/simple-tab-groups#696]
**Is your feature request related to a problem? Please describe.**
Not a big deal since my hourly backups get cleaned up every few days or so, but there are lot of occasions where Firefox is running in the background without being in actual use. Or where you just browse the web using a throwaway window that's not tied to any group. In those cases, STG groups are not altered in any way but backups keep going, cluttering the filesystem with unnecessary (duplicate) files:

```
$ diff stg-backup-2020-10-15\~08-18@drive4ik.json stg-backup-2020-10-15~09-18\@drive4ik.json 
1879c1879
<     "autoBackupLastBackupTimeStamp": 1602742689,
---
>     "autoBackupLastBackupTimeStamp": 1602746299,
$ diff stg-backup-2020-10-15\~09-18@drive4ik.json stg-backup-2020-10-15~10-18\@drive4ik.json 
1879c1879
<     "autoBackupLastBackupTimeStamp": 1602746299,
---
>     "autoBackupLastBackupTimeStamp": 1602749909,
$ diff stg-backup-2020-10-15\~10-18@drive4ik.json stg-backup-2020-10-15~11-18\@drive4ik.json 
1879c1879
<     "autoBackupLastBackupTimeStamp": 1602749909,
---
>     "autoBackupLastBackupTimeStamp": 1602753519,
```

**Describe the solution you'd like**
Track changes or actions in tab groups so that the plugin knows when it's relevant to create more automatic backups.

**Comment by Drive4ik** [comment]
Set the backup time to 1 day, and then the addon will make a backup every 2 hours and overwrite by the current date.
It won't be otherwise
