### ISSUE TITLE
Better UX When Using Microphone/Camera

### ISSUE THREAD

**Issue by FlorianWendelborn** [Drive4ik/simple-tab-groups#697]
Just was very surprised because the addon suddenly stopped working for apparently no reason and switching groups was impossible. I didn’t get a visible error or notification or any indication that the addon even tried to switch

Enabled the debug logs and found the reason:

```json
{
    "before notifications.create": [
        "1602881071643",
        {
            "type": "basic",
            "iconUrl": "some iconUrl",
            "title": "some title",
            "message": "It is not possible to change the group because one of the opened tabs share microphone or camera"
        }
    ],
    "time": "2020-10-16T20:44:31.643Z",
    "stack": []
}
```

I’d suggest recommending affected users this workaround that I found:

I remembered that STG doesn’t "see" pinned tabs. So, I pinned the Google Meet I was on and switching worked flawlessly afterwards. I think that makes it a very minor inconvenience for most workflow.

Thanks for the awesome addon btw.

EDIT: I just re-read the error message and noticed that it says `"before notifications.create"`. I think what happened is that my macOS Do not Disturb was turned on, so I didn’t get the notifiation because of that. Maybe there’s still some potential improvements possible though, like "graying-out" the group switcher with a warning or so. Also, I think the notification should still suggest the workaround as it’s probably not very intuitive for most users.

EDIT2: I can confirm that it was DnD:

![image](https://user-images.githubusercontent.com/1133858/96308936-90c9f400-1004-11eb-9d70-1e955aa8da74.png)

**Comment by Drive4ik** [comment]
Just checked - everything works
There is no other option, because throwing a message (alert) to the user on the page is not a good idea.
