### ISSUE TITLE
Can't select tab groups

### ISSUE THREAD

**Issue by gibinel** [Drive4ik/simple-tab-groups#699]
**Describe the bug**
Not sure if its a bug, but for the last 2 or 3 weeks i have problems with STG.
When i try to switch the groups first it works then the second time i can't select any group (i doesn't even highlight the groups when i mouse over the group names). Then i click on minimize Firefox Window and it minimizes and maximizes the Window really fast (meaning window does not stay minimized)... After a few tries like this it finally works one more time to switch the group and then again its not working.
It's very weird behavior...  
Did anyone else encounter something similar?

**To Reproduce**
1. Switch the group
2. Second try i can't switch group (i can't click on another group), when i mouse over it doesn't even highlight the group names
3. Minimize/Maximize the Firefox window, then works again once
4. Then same problem

**Expected behavior**
Should work like until now, click STG switch group, click STG switch group

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Windows 10 v1809, build 17763.1039
 - Firefox version: 82.0
 - Simple Tab Groups version: 4.5.2

Not sure if there is any other conflicts... or its something related to the last version of Firefox...

**Comment by Drive4ik** [comment]
Really strange behavior. Try testing this on a new clean FF profile
https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles

For more credibility, create a backup of the groups (available in the settings) and restore it to a clean profile.

If the problem persists, try recording a video of how it happens.
https://www.cockos.com/licecap/

**Comment by gibinel** [comment]
> 
> 
> Really strange behavior. Try testing this on a new clean FF profile
> https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles
> 
> For more credibility, create a backup of the groups (available in the settings) and restore it to a clean profile.
> 
> If the problem persists, try recording a video of how it happens.
> https://www.cockos.com/licecap/

I created a new profile and the problem is the same.

I created a recording:
![STG-problem](https://user-images.githubusercontent.com/18382617/97168268-d1f29e80-1790-11eb-8631-f51c43098ce1.gif)

I hope its clear, if not I'll try and record another one.
I also tried rebooting several times, and its still the same.
Another weird thing is that in the recording i just click on the minimize button and it minimizes and maximizes instantly (window should remain minimized).
Is it possible i didn't check some kind of option somewhere (i don't have this problem on my desktop PC)?

**Comment by Drive4ik** [comment]
Yes, this is very strange. I have never seen such behavior. I noticed that the search field becomes active, try typing something in it when you cannot select a group.

This is unlikely to be an STG problem, the browser window should remain minimized, as you said. Apparently, this is interfered with by some other program, or the OS itself (unlikely). You need to find what program is running and doing it.
Also, does this only happen with the FF window? Can't you minimize other windows either? How about Chrome?
If this behavior is only with browser windows, it looks like a malicious program.

**Comment by gibinel** [comment]
I only happens with Firefox, other apps don't have this problem. Chrome is working fine.
Could it be from the last 82 update of Firefox?

**Comment by Drive4ik** [comment]
This is not an STG bug. 
Have you tried reinstalling FF while keeping the profile?
First, you need to find a reason for not minimizing the window.
