### ISSUE TITLE
Does not work correctly with another plugin

### ISSUE THREAD

**Issue by Bigorat** [Drive4ik/simple-tab-groups#7]
Greetings! Since version 1.7, it stopped working with the Tab Open/Close Control plug-in - https://addons.mozilla.org/de/firefox/addon/tab-open-close-control/ 
If you switch from one tab group to another group, while the plug-in Tab Open/Close Control
the tabbed mode is broken, the first becomes the last, the last one is the first and so on. If you can
correct please!
/*-----------------------------------------------------------------------------*/
Приветствую! Начиная с версии 1.7, перестало корректно работать с аддоном Tab Open/Close Control - https://addons.mozilla.org/de/firefox/addon/tab-open-close-control/
Если переключаться с одной группы вкладок на другую группу, при включенном аддоне Tab Open/Close Control нарушается режим расположения вкладок, первая становится последней, последняя первой и так далее. Если можно поправить сделайте пожалуйста!

**Comment by Drive4ik** [comment]
Привет!
Я повторил проблему, и сейчас занимаюсь ее решением. К сожалению подобных проблем много, и я решил переделать основной код. В скором времени проблема будет решена.
Спасибо за то что нашли ошибку и отписались о ней.

**Comment by Drive4ik** [comment]
Hi! I fix this bug in v2.5.3. Please, update to it and retest.
