### ISSUE TITLE
Inconsistent behavior when moving tab to another group

### ISSUE THREAD

**Issue by kssi** [Drive4ik/simple-tab-groups#700]
**Describe the bug**
When moving a tab from one window/group to another group following the method described [here](https://github.com/Drive4ik/simple-tab-groups/issues/635#issuecomment-706607402), the tab sometimes gets prepended to the existing tabs in the other group, and sometimes get appended (which is the expected result).

**Comment by Drive4ik** [comment]
Can you give me more information?
What version of the addon, OS?
Describe the behavior in more detail, because it's hard for me to understand what is moving where, how many windows are open, how many of them are loaded groups, which groups and whether the tab is moved to a loaded group or to an unloaded group.

**Comment by kssi** [comment]
Sorry for not mentioning it:

- Addon version: 4.5.2
- Firefox version: 78.4.0esr
- OS : macOS El Capitan 10.11.6

You can find my usual windows/tabs/groups setup in the debug log file I recently uploaded on issue #635.

What's happening exactly.

Let's consider:
- **group A** with tabs **1**, **2**, **3**
- **group B** with tabs **4**, **5**, **6**

Now let's consider that:
- My current group/window (frontmost Firefox window) is **group A**
- I decide to move the tab **1** from **group A** to **group B** using _Right click on tab **1** in the Firefox tab bar > Move tab to group > **group B**_

The resulting tab list in **group B** may be either:
- **4**, **5**, **6**, **1** (appending, which is the expected result)
- or **1**, **4**, **5**, **6** (prepending, which appears to be a bug)

I can't tell much about the when's and why's, but if I'm correct this only happens when I move a tab to a group that is not currently active, so this may be related.

I couldn't successfully reproduce this on demand to dump a log file, but I'll make sure to enable recording next time I have to move a tab.

**Comment by Drive4ik** [comment]
Thanks for the detailed description, the bug was fixed. Fisk will be in the next release of the addon.
