### ISSUE TITLE
Automatically moving a tab to it's designated container based on URL regex fails

### ISSUE THREAD

**Issue by ChordMankey** [Drive4ik/simple-tab-groups#702]
**Describe the bug**
Automatically moving a tab to it's designated container based on URL regex fails, site also has a default firefox container assigned.
i.e. If I'm on Group 1, but I open a link that matches the regex of Group 2, it doesn't move to Group 2 and instead just opens in Group 1. [Here's the log file](https://github.com/Drive4ik/simple-tab-groups/files/5457569/STG-debug-logs.zip).

**To Reproduce**
Simply open the site that the regex of the group matches while on a different group. IN my case it was store.steampowered.com and the regex was just steam

**Expected behavior**
That the opened tab would automatically be moved to the appropriate group

**Desktop (please complete the following information):**
 - OS and version: Windows
 - Firefox version: 79.0
 - Simple Tab Groups version: 4.5.2

**Comment by Drive4ik** [comment]
STG addon does not assign container to tabs based on tab url.
I have already fixed the error from the logs, it will be in the next update.
