### ISSUE TITLE
Fail to search tab from the pinned tabs

### ISSUE THREAD

**Issue by c02y** [Drive4ik/simple-tab-groups#703]
**Describe the bug**
If I pined a tab, use the search feature by click the STG icon, it won't search the key word from the pinned tabs.

**To Reproduce**
1. Pin one or more tabs
2. Click on STG icon
3. type a word from the the pinned tab url or title
4. no result

**Expected behavior**
Search feature will works for both grouped tabs and pinned tabs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: [e.g. Manjaro Linux]
 - Firefox version: [e.g. 82]
 - Simple Tab Groups version: [e.g. 4.5.2]

**Additional context**

**Comment by Drive4ik** [comment]
Sorry, but STG doesn't work with pinned tabs.

**Comment by c02y** [comment]
Yes, I know it doesn't work, what I was saying is, it doesn't work, so maybe this is a bug, if the feature is not supported by STG, could this feature be implemented? 

I can search the pinned tab using Firefox builtin-in function(at the end of tab bar, there is arrow icon, click it, choose "Search Tabs"), I'm just wondering if this function can be supported by STG.

If it is impossible to do it for some reason such as no such API, I'm OK with that.

**Comment by Drive4ik** [comment]
STG was written with the expectation that pinned tabs are tabs outside of groups. They have limited capabilities, for example, a pinned tab cannot be hidden. To implement your request, code need to unpin the pinned tabs, hide them, and remember which of them are pinned, and then restore in the reverse order.. this needs to rewrite half of the addon. 
And it is not known how many more bugs there may be.
It is also unknown if the user wants some pinned tab to remain the same, that is, it was as it is now, regardless of the loaded group, how to unpin it from the group? There are also possible problems with the order of such pinned tabs.
This is not yet feasible. If FF adds/changes the pinned Tabs API and it gets better and more transparent, I might implement it.
