### ISSUE TITLE
Empty tabs instead of page content

### ISSUE THREAD

**Issue by omares** [Drive4ik/simple-tab-groups#706]
**Describe the bug**

Opening up a new tab and entering any URL results in a new empty tab instead of loading the target URL.
After entering the URL in the new tab, the page is then loaded.

**To Reproduce**

Steps to reproduce the behaviour:
1. Have a group with following settings: 
![image](https://user-images.githubusercontent.com/1375307/98116334-6e5f2400-1ea8-11eb-8442-18045e41e083.png)

2. Open a new tab
3. Enter any target URL (e.g. https://github.com/drive4ik/simple-tab-groups)

**Expected behaviour**

Instead of a new tab the target URL should be loaded.

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Mac
 - Firefox version: 82.0.2 (64-bit)
 - Simple Tab Groups version: [4.5.5

**Comment by Drive4ik** [comment]
fixed, please wait 4.5.5.1 version (under review)

**Comment by Drive4ik** [comment]
I'll leave this ticket open for now so other users can see it.

**Comment by v3470** [comment]
@Drive4ik When will the 4.5.5.1 release on the addons.mozilla.org? I checked update but the latest version is still 4.5.5

**Comment by Drive4ik** [comment]
@v3470 
🤷‍
![изображение](https://user-images.githubusercontent.com/7843031/98186306-22979380-1f17-11eb-99bc-dcfc0b60130e.png)

**Comment by omares** [comment]
Just got the update, can confirm the issue is fixed, but somehow the tab behaviour is weird, but i am not able to pin down the issue.

Does the new tab get closed a new one is opened with the target container?

**Comment by Drive4ik** [comment]
@omares Yes, the logic of work has not changed. The new tab is closed and the tab with the desired container opens. Hot change of containers on the tab without closing it is not yet possible.
