### ISSUE TITLE
New permissions are not documented

### ISSUE THREAD

**Issue by Vinnl** [Drive4ik/simple-tab-groups#707]
**Describe the bug**
After an update just now, I saw the following notification:

![image](https://user-images.githubusercontent.com/4251/98128433-39f36400-1eb8-11eb-95cd-a2755748fb43.png)

However, this permission is not listed at https://addons.mozilla.org/en-GB/firefox/addon/simple-tab-groups/ under the "Permissions used:" header. It would be nice if it would be mentioned there (and possibly in the release notes?).

**To Reproduce**
1. Wait for Firefox to notify you of the upgrade and the updated permissions.

**Expected behavior**
To be able to see the new permission in the "Release notes" tab for the add-on in the Add-ons Manager, on the "Releases" page in GitHub, and at https://addons.mozilla.org/en-GB/firefox/addon/simple-tab-groups/ (or at least at that last location).

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS and version: Ubuntu
 - Firefox version: 82
 - Simple Tab Groups version: 4.5.2 (before the upgrade)

**Additional context**

**Comment by Drive4ik** [comment]
done

**Comment by Vinnl** [comment]
Super, thanks!
