### ISSUE TITLE
"[STG plugin] Create new tab in temporary container" barely visible in dark theme

### ISSUE THREAD

**Issue by ACB1337** [Drive4ik/simple-tab-groups#709]
**Describe the bug**
The icon for "[STG plugin] Create new tab in temporary container" is practically invisible when using the dark theme

**To Reproduce**
1. Enable firefox dark theme
2. Install "[STG plugin] Create new tab in temporary container"

**Expected behavior**
Visible icon

**Screenshots**
https://i.imgur.com/qmmDPet.png

**Desktop (please complete the following information):**
 - OS and version: Windows
 - Firefox version: 82.0.2
 - Simple Tab Groups version: 4.5.5

**Comment by Drive4ik** [comment]
If you turned on the dark theme in STG itself, then you should have met this condition:
![изображение](https://user-images.githubusercontent.com/7843031/98384450-765cc680-2056-11eb-891f-17776b114d9e.png)
