### ISSUE TITLE
Option for disabling notifications

### ISSUE THREAD

**Issue by simmel** [Drive4ik/simple-tab-groups#710]
**Is your feature request related to a problem? Please describe.**
The only time I get notifications from STG is when I move a tab to a different group. I already know that I did this I don't need a notification to tell me what I just did.

**Describe the solution you'd like**
Add an option to disable notifications.

**Describe alternatives you've considered**
Disabling notifcations from Firefox all together, but that also disables them for all other extensions and Fx.

**Additional context**
OS X 10.14.6
Firefox 83.0b6

**Comment by simmel** [comment]
Ignore me! It's already available, I just couldn't find the Settings... Thank you!

**Comment by retorquere** [comment]
Where is it in the settings?

**Comment by retorquere** [comment]
I don't see that option either. @Drive4ik ?

**Comment by SpaceClicker** [comment]
> I don't see that option either. @Drive4ik ?

You have to go to the settings of each group and enable it.

So click on the STG icon in the task bar, then click on the ">" next to the group you want to change, then click on the "gear" icon in the upper right to get to the "Group settings" page.  Then scroll down to find the "Show notification when tabs are moved to this group" option.

You have to do this for EVERY group you want to enable this on, unlike before where it was just one global option for every group.

You can also get to the "Group settings" page for each group within the "STG plugin" "Manage groups" page (where all the groups are shown with thumbnails), by just pressing the "gear" icon in the upper right of each group.
