### ISSUE TITLE
Cannot manage settings or change tab groups

### ISSUE THREAD

**Issue by terminalmage** [Drive4ik/simple-tab-groups#711]
## Describe the bug
Since the most recent update, I cannot use STG at all. Clicking the icon just results in a spinning "loading" icon.

## To Reproduce
1. Click the STG icon in the toolbar

## Expected behavior
To be able to manage settings.

## Screenshots
![stg_wtf](https://user-images.githubusercontent.com/328598/98261422-111baf00-1f4a-11eb-9574-6f57d227c332.png)

## Desktop (please complete the following information):
 - OS and version: Linux
 - Firefox version: 73.0.1
 - Simple Tab Groups version: 4.5.5.1

**Comment by Drive4ik** [comment]
Did you restart your browser completely?

**Comment by terminalmage** [comment]
Yes. Closed browser, ran `ps aux | grep firefox` to confirm no leftover PIDs.

**Comment by Drive4ik** [comment]
Have you tried to open the addon settings through the `about:addons` page?

**Comment by terminalmage** [comment]
I just went there and then clicked to open the Preferences for STG, and it opened up a new tab `moz-extension://<some_uuid>/options/options.html`, which is a blank white page.

**Comment by Drive4ik** [comment]
Try to disable and enable the addon on the addons page. If that doesn't work and there is no error message, then you need to reinstall it.
remove addon -> restart browser -> install addon -> import latest backup which is located in the FF downloads folder

**Comment by terminalmage** [comment]
OK, I removed, restarted browser, and reinstalled. But there is no change. I can't install any backups because the preference page is still a blank page.

The extension still works on my laptop which is running Firefox 82.0.2, but this machine is running Firefox 73.0.1. I can't update that machine because it's a remote machine that I am currently unable to install updates on.

**Comment by Drive4ik** [comment]
Ok, can you go to `about:debugging#/runtime/this-firefox` page, find STG and click inspect button?
Select console tab and take screenshot

**Comment by terminalmage** [comment]
Sure, here it is:

![stg_console](https://user-images.githubusercontent.com/328598/98451663-723fb000-210d-11eb-869f-903f3c51abe8.png)

**Comment by Drive4ik** [comment]
Ok, You can hover your mouse over `background.js` to bring up a popup like this one:
![изображение](https://user-images.githubusercontent.com/7843031/98451843-6aeec580-2152-11eb-8420-8cc8fa5156b2.png)

and find this UUID (highlighted in red) on the qwert page and say what is this addon?

**Comment by terminalmage** [comment]
I cannot see that UUID anywhere in the errors.

**Comment by terminalmage** [comment]
I also can't see that same `ext-onetab-concatenated-sources-background.js`. The errors are mostly from `background.js` in various extensions.

**Comment by Drive4ik** [comment]
No, I showed you for example where to look and where to hover the mouse cursor. You should hover over `background.js` and see a different uuid there, not the one in my picture. It's unique.
![изображение](https://user-images.githubusercontent.com/7843031/98947921-75b4ac00-24fe-11eb-8307-b4c6ed6f6bda.png)

**Comment by terminalmage** [comment]
To be clear, you implied that I should be looking for the ID in your example, by saying:

> and find this UUID (highlighted in red)

The extensions with errors in their `background.js` are:

- [DuckDuckGo Privacy Essentials](https://addons.mozilla.org/en-US/firefox/addon/duckduckgo-for-firefox/)
- [DynamicHistory](https://addons.mozilla.org/en-US/firefox/addon/dynamichistory/)
- [Tridactyl](https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/)

I tried disabling all three of them, and then I closed and reopened Firefox, and there was no change. I then disabled _all_ of my addons, uninstalled and reinstalled STG, and still, no change.

**Comment by terminalmage** [comment]
Any update?

**Comment by terminalmage** [comment]
Closing because of lack of support, and also because I've stopped using STG.
