### ISSUE TITLE
"New Tab" created when creating new window

### ISSUE THREAD

**Issue by deStMathieu** [Drive4ik/simple-tab-groups#712]
**Describe the bug**
Whenever you pull a tab out from a window, firefox creates the new window as expected. But at the same time, a new tab is created and focused on in the new window.
Creating a separate window features the same problem, two New Tab's appear instead of only one. This could be linked to the fact that every new window also creates a new tab group.

**To Reproduce**
1. Have multiple tabs opened
2. Drag and drop a tab to an empty space in the desktop
3. Observe the focused "New Tab" tab side by side with your original tab

**Expected behavior**
No New Tab tab should be opened.

**Desktop (please complete the following information):**
 - OS and version: Windows 10 64b
 - Firefox version: 83.0b8
 - Simple Tab Groups version: v4.5.5.1

**Additional context**
This issue was not present before the latest hotfix update ( in v4.5.5)

**Comment by Drive4ik** [comment]
Thanks, bug was fixed
