### ISSUE TITLE
Simple Tab installed but disappered?

### ISSUE THREAD

**Issue by Ramzh** [Drive4ik/simple-tab-groups#713]
Cannot manage tabs or change groups

Simple Tab disappeared from the toolbar and says it's uninstalled when clearly installed (Firefox says remove). I do not have a backup of the tabs. What to do? 

![image](https://user-images.githubusercontent.com/20802073/98317327-2e955b00-1fd4-11eb-9feb-f35a1ff80bf2.png)

![image](https://user-images.githubusercontent.com/20802073/98317299-250bf300-1fd4-11eb-80d5-9910ba55d86b.png)

![image](https://user-images.githubusercontent.com/20802073/98317280-1de4e500-1fd4-11eb-80da-86b23665dea4.png)

**Comment by Ramzh** [comment]
Had to restart the PC and automatically reinstalled STG but then said to remove Private Mode permission.

Lost few tabs...

**Comment by Drive4ik** [comment]
You can find the backup in the FF downloads folder, and restore it in the addon settings.
