### ISSUE TITLE
What does the "extended search" checkbox do?

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#715]
I can't find any post or documentation of what the checkbox next to the search box does.

**Comment by Drive4ik** [comment]
With an advanced search for "good day" it will find tabs that contain in their title or URL
For example such:
"`good day`"
"`good` some `day`"
"`go` ... `od` ... `day`"
"wcw`g`wqcl wnc`o`w`o`v`d` juyh`d`yu`a` `y`"
