### ISSUE TITLE
Moving tabs between groups sometimes fails completely

### ISSUE THREAD

**Issue by kssi** [Drive4ik/simple-tab-groups#717]
Since v4.5.5, I had many instances of STG failing to move tabs from one group to another group, as described in #700. That latter issue might be related.

The bug triggers auto-logging:

[STG-debug-logs.json.zip](https://github.com/Drive4ik/simple-tab-groups/files/5507078/STG-debug-logs.json.zip)

**Comment by Drive4ik** [comment]
I am aware of this bug.  It is already fixed.  The new version of addon 4.6 has already been uploaded to the FF AMO and is being tested.
