### ISSUE TITLE
Links aren't opening correct URL

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#718]
**Describe the bug**
Links don't open to the correct URL when switching groups

1. Set up two groups: Group A and Group B, and set each to open in a particular container (say, C & D)
2. Set up Group B to open all tabs matching a particular xxx.com URL (regex).
3. Open a tab for site yyy.com in Group A, with a link to xxx.com on the page. Open the link.
4. STG switches to Group B, as it should, with the correct container D. However, it does not open the xxx.com link! Instead it opens the login page to yyy.com.

For example, if Group A has a gmail.com page, a link in an email might point to www.trello.com. If trello.com is set by regex to always open in Group B, then clicking the trello.com link from email will result in a switch to Group B, but instead of opening the trello.com link I'm presented with a Gmail login page.

**Expected behavior**
URL links should open to the correct link

**Desktop (please complete the following information):**
 - Windows 7
 - Firefox version: 82.0.2
 - Simple Tab Groups version: 4.5.5.1

**Additional context**
This started happening sometime in the past few weeks, probably with a recent update.

**Comment by Drive4ik** [comment]
You have an option in group B to open tabs in some container, right?

**Comment by mzguy** [comment]
Yes, I have the option to select a container, and change the container too. That container change does work, but the URL is wrong.

**Comment by Drive4ik** [comment]
No, I mean something else. Do you have automatic container change enabled in group 2?
If so, then you need to understand more about how containers work. Each container has its own cookie visibility area. And this means that you are not in google in group 2. And google very often opens links in emails: first, it opens a link to google and it redirects you to the link that you clicked. This is all for link conversion analytics. On the google search page the same thing, only it replaces the link when you just put down the mouse button.

**Comment by mzguy** [comment]
I think it must be something else, for these reasons:

- It didn't happen a few weeks ago, with no change in STG settings.
- It happens with everything, including Github links within emails notifying me of replies to messages, like yours here. It also happens if I simply email myself a link then click on it. There shouldn't be any analytics in those scenarios.
- If I look at Firefox's link URL preview (bottom of screen), I can see these aren't Gmail links, but correct links to other sites.

**Comment by mzguy** [comment]
By the way, if instead of opening a link from Gmail, I right-click and pick the group from "Open link in Group", it works correctly.

**Comment by Drive4ik** [comment]
> It didn't happen a few weeks ago, with no change in STG settings.

I haven't changed the logic of opening tabs for a long time (probably at the beginning of the year). 

You did not answer the question: do you have an assigned container in the group where the tab should be moved? If the parent tab container and the group tab container are 2 different containers, then they have different visibility area. This means that you will not be logged in container 2 if you did it in container 1 on the same url.

Here is an example of how google works:
![aaaaaaaaaa](https://user-images.githubusercontent.com/7843031/99875215-77fdc100-2bf6-11eb-947b-3879d0035905.gif)

**Comment by mzguy** [comment]
Sorry, yes I do have automatic container change enabled in the second group.

I can replicate the example from your screen recording. I also see the Google URL if I right-click and select "copy link location". However, **this does not occur for links in Gmail**. Can you try this from a Gmail account?

If you simply email yourself a link, say from developer.mozilla.org, you'll find the behavior I described.

Again, the issue is not login or cookie visibility. I simply want to be able to open links within Gmail messages in a dedicated group that always opens URLs in dedicated containers (sometimes temporary containers). The rules for moving to group B work fine, but the wrong URL is passed to that container somehow.

If you email yourself (to Gmail) a link to developer.mozilla.org, the browser does not show that link as pointing back to Gmail. You can use the technique shown in your screen recording, or right-click and copy URL. Either way points to developer.mozilla.org. Right-clicking and choosing the option to move to a group works... it opens in developer.mozilla.org. However, left clicking opens in Group B, changes the container, but **opens a Gmail login page**!

**Comment by mzguy** [comment]
... realized that 100% is too strong. It seems certain websites' links cause the issue, Google or not. I'm not sure if this is a bug with STG, or if there is some type of case that isn't being handled. Thought I'd clarify.

**Comment by mzguy** [comment]
Middle-clicking allows the correct URL to open, but left-clicking does not!

**Comment by mzguy** [comment]
Middle-clicking no longer works either. Can you please try testing this from within a Gmail account?

**Comment by Drive4ik** [comment]
can you record a video with this problem on a new clean FF profile? it does not matter what sites you open, as long as the problem repeats. it is also important that you can see the group settings

**Comment by mzguy** [comment]
@Drive4ik 
I'm not finding the time to do this. Starting from a clean Firefox profile is a major hurdle and disruptive for me.

Are you able to try to replicate? I expect it should be easy to replicate given my description in the Nov 25, 2020 post, and the Oct 7, 2021 post.
