### ISSUE TITLE
Change pale icon

### ISSUE THREAD

**Issue by ColdBlood21** [Drive4ik/simple-tab-groups#72]
![fftabs](https://user-images.githubusercontent.com/36098719/35765336-bed01fd4-08c1-11e8-941a-74a6932a875a.png)
As can be seen in the attached image, you should use an icon with colors and/or higher contrast for the initial state. After selecting a tab group from the drop down menu an icon overlay is shown and the problem is gone.

**Comment by Drive4ik** [comment]
Which of these three icons is STG?

can you record this behavior?
http://www.screentogif.com/

**Comment by ColdBlood21** [comment]
It is always this way only when Firefox is started. It does not recognize which tab group is initially active after loading Firefox and so there is no initial group color overlay for the icon. I think the problem is just, that the Windows title bar color may be too close to the default icon color and you could just use different colors or gray values for the 9 squares in the default icon. Video in ZIP:
[ffox start.zip](https://github.com/Drive4ik/simple-tab-groups/files/1707675/ffox.start.zip)

**Comment by Drive4ik** [comment]
Oh..  Now I understand :)
I added option in addon settings to change icon color.
Please wait for update version.
