### ISSUE TITLE
Last viewed tab incorrectly changes groups when another is auto-moved

### ISSUE THREAD

**Issue by mzguy** [Drive4ik/simple-tab-groups#721]
**Describe the bug**
A tab that auto-moves due to matching a regex takes another tab with it temporarily - the last viewed tab.

**To Reproduce**
1. Go to a group with existing tabs that is not a sticky group.
2. Open a tab.
3. Use Ctrl-t to open a new tab. Enter a URL that matches the regex catch of another group.
4. The new tab moves to the group it should move to, but the tab last viewed in the first group is moved as well.
5. Switching back to the first group restores the tab to its correct group.

**Expected behavior**
Only the tab with matching regex should change groups.

**Desktop (please complete the following information):**
 - OS and version: Windows 7
 - Firefox version: 82.0.2
 - Simple Tab Groups version: 4.6

**Additional context**
This problem is new, probably as of today. I expect the bug was introduced in v4.6 of the extension.

**Comment by mzguy** [comment]
One more aspect to this bug. If the original group is Group A, and Group B catches regex for the new tab, then:

The last viewed tab in Group A moves to Group B along with the new tab that gets caught and auto-moved correctly (the bug described).

AND that tab that is incorrectly moved will get moved to any other Group C, D, etc. that I switch to. The only way to get the original tab back to Group A is to switch to Group A. Then it stays there properly.

**Comment by mzguy** [comment]
This also happens under some circumstances without an auto-move. The last viewed tab starts changing to the currently-displayed group.

**Comment by mzguy** [comment]
Another example: using the button search to switch groups causes the last viewed tab from the previous group to change groups as well.

**Comment by EArmour** [comment]
Yes, this problem definitely exists independent of the regex auto-moving, started happening today for me as well. If I switch groups by expanding the group and clicking on a specific tab within, the active tab in the current group appears in the tab bar. However, clicking just on the group name, not a specific tab, will select the last tab in that group and the tab from the previous group doesn't show up.

It does seem that this is primarily a display issue. The misplaced tab just shows up in Firefox's tab bar, but does NOT show up in the new group in STG itself. So if you just switch back to the other group it will still be there in its correct place and not be permanently duplicated in the other group or anything like that.

**Comment by falolaf** [comment]
I do have the same issue as @EArmour. No regex auto-moving in my case either.

**Comment by Drive4ik** [comment]
Yes, my mistake, sorry. Already fixed now I will make a release. Only the FF AMO will probably check it tomorrow.

**Comment by falolaf** [comment]
I am now on 4.6.2 and the issue I encountered is now gone.
