### ISSUE TITLE
Manage groups tab keeps closing itself

### ISSUE THREAD

**Issue by Benguin** [Drive4ik/simple-tab-groups#724]
**Describe the bug**
When manage groups is open in a tab, it will occasionally disappear from the tablist and needs to be reopened.

**To Reproduce**
1. Go to STG preferences
2. Enable "open manage groups in new tab"
3. Open manage groups, pin the tab.
4. Keep that pinned tab open long enough, and it will disappear within a few days. 

**Expected behaviour**
The tab remains open until manually closed.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - FF: 82.0.3
 - Simple Tab Groups version: 4.6.2

**Additional context**
I like to use a pinned manage groups tab as my group-switcher. It feels a lot more like the old FF panorama tab groups, when done that way. 

I'm aware that there is a plugin to add a separate button for managing tab groups, but I prefer to just keep the tab open and pinned.

Please let me know if you need more info.

**Comment by Drive4ik** [comment]
Yes, there is such behavior. Only it is not a bug, but a special FF behavior. I can tell you when it happens - when the addon is updated. The update procedure is as follows: the browser closes all the tabs related to the addon (they may not exist in the new version) and updates the addon. I can't influence it in any way...
