### ISSUE TITLE
STG Pane sometimes freezes

### ISSUE THREAD

**Issue by faurehu** [Drive4ik/simple-tab-groups#728]
The extension interface - the popup that shows when I click the icon - freezes and I have to restart Firefox to have it working again.

I don't know how to reproduce it, but it happens quite often. It happens sometimes when I send a tab to a different group. I think if there's a lingering STG notification in the bottom right corner then the pane is likely to freeze. 

Sometimes, if the pane has frozen it won't even let me change tabs and disrupt browser functions.

STG Version: 3.2.10
Firefox: 83

**Comment by Drive4ik** [comment]
Hi, please update addon to latest version. And it would be even better if you enable auto update for all addons.
