### ISSUE TITLE
Filter does not work on local url

### ISSUE THREAD

**Issue by Arcesilas** [Drive4ik/simple-tab-groups#73]
First of all, thanks a lot for this AddOn!

I really enjoy regex filters to keep my groups ordered. I've just tried to filter local url like  `file:///home/path/to/somewhere/` and it seems to not be working.

Is that a bug, or just an oversight? (or am I doing it wrong?)

**Comment by Drive4ik** [comment]
Hi! 
this urls are not supported anymore in FF extensions

https://developer.mozilla.org/ru/Add-ons/WebExtensions/API/tabs/create
please, read property URL

**Comment by Arcesilas** [comment]
Thanks for your answer!

Improvements the Firefox way...

**Comment by pointlessone** [comment]
@Drive4ik I assume this won't be an issue when #2 will be implemented as hiding/showing tabs does not require opening tabs with privileged URLs. Is that correct?

**Comment by Drive4ik** [comment]
@pointlessone 
Not certainly in that way. Since I will need, for example, to open group with this url in a new window, and this will not work :(

**Comment by grahamperrin** [comment]
<https://bugzilla.mozilla.org/show_bug.cgi?id=1246236#c113> under Mozilla bug _1246236 - Implement local filesystem read/write access._
