### ISSUE TITLE
Feature request: allow right-click move tab to group when camera is in use

### ISSUE THREAD

**Issue by midgleyc** [Drive4ik/simple-tab-groups#730]
**Is your feature request related to a problem? Please describe.**
A tab that controls the camera can't be hidden, but I can still get the effect of right-clicking a group in "Move tab to group" by pinning it, then doing the right-click which adds it to that group and switches to that group, then unpinning it.

**Describe the solution you'd like**
Ideally, moving a tab to a group and switching to that group (with the right-click group functionality) should also work for tabs using the camera. I don't expect tabs the left-click group switch functionality to work with these tabs because they can't be hidden.

**Describe alternatives you've considered**
I can carry on using my workaround (pin, switch, unpin) -- it's not too involved.

**Comment by Drive4ik** [comment]
The point is that it is forbidden by the browser itself. And when you pin a tab, switch a group, and then unpin the tab, it's not hidden all the time...
https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/tabs/hide
