### ISSUE TITLE
Opening STG results in white window

### ISSUE THREAD

**Issue by KopfKrieg** [Drive4ik/simple-tab-groups#736]
**Describe the bug**
Since the update from Firefox 82 to Firefox 83 STG mostly (in about 9 of 10 cases) only shows a white window when opened (see the screenshot below).

**To Reproduce**
1. Install Firefox 83, install STG
2. Create a few groups
3. Try to open STG from the menu
4. Get blinded by a white window

**Expected behavior**
The window should show all my tab groups.

**Screenshots**
![stg](https://user-images.githubusercontent.com/5047813/100471842-67a88300-30db-11eb-8113-6ae3c3ad75fa.jpg)

**Desktop (please complete the following information):**
 - OS and version: Fedora 33
 - Firefox version: 83.0
 - Simple Tab Groups version: 4.7

**Comment by chuma** [comment]
I am also experiencing this issue, Fedora 33, Firefox 83.0-3 (Fedora build) on Wayland, Simple Tab Groups 4.7.

If I can figure out how to expose any pertinent errors that are being thrown or logged by FF I'll post them here.

**Comment by chuma** [comment]
I launched Firefox with `--jsconsole --jsdebugger --wait-for-jsdebugger` in the hopes of capturing some startup errors related to this issue, but to no avail.

However, when the empty pop-up STG window area closes, I see a number of `WebExtension context not found!` errors thrown in the Browser Console, which do reference STG in the stack trace.  Here is an example:

``` 12:02:58.960 WebExtension context not found! ExtensionParent.jsm:1075
    getContextById resource://gre/modules/ExtensionParent.jsm:1075
    recvRemoveListener resource://gre/modules/ExtensionParent.jsm:1054
    recvRemoveListener self-hosted:1167
    _recv resource://gre/modules/ConduitsChild.jsm:78
    receiveMessage resource://gre/modules/ConduitsParent.jsm:371
    (Async: JSActor query)
    _send resource://gre/modules/ConduitsChild.jsm:63
    _send resource://gre/modules/ConduitsChild.jsm:111
    _send self-hosted:1271
    removeListener resource://gre/modules/ExtensionChild.jsm:663
    removeStub resource://gre/modules/Schemas.jsm:2800
    removeEvents moz-extension://64707d2c-9f62-4137-bfa4-005736239319/popup/popup.js:15651
    (Async: EventListener.handleEvent)
    setupListeners moz-extension://64707d2c-9f62-4137-bfa4-005736239319/popup/popup.js:15661
    setupListeners self-hosted:1167
    mounted moz-extension://64707d2c-9f62-4137-bfa4-005736239319/popup/popup.js:15256
    nextTick moz-extension://64707d2c-9f62-4137-bfa4-005736239319/popup/popup.js:2022
    flushCallbacks moz-extension://64707d2c-9f62-4137-bfa4-005736239319/popup/popup.js:1948 ```

The only difference between the 7 errors thrown is the line number at the removeEvents function in popup.js - they all reference `removeListener()` calls to different events in the`browser.tabs` object.

**Comment by chuma** [comment]
OK last comment I promise:
Looks like the bug is due to having WebRender enabled on FF83 on Linux.
Upstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1899331

**Comment by KopfKrieg** [comment]
> Looks like the bug is due to having WebRender enabled on FF83 on Linux.

Yup, can confirm. Disabling WebRender solves the issue, re-enabling WebRender re-introduces it.

Thank you for finding the problem, I wouldn't have been able to do that.

Since the issue affects multiple (all?) extensions of Firefox on Wayland I'm closing the issue.
