### ISSUE TITLE
List the full names of the required permissons in the add-on description

### ISSUE THREAD

**Issue by aleksejrs** [Drive4ik/simple-tab-groups#75]
Firefox says "`Access your data for all websites`", not "`<all_urls>`".  It's hard to find [the page that connects those](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Request_the_right_permissions), and even that page lists the short one as "`<all-urls>`".

**Comment by Drive4ik** [comment]
Hi!
This permission needs only for tab thumbnails in manage groups.

> Creates a data URI encoding an image of the visible area of the currently active tab in the specified window. You must have the <all_urls> permission to use this method.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/captureVisibleTab


https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Request_the_right_permissions#Use_activeTab_rather_than_tabs_and_host_permissions

**Comment by aleksejrs** [comment]
Please add the full name to the description at https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/ , because when Firefox says the add-on needs that permission, your page does not appear to say why, because it uses a different name for it.

**Comment by Drive4ik** [comment]
![screenshot_6](https://user-images.githubusercontent.com/7843031/35984753-bedf084c-0cfd-11e8-85ab-e3a381cb3a40.png)
![screenshot_7](https://user-images.githubusercontent.com/7843031/35984754-bf022034-0cfd-11e8-9609-8bc6d177c093.png)

**Comment by aleksejrs** [comment]
And when Firefox was telling me there is a new version, it said the add-on needs a permission to "`Access your data for all websites`", which I could not connect to "`all_urls`", and it is difficult to find the proof that they are the same.

**Comment by Drive4ik** [comment]
This is on the page that you gave:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Request_the_right_permissions#Use_activeTab_rather_than_tabs_and_host_permissions

![screenshot_8](https://user-images.githubusercontent.com/7843031/35987975-f47054ae-0d05-11e8-9f6a-aab8a21db662.png)

Ok, I added description of this permission.

**Comment by Drive4ik** [comment]
Description of addon was updated

**Comment by aleksejrs** [comment]
Thanks.

**Comment by Drive4ik** [comment]
I don’t know how I hadn’t thought of it before ...
Made optional
Option in the "Create thumbnails for tabs" settings
