### ISSUE TITLE
[Feature Request] Automatically move tabs to group based on address / page title

### ISSUE THREAD

**Issue by 3v1n0** [Drive4ik/simple-tab-groups#754]
I've loads of tabs and depending on the source I open a link I'd like to be them moved to a different group without having me to organize them all.

I would like to have my tabs to be automatically added to a specific group depending on (regex) matching the address or title.

I suppose a STG plugin could allow this, so that each group may have specific rules associated to it, and when a new opened link will match it, it will be added to the group.

This shouldn't be the case when opening a link from a page already in another group.

**Comment by kalkins** [comment]
This is already implemented, at least for addresses. Go in to the settings for the group (click the cog icon either in the popup or the "Manage groups" page, and scroll down to "Regular expressions for catch tabs". There you can enter several regexes to catch tabs based on their address.

If you want to follow the tab when it's moved, check "Show tab after auto-moving it into this group".

I'm not sure what you mean by your last sentence. If you mean that the tab shouldn't be moved if it already exists in the other group, I don't think that is possible. If you mean that there are some groups which tabs should not be moved out of, turn on "Sticky group" in the group settings.

**Comment by 3v1n0** [comment]
Ok, thanks for the info, I didn't notice it into the group options.
It works quite well, even though having also title selection could be nice.

As per the last sentence, the sticky option indeed does something like what I wanted.

So, there are still things to be improved but the basic aspect is there so let me close this for now.
Thanks
