### ISSUE TITLE
add hotkey to open "manage groups" floating menu

### ISSUE THREAD

**Issue by vitaliis** [Drive4ik/simple-tab-groups#755]
It would be quite cool if one can navigate between tabs and groups easily. Plugin's icon gives you this possibility, but to use it you first have to point your mouse exactly there and click it, only then you can navigate using keyboard. Much easier option, in case you use keyboard shortcuts, is just to press the shortcut and start navigating. 

**Describe the solution you'd like**
Possibility to set the keyboard shortcut to open the floating plugin's menu (see picture below). From there you can start typing and search for the tab needed or use the arrows to navigate to the necessary group.
![image](https://user-images.githubusercontent.com/1839541/102279757-3b3e9480-3f2c-11eb-87b7-39c54ef36383.png)
Having a keyboard shortcut opening this menu would be great!

**Describe alternatives you've considered**
One could set the shortcut for "Open manage groups". Although it works well, it has couple of shortcomings:
* it doesn't allow you to navigate between groups using arrow keys (in the floating menu you can)
* it opens a new browser tab, which is not necessary in the case with the floating menu

**Comment by KerfuffleV2** [comment]
@vitaliis This is a very late reply I wanted to do the same thing and it's actually possible:

1. Go to addon configuration ( `about:addons` )
2. Click the gear near the top right
3. Select "Manage extension shortcuts"
4. In the "Simple Tab Groups" section you can assign a shortcut to "Open popup"

One nice thing about shortcuts assigned with this interface is that they apply to all pages, even special pages like addon download/configuration.

**Comment by vitaliis** [comment]
@KerfuffleV2 no problem. Thank you very much for the response! 

That actually solves the issue for me.
