### ISSUE TITLE
Use tab's container name as criteria in group regex

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#76]
It would be nice to be able to use the name of the container of a tab as a criteria in regex to move it to a given group.
This could be used together with addons such as Containerise which has regex to open a given url in a given container. 
This would allow to merge both groups and containers paradigms for those who want to, in an easy way (of course, there is a workaround today: the same rules can be implemented manually in Containerise and Simple Tab Groups, but that's double work :) )
Thanks

**Comment by Drive4ik** [comment]
Hi!
This is a great idea!
Please, update addon to latest version, its has this feature.

Thanks for the idea!

**Comment by klint** [comment]
Thanks! :)
I have updated to the last version, but I can't get it working although I created a few groups and checked a few containers in those boxes' settings...

**Comment by Drive4ik** [comment]
![catch-ff-containers](https://user-images.githubusercontent.com/7843031/36025240-09631168-0d9b-11e8-952d-9dd0815fa664.gif)

**Comment by klint** [comment]
That's what, I did but I don't think the event is caught as no message pops-up and no tab is added to the group. And I think I have deactivated all other addons dealing with containers.
What I do:
- open a new tab in a container by longclicking the New Tab + button (the container is linked to a group)
- type in a URL in the Location bar, and press enter

**Comment by Drive4ik** [comment]
At the moment when you create a tab, what kind of group is active?

**Comment by klint** [comment]
None, actually. I'm not in the context of a group at that time.
And yes, if I place myself in the context of a group, then it works as you describe

**Comment by Drive4ik** [comment]
Yes, I did it so it worked.
Because if you want to create a new on-line without a group, then all the tabs should belong only to this window, since it is without a group, then the tabs are not tracked. This behavior avoids them from problems when you do not want any rules to work in this window (without group)

**Comment by klint** [comment]
Thanks for the clarification. Works fine now :)
