### ISSUE TITLE
ability to modify font size in popup

### ISSUE THREAD

**Issue by seansweda** [Drive4ik/simple-tab-groups#762]
**Is your feature request related to a problem? Please describe.**
The text in the popup search box is almost too small to read and I'd be happier with larger text for the dropdown list of groups as well.

**Describe the solution you'd like**
Ideally there would be a preference but I understand this may be something that can only be changed via css, so at least some instructions on what to add to userChrome.css to adjust the popup font size.

**Describe alternatives you've considered**
I tried searching github issues ("font", "popup", etc.) and did not find anything relevant to fixing this.  I did learn about the "use full popup width" option which was nice, but doesn't increase the font size.

**Additional context**
Here's what it looks like for me:
<img width="454" alt="Screen Shot 2021-01-05 at 1 14 51 PM" src="https://user-images.githubusercontent.com/1534273/103683644-74c95500-4f58-11eb-9b64-06cb3be6c66c.png">

for comparison, here's another popup:
<img width="443" alt="Screen Shot 2021-01-05 at 1 20 44 PM" src="https://user-images.githubusercontent.com/1534273/103683948-d689bf00-4f58-11eb-8531-99bbaef8ead7.png">

**Comment by 70599** [comment]
Same here.

@Drive4ik Please consider to increase the font size to `1em` or add settings to modify it.

**Comment by Drive4ik** [comment]
I agree, it should have been done a long time ago.

![изображение](https://user-images.githubusercontent.com/7843031/141008490-4650a544-bdda-49da-9a86-61c14724ef95.png)
