### ISSUE TITLE
Shortcuts using Ctrl+Shift+Alt+Letter no longer work

### ISSUE THREAD

**Issue by obvionaoe** [Drive4ik/simple-tab-groups#765]
**Describe the bug**
I used to have shortcuts to load custom groups using Ctrl+Shift+Alt + a letter but as of Firefox84 those no longer work.

**To Reproduce**
1. Go to `about:addons`
2. Click on gear button
3. Select Manage Extension SHortcuts
4. Scroll down to Simple Tab Groups
5. Try to add a Shortcut that incorporates Ctrl, Shift and Alt together
6. See error

**Expected behavior**
The shortcuts should work

**Desktop (please complete the following information):**
 - OS and version: Manjaro Linux 20.2.1
 - Firefox version: 84.0.1 (64-bit)
 - Simple Tab Groups version: 4.7

**Additional context**
Prior to Firefox 84 the shortcuts were very unreliable, they only worked sometimes

**Comment by grahamperrin** [comment]
In Firefox `86.0` you should find that (at least) <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>Q</kbd> is usable *however* I should **not** recommend any shortcut that includes <kbd>Q</kbd>. Consider the future possibility of future shortcuts being reserved (by Mozilla) for quit-_like_ functionality. 

> error

If you mean something like this (a screenshot from Firefox `86.0`): 

![image](https://user-images.githubusercontent.com/192271/109426667-bae5e680-79e6-11eb-95e7-f52dc4b6627f.png)

– it's not an error. 

Many <kbd>Control</kbd>-<kbd>Shift</kbd>- combinations are reserved by Firefox (this is beyond the control of any extension) so as a rule of thumb, it might be good to avoid this key combination as a basis for any _user-defined_ shortcut. 

----

There's direction, from Firefox, to include <kbd>Control</kbd> or <kbd>Alt</kbd>: 

![image](https://user-images.githubusercontent.com/192271/109426758-262fb880-79e7-11eb-8e9e-e77b028b1dd6.png)

– and those two modifier keys can be combined.
