### ISSUE TITLE
Reproducible Loss of All Group Tabs when using Private windows

### ISSUE THREAD

**Issue by arbitar** [Drive4ik/simple-tab-groups#767]
**Describe the bug**
I often lose the contents of all tab groups following certain interactions with private/incognito windows.

**To reproduce**
I reliably lose all my tabs in all my tab groups if the following sequence ever occurs:

1. Have non-private/incognito windows with tab groups containing any number of saved tabs in them
2. Open a private/incognito window
3. Close the non-private/incognito window(s) leaving only the private/incognito window

At this point, my tab groups are immediately lost. The only way to restore them is to promptly open the bookmarks library and restore each group into itself that may, hopefully, have been retained recently within the STG bookmarks directory (if enabled). This can be quite inconvenient if you have many tab groups, and in circumstances I'm still unsure of, they seem to eventually be overwritten with the blank groups?

**Expected behavior**
No loss of data.

Either my tab groups should be retained as the non-private/incognito window is closed, or perhaps the non-private/incognito window can be prevented from closing in this context?

**Desktop:**
- OS and version: Windows 10 (10.0.19041.746)
- Firefox version: 84.0.2 (64-bit)
- Simple Tab Groups version: 4.7 (November 23, 2020)
- It is not permitted to run in private windows, as there are clear indications that the extension does not work in such cases... though I've tried allowing it nonetheless to see if it would help at all. No luck!

**Additional Notes**
This may be related in nature to #716 ?

I understand there may be no good mechanisms for STG to interact with private/incognito windows, but is there a chance that some kind of pre-loss-of-data recovery action could be initiated prior to entering this state, such as immediately re-opening a non-private/incognito window to continue hosting the hidden tabs? Or perhaps a special automatic STG bookmark folder loading when a tab group that apparently consists of 0 tabs is initialized?

I have been trying to be careful to prevent using private windows to trigger this, but I have developed usage habits over years of doing quick out-of-session actions in private instances. I know I should use containers for this instead, but the muscle memory is strong. I end up losing all my tab groups every week or so 😱 

Despite this, I absolutely adore and rely upon the functionality this extension provides. Thank you so much for your development efforts!

**Comment by grahamperrin** [comment]
> … The only way to restore …

There's another way. Use the **History** menu: 

![image](https://user-images.githubusercontent.com/192271/108611707-fece5f80-73d8-11eb-82fa-5c82269c7887.png)
