### ISSUE TITLE
Combatible with IceCat

### ISSUE THREAD

**Issue by NinjaTycoon** [Drive4ik/simple-tab-groups#768]
**Is your feature request related to a problem? Please describe.**
Love your plug-in!  Would like to use it in IceCat, which is a GNU rebuild of FireFox primarily for Linux.  

I cloned and built your plug-in.  However, when I try to install the prod zip, I get the error that it could not be installed because it is not compatible with IceCat 60.5.1.  

**Describe the solution you'd like**
Either a build option for IceCat, or documentation on how to make it compatible.  I have never developed a browser extension, so do not know if this is simple configuration or if it is an issue with the browser API.  

**Describe alternatives you've considered**
Perhaps add to proposed list
https://directory.fsf.org/wiki/Free_Software_Directory:IceCat_WebExtensions_(proposed)/Add-on_list

**Additional context**
I do develop with Node.  

IceCat links:
https://www.gnu.org/software/gnuzilla/
https://directory.fsf.org/wiki/Gnuzilla

**Comment by Drive4ik** [comment]
A fix will be released in STG 5.5+
