### ISSUE TITLE
Please add keyboard shortcut to toggle sidebar with STG

### ISSUE THREAD

**Issue by ygrek** [Drive4ik/simple-tab-groups#769]
**Is your feature request related to a problem? Please describe.**
Sidebar has two shortcuts - Ctrl+B which toggles bookmarks and Ctrl+H which opens history. There seems to be no way to open sidebar and have STG opened without using mouse.

**Describe the solution you'd like**
It seems that extension should be able to assign keyboard shortcut for that.

**Describe alternatives you've considered**
Cursory search didn't find any.

**Comment by DatsDaBeat** [comment]
You can assign a keyboard shortcut for that from the "Manage extension shortcuts in Firefox" page

**Comment by ygrek** [comment]
Apparently I am blind. Thanks, it works.
