### ISSUE TITLE
Only Last Active Tab Group Showing via Firefox Sync

### ISSUE THREAD

**Issue by chrisbrinkworth** [Drive4ik/simple-tab-groups#77]
I have six tab groups on Firefox Mac 58.0.1. I noticed that only the tabs I had up in last active tab group were available on Firefox iOS 10.6 (8836), not the other five groups.

FWIW, I remember the old tab groups add-on permitting sync to show all tabs on other devices under "Synced Devices". I was expecting the same here.

**Comment by Drive4ik** [comment]
Hi! 
Now there is no such possibility.
Synchronization between multiple devices will be implemented in future versions.

**Comment by chrisbrinkworth** [comment]
Ok great, thanks!

**Comment by chrisbrinkworth** [comment]
Sorry for the delay. 

I just tested from an iMac running FF 61.0.1 and the latest STG. I brought up each tab group first, then I did an explicit FF sync. Then I checked FF iOS 12.1 (10941) and all of the tabs from all tab groups appeared to be there (i.e. proper count).

So, seems to work. Thanks!
