### ISSUE TITLE
Tabs are not restored when restarting firefox

### ISSUE THREAD

**Issue by lukasjuhrich** [Drive4ik/simple-tab-groups#772]
*This might be a feature request*, I am not quite sure whether this is officially supported. But as #766 is worded, the author of that issue expects it as well.

**Describe the bug**
The opened tabs are not restored when I re-open firefox.

**To Reproduce**
0. If None exist, create some tab groups.
1. Open a few tabs in one or multiple of the groups.
2. Press Ctrl-Q
3. Press “close tabs” on the dialogue that warns you that you are about to close multiple tabs.
4. Open firefox.
5. Observe that the tabs group are there, but all groups are empty. Also, the tabs are not listed under „other tabs“ when opening the menu.

**Expected behavior**
The groups should load the opened tabs.

**Desktop (please complete the following information):**
 - OS and version: Arch Linux 
 - Firefox version: Firefox 85.0b9 64bit as installed from [`firefox-developer-edition v85.0b9-1`](https://archlinux.org/packages/community/x86_64/firefox-developer-edition/)
 - Simple Tab Groups version: 4.7

**Comment by tardigradus** [comment]
I have the same problem, but only with a second Firefox profile.  With the first, default, profile the tabs with in the groups are saved along with the groups.  With the second, new, profile, the groups are saved but are empty on restarting Firefox.
### Configuration
- OS: Debian 10
- Firefox: 78.7.0esr
- STG: 4.7

**Comment by ryandeussing** [comment]
New user, same problem. I expect all of my tab groups and the tabs they contain to persist unless I close individual tabs.

If this add-on doesn't support that then I'm misunderstanding the utility. Thank you!

**Comment by grahamperrin** [comment]
> 3. Press “close tabs” on the dialogue that warns you that you are about to close multiple tabs.

Simple Tab Groups is not a session manager. 

If you accept closure of tabs when ending your Firefox session (when quitting Firefox) **without enabling session restoration**, then Firefox will have the ability to reopen what was closed, through its History menu. Firefox session management lacks group capability, so if you closed tabs in that way, the (Simple Tab Groups) group context was lost. 

For tabs to be restored, you should set the required preference in Firefox: 

![image](https://user-images.githubusercontent.com/192271/108592880-13264400-7368-11eb-97e3-9bec14bbbae5.png)

– and Simple Tab Groups will maintain the group context.

**Comment by lukasjuhrich** [comment]
Yep! Yep, that's it. Thank you  so much.

I'm also just realizing that this option is already heavily hinted at in the store description by means of a screenshot.
Since I already was determined to use STG, I just pressed install in the search results page and never saw that screenshot.

Sorry about that.

**Comment by grahamperrin** [comment]
> … I just pressed install …

I suspect, many people do the same – no more than that. 

I wonder whether there's the hint elsewhere. Like, on screen after adding the extension for the first time … there should be, ideally …
