### ISSUE TITLE
Remove dependency on Containers

### ISSUE THREAD

**Issue by bvandergiessen** [Drive4ik/simple-tab-groups#775]
The General page in about:preferences says STG requires the Container (or Container Tabs) functionality, and indeed it's enabled. For those who don't use any of that functionality, the feature takes up a lot of real-estate in context menus etc.

Could the add-on be made to function without Containers?

_Edit_ Forgot to say STG is a fantastic extension, thanks!

**Comment by grahamperrin** [comment]
Containers are a feature of Firefox; you need not install Mozilla's extension.

**Comment by bvandergiessen** [comment]
That's right, I'm not talking about the extension [Firefox Multi-Account Containers](https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/) but about the built-in Container (or Container Tabs) functionality, which can be enabled without the extension. In fact, it is enabled automatically when STG is installed, as is revealed by the Preferences page:
<img width="676" alt="STG requires Container Tabs" src="https://user-images.githubusercontent.com/11797190/108636759-a904c080-7487-11eb-81a4-dd3d7dd817f6.png">

When that built-in Container functionality is enabled, it adds clutter to menus and context menus. If you're not using any of it, you might be happier without it. Hence the request.

**Comment by julie777** [comment]
What do you mean by "takes up a lot of real-estate in context menus etc."? I only see one added context menu item.

**Comment by Drive4ik** [comment]
So far it is not possible to do this. The browser does not support this feature.
