### ISSUE TITLE
Compatibility with Tree Style Tab

### ISSUE THREAD

**Issue by haselwarter** [Drive4ik/simple-tab-groups#78]
Hi,

It would be great if STG could save & restore the tree structure of the popular Tree Style Tab extension https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/

**Comment by Drive4ik** [comment]
Hi!
Maybe it will be possible when I add support for tabs hiding.

**Comment by whirm** [comment]
I'd be interested in this feature. 

Is it possible to implement now?

**Comment by Drive4ik** [comment]
@whirm hi, yes.
STG now support messages from other addons. For example Gesturefy. 
This addon has been added to the white list and can perform various actions in the STG.
At the moment such actions are available (not all of them are available in Gesturefy):

- are-you-here
- add-new-group
- delete-current-group
- load-first-group
- load-last-group
- load-next-group
- load-prev-group
- load-custom-group
- open-manage-groups
- move-active-tab-to-group
- move-active-tab-to-custom-group
- get-groups-list

To support them in the addon of the Tree Style Tab, its developer must implement them. I did not talk to him about this topic. If you have a desire, you can create a branch here:
https://github.com/piroor/treestyletab
If he takes up the implementation of this functionality - I will add it to the white list of the addon with the actions that he will need.

**Comment by whirm** [comment]
Thanks!

**Comment by dksher** [comment]
@Drive4ik The actions you listed looks like not related to Tree Style Tab's tree structure. I guess something must be done on STG side about the tree structure?

**Comment by Drive4ik** [comment]
@dksher If the tabs and windows do not close, then the tree view will be saved, since the tabs are simply hidden without other changes.
