### ISSUE TITLE
touch problem

### ISSUE THREAD

**Issue by noo-body** [Drive4ik/simple-tab-groups#780]
**Describe the bug**
touch, cannot open tab list of group
long touch, group list is closed, and somethings of firefox are no response a short time

**To Reproduce**
simple tab groups is added to toolbar

problem 1:
1. touch on simple tab groups icon
2. group list is opened
3. touch on part which will show tabs list of group
4. group list is closed

problem 2:
1. touch on simple tab groups icon
2. group list is opened
3. long touch on group list
4. group list is closed
5. no response when touch on any toolbar item, also page cannot be scroll
6. after a short time, 'no response' is gone

**Expected behavior**
1:
tab list of group will be shown

2:
open context menu

**Desktop (please complete the following information):**
 - OS and version: Windows 10 20H2
 - Firefox version: 86
 - Simple Tab Groups version: 4.7

**Additional context**
before update to firefox 86 there is no problem
if using mouse, there is no problem also

**Comment by nekohayo** [comment]
Since the STG 4.7 release was made in November, nothing changed here, only your Firefox version. Therefore, I doubt it's a STG issue, but rather something with Firefox itself, that you should report on https://bugzilla.mozilla.org (and maybe link here afterwards for reference).

I would suggest closing this ticket here.

**Comment by noo-body** [comment]
reported in bugzilla:
https://bugzilla.mozilla.org/show_bug.cgi?id=1695680

**Comment by noo-body** [comment]
according to
https://bugzilla.mozilla.org/show_bug.cgi?id=1696786#c17

problem is solved
