### ISSUE TITLE
Moving the last tab in a group does not immediately occur

### ISSUE THREAD

**Issue by 0-SamboNZ-0** [Drive4ik/simple-tab-groups#782]
**Describe the bug**
When you move the last tab in a group to another group, the tab is not immediately moved.
You must swap to the target destination group before the tab will actually be moved.

**To Reproduce**
1. Create a new tab group or switch to an empty tab group
2. Open Google.com in a single tab in that group
3. Ensure no other tabs are open in the current group
4. Right click the tab title and select 'Move tab to group'
5. Select another target tab group to move the tab to
6. Observe that the tab does not move
7. Switch to the target tab group
8. Observe the tab has moved and that the original tab group is now empty / contains only a blank tab

**Expected behavior**
Expected behaviour is the same as what normally happens when you move a tab to another group; it is moved immediately.
Additionally, since the tab being moved is the last tab in the group, it is expected that the moved tab is replaced with a blank tab.

**Desktop (please complete the following information):**
 - Windows 10 Pro x64 v2004 (Build 19041.804)
 - Firefox v85.0.2 (64-bit)
 - Simple Tab Groups v4.7

**Comment by grahamperrin** [comment]
Not reproducible with pre-release Firefox `86.0` on FreeBSD `14.0-CURRENT` with the sidebar of Simple Tab Groups `4.7`: 

https://user-images.githubusercontent.com/192271/109158848-ce394d80-776b-11eb-8472-e08ae5daa424.mp4

> 4. Right click the tab title and select 'Move tab to group'

Similarly, not reproducible when using the context menu for tabs presented by Tree Style Tab `3.7.2`.

**Comment by 0-SamboNZ-0** [comment]
I tested again on a different Win10 PC with a pristine install of Firefox and was able to reproduce again:

https://user-images.githubusercontent.com/44484110/109240507-77e80f80-783c-11eb-921a-47b6c6601ee7.mp4

**Comment by grahamperrin** [comment]
Thanks for the recording. Where you use the tab presented by Firefox, I used the tab presented by the sidebar of Simple Tab Groups. 

I tested with a relatively clean profile with Simple Tab Groups alone enabled. 

With the sidebar of Simple Tab Groups visible before performing the move, I see that **the move does occur immediately**, however …

>> it is expected that the moved tab is replaced with a blank tab. …

That's key point. 

I _do_ get that with my everyday profile (with many extensions). 

In your screen recording above: **no notification** after you perform the move. 

I do get a notification, inviting me to switch to the group, and clicking the invitation does switch. 

> … pristine install of Firefox …

Are your notifications disabled in Windows?

**Comment by 0-SamboNZ-0** [comment]
I tested with the Simple Tab Groups toolbar dropdown menu with the same results.  I don't know how to activate the STG sidebar...

I think you're partially right re the lack of a blank tab being a factor, however, as you can see by observing the group tab totals in the STG toolbar dropdown; after the tab is 'moved', while it shows in 'Group 2', the current 'view' still shows as 'Group 1', or at least the current view does not appear to immediately reflect the fact that the tab has actually changed groups.

This can be more clearly demonstrated by having another tab pre-populated in Group 2 prior to the move of the last tab from Group 1.  You will observe that while the tab totals in the STG toolbar dropdown shows that the tab has been 'moved', but the display will not update to reflect this fact (ie; the other tab in Group 2 will not appear in the current view).

I'm guessing that the way STG works is really a bit of 'smoke and mirrors' in that you are not actually 'changing views' per-say, but rather changing the tabs which are either hidden or shown.  Is that correct?

If so, then perhaps the issue is that when the last tab in a group is moved, because it is not being replaced by a new blank tab, there is nothing to display, so the default behaviour is to continue to display the last tab.  Maybe it's impossible to hide the last tab leaving no tabs?

But I'm pretty much speculating here so please ignore me if I'm way off track :)

Windows notifications are enabled in my second test machine (it's a very bog-standard Windows install with minimal modifications).  Strangely, while the STG 'tab move' notification option is enable on my second test PC, they don't appear.  However, STG tab move notifications DO appear on my main PC and clicking to go to the new group works as expected (same result as changing groups manually).  The appearance of tab move notifications has no effect on this issue.

**Comment by grahamperrin** [comment]
> … how to activate the STG sidebar…

The **Sidebars** button: 

![image](https://user-images.githubusercontent.com/192271/109371051-f07db900-789a-11eb-9e50-b84f31883253.png)

**Comment by 0-SamboNZ-0** [comment]
Ah yes, I see it now.

No change in behaviour using the STG sidebar however.

**Comment by grahamperrin** [comment]
Thanks. 

Do you see the move occur immediately in the sidebar? 

(The change of number from 1 to 0 for the group that is viewed before the move.)

**Comment by 0-SamboNZ-0** [comment]
Yes; same behaviour as viewed in the STG toolbar dropdown.

**Comment by grahamperrin** [comment]
Some overlap with #756 I think.

**Comment by 0-SamboNZ-0** [comment]
I would expect (& want) the view to remain in the original group rather than changing to the destination group, but I can see how an option to change this behaviour could be useful.

**Comment by 0-SamboNZ-0** [comment]
Resolved in a recent update (not sure which sorry).  Thanks!

**Comment by 0-SamboNZ-0** [comment]
Closing.
