### ISSUE TITLE
Closing a group in an unfocused window will clear all unloaded tabs

### ISSUE THREAD

**Issue by ACB1337** [Drive4ik/simple-tab-groups#788]
**Describe the bug**
When closing a tab group that was opened in a separate window and where not all tabs have been reloaded. All tabs that had not been fully loaded will be cleared from the group and replaced with "New Tab"

**To Reproduce**
1. Create at least two groups with two tabs each
2. Open both groups in separate windows
3. While having window of group A selected close window of group B
4. Reopen group B but do not select the second unfocused tab
5. Again close window of group B while having window of group A focused
6. Reopening group B will result in losing the second unfocused tab

**Expected behavior**
Completely restore group B

**Screenshots**
https://streamable.com/spqopl

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Firefox version: 86.0 64bit
 - Simple Tab Groups version: 4.7

**Additional context**
N.A.

**Comment by ACB1337** [comment]
Actually this happens regardless of whether or not the window of group B is in focus

**Comment by bigTuxer** [comment]
I can confirm the behavior here on my pc.  

* OS: Ubuntu 20.04 
* Firefox: 86.0
* STG: 4.7

**Comment by grahamperrin** [comment]
> 86.0 

Please retry with 86.0.1.

**Comment by ACB1337** [comment]
The bug seems to be fixed with 86.0.1

**Comment by grahamperrin** [comment]
Thanks for confirming. This was probably a duplicate of #779, which I closed after Mozilla's release of Firefox `86.0.1`. 

https://github.com/Drive4ik/simple-tab-groups/issues/779#issuecomment-797840695
