### ISSUE TITLE
Feature request: Save Tab's history after switching groups

### ISSUE THREAD

**Issue by mzelyony** [Drive4ik/simple-tab-groups#79]
This was a nice feature of the old Tab Group I miss here. I don't think missing history is a bug, just unimplemented feature

**Comment by Drive4ik** [comment]
This feature will be when FF will make stable API for hide tabs

**Comment by mzelyony** [comment]
Спасибо, жду с помытой шеей

**Comment by DrTron** [comment]
+1
I'd love to see this again.

**Comment by klint** [comment]
Will this be implemented with the current api in FF 59, or will you wait until the api gets official...(if it doesof course)?
Thanks ☺️

**Comment by csersyadav** [comment]
waiting

**Comment by Drive4ik** [comment]
Done/Готово
STG 3.0 and FF 61
