### ISSUE TITLE
In letter icon style enable to choose backgrond colour

### ISSUE THREAD

**Issue by ludoja** [Drive4ik/simple-tab-groups#793]
At present, it is possible to pick colour of the letters in the letter/character icon style https://bit.ly/30Rogdx (I really appreciate this improvement!). As the font of letters is thin, the colour is hard to recognise https://bit.ly/3vC8SzO.

For better utilisation of the color code, it would help if the picked color would be backround color of the icon (not letter color as at present). 
The alternative would be to pick the color of letters and background separately (as in gmail labels).

**Comment by Drive4ik** [comment]
You can change the color of the text with this button. Sorry, but I probably won't make an extra option for the background color. That would be a clutter of settings.
![изображение](https://user-images.githubusercontent.com/7843031/142921796-8501bc7a-8c58-4941-9485-b3e5b3a1043c.png)
