### ISSUE TITLE
Technical suggestion for a faster search in STG: timeout-based searching

### ISSUE THREAD

**Issue by nekohayo** [Drive4ik/simple-tab-groups#794]
STG's filter-as-you-type search in the sidebar and the popup menu (accessed through F8) works, but it is very slow, especially when you have many hundreds (or thousands) of tabs spread across many groups.

I believe STG's search does "too much work, at the wrong time" (see Federico's timeless [performance optimization presentations/principles](https://people.gnome.org/~federico/#performance-articles) if you're curious about that claim).

They easiest way to make it faster is to make it _not_ search immediately everytime you type a character in the search field, but instead use a timer, what I call a **timeout-based** search activation algorithm, to prevent it from spamming its search engine. So:

1. Use a "timeout" timer, and everytime you type a character, reset the timer to its default value (ex: 500 ms).
2. When the user stops typing and the timer reaches 0, _then_ trigger the search.

My recommended timeout delay is 500 miliseconds (this might seem like a long time, but it's not really). Anything faster than a 250ms delay will hammer the search engine and cause exponential performance problems, and from my experience and calculations, I believe 500ms is a great middleground that:
* caters both to fast and slow typists (not everyone touch-types at 60-100 words per minute)
* still is not really noticeable for the human eye/brain (and in any case it's still faster than the current no-timer approach that lags the same amount of time due to the search engine not being able to keep up).

See https://github.com/getting-things-gnome/gtg/commit/510a7a49bb12 for an example of how I've had it implemented in the software project I manage. In that desktop application, the difference was "night and day", it was the difference between a search taking 17+ seconds and the same search taking 3 seconds "including typing time" (so less than a second for the actual search).

**Comment by jtagcat** [comment]
Related: #795 (while searching, show a search result with only group names)

**Comment by Drive4ik** [comment]
done. But it works only if tabs more then 500+

**Comment by nekohayo** [comment]
Thank you @Drive4ik, I will be really looking forward to seeing those improvements in the next release! ^_^

Personally I would have recommended the timeout approach to apply even if there are less than 500 tabs (especially for older machines; I'm running Core i5/i7 and Xeon CPUs from 2008-2011, which may be a little bit less snappy than 2019+ CPUs...), either by setting the minimum to 200 tabs instead of 500, or using a faster timeout (like 250ms) when you have less than 500 tabs only (I do think 500ms+ is great for when you have more than 500 tabs). Because I'm suspecting that immediately searching on each and every character when the user is still actively typing might be CPU-heavy/energy-intensive even at 200-499 tabs. Just my 2¢ in case it helps.

**Comment by Drive4ik** [comment]
The interval remained 500 ms, but reduced the number of tabs to 200

**Comment by nekohayo** [comment]
Just a small note of appreciation, as the new version came through my browser updates today, and I can now finally experience the change: the fixes you did here made a **HUGE** difference. It's super fast and reactive now, searches are instantaneous on my machine for the first time ever. It's super cool. _Thank you, thank you, thank you_ @Drive4ik 🤩
