### ISSUE TITLE
Search: Only group names.

### ISSUE THREAD

**Issue by jtagcat** [Drive4ik/simple-tab-groups#795]
**Is your feature request related to a problem? Please describe.**
I'm trying to locate a group and interact with it.

**Describe the solution you'd like**
An option to search only within group names, not matching if only a tab within the group matches.

**Comment by grahamperrin** [comment]
Take the option after keying the search phrase? 

Food for thought: 

![image](https://user-images.githubusercontent.com/192271/112243637-d474f980-8c45-11eb-894e-19d7309f453d.png)
