### ISSUE TITLE
Lost all tab groups

### ISSUE THREAD

**Issue by gaddman** [Drive4ik/simple-tab-groups#8]
Not sure how it happened, but on re-opening Firefox (v57) all my tab groups were lost. Hasn't happened on another PC where I use this addon, so can't offer any insight on why. Any suggested backup options? Maybe just copy browser-extension-data\simple-tab-groups@drive4ik\storage.js ?

**Comment by Drive4ik** [comment]
@gaddman Hi! I'm very sorry that this happened, I'll try to understand what the problem was.
I will backup the data in future versions, as well as save backups in the Mozilla cloud for synchronization.
Now I'm focused on fixing bugs and improve stability.

**Comment by Drive4ik** [comment]
@gaddman Hi! Can you update to latest version and re-test this issue? This bug should no longer be.

**Comment by gaddman** [comment]
Updated now, but I'm also starting with a fresh Firefox profile after re-installing - so many old extensions I figured it was due a cleanup. So I guess unlikely to come across whatever it was that triggered it last time (it could have been the Tab Session Manager addon that did it).

**Comment by Drive4ik** [comment]
Thank you for clarifying!
