### ISSUE TITLE
Is STG still maintained?

### ISSUE THREAD

**Issue by falolaf** [Drive4ik/simple-tab-groups#800]
Hello,

There have been no commits since end of November and I have not seen any comments from @Drive4ik since then either.

Is STG still maintained?

/Anders

**Comment by nekohayo** [comment]
Well sometimes (often) happens that free/open-source software maintainers get busy (and periods of calm seem to have [happened before](https://github.com/Drive4ik/simple-tab-groups/graphs/code-frequency), here), have other concerns going on in their lives at the moment, or undergo burn-out. I hope @Drive4ik is doing OK and will resurface when they can.

In the meantime I would encourage people reading this who have some free time and coding skills to consider contributing bugfix pull requests to help the maintainer (kind of like a welcome-back gift ;) Y'all could rise to top ranks in the [contributors stats](https://github.com/Drive4ik/simple-tab-groups/graphs/contributors) pretty quickly!

**Comment by nekohayo** [comment]
I will also add: if it can be useful, I am willing to offer my help to occasionally triage/tag and close some tickets in the bug tracker to keep it ordered / simple to look at; @Drive4ik if you would like me to do so, feel free to let me know and give me those specific permissions.

**Comment by grahamperrin** [comment]
https://github.com/Drive4ik/simple-tab-groups/commits/master there were commits in May.

**Comment by falolaf** [comment]
> 
> 
> https://github.com/Drive4ik/simple-tab-groups/commits/master there were commits in May.

That was interesting to see.

**Comment by Drive4ik** [comment]
I'm here, I didn't go anywhere) I needed a break and was busy with other things. I will work on the project if possible or on critical bugs/vulnerabilities/changes
@nekohayo Tried to see how to add a moderator - no such option, only a collaborator.

**Comment by falolaf** [comment]
Really nice to see you around @Drive4ik! And, I do understand that other things in life have higher priority.

**Comment by Drive4ik** [comment]
Release coming soon :)
