### ISSUE TITLE
Very high cpu usage, unsure if its the addon or Firefox itself.

### ISSUE THREAD

**Issue by Phooh** [Drive4ik/simple-tab-groups#801]
**Describe the bug**
I can't tell if its this addon or firefox but ever since I updated to Firefox 87.0 I would get very high cpu usage whenever I change groups a lot. Not even a lot but maybe like a couple of times at the least. It gets to the point where the page won't even load, like its stuck loading but at the same time will start to freeze Firefox. I check my cpu usage and its at 100%

**To Reproduce**
1. Switch from one tab group to another tab group
2. Eventually firefox starts to slow down
3. changing to another tab(not group) will get me at infinite loading while freezing
4. Have to end firefox process in the task manager order to exit it 
5. Restarting seems to fix it and everything seems fine for the first current tab group but once I start switching groups the behavior starts all over again.

**Expected behavior**
No page loads and freezes while loading.

**Desktop (please complete the following information):**
 -Windows 7 64bit
 - Firefox version: 87.0
 - Simple Tab Groups version: 4.7

**Additional context**
Like I mentioned, I'm not sure if its this addon or firefox, I've tried closing enough tabs and still nothing. I haven't really installed any new addons so the only thing I can think of that fits is close to the time this started happening is updating firefox to 87.0 I ask here because its much easier to ask here than those devs.

**Comment by Bradley-Schneider** [comment]
Also experiencing the same issue, higher than expected CPU usage when more than one tab group is loaded. 
It is okay when I start the browser and other groups are unloaded except for my initial group, but loading subsequent groups and switching between them slows down the browser very noticeably.

**System Info**
Windows 10 Enterprise 64-bit
Intel 4770K / 32GB RAM / RTX 2070

Firefox 88.0.1 64-bit
Simple Tab Groups Version 4.7

**Comment by grahamperrin** [comment]
No such problem on FreeBSD 14.0-CURRENT. 

Are symptoms reproducible with Firefox 89.0.2?

**Comment by nekohayo** [comment]
Personally I jumped from Firefox 85 to 89.0.2 and did not experience any noticeable issue, but maybe that's because I'm using the "discard tabs after hide" option that unloads the tabs from the previous group when switching groups; so when they are unloaded, they stop consuming CPU and RAM, which is a lifesaver on many websites (such as YouTube, Reddit, Amazon, etc.) that insist on constantly eating a bit of the CPU for every open tab. Have you tried that?

**Comment by Bradley-Schneider** [comment]
> 
> 
> Personally I jumped from Firefox 85 to 89.0.2 and did not experience any noticeable issue, but maybe that's because I'm using the "discard tabs after hide" option that unloads the tabs from the previous group when switching groups; so when they are unloaded, they stop consuming CPU and RAM, which is a lifesaver on many websites (such as YouTube, Reddit, Amazon, etc.) that insist on constantly eating a bit of the CPU for every open tab. Have you tried that?

Did not realise that was a feature! Will be turning that on immediately, pretty confident that will resolve the issue.

**Comment by grahamperrin** [comment]
Alternatively, try an advanced Firefox preference: 

`gfx.webrender.force-disabled` `true`

It's normally `false`; [The whole web at maximum FPS: How WebRender gets rid of jank - Mozilla Hacks - the Web developer blog](https://hacks.mozilla.org/2017/10/the-whole-web-at-maximum-fps-how-webrender-gets-rid-of-jank/) (2017-10-10)

I'm aware of edge cases where people on non-Windows platforms find trouble with WebRender. Maybe there are edge cases with Windows.
