### ISSUE TITLE
Feature Request: Hotkey for opening Plugin Menu

### ISSUE THREAD

**Issue by cruzzer** [Drive4ik/simple-tab-groups#803]
**Is your feature request related to a problem? Please describe.**
It would be great if the Hotkey menu would allow assigning a hotkey to open the plugin dropdown menu as seen in the print screen.  I thought it was there once, as I assigned it to a hotkey (F8) which still works. Or does F8 happen to be the default?

![stg_open](https://user-images.githubusercontent.com/2527732/114367845-2641dd00-9b7d-11eb-914d-6fdda468a1b6.png)

**Describe the solution you'd like**

Add an option here to open the group drop down showing available groups in a list.

![hotkey](https://user-images.githubusercontent.com/2527732/114369932-32c73500-9b7f-11eb-954e-d7402efe62f2.png)

**Describe alternatives you've considered**
 An alternative is to open "manage groups", but I would prefer to have both options. Sometimes I only wish to open the small drop down for minor group management. I do not always need the big view.

P.s. Thank you for your time and effort on this great plugin 👍

**Comment by nekohayo** [comment]
Hi, F8 is the default hotkey, which is what I use too. It seems you have found the fact that you can change that hotkey. I don't understand what is missing?

**Comment by cruzzer** [comment]
Right. Since you've confirmed that F8 is the default to open the drop-down menu, my use own case is fulfilled. 

It might be nice to change the F8 assignment for other users that might wish to use a different key.

Thank you either way :)
