### ISSUE TITLE
Multi-Window Functionality Issues

### ISSUE THREAD

**Issue by dwillis77** [Drive4ik/simple-tab-groups#808]
**Describe the bug**
Multi-window functionality does not always seem to work correctly.

**To Reproduce**
1. Open one FF window, use STG extension to load a group.
2. Open another FF window, use STG to load a different group.
3. From the 2nd FF window, use STG extension dialog to click on the group that was loaded in the first window. The window flashes for a second, and the 1st FF window actually does gain focus, but only in the background - the window that was primary prior to the switch (the 2nd FF window in this example) remains at the forefront (without focus). We can confirm this via an alt-tab which shows the 1st FF window as the "current"/focused window even though its still in the background on the screen.

**Expected behavior**
The first FF window, with the first group loaded, should gain focus and be brought to the forefront.

**Desktop (please complete the following information):**
 - OS and version: Windows 10 LTSC 2019
 - Firefox version: 88
 - Simple Tab Groups version: 4.7

**Additional context**
This functionality appears to work sometimes - I have seen it work before on the same machine on which it is now failing. Unfortunately I haven't been able to nail down exactly what _will_ make it work, but it is easy to reproduce it _not_ working.

**Comment by grahamperrin** [comment]
Maybe a duplicate of #774

If so, please close this issue. Thank you.

**Comment by dwillis77** [comment]
Indeed it does appear that way, I will close this one. Sorry about that.
