### ISSUE TITLE
Tab Group Associations Lost when FF is Restarted with Bookmarks Library Window Open

### ISSUE THREAD

**Issue by dwillis77** [Drive4ik/simple-tab-groups#810]
**Describe the bug**
Tab group associations are lost when the last FF window is closed, and a new window subsequently reopened, while the Bookmarks Library window remains open.

**To Reproduce**

1. Open FF, create a STG group and add some tabs to it
2. Open the Bookmarks Library window
3. Close FF while leaving the Bookmarks Library window open
4. Reopen FF - the tabs that were previously added to the group that was active in last FF window that was previously closed, are no longer in that group - instead, they are ungrouped now (along w/ any other ungrouped tabs that previously existed).

**Expected behavior**
Tabs should stay in their groups.

**Desktop (please complete the following information):**
 - OS version: Windows 10 Pro v20H2
 - Firefox version: 88
 - Simple Tab Groups version: 4.7

**Additional context**
This only happens when closing the _last_ FF window - it does not occur if closing one FF window but still  having others open. Also, if the Bookmarks Library window is closed after closing the last FF window and prior to reopening a new FF window, then the tabs remain in their group properly.

**Comment by dwillis77** [comment]
I am wondering if this is due to the same root cause as [this issue](https://github.com/Drive4ik/simple-tab-groups/issues/716) . Although that is noted to happen _anytime_ the last FF window is closed (regardless of other circumstances) on Mac and Linux, where the FF process(es) apparently stay running after closing, it seems that leaving the Bookmarks Library window open would result in the same behavior on Windows (FF processes still running), thus potentially causing the same problem...

**Comment by Drive4ik** [comment]
Should be fixed in version 4.7.1+
