### ISSUE TITLE
Tabs for local files become "New Tab" when main window closed

### ISSUE THREAD

**Issue by arganoid** [Drive4ik/simple-tab-groups#811]
This is the same as the old bug regarding reader view tabs, except it relates to tabs which show local HTML files.

Steps:

- Open a local HTML file
- Open a new window
- Close the original window. STG will perform some kind of reloading.
- Tabs which previously showed local HTML files are now New Tab.

**Comment by Drive4ik** [comment]
Browser doesn't allow it, it's not safe

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create
![изображение](https://user-images.githubusercontent.com/7843031/142663395-3d512711-530b-41e1-a265-14f6542735a6.png)
