### ISSUE TITLE
Add an option to change the default search engine for each tab group

### ISSUE THREAD

**Issue by obvionaoe** [Drive4ik/simple-tab-groups#812]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to be able to select a search engine to use in a specific tab group. But not restricted to only one group

Example 1: I have a tab group for university stuff and I want to use Google with it, since it has better results for scientific papers and stuff like that., but I'd like to use DuckDuckGo with all of my other tab groups to keep my searches private.

Example 2: I want to use DuckDuckGo in my personal tab group to keep my searches private but I have a group for miscellaneous tabs where I'd like to use Bing and another group for work related tabs where I prefer to use Google. 

**Describe alternatives you've considered**
Using the firefox builtin search keywords but that's kind of cumbersome if I'm using a tab group for a while and every time I search something I have to type '@google' before.

**Additional context**
Not much other than the examples I already provided

**Comment by Drive4ik** [comment]
Unfortunately, browser addons do not support changing the search aggregator. You can only do a search in the addon itself, and it will display the data in the current or new tab. But to do this, you need to open the addon's popup, rather than entering in the search bar of the browser.
