### ISSUE TITLE
Trying to Close (or reject) Opened Tab Groups

### ISSUE THREAD

**Issue by rogergr311049** [Drive4ik/simple-tab-groups#813]
I wonder if there is another way to reject (or close) any Group or Groups.
As far as I understand the only way is to "**Upload the Groups**" and so Firefox will return to its initial status.
In addition, I cannot understand (and cannot force it to work) the utility: "**Discard Group**", since it doesn't eliminate the Group as I thought...

**Comment by Drive4ik** [comment]
You need this
![изображение](https://user-images.githubusercontent.com/7843031/142660189-b17102b6-ab92-4463-b58e-59722c1eb116.png)

"discard" refers to tabs, unloading them from RAM
