### ISSUE TITLE
extension tabs-bar controls menu missing on disable/enable

### ISSUE THREAD

**Issue by CNSKnight** [Drive4ik/simple-tab-groups#814]
The dropdown tabs-bar menu control (right of the tabs-bar "+" control) does not render once simple-tab-groups extension is disabled and then enabled?

I tried closing/reopening browser with no change.

firefox 88.0 Linux

**Comment by Drive4ik** [comment]
If you mean this plugin for STG
https://addons.mozilla.org/firefox/addon/stg-plugin-create-new-tab/
it does not work without STG
