### ISSUE TITLE
keep open tabs in background that has sound

### ISSUE THREAD

**Issue by ZeeD** [Drive4ik/simple-tab-groups#815]
If I select "Reduce RAM consumption on hidden tabs" (sorry if the label is not correct, I see the italian texts) the tabs in other groups are "closed", which is the expected behavior.
I would like to make the plugin automatically "keep open" tabs with music in it.

My use case is that I have a tab group "personal" - linked to firefox container tabs - with, for example, gmail, some personal stuff, and youtube opened.
I also have a "work" tab group, with work stuff. Still, I would like to keep youtube opened and listen to music while using the work tab group.

For now I just disabled the "RAM consumption" flag, but I have "a lot" of tab opened (I normally have 7 tab groups, each with ~10 tabs, and most of them are not html "documents", but more akin to "web applications") and my laptop is... aged...

**Comment by Drive4ik** [comment]
please wait next release
![изображение](https://user-images.githubusercontent.com/7843031/142658614-12028bcd-b1df-4a72-9375-236c88e2e08b.png)
