### ISSUE TITLE
Feature idea: share tab in multiple containers

### ISSUE THREAD

**Issue by JackSlaterIV** [Drive4ik/simple-tab-groups#817]
Hi there,

Sometimes you keep switching between containers and you need one specific tab to follow you (for example a side project, a time managing web app or anything). You just want that tab to be always visible in every container.

So it would be nice to have a way to show the same tab in multiple containers.

Something like: right click on the tab and choose "show/share this tab in all containers".

Maybe it's not easy to implement but it would really help a lot. I hope the dev will have a look at this idea.

**Comment by online-today** [comment]
Firefox offers the possibility to fix a tab on the screen. To do that you rightclick on the tab and choose the menu item. Working with the German version I do not know the exact English text.

**Comment by jtagcat** [comment]
https://support.mozilla.org/en-US/kb/pinned-tabs-keep-favorite-websites-open

**Comment by Drive4ik** [comment]
@JackSlaterIV 
Your query does not apply to STG, but this idea can be implemented in another new extension. Essentially, it would be a right click on the tab and then "open in all containers"

**Comment by JackSlaterIV** [comment]
Thanks, the solution mentioned by online-today works nicely for me.
