### ISSUE TITLE
Do not apply regex/container rules to a tab that was moved manually to another group

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#82]
Context: 
Take a tab which opens in group A due to regex/container automated criteria.
Then move the tab *manually* to group B (via tab context menu or via tab management page).
In this tab (in group B), navigate to a new page (that opens still in the same tab) by clicking on a link in the page.

Current behaviour: automated rules will apply to the target page and the tab will be moved to the appropriate group.

The behaviour I would prefer: as I chose to move the tab manually to group B, I would like it to stay in same group B whatever automated rules apply.

I hope this request makes sense :)
Thanks

**Comment by Drive4ik** [comment]
Hi, I understand that this may seem convenient, but it will be confusing.
In my opinion it is better to make a more accurate selector for capturing tabs.
Also, the behavior remains unclear if the tab changes the url and it matches another rule in the other group.
It will definitely be confusing)

**Comment by klint** [comment]
If you just allow me a last comment, the use case is actually the following: 
I have a lot of rules, mostly container-based, but not only. And that suits 80% of my needs. But sometimes, for a given (and temporary) purpose, I just need to setup a new adhoc group that I want to feed manually with tabs, whatever rule may exist. 
I think this is a legitimate need, don't you think?
I understand the problem of confusion, but maybe you could just add a message the first time a tab is moved manually, or a visual indicator on the tab header/tag? :)

Or maybe the approach of my request should to be different, and there should be a new type of group, a kind of "sticky" group where tabs opened or moved there would stay there whatever rule should apply? A kind of "Vegas" group: what happens in Vegas stays in Vegas... so I heard :P

**Comment by Drive4ik** [comment]
I like your last offer.
I will do this functionality in the next update.
The logic will be this:
you can mark group like as "sticky", and this group has its own rules like the rest of the groups, but the tabs from this group will never automatically move to another group.

**Comment by klint** [comment]
thanks, that will be perfect :)

**Comment by Drive4ik** [comment]
Please, update addon to latest version.

**Comment by klint** [comment]
Thanks a lot, works fine so far :).
