### ISSUE TITLE
Multiple buttons for different groups on the toolbar

### ISSUE THREAD

**Issue by fancyme** [Drive4ik/simple-tab-groups#822]
Hello. Is it possible to make it so that there are several buttons on the browser toolbar, and not one, clicking on which would immediately switch to the desired group, and not select it from the drop-down list of groups?

**Comment by mzguy** [comment]
Suggested workaround: assign a shortcut key to STG search if one isn't assigned already, then type a few letters of the group name and hit enter. Probably faster than moving the mouse up to an icon, and much more flexible. It's also less work as it doesn't require pre-configuration of icons / groups.

**Comment by Drive4ik** [comment]
@fancyme 
https://addons.mozilla.org/firefox/addon/stg-plugin-load-custom-group/

other STG plugins
https://addons.mozilla.org/firefox/user/1017663/

**Comment by mdimura** [comment]
Load custom group plugin allows to add one separate shortcut for a selected group. Is there a way to add a second (third...) shortcut?
