### ISSUE TITLE
Cannot open Simple tabgroups or STG settings in Firefox

### ISSUE THREAD

**Issue by bloodmandarin** [Drive4ik/simple-tab-groups#823]
I cannot open the addon or the addon settings in firefox. 

I presume that it has something to do with JS or Java or sth of the like, because LastPass AddOn and my Gmail login also do not work in Firefox. 

I expect the addons to load. 

![grafik](https://user-images.githubusercontent.com/9247936/121687405-9b208d00-cac2-11eb-8a31-d7307c611c8e.png)

If I create a new profile (with losing all my beautiful TabGroup-Tabs, it works again. 

I, for some reason, also cannot access Firefox Accounts, because it says that Cookies are not activated, yet Cookies are using storage, so I am confused. 

- Windows 10
- Firefox 89
- Simple Tab Groups version: v4.7
- 
If I create a new profile (with losing all my beautiful TabGroup-Tabs), it works again. 

I, for some reason, also cannot access Firefox Accounts, because it says that Cookies are not activated, yet Cookies are using storage, so I am confused.

**Comment by grahamperrin** [comment]
This is probably an issue with Firefox, not the extension. 

Try starting once in safe mode, then start in normal mode.

**Comment by Drive4ik** [comment]
Wan't fix
