### ISSUE TITLE
Context menu items are missing

### ISSUE THREAD

**Issue by bossanovaorca** [Drive4ik/simple-tab-groups#827]
**Describe the bug**
In one of the recent Nightly builds, the "Move to tab group" and "Open link in group" context menu items are no longer appearing

Tab bar context menu

![image](https://user-images.githubusercontent.com/13033321/122581046-43cb7100-d01c-11eb-972b-2045544ce4ad.png)

Link context menu

![image](https://user-images.githubusercontent.com/13033321/122581434-a886cb80-d01c-11eb-829f-159d1c839bde.png)

**To Reproduce**
1. Make sure these settings are enabled
![image](https://user-images.githubusercontent.com/13033321/122581565-cd7b3e80-d01c-11eb-8bd9-5320dd55f1b2.png)

2. Right click on a tab or a link
3. Observe that the "move to tab group" or "Open link in group" items are missing from the menu

**Expected behavior**
The "Move to tab group" and "Open link in group" menu items should be present after right clicking a tab or link

**Desktop (please complete the following information):**
 - OS and version: Windows 10 and macOS Big Sur
 - Firefox version: 91 (nightly)
 - Simple Tab Groups version: 4.7

**Comment by SebastianSimon** [comment]
This is caused by [`browser.extension.getURL`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/extension/getURL) being deprecated. Please use [`browser.runtime.getURL`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/getURL) instead.

**Comment by emyarod** [comment]
it looks like the issue is caused by `browser.menus.ContextTypes` now being undefined (ref https://bugzilla.mozilla.org/show_bug.cgi?id=1717006)
