### ISSUE TITLE
Hotkey for opening Simple Tab Groups

### ISSUE THREAD

**Issue by Daniel451** [Drive4ik/simple-tab-groups#83]
There should be a hotkey (didn't one exist in previous releases?) for opening up Simple Tab Groups so that one can simply "hotkey" and then begin typing to search for a specific tab by name. The hotkey should be customizable preferably.

**Comment by Drive4ik** [comment]
You can open STG popup by F8 key. But you can't change this key - this is FF restriction...
About auto focus, FF has a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1324255), when its fixed in FF - STG will works normaly

**Comment by FatOrangutan** [comment]
>But you can't change this key - this is FF restriction

I believe that's [Bug 1421811](https://bugzilla.mozilla.org/show_bug.cgi?id=1421811), which was recently fixed.

**Comment by Drive4ik** [comment]
I hope so too
