### ISSUE TITLE
Import of old-FF "Tab Groups" extension

### ISSUE THREAD

**Issue by AndrzejSibik** [Drive4ik/simple-tab-groups#831]
Ability of import groups backed-up from old FF (pre-WebExtension, or Waterfox Classic) "Tab Groups" extension would be very welcome.

**Comment by BogudanPro** [comment]
It exist through backups (make backup in old TG and import this backup in STG, there is special button for it). Unfortunately, it loks like breaks addon state (see issue #826).

**Comment by Drive4ik** [comment]
Fixed. Will be available in the next release.
