### ISSUE TITLE
Restore backup...

### ISSUE THREAD

**Issue by cybersrs** [Drive4ik/simple-tab-groups#834]
Loading, please wait...

Just does not restore, "Loading, please wait..." for hours... Already tried to restart the system.

**Comment by matt70tx** [comment]
Have same issue. Been "loading" for hours now.

**Comment by matt70tx** [comment]
I use STG 4.7 and Firefox 90.0.2 (64bit)

**Comment by Drive4ik** [comment]
Try reinstalling the addon:
remove addon -> restart browser -> install addon -> import latest backup which is located in the FF downloads folder

**Comment by victoriastuart** [comment]
I have this issue and attempts to restore backups (per above) results in program activity but as mentioned above"

'Just does not restore, "Loading, please wait..." for hours... Already tried to restart the system.'

I let it run overnight ... never completed.  Perhaps 2500 tabs in perhaps 50-765 groups.

**Comment by victoriastuart** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/834#issuecomment-977985762

2021-11-24 08:20:04 -0800 (PST)

commented 1 hour ago •

I have this issue and attempts to restore backups (per above) results in program activity but as mentioned above"

'Just does not restore, "Loading, please wait..." for hours... Already tried to restart the system.'

I let it run overnight ... never completed. Perhaps 2500 tabs in perhaps 50-765 groups.

Update

I remembered recently installing the "New Tab Override" extension. Disabling that (restarting Firefox, ...) I was then able to reinstall my STG backup within ~1 minute.

==============================================================================
----- Original Message(s): -----
Date: 2021 Nov 24 (Wed) 07:30
