### ISSUE TITLE
Assign special position and hidden for archived groups

### ISSUE THREAD

**Issue by mroutadi** [Drive4ik/simple-tab-groups#839]
I want that archived groups don't appear in the group's menu, I prefer to have a special place to access them and see them all there!

I think we can add a new list item to the menu like create new group button and that refer to the archived groups page (like groups manager page (or still we can use this page and show archived at bottom of page))

The important thing that I think should be considered is that archived isn't shown in the group's list. they make list long but really we archived them and don't need them.

**Comment by jtagcat** [comment]
I archive (and juggle between unarchived) between almost all groups for performance and data reliance.

If you don't need the groups, you might as well delete them.

See also #535 (folders).

**Comment by Drive4ik** [comment]
@mroutadi 
Right mouse click on addon settings popup icon:
![изображение](https://user-images.githubusercontent.com/7843031/129356058-9808bde7-0105-400a-ab47-b91e04af441e.png)

**Comment by mroutadi** [comment]
nice UX ;)
