### ISSUE TITLE
STG dialog is slower to open in Firefox 89

### ISSUE THREAD

**Issue by tobz1000** [Drive4ik/simple-tab-groups#840]
**Describe the bug**
There is more noticeable lag when opening the main dialog than in Fixfox 88 and before. The dialog takes a good 0.5s to open (long enough to be annoying when frequently switching tabs). It also seems to be blocking (i.e. the rest of the UI stops updating), increasing the feeling of sluggishness, whereas before, the main UI seemed to still respond while the dialog was loading.

**To Reproduce**
1. Open the dialog

**Expected behavior**
The dialog is as responsive as in Firefox 87 and before.

**Screenshots**

**Desktop (please complete the following information):**
 - Pop OS 21.04
 - Firefox version: 89.0.2
 - Simple Tab Groups version: 4.7
 - CPU: Ryzen 3600

**Additional context**
I wouldn't be surprised if this is a regression in Firefox rather than this extension :) but I thought I'd raise it anyway.

**Comment by Drive4ik** [comment]
You probably have a lot of tabs in your groups. Try archiving unused groups with a lot of tabs. The popup window loading cannot be accelerated yet.

**Comment by tobz1000** [comment]
> You probably have a lot of tabs in your groups. Try archiving unused groups with a lot of tabs. The popup window loading cannot be accelerated yet.

That's not the issue; it happens even with one tab open.

I've just confirmed that performance is good with STG 4.7 in Firefox v88, and the issue occurs with STG 4.7 in Firefox v90. So this is related to Proton overhaul. But maybe it's still possible to optimise the addon to work better with the new UI?
