### ISSUE TITLE
Can't open the URL into container -> invalid groupId or cookieStoreId

### ISSUE THREAD

**Issue by xeruf** [Drive4ik/simple-tab-groups#844]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/13354331/126754301-52234304-36bd-4d3c-8247-2f9a71ea293f.png">

**To Reproduce**
1. Create a tab group and assign it to open in a container
2. Install an extension that opens a "welcome" tab (such as Invisible Hand)
3. The tab is preceded by the above prompt. Checking the permanent exclusion rule and clicking the confirmation button results in the error.

**Expected behavior**
The tab opens in any container without any prompt, I don't even really care.

**Desktop (please complete the following information):**
 - OS and version: Arch Linux
 - Firefox version: 89.0.2
 - Simple Tab Groups version: 4.5

**Comment by DavidMendes94** [comment]
Great detail with the issue, i have the same issue and for me to continue i clicked on open in personal group and now every time i try to google something it switches me to the personal group
