### ISSUE TITLE
[Accessibility] Icon isn't very visible

### ISSUE THREAD

**Issue by Danielshmaniel** [Drive4ik/simple-tab-groups#845]
**Description:**
I don't think this is a bug per-se, but it's still a concern/problem nonetheless.
I would like for the icon of this add-on to be visible (the icon colour doesn't fit the theme I have on Firefox). How do I change the icon to fit the rest of the theme pls? I am not that savvy when it comes to managing add-ons.

**To Reproduce:**
- Use any dark theme (mine is Dark Alpenglow) on Firefox
- Put the icon in the toolbar

**Here's a sample of my toolbar on Firefox (including this icon I am selecting):**
![Screenshot 2021-07-28 114843](https://user-images.githubusercontent.com/85984021/127302801-ca1f363b-84e6-4429-ba28-b4065c1f0521.png)

**Specs:**
- OS and version: Windows 10
- Firefox version: 90.0.2
- Simple Tab Groups version: 4.7

**Comment by Drive4ik** [comment]
To fully support the other themes, enable the `svg.context-properties.content.enabled` parameter to `true` on the about:config page.

[How to do it?](https://support.mozilla.org/kb/about-config-editor-firefox)
