### ISSUE TITLE
Suddenly my groups were alphabetized...  AND bookmarks duplicated in a ridiculous amount...

### ISSUE THREAD

**Issue by jjneedshelp** [Drive4ik/simple-tab-groups#846]
I LOVE the concept of this, and it can be great to keep my several open webpages organized.  However, I have a few issues so could someone comment?
Today after restarting PC ALL my groups were ALPHABETIZED which I did NOT do, NOR could I ever find a way to do that.  No, this app does NOT auto update.  Is somebody messing with my PC?
Also, my bookmarks are being duplicated.  I put them in Folder A (NOT the Group Tab), if I come back to the tab later it reverts to being BM'd in the STG folder name it's in, then I bookmark it again in the folder I want.  If I leave it alone again for a while, then I go back just to be sure I BM'd it, then it says "remove 2 bookmarks" and on sites I use a lot it said "remove 40 bookmarks" and I'm getting really annoyed because it looks like I'm missing some I know I saved, so it looks like it's running out of room.  I find bookmarks duplicated even when I did NOT BM it.  Maybe that's a separate issue?
I need help figuring this out...  Please...  Thank you...

**Comment by jjneedshelp** [comment]
I don't know what the turn-around for responses are, but if nobody wants to address this then I must come to the conclusion someone is messing with my PC or this extension...

**Comment by Drive4ik** [comment]
Hi. If you're talking about bookmarks in the STG bookmark folder, the extension itself manages those bookmarks. To put it another way, it backs up open tabs to bookmarks. If you move the bookmarks from that folder (default name STG bookmarks) then the addon will not touch or modify them. 
You can do this: go to the addon settings and disable the option:
![изображение](https://user-images.githubusercontent.com/7843031/127927671-71cc837f-129e-411d-9c9f-8dbf4eec3107.png)

After that, the addon will not activate the bookmarks or change the bookmarks in its bookmark folder in any way. It will be possible to make a manual backup to the bookmarks (by right-click):
![изображение](https://user-images.githubusercontent.com/7843031/127927870-0b364dc2-85ac-4f67-9bf8-27b3ab0227e1.png)
