### ISSUE TITLE
Feature request: Use the "squeares and colored triangle" icon every where

### ISSUE THREAD

**Issue by thevladsoft** [Drive4ik/simple-tab-groups#85]
The window icon is very stylized, but the group admin window and group menu uses a plain circle, as it can be seen here:

![example](https://addons.cdn.mozilla.net/user-media/previews/full/193/193159.png?modified=1518038095)

**Comment by Anntoin** [comment]
This would be a nice UI tweak IMO

**Comment by Drive4ik** [comment]
Hi! I see you use very old version of STG. You can update to latest version, it has functional to set group icon from tab icon
![screenshot_2](https://user-images.githubusercontent.com/7843031/36269759-aeb607b0-1282-11e8-9a43-8542fbdecafb.png)

**Comment by thevladsoft** [comment]
I have an updated version. The image that I used is from mozilla addon page (so it's an image you upoladed). I just used it as an example.

Yes, you can change icons, but I should have expressed de request as "Use the "squeares and colored triangle" as the default icon...". The idea is that, if you have many groups, you shouldn't change them all just to make them look cool in the group admin window and group menu. Specially if some of those groups could be short lived.

**Comment by Drive4ik** [comment]
Please, update addon to latest version. Now you manualy change icon style

**Comment by Drive4ik** [comment]
Hi in STG v3.0 and FF 61 you can set default icon for a new groups
