### ISSUE TITLE
Be able to access STG settings from manage groups page

### ISSUE THREAD

**Issue by julie777** [Drive4ik/simple-tab-groups#850]
The context menu for STG on the tab bar has "manage groups" and the gear icon for settings. It is likely that I will think about settings when on the manage groups page.

Add a settings(gear) icon to the title bar on the manage groups page.

**Comment by pixel8mb** [comment]
Yes, please. Very good suggestion julie777, and thanks to creator Drive4ik for very cool STG! Just started and I’m loving it a lot, but frustrated that I can't find settings with overall preferences any more. Maybe I don’t have a main STG page showing? I saw a Settings page when first using STG with lots of preferences for users, decided to wait until later for that. Also used “Manage Groups” page at first, but then that and Settings both disappeared, I couldn’t find any way to access them though I’m usually good at figuring things out. Finally got access to “Manage Groups” from a post here about adding shortcuts on Firefox add-on page, many thanks for that. And I would really like to access overall Settings, this the only post I found mentioning it. Would be nice if there were basic instructions some place, am I missing that, too? Many thanks in advance, for a little help.
