### ISSUE TITLE
Improve the navigation among groups. 

### ISSUE THREAD

**Issue by julie777** [Drive4ik/simple-tab-groups#852]
Ctrl-` is an awkward way to navigate between groups. I need to know where the current group is in the groups list and whether it is faster to ctrl-` or ctrl-shift-`.  Ctrl-tab works in the browser for tabs because tabs are visible and you can see whether ctrl-tab or ctrl-shift-tab will get you there. The browser also supports ctrl-n to go to tab number n which is even better much of the time.

I would like to be able to jump to a specific group with a shortcut key. The number of groups is likely small so a ctrl-n type shortcut would work, assuming I remember the order of the groups.

Even better would be a gmail style shortcut where I type the "goto group" sequence and start typing the group name hitting enter as soon as the one I want is selected.

For reference, the gmail solution lets me type "gl" for goto label, it then provides a drop down menu of all labels. As I continue to type the non matching labels disappear. At any time the top label in the remaining list is selected by hitting <enter>

**Comment by mzguy** [comment]
Suggestion: enable a shortcut for the STG button. There's probably a default already, can't remember. Then, simply start typing. All matching tab titles and groups are filtered. Down arrow / enter as desired to go to the one you want.

**Comment by Drive4ik** [comment]
@julie777 
Made an option to search only for groups:
![изображение](https://user-images.githubusercontent.com/7843031/142651526-ac0f83fd-6a8d-4f56-9d57-576dce9158b5.png)
![изображение](https://user-images.githubusercontent.com/7843031/142651576-573351f1-bd16-415f-b316-fef8760301ec.png)
