### ISSUE TITLE
Add option to automatically delete old backups

### ISSUE THREAD

**Issue by Rexogamer** [Drive4ik/simple-tab-groups#854]
**Is your feature request related to a problem? Please describe.**
My downloads folder is cluttered with old backup files - while I'm happy to have backups, I don't really need the older ones and manually clearing them out is a bit of a pain.

**Describe the solution you'd like**
Add the ability to automatically delete backups before a specific point (eg older than a week).

**Describe alternatives you've considered**
If not automatically, maybe a button in the backup settings to clear them?

**Additional context**
N/A

**Comment by Drive4ik** [comment]
Fix #506 should solve this problem
