### ISSUE TITLE
Workaround for sync with backup on browser exit and import on restart

### ISSUE THREAD

**Issue by llMaxll** [Drive4ik/simple-tab-groups#856]
**Is your feature request related to a problem? Please describe.**
To create a good workaround for syncing between devices (#291), I would like to have a backup every time I stop using the browser. The next time opening it could be on a different system and I want to keep going exactly where I stopped. My only option at the moment would be to make backups very frequently, but that still has a risk of being outdated. This solution (and my solutions below too) result(s) in a cluttered backup folder, so I'd also appreciate #854.

**Describe the solution you'd like**
I would like to have an option to automatically create that backup on close.

**Describe alternatives you've considered**
The context menu has an option for exporting all groups as bookmarks. The same could be useful for creating a backup in general (always navigating to that in the settings is tiresome). That feature could be useful regardless of this concrete problem.

Edit: Having an import last backup on start option and/or an import backup in the context menu would also greatly improve my that Use-Case. Since adding more and more to the context menu could clutter it, it could be made de-/activatable  to have it in that menu.

**Comment by ignRyann** [comment]
Hi, has there been a fix / solution for this?
