### ISSUE TITLE
when searching duckduckgo from the adress bar in a new tab with "always open tabs in container" enabled, the tab duplicates.

### ISSUE THREAD

**Issue by Madac1** [Drive4ik/simple-tab-groups#857]
**Describe the bug**
when searching duckduckgo from the adress bar in a new tab with "always open tabs in container" enabled, the tab duplicates.

**To Reproduce**
1. enable "always open tabs on container" selecting a container from a group config.
2. enable duckduckgo as your search engine.
3. open new tab.
4. search something and press enter. 
5. a duplicate tabs opens along the ddg search tab.

**Expected behavior**
Just a single tab open when searching in duckduckgo

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Windows 10 21H1
 - Firefox version: 91.0.2 (64-bit)
 - Simple Tab Groups version: 4.7

**Comment by Drive4ik** [comment]
I changed the logic a bit, try it in the next addon release

**Comment by benmontour** [comment]
This appears to still be an issue, or the issue has reappeared. Same steps as above to reproduce, though it doesn't matter if it's DuckDuckGo or another search engine. Opening a new tab and typing into the address bar to search and hitting enter will cause a new tab to open in the selected container with the search query. It will also cause a second tab to open which says New Tab until you click on it, and then it opens up to the same search query. See attached shots of what this looks like.
![Screenshot 2023-07-27 at 09 57 38](https://github.com/Drive4ik/simple-tab-groups/assets/8712103/97f72f84-04a3-446d-b45c-9027f873065b)
![Screenshot 2023-07-27 at 09 57 48](https://github.com/Drive4ik/simple-tab-groups/assets/8712103/43778d06-5196-418a-be58-4e4758e0e078)

**Comment by ElSamhaa** [comment]
I can confirm, the issue still exists.
