### ISSUE TITLE
Correcting the index of tabs shown when using shortcut `CTRL+TAB` to switch tabs

### ISSUE THREAD

**Issue by dmiraj** [Drive4ik/simple-tab-groups#858]
**Is your feature request related to a problem? Please describe.**
When using `CTRL+TAB` to switch between tabs. Tabs from other groups are shown in the selection.
When tabs from other groups are selected, it brings that tab to the current group, which is not a desired behaviour.

**Describe the solution you'd like**
To update the index of tabs shown when pressing `CTRL+TAB`, as per the group of tabs selected.

**Describe alternatives you've considered**
The shortcut which permits to switching back and forth is not usable

**Additional context**

**Comment by Drive4ik** [comment]
The addon cannot affect how the browser behaves when switching tabs. I once encountered such a problem in a forum with FF bugs, where hidden tabs were shown when switching tabs. 
All this requires a change in the behavior of the browser itself.
