### ISSUE TITLE
Firefox tabs and toolbar become unresponsive in one window

### ISSUE THREAD

**Issue by zaneselvans** [Drive4ik/simple-tab-groups#859]
I'm running Firefox 91.0.2 on Ubuntu 21.04, with Simple Tab Groups v4.7 and I'm getting a weird behavior where in one window that has a tab group active, the toolbar (including the tabs themselves) become unresponsive, in that the display of the browser's state doesn't change after I've clicked on the interface until after I click outside of that window somewhere (including another Firefox browser window). If I click one of the tabs to select it, nothing happens until I click outside the window, at which point the newly selected tab is displayed. Of course this makes it very hard to change to another tab group in that window.

**Comment by Drive4ik** [comment]
Your browser is freezing. What does the addon have to do with it? Were you using it right before the browser froze?
