### ISSUE TITLE
Reload all tabs

### ISSUE THREAD

**Issue by SladeThe** [Drive4ik/simple-tab-groups#86]
Reload all tabs browser feature does not work for active group tabs. The tab starts to load only after manually clicking on it.

This issue is the reopened #56 which was not fixed, but closed by @Drive4ik.

**Comment by Drive4ik** [comment]
You can disable "Enable fast group switching" and "Reload all tabs" will work normally.
No other way.
Or wait for stable hide tabs API

**Comment by SladeThe** [comment]
Thanks for the info, it works fine now.

Sadly, I have many tabs in some groups and don't want to load them all just after group switch.

**Comment by Drive4ik** [comment]
Please close the issue if you have no more questions
