### ISSUE TITLE
Moving Tabs Issue

### ISSUE THREAD

**Issue by LookingForWayOut** [Drive4ik/simple-tab-groups#860]
Hello. I hope this is the correct place for support.

I am just trying this extension out today and have been trying to figure an issue I not understand.
For example, I have two groups. ABC and XYZ. I moved several tabs from ABC to XYZ. Then I neatly put them in a child parent format as I like. Now, whenever I go to group XYZ and click on one of those tabs, it seems to take me to back to the group it was originally in. I did this a few times and it keeps happening. I make group 123. Move one tab from XYZ into 123. I will go click into ABC. Then go to group 123. When I click that single tab, I get sent back to XYZ.

This happens regardless if Tree Stye Tabs (addon) is enabled or not.

A list of my other active addons are:
Auto Tab Reaper - v1.1
Auto-Sort Bookmarks - v3.4.1
Checker Plus for Gmail - v22.8.1
Copy Tab URLs - v1.3
Disable HTML5 Autoplay - v2018.10.3
Duplicate Tabs Closer - v3.5.3
Form History Control (II) - v2.5.6.1
MySessions - v2021.6.0
Open Tabs Next to Current - v2.0.14
Simple Tab Groups - v4.7
Snap Links - v3.1.10
Tab Count Icon - v0.12.1
Tree Style Tab - v3.8.12
uBlock Origin - v1.37.2

Firefox at a whopping v92, 64b.
Windows 10 Enterprise (once I can maybe sort this addon out, I will test on W10 Home).

Thank you.

**Comment by Drive4ik** [comment]
Try disable addon `Open Tabs Next to Current`
