### ISSUE TITLE
When I close firefox and re-open, all of my tab groups are lost.

### ISSUE THREAD

**Issue by ferguslesley** [Drive4ik/simple-tab-groups#861]
This is a new issue, it didn't happen until recently, but now when i close and re-open firefox, all of my tab groups are gone and I need to reload a backup every time.

**Comment by lsde** [comment]
I second that. Currently, the groups are not persistent across restarts, no matter if I kill Firefox or shut it down gracefully.
What happened?
I'm on STG 4.7, Mozilla Firefox 92.0, Linux x86_64 on Wayland

**Comment by Drive4ik** [comment]
try to fix in 456d0fbafff937380181fb577b89562d664cbf7a
please wait next release

**Comment by machank** [comment]
I cannot find where to input the auto-stg-backup json file.  It's fine that there's a backup and restore offered, but where is the restore button to be found??????

**Comment by machank** [comment]
> I cannot find where to input the auto-stg-backup json file. It's fine that there's a backup and restore offered, but where is the restore button to be found??????

Found it.  But it would be nice if this was more easily located.
