### ISSUE TITLE
Default group title keeps going up even after deleting an old one

### ISSUE THREAD

**Issue by TimestaticYT** [Drive4ik/simple-tab-groups#862]
**Describe the bug**
Number of the new group keeps going up even after i deleted or renamed a group
**To Reproduce**

1. Go to 'simple tab group icon'
2. Click on 'create new group'
3. Click on 'ok'
4. Click on 'create new group'
5. Click on 'ok'
6. Click on 'the group we just created'
7. Click on 'delete icon'
8. Click on 'ok'
9. Click on 'create new group'
10. See higher number of the group in default name than previously

**Expected behavior**
I expect the number of the default group name to go back the first number available after deleting a group

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/58912623/134392412-1c2de81a-0238-4ba2-9840-6e3b34aa1c3d.png)

**Desktop (please complete the following information):**
 - OS and version: Manjaro Gnome
 - Firefox version: 92
 - Simple Tab Groups version: 4.7

**Additional context**

**Comment by Drive4ik** [comment]
it's not a bug, it's designed that way. it's a new group and it should have a new name to avoid conflicts
