### ISSUE TITLE
Any way to assign new Window to group directly?

### ISSUE THREAD

**Issue by rocribera** [Drive4ik/simple-tab-groups#863]
I don't like working with tabs that aren't part of any group, I always have them somewhere, but when opening links from Whatsapp/Telegram/Discord or opening new Windows, I don't get sent to any group (not even the default one). Is there a way to make it so that before loading the site, there's a page showing all the current groups and to select what group this will go to? Kind of like how the extension "Always in Containers" does with Containers?

**Comment by Drive4ik** [comment]
This is not desirable, because STG addon will conflict with this particular addon "Always in Containers". They will sort of fight: who will show their window first, STG - to move to the group, or "Always in Containers" to open in the right container. And the loser will not be able to show his window... Not a good idea

**Comment by rocribera** [comment]
> 
> 
> This is not desirable, because STG addon will conflict with this particular addon "Always in Containers". They will sort of fight: who will show their window first, STG - to move to the group, or "Always in Containers" to open in the right container. And the loser will not be able to show his window... Not a good idea

I'm not saying they should work together. I don't use Always in Containers, but this functionality they have I think could be useful for STG. If you have groups with "always open in Container X" it already has the function of "Always in Containers", so having the option to have STG choose the group before opening a tab that doesn't come from another tab would work out and wouldn't need "Always in Containers" or any other addon
