### ISSUE TITLE
Pinned tabs show up in all groups!

### ISSUE THREAD

**Issue by casablanker** [Drive4ik/simple-tab-groups#866]
Wow, what a deal breaker... I have 1 window with pinned tabs and a few other windows with related material. Great, I love the idea of "groups" and have used a similar tool in the past. However, I just discovered that as soon as I pin a tab, it disappears from the group and, even worse, shows up in all groups! I don't want that! I don't get the logic behind this... so I either give up my pinned tabs so they will stay in a group by themselves or I abandon this extension. 

Pity, it had such potential.

**Comment by nekohayo** [comment]
As a user, I'm actually in favor of the current behavior, it intuitively makes sense to me that pinning a tab makes it universally pinned across groups. I often use pinning to temporarily work with a tab across multiple groups I'm switching between. If I wanted a tab to stay within a group only, I would un-pin it.

Just commenting to point out that the reporter's claim above is not as universal as it is portrayed to be.
