### ISSUE TITLE
Deleting a tab group deletes any Bookmark folder with the same name

### ISSUE THREAD

**Issue by dtryse** [Drive4ik/simple-tab-groups#869]
Deleting a tab group deletes any Bookmark folder with the same name, even if it is not a bookmark folder created by an STG export.

**To Reproduce**
1. STG settings:
1a. check `Allow access to bookmarks`.
1b. set `Default bookmark folder location`: `Bookmarks Menu`.
1c. uncheck `Export groups to STG bookmarks folder`.
2. Create a new STG tab group with the same name as any of your pre-existing bookmark folders.
3. Delete the newly created STG tab group.
4. Your bookmark folder has been deleted.

The same thing happens with renaming - renaming an STG tab group will affect a bookmark folder with the same name.

With the default settings (`Export groups to 'STG bookmarks' folder` checked) it's less serious / unlikely to accidentally delete a user-created bookmark collection.

**Expected behavior**
Bookmarks should never be touched at all, apart from at the time the export is done. An "export" sounds like a once-off action, you wouldn't expect it to maintain a link and continue to be updated (even in the case of a bookmark folder that actually was created by an STG export - see issue #786).

**Desktop (please complete the following information):**
 - OS and version: Windows
 - Firefox version: 93
 - Simple Tab Groups version: 4.7

**Comment by Drive4ik** [comment]
That's the point, it seems like a mistake to you, but it's not. It's done on purpose, a lot of users like the current behavior. Just for other users (the bulk) I made the option "Export groups to 'STG bookmarks' bookmark folder" enabled by default for everyone.

**Comment by dtryse** [comment]
Apologies if the bug report was unclear. The issue is that STG can delete entire bookmark folders that do not belong to it / haven't been created by it. The current behavior causes data loss.

**Comment by Drive4ik** [comment]
As I was writing this post, I came up with a solution to the problem. I'll get right on it.

**Comment by Drive4ik** [comment]
@dtryse done. Please, wait next addon release.

**Comment by dtryse** [comment]
Thanks for the fix!

**Comment by 1sad** [comment]
im sorry for re oppening, but im having the issue
but how do i export groups to bookmarks so this doesnt happen?
i want to export group to bookmarks, and close the group, so the bookmarks are left but group is closed
i dont see why its deleting the groups its defeating the purpose of exporting the group at all?

reason why i want to do it is because i have 5000 tabs combined and my browser barely works, if i export the unused groups to bookmarks, i can close them and it will work again
how do i do this?
