### ISSUE TITLE
No way to update group?

### ISSUE THREAD

**Issue by SladeThe** [Drive4ik/simple-tab-groups#87]
Is there a way to update a group when sync is lost?

I have many tabs that was previously synced with some group. After FF restart the sync was lost (previous version of addon, don't know if this bug was fixed). I have opened some new tabs and closed some old tabs before I realized that fact. Now I want to forcibly update an existing group by my current tabs or create a new group. But new group is created empty, while the selection of previously synced group will override my current tabs.

**Comment by spiralsam** [comment]
I would love to be able to have a general, useful feature like this as well. This is useful broadly, not just when sync is lost for some external unknown reason. The addon called [https://github.com/Drive4ik/simple-tab-groups/issues/87](sync-tab-groups) addresses this in their own way by allowing you to take any open window you have and on-demand either turning the window into a synced group (in the case that the window is not synced or tracked by the addon), or de-syncing the group (in the case that the window was synced and being tracked by the addon). It's under their main menu called "Group Visible" that is simply a checkbox that you toggle on and off.

Is it ok for someone to possibly turn this into a feature request?

As for your problem, I think as of now you only have the option (I'm just a fellow user) to create a new synced window then move them individually one-by-one  to the new group with either 1) drag-drop 2) right-click on the tab and move 3), or possibly with another external addon that will merge two windows together (but you may want to be careful and test that it doesn't conflict somehow with simple-tab-groups and mess things up).

If others have current solution(s) too please feel free to add!

**Comment by Drive4ik** [comment]
@SladeThe you can try this:
![re-sync-group](https://user-images.githubusercontent.com/7843031/36264034-53dac398-1274-11e8-873c-6c039f78894d.gif)

**Comment by SladeThe** [comment]
The main point is that I do not want to add/remove tabs manually one by one. It is simple to add one tab to the group. But what if there is ten tabs or more?

**Comment by Drive4ik** [comment]
Not sync group at start up was fixed in v2.4.2

**Comment by Drive4ik** [comment]
How do you want the group to synchronize?
What will happen with the tabs that are in the group but are not currently open?

**Comment by SladeThe** [comment]
I think there should be an option to add all unassigned tabs to a group. So I can create new empty group instead of old one.

**Comment by Drive4ik** [comment]
You can do it now
![screenshot_1](https://user-images.githubusercontent.com/7843031/36269329-97b5caba-1281-11e8-9250-605e69bfe025.png)

**Comment by SladeThe** [comment]
Whoa-whoa. Not so fast ;)

Thank you. That's exactly what I wanted.
