### ISSUE TITLE
Option to hide archived groups from STG popup

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#870]
When you have a lot of archived groups, the groups list in the STG popup can be quite cluttered by useless information (by default).
An option in the settings or in the popup itself (anyway, an archived group can also be reached via the panorama page) to hide archived groups from the popup, similar to the one in the panorama page would be helpful.
Thanks

**Comment by ravemir** [comment]
I scrambled to find this until I searched Google for it.

Is there any change this setting could also be set (or only, if preferable for maintenance purposes) on the "Settings" menu?

**Comment by icaine** [comment]
@klint you should reopen it, it's super counter-intuitive to have this option hidden (only) behind right click on the cog wheel..

**Comment by ravemir** [comment]
Restored my tabs today after an (unrelated) mistake, only to scratch my head for 5 minutes and finding this thread again.

**Comment by OctopusET** [comment]
I hope this option could be included in settings menu.

**Comment by ravemir** [comment]
At this point, I am bound to have this happen every time I swap to a new laptop or restore tabs.

This should really be more visible, or at least be included with a settings backup, so I don't bump into it the next time it happens.
