### ISSUE TITLE
Feature Reuest: Add option to create new group on new tab opening

### ISSUE THREAD

**Issue by BeatLink** [Drive4ik/simple-tab-groups#873]
**Is your feature request related to a problem? Please describe.**

I miss the tab group functionality in google chrome android. Whenever I opened a new tab, chrome would create a new tab group. 

Logically, this made sense as whenever users opened links from the current tab usually meant the user was continuing that same activity but when users opened a new tab, that almost always meant they would be switching to a new activity or doing something different. 

I wish STG could replicate this behavior to make new tab group creation as seamless and automatic as clicking the new tab button. 

**Describe the solution you'd like**
Add an option in settings to automatically create a new group whenever a new tab is opened.

**Describe alternatives you've considered**
Don't know of any other

**Additional context**

**Comment by rocribera** [comment]
I'd love this. I'd like it so that when I open a link from Whatsapp or some other app to the browser I can choose which group it goes to, instead of having to move it from the group I'm originally in. Something similar to the functionality of the [always-in-container addon](https://github.com/tiansh/always-in-container) would be great imo.

**Comment by Drive4ik** [comment]
Regular expressions will do you all good. In the group settings at the bottom there is a field for entering a regular expression, based on which the Whatsapp tab will be moved to the group in which this regular expression.

**Comment by Drive4ik** [comment]
First, the addon does not know where the tab was opened: from the desktop (shortcut), bookmarks, or just written url address. Secondly, can you imagine how inconvenient it would be for the other many thousands of users to always choose a group for each tab opened from the outside? It's too complicated and it would require an unnecessary action on the part of the user.
