### ISSUE TITLE
Dark mode too hard to find

### ISSUE THREAD

**Issue by shodanx2** [Drive4ik/simple-tab-groups#874]
![image](https://user-images.githubusercontent.com/10621885/139565455-d688fee5-9330-4667-8339-e83e457ff4af.png)

It is simply too hard to find dark mode, and all of the settings in "options"
You have to go to hamburger menu -> addons -> find STG in the list and click on it then the tiny 3 dots menu then option then scroll down.

I was convinced there was no dark mode and I was going to just give up on this plugin

Here is my solution, that "option" menu should be in the context menu here

![image](https://user-images.githubusercontent.com/10621885/139565540-9ae5d4d4-5f48-4c74-adcd-a1563e685a5a.png)
This is where I was looking for it all along.  And many just default dark/light theme with either browser or system default ?

**Comment by Drive4ik** [comment]
![enable dark theme](https://user-images.githubusercontent.com/7843031/140966916-4405f360-72e7-450f-a9d6-1e3ecb2be081.gif)
