### ISSUE TITLE
The "Set this group as main" is not working

### ISSUE THREAD

**Issue by AndRo-Marian** [Drive4ik/simple-tab-groups#875]
**Describe the bug**
I set a ground to Main and currently I am on another group.
I close the Firefox and after relaunch the group is not the main one.
Is the previous session from firefox.

**To Reproduce**

**Expected behavior**
To show the main group on first startup.

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Firefox version: [e.g. 63] 87
 - Simple Tab Groups version: [e.g. 3.0.8] 4.7

**Additional context**

**Comment by Drive4ik** [comment]
This setting specifies which group the tab will be moved to if its url does not match a regular expression in the current group. When the browser opens, the addon does not change the group, but loads the last used group. If you change the group when the browser loads, it will lead to a slow start of the browser, as well as various errors with the layout of the tabs.
