### ISSUE TITLE
Option to cycle through non-empty tab groups only

### ISSUE THREAD

**Issue by forgedhallpass** [Drive4ik/simple-tab-groups#879]
I have multiple groups created, but I don't always have tabs in all of them, hence when using the CTRL+` shortcut to cycle through them I often need to press it multiple times until I get to where I want to be. It would be very useful to have an option to only cycle through tab groups that are not empty.

**Comment by Drive4ik** [comment]
Done. Please wait next release.

![изображение](https://user-images.githubusercontent.com/7843031/142643982-601c31ba-0c64-4441-8c9a-12a5b1e1d982.png)
![изображение](https://user-images.githubusercontent.com/7843031/142644070-808eea4c-7a39-4557-b0df-12c0fe1b8b24.png)

**Comment by forgedhallpass** [comment]
Thank you!
