### ISSUE TITLE
Use a timeout-based search trigger in the "Manage groups" view too

### ISSUE THREAD

**Issue by nekohayo** [Drive4ik/simple-tab-groups#882]
This is the same suggestion as #794, as it worked beautifully in the popup menu search, but it seems it was not implemented in the "Manage groups" tile view, as it is still sluggish.

I would recommend using this same type of approach (and delays) in that view too, to make it feel instantaneous as well.

**Comment by Drive4ik** [comment]
The page has a pending search
![aaaaaaaaaa](https://user-images.githubusercontent.com/7843031/142635235-5d59b073-3132-43c0-9c45-c0c6bd221d98.gif)

**Comment by nekohayo** [comment]
Strange, it felt so much slower/laggier than the popup's search, that I thought it didn't have any timeout-based search, because when you type the first 1-2 characters it lags a lot when you have many tabs. Does something special happen for the first few characters, or is the trigger timeout delay too short for the computational complexity involved in that page, or is it just that the page is too slow in general?
