### ISSUE TITLE
auto-stg-backup-day-of-month-13@drive4ik.json and losses of hourly backups

### ISSUE THREAD

**Issue by grahamperrin** [Drive4ik/simple-tab-groups#883]
### Description

Initially, I imagined a file naming bug. 

After more than an hour<strike> without an additional backup</strike>, <strike>I'm not sure what's wrong.</strike> 

After more than three hours, it seems that, maybe: 

* **the penultimate hourly backup is wrongly deleted**

– leaving only the most recent hourly backup. 

### Reproduction

1. With the previous version of Simple Tab Groups, have hourly backups
2. update to version 4.71
3. quit Firefox
4. start Firefox
5. observe the first backup of the thirteenth day of the month, literally `auto-stg-backup-day-of-month-13@drive4ik.json`
6. after more than hour,<strike> seek the subsequent backup</strike> review the list of backups
7. ~~nothing beyond~~ just one `auto-stg-backup-day-of-month-13@drive4ik.json`

### Expected

7. hourly backups

### Screenshots

2021-11-13 00:44, the initial backup by 4.71: 

![2021-11-13 01:16:09 day-of-month-13](https://user-images.githubusercontent.com/192271/141602199-377f98ec-c735-47a8-a6e2-288fad1a9583.png)

2021-11-13 02:19, ~~no subsequent backup~~ it seems that the 00:44 backup has disappeared: 

![image](https://user-images.githubusercontent.com/192271/141602278-c85ee9e1-91ac-4f06-9436-bd9476522cf1.png)

* at the foot of the Dolphin window: output from `ls -hlrt`

My preference for hourly backups (unchanged): 

![image](https://user-images.githubusercontent.com/192271/141602328-e22548b4-c2ec-4d97-906f-f2fac7ad57b4.png)

### Environment

```text
% pkg query '%o %v %R' firefox
www/firefox 94.0.1,2 FreeBSD
% freebsd-version -kru
14.0-CURRENT
14.0-CURRENT
14.0-CURRENT
% uname -aKU
FreeBSD mowa219-gjp4-8570p-freebsd 14.0-CURRENT FreeBSD 14.0-CURRENT #114 main-n250511-5f73b3338ee: Sat Nov  6 21:15:23 GMT 2021     root@mowa219-gjp4-8570p-freebsd:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG  amd64 1400040 1400040
% 
``` 
Simple Tab Groups 4.71.

### Additional context

https://github.com/Drive4ik/simple-tab-groups/commit/0caedab2682cbfebd86ef9ed41ec2af2525d6f14

https://github.com/Drive4ik/simple-tab-groups/issues/506#issuecomment-898339120

**Comment by grahamperrin** [comment]
Sorry for the strike-throughs in the opening post. 

It took a while for me to realise the disappearance of the initial backup.

**Comment by grahamperrin** [comment]
An 02:52 view of things: 

```text
% pwd
/usr/home/grahamperrin/Downloads/STG-backups-FF-94.0.1
% date ; uptime; ls -hlrt | tail -n 2
Sat 13 Nov 2021 02:52:31 GMT
 2:52a.m.  up 1 day, 22:18, 7 users, load averages: 5.28, 4.59, 3.07
-rw-r--r--  1 grahamperrin  grahamperrin   9.8M 12 Nov 15:48 auto-stg-backup-2021-11-12~15-48@drive4ik.json
-rw-r--r--  1 grahamperrin  grahamperrin   9.8M 13 Nov 02:45 auto-stg-backup-day-of-month-13@drive4ik.json
% 
```

* 02:45 is the ultimate backup
* the 01:44 (penultimate) backup is no longer listed.

**Comment by jtagcat** [comment]
Can replicate with a larger sample size:
...
auto-stg-backup-2021-11-11~22-01@drive4ik.json
auto-stg-backup-2021-11-11~23-01@drive4ik.json
auto-stg-backup-2021-11-12~00-01@drive4ik.json
auto-stg-backup-2021-11-12~01-02@drive4ik.json
auto-stg-backup-2021-11-12~02-06@drive4ik.json
auto-stg-backup-2021-11-12~03-06@drive4ik.json
auto-stg-backup-2021-11-12~04-06@drive4ik.json
auto-stg-backup-2021-11-12~05-06@drive4ik.json
auto-stg-backup-2021-11-12~16-53@drive4ik.json
auto-stg-backup-day-of-month-12@drive4ik.json
auto-stg-backup-day-of-month-13@drive4ik.json
auto-stg-backup-day-of-month-14@drive4ik.json
auto-stg-backup-day-of-month-15@drive4ik.json
auto-stg-backup-day-of-month-16@drive4ik.json
```

**Comment by jtagcat** [comment]
https://github.com/drive4ik/simple-tab-groups/commit/0caedab2682cbfebd86ef9ed41ec2af2525d6f14

**Comment by Drive4ik** [comment]
@grahamperrin disable this option and everything will be as before
![изображение](https://user-images.githubusercontent.com/7843031/142623923-0ace8f4f-2916-40d7-b4e3-fa5f1d184491.png)

**Comment by nekohayo** [comment]
I think the issue being reported here was that it uses the string "day-of-the-month" instead of the actual month number, or is that really what you intended, to have no more than one month's backups so that it essentially overwrites its own backups on a rolling basis?

I was similarly confused and didn't spontaneously imagine/realize this was a new rolling-overwrite feature due to the way that string is named (to the users it "looks" broken even if maybe it isn't). Maybe a string like "monthly-rolling-backup-no{number}" would be clearer (or perhaps @grahamperrin would have a better idea than me here)?

**Comment by Drive4ik** [comment]
@nekohayo 
> I think the issue being reported here was that it uses the string "day-of-the-month" instead of the actual month number, or is that really what you intended, to have no more than one month's backups so that it essentially overwrites its own backups on a rolling basis?

Absolutely right. The backups are overwritten after a month, because the numbers of the day of the month are repeated.

**Comment by grahamperrin** [comment]
Please reopen; not fixed. 

> disable this option and everything will be as before …

I did so (experimentally) before the suggestion was made, it has been disabled for a few days and still, **no hourly backups**: 

![image](https://user-images.githubusercontent.com/192271/143152802-dbf93354-4713-43af-bd44-9e930953bfa0.png)

The most recent succession of true hourly backups was on 12th November, the day before I opened this bug.

**Comment by nhoizey** [comment]
@Drive4ik I can confirm that I don't have hourly backups anymore.

Firefox on macOS Big Sur with STG 4.7.2.1

**Comment by Kelvino9** [comment]
This issue is definitely not yet fixed and should not be closed.

**Comment by grahamperrin** [comment]
https://github.com/Drive4ik/simple-tab-groups/issues/883#issuecomment-977351095

> Please reopen; not fixed.

Truly, it's not fixed. Before the bug bit, I had multiple backups per day. 

Now (bugged since November): no more than one per day. 

![image](https://user-images.githubusercontent.com/192271/148680207-3f6b2d22-959a-4b9c-bbb3-20761c40730b.png)

**Comment by ShingenPizza** [comment]
eh? the backups ARE hourly. if you set them to be hourly, of course.
the problem is only that because of their name lacking hour/minute now, and thus being the same throughout the entire day, they get overwritten by one another.
it was also reported in #901
