### ISSUE TITLE
Release notes for plug-ins

### ISSUE THREAD

**Issue by grahamperrin** [Drive4ik/simple-tab-groups#884]
A minor issue: some recent releases have no release note.

![image](https://user-images.githubusercontent.com/192271/141602739-9893c0c7-8dba-494c-921d-8a9aad322cdb.png)

https://addons.mozilla.org/addon/stg-plugin-create-new-group/versions/ | https://addons.mozilla.org/en-GB/firefox/addon/stg-plugin-create-new-group/versions/ | https://addons.mozilla.org/ru/firefox/addon/stg-plugin-create-new-group/versions/

https://addons.mozilla.org/en-GB/firefox/addon/stg-plugin-create-new-tab/versions/

https://addons.mozilla.org/en-GB/firefox/addon/stg-plugin-create-temp-tab/versions/

https://addons.mozilla.org/en-GB/firefox/addon/stg-plugin-del-current-group/versions/

https://addons.mozilla.org/en-GB/firefox/addon/stg-plugin-del-current-group/versions/

https://addons.mozilla.org/en-GB/firefox/addon/stg-plugin-manage-groups/versions/

I'm always curious about changes to extensions. 

https://addons.mozilla.org/en-GB/firefox/addon/stg-plugin-group-notes/versions/ includes notes :-)

**Comment by Drive4ik** [comment]
There's not a lot of change there, by and large. Updated translations, in particular added Japanese, raised the minimum version of FF, fixed bugs, if they were. I think, I optimized icons for browser theme a long time ago, only one option on about:config page should be turned on.
