### ISSUE TITLE
Option to open current tab group on startup

### ISSUE THREAD

**Issue by Hate9** [Drive4ik/simple-tab-groups#886]
**Is your feature request related to a problem? Please describe.**
I'm using Simple Tab Groups in the sidebar as my tab manager (I have the regular tab bar hidden). This is great, except when I start up my browser, the Simple Tab Groups sidebar opens to the main groups menu, as opposed to the menu for the specific group I'm currently using.

**Describe the solution you'd like**
I would love for there to be a setting to start the Simple Tab Groups sidebar menu with the current tab group open.

**Describe alternatives you've considered**
I may look into creating a UserChrome.js tweak to select the currently active group in the sidebar at startup. This would, however, be a massive hack and also kind of a pain.

**Comment by Drive4ik** [comment]
Please, enable this option in addon settings
![изображение](https://user-images.githubusercontent.com/7843031/142996368-2cecaf19-3dec-4cbf-a4eb-c5248ad3cec8.png)

**Comment by Hate9** [comment]
huh. don't know how I missed that.
