### ISSUE TITLE
Add a color picker to the group settings

### ISSUE THREAD

**Issue by klint** [Drive4ik/simple-tab-groups#89]
The title says it all :)
Thanks

**Comment by Philip-Sutton** [comment]
This is a good idea.

**Comment by Drive4ik** [comment]
I can do it only on Manage groups page, because when color picker was open - addon popup do close((
It will works only on page, not in popup.

**Comment by Philip-Sutton** [comment]
Operating the color picker via the 'Manage groups' page is OK I reckon.  How about also 
![color picker](https://user-images.githubusercontent.com/1549449/38085998-82110bd2-339e-11e8-9d7e-c32c26185e1f.png)
having a link via the pop-up.  See the mock up graphic below.

**Comment by Drive4ik** [comment]
done)
STG 3.0 and FF 61

**Comment by Philip-Sutton** [comment]
Thanks for adding this feature.  Greatly appreciated.
Philip
