### ISSUE TITLE
[Feature Request] Move several tabs at the same time from one group to another

### ISSUE THREAD

**Issue by Elaws** [Drive4ik/simple-tab-groups#895]
**Is your feature request related to a problem? Please describe.**

Currently, one need to move tabs one by one from one group to another.

**Describe the solution you'd like**
Move several tabs at the same time.

**Comment by hirnsushi** [comment]
You can hold *Shift* to select multiple tabs in a row or *Ctrl* to select multiple tabs individually.

**Comment by Elaws** [comment]
@hirnsushi Ups... I wished I tried better before asking -_-'. Anyway, thanks for your comment ;)
