### ISSUE TITLE
Sorting groups

### ISSUE THREAD

**Issue by jurgenhaas** [Drive4ik/simple-tab-groups#9]
Awesome, thanks a lot for this extension - it's already filling a gap that FF57 created.

How about being able to sort the groups in the pop-up list? Sorting them alphabetically should be there at least but other options might be helpful too:

- Sort by "Last used" groups in descending order
- Sort manually

**Comment by Drive4ik** [comment]
@jurgenhaas Hi, I planed this functional in future versions, now I'm focused on fixing bugs and improve stability.
Thanks for proposal!

**Comment by Drive4ik** [comment]
Done. Please, update addon to latest version
