### ISSUE TITLE
Close "Manage groups" tab after clicking a thumbnail in it

### ISSUE THREAD

**Issue by rubcap** [Drive4ik/simple-tab-groups#91]
Currently, when opening the "Manage groups" tab (conveniently using the keyboard shortcut) in group A and clicking a thumbnail in group B to switch to another tab, the "Manage groups" tab is left open in group A. 

After switching from group to group a few times via "Manage groups", many "Manage groups" tabs are left behind, spread over different groups, taking up space and most of the times with no use at all.

So I'd like to suggest that these "Manage groups" tabs are closed automatically when clicking a thumbnail to switch to another tab. Maybe as an option that is activated by default?

Thanks again for this wonderful add-on!

**Comment by Drive4ik** [comment]
Hi! You can disable option in addon settings "Open Manage Groups in new tab" and manage groups will open in new window, after select group this windows will close.

**Comment by rubcap** [comment]
Thank you for your response!

I tried disabling this setting. It works as you described. Still, opening a new window is a little slower than opening a new tab for "Manage Groups", so personally I prefer using tabs. 

Wouldn't it be more consistent if the tab were closed after selecting a group, just like the window? That would be the ideal solution for me. 

Just my 2 cents. Thank you!

**Comment by Drive4ik** [comment]
Please, update addon to latest version.

**Comment by rubcap** [comment]
Thank you very much! Works great. Now I'll promote your add-on even more to friends and colleagues :)
