### ISSUE TITLE
Creating a new group should be easier and more obvious.

### ISSUE THREAD

**Issue by julie777** [Drive4ik/simple-tab-groups#912]
**Is your feature request related to a problem? Please describe.**
Currently to create a new group I click the STG icon in the tab bar, then click create new group. However, the STG menu is a fixed size and with a large number of groups it requires scrolling to see the "create new group" and "show other tabs" choices. Manage and settings are always visible at the bottom of the list.

**Describe the solution you'd like**
Move the manage section to the top of the list and add a create button next to the settings button.

Also allow the dropdown to auto resize to show the entire list if there is screen space for it.

**Comment by Drive4ik** [comment]
Maybe you don't know about mini plugins for the STG addon?
https://addons.mozilla.org/ru/firefox/user/1017663/
https://addons.mozilla.org/ru/firefox/addon/stg-plugin-create-new-group/
Related to #920
