### ISSUE TITLE
STG context menu has delete group and discard group which is confusing

### ISSUE THREAD

**Issue by julie777** [Drive4ik/simple-tab-groups#918]
**Describe the bug**
When looking at the STG button context menu there are choices to: 
- discard group
- discard other groups
- delete group
How is discard group different than delete group?
Because of this I am not sure what discard group does. 
I can't imagine ever wanting to discard all the other groups. This looks dangerous. I would be very upset if I accidentally clicked on discard other groups and they all went away.

**To Reproduce**
1. click the STG icon on the tab bar
2. right click on a group to bring up the context menu
3. see that both delete group and discard group are present

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/5090005/151669403-007c16ad-5e65-4bb8-93d4-504acbd88cb0.png)

**Desktop (please complete the following information):**
 - OS and version: Windows 10
 - Firefox version: 96.0.3
 - Simple Tab Groups version: 4.7.2.1

**Additional context**

**Comment by vitusson** [comment]
So why don't you just try things out (backup function exists), before opening an issue on a non-problem?

Discard group does just unload the tabs of that group, as does "discard tab" does for single tab

**Comment by julie777** [comment]
Discard seems to delete the group. It doesn't work if the group chosen is the current group.

**Comment by vitusson** [comment]
Okay, that's just plainly wrong, You never did that, I do that ion a daily basis, and therefore I can call your claims just FUD

**Comment by julie777** [comment]
Well after much research and reading of API documentation for browser extensions I realize that discard means unload the tab contents but leave the tab. It wasn't obvious to me because in English discard most commonly means "throw away".
