### ISSUE TITLE
STG extension prevents hiding TABs when enabled

### ISSUE THREAD

**Issue by deekej** [Drive4ik/simple-tab-groups#921]
Hello! :)

**Describe the bug**
Few days ago, my Firefox started to show the backround for TABs, which was NOT previously happening for me.

To clarify, I'm using [Tree Style Tab](https://github.com/piroor/treestyletab) (installed as Firefox addon) and I userChrome.css customization to hide all the TABs from the top of Firefox. I'm also running on Fedora Linux with Gnome Shell / Wayland, and I'm using [GTK Title Bar](https://extensions.gnome.org/extension/1732/gtk-title-bar/) to hide the Title Bar completely (top bar where TABs are normally shown).

To make this work I'm using this particular `userChrome.css` configuration:
```
❯ cat .mozilla/firefox/<profile>/chrome/userChrome.css
/* Hide horizontal tabs at the top of the window */
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar > .toolbar-items {
  opacity: 0;
  pointer-events: none;
}

#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}

#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar .titlebar-spacer {
        border-inline-end: none;
}

#tabbrowser-tabs {
  visibility: collapse !important;
}

/* Remove close button*/
.titlebar-buttonbox-container{ display:none }

/* Center items in bookmarks toolbar */
#PlacesToolbarItems {
  display: flex !important;
  justify-content: center !important;
}
```

**To Reproduce**
1. Install both Tree Style Tab & Simple Tab Groups into Firefox as addons.
2. Enable both extensions.
3. Create `chrome` folder in your user profile: `.mozilla/firefox/<profile>/chrome/`
4. Create the `userChrome.css` file in that folder, with the contents mentioned above.
5. Enable loading of `userChrome.css` during Firefox's startup. Set the value below to `true` in `about:config`:
```
toolkit.legacyUserProfileCustomizations.stylesheets
```
6. Restart Firefox. You should now see Firefox without TABs, Close and other buttons at the top. (Hence the Tree Style Tab extension for you to be able to browse with Firefox once the TABs are hidden.)
7. Go to `Settings` -> `Extensions & Themes` and disable the STG extension. The empty tob bar should now be hidden.
8. Reenable the STG extension. The top bar is now visible and empty.

**Expected behavior**
The Firefox should look the same way as in the *DISABLED* screenshot below. (I.e. there should not be empty space between system toolbar and the adress bar.)

**Screenshots**
Here are the screenshots of how the top bar of Firefox loooks for me when the STG extension is enabled and disabled (you can see empty space between clocks and the address bar):
* [Enabled](https://i.imgur.com/VjlMR6D.png)
* [Disabled](https://i.imgur.com/P2pdp6f.png)

**Desktop (please complete the following information):**
 - OS and version: Fedora Linux 34 (Workstation) - with latest OS updates
 - Firefox version: `97.0b9` -- Firefox Developer Edition (official build by Mozilla)
 - Simple Tab Groups version: v4.7.2.1

**Additional context**
I want to reiterate that I've started to see this issue recently, previously it was working for me fine as seen in the *Disabled* screenshot. However, it's also possible that Mozilla changed something in Firefox since I'm de-facto using Firefox's Nightly builds with the Developer Edition. Any of your insight or guidance to resolve this would be most welcome! :)

**Comment by deekej** [comment]
So far, after further investigation, I was able to make things work again with simplyfying the `userChrome.css` contents, namely:
```
/* Hide the native TABs at the top: */
#TabsToolbar {
  visibility: collapse;
}

/* Center items in bookmarks toolbar */
#PlacesToolbarItems {
  display: flex !important;
  justify-content: center !important;
}
```

Most likely this isn't a bug of STG after all. I'll test-run these settings for a few days, and let you know. :)

**Comment by nkakouros** [comment]
So, did the new css rules fix it?

**Comment by deekej** [comment]
Hey, yes it did! :) Sorry for the noise. Maybe this will help someone if they Google for something like this.... :)
