### ISSUE TITLE
Spinning STG Wheel

### ISSUE THREAD

**Issue by RSCA77** [Drive4ik/simple-tab-groups#928]
**Describe the bug**
I have been using STG for 2 months.
A few weeks ago STG started being slow to load and now does not load.
No access to STG or Firefox Bookmark Toolbar. Sometimes the Bookmark Toolbar appears and you have normal access.
Originally the Spinning Wheel was intermittent and now is a permanent problem.

I have another laptop using STG without any issues.

I have uninstalled Firefox completely and then installed a new and only added STG.
This worked until I logged into the Firefox account and the sync started.
While the Spinning Wheel is active and there is no display of the account avatar.
It seems that I am logged in but I and able do the login process again.

There is and incomplete display of the "Recommendations" page under about:addons. Only the heading and no recommendations
There is and incomplete display of the "Extensions" page under about:addons. Only the heading and enabled or disabled extensions.
There is and incomplete display of the "Themes" page under about:addons. Only the heading and not themes.
The "Plugins" page under about:addons shows only "OpenH24" and Widevine" plugins. Any plugins previously installed are not displayed.

I have created a new profile and started by adding STG only.
No account login.
Did not add anything or change any settings nor any pages to STG.
All displaying OK without a Spinning Wheel.
Exit the new profile and start the new profile.
Spinning Wheel is back.

The only way out of this has been to use a Firefox Refresh and then disable STG.

**To Reproduce**
1. Created a new profile.
2. Added in STG.
3. Exited the new profile.
4. STG Spinning Wheel.

**Expected behavior**

**Screenshots**
Spinning Wheel:
![image](https://user-images.githubusercontent.com/98580127/154787299-c9fd2752-33a8-407e-96b2-28136a7e1479.png)
Plugins: Not loaded
![image](https://user-images.githubusercontent.com/98580127/154788134-bf3c7784-d64a-415e-8ffc-6553f7ac8403.png)
Themes: Incorrect display
![image](https://user-images.githubusercontent.com/98580127/154788151-213fce39-720c-471f-87f1-9f4d5153eb69.png)
Extensions: Incorrect Display
![image](https://user-images.githubusercontent.com/98580127/154788160-6d7bdee9-522d-4855-8569-8ae5e01c01f6.png)

**Desktop (please complete the following information):**
 - Windows 10 - Up to date
 - Firefox version: 64bit 97.0.1 up to date. ( I have tried a couple of earlier version without success)
 - Simple Tab Groups version: [4.7.2.1]

**Additional context**
I had the feeling that it was something to do with my existing bookmarks.
Then I thought it might have had something to do with the Firefox account login.
However, since creating a new profile and getting the same result I am thinking it may be something within Firefox.
I also think that after removing Firefox and deleting all the folders I could find before the reinstall that it could be a registry entry.

I have exhausted all the things that I think of to test.
In the mean time I have STG disabled.

**Comment by nekohayo** [comment]
Could it have anything to do with what's been discovered in issue #926 regarding monitor refresh rates?

**Comment by RSCA77** [comment]
👍 Thanks nekohayo
I did read about the work around in #926 but did not try it as I could not see how the refresh rate would make a difference.
But, it did.
Changed the setting from -1 to 60 restarted Firefox and enabled STG and it is now working fine with several Firefox restarts.
