### ISSUE TITLE
STG infinite spinning wheel if installed photon fix ui

### ISSUE THREAD

**Issue by fatalnyl** [Drive4ik/simple-tab-groups#931]
**Describe the bug**
On Firefox startup, STG shows infinite spinning wheel when clicked on the add-on grid icon. Happens if you installed Firefox UI Fix. 

**To Reproduce**
1. Open Firefox
2. Install Firefox UI Fix from https://github.com/black7375/Firefox-UI-Fix/
3. Don't follow step to about:support and clear startup cache
4. STG and some add-ons will break next time Firefox starts

**Expected behavior**
STG loads with groups without infinite loading.

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Firefox version: 97.0.1
 - Simple Tab Groups version: 4.7.2.1

**Additional context**
To fix the problem remember to clear startup cache after installing the new UI.

**Comment by nekohayo** [comment]
Could it have anything to do with what's been discovered in issue #926 regarding monitor refresh rates?

**Comment by fatalnyl** [comment]
Late reply. At first I thought that might be the case for me. Changing the refresh rate setting doesn't seem to fix my issue.
