### ISSUE TITLE
Local files don't restore after reset

### ISSUE THREAD

**Issue by Mipsters** [Drive4ik/simple-tab-groups#941]
**Describe the bug**
a local PDF open in a tab group wont restore after a browser reset

**To Reproduce**
1. open a local PDF in a tab group
2. restart firefox
3. load the tab group
4. there is a "new tab" tab where the local file was

**Expected behavior**
that the local file will reopen

**Screenshots**

Before reset:
![Before](https://user-images.githubusercontent.com/4920832/160095076-9490b853-adb3-4296-be1a-1238814e931a.png)

After:
![After](https://user-images.githubusercontent.com/4920832/160095096-5c772aa8-0062-4622-8d17-52aadd8485ee.png)

**Desktop (please complete the following information):**
 - OS and version: Windows 11
 - Firefox version: 98
 - Simple Tab Groups version: 4.7.2.1

**Additional context**
[STG-debug-logs.json](https://pastebin.com/kFGrFNG3)

**Comment by Drive4ik** [comment]
> For security reasons, in Firefox, this may not be a privileged URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/create#url
