### ISSUE TITLE
Feature request: A container per group

### ISSUE THREAD

**Issue by alkoforumm** [Drive4ik/simple-tab-groups#95]
As a feature it would be pretty good if you can set and and force all tabs in on group to use one container and the other groups their containers. I works manuely already I noticed, if one tab in group "X1" is openend in container "X1" all other tabs are automatic opened in that container "X1".
A nice addition to that would be if you can set per group one specif container so all tabs even the first one would always opened in that container.

..When you add this then the icons or colors of the group should sync with the colors from the containers or otherwise I will make it more confussing maybe.

I am coming mainly from Conex with works at the time better with hiding tabs (no closing) and the seperation in different "groups" using mozzila feature container, but without and overview/panorama window which I like in your addon very much.

Secure wise a could be only a bonus, quite dont know if there is any downside to this.

**Comment by Drive4ik** [comment]
Hi!
Maybe I will make this feature in future versions, after I finish work on "Hide tabs" feature

**Comment by Drive4ik** [comment]
@kimsey0 You choose to use tab containers or not.

@alkoforumm this functionality was partially implemented in STG 3.0 and FF 61
But auto change tab container where its open is very difficult now

**Comment by maverick74** [comment]
Hi @Drive4ik 

Probably i'm missing something, but i was hopping to find an option (Something like "Create a container to each group") to enable or disable this.

The way it is, it seems weird and i didn't understand exactly how this feature works.

I would like that each group i create would be in a container... (pretty much like Conex but without the slowness when dealing with many tabs >200...).

Can you bring some light into the subject, please? :)

**Comment by Drive4ik** [comment]
@maverick74 see https://github.com/Drive4ik/simple-tab-groups/issues/236#issuecomment-456838730

**Comment by Drive4ik** [comment]
Hi all! In latest version (v4.1) I added this option in group settings.
Please test.

**Comment by maverick74** [comment]
@Drive4ik 
Isn't there a way to set it to always treat each group as a container?

e.g.:, i create a new group and as soon as i do so, it creates a new container with the same name.
In other words: it would be creating containers (instead of groups), but with the capacity of current groups (hidding, move, etc).

Or did i miss something in the options?

**Comment by Drive4ik** [comment]
@maverick74 Unfortunately, I still can not do this because it will complicate the logic very much, and there may be conflicts with other add-ons.
Perhaps the functionality of this addon will suit you
https://addons.mozilla.org/firefox/addon/temporary-containers/
