### ISSUE TITLE
Automatic backups defaulting to the /tmp folder?

### ISSUE THREAD

**Issue by YainVieyra** [Drive4ik/simple-tab-groups#951]
In Linux, why the fuck are you defaulting to writing the backups in the /tmp folder? Don't you know that this folder is automatically deleted by the OS by default between restarts? There is no way to define a default folder for the automatic backups outside of the /tmp root through all of the preferences!
This doesn't provide any protection in the case that a bad power outage occurs, killing all the tabs in the browser and also the backup files. These backups should be in a different location, where they can be resilient to restarts!
Also, you should allow the user to CHOOSE where it wants to write the backups by default, without any further action after that. This means that expecting the user to save its own backups manually because of this limitation is out of the question and wouldn't be a proper solution.

Seriously, fix this design problem immediately!

**Desktop (please complete the following information):**
 - OS and version: GNU/Linux Xubuntu 20.04.1 LTS
 - Firefox version: 100
 - Simple Tab Groups version: 4.7.2.1

**Comment by biggianteye** [comment]
You might find this useful: https://github.com/Drive4ik/simple-tab-groups/issues/285
