### ISSUE TITLE
Last auto backup is-to-have-will-been-occurred 8 years in the future!

### ISSUE THREAD

**Issue by sbirl** [Drive4ik/simple-tab-groups#969]
## Describe the bug
I have STG do an auto-backup every hour.  I didnt pay much attention to the backups after a while ... until today.
Last backup recorded: **2030**-April-02 5:19am.
(Last backup before that 2022-April-01 11:18pm.)

It's pretty apparent that my system clock jumped 8 years into the future, as some other Firefox files also have that timestamp.
(Sadly I was given no glimpse of this future, only that it occurred.)

I did a manual backup today, un-installed the extension, re-install the extension, restored backup -- timestamp persists.
Looked at the contents of the backup JSON file, but found no immediate 2030 recorded in there, so Im not sure where that's stored.

## Screenshots
![image](https://user-images.githubusercontent.com/33668651/183110274-8c63ef14-20cc-4f47-8ca4-c67620746768.png)

## Versions:
* Win10
* FF 103
* STG 4.7.2.1

## Additional context:
Happened 4 months ago, but just noticed today.

It's an easy fix, I just need to know where to go to fix it; in some flat file, where I could just edit the file and restart the browser?  Or maybe it's in a SQLite db file?

**Comment by sbirl** [comment]
@drive4ik This bug's been out here for a year, and I have about 7 more years to wait for my next backup.  Thoughts?

**Comment by vitusson** [comment]
It's all in the json: 
`"autoBackupLastBackupTimeStamp": 1691068292,`

which is  epoch time, so no 2030 to find, of course
https://unixtime.org/

**Comment by sbirl** [comment]
Thanks @vitusson.  Im all fixed up.  _Cant believe I overlooked that timestamp entry last year_

**Comment by SpaceClicker** [comment]
> Thanks @vitusson. Im all fixed up. _Cant believe I overlooked that timestamp entry last year_

All fixed up at least until 03:14:07 on  January 19, 2038 😁
