### ISSUE TITLE
Multi Device

### ISSUE THREAD

**Issue by ItMeCorban** [Drive4ik/simple-tab-groups#978]
I must be missing something here. How am I supposed to access my groups on other devices? The bookmarks import creates duplicates everytime and it doesn't seem to sync automatically. Seems like an oversight as I can't be the only one using my browser on multiple devices. I group tabs to go back and look at later but that's useless if they're not there

**Comment by bonnepioche** [comment]
Hi,
I am wondering the same. Any thoughts any one?
Thanks
Pat

**Comment by Drive4ik** [comment]
Duplicate of #291
