### ISSUE TITLE
All tabs moved to unsorted from groups after closing FIrefox.

### ISSUE THREAD

**Issue by Toskin** [Drive4ik/simple-tab-groups#979]
**Describe the bug**
After closing Firefox and opening it next day, every single tab is moved from their tab groups into unsorted.

**To Reproduce**
1. Close Firefox
2. Restart PC
3. Start Firefox

**Expected behavior**
When starting Firefox, I expected tabs still being in groups they were assigned to.

**Screenshots**

**Desktop (please complete the following information):**
 - OS and version: Windows 10 Home 21H2
 - Firefox version: 105.0.2 64bit
 - Simple Tab Groups version: 4.7.2.1

**Additional context**
Needed permissions were given, I had to activate OneTab twice to transfer my tabs from Chrome but extension was deactivated right after that. I also have Tab Session Manager installed.

**Comment by Drive4ik** [comment]
Fixed in v4.8 (under review)
