### ISSUE TITLE
Compatability with Select After Closing Current

### ISSUE THREAD

**Issue by iG8R** [Drive4ik/simple-tab-groups#981]
Hi.

**Is your feature request related to a problem? Please describe.**
[Select After Closing Current](https://addons.mozilla.org/en-US/firefox/addon/select-after-closing-current/) is on with a function to focus on the tab on the left after closing current active tab.
Closing an active tab which is the first tab in a group results in switching to another group as "Select After Closing Current" doesn't consider whether "left tab" in the overall list of tabs belongs to the current group or not just focusing on that "left tab" despite it belongs to a completely different group which in turn leads to switching to another group.

**Describe the solution you'd like**
Is it possible to make "Simple Tab Groups" to be compatible with "Select After Closing Current" or any other add-on with similar functionality in such a way that every group would be treated as a separate set of tabs so that switching to other groups does not occur in this way and all operations with tabs occurred within the group, or implement similar functionality in "Simple Tab Groups" itself?

Thank you.

**Comment by JoshCode94** [comment]
I use both these addons and the option that works for me (to fix the issue you describe) is in the Options tab of the "Select after closing current" addon.
Change it so that it looks like [this](https://imgur.com/a/YBitN77). I had a similar problem where it would open a tab that's in a different group. This fixed it (if I remember right).

**Comment by iG8R** [comment]
@JoshCode94 
At last! Thank you very much! You saved me:)
As it turned out all that needed to be done - check "Skip hidden".

PS. These options for me work more correct:
<details><summary>Screenshot</summary>

![Firefox-closing-tabs-2022-12-04_014903](https://user-images.githubusercontent.com/11407417/205467236-33d236ac-e911-4730-85e3-2f4c8dc9a9f3.jpg)

</details>
