### ISSUE TITLE
Bug in input environment using IME (Input Method Editor).

### ISSUE THREAD

**Issue by n2naokun** [Drive4ik/simple-tab-groups#996]
Translated from Japanese to English using DeepL.com.

English (translated)
In an input environment that uses an Input Method Editor (IME) such as Japanese,
if you use the tab search function while the second or later tab group is open,
the search will be performed with an empty word because the search is performed
with the Enter key input to confirm the conversion.

Japanese (original)
日本語などのIME(Input Method Editor)を使用している入力環境で、
2つ目以降のタブグループを開いている状態でタブの検索機能を使用すると、
変換を確定するためのEnterキー入力で検索されるため、
空のワードで検索が行われる不具合があります。

**Comment by Drive4ik** [comment]
I don't quite understand the problem. Can you record a gif or video of it replicate?

**Comment by n2naokun** [comment]
Translated from Japanese to English using DeepL.com.

English (translated)
Somewhere along the line, the problem of searching for empty words disappeared.
However, when the IME text input is confirmed, the first in the list of tabs containing that word is opened.


If you type in English input mode (IME OFF)
The list of tabs that contain the word you entered will be displayed because you don't have to press Enter to confirm.
https://drive.google.com/file/d/1-YD3NM9N0yH22CAsscnRnXQe5H5524U8/view


If you type in Japanese input mode (IME ON)
When you type a word and press the Enter key to confirm it in the IME, Simple Tab Groups also receives the Enter key input, and the list of tabs containing the word you typed is displayed for a moment, then the first tab in the list is opened.
https://drive.google.com/file/d/1KdXpD1cxR9kAx3Js0f1ZGhOBaEhCoa33/view

https://drive.google.com/file/d/1oClqOn8paXff_TNhFoGubPZhsV6GAwL_/view

If you confirm your input with the right cursor key instead of using the Enter key, the list of tabs will be displayed as in English input.
https://drive.google.com/file/d/1196odjLZf95o43WAjYsGEpG4BCeEsNLf/view


Reference video
Video of Japanese input using the IME
In Japanese input, after a character is converted, the conversion is confirmed with the Enter key.
https://drive.google.com/file/d/1d5sI93LnQ456en1t6IK_DgmpAG4p_6Eb/view




Japanese (original)
いつの間にか空のワードで検索される不具合は無くなっていました。
しかし、IMEの文字入力を確定させるとそのワードが含まれるタブのリストの1番目が開かれてしまいます。


英語入力モード(IME OFF)でを入力した場合
・Enterキーで確定する必要が無いので、入力したワードが含まれるタブのリストが表示されます。
https://drive.google.com/file/d/1-YD3NM9N0yH22CAsscnRnXQe5H5524U8/view


日本語入力モード(IME ON)で入力した場合
・ワードを入力してIMEに対してEnterキーで確定を行うと、Simple Tab GroupsもEnterキー入力を受け取ってしまい入力したワードが含まれるタブのリストが一瞬表示された後にリストの1番目のタブが開かれます。
https://drive.google.com/file/d/1KdXpD1cxR9kAx3Js0f1ZGhOBaEhCoa33/view

https://drive.google.com/file/d/1oClqOn8paXff_TNhFoGubPZhsV6GAwL_/view

・Enterキーを使用せずに右カーソルキーで入力を確定すると英語入力と同じようにタブのリストが表示されます。
https://drive.google.com/file/d/1196odjLZf95o43WAjYsGEpG4BCeEsNLf/view


参考映像
IMEを使用した日本語入力の映像
日本語入力は文字を変換した後Enterキーでその変換を確定します。
https://drive.google.com/file/d/1d5sI93LnQ456en1t6IK_DgmpAG4p_6Eb/view

**Comment by Drive4ik** [comment]
I understand the problem. Can you please go to 
https://javascript.info/keyboard-events#keyboard-test-stand 
and enter some text there using IME-on, and copy or take a screenshot/video of what the console wrote?

**Comment by n2naokun** [comment]
input
nihongo nyuuryoku tesuto .

input Result (Video)
https://drive.google.com/file/d/1lqwOTxIHsQqS5j-1fWxUjfYtgmnPGCNl/view


The last two shortcut keys, Alt and F9, are for stopping the recording.
input Result (text)
keydown key=Process code=KeyN
keyup key=n code=KeyN
keydown key=Process code=KeyI
keyup key=i code=KeyI
keydown key=Process code=KeyH
keyup key=h code=KeyH
keydown key=Process code=KeyO
keyup key=o code=KeyO
--------------------------------------------------------------------------------
keydown key=Process code=KeyN
keyup key=n code=KeyN
keydown key=Process code=KeyN
keyup key=n code=KeyN
keydown key=Process code=KeyG
keyup key=g code=KeyG
keydown key=Process code=KeyO
keydown key=Process code=Space
keyup key=o code=KeyO
keyup key=  code=Space
keydown key=Process code=Enter
keyup key=Enter code=Enter
--------------------------------------------------------------------------------
keydown key=Process code=KeyN
keyup key=n code=KeyN
keydown key=Process code=KeyY
keyup key=y code=KeyY
keydown key=Process code=KeyU
keyup key=u code=KeyU
keydown key=Process code=KeyU
keyup key=u code=KeyU
keydown key=Process code=KeyR
keydown key=Process code=KeyY
keyup key=r code=KeyR
keyup key=y code=KeyY
keydown key=Process code=KeyO
keyup key=o code=KeyO
keydown key=Process code=KeyK
keyup key=k code=KeyK
keydown key=Process code=KeyU
keydown key=Process code=Space
keyup key=u code=KeyU
keyup key=  code=Space
keydown key=Process code=Enter
keyup key=Enter code=Enter
--------------------------------------------------------------------------------
keydown key=Process code=KeyT
keydown key=Process code=KeyE
keyup key=t code=KeyT
keyup key=e code=KeyE
keydown key=Process code=KeyS
keyup key=s code=KeyS
keydown key=Process code=KeyU
keyup key=u code=KeyU
keydown key=Process code=KeyT
keyup key=t code=KeyT
keydown key=Process code=KeyO
keyup key=o code=KeyO
keydown key=Process code=Space
keyup key=  code=Space
keydown key=Process code=Enter
keyup key=Enter code=Enter
--------------------------------------------------------------------------------
keydown key=Process code=Period
keyup key=. code=Period
--------------------------------------------------------------------------------
keydown key=Process code=Enter
keyup key=Enter code=Enter
--------------------------------------------------------------------------------
keydown key=Alt code=AltLeft altKey
--------------------------------------------------------------------------------
keydown key=Alt code=AltLeft altKey (repeat)
keydown key=Alt code=AltLeft altKey (repeat)
keydown key=Alt code=AltLeft altKey (repeat)
keydown key=Alt code=AltLeft altKey (repeat)
keyup key=F9 code=F9 altKey
keyup key=Alt code=AltLeft

**Comment by Drive4ik** [comment]
Will be available in future versions. Probably through one version, because version 4.8 has not yet been tested in FF.

**Comment by n2naokun** [comment]
Translated from Japanese to English using DeepL.com.

English (translated)
Thank you very much for the correction.
Looking forward to the new version.

Japanese (original)
修正していただき、ありがとうございます。
新しいバージョンを楽しみにしています。
