### ISSUE TITLE
Using Emoji with multiple Unicode points in a tab group name leads to `malformed URI sequence` error

### ISSUE THREAD

**Issue by jpkempf** [Drive4ik/simple-tab-groups#997]
**Describe the bug**
Using certain emoji in the name of a group leads to unpredictable behaviour, such as not being able to save changes to the group or the list of all groups appearing to be empty.

**To Reproduce**
Steps to reproduce the behavior (I recommend using a separate instance of Firefox and the plugin for this)
1. Create a new group
2. Use the `teacher` 👨‍🏫 emoji as part of the group name
3. Attempt to save the group

I tried various iterations of this, such as using the macOS emoji picker, the Rocket emoji picker and copy-pasting in the emoji from the clipboard. It should be noted that lots of other emoji work just fine; this is the first one that I've encountered which seems to be an issue. Perhaps because it is a combination of multiple (three) unicode characters?

**Update**: Other emoji seem to have the same effect, such as `student` 🧑‍🎓. I am now wary of using any emoji in group names. The following emoji are _not_ causing the problem:

 * 💻 `computer`
 * 👷‍♂️`worker`
 * 🔎 `mag-right`
 * 📖 `book`

All of these use a single unicode point, while `student` is another example of multiple unicode points. To me this looks like it seems to be the cause of the issue.

**Expected behavior**
The group is created as usual and behaves normally.

**Actual behaviour**
The Simple Tabs Extension will start acting erratically and eventually all groups will be hidden or lost.

**Desktop (please complete the following information):**
 - macOS Monterey 12.6.1
 - Firefox Developer Edition 109.0b3
 - Simple Tab Groups version: 4.7.2.1

**Additional context**

I'm attaching a zipped JSON log file; below is a small excerpt of said file that I believe shows the relevant error.

[STG-debug-logs.json.zip](https://github.com/Drive4ik/simple-tab-groups/files/10258132/STG-debug-logs.json.zip)

```
{
    "time": "2022-12-19T09:35:53.836Z",
    "fileName": "moz-extension://6947c680-d949-427f-89af-3cbd620ebb32/js/utils.js",
    "lineNumber": 619,
    "columnNumber": 40,
    "message": "malformed URI sequence",
    "stack": [
        "getGroupIconUrl -> js/utils.js:606:22",
        "iconUrlToDisplay -> manage/manage.js:14799:38",
        "get -> manage/manage.js:4165:25",
        "evaluate -> manage/manage.js:4267:21",
        "computedGetter -> manage/manage.js:4465:17",
        "render/< -> manage/manage.js:8407:44",
        "renderList -> manage/manage.js:2446:16",
        "render -> manage/manage.js:8340:23",
        "renderMixin/Vue.prototype._render -> manage/manage.js:3326:22",
        "updateComponent -> manage/manage.js:3778:21",
        "get -> manage/manage.js:4165:25",
        "run -> manage/manage.js:4240:22",
        "flushSchedulerQueue -> manage/manage.js:4017:13",
        "nextTick/< -> manage/manage.js:1918:12",
        "flushCallbacks -> manage/manage.js:1844:14"
    ]
}
```

I'm going to attempt updating my browser and loading a backup of my tab groups from last week to see if that reverts the broken state I am currently in. Will update the ticket afterwards.

**Update**: I was able to restore all my tabs and settings by manually editing my most recent backup file to remove the teacher emoji from the group name and then using that file to restore.

So the bug should be reproducible by attempting to restore from a broken backup file. I'm attaching a minimal backup file here that contains a group with the teacher emoji in the name. (rename from `.txt` to `.json` to use)

[997-broken-backup-file.txt](https://github.com/Drive4ik/simple-tab-groups/files/10258235/997-broken-backup-file.txt)

**Comment by Drive4ik** [comment]
Fixed it. I also made the first emoji not to duplicate the name of the group.
![изображение](https://user-images.githubusercontent.com/7843031/222941887-7c14bf18-696b-4cfc-896d-df686062153a.png)
![изображение](https://user-images.githubusercontent.com/7843031/222941894-8b20b528-bb96-4a43-933c-6246341bc8aa.png)

**Comment by jpkempf** [comment]
Wonderful news! Thank you so much 😊
